### ISSUE TITLE
P2102R0: Make "implicit expression variations" more explicit (Wording for US185)

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#100042]
**Link:** https://wg21.link/p2102r0

This was implemented from the beginning.

**Comment by frederick-vs-ja** [comment]
This paper doesn't seem strictly "Nothing to do" to me. It enforced some expression variants in `copyable` and `indirectly_copyable_storable` to be checked - so that there're some substitution failures or hard errors that would cause IFNDR-ness without this paper.

I think it should be considered completed in 15.0, after implemeting both `copyable` (in LLVM 13, 8ef69c66d5aab9ca2f04e0aecf109a2d2f7bb4b9, https://reviews.llvm.org/D97443) and `indirectly_copyable_storable` (in LLVM 15, e65d3760a31ba7e84e0f3b46cde2c9169e00cd19, https://reviews.llvm.org/D118432).
