### ISSUE TITLE
[clang-format] nested ternary misformatted in version 19

### ISSUE THREAD

**Issue by rmarker** [llvm/llvm-project#100300]
While trying out clang-format on the new 19.x branch, I discovered an issue with the formatting with a nested ternary.
I came up with the following minimal reproducer.

In clang-format 18.1.7 with the default LLVM style:
`bool foo(int A, int B) { return A < B ? true : A > B ? false : false; }`

In clang-format 19.1.0 (183e8ec)
`bool foo(int A, int B) { return A<B ? true : A> B ? false : false; }`

**Comment by owenca** [comment]
Bisected to 834ac2e205dd8e492d6084a7952e68e19a1f54db. @rymiel

**Comment by rymiel** [comment]
Not limited to nested ternaries, this is sufficient:
```cpp
bool foo(int A, int B) { return A < B ? true : A > B; }
// becomes
bool foo(int A, int B) { return A<B ? true : A> B; }
```

It also doesn't need ternaries at all, something like this has existed since at least 10 versions ago:
```cpp
bool foo(int A, int B) { return A < B ^ A > B; }
// becomes
bool foo(int A, int B) { return A<B ^ A> B; }
```

I'm not sure if I know how to fix this, but I will try, though I sympathize with this comment:
https://github.com/llvm/llvm-project/blob/ccae7b461be339e717d02f99ac857cf0bc7d17fc/clang/lib/Format/TokenAnnotator.cpp#L238

**Comment by owenca** [comment]
@rymiel please unassign me if you already started on it. I just want to get the fix in before the first point release of 19.
