### ISSUE TITLE
LWG3317: Incorrect `operator<<` for floating-point durations

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#100429]
**Link:** https://wg21.link/lwg3317

**Comment by deniskilseev** [comment]
I'd like to work on this.

**Comment by deniskilseev** [comment]
@ldionne Is this as well as a bunch of other LWG issues in 'potentially good for outreach' still needs to be done or..?

**Comment by ldionne** [comment]
This is still open, so it remains to be done indeed!

Note that I am a bit ambivalent about the "potentially good for outreach" tag because it can be misleading. For example, this LWG issue seems simple but sometimes we've had surprises where apparently simple LWG issues ended up requiring a lot of thought. So TLDR I'd say if you want to tackle an issue, go for it and that's the best way to find out whether the issue is easy to work on or not :-)

**Comment by deniskilseev** [comment]
I believe this has been done.

https://github.com/llvm/llvm-project/commit/719c3dc6f2f7c7dd01b190496acd8ddecacabe01#diff-dcf2cfef8f872860b4d26037bfc5faa8bf2d09d51f2ee4890a52e903098919e3R88-R98

Most likely other chrono issues from "potentially good for outreach" were implemented at some point as well 😅

**Comment by frederick-vs-ja** [comment]
> I believe this has been done.
> 
> [719c3dc#diff-dcf2cfef8f872860b4d26037bfc5faa8bf2d09d51f2ee4890a52e903098919e3R88-R98](https://github.com/llvm/llvm-project/commit/719c3dc6f2f7c7dd01b190496acd8ddecacabe01#diff-dcf2cfef8f872860b4d26037bfc5faa8bf2d09d51f2ee4890a52e903098919e3R88-R98)
> 
> Most likely other chrono issues from "potentially good for outreach" were implemented at some point as well 😅

Agreed. I think we can just add `|Complete|` & `16.0` here.
https://github.com/llvm/llvm-project/blob/dbad963a69fd7b16c6838f81b61167fbf00a413c/libcxx/docs/Status/Cxx20Issues.csv#L242

**Comment by ldionne** [comment]
Sorry, I stand corrected!
