### ISSUE TITLE
[WebAssembly] A relocation to get the offset of a section in the final binary

### ISSUE THREAD

**Issue by SingleAccretion** [llvm/llvm-project#100734]
I am constructing a parser that would be able to map file offsets of functions from stack traces to entries in a custom data structure.

I can get the section relative offset of a function via `R_WASM_FUNCTION_OFFSET_I32`, but it appears there is no way to get the offset a WASM section (in this case, `Code`), which is needed to compute the final file offset.

**Comment by dschuff** [comment]
I think `R_WASM_SECTION_OFFSET_I32` is meant to get the offset of a symbol from the start of its containing section, not a file offset. It's analogous to `R_WASM_FUNCTION_OFFSET_I32` for functions or `R_WASM_MEMORY_ADDR_I32` for data, but for custom sections. I would actually expect that if you used `R_WASM_SECTION_OFFSET_I32` on a section symbol that it would give you 0 or otherwise not work, but I'm not actually sure?

So maybe this is more a feature request to implement a way to get the file offset of sections. I can definitely see how that would be useful. It could potentially be done by allowing `R_WASM_SECTION_OFFSET_I32` to be used against section symbols (it would sort of be a different interpretation than for symbols inside sections, but I can kind of see it). What I'm not sure about is how hard it would be to implement in the linker. All of the known sections other than code and data (i.e. type, import, export, etc) are generated by the linker, and I'm not sure whether that generation happens before or after the relocation values are calculated. Maybe @sbc100  knows?

**Comment by sbc100** [comment]
Is it not possible to simply parse the binary file to find the code section offset?

Encoding the absolute offset one section within another section seems especially fragile since almost any change the binary would render these invalid.

**Comment by sbc100** [comment]
> > Is it not possible to simply parse the binary file to find the code section offset?
> 
> It is certainly possible. It is also an overhead (both code size and runtime) that can be avoided.

Given that you already have the file bytes (otherwise the offset is not useful) I would recommend that route over trying to add a new relocation type.   If the resulting code particularly egregious we can perhaps revisit?

> 
> > Encoding the absolute offset one section within another section seems especially fragile since almost any change the binary would render these invalid.
> 
> The use case for such a relocation would already be incompatible with any interesting post-link modifications, since they invalidate function offsets.

Not all Wasm file modifications need to change the code section.  Only code section modifications invalidate R_WASM_SECTION_OFFSET_I32 relocations, whereas the relocation type you are proposing is even more fragile.     For example, imagine a adding a new custom section right at the beginning on a file.

**Comment by SingleAccretion** [comment]
> Given that you already have the file bytes (otherwise the offset is not useful) I would recommend that route over trying to add a new relocation type.

Yes, that is what I will be doing. I agree adding a new relocation just for this one use case seems premature.

I'll toss in one more point, though: let's imagine we need to do what I am doing, but we don't have access to host code (WASI-like situation), with just a "get me a list of IPs" in-WASM API. In that situation, a mechanism like this would be the only way (short of custom post-link tools). However, perhaps that just points to the fact that file offsets are a poor abstraction for the aforementioned API.
