### ISSUE TITLE
[Clang][Module] Miss definition of inline function in implementation partition units

### ISSUE THREAD

**Issue by 24bit-xjkp** [llvm/llvm-project#101348]
## Information

clang version 20.0.0git (https://github.com/llvm/llvm-project.git 73c72f2c6505d5bc8b47bb0420f6cba5b24270fe)
Target: x86_64-unknown-windows-gnu
Thread model: posix
InstalledDir: D:/Tools/clang/bin
OS: Windows11 24H2

Here is my code:

```c++
// a.cpp
import B;
int main()
{
    g<void>();
}
// b.cppm
export module B;
import :C;
export template <typename T> inline void g() noexcept
{
    return f<T>();
}
// c.cppm
module B:C;
template<typename> inline void f() noexcept {}
```

I can compile these code with gcc and msvc, but when I compile with clang:

```shell
mkdir build
clang++ -std=c++26 c.cppm --precompile -o build/c.pcm
clang++ -std=c++26 b.cppm "-fmodule-file=B:C=build/c.pcm" --precompile -o build/b.pcm
clang++ -std=c++26 a.cpp "-fmodule-file=B=build/b.pcm" "-fmodule-file=B:C=build/c.pcm"
```

Then I receive errors below:

```log
In module 'B' imported from a.cpp:1:
C:/Users/2283/Desktop/test/c.cppm:4:13: warning: inline function 'f<void>' is not defined [-Wundefined-inline]
    4 | inline void f() noexcept
      |             ^
C:/Users/2283/Desktop/test/b.cppm:7:12: note: used here
    7 |     return f<T>();
      |            ^
1 warning generated.
ld.lld: error: undefined symbol: void f@B<void>()
>>> referenced by C:/Users/2283/AppData/Local/Temp/a-7d0622.o:(void g@B<void>())
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Clang doesn't generate code correctly for the inline function `f<void>` therefore lld can't find the symbol `f@B<void>()` while linking objects.

**Comment by ChuanqiXu9** [comment]
BTW, the last command you give should be `clang++ -std=c++26 a.cpp "-fmodule-file=B=build/b.pcm" "-fmodule-file=B:C=build/c.pcm" build/c.pcm build/b.pcm -o build/a.out`. But it doesn't matter. The error is still there.

For the issue itself, the compiler's behavior may be good. According to [[module.reach]](http://eel.is/c++draft/module.reach):

> A translation unit U is [necessarily reachable](http://eel.is/c++draft/module#def:reachable,necessarily,translation_unit) from a point P if U is a module interface unit on which the translation unit containing P has an interface dependency, or the translation unit containing P imports U, in either case prior to P

> All translation units that are necessarily reachable are [reachable](http://eel.is/c++draft/module#def:reachable,translation_unit)[.](http://eel.is/c++draft/module#reach-2.sentence-1) Additional translation units on which the point within the program has an interface dependency may be considered reachable, but it is unspecified which are and under what circumstances[.](http://eel.is/c++draft/module#reach-2.sentence-2)

Here the module unit `c.cppm` is not necessarily reachable to `a.cpp` since:
(1) `c.cppm` is an implementation partition unit. And,
(2) `a.cpp` doesn't import `c.cppm`.

So whether or not `c.cppm` is reachable to `a.cpp` or not is unspecified. And clang's decision is, only the necessary reachable TU are reachable. So the compiler's behavior is not bad at least.

---

My personal suggestion for implementation partition unit is, envision them like the headers which can only be included by sources. In another word, only import the implementation partition unit in the implementation unit (note that implementation unit is different from implementation partition unit). Otherwise, users need to understand what they are doing.
