### ISSUE TITLE
Clang rejects valid program involving explicitly default move ctor with const T&& parameter

### ISSUE THREAD

**Issue by ranaanoop** [llvm/llvm-project#101441]
The following [valid](https://stackoverflow.com/a/78817438/12002570) program is rejected by clang, gcc and msvc. Only edg correctly accepts this. [Demo](https://godbolt.org/z/c9Wf8hh16). 

```
struct C
{
   C(const C&&) = default; // EDG: ok, gcc: No, Clang: No
};
int main()
{
    
}
```
As explained in the [thread](https://stackoverflow.com/a/78817438/12002570), `F1` will be deleted here as per [dcl.fct.def.default#2.6](https://eel.is/c++draft/dcl.fct.def.default#2.6). Note also there that [constructors now do  have  a type](https://stackoverflow.com/questions/71724811/does-a-constructor-has-a-type-in-c-since-it-is-a-special-member-function/78818721#78818721) through CWG2479.

**Comment by shafik** [comment]
I don't think those two core issues are it, I am having a hard time nailing down all the wording changes in `dcl.fct.def.default`, it is not clear to me that was intended.

CC @cor3ntin @zygoloid

**Comment by MitalAshok** [comment]
Clang does accept this, it just warns about it being deleted (which it is). It compiles without warning if you have `-Wno-defaulted-function-deleted`.

This was changed with [CWG1331](https://cplusplus.github.io/CWG/issues/1331.html)/[CWG1426](https://cplusplus.github.io/CWG/issues/1426.html), by [P0641R2](https://wg21.link/P0641R2) which made `C(const C&&) = default`; deleted instead of ill-formed.

**Comment by zygoloid** [comment]
Clang rejects under `-std=c++17` and earlier, and accepts under `-std=c++20` and later, which appears to be correct, given P0641R2 was not applied as a defect report resolution. I think there's no bug here.

**Comment by shafik** [comment]
Worth noting implementation compliance is 50/50 here: https://godbolt.org/z/n5jGKc888
