### ISSUE TITLE
[libc++] error: call to constructor of 'std::complex<float>' is ambiguous

### ISSUE THREAD

**Issue by amilendra** [llvm/llvm-project#101960]
```c++
#include <complex>

typedef std::complex<float> Fcx;

struct S {
    S() {}
    S(const S&) {}
    template <class T> operator T() { return 0; }
} s;

int main(void)
{
    std::complex<float> *p00 = new std::complex<float>(s, s);
}
```

This program is accepted by libstdc++ but rejected by libc++
```
<source>:13:36: error: call to constructor of 'std::complex<float>' is ambiguous
   13 |     std::complex<float> *p00 = new std::complex<float>(s, s);
      |                                    ^                   ~~~~
/opt/compiler-explorer/clang-trunk-20240805/bin/../include/c++/v1/complex:422:43: note: candidate constructor
  422 |   _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR complex(float __re = 0.0f, float __im = 0.0f) : __re_(__re), __im_(__im) {}
      |                                           ^
/opt/compiler-explorer/clang-trunk-20240805/bin/../include/c++/v1/complex:424:43: note: candidate constructor
  424 |   _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR complex(__from_builtin_tag, _Complex float __v)
      |                                           ^
1 error generated.
Compiler returned: 1
```

https://godbolt.org/z/6Ph1W7bq5
We found this from a downstream C++ library comparison test.

I think this is due to merge https://github.com/llvm/llvm-project/pull/83575
Would someone please have a look?

**Comment by MitalAshok** [comment]
Current libc++ behaviour seems to go against [[member.functions]p2](https://eel.is/c++draft/member.functions#2)

> For a non-virtual member function described in the C++ standard library, an implementation may declare a different set of member function signatures, provided that any call to the member function that would select an overload from the set of declarations described in this document behaves as if that overload were selected.

---

Similar problem with `std::optional`'s tagged constructor (https://github.com/llvm/llvm-project/blob/dc95aa209b9a64ed4cce9c47ed53a26376cca0be/libcxx/include/optional#L303-L306): https://godbolt.org/z/q1jjnWa6G

```c++
#include <optional>

struct X {
    template <class T> operator T();
};

int main() {
    std::optional<int> x(X{}, 0);  // Intended: `X{}.operator std::in_place_t()`
}
```

---

For `std::optional`, this can be avoided by not inheriting this constructor. That's not really an option for `std::complex` since the layout is important.

For `std::complex` there could be a static function `static complex __from_builtin(_Complex T __v) { return complex(__real__ __v, __imag__ __v); }` instead of a tagged constructor.

Something that could be done with all tagged constructors is instead of:

```c++
class_name(__tag_type, ...);
```

Have:

```c++
template<typename _Tag, __enable_if_t<is_same<_Tag, __tag_type>::value, int> = 0>
explicit class_name(_Tag, ...)
```

**Comment by androm3da** [comment]
> We found this from a downstream C++ library comparison test.

I can confirm that I also have encountered this defect - (also while running a downstream conformance suite).

**Comment by frederick-vs-ja** [comment]
For the `complex`-specific case, I guess we can `__bit_cast` between `std::complex` and `_Complex`.

**Comment by androm3da** [comment]
FYI @philnik777

**Comment by efriedma-quic** [comment]
Is anyone looking at this?  It's a regression from 18 to 19.
