### ISSUE TITLE
[analyzer] Should we trust types of regions based of SymbolicRegions?

### ISSUE THREAD

**Issue by steakhal** [llvm/llvm-project#102908]
We had user reports like [this](https://sonarcloud.io/project/issues?id=c-ares_c-ares&issues=AZELfCzXHmoVXF22rrn1&open=AZELfCzXHmoVXF22rrn1&tab=code) one, where we can't see the allocation of an object that is refereed to by a pointer we use.

Example:
```c++
struct MyStruct { int data; };
struct { unsigned char f; } *UChar;
void we_cant_trust_symbolic_pointee_type_uchar(const char *src) {
  memcpy(&UChar->f, src, sizeof(MyStruct)); // we report an issue here for overflowing the destination.
  //     ^^^^^^^^^: FieldRegion{Elem{..., SymbolicRegion}}
}
```

Currently, if we see a `FieldRegion`, `DynamicExtent.cpp:getDynamicExtent()` will query `getStaticSize()`, which will eventually reach the `FieldRegion` handler, which will just take the field type and return `1 S32b` in the example.

However, I'd argue, we could only trust the type for extent information if we have seen the allocation of the pointee object - no matter that offsets or other subregions were formed on top of that symbolic region.

Hence, I propose checking that property first, and return a symbolic extent for symbolic region bases:
```c++
getStaticSize(...) {
  if (isa<SymbolicRegion>(R->getBaseRegion())) {
    return nonloc::SymbolVal(SymMgr.getExtentSymbol(SR));
  }
```

However, this would break a couple of tests, so before I'd look into those or uplift them, I wanted to raise this issue to see if you agree with my reasoning.
@NagyDonat as you may have opinion about OOBs like this one.

**Comment by NagyDonat** [comment]
I'd say that yes, we should trust the types and static sizes of `FieldRegion`s even if they are within `SymbolicRegion`s.

In object-oriented code (or in C code that's referencing `struct` values via pointers) many important values are stored as `this->member` (or `arg->field`) and these are all represented by `FieldRegion`s within `SymbolicRegion`s. An overflow between adjacent fields of the same struct (e.g. an `username` that overflows into `privileges`) is a stereotypically common was of getting pwned and the analyzer should definitely report when this is possible.

Seeing the allocation of the pointee object is irrelevant, because they are not "writing outside of the allocated area, may trigger a segfault" errors but "writing into semantically different allocated area, may be exploited" situations.

Field regions are only created when the developer actually uses the field access syntax, which very strongly implies that they do think that their data is arranged according to the used struct type. (This is different from `ElementRegion`s which can be created by raw pointer arithmetic and do not always imply that the developer is only thinking about the memory area of that particular element.)

Moreover, in the example that you showed the false positive isn't caused by the fact that `a` is a `FieldRegion` within the symbolic region corresponding to the parameter `dns_rr` -- the same false positive would also appear if we were working with a concrete local variable of type `ares_dns_rr_t!`

I think the real issue is that `ares_dns_rr_data_ptr()` can return pointers to various differently-sized fields of the struct `ares_dns_rr_t` (this kind of generic logic is very rare) and the analyzer cannot understand that assuming `ares_dns_rr_key_datatype(key) == ARES_DATATYPE_INADDR` guarantees that it will return a pointer to a field that has the right size.

This happens because the analyzer cannot see [the definition of `ares_dns_rr_key_datatype()`](https://github.com/c-ares/c-ares/blob/1b5473fbb94b8f632c638b8c13f33794cc00f17c/src/lib/record/ares_dns_mapping.c#L451) -- I'd guess that the false positive would disappear if CTU analysis would inline the definition of `ares_dns_rr_key_datatype()`.

**Comment by haoNoQ** [comment]
> Currently, if we see a FieldRegion, DynamicExtent.cpp:getDynamicExtent() will query getStaticSize(), which will eventually reach the FieldRegion handler, which will just take the field type and return 1 S32b in the example.

That's a slightly different problem: For OOB access purposes you probably shouldn't try to figure out the type of a nested sub-region such as `FieldRegion` or `ElementRegion`. It only matters how wide the *allocated buffer* is. Just do a `getBaseRegion()` and move on.

Well, it technically does matter when you overrun an array member variable and run into other member variables. That's very unlikely to be intended, even if it's not always UB. But this requires a significantly more careful pattern-matching logic to cover a lot of cornercases where even this is technically acceptable. (Including, but not limited to, ad-hoc flexible array members that are allowed to be larger than the entire struct.)

> Should we trust types of regions based of SymbolicRegions?

Arguably the answer should be "as much as TBAA trusts them". A pointer can point to a larger object than its target type in the type system tells you (eg. pointer to a field of a larger object, or a base class pointer to a polymorphic object), or to a buffer of objects of that type. All of these are completely normal situations. A `char *` can point to virtually anything, just like in your example. But an `int *` cannot point to an object of type `float` assuming that `-fstrict-aliasing` is enabled.

That said, whatever TBAA tells us isn't really helpful to the OOB access problem whatsoever. You can't decide whether an OOB access happens without knowing whether the pointer points to a bigger object, and that's exactly the kind of info that TBAA doesn't provide.

So I think this answers the question "_can_ we trust types of regions based on SymbolicRegions?": in the general case probably not.

Now, whether we *should* trust them, that's a completely different question. It depends on what kind of checker do you want to make. If you want to find only real exploitable bugs, probably not. If you want your users' code to make sense and you want to help them be careful by introducing a clear coding convention that the checker would help them follow, absolutely go for it. It's kind of great that the engine doesn't force you to make that decision so it's largely offloaded to the checkers.

**Comment by NagyDonat** [comment]
> Well, it technically does matter when you overrun an array member variable and run into other member variables. That's very unlikely to be intended, even if it's not always UB. But this requires a significantly more careful pattern-matching logic to cover a lot of cornercases where even this is technically acceptable. (Including, but not limited to, ad-hoc flexible array members that are allowed to be larger than the entire struct.)

As far as I know the standard says that overrunning the memory area of a member variable **is always undefined behavior** (see e.g. [expr.add 4.2](http://eel.is/c++draft/expr.add#4.2) and [expr.sub](http://eel.is/c++draft/expr.sub) in the current C++ standard draft, but I checked that [C89](http://port70.net/%7Ensz/c/c89/c89-draft.html#3.3.6) also specifies equivalent limitations).

The C standard allows flexible array members since C99, but only with syntax like `int flexible[]` (that is, an array of _unspecified_ size as opposed to an array of 0 or 1 elements), so that is _not_ overrunning the memory area of the field. (The C++ standard does not allow flexible array members.)

Note that the analyzer already special cases flexible array members (including the non-standard-compliant ones declared with 0 or 1 elements) with a suitable dynamic extent.

Based on these, I still strongly support bounds checking the array subobjects even within symbolic regions. Trickery which oversteps these bounds is suspicious enough to deserve a big fat warning. (If somebody wishes to use dangerous undefined behavior without analyzer warnings, then why are they using the analyzer?)
