### ISSUE TITLE
[lldb-dap] show breakpoint hit count

### ISSUE THREAD

**Issue by fr43nk** [llvm/llvm-project#104396]
Hi,

is it possible to show the hit count of a breakpoint somewhere in the hover quickinfo? I do not want to create a log point for this as this gets confusing when there are multiple breakpoints.

Best regards,
Frank

**Comment by Da-Viper** [comment]
![image](https://github.com/user-attachments/assets/5e2dc1f2-7db2-4808-8c10-a6b7802333d9)
 @fr43nk  Is this what you mean ?

**Comment by fr43nk** [comment]
@Da-Viper that looks very promising. Is this a new feature in the extension? I cannot see it on my vscode.

**Comment by Da-Viper** [comment]
> @Da-Viper that looks very promising. Is this a new feature in the extension? I cannot see it on my vscode.

It is in vscode and this is using the lldb-dap 

Right click on the space before the numbering you should see option 

add conditional breakpoint -> from the drop down select -> Hit Count ->  then set the number of hit count

**Comment by fr43nk** [comment]
@Da-Viper  Ah, no, so we had a misunderstanding here. What I mean is, that there is some kind of information for every set breakpoint, how often the breakpoint is hit.  The "hit count" setting is something different, It means to stop at a certain hit count value.

**Comment by vogelsgesang** [comment]
Afaict, this feature request is directed to the wrong project. This should be implemented in VS Code's debugger UI.  I would recommend you open a corresponding feature request in https://github.com/microsoft/vscode/issues

The VS Code frontend apparently already keeps track of hit-counts for special "Hit Count" breakpoints, as shown by @Da-Viper's screenshot. I assume it would be rather straightforward to extend this bookkeeping also to normal breakpoints.

Even if we wanted to implement this functionality in lldb-dap, there seems to be no way for the debug adapter to instruct the UI to show additional information in the hover of a breakpoint. As such lldb-dap's hands are tied here.

Closing this issue, as I think it is out-of-scope of lldb-dap

**Comment by fr43nk** [comment]
Thank you @vogelsgesang.
One short question: is the management of the "hit count" breakpoint also part of the vscode or is that something related to llvm-dap?

**Comment by vogelsgesang** [comment]
I did some more digging. Turns out I was partially wrong.

Hit counts are in fact tracked in lldb itself, and not in the frontend. The way this works is:

* The user creates a breakpoint with a hit-count expression in the UI
* The UI uses [setBreakpoints](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_SetBreakpoints) to set this breakpoint. The [SourceBreakpoint](https://microsoft.github.io/debug-adapter-protocol/specification#Types_SourceBreakpoint)'s `hitCondition` is set to whatever the user entered in the UI as the hit-count expression
* LLDB-DAP parses the expression as an integer, and sets the ignore-count of the underlying breakpoint accordingly
* LLDB will then ignore the first couple of times this breakpoint is triggered

Based on this, it turns out that lldb actually already has the hit count available. You can get it from the debug console in VS Code by running, e.g., `break list`:

```
(lldb) break list
Current breakpoints:
1: file = '/home/avogelsgesang/Documents/corotest/test-invoke.cpp', line = 22, exact_match = 0, locations = 1, resolved = 1, hit count = 1
  Names:
    dap

  1.1: where = a.out`PrintAdder::print_add(int) const + 19 at test-invoke.cpp:22:18, address = 0x0000555555555483, resolved, hit count = 1 
```

However, I am not aware of a way to communicate this information from lldb via the debug adapter protocol to the frontend, such that VS Code would display it in the UI

**Comment by fr43nk** [comment]
@vogelsgesang that sounds like a good workaround until a real solution is implemented:)

The question I had regarding "hit count" breakpoints: If I create a "hit count" breakpoint it gets active for the amount of hits like configured. But, when I restart the debugger (the green circle icon) this count is not reset. Means, the breakpoint gets hit immediately and not after the configured hit count. Is this worth a new issue?

Best regards
