### ISSUE TITLE
clang preprocessor crashes when using -E -CC option on MFC code.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#10525]
|  |  |
| --- | --- |
| Bugzilla Link | [10153](https://llvm.org/bz10153) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @akyrtzi,@ismail |

## Extended Description 
If you are trying to get the preprocessed output file of a MFC file using the -E -CC options, clang will crash.

Here is a reduction:
test.cpp:
#define A text//\

clang -E -CC test.cpp

**Comment by Endilll** [comment]
Crash was indeed fixed in Clang 3.1: https://godbolt.org/z/cGrxoe5fn

As for the last example:
```cpp
int main(int argc, char* argv[]) {
	// \
	int a; //dead line
	int b;
	return 0;
}
```
per __N4944__.lex.phases, backslashes are processed during the second phase, whereas comments are processed on the third phase. Which means `int a; //dead line` becomes a part of the previous line `//` before compiler recognizes comments to skip over them. There's no implementation divergence on this, save for MSVC  `/C` (preserve comments) mode: https://godbolt.org/z/PYYhhdjKb
