### ISSUE TITLE
[lld][RISC-V] No Warning/Error on R_RISCV_PCREL_LO referencing symbol/relocation in different section

### ISSUE THREAD

**Issue by quic-seaswara** [llvm/llvm-project#107304]
The following test shows that lld creates a image that has a LO relocation thats connected to a HI relocation in a different section.

```
.section .text.foo
.global foo
foo:
        addi    a0, a0, %pcrel_lo(.Lpcrel_hi0)
        lw      a0, 0(a0)
.section .text.bar
.Lpcrel_hi0:
        auipc   a0, %pcrel_hi(a)
.data
.global a
a:
.word 100

```

```
$ riscv-ld r.o
riscv-ld: warning: cannot find entry symbol _start; defaulting to 00010094
r.o: in function `foo':
(.text.foo+0x0): dangerous relocation: %pcrel_lo missing matching %pcrel_hi
```
```
$ ld.lld r.o
ld.lld: warning: cannot find entry symbol _start; not setting start address
```

The RISC-V ABI mentions this :-

https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-elf.adoc

> The `R_RISCV_PCREL_LO12_I` or `R_RISCV_PCREL_LO12_S` relocations contain a label pointing to an instruction in the same section with an `R_RISCV_PCREL_HI20` relocation entry that points to the target symbol:
> 
> At label: `R_RISCV_PCREL_HI20` relocation entry → symbol
> 
> `R_RISCV_PCREL_LO12_I` relocation entry → label

**Comment by lenary** [comment]
GNU ld's error message isn't very obvious here, it says "missing matching `%pcrel_hi`", presumably because it's only looking in the same section? It's not actually saying anything about not matching the psABI.

Looking at LLD's behaviour:
- LLD does look to be doing the right address calculations needed for the relocations in the testcase you provided.
- Nonetheless, it would be good to emit a warning or error in this case, like GNU ld does (though maybe with clearer messaging), given we know the ABI wants these to be in the same section.
