### ISSUE TITLE
[mlir] Semantic inconsistency in `ceildiv` optimization

### ISSUE THREAD

**Issue by Emilyaxe** [llvm/llvm-project#107508]
Git version: [c28b1a19aa](https://github.com/llvm/llvm-project/commit/c28b1a19aa)
System: Ubuntu 18.04.6 LTS

# Issue Description:
In the following MLIR:
a.mlir
```
func.func @semiaffine_composite_floor(%arg0: index, %arg1: index) -> index {
  %a = affine.apply affine_map<(d0)[s0] ->(((((s0 * 2) ceildiv 4) * 5) + s0 * 42) ceildiv s0)> (%arg0)[%arg1]
  return %a : index
}
```
After running `mlir-opt -canonicalize a.mlir`, the resulting optimized MLIR is:
```
module {
  func.func private @semiaffine_composite_floor(%arg0: index, %arg1: index) -> index {
    %c47 = arith.constant 47 : index
    return %c47 : index
  }
}
```
This leads to the result always being 47.

However, without applying the canonicalize optimization, the result of a.mlir varies depending on the input `%arg1` as follows:

- 44 if `%arg1` is less than 0
- Floating-point exception if `%arg1` is 0
- 47 if `%arg1` is 1
- 45 if `%arg1 `is greater than 1

This seems like a misoptimization in the handling of ceildiv. The canonicalize pass simplifies the expression to always return 47, but the expected behavior is input-dependent as shown above. Is this an unintended side effect of the ceildiv optimization?

**Comment by lipracer** [comment]
`(s * a) ceildiv b` equal to `a ceildiv b` iff `b` divided by `a`, it's indeed is a bug.I will fixed it later.

**Comment by lipracer** [comment]
we can simple `(n * s) ceildiv a ceildiv s` to `n ceildiv a`
because `(n * s) ceildiv a ceildiv b` <=> `(n * s) ceildiv s ceildiv a`
<=> `n ceildiv a`

let's prove the `s floordiv a floor b` <=> `s floordiv b floor a`
let `s = ka +m (m < s)` so `s floordiv a` <=> `s / a - m / s`

similarly, it can be proven that: 
`s floordiv a floordiv b` <=> `s / (a *b) - m / (s * b) - n / (b)   constrain  (n < b)` 
<=> `s / (a * b) - (m + s*n) / (s*b)`

because `s * b - (m + s*n)` <=> `s*b - s*n - m` > `s - m` > `0`
so `s floordiv a floordiv b` <=> `[s / (a*b)]` <=> `s floordiv b floordiv a`
but if `s floordiv b` mutiply a factor above didn't always hold true.
