### ISSUE TITLE
Clang uses fneg+fadd to subtract 0.5 when Zfa is enabled.

### ISSUE THREAD

**Issue by pirama-arumuga-nainar** [llvm/llvm-project#107772]
Reproducer is the [simplest possible code](https://godbolt.org/z/M3dosqM3v):

```
float foo(float x) {
    return x - 0.5f;
}
```

GCC does the expected thing.

**Comment by topperc** [comment]
@dtcxzyw what's your plan to fix this? There's a similar issue with the FMA instructions.

**Comment by dtcxzyw** [comment]
> @dtcxzyw what's your plan to fix this? There's a similar issue with the FMA instructions.

Do you think it is better to add new (custom) isel patterns instead of folding this in MachineCombiner?

**Comment by dtcxzyw** [comment]
> > @dtcxzyw what's your plan to fix this? There's a similar issue with the FMA instructions.
> 
> Do you think it is better to add new (custom) isel patterns instead of folding this in MachineCombiner?

I prefer the latter one since some FMA instructions are created in MachineCombiner. See https://reviews.llvm.org/D136764.

**Comment by topperc** [comment]
> > > @dtcxzyw what's your plan to fix this? There's a similar issue with the FMA instructions.
> > 
> > 
> > Do you think it is better to add new (custom) isel patterns instead of folding this in MachineCombiner?
> 
> I prefer the latter one since some FMA instructions are created in MachineCombiner. See https://reviews.llvm.org/D136764.

Those originate from FSUB/FADD though so catching FADD/FSUB in isel would catch those right? It doesn't look like MachineCombiner handles fneg on the multiplicands, is that a missed optimizaton even without Zfa?

**Comment by VorfeedCanal** [comment]
Without `Zfa` you wouldn't see `fneg` because it would be folded into the constant. It's equally easy to produce `0.5` and `-0.5` without `Zfa` and that holds for all constants (all important immediates on RISC-V are signed).

But `Zfa` only provides positive values of most popular constants and assumes that `fsub` (and appropriate FMA instructions) would be used where needed.

Note that for non-constant operands `fsub` is used, which means that it's not ”missed“ optimization but a case where replacement of `fsub` with `fadd` (why does that happen at all?) leads to suboptimal code.
