### ISSUE TITLE
[mca] crash when attempting to use avx512 on znver4

### ISSUE THREAD

**Issue by kiroma** [llvm/llvm-project#108157]
Given the following assembly (minimized code taken from Intel's histogram example):
```asm
histogram_loop:
vpconflictd zmm0, zmm3
kxnorw k1, k1, k1
vpxord zmm1, zmm1, zmm1
```
A crash occurs
```
$ llvm-mca-18 hist.s -mcpu=znver4 --x86-asm-syntax=intel
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: llvm-mca-18 hist.s -mcpu=znver4 --x86-asm-syntax=intel
 #0 0x00007adbd7194716 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0xd94716)
 #1 0x00007adbd71926d0 llvm::sys::RunSignalHandlers() (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0xd926d0)
 #2 0x00007adbd7194ddb (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0xd94ddb)
 #3 0x00007adbd5c42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x00007adbd888aec4 llvm::mca::ResourceManager::issueInstruction(llvm::mca::InstrDesc const&, llvm::SmallVectorImpl<std::pair<std::pair<unsigned long, unsigned long>, llvm::mca::ReleaseAtCycles>>&) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x248aec4)
 #5 0x00007adbd888c0fb llvm::mca::Scheduler::issueInstructionImpl(llvm::mca::InstRef&, llvm::SmallVectorImpl<std::pair<std::pair<unsigned long, unsigned long>, llvm::mca::ReleaseAtCycles>>&) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x248c0fb)
 #6 0x00007adbd888c31a llvm::mca::Scheduler::issueInstruction(llvm::mca::InstRef&, llvm::SmallVectorImpl<std::pair<std::pair<unsigned long, unsigned long>, llvm::mca::ReleaseAtCycles>>&, llvm::SmallVectorImpl<llvm::mca::InstRef>&, llvm::SmallVectorImpl<llvm::mca::InstRef>&) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x248c31a)
 #7 0x00007adbd8895756 llvm::mca::ExecuteStage::issueInstruction(llvm::mca::InstRef&) (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x2495756)
 #8 0x00007adbd889615e llvm::mca::ExecuteStage::cycleStart() (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x249615e)
 #9 0x00007adbd8893b1d llvm::mca::Pipeline::runCycle() (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x2493b1d)
#10 0x00007adbd88939d5 llvm::mca::Pipeline::run() (/lib/x86_64-linux-gnu/libLLVM-18.so.18.1+0x24939d5)
#11 0x000061300efec201 (/usr/lib/llvm-18/bin/llvm-mca+0x16201)
#12 0x000061300efeac8b (/usr/lib/llvm-18/bin/llvm-mca+0x14c8b)
#13 0x00007adbd5c29d90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#14 0x00007adbd5c29e40 call_init ./csu/../csu/libc-start.c:128:20
#15 0x00007adbd5c29e40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#16 0x000061300efe4675 (/usr/lib/llvm-18/bin/llvm-mca+0xe675)
Segmentation fault (core dumped)
```

**Comment by RKSimon** [comment]
crashes on trunk (and appears to be znver4 model specific): https://compiler-explorer.com/z/Mx5acv8nx

**Comment by boomanaiden154** [comment]
Doing some debugging, it seems like this might be related to the handling of the `vpxord` as a zeroing idiom. I'm seeing the following sequence of events:
```
VPCONFLICTDZrrkz takes resource
VPCONFLICTDZrrkz takes resources
resource released
resource released
VPXORDZrrkz takes resource
VPXORDZrrkz takes resource
resource released
VPCONFLICTDZrrkz takes resources
VPCONFLICTDZrrkz tries takes resources (assertion failure)
```

Will keep investigating for a little bit longer.

**Comment by boomanaiden154** [comment]
Actually doesn't seem to be related to zero-idiom handling of `VPXORDZrrkz` given that instruction is not in the `znver4` scheduling model at all. Adding it to the scheduling model as a zeroing-idiom fixes the issue.

That seems like it probably only hides the problem though.

**Comment by adibiagio** [comment]
I think I know what is causing the issue with that particular code snippet.

The pipeline selection logic in `ResourceManager::issueInstruction()` doesn't correctly handle instructions which consume multiple partially overlapping resource groups. In some (rare) cases, it might fail to allocate resources on instruction issue.

According to the znver4 model, instruction `VPCONFLICTDZrr` consumes the following resources:
```
  Zn4FPAES01    -> {Zn4FP0 | Zn4FP1}   - 2cy
  Zn4FPFAdd01  -> {Zn4FP2 | Zn4FP3}   - 2cy 
  Zn4FPFMisc12 -> {Zn4FP1 | Zn4FP2}   - 2cy 
```
Here, group Zn4FPFMisc12 partially overlaps with both Zn4FPAES01 and Zn4FPFAdd01.

Method `ResourceManager::issueInstruction()` (file ResourceManager.cpp) is responsible for mapping writes to resource units. Writes are always processed in sequence.
In the case of instruction VPCONFLICTDZrr , group `Zn4FPAES01` is always selected first, while group `Zn4FPFMisc12` is always selected last.

Here is what happens when resource unit `Zn4FP1` is unavailable:

At first, the algorithm selects `Zn4FP0` for Zn4FPAES01 (this is the only possible choice, since `Zn4FP1` is unavailable).
It then selects a pipe for `Zn4FPFAdd01`; in this case, the algorithm sees that `Zn4FP2` and `Zn4FP3` are both available.
However, selecting `Zn4FP2` would be a mistake, because it would leave group `Zn4FPFMisc12` with no choice.

The presence of multiple partially overlapping groups complicates the selection process by introducing extra constraints.
For those cases, the algorithm should prioritize groups which are more constrained than others.

Marking VPXORDZrrkz as suggested by @boomanaiden154 is not a bad idea in general. However - as he also mentioned - it would only hide the real issue.

Fixing this issue is not straightforward. I'll see if I can come up with a solution for this problem.

**Comment by boomanaiden154** [comment]
Ah, that would make sense. I was still debugging resource release (thinking that would be the issue) in `ResourceManager.cpp` and finally figured out that what I thought was a resource not getting freed was actually just a resource with an additional cycle left. 🤦 

That explanation makes quite a bit of sense.

I'll leave you to writing up an actual fix. I'll try and get a fix in for the znver4 scheduling model to at least fix the proximal cause. As you mentioned, that would be a good idea in general as right now the znver4 scheduling model seems to be missing all AVX512 zeroing idioms. I don't have `znver4` hardware on me to test, but I can't imagine `VPXORDZrr` wouldn't be.

@ganeshgit Do you have information on what AVX512 instructions in `znver4` are AVX512 zeroing idioms so that we can hopefully get all of them in at some point?

**Comment by RKSimon** [comment]
According to the Zen4 SoG:
```
The processor supports the following Zeroing Idioms:
GPR Zeroing Idioms
• XOR reg, reg (clears reg and the flags, 0-cycle operation)
• SUB reg, reg (clears reg and the flags, 0-cycle operation)
• CMP reg, reg (sets Z flag and clears other flags, 0-cycle operation)
• SBB reg, reg (copies the zero extended value of the carry flag into reg without a dependency on the previous value of reg, 1-cycle operation)

SIMD Zeroing Idioms (all clear destination register as a 0-cycle operation)
• XORP(S/D) xmm,xmm
• VXORP(S/D) zmm/ymm/xmm,zmm/ymm/xmm,zmm/ymm,xmm
• ANDNP(S/D) xmm,xmm
• VANDNP(S/D) zmm/ymm/xmm,zmm/ymm/xmm,zmm/ymm/xmm
• PCMPGT(B/W/D/Q) xmm,xmm
• VPCMPGT(B/W/D/Q) zmm/ymm/xmm,zmm/ymm/xmm,zmm/ymm/xmm
• PANDN xmm,xmm
• VPANDN zmm/ymm/xmm,zmm/ymm/xmm,zmm/ymm/xmm
• PXOR xmm,xmm
• VPXOR zmm/ymm/xmm,zmm/ymm/xmm,zmm/ymm/xmm
• PSUBB(B/W/DQ/) xmm,xmm
• VPSUB(B/W/D/Q) zmm/ymm/xmm,zmm/ymm/xmm,zmm/ymm/xmm

A number of instructions can be used to set a register to all ones and break input dependencies. These are referred to as Ones Idioms:

The processor supports the following Ones Idioms:
• PCMPEQ(B/W/D/Q) xmm,xmm
• VPCMPEQ(B/W/D/Q) zmm/ymm/xmm,zmm/ymm/xmm,zmm/ymm/xmm
```
