### ISSUE TITLE
Missing default branch in switch cases.

### ISSUE THREAD

**Issue by NEWPLAN** [llvm/llvm-project#108479]
Hi, in the code segment(https://github.com/llvm/llvm-project/blob/main/mlir/lib/Conversion/ArmSMEToLLVM/ArmSMEToLLVM.cpp#L127), a default case is missing in switch, making it non-self-consistent.

**Comment by braw-lee** [comment]
@NEWPLAN added default branches, not sure if this will affect anything but seems like good coding practice

**Comment by braw-lee** [comment]
i think this issue can be closed as all the switch cases are covered as said by banach-space
"It's not clear to me whether this follows https://llvm.org/docs/CodingStandards.html#don-t-use-default-labels-in-fully-covered-switches-over-enumerations. I do remember that we skipped default because most of these switch statements are fully covered. Is there one that isn't?"
