### ISSUE TITLE
Question about attrbutes and C++20 coroutines

### ISSUE THREAD

**Issue by kelbon** [llvm/llvm-project#108730]
As i understand, now all attributes like [[pure]] [[always_inline]] [[flatten]] [[cold]] [[hot]] etc when applied to coroutine function applied to implicit function which return coroutine, not to coroutine itself

So, my question is how to, for example, apply [[flatten]] to coroutine::resume function? Is it possible?

**Comment by AaronBallman** [comment]
I believe that you can't apply the attribute to anything but the implicit coroutine function because the [as-if](https://eel.is/c++draft/dcl.fct.def.coroutine#5) is on the function body not on the function declaration.

I'm closing the issue, but if you have further questions or want to discuss further, feel free to reopen it!
