### ISSUE TITLE
Requires expression with local parameter of void type

### ISSUE THREAD

**Issue by Fedr** [llvm/llvm-project#109538]
This program is accepted by Clang (`requires` is evaluated as `true`):
```
static_assert( requires(void t) {t;} );
```
but rejected by GCC and MSVC with hard error: https://gcc.godbolt.org/z/W7f3zqbMb

If it were evaluated as `false`, it would be more understandable.

**Comment by shafik** [comment]
Looks like a clang bug: https://godbolt.org/z/E7a4eEeKs

**Comment by zyn0217** [comment]
This seems to be an oversight in `Sema::ActOnStartRequiresExpr()` and we forgot to ensure the non-void parameter types in a RequiresExpr.

Like what we did in `Sema::BuildFunctionType()`, we probably should check if any ParmVarDecl in `LocalParameters` is of void type, and if so, we should diagnose it with `diag::err_param_with_void_type`.

Further, we should set the RequiresExprBodyDecl to invalid in that event; we also want to set the satisfaction flag to false in `RequiresExpr`'s constructor so that the expression could be evaluated to false.

**Comment by erichkeane** [comment]
> I would like to work on this issue. 💪

I've assigned it to you, have fun!  Make sure you add a few of us (myself and @zyn0217 included!) to the review, and feel free to ask questions.
