### ISSUE TITLE
Make `std::variant<>` a soft error (SFINAE friendly)

### ISSUE THREAD

**Issue by ilazaric** [llvm/llvm-project#111268]
https://godbolt.org/z/8xojM67ev
Simplified, without `<variant>` : https://godbolt.org/z/KdK8n76hb
Proposed alternative, on simplified: https://godbolt.org/z/PPrPzjfb1
So instead of the internal `static_assert()`, I suggest moving the condition into a constraint
The `static_assert()` in question: https://github.com/llvm/llvm-project/blob/main/libcxx/include/variant#L1164

**Comment by ilazaric** [comment]
Forgot passing `-stdlib=llibc++`, updating description

**Comment by ilazaric** [comment]
After fixing the links, seems my fix doesn't work
Fix version with clang: https://godbolt.org/z/GxshffYsM (doesn't work)
Fix version with gcc: https://godbolt.org/z/zYrz5Tf8E (works)
Unsure what I think

**Comment by ilazaric** [comment]
This works though: https://godbolt.org/z/qWrf9G8j1
^ this is mimicking better the context in which I came across this
`bla` is `std::cout`, `noop` is `std::endl`
So I still think it's worth it

**Comment by philnik777** [comment]
This is how every implementation handles it (https://godbolt.org/z/hdh96essd) and also how the standard specifies it (http://eel.is/c++draft/variant#variant.general-3), so I don't think we should add an extension. Since that is our general policy anyways I'm closing this. If you want this kind of thing to work you can simply constrain your function instead.
