### ISSUE TITLE
`fcmp` miscompiled to a constant

### ISSUE THREAD

**Issue by bongjunj** [llvm/llvm-project#114947]
Alive2 report: https://alive2.llvm.org/ce/z/324E7x

```llvm
----------------------------------------
define i1 @fcmp_double_dynamic_dynamic.2() denormal-fp-math=dynamic,dynamic {
#0:
  %cmp = fcmp une double 0x0008000000000000, -0.000000
  ret i1 %cmp
}
=>
define i1 @fcmp_double_dynamic_dynamic.2() nofree noundef willreturn denormal-fp-math=dynamic,dynamic memory(none) {
#0:
  ret i1 1
}
Transformation doesn't verify!

ERROR: Value mismatch

Example:

Source:
i1 %cmp = #x0 (0)

Target:
Source value: #x0 (0)
Target value: #x1 (1)

Summary:
  0 correct transformations
  1 incorrect transformations
  0 failed-to-prove transformations
  0 Alive2 errors
```

**Comment by arsenm** [comment]
I don't see the issue? Those values are in fact not equal, so this is true. Alive bug?

**Comment by jcranmer-intel** [comment]
it's comparing a denormal to 0, and the `denormal-fp-mode` is set to `dynamic`, so `fcmp` may or may not be flushing denormals to 0.

**Comment by nikic** [comment]
I expect this is because we got through ValueLattice comparison, which does not have access to the denormal mode: https://github.com/llvm/llvm-project/blob/9501af5f92bb31fa9527d12a4b17b88d9fd651c4/llvm/lib/Analysis/ValueLattice.cpp#L28-L29

Really, the constant folding implementation should be defaulting to the conservatively correct behavior if the denormal mode is unknown.
