### ISSUE TITLE
The building proccess keeps crashing.

### ISSUE THREAD

**Issue by AugustineYang** [llvm/llvm-project#115134]
OS: Ubuntu Linux 22.04
GCC&G++: 11.4.0
CMake: 3.22.1
Hardware: i7-12700K with 64GB RAM

I'm trying to build llvm 19.1.0 from the source code following the instruction in [Getting Started with the LLVM System](https://llvm.org/docs/GettingStarted.html). I "make" the project with the command `cmake -S llvm -B build -G Ninja -DLLVM_ENABLE_PROJECTS=all -DCMAKE_BUILD_TYPE=Debug -DLLVM_ENABLE_RUNTIME=all -DCMAKE_C_COMPILER=/usr/bin/gcc-11 -DCMAKE_CXX_COMPILER=/usr/bin/g++-11`. I "build" the project with the command `cmake --build build -j16`, but I'm facing steadily crashes after building about 7,000 of over 13,000 tasks with TOTALLY NO error message. The terminal window just crashed and disappeared with no error message or OS error report. Or the VSCode window just crashed if I'm using the integreted terminal of VSCode. The crash follows a sudden CPU usage decrease. "Build" can continue in a new terminal window, but the crash will happen again after about 200 tasks. Changing the GCC compiler to 12.3.0 makes no difference. Does anyone face the same issue?

**Comment by DimitryAndric** [comment]
Usually this is due to out-of-memory (OOM) conditions, which can cause random processes to be killed, such as your terminal or IDE. You can check the system logs or`dmesg` output to see if that occurred.

Try to work around this by lowering the `-j` level, or adding more RAM or swap to the build machine.

**Comment by git-flyer** [comment]
I am building an llvm project on a Linux system, and 16GB of memory plus a 60GB swap partition is still a struggle

**Comment by DimitryAndric** [comment]
Note that especially with `-DCMAKE_BUILD_TYPE=Debug`, the linking phase can take enormous amounts of memory. Since link jobs tend to cluster together too, this can lead to even higher memory usage. To limit number of parallel link jobs, try adding `-DLLVM_PARALLEL_LINK_JOBS=1` (or 2 if you are brave :).

**Comment by AugustineYang** [comment]
> Usually this is due to out-of-memory (OOM) conditions, which can cause random processes to be killed, such as your terminal or IDE. You can check the system logs or`dmesg` output to see if that occurred.
> 
> Try to work around this by lowering the `-j` level, or adding more RAM or swap to the build machine.

It seems that you're right. But it's quite weird that there're still around 200GB swap space available (250GB total) when the crashes happen.

**Comment by DimitryAndric** [comment]
Since you are running on a relatively new Ubuntu system, it could also be that this is due to [systemd-oomd](https://www.freedesktop.org/software/systemd/man/latest/systemd-oomd.service.html). Quoting from their manpage (emphasis added by me):

> systemd-oomd is a system service that uses cgroups-v2 and pressure stall information (PSI) to monitor and take corrective action **before an OOM occurs in the kernel space**.

I don't know if systemd-oomd is available and enabled on your system, but if it is, check its logs.

**Comment by DimitryAndric** [comment]
There's this thread on AskUbuntu where a user complains about a similar issue as yours:
https://askubuntu.com/questions/1404888/how-do-i-disable-the-systemd-oom-process-killer-in-ubuntu-22-04
> Ubuntu 22.04 comes with the systemd-oomd service enabled by default, which has been "helpfully" killing my IDE and / or terminals whenever I try to compile an application using an abundance of threads / memory.

**Comment by AugustineYang** [comment]
> There's this thread on AskUbuntu where a user complains about a similar issue as yours: https://askubuntu.com/questions/1404888/how-do-i-disable-the-systemd-oom-process-killer-in-ubuntu-22-04
> 
> > Ubuntu 22.04 comes with the systemd-oomd service enabled by default, which has been "helpfully" killing my IDE and / or terminals whenever I try to compile an application using an abundance of threads / memory.

@DimitryAndric   64GB RAM and 250GB swap space is quite enough I think. It seems that systemd-oomd is to be blame. Disabling the service solves the issue! Awesome! Really appreciate your help!

**Comment by DimitryAndric** [comment]
Happy building, I will close this now. :)
