### ISSUE TITLE
compile time regression introduced by Sema checking for __builtin_counted_by_ref

### ISSUE THREAD

**Issue by rapidsna** [llvm/llvm-project#115520]
As reported by @nikic 
https://github.com/llvm/llvm-project/pull/114495#issuecomment-2464318302

This is likely because the checks are currently implemented to walk through the whole child nodes for every single assignments. We may be able to remove the overhead by rolling up the information about usage of `counted_by` or `__builtin_counted_by_ref` to the assignment, instead of re-visiting child nodes.

**Comment by bwendling** [comment]
Could you expand on what you mean by rolling up the information about usage of __builtin_counted_by_ref into the assignment?

**Comment by bwendling** [comment]
Okay. So what I'd like to do is emit these diagnostics while processing the `__builtin_counted_by_ref()` call. What I need to do is be able to crawl up the AST from the `CallExpr` to see how it's used. Is there a way to do that in the front-end?

**Comment by nikic** [comment]
Maybe @Sirraide knows how to do that?

**Comment by bwendling** [comment]
I think I found it. You have to use the `ParentMapContext` to get it. It's so odd...

**Comment by Sirraide** [comment]
> Is there a way to do that in the front-end?

Walking *up* isn’t really something that’s easy to do in the general case. The only solution I can think of is that it’d be possible to use a placeholder expression for this, but I’m not sure we want to introduce an extra AST node for this (and I don’t think there’s an existing one we could use); that said, maybe there is another way that I’m just not thinking of atm.

Maybe @AaronBallman has an idea?

**Comment by rapidsna** [comment]
I haven't done it before but could we perhaps put these into some kind of DelayedDiagnostics and then emit it only when certain conditions are met?

**Comment by Sirraide** [comment]
> I haven't done it before but could we perhaps put these into some kind of DelayedDiagnostics and then emit it only when certain conditions are met?

I mean, the problem w/ that is where would you store those, and where would you check for them?

**Comment by rapidsna** [comment]
If a delayed diagnostics approach won't work then we may need to implement the checking in each place where a pointer can appear as an operand, e.g., binary op (+, -), unary op (*, --, ++), a function call, etc.  and prevent it from using the builtin.

**Comment by Sirraide** [comment]
> If a delayed diagnostics approach won't work then we may need to implement the checking in each place where a pointer can appear as an operand,

Yeah, that’s what I was thinking of using a placeholder expression because that’s already checked everywhere

**Comment by AaronBallman** [comment]
We don't have a cheap way to walk *up* the AST, only down (walking up involves quite a bit of work). 

A placeholder expression could possibly work, but IIRC that involves coming up with a placeholder type that is then used as the type of the operand expression and I don't think we have any such type that maps closely to what we want to do here. Though maybe there is? This call is a sort of reverse-pseudo-object. (Pseudo objects in Clang are used when the syntactic form of the code looks like an object access but the semantic form of the code is a function call; here we have a syntactic form that's a function call but the semantic form is accessing an object.) It's worth investigating whether a placeholder expression would work.

If that doesn't work, then another idea to consider would be an RAII object of some sort. e.g., 
```
struct DiagnoseBuiltinCountedByRefUses;

class Sema {
  ...
  std::vector<DiagnoseBuiltinCountedByRefUses&> BuiltinCountedByRefTrackers;
  bool isTrackingCountedByRef() const { return !BuiltinCountedByRefTrackers.empty(); }
  DiagnoseBuiltinCountedByRefUses& getCurrentBuiltinCountedByRefTracker() {
    assert(isTrackingCountedByRef()); // Alternatively, we could have a default "tracker" that issues no diagnostics
    return BuiltinCountedByRefTrackers.back();
  }
  ...
};

struct DiagnoseBuiltinCountedByRefUses {
  std::vector<SourceLocation> Locs;
  Sema &Sem;

  DiagnoseBuiltinCountedByRefUses(Sema &S) : Sem(S) {
    Sem.BuiltinCountedByRefTrackers.push_back(*this);
  }
  ~DiagnoseBuiltinCountedByRefUses() {
    llvm::for_each(Locs, [this](SourceLocation Loc) {
      Sem.Diag(Loc, diag::bad_things_have_happened);
    }
    Sem.BuiltinCountedByRefTrackers.pop_back();
  }
};
```
Then from the various operators you want to guard against using `__builtin_counted_by_ref` from, you could do:
```
  {
    DiagnoseBuiltinCountedByRefUses Tracker(TheSemaObject);
    // Continue processing operands of the operator.
  } // Diagnoses any calls to __builtin_counted_by_ref made in an operand.
```
and from the `CallExpr` handler where we know we've hit a `__builtin_counted_by_ref` call, you can do:
```
if (TheSemaObject.isTrackingCountedByRef())
  TheSemaObject.getCurrentBuiltinCountedByRefTracker().Locs.push_back(TheCallExprLoc);
```
(You may need additional things to be tracked so you're able to issue a high-quality diagnostic, but it seems like a design like this could work?)

**Comment by Sirraide** [comment]
> but I’m not sure we want to introduce an extra AST node for this

Also, looking at this again, I don’t think we need a new AST node—just a new placeholder type would be enough.

**Comment by rapidsna** [comment]
>> If a delayed diagnostics approach won't work then we may need to implement the checking in each place where a pointer can appear as an operand,

> Yeah, that’s what I was thinking of using a placeholder expression because that’s already checked everywhere

Actually, my suggestion was that this way we can emit an error "immediately" without having to look at the parent nodes. Or having to traverse the subexpressions later:

__builtin_counted_by_ref(...) + 1; -> error immediately at binary op
& __builtin_counted_by_ref(...); -> error immediately at unary op
__builtin_counted_by_ref(...)++; -> error immediately at unary op
LHS = __builtin_counted_by_ref(...); -> error immediately at binary op

LHS = __builtin_counted_by_ref(...) + 1; -> was an error at subexpression already

**Comment by AaronBallman** [comment]
> It's just that we need to add checks in these individual places, instead of simply checking it at assignment (which is the current implementation).

That approach would work. Placeholder expressions are somewhat analogous though in that we have already sprinkled `CheckPlaceholderExpr()` calls all over Sema, and that basically means "if you get a placeholder type out of this expression at this point, it's an error". So you could use that by creating a placeholder type for the `CallExpr` when processing the call to `__builtin_counted_by_ref`, and then turn that into a real type when it appears on the LHS of an assignment (so it remains a placeholder in circumstances where uses in other expressions should be diagnosed). Note: I've not tried any of this, so maybe it's a bad idea.

**Comment by bwendling** [comment]
*sigh* This is why I hate doing anything in the front-end. Nothing is ever "easy" to do, which was one of the overriding principles of the middle-end.

Okay, so @rapidsna's suggestion for looking at the immediate neighborhood of the builtin doesn't work because I'll have access to the builtin node, but not to anything around it. So I can't diagnose, say `&__builtin_counted_by_ref(...)` because I'd have to know its parent node. If you're suggesting that every time we look at a unary op we also check for this builtin, it's not infeasible, given the fact that you could have any number of casts, unary operators, or binary operators between the builtin and the `&`.

Looking at the RHS of an expression is actually one of the reasons why the compilation time went down. If you have something like:

```c
a[0] = a[1] = ... = a[301] = __builtin_counted_by_ref();
```

then you have to process ALL the way down to the builtin call before you can emit a diagnostic.

My point of using the parent map is to simplify everything, and I think it'll do a much better job rather than having to jump through so many hoops that I'm seriously considering closing this bug as WAI (infeasible). There are only a limited number of valid ways to use this builtin. We're libel to hit on any invalid uses quickly.

What I DON'T want to do is have to go through the entirety of SEMA and find every single place that this builtin may end up and put a check there. It's possibly the worst way to add this check.

**Comment by bwendling** [comment]
> (You may need additional things to be tracked so you're able to issue a high-quality diagnostic, but it seems like a design like this could work?)

How does that help at all? It looks like it's storing the node containing the builtin. Do I magically now have access to the whole AST containing that builtin just because I'm using that strange design?

**Comment by rapidsna** [comment]
> you could have any number of casts, unary operators, or binary operators between the builtin and the &

My point is that, then you don't emit an error at the unary operator, but you would emit an error at the binary operator that's immediately using it.

> What I DON'T want to do is have to go through the entirety of SEMA and find every single place that this builtin may end up and put a check there.

But yea, I agree doing this might be a pain. I was suggesting it in case this is still simpler than other complex new way of handling delayed diagnosis.

**Comment by bwendling** [comment]
> The only solution I can think of is that it’d be possible to use a placeholder expression for this

@Sirraide What is a "placeholder expression?" Are there examples of it in Sema? And no, I do **not** want to add a new AST node.

**Comment by Sirraide** [comment]
> > The only solution I can think of is that it’d be possible to use a placeholder expression for this
> 
> @Sirraide What is a "placeholder expression?" Are there examples of it in Sema? And no, I do **not** want to add a new AST node.

Just adding a placeholder type might actually be enough. A ‘placeholder type’ is a type that’s often used in situations where we have some sort of construct that is only valid in very specific circumstances, e.g. if you have a builtin function like `__builtin_memcpy`, it’s still parsed like a regular function, but the only thing you can do with it is call it (e.g. `auto ptr = &__builtin_memcpy;` would be invalid since it’s not *actually* a function). Another example would be Clang’s matrix type extension, which allows indexing using two subscripts, e.g. `a[b][c]`; just a single subscript on its own is invalid (e.g. `auto foo = a[b];`), but we still *parse* it as two subscripts

The way this is implemented is that `__builtin_memcpy` and `a[b]` are assigned a placeholder type (`BuiltinFunctionTy`/`IncompleteMatrixIndexTy` iirc; I don’t remember the exact names). Every place in Sema that deals w/ subexpressions calls `CheckPlaceholderExpr()` (or a variant of it, e.g. `CheckArgsForPlaceholders()`), which diagnoses and rejects any expressions that have placeholder type. Any places that allow certain placeholder types must handle them appropriately before that happens.

So in this case, the way I’m envisioning this working is:
1. The call to `__builtin_counted_by_ref` gets a placeholder type (you’ll probably have to add a new placeholder type for that; we can call it `BuiltinCountedByRefTy` or whatever); 
2. As a result, any attempt to use the builtin as a subexpression of another expression will cause an error; you’ll have to update `CheckPlaceholderExpr()` to actually handle the new placeholder type and issue the diagnostic. 
3. Lastly, in any place where we *do* want to allow the builtin to be used, we have to check for `BuiltinCountedByRefTy`, and then handle it accordingly, and eventually change the type of the expression to be whatever the actual type is supposed to be.

   1. E.g. to allow `*__builtin_counted_by_ref(x) = y;`, the code that builds a unary `*` expression would have to be modified accept arguments of type `BuiltinCountedByRefTy` iff the argument is a (possibly parenthesised) call to the builtin (so we don’t accidentally allow `**__builtin_counted_by_ref(x)`), with the resulting unary expression itself being of type `BuiltinCountedByRefTy`; then, the code that handles assignments checks if its lhs is a dereference expression of type `BuiltinCountedByRefTy`, and if so, changes its type to whatever it’s actually supposed to be and then just lets the rest of the assignment logic do its thing.

   2. Iirc `ActOnParenExpr` *doesn’t* check for placeholders, so `*(__builtin_counted_by_ref(x)) = x;` *should* just work if you do an `IgnoreParens()` before you check whether the argument is a call to the builtin in the dereference code.

   3. The code that builds `if` statements probably also needs to check for the builtin to allow `if (__builtin_counted_by_ref(x)) {}`, in which case you’d just have to change the type of the expression to have the correct pointer type (normally, you’re not supposed to change e.g. the type of an expression after it’s been created, but I think it’s fine in this case).

CC @AaronBallman again in case there are any obvious issues w/ this plan that I missed ;Þ

I arguably haven’t thought too hard as to whether there are any pitfalls with this, but disallowing it everywhere by default (which is what giving it a placeholder type will do automatically) and then allowing it in very specific circumstances seems easier to me at least than doing it the other way around.

If you want to try this approach, I’d probably recommend looking at the code that deals with `IncompleteMatrixIndexTy` (and incomplete matrix index expresions, because iirc those do have a separate AST node, but I don’t think you need a separate AST node for this feature), because there’s probably less code that deals w/ those than e.g. builtin functions, though admittedly, I haven’t checked that in a while.

**Comment by Sirraide** [comment]
The approach I’m proposing would also entail disallowing e.g. `*(size_t*)__builtin_counted_by_ref(x) = y` (updating the code that does casts to handle this builtin as well would probably be possible, but it’s probably a bit more annoying seeing as you could have any number of casts between the dereference and the builtin call). 

However, looking at the test cases we have for this, it’s probably fine to disallow casts (considering that we’re already restricting the use of this as much as we are, I don’t think there’s much of a use case for adding casts here—the only thing that would even make sense semantically is a cast to another pointer type, which is pointless if it’s used as the condition of an `if`, and probably also a bad idea if you then want to assign to it).
