### ISSUE TITLE
clang-19 cannot mangle what clang-17 mangles

### ISSUE THREAD

**Issue by kelbon** [llvm/llvm-project#115990]
I updated the clang version from 17 to 19 on windows and now i get error:
```
error: cannot mangle this template type parameter type yet
```
(no additional info provided)

**Comment by zyn0217** [comment]
Without a reproducer we're also unable to tell what was broken :(

**Comment by efriedma-quic** [comment]
It looks like this is Windows-specific; the Itanium mangler can't generate an error message like this.

https://llvm.org/docs/HowToSubmitABug.html#front-end-bugs has some tools you can use to automatically reduce testcases, if you can't share the original.  But maybe @MaxEW707 has some idea what might trigger this.

CC @rnk @zmodem

**Comment by MaxEW707** [comment]
@kelbon What C++ version are you building against. Notably pre C++20 or C++20?

I have time this weekend to look into this and try to reproduce locally based on the changes made to make the microsoft mangling code more conformant with MSVC in clang 19.

> for example the line number

That is odd. The source range is passed into the error diagnostic. We must be passing in an empty source range. I'll dig into this as well.

**Comment by kelbon** [comment]
> @kelbon What C++ version are you building against. Notably pre C++20 or C++20?
> 
> I have time this weekend to look into this and try to reproduce locally based on the changes made to make the microsoft mangling code more conformant with MSVC in clang 19.
> 
> > for example the line number
> 
> That is odd. The source range is passed into the error diagnostic. We must be passing in an empty source range. I'll dig into this as well.

C++20.
Empty source range may be because its coroutines and some inner compiler generated code ?

This code also produces gcc-14 internal error on 'end translation unit'...

**Comment by MaxEW707** [comment]
@kelbon I haven't been able to find a reproducer yet after going thru the commits that modified the mangling code.

> Its really huge private file with codegen and compile time strings, i tried to minimize it, but it still really big.

If you are able to strip away or replace any internal private details with generic stuff such as replacing strings with random characters or renaming class names that won't leak any private details then even a large reproducer will help me track down what is going awry.

**Comment by kelbon** [comment]
> @kelbon I haven't been able to find a reproducer yet after going thru the commits that modified the mangling code.
> 
> > Its really huge private file with codegen and compile time strings, i tried to minimize it, but it still really big.
> 
> If you are able to strip away or replace any internal private details with generic stuff such as replacing strings with random characters or renaming class names that won't leak any private details then even a large reproducer will help me track down what is going awry.

If it possible, may be improve diagnostic or for example replace it with segfault, so i can run it on my code and get preprocessed sources + right place where code fails?
Anyway i will try to reduce example, but its not easy

**Comment by MaxEW707** [comment]
@kelbon I pushed a local branch here off of 19.1.3, https://github.com/MaxEW707/llvm-project/tree/mew/assert-invalid-mangle-1913, which turns all the diagnostic error paths into an `llvm_unreachable`.

If you can build that with assertions enabled then we should get a nice stack trace with the current parser tokens and the current decl we are trying to mangle :).

**Comment by kelbon** [comment]
> @kelbon I pushed a local branch here off of 19.1.3, https://github.com/MaxEW707/llvm-project/tree/mew/assert-invalid-mangle-1913, which turns all the diagnostic error paths into an `llvm_unreachable`.
> 
> If you can build that with assertions enabled then we should get a nice stack trace with the current parser tokens and the current decl we are trying to mangle :).

im not sure how to build clang under windows, im using

cmake -S llvm -B build -G "Ninja" -DLLVM_ENABLE_PROJECTS='clang' -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_BUILD_TYPE=Debug -DLLVM_HOST_TRIPLE=x86_64 -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_INSTALL_PREFIX=../install

+ ninja clang

results in 
```cpp
clang: error: unable to execute command: program not executable
clang: error: linker (via gcc) command failed with exit code 1 (use -v to see invocation)
```
i cannot set -fsyntax-only in cmake, because it checks compiler

**Comment by kelbon** [comment]
Okay after some workarounds i rebuild clang and get assertion failure (before type mangling)
```cpp
Assertion failed: isa<UsingDecl>(Cand.getDecl()) && "illegal Kind of operator = Decl", file D:/llvm_mangle_error/llvm-project/clang/lib/Sema/SemaLookup.cpp, line 3483
```

@MaxEW707 where i can send all 230k preprocessed lines and full error log for you?

**Comment by kelbon** [comment]
anyway:
error log for compiler run for several targets:
src/long_poll.cpp.obj
src/bot.cpp.obj 
src/telegram.cpp.obj

all failed with assert while parsing Update struct (but with different call stack)

 Assertion failed: isa<UsingDecl>(Cand.getDecl()) && "illegal Kind of operator = Decl", file D:/llvm_mangle_error/llvm-project/clang/lib/Sema/SemaLookup.cpp, line 3483

https://pastebin.com/SY4bQs3S

link for downloading files with preprocessed code:
https://gofile.io/d/MZ79hE

**Comment by MaxEW707** [comment]
@kelbon Can you attach the preprocessed cpp source code file(s) here on github. In the comment box there should be an icon with a paper clip to attach files. Thanks :).

**Comment by kelbon** [comment]
@MaxEW707 

> We don’t support that file type.
> Try again with GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, > JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP.

Thats why i added extension .txt for all files

[long_poll-571c97.sh.txt](https://github.com/user-attachments/files/17792030/long_poll-571c97.sh.txt)
[bot-f6b5c9.cpp.txt](https://github.com/user-attachments/files/17792026/bot-f6b5c9.cpp.txt)
[bot-f6b5c9.sh.txt](https://github.com/user-attachments/files/17792028/bot-f6b5c9.sh.txt)
[long_poll-571c97.cpp.txt](https://github.com/user-attachments/files/17792029/long_poll-571c97.cpp.txt)
[telegram-774a11.sh.txt](https://github.com/user-attachments/files/17792035/telegram-774a11.sh.txt)
[telegram-774a11.cpp.txt](https://github.com/user-attachments/files/17792036/telegram-774a11.cpp.txt)

**Comment by MaxEW707** [comment]
@kelbon @efriedma-quic I managed to get a minimal reproducer for the "Assertion failed: isa<UsingDecl>(Cand.getDecl()) && "illegal Kind of operator = Decl", file F:\llvm-project\clang\lib\Sema\SemaLookup.cpp, line 3483" assertion.

[godbolt for the reproducer](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIAMykrgAyeAyYAHI%2BAEaYxCBmXKQADqgKhE4MHt6%2BASlpGQKh4VEssfGJtpj2jgJCBEzEBNk%2BfoF2mA6Z9Y0ExZExcQlJCg1NLbntY31hA2VDiQCUtqhexMjsHASYLMkG2yb%2BbgQAnsmMrJgA1AAqh9gmGgCCo8ReDlcWTEqPTyYA7FZngCACKHIF/Z7bXb7TCHY5nC5sAB0qNuiIU91%2Br3eBCuILieAAbph0FcQFdksRiUxtp9vnCjjcMfdUcjfgCIckvNFaHhkCBfldhVcvOkjPSfkyWf5sCAQKhzsRaSRDiC2eChSKCdSSehzAA2K6KuIq4hqiBoBijfGEvWG40EBBxRZa4Wct0i4XETAENYMK4AKideEx/ghXtBHP%2BYPDHOeOI%2BADFUKgrh6Y5qEwQ3h85Ml0LS4cDAZ6dcTSfCU6h7ldCw0s39M%2BGOMtaJwAKy8PwcLSkVCcNzWaxXBSrdbXcz%2BHikAiaVvLADWCQ7yP8/g7/wN/y4/03BoAHABOJLtjiSbvz/ucXgKEAaWfz5ZwWAwRAoVC7OhxciUNBf%2Bh4mQAwjAAfW%2BJQmkyBRQJzLwGEXPg6G2Yg7wgaIr2iMJGhOTgZyw5hiBOAB5aJtE6OduF4f82EEYiGFoXDe14LBoi8YA3DEWg7yo0gsBYQxgHEZi%2BLwH0uhJHi%2B0wVROi8bY8N4MJtjPPs%2BWiZUiI8LArxzPAWEU0gSWIaI0kwAkBKMPkjCfPgDGABQADU8EwAB3Yjzh7Gd%2BEEEQxHYKQZEERQVHUETdFPQSUGHSx9DwaI70gZZFVqa1OAAWlGfV/BBUxLGsXdeFQYzqSwRKIGWDoumcCBXAmPwkhCWZSnKPRUnSVL6ragpUv6FqhhGaoKO6aYusGmoRt6PrBniEZRs8Vo9FGKbmpmiRKvHDZ1v0TtLxEgcOCuVQDwNdKDUkK5gMEq4IAguJUoUK44IQxYbtwQgSHTMxp0WXhKK0RYlwSSQ1w0DRJAPDsNChiGpA7Hbz14AyzDMZEzA0A9/n8f4TskDR/i3f5SB7PsDtve9H2Y583wgJB/2Sb8yAoS1PwZwCUBA4AuAPLg7qaJDaBQtCMJEgicMMsWiNI8iHEMmjGAIejGKvVj2M42huMM/jBOEvt8HExxJKvGS5IU3jlOqK91M0k5tM2Ps9IM3jjNMpQLJ1sJQCpuymAc5y3I8xhDJ84RRHEQKQ5CtQr10aROei/LYvU8rkuSB6MqytU8qsSxCv7Eq8DK%2BBKqG6q/Fqhh3AW3JGsr6b5lm/IOsyMam8KBh69a8bhrqeacgaqoJt7laSjWubelb5amk7gaNrWLauDbXbiavA6jpOs6LquiVueRLhkQ0G6%2BYe16IHeohiC%2Bn6/qfZZnSYLB4gqhGL1IAz/FR/w8e5rczCPDs8b/GkCTIqN5bAU3%2Bq2UgL53z00Zr%2BFmAEhjby5ieY%2BAshaUBFn2SWTF8LYSlmRCictPy0UVgxJietMBsQ4lxHiM5tZWXtixMSw0jYiRNsgeSmwZwW1Urwa2OE7a6WpE7GcLszLuysp7WyVB7JORcu5TywdZB%2BXDtISOSho7hRAPDeO2drBxQSsXfsadoIZwINlXKMULB52KnEUqmAU6Dx7uXOq1cB5NVHg3bqzcBCt3au3GejcqqpR6OMDxS1S5hOmMEpafdFrj2nqtHxi8VjzwCkvDgXYV77U4OvU651LqcyuFwI8e8D5HwUJBE%2Bb18AXyvovG%2BVM76YAfkMZ%2BZ5X4GUkKuXpXB8a9I0AafwPMOwHlyaTMBd4HyQMBqQZcZgQYGnOt9MwB4lnfQGUeA0CN/B7SmRwZpANoE0xpnTVm8DmZwPZlzSQZgMFxGFphAheDeC4OlsQ3i8s6IUJVtQtWdCtY7B1sw0SBsKxSV4Jw7hhk%2BFW3ijbYRIlHaGQkW7EF0ibLezkb7BRAdlG8RDmogKGjZBRzCn2XQgR9E2KMc4lK5iOCZUsVnGxdiC5FySi4suLhK6ty8XMLubdOqRKSIE3qKThWhMmhE/uUSh4MHCTMbx0qEk11sLEqVs90kTm2meHJIDryHWOoUi6wBkDIFKSDMwdSPqXynE0ymAMgbrjXOuD1nrPW7K6UjXRD4jVk3AbM2yMDaYfiQUzP8lz2ZEmQMkZIoEiRlNAnjUCjkhC7lAgM0CqhzqPNQlgl5hE3mkA%2BUQ2W3zSEKyVpQliALaEa3ofWyyQkwX6zYU4wyMKza8MEJbESgitIYB4X9URaK4iu3MpioSMicXyP9kooORLVFh1JUFeQWjKU6ASPoKKBik7xQZWYgQPEAD0WUE451sf8IqnKu3cplTVdx8ra7oDieKnqLcxUisyB%2BnlMSJ4/qfUqrVqqBqaqA6%2ByDyTwOzTnnqtJBqDmgJNUUlgCg41XGTeUvGVwM27j3ofM%2B9TPqOt%2Bs6hcpB76P0oFk7p/rJmofJiGlpCyVx7JQ8a45UCw0XMjQgm5yDOa7g0OgmggsnlFtFq8iWrzPmVpnD88hysRKq0bZrXijC20q1YRJLtHDZJcN7Upft/CjFIpHSI/SE6TKSJndZL2JzcV%2B0UYHLyvBiVrokGS4KW6Y4gB9fuulycTGMtPWA%2BxxBHHOJA3yqu0HBX9UbhK790HUtFG1SE6JsrmjAZy8PWDQqINTzy9B0rH6EMLyyYa1e%2BTTWb2KddQjGg95VJqdBU%2B58yNbIo3MoGZg9GcFfoG6ZEDb4IzMFxoN/WjJPMyCASQQA%3D%3D)
```
template<typename T>
struct Base
{
};

template<typename... Types>
struct Derived : private Base<Types>...
{
public:
    using Base<Types>::operator=...;
    Derived& operator=(const Derived& other)
    {
        return *this;
    }
};

struct Foo {};
struct Update
{
    Derived<Foo> data;
};
```

It appears the assertion hit was a red herring and is unrelated to the mangling issue here.
That is the assertion is always fired in debug builds of clang going back to 17.x.x.
Since release builds of clang compile the code fine the assertion is no longer valid. I'll make a separate github issue sometime next week for this assertion failure.

Now knowing that the assertion is an unrelated issue I can workaround that and dig into the mangling issue. I'll do that over the next week :).

**Comment by MaxEW707** [comment]
@kelbon I can't reproduce the invalid mangling on the 3 source files provided with the faulty assertion removed.

I updated my local branch here, https://github.com/MaxEW707/llvm-project/tree/mew/assert-invalid-mangle-1913, to remove said faulty assert. If you can pull that down, rebuild clang, and then build your code so we can hopefully get a stack trace of the invalid mangling that would be greatly appreciated. Thanks for all the help so far in tracking this issue down :).

**Comment by kelbon** [comment]
...

https://pastebin.com/FDKNxGPj

[test_oneof-ce9437.cpp.txt](https://github.com/user-attachments/files/17802276/test_oneof-ce9437.cpp.txt)
[test_oneof-ce9437.sh.txt](https://github.com/user-attachments/files/17802277/test_oneof-ce9437.sh.txt)

**Comment by MaxEW707** [comment]
Here is a minimal reproducer. https://godbolt.org/z/7nPvac68a

```
namespace ns0
{

template <typename T>
concept test_api_type = requires(const T& t)
{
    { T::test([](){}) };
};

template<typename T>
struct test {};

template <test_api_type T>
struct test<T> {};

} // namespace ns0

struct Baz
{
    template<typename F>
    static constexpr decltype(auto) test(F&&) {}
};

void test()
{
    ns0::test<Baz> t;
}
```

Working on a fix. Should be up sometime this week :).

**Comment by kelbon** [comment]
> Here is a minimal reproducer. https://godbolt.org/z/7nPvac68a
> 
> ```
> namespace ns0
> {
> 
> template <typename T>
> concept test_api_type = requires(const T& t)
> {
>     { T::test([](){}) };
> };
> 
> template<typename T>
> struct test {};
> 
> template <test_api_type T>
> struct test<T> {};
> 
> } // namespace ns0
> 
> struct Baz
> {
>     template<typename F>
>     static constexpr decltype(auto) test(F&&) {}
> };
> 
> void test()
> {
>     ns0::test<Baz> t;
> }
> ```
> 
> Working on a fix. Should be up sometime this week :).

Thanks, i workaround [] {} lambda in concepts and runs code. Its interesting to observe how benchmark runs faster with every new clang version (specially coroutines)

**Comment by MaxEW707** [comment]
For reference I bisecting the PR that breaks the MSVC mangling to this: https://github.com/llvm/llvm-project/pull/83997

https://godbolt.org/z/xYYPM4noY
Notice in the clang 19 godbolt we get an extra template instantation in the AST that we end up mangling.
```
`-CXXMethodDecl 0xcb71098 <line:18:5, line:21:5> line:18:27 referenced constexpr test2 'void (Widget<type-parameter-0-0>::(lambda at <source>:4:16) &&)' implicit_instantiation static implicit-inline
|     |-TemplateArgument type 'Widget<type-parameter-0-0>::(lambda at <source>:4:16)'
```
The `TemplateTypeParamType` of `type-parameter-0-0` which we don't implement currently breaks us.

I am still digging if this extra mangling when doing the concept constraint is actually intended or an intended byproduct.

@zyn0217 if you have any insight :).
