### ISSUE TITLE
Clang crash with -Wunsafe-buffer-usage on assertion failure: const ASTRecordLayout &clang::ASTContext::getASTRecordLayout(const RecordDecl *) const: Assertion `D && "Cannot get layout of forward declarations!"' failed.

### ISSUE THREAD

**Issue by ZequanWu** [llvm/llvm-project#116286]
Trunk clang crashes with `-Wunsafe-buffer-usage`: https://godbolt.org/z/Pjj413W68 and https://godbolt.org/z/j4hnY3eEz.

#91991 (reverted) introduced the same crash with `-Wunsafe-buffer-usage`: https://godbolt.org/z/vcv8d6sYr, which is likely due to the same underlying issue.

**Comment by danakj** [comment]
To help make things clear, https://github.com/llvm/llvm-project/pull/91991did not introduce the crash, it exposed the crash in Chromium code because it ran the analysis machinery on code inside field initializers. The crash happens outside of field initializers too, but the problematic code is only in a field initializer in Chromuim.

Once the underlying issue is fixed, the revert of https://github.com/llvm/llvm-project/pull/91991 can be reverted to reland it, as there's no related bug in that PR afaik.

**Comment by danakj** [comment]
@haoNoQ I am no longer working in Chromium so I won't have a lot of time to follow up here. And the bug appears to be in the handling of casts in AnalysisBasedWarnings at https://github.com/llvm/llvm-project/blob/7d20ea9d32954e8e5becab8495fa509a3f67b710/clang/lib/Sema/AnalysisBasedWarnings.cpp#L2271-L2277 Could you handle triaging this?

**Comment by ZequanWu** [comment]
A further reduced repro for https://godbolt.org/z/vcv8d6sYr: https://godbolt.org/z/1vn6adWhc

**Comment by ziqingluo-90** [comment]
@danakj  I will work on it.

**Comment by ziqingluo-90** [comment]
> https://godbolt.org/z/1vn6adWhc

Hi @ZequanWu,  I'd prefer to keep the assumption that `std::array::data()`/`std::span::data()` always return a pointer.   In your example, it returns an `int`.   Is it coming from any real code where `std::array::data()` returns a non-pointer?

**Comment by ZequanWu** [comment]
> > https://godbolt.org/z/1vn6adWhc
> 
> Hi @ZequanWu, I'd prefer to keep the assumption that `std::array::data()`/`std::span::data()` always return a pointer. In your example, it returns an `int`. Is it coming from any real code where `std::array::data()` returns a non-pointer?

I think it's just reduced by creduce. Changing data() to return a pointer also cause crash: https://godbolt.org/z/coT53Kh5j

**Comment by ziqingluo-90** [comment]
> > > https://godbolt.org/z/1vn6adWhc
> > 
> > 
> > Hi @ZequanWu, I'd prefer to keep the assumption that `std::array::data()`/`std::span::data()` always return a pointer. In your example, it returns an `int`. Is it coming from any real code where `std::array::data()` returns a non-pointer?
> 
> I think it's just reduced by creduce. Changing data() to return a pointer also cause crash: https://godbolt.org/z/coT53Kh5j

Yup,  it is not the cause of the crash.  For the crash I have a fix here: https://github.com/llvm/llvm-project/pull/116433.  It is because we were trying to get type size from incomplete types.

What I was talking about above is that your original example will hit an assertion violation after the fix.  Because we assume `std::array::data()` always return pointers.   We assume these hardened(-able) containers/views are standard otherwise many other places in the code need change.

**Comment by ZequanWu** [comment]
> > > > https://godbolt.org/z/1vn6adWhc
> > > 
> > > 
> > > Hi @ZequanWu, I'd prefer to keep the assumption that `std::array::data()`/`std::span::data()` always return a pointer. In your example, it returns an `int`. Is it coming from any real code where `std::array::data()` returns a non-pointer?
> > 
> > 
> > I think it's just reduced by creduce. Changing data() to return a pointer also cause crash: https://godbolt.org/z/coT53Kh5j
> 
> Yup, it is not the cause of the crash. For the crash I have a fix here: #116433. It is caused by trying to get the type size from an incomplete type.
> 
> What I was talking about above is that your original example will hit an assertion violation after the fix. Because we assume `std::array::data()` always return pointers. We assume these hardened(-able) containers/views are standard otherwise many other places in the code need change.

Verified that `std::array::data()` returns a pointer  in the original crash source code.
