### ISSUE TITLE
RISC-V va_end generates what seems to be unnecessary code

### ISSUE THREAD

**Issue by davidben** [llvm/llvm-project#116418]
RISC-V ABI docs say that `va_end` is a no-op:

> The va_copy macro is a single pointer copy and the va_end macro performs no operation.

https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-cc.adoc#va_list-va_start-and-va_arg

But LLVM seems to generate the following code:

```
void nop(va_list l) { }
void call_va_end(va_list l) { va_end(l); }

nop(void*):
        ret

call_va_end(void*):
        addi    sp, sp, -16
        sd      a0, 8(sp)
        addi    sp, sp, 16
        ret
```

https://godbolt.org/z/P73hcfvoh

I don't know RISC-V at all, but at a glance that seems to be doing nothing useful? It seems to be allocating 16 bytes on the stack, saving `a0`, and then deallocating those bytes.

GCC does not do this: https://godbolt.org/z/Y1d833vrE

**Comment by topperc** [comment]
Mips seems to do the same thing. So it looks like something common in targets that use void* for va_list.

**Comment by pfusik** [comment]
At first this looks like a missing optimization for `va_end`. It's on many architectures besides RISC-V, including ARM 32-bit, MIPS and WebAssembly. On M68k it's not seen when calling with a `va_list` parameter, but still [with a local variable](https://godbolt.org/z/3bbGvhaYc).

This happens because `va_list` is passed to `va_end` via reference, i.e. `va_list` needs to reside in memory.
[CodeGenFunction::EmitBuiltinExpr](https://github.com/llvm/llvm-project/blob/53e9eee0e2c9587fc7a1e7b5f64ba2a935f58e0a/clang/lib/CodeGen/CGBuiltin.cpp#L3370) puts `va_list` on stack:

```
  %l.addr = alloca ptr, align 8
  store ptr %l, ptr %l.addr, align 8, !tbaa !9
  call void @llvm.va_end.p0(ptr nonnull %l.addr)
```

`call void @llvm.va_end.p0` is lowered to `ISD::VAEND` which is then [removed](https://github.com/llvm/llvm-project/blob/53e9eee0e2c9587fc7a1e7b5f64ba2a935f58e0a/llvm/lib/CodeGen/SelectionDAG/LegalizeDAG.cpp#L3027), but the stack copy of `va_list` remains.

`va_end` is normally used together with `va_start` or `va_copy` and there is no extra code emitted in this case: see [my_printf](https://godbolt.org/z/3bbGvhaYc). Functions with a `va_list` argument should call `va_arg` but not `va_end`.

The C standard says that `va_end` shouldn't be called alone:

> If there is no corresponding invocation of the `va_start` or `va_copy` macro, or if the `va_end` macro is not invoked before the return, the behavior is undefined.

Closing because the only missing optimization is apparently for UB scenario.

**Comment by davidben** [comment]
Ah good call. There does seem to be extra code emitted in this case https://godbolt.org/z/q3vvM3hhn, but it is a very silly case and probably won't impact any real code.

**Comment by pfusik** [comment]
Yes, `va_start` + `va_end` is legit, but not useful.
