### ISSUE TITLE
[clang] error: constexpr variable must be initialized by a constant expression

### ISSUE THREAD

**Issue by itou-fj** [llvm/llvm-project#116969]
When I compiled this code with clang, it returned a compilation error.
Other compilers (gcc, msvc, etc.) can compile without errors.

[Compiler Explorer](https://godbolt.org/z/ErhdPo7Me)

Code:
```c++
class Apple {
 public:
  constexpr Apple() {}
  constexpr operator int() { return 555; }
};

class Meal {
 public:
  //constexpr Meal(Apple apple) {} // OK
  constexpr Meal(int apple) {}     // NG
};

class Dinner : Meal {
 public:
  Apple apple_;
  constexpr Dinner() : apple_(), Meal(apple_) {}
};

int main() {
  constexpr Dinner my_dinner;
  return 0;
}
```

Error Message:

```
<source>:18:39: warning: field 'apple_' is uninitialized when used here [-Wuninitialized]
   18 |   constexpr Dinner() : apple_(), Meal(apple_) {}
      |                                       ^
<source>:22:20: error: constexpr variable 'my_dinner' must be initialized by a constant expression
   22 |   constexpr Dinner my_dinner;
      |                    ^~~~~~~~~
<source>:18:39: note: member call on object outside its lifetime is not allowed in a constant expression
   18 |   constexpr Dinner() : apple_(), Meal(apple_) {}
      |                                       ^~~~~~
<source>:22:20: note: in call to 'Dinner()'
   22 |   constexpr Dinner my_dinner;
      |                    ^~~~~~~~~
1 warning and 1 error generated.
Compiler returned: 1

```

**Comment by zygoloid** [comment]
This is a bug in the other compilers, not in Clang. The field initializers in the constructor are in the wrong order, and the language rules reorder them to:
```c++
  constexpr Dinner() : Meal(apple_), apple_() {}
```
And `apple_` is implicitly converted to `int`, so this is equivalent to:
```c++
  constexpr Dinner() : Meal(apple_.operator int()), apple_() {}
```
This [has undefined behavior](https://eel.is/c++draft/basic.life#7.2) because it's performing a member function call on `apple_` outside its lifetime, and so is [not constant](https://eel.is/c++draft/expr.const#5.8). Clang detects that; the other compilers seemingly fail to do so. (Note that they accept even if the constructor is rewritten as described above.)

Closing as this is not our bug.
