### ISSUE TITLE
__builtin_bit_cast does not allow bitcasting from nullptr_t

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#117166]
`nullptr_t` is not a pointer type, see the `static_assert` in https://godbolt.org/z/vjq1Tse7W

In this example, the second bitcast works, but the first one does not:
```c++
typedef __UINTPTR_TYPE__ uintptr_t;
constexpr uintptr_t A = __builtin_bit_cast(uintptr_t, nullptr);


typedef decltype(nullptr) nullptr_t;
constexpr decltype(nullptr) N = __builtin_bit_cast(nullptr_t, (uintptr_t)12);
static_assert(N == nullptr);
```
The output suggests some bogus reason though:

```console
./array.cpp:26:21: error: constexpr variable 'A' must be initialized by a constant expression
   26 | constexpr uintptr_t A = __builtin_bit_cast(uintptr_t, nullptr);
      |                     ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./array.cpp:26:25: note: indeterminate value can only initialize an object of type 'unsigned char' or 'std::byte'; 'unsigned long' is invalid
   26 | constexpr uintptr_t A = __builtin_bit_cast(uintptr_t, nullptr);
      |                         ^
```

GCC accepts the first one, but not the second. I opened https://gcc.gnu.org/bugzilla/show_bug.cgi?id=117727 for that.

**Comment by tbaederr** [comment]
I guess this is on purpose actually: https://github.com/llvm/llvm-project/blob/a12e79a85fc18d535c58f2c82d2b2e80586e43d7/clang/lib/AST/ExprConstant.cpp#L7216-L7218

**Comment by tbaederr** [comment]
Paging @frederick-vs-ja for spec knowledge, since this isn't as clear-cut as I thought, according to the gcc bug linked above.

**Comment by zygoloid** [comment]
In Clang, we treat `nullptr_t` as having no bits in its value representation. (This choice is not specified by the standard, and is instead up to the implementation -- and part of the ABI, but sadly psABIs don't seem to actually specify it.) For example:
```c++
struct X {
  X() {}
  decltype(nullptr) p;
};
X f() { return X(); }
```
... does not store zero bits to the `p` field within `X`, instead leaving it indeterminate. (Some other uses of `nullptr` *do* store zero bits; I think that's just bad codegen rather than being intentional.)

Because `nullptr_t` has no value bits, `bit_cast` treats its bits as being indeterminate. So I think the behavior observed is correct -- you can `bit_cast` any value *to* `nullptr_t` (because it has no bits in its value representation) but you cannot `bit_cast` any type with a non-empty value representation *from* `nullptr_t`.

**Comment by tbaederr** [comment]
That makes sense and matches what Jakub said in the gcc bug. Closing this then, seems clang is doing the right thing.
