### ISSUE TITLE
[Clang][AST Matchers] Missing attributedStmt AST matcher

### ISSUE THREAD

**Issue by DistinctWind** [llvm/llvm-project#117879]
Currently I'm playing with AST Transformer and I want to transform certain attributed statements. In the first step, I need to match the attributed statements. However, I didn't find any AST Matcher that will match AST Nodes `AttributedStmt`, `AnnotateAttr` and its corresponding statement in ASTMatchers.h.

I found a [code review](https://reviews.llvm.org/D120949?id=418341#inline-1163697) from the old llvm review platform, which is well discussed and approved. But it doesn't appear in current llvm 20 git build and I can't find any related Github Issue.

I wounder if it's forgot for some reason. Clang 20 now [supports](https://github.com/llvm/llvm-project/pull/110334) adding custom attribute in a plugin, so I think it's also a point to add support for matching `AttributedStmt` nodes.

**Comment by AaronBallman** [comment]
Generally speaking, we only add ast matchers to ASTMatchers.h when there's enough uses of it to justify the cost (because that file is extremely expensive to compile due to the amount of template instantiations it generates). Otherwise, we let folks define local matchers (e.g., https://github.com/llvm/llvm-project/blob/89b31c9c32f2cd2c038fe2b12d9c66a53c779fc1/clang-tools-extra/clang-tidy/bugprone/OptionalValueConversionCheck.cpp#L22) until there is enough reason to surface the matcher more generally.

Would a local matcher suffice for you?

**Comment by DistinctWind** [comment]
So there's a way to define local AST matcher, that will be great.

I'll try to learn how to define a local AST matcher that finds an `AttrubutedStmt`, and later post that working code snippet here to help others who also come up with this problem.

**Comment by AaronBallman** [comment]
> So there's a way to define local AST matcher, that will be great.
> 
> I'll try to learn how to define a local AST matcher that finds an `AttrubutedStmt`, and later post that working code snippet here to help others who also come up with this problem.

FWIW, that matcher would look like:
```
extern const internal::VariadicDynCastAllOfMatcher<Stmt, AttributedStmt> attributedStmt;
```
I'm going to close this issue as not planned, but if there's a need to upstream this matcher, feel free to reopen the issue with more details about those needs.
