### ISSUE TITLE
Allow elemental functions in Fortran REDUCE intrinsic function

### ISSUE THREAD

**Issue by ivan-pi** [llvm/llvm-project#118610]
Flang 20.0.0 does not allow elemental functions in the `REDUCE` function:
```fortran
real :: c(3), res
c = [1,2,3]
res = reduce(c,operation=my_add1) ! works
print *, res
res = reduce(c,operation=my_add2) ! error: Non-intrinsic ELEMENTAL procedure ...
print *, res
contains
    pure real function my_add1(a,b)
        real, intent(in) :: a, b
        my_add1 = a + b
    end function
    elemental real function my_add2(a,b)
        real, intent(in) :: a, b
        my_add2 = a + b
    end function
end 
```

According to J2/24-007, section 16.9.173, the operation should be a pure function. According to section 15.7 this means it could be a function with prefix-spec `PURE`, `SIMPLE`, or `ELEMENTAL` (but no `IMPURE`).

**Comment by ivan-pi** [comment]
This would also apply to pure intrinsic procedures, e.g.

```fortran
use, intrinsic :: iso_fortran_env
integer :: c(3)

c = [int(b'1'),int(b'10'),int(b'100')]

print *, iany(c) == int(b'111')
print *, reduce(c,my_or) == int(b'111')
print *, reduce(c,ior) == int(b'111')    ! error

contains
    pure integer function my_or(a,b)
        integer, intent(in) :: a, b
        my_or = ior(a,b)
    end function
end 
```

**Comment by klausler** [comment]
F'2023 C1533: "A nonintrinsic elemental procedure shall not be used as an actual argument." invalidates the first example.

**Comment by ivan-pi** [comment]
Thanks. I missed that named constraint. It seems like a nuisance to need two procedures (one elemental and one `pure` just for `reduce`) when a single could do. Perhaps the standards committee idea was the the reduce operator would usually be a pure [internal] procedure declared nearby the point of use, so a smart compiler could generate a custom reduce on the spot.

**Comment by klausler** [comment]
An implementation can use special calling conventions for `ELEMENTAL` procedures to accommodate vectorized arguments and such, so they just don't interact well with dummy procedures.  A runtime has to be careful to note `ELEMENTAL` finalizers and deal with them as special cases, too.

**Comment by klausler** [comment]
The second example isn't valid, either, because `IOR` is not an unrestricted specific intrinsic function, and thus cannot appear as an actual argument.  But if you adjust it to an implicitly typed undeclared external function name, or to an unrestricted specific intrinsic (e.g. 'IDIM`, although that's not a meaningful reduction), the example should conform, and seems to expose a bug, which I'll fix.

**Comment by klausler** [comment]
```
program main
  call wantsFunc(mod)
  call wantsFunc(ifoo)
 contains
  integer function foo(a,b)
    integer, intent(in) :: a, b
    foo = mod(a,b) + ifoo(a,b)
  end
end

subroutine wantsFunc(intf)
  print *, intf(1,2)
end
function ifoo(j,k)
  ifoo = j + k
end
```

**Comment by klausler** [comment]
Update: It turns out (15.5.2.10 p7) that an external procedure cannot be passed as an actual argument without having an explicit interface declaration or an explicit `EXTERNAL` attribute.  So there's a bug only with unrestricted specific intrinsics.

"If an external procedure or a dummy procedure is used as an actual argument, its interface shall be explicit or it shall be explicitly declared to have the EXTERNAL attribute."

Neither can an (unrestricted specific) intrinsic function be passed as an actual argument without having an explicit `INTRINSIC` attribute; see 8.5.1 p2.

So there isn't a bug remaining to be fixed here, as far as I can tell.  Please close this issue if you agree, or comment if you do not.

**Comment by ivan-pi** [comment]
There are few unrestricted specific functions dealing with two real arguments (for instance `atan2` and `sign`). Would those count:
```fortran
real :: a(3), res
intrinsic :: sign
a = [1,-2,3]
res = reduce(a,operation=sign)
print *, res
end
```
On the other hand the description of `REDUCE`, section 16.9.173, says
> OPERATION should implement a mathematically associative operation.

**Comment by klausler** [comment]
I don't understand the question, sorry.  Your latest example does seem to compile and run.

**Comment by ivan-pi** [comment]
`dim` and `ddim` aren't working for me with real types, nor is `mod`. But `sign` and `atan2` work. This is with commit `0a96161beb161933e64e188bfb0754df494c3a58`.

But since none of these are mathematically associative it doesn't make sense anyways. I'm happy to put this issue to rest. Sorry for any confusion or time wasted.
