### ISSUE TITLE
[libc][docs] fix link for implementation status of libc headers

### ISSUE THREAD

**Issue by Sh0g0-1758** [llvm/llvm-project#119059]
After the doc reorg in this [PR](118836), the implementation status for the complex header is available [here](https://libc.llvm.org/headers/complex.html) but on the [main page](https://libc.llvm.org/) the column for complex.h status still directs us [here](https://libc.llvm.org/complex.html), which is wrong. This is true for all the headers. The links for the implementation status pages on the main page need to be fixed.

**Comment by nickdesaulniers** [comment]
I don't follow.  The PR you first link to also updated the main page so that complex.h is NOT listed on the column on the left hand side. Maybe you need to clear your browser cache for that page (ctrl+shift+r), or that page was not up to date when you last viewed it?

I think this issue is no longer reproducible, so closing as such, but please do reopen if I misunderstood.

**Comment by Sh0g0-1758** [comment]
the page was probably not up to date when I viewed it.

**Comment by nickdesaulniers** [comment]
No worries! Always best to file a bug when you see something; they don't cost us anything! :) Then we can sort it out later in a distinct thread. Thanks for reporting it anyways.
