### ISSUE TITLE
[lld][MachO] llvm::upper_bound called on not correctly sorted input

### ISSUE THREAD

**Issue by karka228** [llvm/llvm-project#120559]
When building llvm-project with -DLLVM_ENABLE_EXPENSIVE_CHECKS=ON with a recent libstdc++ (e.g. from gcc 13.3.0) the testcases:
```
  lld :: MachO/local-alias-to-weak.s
  lld :: MachO/symtab.s
  lld :: MachO/weak-definition-gc.s
```
fail with the message:

```
.../include/c++/13.3.0/bits/stl_algo.h:2100:
In function:
    _ForwardIterator std::upper_bound(_ForwardIterator, _ForwardIterator, 
    const _Tp &, _Compare) [_ForwardIterator = lld::macho::Defined **, _Tp = 
    unsigned long, _Compare = (lambda at 
    ../../lld/MachO/SymbolTable.cpp:77:15)]

Error: elements in iterator range [first, last) are not partitioned by the 
predicate __comp and value __val.

Objects involved in the operation:
    iterator "first" @ 0x7ffc2bfd9af8 {
    }
    iterator "last" @ 0x7ffc2bfd9af0 {
    }
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /repo/llvm-project/llvm/build/bin/ld64.lld -arch x86_64 -platform_version macos 11.0 11.0 -syslibroot /repo/llvm-project/lld/test/MachO/Inputs/MacOSX.sdk -lSystem -fatal_warnings -lSystem -dylib /repo/llvm-project/llvm/build/tools/lld/test/MachO/Output/local-alias-to-weak.s.tmp/no-subsections.o /repo/llvm-project/llvm/build/tools/lld/test/MachO/Output/local-alias-to-weak.s.tmp/local-then-weak.o -o /repo/llvm-project/llvm/build/tools/lld/test/MachO/Output/local-alias-to-weak.s.tmp/nosub-sub
 #0 0x000055af1d9c8706 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/repo/llvm-project/llvm/build/bin/ld64.lld+0x4d89706)
 #1 0x000055af1d9c60ce llvm::sys::RunSignalHandlers() (/repo/llvm-project/llvm/build/bin/ld64.lld+0x4d870ce)
 #2 0x000055af1d9c8f79 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007efebf8c7cf0 __restore_rt (/lib64/libpthread.so.0+0x12cf0)
 #4 0x00007efebe980acf raise (/lib64/libc.so.6+0x4eacf)
 #5 0x00007efebe953ea5 abort (/lib64/libc.so.6+0x21ea5)
 #6 0x000055af223cfa43 (/repo/llvm-project/llvm/build/bin/ld64.lld+0x9790a43)
 #7 0x000055af1df2aab1 transplantSymbolsAtOffset(lld::macho::InputSection*, lld::macho::InputSection*, lld::macho::Defined*, unsigned long, unsigned long) SymbolTable.cpp:0:0
 #8 0x000055af1df29519 lld::macho::SymbolTable::addDefined(llvm::StringRef, lld::macho::InputFile*, lld::macho::InputSection*, unsigned long, unsigned long, bool, bool, bool, bool, bool) (/repo/llvm-project/llvm/build/bin/ld64.lld+0x52ea519)
 #9 0x000055af1de8a33e void lld::macho::ObjFile::parseSymbols<lld::macho::LP64>(llvm::ArrayRef<lld::macho::LP64::section>, llvm::ArrayRef<lld::macho::LP64::nlist>, char const*, bool) (/repo/llvm-project/llvm/build/bin/ld64.lld+0x524b33e)
#10 0x000055af1de78214 void lld::macho::ObjFile::parse<lld::macho::LP64>() (/repo/llvm-project/llvm/build/bin/ld64.lld+0x5239214)
#11 0x000055af1de77cc8 lld::macho::ObjFile::ObjFile(llvm::MemoryBufferRef, unsigned int, llvm::StringRef, bool, bool, bool, bool) (/repo/llvm-project/llvm/build/bin/ld64.lld+0x5238cc8)
#12 0x000055af1de492dc lld::macho::ObjFile* lld::make<lld::macho::ObjFile, llvm::MemoryBufferRef&, unsigned int, char const (&) [1], bool&>(llvm::MemoryBufferRef&, unsigned int&&, char const (&) [1], bool&) (/repo/llvm-project/llvm/build/bin/ld64.lld+0x520a2dc)
#13 0x000055af1de43090 addFile(llvm::StringRef, LoadType, bool, bool, bool, bool) Driver.cpp:0:0
#14 0x000055af1de40cdd lld::macho::link(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, bool, bool) (/repo/llvm-project/llvm/build/bin/ld64.lld+0x5201cdd)
#15 0x000055af1d9cafbe lld::unsafeLldMain(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, llvm::ArrayRef<lld::DriverDef>, bool) (/repo/llvm-project/llvm/build/bin/ld64.lld+0x4d8bfbe)
#16 0x000055af1d8f6f1b lld_main(int, char**, llvm::ToolContext const&) (/repo/llvm-project/llvm/build/bin/ld64.lld+0x4cb7f1b)
#17 0x000055af1d8f76a6 main (/repo/llvm-project/llvm/build/bin/ld64.lld+0x4cb86a6)
#18 0x00007efebe96cd85 __libc_start_main (/lib64/libc.so.6+0x3ad85)
#19 0x000055af1d8f6cae _start (/repo/llvm-project/llvm/build/bin/ld64.lld+0x4cb7cae)
Aborted (core dumped)
```

The reason for this is that the requirement for calling llvm::upper_bound (std::upper_bound) in function transplantSymbolsAtOffset() in file lld/MachO/SymbolTable.cpp is not fulfilled. The input to std::upper_bound needs sorted vector because it implements binary search to find the value.

**Comment by bjope** [comment]
@int3 , do you know anything about this?

I figure the goal in `transplantSymbolsAtOffset` is to scan to find an iterator for which the symbol->value is greater than `toOff` and insert before that position in the vector.

So the code should be changed like this:

```
  auto insertIt = llvm::upper_bound(toIsec->symbols, toOff,
                                    [](uint64_t off, const Symbol *s) {
-                                      return cast<Defined>(s)->value < off;
+                                      return cast<Defined>(s)->value > off;
                                    });
```

Right now the upper_bound call is undefined since the vector is partitioned with increasing values, but the comparison function is not fulfilling the partitioning rules. And if for example the symbol values in the vector is [0, 1, 2, 3] and we search with `toOff=2` , then the comparison return true already for the first element.
Depending on libcxx implementation we might as well end up inserting at the end, because a binary search starting scanning from the middle would first find that 2<2 being false, and then that 3 < 2 is false, and then it would just return the end iterator indicating that there was no match.
But neither inserting at the front or the end would be correct. Because we want to insert before the symbol with value 3.

**Comment by bjope** [comment]
> Can't reproduce on macOS 15.2. Tried linking against Apple libc++ and against libc++ from the 19.1.6 release. Used current `main` ([93743ee](https://github.com/llvm/llvm-project/commit/93743ee566694d2fcafa3243c03330e86bf9c806)).

But you agree that the code is doing the wrong thing (even without expensive checks)?

**Comment by bjope** [comment]
Just to clarify something about my analysis. The description of this ticket talks about the input to uppper_bound not being sorted correctly. But I don't think that is the problem (I haven't actually seen that myself). Problem is that the comparison function provided to upper_bound is invalid (given the sorting order), so we could end up inserting at the wrong position, resulting in a incorrectly sorted result. Then ofcourse, at a later call to transplantSymbolsAtOffset the input might be wrongly sorted due to transplantSymbolsAtOffset not keeping the sorting order.

The problem can be seen for the lld/test/MachO/symtab.s test case if adding some printouts in transplantSymbolsAtOffset.

```
diff --git a/lld/MachO/SymbolTable.cpp b/lld/MachO/SymbolTable.cpp
index f0a92da8777e..a8a515434c1f 100644
--- a/lld/MachO/SymbolTable.cpp
+++ b/lld/MachO/SymbolTable.cpp
@@ -67,10 +67,20 @@ static void transplantSymbolsAtOffset(InputSection *fromIsec,
                                       InputSection *toIsec, Defined *skip,
                                       uint64_t fromOff, uint64_t toOff) {
   // Ensure the symbols will still be in address order after our insertions.
+  dbgs() << "toISec-symbols: " << toIsec->symbols.size() << "\n";
+  for (const Symbol *s : toIsec->symbols) {
+    dbgs() << "  " << cast<Defined>(s)->value << "\n";
+  }
+  dbgs() << "toOff: " << toOff << "\n";
   auto insertIt = llvm::upper_bound(toIsec->symbols, toOff,
                                     [](uint64_t off, const Symbol *s) {
                                       return cast<Defined>(s)->value < off;
                                     });
+  if (insertIt != toIsec->symbols.end())
+    dbgs() << "insertIt idx: " << std::distance(toIsec->symbols.begin(), insertIt) << "\n";
+  else
+    dbgs() << "insertIt at end\n";
+
```

If running the symtab.s test the output will be:
```
toISec-symbols: 4
  0
  1
  2
  3
toOff: 0
insertIt at end                      <------------ Looks wrong to me! The result here is actually undefined.
toISec-symbols: 4
  0
  1
  2
  3
toOff: 2
insertIt at end                      <------------ Looks wrong to me! The result here is actually undefined.

```

While if swapping the '<' to '>' we get:
```
toISec-symbols: 4
  0
  1
  2
  3
toOff: 0
insertIt idx: 1                              <-------- We should insert before second element (between 0 and 1)
toISec-symbols: 4
  0
  1
  2
  3
toOff: 2
insertIt idx: 3                               <-------- We should insert before second element (between 2 and 3)
```

**Comment by carlocab** [comment]
> > Can't reproduce on macOS 15.2. Tried linking against Apple libc++ and against libc++ from the 19.1.6 release. Used current `main` ([93743ee](https://github.com/llvm/llvm-project/commit/93743ee566694d2fcafa3243c03330e86bf9c806)).
> 
> But you agree that the code is doing the wrong thing (even without expensive checks)?

Yes, I agreed with your analysis with a cursory inspection, and your follow-up comment with debugging output removed any uncertainty I had.

The fix seems simple enough, but it would be nice to add a test to avoid this regressing.

**Comment by bjope** [comment]
> 
> The fix seems simple enough, but it would be nice to add a test to avoid this regressing.

Yes, I think some kind of test would be nice. It was surprising that I could change that without seeing any lit-test failures.

I don't even use MachO myself and don't even know much about lld. I just debugged this a bit since we see these failures in our downstream builds using EXPENSIVE_CHECKS. I rather leave it to someone who knows about lld and to actually fix this issue and to create proper regression tests for this part of transplantSymbolsAtOffset.

I'm just glad if I could help out debugging a bit and spotting why the function has undefined behavior.

**Comment by carlocab** [comment]
I was able to reproduce exactly the three test failures by compiling with GCC 14 instead (installed via Homebrew).

Applying the patch you [suggested above](https://github.com/llvm/llvm-project/issues/120559#issuecomment-2554622746) fixes the test failures (as expected).

Would you like to open a PR for it? Perhaps a reviewer can suggest an appropriate test. I can open the PR otherwise, if you prefer.

**Comment by bjope** [comment]
I have no real interest in opening a PR myself (and I would have very little time to follow up on it anyway the upcoming week).
So I'm really glad if you can take over doing pull-request here. Thanks!!
