### ISSUE TITLE
you shouldn't be able to set -fmath-errno if your libm doesn't support errno

### ISSUE THREAD

**Issue by jayfoad** [llvm/llvm-project#12533]
|  |  |
| --- | --- |
| Bugzilla Link | [12161](https://llvm.org/bz12161) |
| Version | 3.0 |
| OS | other |
| CC | @lattner,@sunfishcode |

## Extended Description 
(I've split this specific issue out from llvm/llvm-project#12230 .)

On systems like Darwin where libm doesn't support setting errno, it makes no sense to compile with -fmath-errno, because the compiler can't possibly guarantee that math functions will set errno. So on such systems the option shouldn't exists, or you should get an error or a warning if you try to set it.

**Comment by AaronBallman** [comment]
There is no way to implement this in general -- we don't control what libc is actually loaded at program execution time. We might be able to look at the target in the very specific case of OS X, but I don't think that's a reasonable approach because the system could (at least in theory) have a different libc (such as llvm-libc).

I think this should be closed as won't fix.
