### ISSUE TITLE
warn on conditions that are too late to check for undefined behaviour

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17242]
|  |  |
| --- | --- |
| Bugzilla Link | [16868](https://llvm.org/bz16868) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @efriedma-quic,@zygoloid,@seanm |

## Extended Description 
Examples:

bool test(int *p) {
  int i = *p;
  if (!p)
    return false;
  // ... continue using i
}

We should warn on the condition, because if the condition is ever true then undefined behaviour must have already occurred. (Similarly on 'p' and the condition being false.)

bool test2(int idx) {
  char arr[100];
  arr[idx] = '\0';
  if (idx < 0 || idx >= 100)  // either of these alone should also suffice to warn
    return false;
  // ...
}

Examples putting the overflow inside the condition expression:

bool test3(int x) {
  if ((x+1) < x)
  ...

bool test4(int x, int y) {
  if (x != (x*y)/y)
  ...

**Comment by Quuxplusone** [comment]
Clang (the front-end itself) can't do this because it requires dataflow analysis; but surely Clang's static analyzer (`scan-build`) already does exactly this kind of analysis, right? I'm going to be bold and close this, and if `scan-build` somehow _can't_ detect redundant null-checks, feel free to reopen.
