### ISSUE TITLE
The --machine= option is not working as expected

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#17716]
|  |  |
| --- | --- |
| Bugzilla Link | [17342](https://llvm.org/bz17342) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
$clang --machine=sse4 -c test.c 
clang: warning: argument unused during compilation: '-msse4'

**Comment by widberg** [comment]
The same person who created this issue committed https://github.com/llvm/llvm-project/commit/4f3f5ade5467cd9d8b2ba0f37489f1b8ea8fcee3 which removed `-m` and all of it's aliases including`--machine=` among other spellings a few hours later and they were never re-added. This leaves only the individually defined `m_Group` options i.e. `-msse4` etc. Since these alternate spellings no longer exist and as far as I can tell the `m_Group` options in Clang now work fine, I think we can close this.
