### ISSUE TITLE
GCC extension rejected in C++ mode

### ISSUE THREAD

**Issue by d0k** [llvm/llvm-project#19930]
|  |  |
| --- | --- |
| Bugzilla Link | [19556](https://llvm.org/bz19556) |
| Version | trunk |
| OS | All |
| CC | @DougGregor,@hfinkel |

## Extended Description 
Here's some evil code from glibc's mathinline.h.

$ cat evil.cc
```cpp
int foo(double __x) {
  return (__extension__
          (((((union { double __d; int __i[2]; }) {__d: __x}).__i[1]))));
}
```

$ clang evil.cc
evil.cc:3:17: error: '(anonymous union at evil.cc:3:17)' cannot be defined in a type specifier
           (((((union { double __d; int __i[2]; }) {__d: __x}).__i[1]))));
                ^
evil.cc:3:53: warning: use of GNU old-style field designator extension [-Wgnu-designator]
           (((((union { double __d; int __i[2]; }) {__d: __x}).__i[1]))));
                                                    ^~~~
                                                    .__d = 
evil.cc:3:63: error: member reference base type 'void' is not a structure or union
           (((((union { double __d; int __i[2]; }) {__d: __x}).__i[1]))));
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
1 warning and 2 errors generated.

We accept this beast in C mode, but reject it as C++. GCC accepts it in C++ code too.

**Comment by AaronBallman** [comment]
C allows a type to be defined anywhere a type-name can be specified, which allows you to define the type in a compound literal or within a sizeof, etc. C++ does not allow this. GCC is inconsistent about allowing types to be defined in such contexts in C++, it seems only compound literals have this property in their implementation: https://godbolt.org/z/1Wxacsqb4 and their C++ language extension documentation (https://gcc.gnu.org/onlinedocs/gcc-13.1.0/gcc/C_002b_002b-Extensions.html) makes no mention of compound literals at all, and their documentation on extensions to compound literals in C (https://gcc.gnu.org/onlinedocs/gcc/Compound-Literals.html) does not mention allowing type definitions in C++. So I'm not certain whether this extension is by design or not.

Unless there's a compelling need to implement this extension (such as it being used in system headers somewhere), I don't think we will implement this due to the inconsistency it would introduce into C++ (I don't think we want to allow types to be defined anywhere they can be spelled in C++ as is done in C; that opens up a can of worms regarding name lookup that is best avoided).
