### ISSUE TITLE
clang-format does strange things with CF_OPTIONS and related

### ISSUE THREAD

**Issue by akyrtzi** [llvm/llvm-project#21863]
|  |  |
| --- | --- |
| Bugzilla Link | [21489](https://llvm.org/bz21489) |
| Version | unspecified |
| OS | All |
| Attachments | [clang-format config file](https://user-images.githubusercontent.com/46970/143750327-fac4354a-818f-4139-8642-a6243d9a38cb.gz) |

## Extended Description 

In the outermost scope of a header file:
```
typedef CF_OPTIONS(UInt64, fooOptions) {
	foo_bar = 1
};
```

clang-format does two strange things with this:
- indents the whole thing
- removes the space between ) and {

producing:
```
	typedef CF_OPTIONS(UInt64, fooOptions){
		foo_bar = 1
	};
```

Config file is attached.

Also reflected in rdar://18880093.

**Comment by mkurdej** [comment]
The above attached file is:
```
// AQMETap.h
// Copyright © 2014 Apple Inc.

#ifndef __ABFoo_h__
#define __ABFoo_h__

typedef struct OpaqueABFoo *ABFoo;

#ifdef __cplusplus
extern "C"
#endif

	typedef CF_OPTIONS(UInt64, ABFooOptions) {
		kABFoo_Opt1 = 1
	};

struct ABFooStruct {
	int mMember1;
};

#ifdef __cplusplus
}
#endif

#endif // __ABFoo_h__
```

Closing as it seems to be fixed.
To be precise:
Issue 1) typedef is indented as it is the continuation of `extern "C"`.
Issue 2) the space between `)` and `{` is not removed since at least version 3.7.

Also, IMO, the code itself is buggy, as the mentioned `extern "C"` line was probably supposed to end with `{`, because there's a corresponding `#ifdef __cplusplus` block with a closing brace.
