### ISSUE TITLE
[Statepoint] Rename OcamlGC to reflect that it is purely an example

### ISSUE THREAD

**Issue by preames** [llvm/llvm-project#22472]
|  |  |
| --- | --- |
| Bugzilla Link | [22098](https://llvm.org/bz22098) |
| Version | trunk |
| OS | Linux |

## Extended Description 
Per comment by Peter on the review thread for "Introduce an example statepoint GC strategy", http://reviews.llvm.org/D6808.

It makes a good example for gc.root and should be documented as such.

**Comment by Quuxplusone** [comment]
The relevant code has moved to `llvm/lib/IR/BuiltinGCs.cpp`, but I also notice that the original PR's `StatepointExampleGC` is now named simply `StatepointGC` — only the code comments mention anything about its being an example. And there are already code comments for `OcamlGC` and `ErlangGC` that say "example", too. So maybe this issue is obsolete? Or at least not a good-first-issue, unless someone can concretely describe the intended fix.

Should this issue be closed?

**Comment by evaporei** [comment]
@Endilll do you have more context on this issue?

**Comment by Endilll** [comment]
Unfortunately, I don't, and it's not a part of code base I'm familiar with.
I just merged `beginner` issues migrated from our old bugtracker into `good first issue` pool.

**Comment by Endilll** [comment]
If you're interested in working on this, consider joining our Discord server (https://discord.gg/xS7Z362), and asking on #llvm or #jit channels.

**Comment by xgupta** [comment]
Yes, this seems absolute. Comments are there to reflect OcamlGC is an example GC.
```
/// An example GC which attempts to be compatible with Objective Caml 3.10.0
///
/// The frametable emitter is in OcamlGCPrinter.cpp.
class OcamlGC : public GCStrategy {
public:
  OcamlGC() {
    NeededSafePoints = true;
    UsesMetadata = true;
  }
};
```
