### ISSUE TITLE
clang-cl does not properly support /O parsing

### ISSUE THREAD

**Issue by compnerd** [llvm/llvm-project#22590]
|  |  |
| --- | --- |
| Bugzilla Link | [22216](https://llvm.org/bz22216) |
| Version | trunk |
| OS | All |
| CC | @zmodem |

## Extended Description 
/O can take multiple arguments packed together, e.g. /Ob0xy is equivalent to /Ob0 /Ox /Oy.  We currently do not support this properly.

**Comment by widberg** [comment]
Looks like this was fixed by https://github.com/llvm/llvm-project/commit/015ce0f68f791b3abec4225c1b2e532ce5020174. The help text for `/O` was improved to "Set multiple /O flags at once; e.g. '/O2y-' is the same as '/O2 /y-'" in https://github.com/llvm/llvm-project/commit/934230c061082be6c0950636ca610aae11e73b1c to indicate the new supported behavior.
