### ISSUE TITLE
merging of code can lead to misleading line number information; add flag to disable it in some cases?

### ISSUE THREAD

**Issue by antonrang** [llvm/llvm-project#22953]
|  |  |
| --- | --- |
| Bugzilla Link | [22579](https://llvm.org/bz22579) |
| Version | trunk |
| OS | All |
| CC | @pogo59 |

## Extended Description 
In cases where several lines of code are merged together to share instructions, llvm
currently picks a single line number to 'represent' those in the DWARF.  This can lead
to misleading backtraces.

An example from our source base is a large function with some 20 assertion failure
points.  If any of those assertions fails, the backtrace will point to a single one
of them, because all of them share the code to our assertion failure function.  This
is, in part, because that function has __attribute((noreturn)).

We could remove that attribute, but that opens us up to warnings based on static
analysis of the code.

If there were a flag to disable the code merging which is happening here, we could
get useful backtraces.

For example, code like this

  extern int do_assert(const char *, int, const char *, ...) __attribute((noreturn));

  void try(int a)
  {
    if (a & 1)
      do_assert("one", 0, "");
    if (a & 2)
      do_assert("two", 0, "");
    if (a & 4)
      do_assert("three", 0, "");
  }

generates a single call to do_assert.  This is normally a Good Thing, but it has been
confusing some of our developers (and we don't care that much).

Changing __attribute((noreturn)) to __attribute((analyzer_noreturn)) seems like it
might be a path forward, but it triggers missing-return-value warnings for code like

  int val(int a)
  {
    if (a == 1) return 1;
    if (a == 2) return 2;
    do_assert("bad a", 0, "");
  }

Interestingly, it does *not* trigger a number of other warnings, such as uninitialized
variables in the default case of a switch, so perhaps this is a case where this warning
should have been disabled [somehow] by the analyzer_noreturn attribute?

An alternative would be to avoid generating line numbers in the DWARF at all for this
type of merged code.  That might be reasonable too.

**Comment by dwblaikie** [comment]
I believe this has been fixed. The actual `do_assert` call will be attributed to line zero, so as not to misleadingly represent it as coming from any of the three calls. That's the best we can do with DWARF today. (even with hypothetical DWARF features, we could probably only give a vague "it came from one of these three places" - because the code has been merged & so it's ambiguous)

https://godbolt.org/z/hvbz1cMM7

@jmorse speculated that we could, in some cases, use the CPU branch cache to reconstruct which path was used to reach some shared code like this. Though if you crashed too far away (eg: inside `do_assert` after a bunch of other branches inside there were taken) the cache wouldn't include the jump needed to disambiguate the `do_assert` call.

**Comment by dwblaikie** [comment]
I guess whether it's fixed depends on what you think this bug is. The issue of "misleading backtraces" is fixed (but it was probably fixed back in 2020 too, I'd have thought... - yeah, was fixed to attribute the merged call to line 0 in LLVM 4.0: https://godbolt.org/z/Ydhn4395r which would've been back in March 2017?)
