### ISSUE TITLE
The -target  foo option doesn't accept a -target=foo variant.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#23211]
|  |  |
| --- | --- |
| Bugzilla Link | [22837](https://llvm.org/bz22837) |
| Version | 3.5 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
This is slightly inconsistend and also slightly annoying (for example, in my build scripts I iterate over possible build flags that are separated by whitespace to pass to the compiler and so the -target foo form parses as two options to test instead of one). It is easy enough to work around but it is still slightly annoying.

**Comment by widberg** [comment]
This issue has been settled. Around two years before this issue was opened, commit https://github.com/llvm/llvm-project/commit/274b6f0c87a6a1798de0a68135afc7f95def6277 added support for the `--target=<triple>` spelling and added a legacy alias for the `-target <triple>` spelling. Three days after this issue was opened, commit https://github.com/llvm/llvm-project/commit/496059c8c9c0ab6f3c2f5c97fe40dfbde2abd575 added support to allow all the `--target <triple>` and `-target=<triple>` spellings in addition to the other two spellings. This was later reverted in https://github.com/llvm/llvm-project/commit/ad25da87b5ab60496e9b192282a88e7fd791d0d7 after a discussion on the mailing list (according to the commit message). Following that commit only the `-target <triple>` and `--target=<triple>` spellings are allowed, which is where we stand today. Since `-target=<triple>` was explicitly removed following a mailing list discussion and `--target=<triple>` is allowed without whitespace, solving the problem raised in the issue, I think this is safe to close.

**Comment by Endilll** [comment]
Thank you digging this up @widberg!
