### ISSUE TITLE
not recognized in clang-format 3.7: AlignConsecutiveAssignments: true

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24324]
|  |  |
| --- | --- |
| Bugzilla Link | [23950](https://llvm.org/bz23950) |
| Version | unspecified |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Hi,

I tried to use

AlignConsecutiveAssignments: true

which seems to be part of the 3.7 release, but it fails with the following error:

YAML:4:30: error: unknown key 'AlignConsecutiveAssignments'
AlignConsecutiveAssignments: true
                             ^~~~
Error reading /Users/Jiri/.clang-format: Invalid argument
Can't find usable .clang-format, using LLVM style

Seems like a bug ?
Regards
Jiri

System details:

$  clang-format --version
clang-format version 3.7.0 (tags/google/testing/2015-04-21)

$  brew info clang-format
clang-format: stable 2015-04-21 (bottled), HEAD
C/C++/Obj-C formatting tools: standalone and editor plugins
http://clang.llvm.org/docs/ClangFormat.html
/usr/local/Cellar/clang-format/2015-04-21 (5 files, 1.4M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/clang-format.rb
==> Dependencies
Build: xz ✔, cmake ✘, ninja ✔, subversion ✘

$  uname -a
Darwin JiriMBP.home 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64 i386 MacBookPro11,2 Darwin

**Comment by mydeveloperday** [comment]
This wasn't added until 3.8 so 3.7,3.6 and 3.5 were not going to work.

![image](https://user-images.githubusercontent.com/16046346/149936729-2b5841ca-985d-47aa-b128-7b2c7957263b.png)

I feel this issue has come about because of reading the options online, at https://clang.llvm.org/docs/ClangFormatStyleOptions.html

You have to remember that prior to  each version of clang-format being released, this document outlines items in `main` so for example at the current time clang-format-13 has been release, but this file contains description of options added in v14 (not yet branched)

We now label the options with a version number, I'm going to close this as according to the documentation this wasn't added in v3.8 or below.
