### ISSUE TITLE
Windows build cannot be installed silently or to a specific directory

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24684]
|  |  |
| --- | --- |
| Bugzilla Link | [24310](https://llvm.org/bz24310) |
| Resolution | WONTFIX |
| Resolved on | Jul 31, 2015 15:02 |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zmodem |

## Extended Description 
The LLVM Windows installer (currently LLVM-3.6.2-win32.exe) cannot be installed silently or locally, and accepts no command line arguments (including `/?`, `/h`, `-h`, `--help`, or `-?`). Nor is there any way to obtain LLVM on Windows without modifying the registry.

This is an especially an issue for Windows package managers like Chocolatey, which want to distribute zip/7z/tar.gz/tar.xz archives (or even MSI) of "portable" Windows binaries, and to install them to a sandboxed location (like C:/ProgramData/chocolatey/lib/llvm/) and symlink them into a common folder in the PATH (like C:/ProgramData/chocolatey/bin).

The build scripts should be modified to produce either a zip/7z/tar.gz/tar.xz/msi archive of the Windows binaries, or if all else fails to add options to ".exe" installer to enable silent, local installation.

**Comment by billti** [comment]
Just looking for exactly this, and think I've found a usable solution.

It looks like LLVM is built using CPack and NSIS (see https://cmake.org/cmake/help/latest/module/CPack.html). The LLVM installer is very simple and just pretty much copies the files to the install dir without any custom actions, etc. - see https://github.com/llvm/llvm-project/blob/release/14.x/llvm/CMakeLists.txt#L256 ).

Turns out you can just use 7Zip to extract the contents of the installer. It has a couple extra files in a $PLUGINDIR directory and an uninstall.exe in the root dir that you don't need, but other than that that is the folder you want.

In fact, if you look at the LLVM release build script, it does do exactly this to create a zip file of the type you are after! See the few lines after https://github.com/llvm/llvm-project/blob/release/14.x/llvm/utils/release/build_llvm_package.bat#L145 . I don't know what the official release builds do with this zip file that the script creates, but it's exactly what you (and I) are after.

**Comment by bebuch** [comment]
This issue is strongly releated to #62492.

> > Why not? This isn't "providing a different installer," this is declining to
> > provide one.
> > LLVM provides an archive for every other platform, even Apple, despite the
> > existence of Apple's PKG installer format. At the very least, the same
> > format should exist for Windows.
> 
> We made the choice of providing a .exe installer instead of just a .zip file with the motivation that it would be more convenient for most users (it's easy to run, and also installs the VS integration). I still think this is true.

In its current form, the installer requires mandatory admin rights. This makes it unusable for many use cases. In addition, company restrictions often prevent the execution of NSIS installers (and others).

> I'm not categorically opposed to shipping a .zip file on Windows as well, but I'm not sure I see that the value would outweigh the extra work required.

I've been trying to find a solution to somehow integrate the installer into our processes for over two weeks now and I'm getting really desperate. 7-Zip works, but only through manual actions in the GUI. It can't be used in a script process. The command line version of 7-Zip does not support NSIS installers.

LLVM is currently the only one of over 10 projects that does not provide a ZIP version. Everything else is fully automated. I beg you, please provide a simple ZIP version! You are welcome to do this in addition to the installer, many projects do it this way. (CMake., Doxygen, Graphviz ...)

> > But you missed the other part of this bug, which is that regardless of
> > "providing a different installer" the current installer doesn't do enough.
> > It needs to handle silent installation, and to handle receiving its target
> > directory from the command line, as almost every other installer does
> > (InstallShield and .msi come to mind).
> 
> Our installer is NSIS-based, and apparently it can be invoked with /S /D=c:\llvminstalldir (see http://nsis.sourceforge.net/Docs/Chapter3.html#installerusage). Does that work for your use case?

For our case, this does not work. I can't even run this without admin rights.
