### ISSUE TITLE
False negative for -Wdivision-by-zero

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#24711]
|  |  |
| --- | --- |
| Bugzilla Link | [24337](https://llvm.org/bz24337) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@rnk |

## Extended Description 
int main(void)
{
  int z = 0;
  int x = 1 / z;
  (void)x;
  int y = 1 / 0;
  (void)y;
  return (0);
}

clang warns on the assignment of y, but it doesn't on the assignment of x.
For what it's worth, GCC seems to have the same behaviour, but the two cases seems pretty much identical to me so I think we should warn on the first as well.

I dug into that a little bit more, and we seem to fail evaluatingAsInt the RHS of the expression:

7428        if (RHS.get()->EvaluateAsInt(RHSValue, S.Context)) {
[...]

(gdb) p RHS.get()->dump()
ImplicitCastExpr 0x8080c9f38 'int' <LValueToRValue>
`-DeclRefExpr 0x8080c9f10 'int' lvalue Var 0x8080c9de8 'z' 'int'
$7 = void

Is this a limitation or is this the expected behaviour? Any ideas on how to fix this?

**Comment by Quuxplusone** [comment]
The expression `1/0` statically contains a division by zero. The expression `1/z` doesn't. You'd have to do dataflow analysis (like `scan-build`/Clang Static Analyzer does) in order to find out that the subexpression `z` was guaranteed to hold `0` at the relevant point, and Clang (the front-end) doesn't do that.
