### ISSUE TITLE
readability-simplify-boolean-expr doesn't always work in included files

### ISSUE THREAD

**Issue by EugeneZelenko** [llvm/llvm-project#26706]
|  |  |
| --- | --- |
| Bugzilla Link | [26332](https://llvm.org/bz26332) |
| Version | unspecified |
| OS | Linux |
| CC | @LegalizeAdulthood |

## Extended Description 
When working with my work code base I noticed that readability-simplify-boolean-expr doesn't always work in included files (more precisely in inlined methods file included from header).

To reproduce this problem include readability-simplify-bool-expr.cpp in other source file and run Clang-tidy on it.

Looks like removing isExpansionInMainFile() from SimplifyBooleanExprCheck.cpp fix problem but I don't know why isExpansionInMainFile() was used at all.

**Comment by LegalizeAdulthood** [comment]
@EugeneZelenko Is this still an issue?  I seem to recall that someone removed the main file check a while ago on a code review.

**Comment by EugeneZelenko** [comment]
Looks like `isExpansionInMainFile` checks were removed in 7009d6571494f5f4e6590ae8b71772186a905214, but will be good idea to review this change closer.

**Comment by LegalizeAdulthood** [comment]
I was working on making tests for header file fixes, but there were no existing unit tests for clang-tidy that checked changes to header files!  So it required some rework of the python script that runs the test and that took forever to get reviewed.  (Honestly, it was years ago, I don't even know if my incremental progress was ever committed.)

So, unless there's an open bug that reproduces a problem, it's hard to say whether or not this has been fixed.  More infrastructure work is needed (unless someone else has done it in the meantime; possible) in order to write tests for fixits applied to header files.

Are you still having problems with header files?

**Comment by EugeneZelenko** [comment]
Just tried to run this check on Clang-tidy built from `main` on LLVM source code: issues in headers were reported.

**Comment by LegalizeAdulthood** [comment]
Were correct fixits supplied?

**Comment by LegalizeAdulthood** [comment]
Oh, duh.  You closed it `:)`.  Thanks!
