### ISSUE TITLE
LLVM/Cmlang regressions failures with libc++abi built with libunwind on RHEL 6

### ISSUE THREAD

**Issue by EugeneZelenko** [llvm/llvm-project#28345]
|  |  |
| --- | --- |
| Bugzilla Link | [27971](https://llvm.org/bz27971) |
| Version | unspecified |
| OS | Linux |
| Attachments | [Regressions failures log](https://user-images.githubusercontent.com/92601273/143753619-f5b9dedc-2009-44a3-a0ab-9ddbdb2d58b9.gz), [libc++/libc++abi/libunwind CMake parameters](https://user-images.githubusercontent.com/92601273/143753620-a3646972-d4a6-4830-9256-37124b2c85ee.gz) |
| CC | @mclow |

## Extended Description 

I built LLVM/Clang with libc++/libc++abi/libunwind on RHEL 6 and had 10 LLVM and 2 Clang failures. Same version built with libgcc_eh/libc++abi/libunwind passed all regressions.

**Comment by philnik777** [comment]
There isn't a lot we can work with here, since
1. RHEL 6 isn't officially supported and is effectively EOL
2. Clang and LLVM have changed a lot in the past 6 years, so the tests listed aren't really useful
3. We don't have any libc++/libc++abi/libunwind test cases here, so we don't have any way to know if the problems are resolved
Closing this for now. If this is still a problem on a relevant OS, please reopen.
