### ISSUE TITLE
Wrong code bug after GVN/PRE

### ISSUE THREAD

**Issue by mikaelholmen** [llvm/llvm-project#30999]
|  |  |
| --- | --- |
| Bugzilla Link | [31651](https://llvm.org/bz31651) |
| Version | trunk |
| OS | Linux |
| Attachments | [Reproducer](https://user-images.githubusercontent.com/55733087/143754967-208904db-8076-4d7b-ab31-cf852cd16487.gz) |
| CC | @efriedma-quic,@fhahn,@zmodem,@preames |

## Extended Description 

Reproduce with
 opt -S -gvn pre_gvn.ll
Adding 
 -debug-only=gvn
We see e.g
 GVN REMOVING PRE LOAD:   %_tmp79 = load i16, i16* %_tmp78, align 2
and I think it goes wrong during this optimization.

In the input we have something like

    for (int step1 = 0; step1 < LOOP_AMOUNT; step1++)
    {
        lb[step1] = step1 + 7;
        ub[step1] = (step1 == 0 ? 10: ub[step1-1]*10);

        switch(lb[step1]) {
        case 7:    CVAL_VERIFY(step1 == 0);
            CVAL_VERIFY(ub[step1] == 10);
                        __label(511);
            break;
        case 8:    CVAL_VERIFY(step1 == 1);
            CVAL_VERIFY(ub[step1] == 100);
                        __label(512);
            break;
        case 9:    CVAL_VERIFY(step1 == 2);
            CVAL_VERIFY(ub[step1] == 1000);
                        __label(513);
            break;
        default:;
        }

        [...]
    }

    int i, j;
    for ( j = 10, i = 0; j < 101; j=j*10, i++ )
    {
        CVAL_VERIFY(ub[i] == j);
    }

So we have two loops. In the first one the array ub is written (low index first, high index last), and then in the second loop the content of ub is checked (low index first, high index last).

After gvn this is changed into something like

    int tmp;
    for (int step1 = 0; step1 < LOOP_AMOUNT; step1++)
    {
        lb[step1] = step1 + 7;
        ub[step1] = (step1 == 0 ? 10: ub[step1-1]*10);

        switch(lb[step1]) {
        case 7:    CVAL_VERIFY(step1 == 0);
                        tmp = ub[step1];
            CVAL_VERIFY(tmp == 10);
                        __label(511);
            break;
        case 8:    CVAL_VERIFY(step1 == 1);
                        tmp = ub[step1];
            CVAL_VERIFY(tmp == 100);
                        __label(512);
            break;
        case 9:    CVAL_VERIFY(step1 == 2);
                        tmp = ub[step1];
            CVAL_VERIFY(tmp == 1000);
                        __label(513);
            break;
        default:;
        }

        [...]
    }

    int i, j;
    for ( j = 10, i = 0; j < 101; j=j*10, i++ )
    {
        CVAL_VERIFY((i == 0 ? tmp : ub[i]) == j);
    }

Note the introduced variable tmp (%_tmp792 in the ll output).

Also note that with this rewrite, after the first loop tmp will contain the value of the element at the highest index in ub, and then we use tmp in the first round of the second loop, but there we expect the value of the lowest index element in ub.

**Comment by bjope** [comment]
The reproducer for this ticket (as well as the modified version in the proposed patch that never landed, https://reviews.llvm.org/D65204) does not seem to work if enabling opaque-pointers.

No idea if that means that the actually bug goes away by enabling opaque pointers, or if it merely is that since `%_tmp47 = getelementptr [4 x i16], [4 x i16]* %ub.16, i16 0, i16 0)` would be rather pointless as one could just replace `%_tmp47` by `ptr %ub`. So maybe it depends on if GVN will simplify that first or not?

Btw, downstream we've been bailing out early from GVNPass::PerformLoadPRE for several years due to this bug. So we haven't included that function in any kind of test (neither normal regression or fuzzy testing) for very long time. If opaque pointers would imply that this bug could be solved, perhaps we could start enabling this in some testing to see that we do not find more faults in this area.

**Comment by fhahn** [comment]
I think the bug is independent of opaque pointers. I pushed a test case that uses opaque pointers and performs incorrect PRE (it's possibly to verify that using alive2, it just requires ` -tv-src-unroll=2 -tv-tgt-unroll=2`): https://github.com/llvm/llvm-project/blob/411b9b8153ee95a51a2b7b3ebdb6fec9a7229f5a/llvm/test/Transforms/GVN/condprop-memdep-invalidation.ll

> Btw, downstream we've been bailing out early from GVNPass::PerformLoadPRE for several years due to this bug. So we haven't included that function in any kind of test (neither normal regression or fuzzy testing) for very long time. If opaque pointers would imply that this bug could be solved, perhaps we could start enabling this in some testing to see that we do not find more faults in this area.

That's unfortunate. I forgot about the patch, let's see if we can move forward with it. Note that there's currently work underway to transition GVN to use MemorySSA instead of the bug-prone MemDepAnalysis.

**Comment by mikaelholmen** [comment]
Note: the testcase
```llvm/test/Transforms/GVN/condprop-memdep-invalidation.ll```
does not miscompile anymore after 4f046bc8e0b9
```[PHITranslateAddr] Require dominance when searching for translated address (PR57025)```

**Comment by fhahn** [comment]
@mikaelholmen can this now be closed?

**Comment by mikaelholmen** [comment]
@fhahn : I suppose so. I at least don't have a reproducer anymore.
As far as I know though, we don't really know if the problem is really fixed, or just not triggered anymore with the patch above.
But let's close this. If there is still a bug I suppose we will trip over it at some point and can open another TR with a fresh repro then.
