### ISSUE TITLE
Suboptimal code generation for __builtin_ctz(ll)

### ISSUE THREAD

**Issue by 9834e6df-18ef-4c63-9c05-66fa74b7fdd9** [llvm/llvm-project#34191]
|  |  |
| --- | --- |
| Bugzilla Link | [34843](https://llvm.org/bz34843) |
| Version | 5.0 |
| OS | Linux |
| CC | @topperc,@RKSimon,@rotateright |

## Extended Description 
Right now, when no specific arch target is set, the builtin

__builtin_ctz (and long, long long variants)

will generate a bsf instruction.

This is suboptimal for AMD machines, which can do a TZCNT much faster than they can do a BSF. Due to the way TZCNT is encoded, it is equal to a REP BSF, so it is in fact "backwards compatible" as long as the different behavior for a 0 is fine. And it is, because __builtin_ctz has undefined behavior for 0 (which is why it can use BSF in the first place). 

On Intel hardware, either way is equally fast, so for a generic target it makes sense to deal with the AMD case and encode the intrinsic as REP BSF/TZNCT.

At least GCC 4.8 and later are able to do this optimization and generate a REP BSF for their generic target. Clang fails to do so. (It does generate TZCNT with -march=znver1)

Example snippet:
https://godbolt.org/g/eXU6xf

Of note in this snippet is also that newer GCC adds a XOR ESI, ESI before the REP BSF. So there may be a false dependency issue in some CPUs.

**Comment by RKSimon** [comment]
Candidate Patch: https://reviews.llvm.org/D130956

**Comment by nickdesaulniers** [comment]
sounds like this was reverted in 84e91948289cd606a0cd8a3372398b363d4b5460

**Comment by aaronpuchert** [comment]
> [...] __builtin_ctz has undefined behavior for 0 (which is why it can use BSF in the first place).

Turns out that's not quite the case. [GCC docs simply state](https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html) that "the result is undefined" instead of the "the behavior/program is undefined". As long as you're not using the result in the problematic case you're fine. Similarly `llvm.cttz.*` [is specified](https://llvm.org/docs/LangRef.html#llvm-cttz-intrinsic) to return `poison` for zero input.

The `bsf` instruction similarly leaves the destination operand undefined, but still sets ZF to indicate zero input. One might want to use this flag to overwrite the undefined result in the zero input case. But here it gets tricky, because `tzcnt` sets CF instead, so if we always emit `tzcnt` without knowing the machine that will run the code, we don't know which flag to look at.

**Comment by nickdesaulniers** [comment]
Given the risk of the first landing, I'm content to let this ride the release trains out to clang-16. Thanks again for the patch and fix, @phoebewang !

**Comment by tstellar** [comment]
I've dropped this from the 15.0.0 milestone.  It can always be re-added we change our minds.
