### ISSUE TITLE
MergeIdenticalFuncs is unable to merge identical lambdas

### ISSUE THREAD

**Issue by 614eaf53-7ecd-4c4f-a941-40bf78db1486** [llvm/llvm-project#35131]
|  |  |
| --- | --- |
| Bugzilla Link | [35783](https://llvm.org/bz35783) |
| Version | trunk |
| OS | Linux |
| CC | @dwblaikie,@DougGregor,@rnk |

## Extended Description 
Case 1: https://godbolt.org/g/JvmxJr
Case 2: https://godbolt.org/g/FWo12z

Ideally, the compiler should be able to detect that the code is the same and merge it. 

I opened a similar bug report in GCC: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83582

**Comment by nikic** [comment]
The examples in the initial report get optimized away entirely nowadays. https://godbolt.org/z/7qba6ja3b gets merged when using `-Xclang -fmerge-functions`. I think at this point this issue is not sufficiently specific anymore (and the question of enabling function merging by default is a separate one), so I'm going to close this.

If there are specific, interesting cases where `-Xclang -fmerge-functions` fails, they should be reported separately.
