### ISSUE TITLE
clang-format FixNamespaceComments does not understand namespace aliases

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#35876]
|  |  |
| --- | --- |
| Bugzilla Link | [36528](https://llvm.org/bz36528) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
# cat test.cpp

```
namespace nn {}
void f()
{
    namespace n = nn;
    {
        int i;
        int j;
    }
}
```

#` clang-format -style="{FixNamespaceComments: true}" test.cpp`

```
namespace nn {}
void f() {
  namespace n = nn;
  {
    int i;
    int j;
  } // namespace n=nn;
}
```

In this case comment "// namespace n=nn;" should not be added.

**Comment by mydeveloperday** [comment]
Is this what we'd expect?

```
$ clang-format -style="{FixNamespaceComments: true}" test2.cpp

namespace nn {}
void f() {
  namespace n = nn;
  {
    int i;
    int j;
  } // namespace ;
}
```
This isn't what we see for anonymous namespaces

```
namespace nn {}
void f() {
  namespace n = nn;
  {
    int i;
    int j;
  } // namespace ;
  namespace n {
  int i;
  int j;
  } // namespace n
  namespace {
  int i;
  int j;
  } // namespace
}
```
If feel the ; at the end of namespace is incorrect should it say `// namespace n`

**Comment by zero9178** [comment]
I think the issue here is that this is actually not a namespace being opened, but just an alias declaration. Since its inside a function, the 
```cpp
{
  int i;
  int j;
}
``` 
portion is a compound statement. 
The `namespace n = nn;` is just a namespace alias, allowing one to refer to the `nn` namespace using the name `n`. 

So the expected output is probably for their to simply be no change (aka for the `//namespace ;`  not to be there)

**Comment by mydeveloperday** [comment]
Of course... well spotted.  I'm thinking this could just be a bug in the regular expression it should ignore anything ending with a ";"
I think this one would be good for a beginner
