### ISSUE TITLE
std::copy_n requires non-overlapping inputs

### ISSUE THREAD

**Issue by TNorthover** [llvm/llvm-project#36198]
|  |  |
| --- | --- |
| Bugzilla Link | [36850](https://llvm.org/bz36850) |
| Version | unspecified |
| OS | All |
| Attachments | [Example of unexpected behaviour](https://user-images.githubusercontent.com/1629360/143757273-470e07b1-4449-4d5e-8b90-c365cbe99723.gz) |
| CC | @mclow |

## Extended Description 

Most of the "std::copy*" functions explicitly require their input and output iterators not to overlap, but std::copy_n doesn't seem to.

However, the implementation of std::copy_n in libc++ forwards to a version of std::copy which behaves differently than expected from a straightforward reading of copy_n's effects clause and calls memmove.

This came up on IRC, where Eelis came up with the attached C++ file demonstrating the difference from a naive copy_n.

**Comment by philnik777** [comment]
Closing this, since every major implementation has the same "bug" https://godbolt.org/z/asW3jeadf. Even if this was intended to work (which I don't think) I think the standard should be changed and not the implementations, since none of the other `copy` algorithms have this requirement and nobody seems to expect this to work.
