### ISSUE TITLE
Clang should support `_BitscanForward` and `_BitscanForward64` in constant expressions

### ISSUE THREAD

**Issue by BillyONeal** [llvm/llvm-project#36410]
|  |  |
| --- | --- |
| Bugzilla Link | [37062](https://llvm.org/bz37062) |
| Version | trunk |
| OS | Windows NT |
| CC | @DougGregor |

## Extended Description 
In MSVC++'s STL, we implemented binary GCD as this can be faster, as it replaces divisions with `bsf`. Unfortunately, right now we had to fake `bsf` with a loop, resulting in `std::gcd` actually being slower than a naïve Euclid's algorithm implementation. This could be substantially faster with real `bsf`.

Note that C1XX doesn't currently support `_BitscanForward` in `constexpr` contexts; this bug is being filed at the same time it's being filed against C1XX (and EDG).

**Comment by cor3ntin** [comment]
@StephanTLavavej is that something you still need or is `if consteval` a good solution to that problem?

**Comment by StephanTLavavej** [comment]
I don't think we need this anymore. We don't have `if consteval` yet, but we do have `if (is_constant_evaluated())`, and we already need an elaborate fallback scheme because we attempt to light up with both tzcnt and bsf (and maybe ARM64 intrinsics in the future) before falling back to a pure constexpr implementation.

Feel free to close this as wontfix.
