### ISSUE TITLE
use of MAP_ANONYMOUS blocks build on OS X 10.10 and earlier

### ISSUE THREAD

**Issue by kencu** [llvm/llvm-project#38306]
|  |  |
| --- | --- |
| Bugzilla Link | [38958](https://llvm.org/bz38958) |
| Version | unspecified |
| OS | MacOS X |
| Attachments | [instances of MAP_ANONYMOUS in compiler-rt/* as of 20180915](https://user-images.githubusercontent.com/95090711/143758103-2a5d362b-3340-4b7f-9883-4209318a4e18.gz) |

## Extended Description 

A number of uses of MAP_ANONYMOUS have crept into the compiler-rt codebase, and causes build failures on systems that only define MAP_ANON and not MAP_ANONYMOUS (including macOS 10.10 and earlier).

Previously <https://reviews.llvm.org/D15180> it was decided to use MAP_ANON instead for this reason.

This could possibly be fixed in compiler-rt/CMakeLists.txt with a simple blanket change: 

IF (APPLE)
  add_definitions(-DMAP_ANONYMOUS=MAP_ANON)
ENDIF

Or more elegantly the define could be tested for and added only if missing.

Or the instances of MAP_ANONYMOUS in the compiler-rt codebase could be individually changed to MAP_ANON.

(I note tsan has done it's own version of managing this mapping with TSAN_MAP_ANON in compiler-rt/test/tsan/ignore_lib5.cc)

A present list of involved files is attached.

**Comment by MaskRay** [comment]
Maybe not worth addressing as OS X 10.10 is older now...
Both are quite popular, but MAP_ANONYMOUS is likely more popular, possibly because Linux man-pages has marked `MAP_ANON` as deprecated for 20 years (with unclear reasons). 
https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/commit/?id=9154da7f05006ce007194eccd53774370d967464 (2020) removed the deprecated mark.
