### ISSUE TITLE
Compile error when input operator constraint of inline asm has "o"

### ISSUE THREAD

**Issue by ce0850b8-0b77-4c06-bf81-4071c8426082** [llvm/llvm-project#42184]
|  |  |
| --- | --- |
| Bugzilla Link | [42839](https://llvm.org/bz42839) |
| Version | unspecified |
| OS | Linux |
| Attachments | [Error log when compiling ruby](https://user-images.githubusercontent.com/92601759/143759567-91980646-4527-40a3-b7ca-17154edf3237.gz) |

## Extended Description 

When compiling ruby-2.5.5 on aarch64/thunderX2t99, the compilation process is aborted.
The problem seems to be due to the input operator constraint of inline asm having "o".

Here's a short example.
-------------------
//This program aborts because "o" is included in "nor".

void hoge(void)
{
    static const char *str = "HOGE";
    __asm__ __volatile__(".asciz \"%[_SDT_A2]\"" : : [_SDT_A2] "nor" ((str)));
}

-------------------

There is no description of the "o" in the AArch64 section of the following URL, but how should it be done?
 > https://llvm.org/docs/LangRef.html#supported-constraint-code-list
If "o" is included, is it correct to ignore it?

The environment used for confirmation is as follows.
$ clang --version
clang version 7.0.1 (tags/RELEASE_701/final)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /oss/LLVM/llvm-7.0.1/install/bin

**Comment by lenary** [comment]
This looks like it was solved between clang 12 and clang 13.

https://godbolt.org/z/zPGrfcx1j

Oddly enough, I had to use godbolt's x86-64 clang with `--target=aarch64-unknown-linux` because I could not reproduce this issue with any of the armv8a clang versions (which only go back to clang 9 anyway). I don't fully understand why the reproduction between these two compilers is differing in the version it can be reproduced for (the assertion message certainly changes between clang 9 and clang 12 for x86-64 with assertions). I think we can close this as fixed anyway.
