### ISSUE TITLE
Bad floating-point "optimizations"

### ISSUE THREAD

**Issue by dbc7d0cf-60de-4ba2-bc9a-c1b7219315df** [llvm/llvm-project#43070]
|  |  |
| --- | --- |
| Bugzilla Link | [43725](https://llvm.org/bz43725) |
| Version | 8.0 |
| OS | Linux |
| CC | @DougGregor,@zygoloid |

## Extended Description 
Is there a way to disable ALL "optimizations" related to floating-point?
My testing has shown that clang does the following:
  1. * x  => x
  0. * x  => 0.
  x / 1.  => x
  x / x   => 1.
  0. / x  => 0.
  x + 0.  => x
  x - 0.  => x
  x - x   => 0.
They are all invalid "optimizations" if x is a signaling NaN.
In addition, some are invalid if x is a signed zero or infinity.
In the above, 'x' can be either a variable or a constant.
It might matter if 'x' is float, double, or long double.

**Comment by CAD97** [comment]
> LLVM assume[s] that floating point generates no side effects.

For what it's worth, I don't think this is enough to justify turning `x * 1.0f` into `x` ([[alive2]](https://alive2.llvm.org/ce/z/z7f5bm). If `x` is a signaling NaN, the IEEE standard specifies that the operation returns a quiet NaN after raising the invalid operation exception. If you want to justify this transformation, you need to also treat all NaNs as quiet NaNs.

This is a reasonable simplifying assumption for LLVM to make, but it should be made explicitly.

**Comment by rotateright** [comment]
The Language Reference says this about the default FP env:
"No floating-point exception state is maintained in this environment. Therefore, there is no attempt to create or preserve invalid operation (SNaN) or division-by-zero exceptions."

https://llvm.org/docs/LangRef.html#floatenv

Suggestions welcome if that text is not clear. Otherwise, I think we can close this bug now. "Strict" FP is supported for multiple targets. If anything is still broken in that mode, there should be narrower bugs filed with examples to show a problem.

**Comment by efriedma-quic** [comment]
The only thing that's a little weird for non-strict FP is that if we optimize `x * 1.0 -> x`, that effectively means fmul can produce an SNaN.  If we're okay with that, it's probably worth documenting explicitly.  (If we want to avoid that, we can transform `x * 1.0 -> llvm.canonicalize(x)`.)

**Comment by CAD97** [comment]
This was in fact exactly my point; if reducing `x * 1.0 -> x` is acceptable for nonstrict FP, this should be documented more explicitly. This is not just a case of not preserving an invalid operation (SNaN) exception; it's actually changing the value from the IEEE-defined result. In fact, all of the OP's examples are not about exceptions; they're all operations that should produce some qNaN when `x` is sNaN. Any other FP nonstrictness is not the intended domain of this specific issue.

FWIW,

- It's currently the case that a constrained fmul with `!"round.tonearest", !"fpexcept.ignore"` (i.e. the default environment settings) will not perform this contraction (nor to `llvm.canonicalize`). [[godbolt]](https://godbolt.org/z/6jhcMYYv3)
- Alive2 seems to not have full `strictfp` support, as it reports the contraction as valid even for the `strictfp` version. [[godbolt]](https://alive2.llvm.org/ce/z/gas-qe)
- I tried to test `llvm.canonicalize` to see if it lowered differently and got an instselect error instead. [[godbolt]](https://alive2.llvm.org/ce/z/gas-qe)

Personally, I'm perfectly agreeable with a resolution of clarifying that non-`strictfp` ignores sNaN, treating all NaN as qNaN, so long as that choice is documented.

<details><summary>Additional but unnecessary nice-to-haves:</summary>

- A commitment that treating all NaN as quiet is the extent of the sNaN weakening; that it's not actually just UB to operate on sNaN outside `strictfp`.
- Ensuring most optimizations still work under `strictfp` when supplying the default rounding mode and exception behavior.
- Being able to use default-modal strict floating point intrinsics without annotating functions/calls with `strictfp`.
  - Having to respect full `strictfp` semantics for function calls is a significant expense solely to preserve IEEE semantics for sNaN.
- Being able to tag floating-point operations directly with `strictfp` (without tagging the rest of the world) to get sNaN-respecting (but still exception-ignoring) semantics.
- Clarification on exactly how strict `strictfp` is; is it just about respecting the floating-point environment, or is it fully "match the target's FPU" level strict and guarantees that the NaN payload matches what the target FPU does (if the target has a deterministic behavior)?
- Clarification on NaN semantics more generally; what operations preserve NaN payload bits, and are the NaN payload bits from a NaN-producing operation arbitrary-but-consistent (a la implied `freeze`) or fully nondeterministic?
  - This as an axis of control for `strictfp`, or being able to use `freeze` for this purpose.
  - Note that arbitrary-but-consistent makes floating-point operations impure, in that it's not valid to duplicate computation anymore, since the separate copies may make different decisions inconsistent with each other.
- Promoting the constrained floating point intrinsics out of the `experimental` namespace.

I'll probably make a fresh issue for all of the NaN clarifications that I'm aware of us (Rust) wanting from LLVM, since it's not just the sNaN semantics covered by this issue.

</details>

**Comment by Muon** [comment]
FWIW, I believe the offending transformations are in [`simplifyFMAFMul()`](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Analysis/InstructionSimplify.cpp#L5527) and [`visitFMul()`](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Analysis/InstructionSimplify.cpp#L5528), run in instcombine. This has nothing to do with exception flags. It is a direct violation of IEEE 754, since an sNaN can never be the result of an addition or multiplication.

I suspect the reason alive2 considers this valid is because the SMT-LIB floating-point theory does not differentiate between different kinds of NaNs.

Also @CAD97 your last example link points to the alive2 run.

**Comment by rotateright** [comment]
To be clear, this is about more than "x * 1.0" alone. As noted in the original problem report, we allow several FP simplifications that ignore converting SNaN to QNaN.

Here's an incomplete sampling of FP transforms that are allowed in LLVM's default FP environment:
https://alive2.llvm.org/ce/z/igb55y

Proposal to update the LangRef text to make it clearer that those are expected transforms:

"The default LLVM floating-point environment assumes IEEE754-compliant operations except that floating-point instructions do not have side effects. Results assume the round-to-nearest rounding mode. No floating-point exception state is maintained in this environment. Therefore, there is no guarantee that exceptions or their associated state (signaling NaN values) are created, cleared, or preserved. All NaN values are treated as quiet values, but otherwise they are propagated according to IEEE754 rules.

The benefit of this exception-free assumption is that floating-point operations may be speculated freely without any other fast-math relaxations to the floating-point model."

**Comment by Muon** [comment]
There seems to be some confusion about how exceptions and signaling NaNs relate there. An sNaN is a NaN that always causes the "invalid operation" exception to be raised when you try to operate on it, not a kind of NaN that is produced by things signaling exceptions. It's not associated state, and it can only be created by directly specifying it in the source code. (Under default exception handling, IEEE 754 mandates that a float-producing operation that signals an invalid operation exception must deliver a qNaN.) Note that the invalid operation exception is also raised whenever you compute 0/0 or ∞ - ∞, and it's the default handling of that exception that produces the qNaN.

**Comment by rotateright** [comment]
I'm not sure how to word it better, but here's an attempt:
https://reviews.llvm.org/D143074
I didn't find Phab IDs for @muon or @CAD97 , so please add yourselves there if you'd like to comment on the patch.

**Comment by rotateright** [comment]
We made the documentation clearer, so closing this. If there are still problems, please file new issues with specific examples/requests.
