### ISSUE TITLE
Insufficient locking in std::atomic_compare_exchange_strong for std::shared_ptr

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43158]
|  |  |
| --- | --- |
| Bugzilla Link | [43813](https://llvm.org/bz43813) |
| Version | 9.0 |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @mclow |

## Extended Description 

The implementation of `std::atomic_compare_exchange_strong(shared_ptr* p,
shared_ptr* v, shared_ptr w)` only locks the mutex related to `p`, but not the one
for `v` as well.

This means the following code (which should have no race conditions):

```
#include <memory>
#include <atomic>
#include <unistd.h>
#include <pthread.h>

std::shared_ptr<int> g_p;

static void* thread_run(void*) {
    auto w = std::make_shared<int>();

    while (true) {
        auto p = std::make_shared<int>();

        std::atomic_compare_exchange_strong(&p, &g_p, w);
    }

    return nullptr;
}

int main() {
    pthread_t tid;
    pthread_create(&tid, nullptr, thread_run, nullptr);

    auto w = std::make_shared<int>();

    while(true) {        
        std::atomic_store(&g_p, w);
    }
}
```

may attempt to access the same `g_p` instance from multiple threads - The main
thread (Via `std::atomic_store()`) will properly lock the matching mutex, but the 2nd
thread will not, causing a race condition.

I believe the mutex for `v` should be locked as well, with special care as to not
introduce a deadlock now that 2 mutexes are being locked.

**Comment by Quuxplusone** [comment]
Your sample program is exercising
```
template<class T>
bool atomic_compare_exchange_strong(std::shared_ptr<T>* p,  // this cmpxchg access is atomic
                                    std::shared_ptr<T>* expected,  // these load/store accesses are not atomic
                                    std::shared_ptr<T> desired);
```
Your code's `p` is in the role of `p`, and `g_p` is in the role of `expected`.
The library's access to `p` is guaranteed atomic. The library's access to `expected` (i.e. `g_p`) is _not_ guaranteed atomic. (In fact it can't be atomic, because the hardware physically can't exchange values in two different cache lines atomically; the only atomic exchange that exists on most hardware goes between one memory operand and one _register_ operand.)

This is true for all types, not just `shared_ptr`.

So, if I understand correctly, this is Not a Bug.
