### ISSUE TITLE
strange whitespace in fix-it of readability-convert-member-functions-to-static

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#43219]
|  |  |
| --- | --- |
| Bugzilla Link | [43874](https://llvm.org/bz43874) |
| Version | unspecified |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @EugeneZelenko,@mgehre |

## Extended Description 
While whitespace is technically just a formatting issue, it's still strange to see an "obviously incorrect" output from a fix-it.

Code:

class Foo {
public:
    int id(int i) const;
};

int Foo::id(int i) const {
    return i;
}

Result:

class Foo {
public:
    static int id(int i) ;
};

int Foo::id(int i) {
    return i;
}

Note the whitespace before ;

**Comment by AaronBallman** [comment]
We've considered automatically formatting fixes on a few occasions and always come to the same conclusion: clang-tidy fixes should not attempt to automatically fix formatting issues at the same time as issuing fixes. One problem which I remember: it doesn't scale well. The performance from running the formatting tool repeatedly after each check (where we know the range of lines to format) instead of only once at the end of running all the checks (where we wouldn't have that information unless we wrote it out to a side file, which comes with its own issues) was a very real issue.

Closing this as not a bug.
