### ISSUE TITLE
bugprone-branch-clone: don't fire if there's a comment likely explaining the duplicated code?

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [llvm/llvm-project#43510]
|  |  |
| --- | --- |
| Bugzilla Link | [44165](https://llvm.org/bz44165) |
| Version | unspecified |
| OS | other |
| CC | @mathstuf,@Szelethus,@EugeneZelenko,@pavelkryukov |

## Extended Description 
We have

if (comparison == CommitComparison::LEFT_SUBSET_OF_RIGHT) {
  return MergeCommitsToContentOfLeftSync(handler, std::move(right),
                                         std::move(left));
} else if (comparison == CommitComparison::RIGHT_SUBSET_OF_LEFT) {
  return MergeCommitsToContentOfLeftSync(handler, std::move(left),
                                         std::move(right));
} else if (comparison == CommitComparison::EQUIVALENT) {
  // The commits are equivalent so we can merge to the content
  // of either of them.
  return MergeCommitsToContentOfLeftSync(handler, std::move(left),
                                         std::move(right));
}

(https://fuchsia-review.googlesource.com/c/fuchsia/+/333728)

on which bugprone-branch-clone is firing, and it seems like it shouldn't be firing, because we have a comment there explaining why the branch code is duplicated.

It's a case of the duplication being simple coincidence rather than pointing to some deeper truth about why unifying the branches would be the right move for the code.

Could bugprone-branch-clone be made to detect the presence of a comment in a duplicated branch and not issue warnings about such code?

**Comment by carlosgalvezp** [comment]
Since you already have a comment justifying why the branch must be duplicated, I believe it's not much effort to add one more line with `NOLINTNEXTLINE`. clang-tidy cannot tell if a comment found in a branch is good-enough justification to grant a suppression - this can only be done via code review. Having the `NOLINT` comment is an eye-catcher that is easy to spot during code review and trigger good discussions on how the code can be improved (like in the posted link, where a switch was suggested). 

Since there hasn't been any more activity for 3 years I will close the issue, please open it again if you would like to revisit it.
