### ISSUE TITLE
Missing -Wreturn-type on uninstantiated template

### ISSUE THREAD

**Issue by ThomasCZ** [llvm/llvm-project#45096]
|  |  |
| --- | --- |
| Bugzilla Link | [45751](https://llvm.org/bz45751) |
| Version | unspecified |
| OS | Windows NT |
| Attachments | [screenshot](https://user-images.githubusercontent.com/95090635/143760677-36083b9e-250d-4606-93f0-ef4833e04b9f.gz) |
| CC | @ThomasCZ,@dwblaikie,@zygoloid |

## Extended Description 

Looks like template breaks inspection. Android Studio doesn't show "Control reaches end of non-void function" and "Member function can be static" warnings (maybe more) when using a template.

Is possible to set severity to Error for message "Control reaches end of non-void function"? Application crashes when non-void function does not return something.

Test code:
```
#pragma once

float getFloatValue() {
}

float &getFloatReference() {
}

float *getFloatPointer() {
}

template<typename T>
T doSomething(float a) {
}

template<typename T>
float doSomething(T a, T b) {
}

template<typename T>
struct ClassA {
        ClassA &doSomething();
};

template<typename T>
ClassA<T> &ClassA<T>::doSomething() {
}

struct ClassB {
        float doNothing();
};

float ClassB::doNothing() {
}
```

**Comment by Endilll** [comment]
Nothing has changed since then: https://godbolt.org/z/M3v5sWaqh
```
float getFloatValue() {} // diagnosed
float &getFloatReference() {} // diagnosed
float *getFloatPointer() {} // diagnosed

template<typename T>
T doSomething(float a) {} // shouldn't be diagnosed, I think

template<typename T>
float doSomething(T a, T b) {} // not diagnosed

template<typename T>
struct ClassA {
  ClassA &doSomething();
};

template<typename T>
ClassA<T> &ClassA<T>::doSomething() {} // not diagnosed

struct ClassB {
  float doNothing();
};

float ClassB::doNothing() {} // diagnosed
```

**Comment by dwblaikie** [comment]
So the reason this isn't currently diagnosed is that missing return is diagnosed through clangc's "runtime behavior" warning (it has to prove the path is reachable before warning about it, so it doesn't warn on, say `void f() { while (true) { return false; } /* this isn't really a missing return, because you can't get here */ }`)

And since template parameters can affect what is or isn't reachable (eg: the while condition above could be from a bool non-type-template parameter) we defer any such checking until there's a specific instantiation to check.

We could check the template pattern, but that wouldn't find all missing returns, so we'd have to also check the instantiations then use some mechanism to avoid duplicates between those two approaches. (or, I guess, warn on the template pattern and if any warnings were emitted for it (checking that those warnings weren't suppressed by pragmas or system header suppression, etc... ) - then emit the instantiation ones, if present)

But I think this is probably just a "won't fix" - if someone wanted to write a patch to do all the above work it probably wouldn't be rejected, depending on complexity/tidiness of the implementation, though.
