### ISSUE TITLE
Fix passes that introduce new branches on undef/poison

### ISSUE THREAD

**Issue by fhahn** [llvm/llvm-project#45489]
|  |  |
| --- | --- |
| Bugzilla Link | [46144](https://llvm.org/bz46144) |
| Version | trunk |
| OS | All |
| Depends On | llvm/llvm-project#45301  |
| CC | @efriedma-quic,@eugenis,@LebedevRI,@nunoplopes,@regehr |

## Extended Description 
Currently there are some passes that may introduce new branches on undef/poison, which h potentially introduces UB where there was none before.

While the LangRef was clear about branch on poison being UB, recently it was also clarified that this applies to branches on undef as well (https://reviews.llvm.org/rG05f0e598ab265a80fedb23225cde4176f11774ac).

There has been some discussion about problematic passes (https://reviews.llvm.org/D76973, 
https://reviews.llvm.org/D80875.

Nuno mentioned "The passes we are aware that introduce branch on poison are: IndVarSimplify, LoopUnswitch, SimpleLoopUnswitch, and SimpifyCFG.
(https://web.ist.utl.pt/nuno.lopes/alive2/index.php?hash=4beb2b117e2fdd2c)"

Eli mentioned that some passes condition certain transforms on the`Attribute::SanitizeMemory`attribute, because of MemSAN does not like new branches on undef/poison values. See also llvm/llvm-project#28428

**Comment by fhahn** [comment]
SimpleLoopUnswitch has been fixed, LoopUnswitch has been removed.

**Comment by nikic** [comment]
From https://web.ist.utl.pt/nuno.lopes/alive2/index.php?hash=7fc0899d6af2b9f6 remaining issues are:

 * [ ] https://web.ist.utl.pt/nuno.lopes/alive2/index.php?hash=7fc0899d6af2b9f6&test=Transforms%2FCodeGenPrepare%2FX86%2Fcttz-ctlz.ll (GCP, not relevant for mid-end)
 * [ ] https://web.ist.utl.pt/nuno.lopes/alive2/index.php?hash=7fc0899d6af2b9f6&test=Transforms%2FIndVarSimplify%2Floop-predication.ll (IndVarSimplify, fixed by https://reviews.llvm.org/D124910)
 * [ ] https://web.ist.utl.pt/nuno.lopes/alive2/index.php?hash=7fc0899d6af2b9f6&test=Transforms%2FIndVarSimplify%2Fpost-inc-range.ll (IndVarSimplify, fixed by https://reviews.llvm.org/D124910)
 * [ ] https://web.ist.utl.pt/nuno.lopes/alive2/index.php?hash=7fc0899d6af2b9f6&test=Transforms%2FLoopUnroll%2Fruntime-loop-multiexit-dom-verify.ll (LoopUnroll -- related to previous, but a distinct problem)
 * [ ] https://web.ist.utl.pt/nuno.lopes/alive2/index.php?hash=7fc0899d6af2b9f6&test=Transforms%2FLoopUnroll%2Fruntime-loop-multiple-exits.ll (LoopUnroll)
 * [ ] https://web.ist.utl.pt/nuno.lopes/alive2/index.php?hash=7fc0899d6af2b9f6&test=Transforms%2FPGOProfile%2Fchr.ll (ControlHeightReduction, PGO-only)
 * [ ] https://web.ist.utl.pt/nuno.lopes/alive2/index.php?hash=7fc0899d6af2b9f6&test=Transforms%2FJumpThreading%2Fselect.ll (JumpThreading -- I believe jump-threading-freeze-select-cond fixes this, but actually it would probably be best to remove the select unswitching optimization entirely and directly thread selects instead.)

**Comment by nikic** [comment]
I believe all known issues are fixed now. Let's open new issues if something more turns up.

There's one more followup for CGP (https://reviews.llvm.org/D126638), but it's not a branch on poison issue anymore.
