### ISSUE TITLE
clang crashes on the lsp-plugins-lv2 project

### ISSUE THREAD

**Issue by yurivict** [llvm/llvm-project#45562]
|  |  |
| --- | --- |
| Bugzilla Link | [46217](https://llvm.org/bz46217) |
| Version | 9.0 |
| OS | FreeBSD |
| CC | @DougGregor,@zygoloid |

## Extended Description 
https://people.freebsd.org/~yuri/llvm-crashes-on-sse-cpp-lsp-plugins-lv2.tgz

Project: https://github.com/sadko4u/lsp-plugins

**Comment by Endilll** [comment]
Attached archive ([reupload](https://github.com/llvm/llvm-project/files/12536639/llvm-crashes-on-sse-cpp-lsp-plugins-lv2.tgz)) contains 3 SSE crashes and 3 SSE2 crashes.
All SSE crashes hit the same assertion, which appears to be fixed in Clang 11: https://godbolt.org/z/EEPaPK633
I reduced one of them with C-Reduce, assuming that the rest are the same:
```cpp
float fill_value;
void fill() { __asm__("" : "+Yz"(fill_value)); }
```

SSE2 crashes hit a different assertion in backend, but also appear to be fixed in Clang 11: https://godbolt.org/z/scEj5o44r
I reduced one of them with C-Reduce, assuming that the rest are the same:
```cpp
int min_index_index;
void min_index() { __asm__("" : "=Yz"(min_index_index)); }
```
