### ISSUE TITLE
BraceWrapping: AfterEnum is false, but it does not work

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#46271]
|  |  |
| --- | --- |
| Bugzilla Link | [46927](https://llvm.org/bz46927) |
| Version | 11.0 |
| OS | Linux |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
Brace after enum is broken although BreakBeforeBraces=Attach or AfterEnum=false.

Here is an code example.

```
typedef enum
{
    SVC_DMS = 0,
    SVC_SAR,
    SVC_MAX
} ServiceType;

typedef struct {
    EventType event;
    ServiceType service;
} Event;
```

and this is my .clang-format.

```
BraceWrapping:
  AfterCaseLabel:  false
  AfterClass:      false
  AfterControlStatement: Never
  AfterEnum:       false
  AfterFunction:   false
  AfterNamespace:  false
  AfterObjCDeclaration: false
  AfterStruct:     false
  AfterUnion:      false
  AfterExternBlock: false
  BeforeCatch:     false
  BeforeElse:      false
  BeforeLambdaBody: false
  BeforeWhile:     false
  IndentBraces:    false
  SplitEmptyFunction: true
  SplitEmptyRecord: true
  SplitEmptyNamespace: true
BreakBeforeBinaryOperators: None
BreakBeforeBraces: Attach
```

**Comment by mydeveloperday** [comment]
I believe `BraceWrapping` is ignored unless you have `BreakBeforeBraces: Custom` 

However I think you issue has been fixed

```
typedef enum {
  SVC_DMS = 0,
  SVC_SAR,
  SVC_MAX,
  SVC_1,
  SVC_2,
  SVC_3,
  SVC_4
} ServiceType;

typedef struct {
  EventType event;
  ServiceType service;
} Event;
```

If you format with the following

```
BreakBeforeBinaryOperators: None
BreakBeforeBraces: Attach

```

I think your specific example you need to add the following (at least with the v13 I tried), (which is why I added the extra above.

`AllowShortEnumsOnASingleLine: false`

Also after doing so it shows as

```
typedef enum {
  SVC_DMS = 0,
  SVC_SAR,
  SVC_MAX,
} ServiceType;

typedef struct {
  EventType event;
  ServiceType service;
} Event;
```

I'm going to close this, please reopen if you still see an issue
