### ISSUE TITLE
Support -mstack-protector-guard=sysreg for riscv

### ISSUE THREAD

**Issue by kees** [llvm/llvm-project#46685]
|  |  |
| --- | --- |
| Bugzilla Link | [47341](https://llvm.org/bz47341) |
| Version | trunk |
| OS | Linux |
| Blocks | llvm/llvm-project#4440  |
| CC | @efriedma-quic,@nickdesaulniers,@zygoloid,@stephenhines |

## Extended Description 
The Linux kernel uses this for having a per-thread stack canary. Implementing this for both arm64 and riscv is desired.

For example, gcc's arm64 support is used like this in the kernel:

-mstack-protector-guard=sysreg
-mstack-protector-guard-reg=sp_el0
-mstack-protector-guard-offset=0

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0a1213fa7432778b71a1c0166bf56660a3aab030

Here are discussions on the start of riscv support:

https://lore.kernel.org/lkml/CAJF2gTTr_ENhGRmjqNbGBhEc8y4D3YSqAResvwHuB1ykemKTUw@mail.gmail.com/

**Comment by phoebewang** [comment]
I think we have already supported it, see https://github.com/llvm/llvm-project/commit/7c3fea7721e421de235917d9454d448f976500fc
cc @xiangzh1

**Comment by nickdesaulniers** [comment]
cc @asb

**Comment by xgupta** [comment]
I thought to look at RISCV but it seems they don't have basic stack guard protection. so that needs to be implemented first (like [powerpc](https://github.com/llvm/llvm-project/commit/a1d8bc559761c94dded3d1e7200cb264a982d1c5) or [sparc](https://github.com/llvm/llvm-project/commit/33571e2c415cc4d6f2375a6499278110a65da1b7)) and then customization of stack protector guard.
