### ISSUE TITLE
__builtin_round not constexpr

### ISSUE THREAD

**Issue by carewolf** [llvm/llvm-project#46904]
|  |  |
| --- | --- |
| Bugzilla Link | [47560](https://llvm.org/bz47560) |
| Version | 10.0 |
| OS | Linux |
| CC | @DougGregor,@RKSimon,@zygoloid |

## Extended Description 
The builtin __builtin_round is not constexpr, which is unfortunate as it is nicely replaces with a single fcvtas instruction on arm64 architectures.

The same builtin on GCC is constexpr (though I don't think the C wrapped round functions in cmath is).

**Comment by wheatman** [comment]
closing this issue since this can now be solved with all the cmath round functions being constexpr starting in c++23 https://en.cppreference.com/w/cpp/numeric/math/round

feel free to reopen if this does not solve your issue

It also seems usable with `-std=c++11` since clang 12 (https://godbolt.org/z/z51PWa8bv)
