### ISSUE TITLE
[AMDGPU][MC][GFX10] Too generic error message for missing 'dim' operand

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#47585]
|  |  |
| --- | --- |
| Bugzilla Link | [48241](https://llvm.org/bz48241) |
| Version | trunk |
| OS | All |

## Extended Description 
GFX10 requires that all MIMG instructions specify a dim operand. However when the operand is missing assembler does not report the issue but says that "operands are not valid for this GPU or mode". This should be corrected.

AN example:

    image_load v[0:3], v0, s[0:7] dmask:0xf unorm

    error: operands are not valid for this GPU or mode

**Comment by jwanggit86** [comment]
When the above instruction is matched by calling `MatchInstructionImpl()`. All the operands match with, e.g., the gfx90a version of the instruction, but with the feature "isGfx10Only" missing. On the other hand, this instruction doesn't match any of the gfx10 instructions because of the missing 'dim' operand. Therefore, `MatchInstructionImpl()` returns the error code Error_MIssingFeature, which leads to the error msg above.

**Comment by jwanggit86** [comment]
In `MIMGInstructions.td`, `dim` is a mandatory operand for gfx10 and above. However in the instruction AsmStrings, it is put after `dmask`, which is optional. So we have the following options:
1. Move `dim` in front of `dmask`. For the above example instruction, this will correctly points out that `dmask` is invalid (because `dim` is expected). However, this will break existing assembly code that has `dmask` in front of `dim`. Creating an alias to prevent breaking such existing code does not help the original problem.
2. Make dim optional. Then the example instruction will be matched without problem against the gfx10 version. However, it's not clear what a suitable default value should be for `dim`.
3. Sightly modify the error msg. For example, add something like "check for possibly missing operand". But such error msg still is not precise.
4. Change `dim` to operational, but add a new validation function to ensure `dim` is present. This effectively keeps `dim` mandatory, but allowing it to be optional during the matching phase allows the example instruction to match with intended version.

**Comment by jwanggit86** [comment]
@arsenm Pls let us know your thoughts, particularly on options 3 and 4 above. Thanks!

**Comment by arsenm** [comment]
What is the order and default that sp3 uses?

**Comment by jwanggit86** [comment]
The operand order is as follows: `let AsmString = opcode#" $vdata, $vaddr0, $srsrc$dmask$dim$unorm$cpol$r128$a16$tfe$lwe"`. So `dmask`, which is optional, appears before `dim`, which is non-optional.

In sp3, `dim` is optional, with the default value of 1, meaning 2D array. Also, in sp3, `dim` can appear either before or after `dmask`.

**Comment by jwanggit86** [comment]
Fixed with PR #96588.
