### ISSUE TITLE
Failure to optimize modulo pattern made from division optimally

### ISSUE THREAD

**Issue by GabrielRavier** [llvm/llvm-project#48013]
|  |  |
| --- | --- |
| Bugzilla Link | [48669](https://llvm.org/bz48669) |
| Version | trunk |
| OS | Linux |
| CC | @RKSimon |

## Extended Description 
```
__INT64_TYPE__ f(__INT32_TYPE__ x, __INT32_TYPE__ y)
{
    return (__INT64_TYPE__)y - (y / x) * x;
}
```
This example (and most likely also a more generic form) can be optimized into `return y % x;`. This transformation is done by GCC, but not by LLVM.

**Comment by RKSimon** [comment]
Current Codegen: https://godbolt.org/z/Y7dT8GW93

**Comment by xgupta** [comment]
@RKSimon, Do you have idea where is the relevant source code to add this optimization, I wanted to try. Thanks.

**Comment by RKSimon** [comment]
Its probably just going to have to be a pattern match inside InstCombinerImpl::visitSub.

I'd probably start by working with alive2 to determine the general pattern - and possibly the unsigned variant as well - @rotateright any suggestions?

**Comment by rotateright** [comment]
I'm hoping we can do better than a full pattern-match on that sequence.

If we can recognize that the inputs to the sign-extended subtract have the same sign, then the subtract can be narrowed:
https://alive2.llvm.org/ce/z/Mp48Wv

Once we do that, it should reduce as expected. Unsigned might be easier to start with. It's possible that the no-wrap flags will come into play, but I think we are as good as possible on this pattern after:
https://reviews.llvm.org/D125500

For signed, I was curious how we'd do on that same-sign check. The answer is 'not good', so that's another potential missing piece of the puzzle:
issue #55988

**Comment by rotateright** [comment]
After thinking about it some more, I think we can solve this with a ValueTracking enhancement:
https://reviews.llvm.org/D127754

**Comment by rotateright** [comment]
Fixed with:
8605b4d8c5cc 
...and the related unsigned pattern:
4022551a154e

There are still several potential missed subtract narrowing folds as I mentioned in the commit messages.
