### ISSUE TITLE
Missing known bits info for x*x

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#48027]
|  |  |
| --- | --- |
| Bugzilla Link | [48683](https://llvm.org/bz48683) |
| Version | trunk |
| OS | Linux |
| CC | @RKSimon,@nikic,@rotateright |

## Extended Description 
bool foo(unsigned x) {
    return (x * x) & 2;
}

Square is always congruent to 0 or 1 mod 4 so we can fold it to return false (For knownbits, second LSB is not set).

define i1 @&#8203;src(i32 %0) {
%1:
  %2 = mul i32 %0, %0
  %3 = and i32 %2, 2
  %4 = icmp ne i32 %3, 0
  ret i1 %4
}
=>
define i1 @&#8203;tgt(i32 %0) {
%1:
  ret i1 0
}
Transformation seems to be correct!

https://en.wikipedia.org/wiki/Quadratic_reciprocity

**Comment by rotateright** [comment]
knownbits support was added here:
0a07ae6ebfffb7724

And a fold was enabled in the backend with:
d6fee6c3b0e7449d

So that was enough to fix the example if compiled through to x86 asm.

It was then noted that the transform is not safe with 'undef' (but it's ok with poison), so we need another check:
48f45f6b25f086e5c

That's still ok with the example here, but made the transform less effective/general.

But we can also handle the pattern in the description using demanded bits, so that's in the backend now too:
2d1390efbe610ff15a

**Comment by rotateright** [comment]
More improvements in demanded bits for multiply in IR:
5372160a188e
79b3fe80707b
897d92faeff6

And for consistency, we have the folds in codegen too:
fc6bee1c11d4
d1ecfaa097b1

I think that concludes work inspired by this report.
