### ISSUE TITLE
[AMDGPU][MC][GFX10] Incorrect handling of FLAT instructions with saddr=null

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#48508]
|  |  |
| --- | --- |
| Bugzilla Link | [49164](https://llvm.org/bz49164) |
| Version | trunk |
| OS | All |

## Extended Description 
FLAT GLOBAL instructions with saddr=null are handled incorrectly. 'null' is an alias for 'off' but it is handled as a regular register and results in an invalid vaddr size.

Examples:

    global_atomic_add v1, v2, null

This is not a valid code but it is assembled ok and results in the same encoding as the following legal instruction:

    global_atomic_add v[1:2], v2, off

There is a similar issue with FLAT SCRATCH instructions. For example, the following instruction is illegal, but it is accepted by llvm assembler:

    scratch_load_ubyte v1, off, null

The produced code is the same as generated for the following legal instruction:

    scratch_load_ubyte v1, v0, off

**Comment by jwanggit86** [comment]
@dpreobra In the problem description, you mentioned "'null' is an alias for 'off'". Could you pls point to me where this statement can be found? Based on my investigation, it appears GFX10 introduced a new reg SGPR_NULL which is represented with null.

**Comment by dpreobra** [comment]
You won't find a description of "off" operand in the official AMD documentation. However, SP3 documentation for GFX10 clearly states that "In sp3 an SGPR address may be omitted by specifying "off" or "null" in the SADDR operand slot". 

Yes, the "null" operand is defined as SGPR_NULL in llvm code.

**Comment by jwanggit86** [comment]
So the instruction `global_atomic_add v1, v2, null` is perfectly fine for GFX10?

**Comment by dpreobra** [comment]
> So the instruction `global_atomic_add v1, v2, null` is perfectly fine for GFX10?

According to AMD documentation, when SADDR is omitted, VADDR must be 64 bit. So the following instructions are illegal and should be rejected by assembler:

    global_atomic_add v1, v2, null
    global_atomic_add v1, v2, off

And the following instructions are legal:

    global_atomic_add v[1:2], v2, null
    global_atomic_add v[1:2], v2, off

**Comment by arsenm** [comment]
I would assume the operand type for this operand to be a different class that excludes null (e.g. MCK_SReg_64_XEXEC_XNULL)

**Comment by jwanggit86** [comment]
Brief summary of the problem. In LLVM there are 2 variants for flat instructions: no-return (3 required operands) and with-return (4 required operands). The latter has an extra required operand, i.e., the 1st operand representing destination. Within each variant there are 2 versions, e.g for the no-return variant:
- `" $vaddr, $vdata, off$offset$cpol"`: the 3rd operand is "off"; the 1st operand is 64b.
- `" $vaddr, $vdata, $saddr$offset$cpol"`: the 3rd operand is "saddr", which must be SReg_64; the 1st operand is 32b.
Because "null" is allowed to match SReg_64, the following instruction is allowed where "null" is parsed as the saddr: `global_atomic_add v1, v2, null`. The problem is the following 2 instructions produce the same encoding, making it ambiguous to decode:
```
global_atomic_add v[1:2], v2, off       ; encoding: [0x00,0x80,0xc8,0xdc,0x01,0x02,0x7d,0x00]
global_atomic_add v1, v2, null          ; encoding: [0x00,0x80,0xc8,0xdc,0x01,0x02,0x7d,0x00]
```
Similarly, the following 2 instructions also have the same encoding:
```
global_atomic_add v1, v2, v3, null glc  ;   encoding: [0x00,0x80,0xc9,0xdc,0x02,0x03,0x7d,0x01]
global_atomic_add v1, v[2:3], v3, off glc ; encoding: [0x00,0x80,0xc9,0xdc,0x02,0x03,0x7d,0x01]
```
So, "null" as saddr should be disallowed.

**Comment by jwanggit86** [comment]
PR 101730 fixed this.
