### ISSUE TITLE
__has_declspec_attribute falsely reports some attrs as supported for MinGW and Cygwin targets

### ISSUE THREAD

**Issue by 2e1c2d01-a631-41c2-93fe-8d40b95d8607** [llvm/llvm-project#49958]
|  |  |
| --- | --- |
| Bugzilla Link | [50614](https://llvm.org/bz50614) |
| Version | 12.0 |
| OS | Linux |
| Attachments | [Repro](https://user-images.githubusercontent.com/95090385/143762199-43fe0d13-79e7-4c11-981b-be5f574d9856.gz) |
| CC | @zygoloid |

## Extended Description 

It is true that the warnings for this specific repro can be silenced by adding the -fms-extensions option, but this option causes other problems in practice (causing function redefinition errors) and so I think I cannot use it.

$ cat mingw-declspec.c

#if __has_declspec_attribute(noalias)
__declspec(noalias)
#else
#warning no declspec noalias
#endif
void foo(void *a, void *b);

struct
#if __has_declspec_attribute(align)
__declspec(align(8))
#else
#warning no declspec align
#endif
bar { int i, j; } baz;

$ clang --target=x86_64-w64-mingw32 -fdeclspec -c mingw-declspec.c
mingw-declspec.c:3:12: warning: unknown attribute 'noalias' ignored [-Wunknown-attributes]
__declspec(noalias)
           ^~~~~~~
<built-in>:343:38: note: expanded from here
#define __declspec(a) __attribute__((a))
                                     ^
mingw-declspec.c:11:12: warning: unknown attribute 'align' ignored [-Wunknown-attributes]
__declspec(align(8))
           ^~~~~~~~
<built-in>:343:38: note: expanded from here
#define __declspec(a) __attribute__((a))
                                     ^
2 warnings generated.

**Comment by alejandro-colomar** [comment]
I reproduced something similar.

Originally received a report in Nginx Unit <https://github.com/nginx/unit/issues/653>,
and later reported to ruby <https://bugs.ruby-lang.org/issues/18616>,
it now seems to me a clang bug.

Reproducer:

```c
$ cat declspec.c 
#include <stdio.h>

int main(void)
{
	printf("%i\n", __has_declspec_attribute(noreturn));
}
```
In Debian:
```sh
$ clang -Weverything declspec.c
$ ./a.out 
0
$ clang -Weverything -fdeclspec declspec.c
$ ./a.out 
1
$ clang -v
Debian clang version 13.0.1-3
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

**Comment by alvinhochun** [comment]
@alejandro-colomar:
As of https://github.com/LLVM/llvm-project/commit/ef3800e82169c674219501d9ac09ef12b28e6359, `__has_declspec_attribute(x)` will always return false when `__declspec` is not enabled (i.e. without `-fdeclspec`). If the behaviour of Apple Clang is different, that sounds like a bug specific to Apple Clang which should be reported to Apple (I am unfamiliar with how Apple handles __declspec.)

The original bug report refers to a different issue, caused by a built-in `#define __declspec(a) attribute((a))` specifically added for MinGW/Cygwin targets incorrectly when `-fdeclspec` is enabled. I've submitted a fix: https://reviews.llvm.org/D135027
