### ISSUE TITLE
[llvm-mca] Improve barriers for strict region marking

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#51540]
|  |  |
| --- | --- |
| Bugzilla Link | [52198](https://llvm.org/bz52198) |
| Version | trunk |
| OS | Windows NT |
| CC | @adibiagio,@LebedevRI |

## Extended Description 
https://godbolt.org/z/er1Wsb3da

Efficiently calculating the interleaved load/store costs has been greatly hindered as the llvm-mca region markers aren't great barriers.

https://reviews.llvm.org/D111945

Even if it affects codegen, it'd be very useful if we can get llvm-mca to give us at least an estimate of costs so we can automate this a little.

**Comment by adibiagio** [comment]
> Efficiently calculating the interleaved load/store costs has been greatly hindered as the llvm-mca region markers aren't great barriers.

In the docs, we suggest to use the following syntax for code region markers:

  __asm volatile("# LLVM-MCA-BEGIN foo");
  __asm volatile("# LLVM-MCA-END");

Part of the issue is that those are not proper compilation barriers. Something like this would be much better:

  __asm volatile("# LLVM-MCA-BEGIN foo":::"memory");
  __asm volatile("# LLVM-MCA-END":::"memory");

NOTE: it won't fix all the issues related to region markers. However, it would make things better in some (hopefully most) cases.
The reason why explicitly adding {rsp} to the clobber list helps is because presumably region markers weren't declared as clobbering "memory" in the first place.

I think that we should update the docs. It won't solve the issue with barriers, but it would definitely help in some cases.

**Comment by RKSimon** [comment]
doc fix - https://reviews.llvm.org/D117788

**Comment by RKSimon** [comment]
Committed at 0ca426d6ac65b84c70ac7fd9511628ce5115423e
