### ISSUE TITLE
Enhance sparse->sparse conversions (medium level starter, fun research)

### ISSUE THREAD

**Issue by aartbik** [llvm/llvm-project#51652]
|  |  |
| --- | --- |
| Bugzilla Link | [52310](https://llvm.org/bz52310) |
| Version | unspecified |
| OS | Linux |
| CC | @joker-eph |

## Extended Description 
The sparse_tensor.convert operation provides dense->sparse, sparse->sparse, and sparse->dense conversion, useful for testing but also (mainly sparse->sparse) for production code.

Currently the sparse->sparse conversion is always implemented as
(1) convert source to COO
(2) construct dest from COO

Using COO as intermediate avoids the full n^2 conversion matrix implementation. However, the performance is not always optimal.

This entry requests investigating what sparse->sparse conversions are commonly used (e.g. CSR to CSC), what the current performance is, and if there are better ways. Where useful, the current lowering code in the compiler (see SparseTensorConvertConverter in https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/SparseTensor/Transforms/SparseTensorConversion.cpp) should specialize into a better implementation.

Relevant paper [Chou et al.]:
https://arxiv.org/abs/2001.02609

**Comment by aartbik** [comment]
Thanks for your interest in helping out! Please note that this bug assigned to @wrengr who has started work on this, so please coordinate any future design plans first before starting the actual code.

**Comment by usama54321** [comment]
@aartbik Thanks I will do that!

**Comment by wrengr** [comment]
The following changes implement this change. The earlier ones have landed, but the latter ones are still in review. Once D122061 lands we can close this ticket.

- [D122054](https://reviews.llvm.org/D122054) Introducing options for the `SparseTensorConversion` pass
- [D122055](https://reviews.llvm.org/D122055) Adding `Action::kSparseToSparse` for `@newSparseTensor`
- [D122435](https://reviews.llvm.org/D122435) Moving `delete coo` into codegen instead of runtime library
- [D122928](https://reviews.llvm.org/D122928) Moving `<P,I,V>`-invariant parts of `SparseTensorStorage` to the base class
- [D122060](https://reviews.llvm.org/D122060) Factoring out an enumerator over elements of `SparseTensorStorage`
- [D122061](https://reviews.llvm.org/D122061) Enhancing sparse=>sparse conversion
