### ISSUE TITLE
Incorrect result with -O1 -march=skx

### ISSUE THREAD

**Issue by Vsevolod-Livinskij** [llvm/llvm-project#51677]
|  |  |
| --- | --- |
| Bugzilla Link | [52335](https://llvm.org/bz52335) |
| Version | trunk |
| OS | Linux |
| CC | @dbabokin,@topperc,@RKSimon,@phoebewang,@regehr,@rotateright,@Vsevolod-Livinskij |

## Extended Description 
It looks like LoopVectorizePass introduces changes that uncover a bug in the backend. The transformation was verified with alive2. I've attached C++ and LLVM IR reproducers.

C++ reproducer:
```
// func.cpp
extern int var_3;
extern bool var_23;
extern int arr_12[];
extern short arr_13[];
void test() {
#pragma clang loop vectorize_predicate(enable)
  for (char a = 4; a < var_3; a++) {
    arr_13[a] = arr_12[a - 3];
    var_23 = arr_12[a - 1];
  }
}

// driver.cpp 
#include <stdio.h>

int var_3 = 24;
bool var_23 = 1;
int arr_12 [25];
unsigned short arr_13 [25];

void test();

int main() {
    for (size_t i_0 = 0; i_0 < 25; ++i_0)
        arr_12 [i_0] = 1;
    test();
    printf("%d\n", (int)var_23);
}
```
>$ clang++ -O0 -march=skx func.cpp driver.cpp && sde -skx -- ./a.out 
1
>$ clang++ -O1 -march=skx func.cpp driver.cpp && sde -skx -- ./a.out 
0

LLVM IR Reproducer:
```
; ModuleID = 'func.cpp'
source_filename = "func.cpp"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@var_3 = external dso_local local_unnamed_addr global i32, align 4
@arr_12 = external dso_local local_unnamed_addr global [0 x i32], align 4
@arr_13 = external dso_local local_unnamed_addr global [0 x i16], align 2
@var_23 = external dso_local local_unnamed_addr global i8, align 1

; Function Attrs: mustprogress nofree norecurse nosync nounwind uwtable
define dso_local void @_Z4testv() local_unnamed_addr #0 {
entry:
  %0 = load i32, i32* @var_3, align 4, !tbaa !3
  %cmp13 = icmp sgt i32 %0, 4
  br i1 %cmp13, label %for.body.preheader, label %for.cond.cleanup

for.body.preheader:                               ; preds = %entry
  br label %for.body

for.cond.for.cond.cleanup_crit_edge:              ; preds = %for.body
  %conv15.lcssa = phi i32 [ %conv15, %for.body ]
  %sub6 = add nsw i32 %conv15.lcssa, -1
  %idxprom7 = sext i32 %sub6 to i64
  %arrayidx8 = getelementptr inbounds [0 x i32], [0 x i32]* @arr_12, i64 0, i64 %idxprom7
  %1 = load i32, i32* %arrayidx8, align 4, !tbaa !3
  %tobool = icmp ne i32 %1, 0
  %frombool = zext i1 %tobool to i8
  store i8 %frombool, i8* @var_23, align 1, !tbaa !7
  br label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond.for.cond.cleanup_crit_edge, %entry
  ret void

for.body:                                         ; preds = %for.body.preheader, %for.body
  %conv15 = phi i32 [ %conv, %for.body ], [ 4, %for.body.preheader ]
  %a.014 = phi i8 [ %inc, %for.body ], [ 4, %for.body.preheader ]
  %sub = add nsw i32 %conv15, -3
  %idxprom = sext i32 %sub to i64
  %arrayidx = getelementptr inbounds [0 x i32], [0 x i32]* @arr_12, i64 0, i64 %idxprom
  %2 = load i32, i32* %arrayidx, align 4, !tbaa !3
  %conv2 = trunc i32 %2 to i16
  %idxprom3 = sext i8 %a.014 to i64
  %arrayidx4 = getelementptr inbounds [0 x i16], [0 x i16]* @arr_13, i64 0, i64 %idxprom3
  store i16 %conv2, i16* %arrayidx4, align 2, !tbaa !9
  %inc = add i8 %a.014, 1
  %conv = sext i8 %inc to i32
  %cmp = icmp sgt i32 %0, %conv
  br i1 %cmp, label %for.body, label %for.cond.for.cond.cleanup_crit_edge, !llvm.loop !11
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind uwtable "frame-pointer"="none" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="skx" "target-features"="+adx,+aes,+avx,+avx2,+avx512bw,+avx512cd,+avx512dq,+avx512f,+avx512vl,+bmi,+bmi2,+clflushopt,+clwb,+crc32,+cx16,+cx8,+f16c,+fma,+fsgsbase,+fxsr,+invpcid,+lzcnt,+mmx,+movbe,+pclmul,+pku,+popcnt,+prfchw,+rdrnd,+rdseed,+sahf,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+ssse3,+x87,+xsave,+xsavec,+xsaveopt,+xsaves" }

!llvm.module.flags = !{#0, !&#8203;1}
!llvm.ident = !{#2}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 7, !"uwtable", i32 1}
!2 = !{!"clang version 14.0.0 (https://github.com/llvm/llvm-project.git 2d77b272a8f9b5b89b022628ca30b6b896a8f725)"}
!3 = !{#4, !4, i64 0}
!4 = !{!"int", !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C++ TBAA"}
!7 = !{#8, !8, i64 0}
!8 = !{!"bool", !5, i64 0}
!9 = !{#10, !10, i64 0}
!10 = !{!"short", !5, i64 0}
!11 = distinct !{#11, !12, !13, !14, !15}
!12 = !{!"llvm.loop.mustprogress"}
!13 = !{!"llvm.loop.unroll.disable"}
!14 = !{!"llvm.loop.vectorize.predicate.enable", i1 true}
!15 = !{!"llvm.loop.vectorize.enable", i1 true}
```
>$ clang++ -O0 ok.ll driver.cpp && sde -skx -- ./a.out 
1
>$ opt -loop-vectorize ok.ll > opt.ll && clang++ -O0 opt.ll driver.cpp && sde -skx -- ./a.out 
0

LLVM version:
clang version 14.0.0 (https://github.com/llvm/llvm-project.git 2d77b272a8f9b5b89b022628ca30b6b896a8f725)

**Comment by rickyz** [comment]
Here's a small repro:
```c
#include <stddef.h>
#include <stdint.h>

int test(int* arr, size_t n) {
  int value = 0;
#pragma clang loop vectorize_predicate(enable)
  for (uint8_t i = 1; i < n; ++i) {
    arr[i - 1] = 0x41;
    value = arr[i];
  }
  return value;
}
```

Note that this C no longer miscompiles on the latest clang build from git main, as the InstCombine pass now changes `i` to an i64 that is masked with 0xff. This seems to prevent LoopVectorizationLegality from detecting `i` as an induction variable, so the loop cannot be vectorized at all. I ended up having to extract IR from an older version of clang to repro this bug (see repro.ll).

```
$ opt -passes=loop-vectorize repro.ll -S > after_vectorize.ll # See attached after_vectorize.ll.
```

The loop vectorization pass generates incorrect code. The `for.cond.for.cond.cleanup_crit_edge` block outside of the loop is responsible for loading `arr[i]` from the last iteration into `value`. When this block is reached from the vectorized loop via `middle.block`, the index for the load ends up equaling `%n.vec`, which is the number of loop iterations (`n - 1`) rounded up to the next multiple of 4. When the number of iterations isn't divisible by 4, this causes the load to read past the end of `arr`.

Reading through https://github.com/llvm/llvm-project/blob/04d083b/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp, we see that `%n.vec` is generated here:
https://github.com/llvm/llvm-project/blob/04d083b/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp#L3144-L3191

Usually, the vector trip count is equal to the trip count rounded down to the next multiple of the step. However, the loop vectorization code supports "tail loop folding," where the final iteration of the vectorized loop is able to handle a number of elements than less than the step size by masking the vector operations appropriately. In that case, the vector trip count is equal to the trip count rounded /up/ to the next multiple of the step size.

The vector trip count is passed here

https://github.com/llvm/llvm-project/blob/04d083b/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp#L4104-L4106

which ends up generating the index computation in `middle.block` here:

https://github.com/llvm/llvm-project/blob/04d083b/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp#L3759-L3787

The vector trip count is passed in an argument named `CountRoundDown`, which implies that the rounded-up value in the tail loop folding case is not expected here. This is how we end up computing the incorrect index described above.

Looking at how loop vectorization decides whether to perform tail loop folding, it seems like tail loop folding isn't supposed to be allowed when there are uses of induction variables outside of the loop:
https://github.com/llvm/llvm-project/blob/04d083b/llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp#L1253-L1278

Adding some debugging prints to this code shows that the induction variable `%conv12` in repro.ll is missing from `AllowedExit` despite being used outside of the loop. The reason is this logic:
https://github.com/llvm/llvm-project/blob/04d083b/llvm/lib/Transforms/Vectorize/LoopVectorizationLegality.cpp#L549-L558

This code claims to disallow external uses of the induction PHI node if its SCEV might rely on predicates that might not hold outside of the loop (in the case of this bug, I'm guessing there is a predicate on the the i8 IV not overflowing). However, it never actually checks for external uses of the PHI node (on the other hand, uses of the "post-increment" value will be properly checked when `LoopVectorizationLegality::canVectorizeInstrs()` processes that instruction). The only effect of this logic on the PHI node is that that it skips adding it to `AllowedExit`. This hides the the PHI from the tail loop folding logic, which expects all externally used values to appear in `AllowedExit`.

If I understand correctly, it should be safe to use the induction variable externally, since all of the necessary SCEV predicates should have held at the time that it was computed. If this is correct, then we can fix this bug by unconditionally adding the induction PHI to `AllowedExit` in `LoopVectorizationLegality::addInductionPhi()`.

I mailed https://reviews.llvm.org/D115109 a few days ago to try to fix this (only commenting here now since the BZ migration just completed :-))

**Comment by rickyz** [comment]
Oops, forgot to attach the files mentioned above:
[after_vectorize.ll.txt](https://github.com/llvm/llvm-project/files/7696988/after_vectorize.ll.txt)
[repro.ll.txt](https://github.com/llvm/llvm-project/files/7696989/repro.ll.txt)
