### ISSUE TITLE
list constructor does not use correct allocator

### ISSUE THREAD

**Issue by 7d5b63e0-038f-4eec-81b4-58b6a93e579c** [llvm/llvm-project#51816]
|  |  |
| --- | --- |
| Bugzilla Link | [52474](https://llvm.org/bz52474) |
| Version | 11.0 |
| OS | All |
| CC | @mclow |

## Extended Description 
If an allocator is not specified for a list constructor call, the allocator used should be the lists allocator.   It seems this is not the case for libc++

Consider the following from a cygwin cut/paste where the g++ library seems to do the right thing, but libc++ does not:

```
$ cat t.cpp
#include <list>
#include <memory>
#include <cstdio>

struct myalloc : public std::allocator<int> {
  myalloc() { printf("in ialloc\n"); }
};

int main(void)
{
  // This should use the myalloc allocator, it does not
  std::list<int,myalloc> c00((std::list<int,myalloc>::size_type) 3);
}

VogelEd@XLB3502Q4E ~
$ clang++  -o a.out t.cpp

VogelEd@XLB3502Q4E ~
$ ./a.out
in ialloc

VogelEd@XLB3502Q4E ~
$ clang++  -o a.out -stdlib=libc++ t.cpp

VogelEd@XLB3502Q4E ~
$ ./a.out

VogelEd@XLB3502Q4E ~
```

Not an important problem, but one found by our verification tests.

Thank you,

Ed Vogel

**Comment by cneumann** [comment]
Drive by comment, feel free to ignore 😃 
No idea what the standard says about this, but in practice a `std::list` implementation mostly cares about the allocator for its node type, i.e. [`typedef typename __rebind_alloc_helper<__alloc_traits, __node>::type __node_allocator`](https://github.com/llvm/llvm-project/blob/6d702a1e6a069e22e4b7f679a408e95bcc7db66c/libcxx/include/list#L553). Your `myalloc` does not define its own `rebind_alloc` member template struct, instead re-using the inherited one, so `__node_allocator` is `std::allocator<__node>` and default constructing an instance of that naturally does not print anything.
To me this comes down to the question if the standard requires instantiating the exact allocator type passed as template argument vs. allowing to instantiate only (!) rebound "versions" of it.

**Comment by Quuxplusone** [comment]
@cneumann's diagnosis looks correct to me.

[Notice](https://en.cppreference.com/w/cpp/memory/allocator) that `std::allocator<T>::rebind` was actually removed in C++20, which means that [all vendors reject your test program as of C++20](https://godbolt.org/z/9nd4MGcod) — there's no longer any way to allocate a `Node` using a `myalloc` object, because `std::allocator_traits<myalloc>::rebind_alloc<Node>` no longer denotes an allocator type.

Also [notice](https://godbolt.org/z/hT9KhqYs1) that actually *none* of the big three vendors put a `myalloc` data member inside the `std::list` object. GCC default-constructs a `myalloc` only because their constructor uses [default function arguments](https://quuxplusone.github.io/blog/2020/04/18/default-function-arguments-are-the-devil/) instead of an overload set: they have
```
explicit list(size_type __n, const value_type& __value = value_type(),
    const allocator_type& __a = allocator_type())
```
so when you call `list(3)` you're really calling `list(3, 0, myalloc())`. That's where the extra constructor call is coming from on libstdc++ in particular, and it's a deficiency-not-a-feature.

So I think there's nothing here for libc++ to change.
