### ISSUE TITLE
llvm-objcopy: "error: invalid symbol index" with mips64el-linux-gnuabi64

### ISSUE THREAD

**Issue by nathanchance** [llvm/llvm-project#52647]
Initial reported and triaged at https://github.com/ClangBuiltLinux/linux/issues/1534.

While building the Linux kernel with `OBJCOPY=llvm-objcopy`, the following error is observed:

```
llvm-objcopy: error: invalid symbol index: 67108864
make: *** [Makefile:1161: vmlinux] Error 1
```

This appears to be related to the use of `-EL` and `-mabi=64`. A very simple C reproducer:

```
$ cat test.c
void lkdtm_rodata_do_nothing() {}

$ clang --target=mips64el-linux-gnuabi64 -c test.c

$ llvm-objcopy test.o test_objcopy.o
llvm-objcopy: error: invalid symbol index: 33554432
```

It does not happen with `mips64-linux-gnuabi64` or 32-bit MIPS targets.

**Comment by jh7370** [comment]
I think the problem is in `initRelocations` in the llvm-objcopy code: it has references to `Rel.getType(false)` and `Rel.getSymbol(false)`. The latter in particular is likely the culprit, but both are probably wrong, based on my reading of this bug: the boolean corresponds to an `isMips64EL`, which I'd expect to be true for the test case.

The fix will be to pass this information to these functions, and quite possibly other functions in the code (I see a reference to `getSymbolAndType` in `writeRel` that also has a suspicious hard-coded false).

Unfortunately, my MIPS knowledge is limited, so I don't know how to get the proper value for the `isMips64EL` parameter from the object into llvm-objcopy. As such, I cannot provide a fix myself.

**Comment by atanasyan** [comment]
I will take a look at this bug.

**Comment by atanasyan** [comment]
The fix is in the https://reviews.llvm.org/D115635.

**Comment by nathanchance** [comment]
Thanks Simon!

https://github.com/llvm/llvm-project/commit/d5d8b1c972bca995133f358f01ce474fb8d0b669
