### ISSUE TITLE
libcxx's `sort(it1, it2)` unnecessarily requires that op< should be callable on const& lhs/rhs

### ISSUE THREAD

**Issue by nsmrnsmr** [llvm/llvm-project#52650]
[alg.sorting] does not require that op< should be callable on const& lhs/rhs.  It seems that libcxx's `sort(it1, it2)` calls `__less`, which requires this condition.

This code compiles fine on libstdc++ with GCC and MSSTL with VC++, but fails to compile on libcxx (trunk):
```
#include <algorithm>
struct Type{
  int x;
  bool operator<(Type const& other) { return x < other.x; }
};
int main(){
  Type array[2] = {};
  std::sort(array, array + 2); // Error: Type's op < is not callable on const& lhs/rhs
}
```

**Comment by nsmrnsmr** [comment]
To be precise, [alg.sorting] does not require that op< should be callable on const& lhs/rhs for `sort`. (Note that `ranges::sort` _does_ require the condition, but `sort` doesn't.)

**Comment by Quuxplusone** [comment]
https://eel.is/c++draft/algorithms.requirements#8.sentence-5 definitely requires that the `comp` in `std::sort(first, last, comp)` should be callable on const& lhs/rhs.

https://eel.is/c++draft/alg.sorting#general-3.sentence-2 says that, quote, "`comp(*i, *j) != false` defaults to `*i < *j != false`," which can _kinda_ be read as implying that in those cases, `op<` shall induce a strict weak ordering, and `op<` shall meet the requirements for a template parameter named `BinaryPredicate`, and so on and so forth. It doesn't _literally_ say that, though, I agree (as far as I can tell).

To me this seems like less of a libc++ bug and more of an LWG issue: the Standard uses vague words like "`comp(*i, *j) != false` defaults to `*i < *j != false`" without really saying what that means. Also, if this situation ever happens in real code it's clearly due to programmer error. libc++ is doing the programmer a favor: "Hey, you missed a `const` keyword here!" I'd call this Not A Bug.

**Comment by philnik777** [comment]
I'm with Arthur on this one. I don't think libc++ is doing anything wrong here, and IMO this should be rejected as a matter of QoI.
