### ISSUE TITLE
MSVC -std=xx argument not supported by clang-tidy 13.0.0

### ISSUE THREAD

**Issue by martingalvan-nordic** [llvm/llvm-project#52662]
This was previously reported at https://bugs.llvm.org/show_bug.cgi?id=45017. We had worked around this by passing `--extra-arg-before=--driver-mode=cl` to clang-tidy; however, since 13.0.0 this breaks anyway with the following error:

`error: unknown argument ignored in clang-cl: '-std=c++17' [clang-diagnostic-unknown-argument,-warnings-as-errors]`

clang-tidy 12.0.1 works fine.

**Comment by martingalvan-nordic** [comment]
I just did a bit more testing. It appears that clang-tidy will accept `/std:c++17` when using the cl driver, but not `-std=c++17`. I wonder what was the reason for this change, since 12.0.1 was working fine with the latter.

**Comment by PiotrZSL** [comment]
No issue here, this is expected behavior, use /std:c++17, same behavior is with clang-cl.
Most probably it were broken before.
And to handle properly /std:c++ you may need to wait for a #66553 or pass it after -- or in compile commands file.

As for 12 vs 13, simply looks like it were broken on 12, and it behave more correctly.
