### ISSUE TITLE
clang 13 dropping debug symbols for types

### ISSUE THREAD

**Issue by hotsphink** [llvm/llvm-project#52710]
First reported at https://bugzilla.mozilla.org/show_bug.cgi?id=1739321

I have a large source file that defines the class `JSString` and a subclass `JSLinearString` (among many others). The debuginfo is present for `JSLinearString`, but missing for `JSString`. (`ptype JSLinearString` in gdb shows the full class definition, including inheriting from `JSString`; `ptype JSString` fails and says there is no such symbol.)

The DWARF info shows a forward declaration of `JSString` but no definition.

clang 12 did not have this problem, nor does gcc.

The DWARF info for the .o file contains:
```
<1><48cbf>: Abbrev Number: 43 (DW_TAG_class_type)
    <48cc0>   DW_AT_calling_convention: 4       (pass by ref)
    <48cc1>   DW_AT_name        : (indirect string, offset: 0x6830): JSLinearString
    <48cc5>   DW_AT_byte_size   : 24
    <48cc6>   DW_AT_decl_file   : 25
    <48cc7>   DW_AT_decl_line   : 788
 <2><48cc9>: Abbrev Number: 5 (DW_TAG_inheritance)
    <48cca>   DW_AT_type        : <0x4862b>
    <48cce>   DW_AT_data_member_location: 0
    <48ccf>   DW_AT_accessibility: 1    (public)
    ...
```
so a complete declaration of JSLinearString. It is tagged as inheriting from 0x4862b, which is:
```
 <1><4862b>: Abbrev Number: 19 (DW_TAG_class_type)
    <4862c>   DW_AT_name        : (indirect string, offset: 0x44c1): JSString
    <48630>   DW_AT_declaration : 1
 <2><48630>: Abbrev Number: 20 (DW_TAG_subprogram)
    <48631>   DW_AT_linkage_name: (indirect string, offset: 0x2b059): _ZN8JSString23fillWithRepresentativesEP9JSContextN2JS6HandleIPN2js11ArrayObjectEEE
    <48635>   DW_AT_name        : (indirect string, offset: 0x2b0ac): fillWithRepresentatives
    <48639>   DW_AT_decl_file   : 25
    ...
```

**Comment by hotsphink** [comment]
Full preprocessed source file: [original.txt](https://github.com/llvm/llvm-project/files/7716163/original.txt)
Compile with `clang -x c++ -std=c++17 -c -g original.txt`

Reduced version with the same problem, but if either `static size_t dummy = sizeof(JSString)` or `class JSRope : public JSString {};` are added, the problem is fixed: [fixable.txt](https://github.com/llvm/llvm-project/files/7716205/fixable.txt)

Much, much reduced (but not minimal) version that, uh, doesn't seem to emit any symbols at all unless a use of one of the types `JSString` or `JSRope` (which inherits from `JSString`) is added of some sort: [small.txt](https://github.com/llvm/llvm-project/files/7716206/small.txt)

**Comment by dwblaikie** [comment]
This is probably constructor homing at work ( https://blog.llvm.org/posts/2021-04-05-constructor-homing-for-debug-info/ )

It /looks/ like JSString has only deleted constructors, so the code's probably invoking UB by "faking" these objects through some construction that doesn't invoke the ctors - and without generating code for ctors the debug info for those types will be omitted.

You can workaround this by tagging the types `[[clang::standalone_debug]]` attribute, or by compiling with `-fstandalone-debug` - or fixing the type to not use UB - calling placement new on some memory, for instance would be usable.

(it's possible the ctor homing could be disabled for a type with all deleted constructors - since it's clear it won't ever have a home, but also clear the code's UB too... )

@amykhuang (as the author of ctor homing)

**Comment by hotsphink** [comment]
I believe you're right. It looks like our allocation path boils down to doing a `reinterpret_cast` of a bump-allocated pointer. From C++'s standpoint, no memory ever contains a JSString.

I apologize for the mean thoughts I have entertained towards clang 13. I prefer the new behavior and would rather change our code than work around it with flags or attributes. It's going to be a pain to change, though; we don't have detailed subtype information where we need it at the moment.
