### ISSUE TITLE
enabling libcurl support for lldb results in libcurl getting pulled into Mesa drivers

### ISSUE THREAD

**Issue by smcv** [llvm/llvm-project#52731]
In recent prereleases of LLVM 14, the Debuginfod component has gained an optional dependency on libcurl. It's off by default (since https://reviews.llvm.org/D115500), but I expect that general-purpose Linux distributions will probably want to enable it, to give `lldb` the same level of support for downloading debug symbols as `gdb`.

Linux distributions typically build LLVM with `-DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_LINK_LLVM_DYLIB=ON`, which results in one large `libLLVM-X.so.Y` containing everything, including the Debuginfod component. This means libLLVM can end up depending on libcurl.

Some Mesa OpenGL and Vulkan drivers (such as RADV and llvmpipe) are linked with libLLVM, so this brings libcurl into the dependencies of Mesa drivers, which get loaded by games and other 3D applications.

These extra dependencies can become a problem when sharing graphics drivers between runtime environments that use a special `LD_LIBRARY_PATH`, and in particular the Steam Runtime, which has an incompatible build of libcurl for historical reasons. Games often use strange library stacks that aren't completely compatible with application-level system libraries like libcurl, but still want to use system graphics drivers.

I'm also concerned that the indirect dependency on OpenSSL could cause crashes when loaded by programs that statically link a different version of OpenSSL, similar to the way an indirect dependency from GTK, via GLib, libmount and libcryptsetup, to OpenSSL caused crashes in https://github.com/ValveSoftware/steam-for-linux/issues/7223.

More discussion here: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5732

## Possible solutions

* split the Debuginfod component into a separate, smaller shared library, used by `lldb` and maybe `llvm-symbolize` but not part of `libLLVM`
    * from https://reviews.llvm.org/D113717#3189211 it looks like this might be desirable for other reasons too
* and/or load libcurl "lazily" with `dlopen()` instead of "eagerly" with `-lcurl`

## Workarounds

* (encourage distros to) build LLVM with the libcurl feature disabled
* or (encourage distros to) statically link LLVM components into Mesa instead of linking dynamically (it is unconfirmed whether this works)

**Comment by tstellar** [comment]
I think splitting the Debuginfod component into a separate library is the best solution.

**Comment by petrhosek** [comment]
We discussed this with @nico @dwblaikie @noajshu and our proposal is to split the Debuginfod component into a separate library, and then use dependency injection to use it from the `Symbolize` library.

This will likely require creation of a new interface for fetching debuginfo inside the `Symbolize` library (for example `llvm::symbolize::DebugInfoFetcher`), providing a setter for an implementation of this interface in `llvm::symbolize::LLVMSymbolizer` and use it [fetch debuginfo instead of calling `getCachedOrDownloadDebuginfo` directly](https://github.com/llvm/llvm-project/blob/c415ff186dbb9891886c6ac1f03060ad537e7074/llvm/lib/DebugInfo/Symbolize/Symbolize.cpp#L389), and implementing this interface using Debuginfod inside the new library (for example `llvm::debuginfod::DebuginfodDebugInfoFetcher`). Any tool that wants to support Debuginfod, such as `llvm-symbolizer`, would then instantiate this implementation in inject it into `llvm::symbolize::LLVMSymbolizer`, so it's only this tool that has the dependency on `libcurl`.

This design also allows creating other implementations in the future which may be useful, for example if we eventually decide to also support Microsoft symbol server in addition to Debuginfod. 

If everyone is fine with this plan, @mysterymath is going to start working on the implementation. We'll try to have it ready before the LLVM 14 branch point, and if it doesn't land in time have it cherry-picked into the LLVM 14 branch.

**Comment by dwblaikie** [comment]
Yeah, still sounds pretty reasonable to me (might not hurt to have a link to that thread we had with @nico I think it was where this was all hashed out - for continuity/etc)

**Comment by petrhosek** [comment]
@tstellar cURL is [disabled by default](https://github.com/llvm/llvm-project/blob/c39d22d1968cf07e54b5816ba76dccef8acaace1/llvm/CMakeLists.txt#L411) and you have to explicitly enable it by setting `-DLLVM_ENABLE_CURL=ON`. When it's disabled, remote Debuginfod operations are no-op.

We also talked about adding a new command line option to `llvm-symbolizer` to disable the use Debuginfod even if cURL is enabled (for example `--no-remote`) so you can set this in environment when you don't want `llvm-symbolizer` to fetch files from the network (that is, you'd set the `LLVM_SYMBOLIZER_OPTS="--no-remote"` environment variable).

Does that address your concern?

**Comment by dwblaikie** [comment]
I imagine it /might/ be suitable for llvm-symbolizer to have it non-remote by default, but not sure/don't take this as a strong suggestion in any way. (& could be controlled by a build config flag too) - but yeah, maybe folks who don't want network lookup for symbolizing are OK just not compiling it in at all

**Comment by tstellar** [comment]
> @tstellar cURL is [disabled by default](https://github.com/llvm/llvm-project/blob/c39d22d1968cf07e54b5816ba76dccef8acaace1/llvm/CMakeLists.txt#L411) and you have to explicitly enable it by setting `-DLLVM_ENABLE_CURL=ON`. When it's disabled, remote Debuginfod operations are no-op.
> 
> We also talked about adding a new command line option to `llvm-symbolizer` to disable the use Debuginfod even if cURL is enabled (for example `--no-remote`) so you can set this in environment when you don't want `llvm-symbolizer` to fetch files from the network (that is, you'd set the `LLVM_SYMBOLIZER_OPTS="--no-remote"` environment variable).
> 
> Does that address your concern?

Yes, thanks.

**Comment by mysterymath** [comment]
See https://reviews.llvm.org/D118413

**Comment by mysterymath** [comment]
The above PR just landed, which should break the dependency of libLLVM on libcurl.

**Comment by nico** [comment]
(See also https://reviews.llvm.org/D113717#3295350 . Thanks, @mysterymath!)

**Comment by stefson** [comment]
this doesn't affect llvm-13 branch, right?

**Comment by smcv** [comment]
> this doesn't affect llvm-13 branch, right?

To the best of my knowledge, this was a new thing in 14 and doesn't affect 13 (but I'm not a LLVM developer).

**Comment by tstellar** [comment]
Merged: ecdd25c8651145916f52bf84d094fe94db1a3686
