### ISSUE TITLE
clang optimizes away a volatile variable

### ISSUE THREAD

**Issue by billionai** [llvm/llvm-project#52755]
Consider the following code:

```
static volatile int var = 123;
int main(){
    return 0;
}
```

When compiling this code with `clang -g3 -O0` and reading the debugging symbols with `readelf -w` we can't find any mention of the `var`

**Comment by zero9178** [comment]
Clang simply does so because globals with internal linkage that are never ever used are simply never emitted. `volatile` doesn't change that fact either. It only really changes the semantics of loads and stores to the volatile variable. 

There is the `__attribute__((used))` if you want to force clang to emit statics into the binary.

**Comment by billionai** [comment]
I see. Thank you! __attribute__((used)) solved my problem!
