### ISSUE TITLE
Clang tooling AST introspection breaks cross compilation of LLVM

### ISSUE THREAD

**Issue by andrew-wja** [llvm/llvm-project#52819]
I am trying to produce an AArch64 toolchain which I can deploy to an embedded system following https://www.llvm.org/docs/HowToCrossCompileLLVM.html -- the host machine is an x86_64 machine.

Attached is a script which reproduces the problem on most Linux systems. You will need to install an aarch64 cross toolchain, for example, `apt-get install g++-aarch64-linux-gnu` on Debian based distributions.

[cross-compile-aarch64.txt](https://github.com/llvm/llvm-project/files/7755354/cross-compile-aarch64.txt)

The issue is in `clang/lib/Tooling/CMakelists.txt`. When we are cross-compiling (`CMAKE_CROSSCOMPILING=True`) or when `LLVM_NATIVE_ARCH` is not in `LLVM_TARGETS_TO_BUILD`, we build a `$<TARGET_FILE:clang-ast-dump>` which is not in the correct executable format for the system running the build. So when that executable is invoked to generate `${CMAKE_CURRENT_BINARY_DIR}/ASTNodeAPI.json`, we get an error and the build fails. For example, using the attached build script, `$<TARGET_FILE:clang-ast-dump>` is an AArch64 ELF executable, which the build tries to execute on X86.

The `if` conditions at the top of the CMakelists.txt appear correct, in so far as they explicitly check for those conditions I mentioned. However, for some reason, the build still tries to execute `$<TARGET_FILE:clang-ast-dump>`, even though it should just be copying a file! I cannot figure out why it is doing so. Deleting the entire `if` and replacing it with the contents of the false branch fixes the build and results in a working target toolchain being built.

Tested with LLVM 13.0.0 release, and also against `main` at the time of filing this bug.

**Comment by atsampson** [comment]
It looks like #51448 is the same problem.

**Comment by fourdim** [comment]
https://gitlab.kitware.com/cmake/cmake/-/issues/23222 Link it here.

**Comment by fourdim** [comment]
[](https://gitlab.kitware.com/brad.king)Brad King
[Brad King ](https://gitlab.kitware.com/brad.king)[@brad.king](https://gitlab.kitware.com/brad.king) · [6 hours ago](https://gitlab.kitware.com/cmake/cmake/-/issues/23222#note_1142857)
Owner
The linked [CMAKE_CROSSCOMPILING](https://cmake.org/cmake/help/v3.22/variable/CMAKE_CROSSCOMPILING.html) documentation says:

This variable will be set to true by CMake if the `CMAKE_SYSTEM_NAME` variable has been set manually (i.e. in a toolchain file or as a cache entry from the cmake command line).

It is not meant to be set by project code or toolchain files. It is always set automatically. Don't put `set(CMAKE_CROSSCOMPILING ON)` anywhere in your code.

`CMAKE_CROSSCOMPILING` indicates only whether `CMAKE_SYSTEM_NAME` was set by the user/project/toolchain-file instead of by CMake.

In LLVM project, `CMAKE_CROSSCOMPILING` is used to determine whether to execute some tests on the host machine.

LLVM needs to use another method for that. `CMAKE_CROSSCOMPILING` is not a reliable indicator of whether produced binaries will run on the host, and does not claim so in its documentation. If one sets `CMAKE_SYSTEM_NAME` to Linux in a toolchain file, and builds on a Linux host, that doesn't mean the target architecture or minimum glibc version is the same.

See also [cmake#21744](https://gitlab.kitware.com/cmake/cmake/-/issues/21744).

See also [cmake#22881](https://github.com/cmake/cmake/-/issues/22881) and [cmake#17702](https://github.com/cmake/cmake/-/issues/17702) about the possibility of computing the compiler's target architecture.

**Comment by fourdim** [comment]
Closed by https://reviews.llvm.org/D119804
