### ISSUE TITLE
Valid C program segmentation fault

### ISSUE THREAD

**Issue by Skeevert** [llvm/llvm-project#52888]
code:
```
#include <stdio.h>
#include <limits.h>

unsigned int
proveit (unsigned int n) 
{
    while (1) {
        n++;
    }

    return n;
}

int
main ()
{
    unsigned int keke = 0;

    printf("program started\n");
    keke = proveit(keke);
    printf("%u kek\n", keke);
    return 123;
}
```
clang version: 11.0.1-2

steps to reproduce:
`clang -O code.c && ./a.out`

The resulting program prints "program started" 2 times and crashes with a segmentation fault.

**Comment by uenoku** [comment]
Actually it was a bug of clang-11 but I think it was intended behavior at that point. 
clang had incorrectly applied the forward progress guarantee of C++ to C as well. Recently this was fixed by introducing `must-progress` function attribute and annotating only C++ with the attribute. 

These threads describe the details : https://reviews.llvm.org/D65718, https://reviews.llvm.org/D86841

**Comment by Skeevert** [comment]
@uenoku 
I checked the C Standard before posting this, and it has an exception for a loops whose controlling exception is a constant value.
There's no such exception for C++, but it's C.
ISO/IEC 9899:201x,
6.8.5.6

**Comment by uenoku** [comment]
Yes, the current trunk produces what you want: https://godbolt.org/z/o5efosdTc

**Comment by Skeevert** [comment]
Ok, thanks for the information
