### ISSUE TITLE
Support for "object libraries" -- a "--start-lib"/"--end-lib" like mode in lld-macho

### ISSUE THREAD

**Issue by oontvoo** [llvm/llvm-project#52931]
This allows it to accept "-objlib foo.o", which lazily includes foo.o into the link, as if it was in an archive file.

Edit: (Optional)
Also support spelling of "//-objlib". This allows it to be passed through older versions of Clang properly, when spelled as "-Wl,//-objlist". Older Clang versions will invoke the linker with "-filelist", which can only pass "filenames", not options, so we pretend to be a filename.

**Comment by smeenai** [comment]
Does ld64 have equivalent functionality, or would it be an extension? It's fine either way; I was just wondering where the `-objlib` spelling came from :)

**Comment by oontvoo** [comment]
I don't think it does. This is one of our internal LD64 optimisations, which I'd like preserve. 
We kind of made up the name. :)

**Comment by MaskRay** [comment]
I prefer start/end because it conveys more information.

In ld.lld, `--start-lib a.o b.o --end-lib` means a.o and b.o conceptually belong to the same archive (which implies `-(` `-)`) and helps this feature: https://maskray.me/blog/2021-06-13-dependency-related-linker-options#warn-backrefs
(As my article says, I understand that ld64 never has the GNU ld/gold semantics.)

For `-objlib a.o -objlib b.o`, it is unclear whether a.o and b.o should belong to the same archive.

Note that this feature should be carefully implemented so that it is possible to use this lazy object file to model `ArchiveFile` as well for eager initialization of symbol table/section https://maskray.me/blog/2021-12-19-why-isnt-ld.lld-faster#parallel-initialization-of-sections

Actually I have some interest to implement this, as I did some work for ELF and [PE/COFF](https://reviews.llvm.org/D116434), even just to find a random contribution I can make :)

**Comment by oontvoo** [comment]
Re: start/end
I'd prefer not to go that route because LD64 doesn't have any stateful flag like that (i know GOLD, for eg.,  does).
But if you all think it's ok then 👍 

Feel free to take it! 👏  thanks!

**Comment by MaskRay** [comment]
Patch: https://reviews.llvm.org/D116913
