### ISSUE TITLE
LLD for MinGW reports an undefined symbol for a function in a linked dependency

### ISSUE THREAD

**Issue by ddobrev** [llvm/llvm-project#52969]
I'm trying to link some very simple code on windows 7 64-bit:
```c++
#include <QtCore>

class QString (*identifier)(const class QString&) = &QRegularExpression::anchoredPattern;
```
with `Qt5Core 5.15.2`. I get this error:

`windows: error: undefined symbol: __declspec(dllimport) QRegularExpression::anchoredPattern(QStringView)`

At the same time opening `Qt5Core.dll` with [`Dependency Walker 2.2`](https://dependencywalker.com/) shows this inside:

`_ZN18QRegularExpression15anchoredPatternE11QStringView`

which https://demangler.com/ proves to be exactly [QRegularExpression::anchoredPattern(QStringView)](https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/text/qregularexpression.h?h=5.15.2#n161).

My guess which I hope can be of use is that `LLD` is confused by `QStringView` which you can see in https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/text/qstringview.h?h=5.15.2#n104 isn't exported.
The MinGW linker works fine.

**Comment by ddobrev** [comment]
Adding `-auto-import` doesn't help.

**Comment by MaskRay** [comment]
In IRC, @ddobrev mentioned that the `.lib` file does not provide the `__imp_` version for `_ZN18QRegularExpression15anchoredPatternE11QStringView`.

@mstorsjo

**Comment by ddobrev** [comment]
[There's some code ](https://github.com/llvm/llvm-project/blob/main/lld/COFF/SymbolTable.cpp#L303) which also looks for symbols prefixed with `__imp_`. However, such are only contained in `libQt5Core.a` and not in `Qt5Core.dll`. However again, I've only linked the DLL so far and it's worked for me with this effective call:

`lld-link Qt5Core mylib.dll`

Note: I use LLD as a library but any problems this might bring are of other essence such as global state.

**Comment by mstorsjo** [comment]
This is missing lots of details needed for exactly reproducing what you're doing, including the exact linker command you're invoking, and reference copies of the relevant files. (I understand that you're invoking LLD via the library interface, but even then, you're providing it with a command line which would give much more clues about what you are doing.)

I tried reproducing the issue, by using https://github.com/mstorsjo/llvm-mingw/releases/tag/20211002 (shouldn't matter much exactly what tools are used, but I'm stating this for reference and reproducibility). With this release, I built Qt 5.15.2 for x86_64. (I cross compiled it from Linux, but this shouldn't matter for the linking issue at hand.) I configured this build with `./configure -xplatform win32-clang-g++ -device-option CROSS_COMPILE=x86_64-w64-mingw32- -release -opensource -confirm-license -nomake examples -silent -opengl desktop -prefix $HOME/qt-5.15.2 `. From that, I got this built package of Qt: https://martin.st/temp/qt-5.15.2.zip

With those files, I tried out your example like this (still cross compiling, but it shouldn't matter):
```sh
$ cat test.cpp
#include <QtCore>
class QString (*identifier)(const class QString&) = &QRegularExpression::anchoredPattern;
$ x86_64-w64-mingw32-clang++ -c test.cpp -Iinclude -Iinclude/QtCore
$ x86_64-w64-mingw32-clang++ test.o -shared -o test.dll -Llib -lQt5Core # Using import library
$ x86_64-w64-mingw32-clang++ test.o -shared -o test.dll bin/Qt5Core.dll # Linking directly against DLL
```

This worked fine for me, both when linking with the import library and when linking directly against the DLL.

I understood from IRC, that your issue disappeared when you linked against the import library instead of the DLL. So that would indicate an issue with the linking directly against a DLL.

The feature of linking directly against a DLL instead of using import libraries is rather new in LLD (it was implemented around 7 months ago) and I think this is the first bug report I get about that feature.

LLD has got a great feature for packaging up a reproducer including all used input files. Try adding the option `-linkrepro:.` to the LLD command line invocation that is showing the error. That produces a file `repro.tar` in the indicated directory (`.` meaning the current directory here), which contains all input object files and the exact command line arguments that you provided. If you'd upload that file, it would allow me to exactly reproduce the issue you're seeing.

**Comment by ddobrev** [comment]
@mstorsjo [here you go](https://ufile.io/iys67jvz). I had trouble uploading here so I was forced to use an external service but it's exactly what you want. Let me know if I can help further.

**Comment by mstorsjo** [comment]
> @mstorsjo [here you go](https://ufile.io/iys67jvz). I had trouble uploading here so I was forced to use an external service but it's exactly what you want. Let me know if I can help further.

Ok, I reproduced the issue with that file. Running `lld-link @response.txt -demangle:no`, I get this:
```
lld-link: error: undefined symbol: __imp__ZN18QRegularExpression15anchoredPatternE11QStringView 
>>> referenced by C/QtSharp/QtSharp.CLI/bin/Debug/netcoreapp3.1/QtCore-symbols.o:(_ZN18QRegularExpression15anchoredPatternERK7QString)
```
(Among other errors.)

However when I inspect the provided Qt5Core.dll, I can't find that symbol (without the `__imp_` symbol prefix):
```
 llvm-readobj --coff-exports C/QtSharp/QtSharp.CLI/bin/Debug/netcoreapp3.1/Qt5Core.dll | grep _ZN18QRegularExpression15anchoredPatternE11QStringView
```
This command comes up with nothing.

So I believe you might have inspected a different Qt5Core.dll when you said that Dependency Walker says that symbol does exist.

So it seems like the issue is simply that you're passing the wrong (too old) Qt5Core.dll to the linker, a different one than the one you're really trying to use. This is further confirmed like this:
```
$ strings C/QtSharp/QtSharp.CLI/bin/Debug/netcoreapp3.1/QtCore-symbols.o |grep 5\\.1
C:/Qt/5.15.2/mingw81_64/include\QtCore/qarraydata.h
C:/Qt/5.15.2/mingw81_64/include\QtCore/qlist.h
C:/Qt/5.15.2/mingw81_64/include\QtCore/qvector.h
C:/Qt/5.15.2/mingw81_64/include\QtCore/qmap.h
C:/Qt/5.15.2/mingw81_64/include\QtCore/qscopedpointer.h
C:/Qt/5.15.2/mingw81_64/include\QtCore/qstring.h
C:/Qt/5.15.2/mingw81_64/include\QtCore/qbytearray.h
C:/Qt/5.15.2/mingw81_64/include\QtCore/qrefcount.h
C:/Qt/5.15.2/mingw81_64/include\QtCore/qstringview.h
C:/Qt/5.15.2/mingw81_64/include\QtCore/qstringlist.h
C:/Qt/5.15.2/mingw81_64/include\QtCore/qregularexpression.h
C:\Qt\5.15.2\mingw81_64\include\QtCore/qbitarray.h
C:/Qt/5.15.2/mingw81_64/include\QtCore/qsharedpointer_impl.h
C:\Qt\5.15.2\mingw81_64\include\QtCore/qcborarray.h
C:\Qt\5.15.2\mingw81_64\include\QtCore/qcbormap.h
C:/Qt/5.15.2/mingw81_64/include\QtCore/qcborstreamreader.h
C:/Qt/5.15.2/mingw81_64/include\QtCore/qmutex.h
C:\Qt\5.15.2\mingw81_64\include\QtCore/qline.h
C:\Qt\5.15.2\mingw81_64\include\QtCore/qrandom.h
C:\Qt\5.15.2\mingw81_64\include\QtCore/qreadwritelock.h
C:/Qt/5.15.2/mingw81_64/include\QtCore/qsize.h
C:/Qt/5.15.2/mingw81_64/include\QtCore/qset.h
C:/Qt/5.15.2/mingw81_64/include\QtCore/qhash.h
```
So your object file is clearly built against Qt 5.15.2. But inspecting the provided DLL shows this:
```
$ strings C/QtSharp/QtSharp.CLI/bin/Debug/netcoreapp3.1/Qt5Core.dll |grep 5\\.1
5.12.5
Qt 5.12.5 (x86_64-little_endian-llp64 shared (dynamic) release build; by GCC 7.3.0)
qt_prfxpath=C:\Qt\5.12.5\mingw73_64
```
So you're linking against a DLL from Qt 5.12.5 but using headers from Qt 5.15.2. That's your issue.

**Comment by ddobrev** [comment]
@mstorsjo I'm so sorry, I haven't felt this ashamed in a decade. I had forgotten an old copy of `Qt5Core.dll` in the working directory, probably because of unrelated tests. Since the working directory gets higher precedence than supplied library dirs, there I go...
Thank you for putting in the time and patience to solve my problem. I'll make sure to be careful next time.
Have a wonderful new year.
