### ISSUE TITLE
please explain weak_ptr destruction undefined behavior

### ISSUE THREAD

**Issue by winter-loo** [llvm/llvm-project#52974]
https://github.com/llvm/llvm-project/blob/9fb4e79d06aa690c611c0ef601c134f57788590a/libcxx/src/memory.cpp#L89.

Can someone give me an example about the undefined behavior?

**Comment by Quuxplusone** [comment]
The libc++ bug tracker seems like the wrong place for this question; please take it to https://cppalliance.org/slack/ or https://discord.gg/xS7Z362 or something along those lines.
(But FYI, accessing an object from two threads simultaneously is _always_ a data race, unless both accesses are reads; and a destructor call is definitely not a read. So that's the deal.)
