### ISSUE TITLE
[clang-format] Read config under XDG_CONFIG_HOME?

### ISSUE THREAD

**Issue by jasonhan-vassar** [llvm/llvm-project#52987]
Hi, does `clang-format` support reading a global config under something like `$HOME/.config/clang-format/`, as specified by XDG Base Directory?

**Comment by mydeveloperday** [comment]
This commit which landed recently allows an explicit path
https://github.com/llvm/llvm-project/commit/b9e173fcd46b336b5589f577a74de9472d4deae3

Otherwise just place your .clang-format at the top of your tree! and it will find it

i.e. if your source is in 

$HOME/Source/MyProject

if you place the .clang-format file in $HOME it will find it. (as long as there are no .clang-format files in the subdirectories between.

**Comment by jasonhan-vassar** [comment]
I see, I'm just in time for that commit then! To build `clang-format`, do I need to build the entire project, or is there a way I can specify that target?

**Comment by jasonhan-vassar** [comment]
@mydeveloperday  So I ended up building the entire project anyways and got the latest `clang-format`. Sorry to bother you once more, but is tilde supported to get the home directory? For example:

`clang-format --style=file:~/.config/clang-format/.clang-format file.cpp`

I get the following error: `Error reading ~/.config/clang-format/.clang-format: No such file or directory`. I'm not sure if I'm just not following Bash syntax or if `clang-format` does not support that yet.

**Comment by mydeveloperday** [comment]
I suspect ~ is something the shell expands

**Comment by mydeveloperday** [comment]
I normally user ninja and do `ninja clang-format`

Here is my cmake command that I use on Windows

```
export CC=cl.exe
export CXX=cl.exe
/cygdrive/c/Program\ Files/CMake/bin/cmake -G "Ninja" ../llvm-project/llvm \
-DCMAKE_BUILD_TYPE=Release\
-DLLVM_BUILD_TESTS=ON \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
-DLLVM_ENABLE_SPHINX=ON \
-DSPHINX_OUTPUT_HTML=ON \
-DPYTHON_EXECUTABLE=$PYTHON_EXECUTABLE \
-DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra"
```
