### ISSUE TITLE
[msvc] Resolve conflict between MSVC STL <experimental/coroutines> header and Clang

### ISSUE THREAD

**Issue by rnk** [llvm/llvm-project#53010]
If you include <coroutines> with the MSVC STL using clang-cl, you will hit this error:
https://github.com/microsoft/STL/blob/main/stl/inc/experimental/coroutine#L29

```
#if defined(__clang__) && !defined(_SILENCE_CLANG_COROUTINE_MESSAGE)
#error The <experimental/coroutine>, <experimental/generator>, and <experimental/resumable> headers currently do not \
support Clang. You can define _SILENCE_CLANG_COROUTINE_MESSAGE to silence this message and acknowledge that this is \
unsupported.
#endif // defined(__clang__) && !defined(_SILENCE_CLANG_COROUTINE_MESSAGE)
```

It's not surprising that new library features don't work with all compilers, but what makes this more urgent is that the winrt/Windows.Foundations.h header includes coroutines:

```
In file included from <redacted>
In file included from <redacted>/winrt/Windows.Foundation.h:6:
In file included from <redacted>/winrt/base.h:53:
<redacted>/MSVC/14.28.29910/include/experimental/coroutine(30,2): error: The <experimental/coroutine>, <experimental/generator>, and <experimental/resumable> headers currently do not support Clang. You can define _SILENCE_CLANG_COROUTINE_MESSAGE to silence this message and acknowledge that this is unsupported.
#error The <experimental/coroutine>, <experimental/generator>, and <experimental/resumable> headers currently do not \
 ^
1 error generated.
```

We need to understand the conflict better, and at least try to make winrt work out of the box in new SDK versions.

**Comment by ericastor** [comment]
Might this be a testing/support issue on the MSVC STL side? If so, should we file an issue there as well?

**Comment by rnk** [comment]
That's possible, but I think it falls to the LLVM project to make sure that the compiler support is good enough for them to implement this library feature first. My understanding is that Clang's coroutine support is incomplete in some ways.

**Comment by ChuanqiXu9** [comment]
According to my knowledge, the <experimental/coroutine> in MSVC's STL is MSVC's extension instead of standard coroutine header. The standard coroutine header in MSVC should be https://github.com/microsoft/STL/blob/main/stl/inc/coroutine . I think clang should have supported the standard one. For the experimental one, it contains other compiler intrinsics which is not defined in clang so that clang couldn't compile it. I think we need wait for the engineer from MSVC to support <experimental/coroutine>. Or at least we need wait for the design document for the extension, which I didn't find now.

**Comment by rnk** [comment]
I see, the <coroutine> header doesn't have the #error but the <experimental/coroutine> one does. Then the issue becomes that winrt/Windows.Foundation.h includes the experimental header, and ideally they would migrate to the standard one if possible. There's probably nothing for us (LLVM) to do, the most we can do is pass this over to MSVC STL folks.

**Comment by ChuanqiXu9** [comment]
Agreed. The best we could do is to file an issue at https://github.com/microsoft/STL/issues.

**Comment by ericastor** [comment]
I think this is a Windows SDK issue, rather than a Microsoft STL issue? Not sure where we can file bugs about that, unfortunately. Anyone have a Microsoft contact?

**Comment by ChuanqiXu9** [comment]
I think <experimental/coroutine> in MSVC couldn't be an alias for <coroutine>. Since <experimental/coroutine> is an extension. It contains different ability with <coroutine>. So they couldn't be compatible.

**Comment by cpplearner** [comment]
It seems that newer releases in https://github.com/microsoft/cppwinrt/ doesn't unconditionally include `<experimental/coroutine>`.

**Comment by ericastor** [comment]
Unfortunately, `Windows.Foundation.h` is actually a Windows SDK header, not released in the cppwinrt project.

**Comment by CaseyCarter** [comment]
I can't speak for the Windows SDK (which I hope will transition to `<coroutine>` soon) but it's certainly intended that MSVC's `<experimental/coroutine>` doesn't support Clang. MSVC's pre-standard-coroutines use an undocumented coroutine frame layout - different from Clang's pre-standard-coroutines - and we never thought it was worth the trouble to document that bit of ABI and get it supported in Clang.

MSVC's C++20 `<coroutine>` does fully support Clang.

**Comment by alvinhochun** [comment]
> Unfortunately, `Windows.Foundation.h` is actually a Windows SDK header, not released in the cppwinrt project.

Let's not mix things up -- `Windows.Foundation.h` located in `C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\winrt`, and many of the other headers in the same directory is are Windows SDK header. They declare the WinRT ABI types, which is the lowest level of interaction with WinRT via COM interfaces. These are usable from plain C and do _not_ depend on coroutine support, so Clang-cl should not have any issues consuming them.

In contrast, `winrt/Windows.Foundation.h` (which is the one involved in the OP) and other headers located in `C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\cppwinrt` are C++/WinRT projection headers. These are purely C++ headers and do require coroutine support. Note that [using the C++/WinRT projection from the Windows SDK is discouraged](https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt#sdk-support-for-cwinrt) because it is updated very infrequently. (The officially recommended way of using it is through the NuGet package in Visual Studio, but one can also craft some custom commands in other build systems to generate the headers dynamically.) Because of this, I think there is no point in trying to make Clang-cl work with the C++/WinRT projection headers shipped with the Windows SDK (which are indeed quite outdated).

The C++/WinRT projection generated with [upstream cppwinrt](https://github.com/microsoft/cppwinrt) does work with Clang-cl to some extent when using C++20 coroutine (not `experimental/coroutine`); I've even added CI checks for it with GitHub Actions. Problem is there are some crashes related to coroutines which led me to disable certain tests, but these are not the same issues as OP.


> MSVC's C++20 `<coroutine>` does fully support Clang. I suggest that this issue be closed, or retitled and relabeled to avoid confusion.

I agree with this.

**Comment by CaseyCarter** [comment]
Full disclosure: I'm a Microsoft employee on the MSVC team.

I've retitled and relabeled this issue as being specific to MSVC `<experimental/coroutines>` and unrelated to C++20 coroutine support. I don't feel authorized to close it, since there's definitely a gap in clang support for MSABI TS coroutines and I'm not a clang/clang-cl "owner". I do recommend that someone who _is_ closes this because MSVC is unlikely to document the deprecated TS coroutine ABI well enough for Clang to support it even if someone did deem it worth their time to do so.

**Comment by ChuanqiXu9** [comment]
Although I am not a formal "owner" for coroutines, I maintain it for a relatively long time. I'd like to close it by the above comment.
