### ISSUE TITLE
RISC-V Register Allocation Error

### ISSUE THREAD

**Issue by wangcheng22** [llvm/llvm-project#53016]
I  uses the following command to generate RISC-V assembly code from llvm bytecode:

llc -march=riscv64 -mattr=+m,+a,+f,+d,+c,+experimental-v -riscv-v-vector-bits-min=128 test.ll

In the following generated assembly code, the register **s1** is used as both general register and frame-pointer for spill, which causes memory fault during execution.

[test.zip](https://github.com/llvm/llvm-project/files/7817425/test.zip)

        mv      **s1**, sp
        ...

.LBB1_6:                                # %no_errors_bb
        ld      a0, 40(s11)
        fmv.w.x ft0, a7
        lw      a4, 16(a0)
        lw      a3, 20(a0)
        lw      **s1**, 0(a0)
        lw      a1, 4(a0)
        sd      a4, 648(**s1**)                     # 8-byte Folded Spill
        srai    a5, a4, 4
        sd      a3, 728(**s1**)                     # 8-byte Folded Spill
        srai    a3, a3, 4
        add     a4, a3, a5
        sd      **s1**, 616(**s1**)                     # 8-byte Folded Spill

**Comment by Hsiangkai** [comment]
When the function call has out-going arguments and it is not reserved by the call frame, we need to adjust the stack pointer at the call-site. Under the condition, we need to reserve BP as a reference point. The problem is how do we determine whether if the space for out-going arguments is reserved by the call frame or not? It is decided by RISCVFrameLowering::hasReservedCallFrame(). In D103622, I added a condition in hasReservedCallFrame() to avoid the out-going scalar arguments overwrite the scalable vector values in the stack. The bug is caused by the decision function hasRVVFrameObject(). Before RA, hasRVVFrameObject() returns false because there is no RVV stack objects. After RA, hasRVVFrameObject() returns true because there are spilling slots for RVV values during RA. That’s why it does not reserve BP when RA and generate BP access in FrameLowering.

**Comment by kito-cheng** [comment]
@wangcheng22 https://reviews.llvm.org/D117663 should address this issue, could you confirm that fixed your case?

**Comment by wangcheng22** [comment]
It works for my code.  Thanks.

**Comment by EugeneZelenko** [comment]
Fixed in ad06e65dc4da45be2cda3e07664502651679622a.
