### ISSUE TITLE
[SCEV] Can not compute loop exit counts with branch on or-like select 

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#53020]
This blocks https://reviews.llvm.org/D116692:
good/bad ir: https://godbolt.org/z/8cvhE9Ks7

CC @rnk @preames

**Comment by LebedevRI** [comment]
So, basically, this block is responsible here:
https://github.com/llvm/llvm-project/blob/b061d86c6930acef1b246874adf2f11e9120894c/llvm/lib/Analysis/ScalarEvolution.cpp#L8157-L8191
We end up with `MaxBECount = getUMinFromMismatchedTypes(EL0.MaxNotTaken, EL1.MaxNotTaken);`:
```
EL0.ExactNotTaken: ((-1 * (ptrtoint i64* %start.i to i64)) + (ptrtoint i64* %end.i to i64))
EL1.ExactNotTaken: ((-1 * (ptrtoint i64* %start.i2.peel to i64)) + (ptrtoint i64* %end.i4.peel to i64))
EL0.MaxNotTaken: -1
EL1.MaxNotTaken: -1
```

**Comment by LebedevRI** [comment]
CC @aqjune @nikic

**Comment by aqjune** [comment]
Hi,

It is a bit unfortunate that it is returning different results for two loops that are essentially equivalent. :(

I think that if we are to use backedge counts for cost analysis, it does not need to be strictly poison-safe.
It is necessary only when the backedge count is to be expanded into LLVM IR instructions, because it will introduce UB in this case indeed.

**Comment by LebedevRI** [comment]
Super rough proof of concept: https://reviews.llvm.org/D116766

**Comment by LebedevRI** [comment]
Forgot the auto-close magic.
This has now been fixed via https://github.com/llvm/llvm-project/commit/82fb4f4b223d78e86647f3576e41e3086ab42cd5.
