### ISSUE TITLE
[libsanitizer] Can we support libsanitizer for x86_64-w64-mingw32 gcc?

### ISSUE THREAD

**Issue by tearosccebe** [llvm/llvm-project#53080]
Currently libsanitizer does not support windows for GCC. Can we fix it?

**Comment by zero9178** [comment]
Undefined behaviour sanitizer as well as Address sanitizers inside of LLVM (to be precise, compiler-rt) do support Windows and are useable with both a MinGW clang as well as clang-cl. 
It is up to the GCC developers whether they import the changes and add support for it in their compiler. You are probably best of posting on https://gcc.gnu.org/bugs/ instead.

That said, you can at least somewhat use Undefined Behaviour Sanitizer with GCC on Windows by using the command line options ` -fsanitize=undefined -fsanitize-undefined-trap-on-error`. This will do most of the work the undefined behaviour sanitizer does but generate trap instructions for the error branch instead of calling into a runtime library. That way you can still detect undefined behaviour and debuggers ought to halt when encountering a trap instructions, making it easy to see where it happened.
