### ISSUE TITLE
std::conjunction value has wrong type

### ISSUE THREAD

**Issue by aj-michael** [llvm/llvm-project#53133]
I believe std::conjunction is supposed to derive from one of the template parameters (if there are any), so its `::value` should have the type of one of the template parameters `::value`s. However, it looks like the libc++ implementation will always derive from either `true_type` or `false_type`.

Here's an example that compiles with libstdc++ but fails with libc++.

```
#include <type_traits>

struct V {
    operator bool() {
        return false;
    }
};

struct S {
    static constexpr V value;
};

static_assert(
    std::is_same_v<
        const V,     // <--- This is `const bool` in libc++
        decltype(std::conjunction<S>::value)
    >
);
```

**Comment by Quuxplusone** [comment]
Confirmed; https://eel.is/c++draft/meta.logical says this should work, and it doesn't work with libc++ right now.
```
using A = std::is_same<int, int>;
static_assert(std::is_base_of_v<A, std::conjunction<A>>);
static_assert(std::is_base_of_v<A, std::disjunction<A>>);
```

**Comment by KB9** [comment]
I'd like to take this issue on (if there hasn't been any progress on it already).

**Comment by Quuxplusone** [comment]
@KB9 go for it!
(For details on the review process, see https://libcxx.llvm.org/Contributing.html ; and while the `arc diff` tool is apparently the preferred approach, I'll point you at https://reviews.llvm.org/differential/diff/create/ also.)

**Comment by KB9** [comment]
I see the issue here, though I'm at a bit of a loss as to what to do about it. `std::conjunction` is defined as:

```cpp
template <class... _Args>
struct conjunction : _And<_Args...> {};
```

Where `_And` is defined as:

```cpp
template <class ...> using __expand_to_true = true_type;
template <class ..._Pred>
__expand_to_true<__enable_if_t<_Pred::value>...> __and_helper(int);
template <class ...>
false_type __and_helper(...);
template <class ..._Pred>
using _And _LIBCPP_NODEBUG = decltype(__and_helper<_Pred...>(0));
```

Thus `std::conjunction` will only ever return `true_type` or `false_type`.

We could take inspiration from the current implementation of `_Or` used by `std::disjunction` to implement a more conformant `_And`:

```cpp
template <bool> struct _MetaBase;
template <>
struct _MetaBase<true> {
  template <class _Result, class _First, class ..._Rest>
  using _OrImpl _LIBCPP_NODEBUG = typename _MetaBase<_First::value != true && sizeof...(_Rest) != 0>::template _OrImpl<_First, _Rest...>;
};

template <>
struct _MetaBase<false> {
  template <class _Result, class ...>
  using _OrImpl _LIBCPP_NODEBUG = _Result;
};

template <class ..._Rest>
using _Or _LIBCPP_NODEBUG = typename _MetaBase< sizeof...(_Rest) != 0 >::template _OrImpl<false_type, _Rest...>;
```

The problem with doing this is that such an implementation fails the [tuple recursion depth test](https://github.com/llvm/llvm-project/blob/main/libcxx/test/std/utilities/tuple/tuple.tuple/tuple.cnstr/recursion_depth.pass.cpp), since `std::tuple` also leverages `_And`. In this test, every template parameter passed to `_And` will have a member variable `value` equal to `true`.

I can't think of an implementation of `_And` which does not involve recursion in this way, and I'm hesitant to introduce any change which effectively reduces the maximum size of a tuple at a maximum template depth of 1024.
