### ISSUE TITLE
Ryzen vhaddps has weird latency 100 

### ISSUE THREAD

**Issue by marcovtje** [llvm/llvm-project#53242]
Put this through llvm-mca ( I tested on godbolt, since I have a Windows computer,  but they say they have  trunk ref
https://github.com/compiler-explorer/compiler-explorer/issues/3263 )

vhaddps xmm4,xmm3,xmm3 // x im1re2+re1im2

with -mcpu=znver1 and the result is strangely enough (note the "100" in the [2] column, Agner Fog says 7 or 8). Note also that this is all 128-bit registers, so the dual pipe znver1 AVX256 design doesn't come into play.

Instruction Info:
[1]: #uOps
[2]: Latency
[3]: RThroughput
[4]: MayLoad
[5]: MayStore
[6]: HasSideEffects (U)

[1] [2] [3] [4] [5] [6] Instructions:
1 100 0.25 vhaddps xmm4, xmm3, xmm3
1 1 0.50 * movq qword ptr [r8], xmm4

With other -mcpu's te number 100 is not directly visible, but the total cycle count is also off by that amount

**Comment by LebedevRI** [comment]
`100` is a magic number for "either this instruction is macro-coded and has unpredictable latency, or we didn't bother exactly specifying/measuring it's latency".

**Comment by adibiagio** [comment]
> `100` is a magic number for "either this instruction is macro-coded and has unpredictable latency, or we didn't bother exactly specifying/measuring it's latency".

In my experience, the znver1 scheduling model is poorly defined.

The fact that horizontal operations default to 100cy is a bit embarrassing and frustrating. There are several instructions with a completely broken latency/throughput profile. For example, the default 100cy latency is sadly also applied to other instructions (e.g.: vdppd, vdpps, vpclmulqdq and vperm2f128 (!!)). The fact that vperm2f128 also defaults to 100cy is ridiculous.

znver2 model is also wrong in many parts, but at least it doesn't report a silly 100cy for horizontal operations. That being said, dot-product and carry-less multiply still default to 100cy.

I wish that somebody would improve znver1 and znver2 models.
I'd be very happy to review and accept patches in this area.

**Comment by fabian-r** [comment]
> I wish that somebody would improve znver1 and znver2 models.
> I'd be very happy to review and accept patches in this area.

For many of these instructions, AMD's instruction table provides no exact resource usage and there are also no suitable performance counters for uops.info-style experiments. While we could measure latencies, only adjusting them will also lead to wrong predictions since llvm-mca cannot know about the instructions' usage of functional units.
Is there an established way of handling such cases? E.g. with resource usages that produce predictions that are consistent with a set of microbenchmarks, but are not necessarily correct? Or do we have to hope that the vendor provides exact models with their internal knowledge?

**Comment by RKSimon** [comment]
llvm-exegesis reports are usually a good starting point, with suitable corroborating values from other sources such as Agner, uops.info and instlatx64

**Comment by fabian-r** [comment]
Those won't help for AMD CPUs, since there are no performance counters that count executed ops per functional unit (cf. the empty "Ports" column on uops.info, [here](https://uops.info/table.html?search=&cb_lat=on&cb_tp=on&cb_uops=on&cb_ports=on&cb_ZENp=on&cb_measurements=on&cb_doc=on&cb_base=on)).
AFAIK, the only approaches operating in this setting are PMEvo (ours) and PALMED (who have a different kind of resource model that is not based on uops). However, neither tool can find a "correct" resource usage in terms of the existing functional units.

I believe it might be possible to adjust PMEvo to respect available port usages in the existing model and infer port usages for the 100cy instructions that produce throughput predictions that are reasonably consistent with microbenchmarks that combine them with other instructions (but not necessarily exactly what the machine does).
Would such an adjustment to the scheduling model be a welcome patch?

**Comment by fabian-r** [comment]
True, but this issue does not only affect FPU operations: e.g. RCR/RCL and SHLD/SHRD are also marked as `WriteMicrocoded` in the znver1 model.
For the horizontal operations, this should indeed work.

**Comment by adibiagio** [comment]
> True, but this issue does not only affect FPU operations: e.g. RCR/RCL and SHLD/SHRD are also marked as `WriteMicrocoded` in the znver1 model. For the horizontal operations, this should indeed work.

AMD historically has never provided counters to accurately measure pipeline activity for the Integer unit.

That being said, RCR/RCL have a known #uOPs/latency/throughput. So, it is unclear to me why those are marked as Microcode. They are well described by the AMD SOG for family 17h. Basically, it is just a matter of porting those numbers into our .td files.

I am afraid that we cannot do much for SHLD/SHRD because AMD doesn't provide decent PMCs to measure pipe allocation for those. That being said, personally I can live with that limitation in practice; those instructions are known to be very slow on AMD processors, and code generators for x86 already avoid to select them.

--

Back to this issue:

The goal is to fix the perf numbers for horizontal operations.

It should be fairly easy to (at least) measure the latency/throughput of all horizontal operations, and then update our .td files.
