### ISSUE TITLE
[Linux x86_64, clang++12] Template lookup does not work in debug builds if 2 structs have the same name in different .cpp

### ISSUE THREAD

**Issue by Julien-goupy** [llvm/llvm-project#53264]
See https://github.com/Julien-goupy/bug_clang for the code.

The code is so small that no description would help more.

**Comment by dwblaikie** [comment]
This looks like an ODR violation ("One Definition Rule" - that a given externally visible name must have the same definition in all places in the program) - and ODR violations are invalid, no diagnostic required - so there are no guarantees about the behavior of the program. Ultimately it'll pick one of those, because it thinks they're the same/equivalent functions - it can't have both of them in the final program because they're not distinct (picture if the type was defined in a header instead of in each of the .cpp files - and you instantiated some template with the type in multiple places - it's important that all those instantiations get deduplicated (both for code size, and for correctness - if you take the address of one of the instantiations C++ requires that that address is equal to taking the address of another instantiation with teh same parameters)

https://en.cppreference.com/w/cpp/language/definition

If you only need the type defined locally in the .cpp files, then they should be defined in an anonymous namespace (`namespace { ... }`) - that'll cause them to be distinct types (the anonymous namespace in one file is distinct from the one in the other file - so the types inside them are distinct too) 

If there's more to this (do you see significantly different behavior on other compilers/platforms?), feel free to re-open/clarify.
