### ISSUE TITLE
Lexer/__has_declspec_attribute regression in Clang 14

### ISSUE THREAD

**Issue by lilianmoraru** [llvm/llvm-project#53269]
Regression tracked to this commit: https://github.com/llvm/llvm-project/commit/2edb89c746848c52964537268bf03e7906bf2542#diff-d8dd6191130efea27aca1a54b23fc45eeeb1cc377147f9d6f5ec8b00ff56fafc
Confirmed that reverting `2edb89c746848c52964537268bf03e7906bf2542` on `d8e0e125a2ff03335838039f5d33ecd61dfec654`(`main` branch/clang 14) fixes the bug.

#### Description:
libcurl 7.78.0(the line was there for years, it's not specific to this version) fails to compile when consumed in a C++ project(unknown if specific to C++ - this was the initial setup when the issue was hit):

```
linux/include/curl/curl.h:120:41: error: too few arguments provided to function-like macro invocation
      __has_declspec_attribute(dllimport))
                                        ^
```

Clang 13.0.1(`release/13.x` branch) works fine.
Clang 14(`d8e0e125a2ff03335838039f5d33ecd61dfec654`, branch `main`) fails.

This is the line upstream:
https://github.com/curl/curl/blob/bfbde883af33397943df68a3ae01847a634d33bf/include/curl/curl.h#L120

Attaching the libcurl source code used in the project(note: not building libcurl itself, just consuming the `curl.h` header):
[libcurl.zip](https://github.com/llvm/llvm-project/files/7890954/libcurl.zip)

**Comment by lilianmoraru** [comment]
Is there a way for me to help move this along for LLVM 14?

**Comment by lilianmoraru** [comment]
The regression is still present in LLVM 14.0.0-rc4.

**Comment by tstellar** [comment]
@AaronBallman Can you take a look at this?

**Comment by AaronBallman** [comment]
I'm not able to reproduce on Windows, but I suspect that's expected (I don't have a Linux box handy to test on at the moment). I'm also not able to reproduce on godbolt (even after adding the includes I spotted): https://godbolt.org/z/zPTjbo6nY, but they don't have curl as a library option so I can't test exactly. I looked through the curl source attached and didn't spot the obvious culprit (`#define dllimport(something)`), but that's ultimately what the issue is presenting as -- we're lexing a token we expect to be expandable and we can't because something defined the token as a function-like macro. 

Could you take Clang 13 and run a `-E -dD` invocation over your test and attach the resulting preprocessed content? That could help us spot where `dllimport` is being defined as a macro (if it is indeed being defined as one).

**Comment by lilianmoraru** [comment]
@AaronBallman Here is the reduced code on [godbolt](https://godbolt.org/z/7qqe185GK)
Adding this line breaks it:
```cpp
#define dllimport
```

[Thanks to](https://github.com/citizenfx/fivem/commit/bbc87951902ef7aa966ad99cd47e115dee93526e#commitcomment-76174655) @[gottfriedleibniz](https://github.com/gottfriedleibniz) for the snippet

**Comment by AaronBallman** [comment]
@lilianmoraru -- thank you for the extra details! This behavior is by-design; we want `__has_declspec_attribute` (and `__has_attribute`) to behave like the standards-based feature test functionality in `__has_c_attribute` and `__has_cpp_attribute`. Those are defined to expand their arguments (http://eel.is/c++draft/cpp#cond-5). Because `dllimport` is defined to expand to nothing, the resulting expression becomes `__has_declspec_attribute()` which is syntactically invalid and is consistent with the behavior you get here: https://godbolt.org/z/hb3EdsW94.

So yes, the behavior changed, but it's intentional. I'm sorry for the extra hassle this causes you, though! Now the question becomes, what to do, if anything, about the impacted CURL header. I'd rather avoid making `__has_declspec_attribute` behave differently from the other attribute queries (that will just lead to confusion). We've worked around issues in STL or system headers with targeted fixes and maybe such an approach is possible here (I've not explored that), but I'm not certain we've done that for other 3rd party headers. We could leave the situation alone, but that means Clang 14+ users consuming older CURL headers will have struggles.

@zygoloid -- do you have opinions here?

**Comment by lilianmoraru** [comment]
> Now the question becomes, what to do, if anything, about the impacted CURL header

Just realized that `cURL` is fine on it's own(most users won't hit this issue). The issue comes from casablanca + cURL, here is another [godbolt link](https://godbolt.org/z/T6nxGY4cz).
This uses the latest code from [casablanca](https://github.com/microsoft/cpprestsdk/blob/80444805898842f7e5c62b256337c0897eb254bb/Release/include/cpprest/details/cpprest_compat.h) - potentially needs a fix in casablanca or maybe it tells you something else.

**Comment by barcharcraz** [comment]
Yep, this is 100% a bug in cpprestsdk (and frankly I'm surprised that header didn't blow up in someone's face much earlier)
