### ISSUE TITLE
[OpenMP][NVPTX] Multiple tests failing with new device runtime

### ISSUE THREAD

**Issue by pdhaliwal-amd** [llvm/llvm-project#53290]
We are seeing an AOMP test failing when using new device runtime. This test compiles completely fine but fails to produce correct results. However, when using `-fno-openmp-target-new-runtime` the test starts working fine.

The test is located here -> https://github.com/ROCm-Developer-Tools/aomp/tree/aomp-dev/test/smoke/assertok_error
Example command used is
```
/work/pdhaliwal/usr/bin/clang  -O2    -fopenmp -fopenmp-targets=nvptx64 -Xopenmp-target=nvptx64 -march=sm_70 assertok_error.c -o assertok_error -L/usr/local/cuda/targets/x86_64-linux/lib -lcudart
```

Edit: removed tests which were failing for both old and new runtime

**Comment by JonChesterfield** [comment]
Tests that fail on the new runtime and the old runtime are probably of interest as well. The crucial part really is failing on the new one.

**Comment by jdoerfert** [comment]
So, https://github.com/ROCm-Developer-Tools/aomp/tree/aomp-dev/test/smoke/assertok_error "works" with the old runtime because it literally ignores the critical clause. The critical is implemented with a lock which causes a warning (we cannot see without printf) and that's it. Take a look at https://github.com/llvm/llvm-project/blob/main/openmp/libomptarget/deviceRTLs/amdgcn/src/amdgcn_locks.hip if you want to see for yourself.
The new runtime is more direct about this, locks are not implemented for amdgcn and it will simply trap.
Now one can argue it should not, but then we need a reasonable alternative.

My 2c, tests including critical, locks, ... are not supported on amdgcn (for now or ever).

**Comment by JonChesterfield** [comment]
The test probably works robustly on rocm. The implementation of locks on there is roughly as in https://github.com/ROCm-Developer-Tools/llvm-project/blob/aomp-dev/openmp/libomptarget/deviceRTLs/amdgcn/src/amdgcn_locks.hip which is very similar to what nvptx used.

If 'critical' means 'executed one by one thread within the warp', then the kmpc_critical implementation combined with those locks will do the right thing. If 'critical' means 'executed by each thread within the warp in turn' then it will not.

The test case does not distinguish between 64 executions of one thread and one execution of each thread. The rocm implementation will definitely run the critical section on the lowest thread ID currently active each time it executes.

**Comment by jdoerfert** [comment]
I'd recommend:
change the trap in the new RT to a `PRINT(...); trap`, aka assert.
Expect the test to fail or disable it.
Eventually someone can go back an implement locks, this should not block us now, IMHO.

**Comment by pdhaliwal-amd** [comment]
Should it expectedly fail for NVPTX as well?

**Comment by jdoerfert** [comment]
> Should it expectedly fail for NVPTX as well?

I think pre-volta the lock impl we have for nvptx won't really work. post-volta it might. That said, I would very much like us to diagnose things we cannot implement rather than may or may not implement them properly. XFail it might not work due to the pre/post volta thing, so maybe disable it for now.

**Comment by shiltian** [comment]
The new device runtime has been the only one for a long time now. If there is still any failure, feel free to reopen it.
