### ISSUE TITLE
"error: unsupported size for integer register" in function __kmp_spin_backoff(kmp_backoff_t*)

### ISSUE THREAD

**Issue by BalaRishi-AMD** [llvm/llvm-project#53309]
Facing the below while building OpenMP (with -DLIBOMP_ARCH=i386) of the latest source:
/home/build/llvm-project/openmp/runtime/src/kmp_lock.cpp: In function ‘void __kmp_spin_backoff(kmp_backoff_t*)’:
/home/build/llvm-project/openmp/runtime/src/kmp_lock.cpp:2684:1: **error: unsupported size for integer register**

**Comment by BalaRishi-AMD** [comment]
Clang 
	Version: 14.0.0 
	Faced this issue with source cloned on January 18th. This issue was not faced with the source cloned on January 17th (commit id: 42bc3275d3687524ddc0d20c72722b9324f87be4).
	
Platform: 
	Intel(R) Xeon(R) CPU E5-2698 v3 (RHEL 7.8)
	
Options:
	cmake -G \'Unix Makefiles\' -DLLVM_LIT_ARGS="--xunit-xml-output=testresults.xunit.xml -v" -DLLVM_ENABLE_PROJECTS=clang;lld;compiler-rt;openmp -DBUILD_SHARED_LIBS:STRING=ON  -DLLVM_ENABLE_LIBEDIT=OFF -DCMAKE_BUILD_TYPE:STRING=RELEASE -DCLANG_DEFAULT_LINKER:STRING=lld -DLLVM_BUILD_EXTERNAL_COMPILER_RT=ON -DCOMPILER_RT_BUILD_XRAY=OFF -DLLVM_TARGETS_TO_BUILD:STRING=X86;AMDGPU -DLLVM_ENABLE_ASSERTIONS:BOOL=ON -DPACKAGE_VERSION=LLVM.14.0.0 -DCLANG_VENDOR=LLVM  -DCLANG_REPOSITORY_STRING=CLANG: -DLLVM_ENABLE_WERROR=OFF -DCMAKE_CXX_FLAGS='-Wno-error=pedantic' -DCOMPILER_RT_USE_LIBCXX:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=<install path> <llvm src>

	Make was used to build.

**Comment by BalaRishi-AMD** [comment]
This issue started after the below change:

commit 2e02579a76cf4ea3acdc0e076f53ff9cb15fa38f
Author: Terry Wilmarth <terry.l.wilmarth@intel.com>
Date: Tue Dec 14 15:04:55 2021 -0600

[OpenMP] Add use of TPAUSE

Add use of TPAUSE (from WAITPKG) to the runtime for Intel hardware,
with an envirable to turn it on in a particular C-state. Always uses
TPAUSE if it is selected and enabled by Intel hardware and presence of
WAITPKG, and if not, falls back to old way of checking
__kmp_use_yield, etc.

Differential Revision: https://reviews.llvm.org/D115758

**Comment by BalaRishi-AMD** [comment]
@TerryLWilmarth 
Can you please help to overcome this issue?
Thanks.

**Comment by jpeyton52** [comment]
@BalaRishi-AMD Is this build failure only on RHEL7? Can you replicate this on Ubuntu?

The replication instructions are not clear. The cmake commands aren't clear since they do not specify the target CMakeLists.txt file you want to run. i.e., there is no path specified in the cmake command, plus they seem to be lacking "" around the arguments with semicolons in them.

To help clarify the build failure replication can you confirm that you are:
1) First building & installing all of LLVM, Clang (using what compiler?)
2) Then building 32-bit libomp library using the newly built clang compiler? You're using a new build directory so I'm assuming it's the standalone build of libomp and not using LLVM's CMakeLists.txt file but the -DLLVM_DIR (not used in standalone builds of libomp) makes me believe otherwise.

Any guidance would be greatly appreciated!

**Comment by jpeyton52** [comment]
I've submitted a fix: https://reviews.llvm.org/D120519

**Comment by BalaRishi-AMD** [comment]
@jpeyton52 
Thank you for the fix.
Now I'm not facing the build error.

**Comment by jpeyton52** [comment]
Glad the fix worked and thanks for reporting the issue!
