### ISSUE TITLE
[MLIR] Propagate tensor casts through linalg ops.

### ISSUE THREAD

**Issue by benvanik** [llvm/llvm-project#53302]
Currently `tensor.cast` and its associated dimension information is not propagated through linalg ops. Frontends with dynamic shape emission that rely on MLIR to propagate shapes (torch-mlir, dynamic mhlo, etc) suffer as all ops are treated as dynamic even if the static shapes are sitting right next to them:

```mlir
  %226 = linalg.init_tensor [1, 512, 12, 32] : tensor<1x512x12x32xf32>
  %227 = tensor.cast %226 : tensor<1x512x12x32xf32> to tensor<?x?x12x32xf32>
  %228 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d2, d1, d3)>], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%225 : tensor<?x12x?x32xf32>) outs(%227 : tensor<?x?x12x32xf32>) {
  ^bb0(%arg1: f32, %arg2: f32):  // no predecessors
    linalg.yield %arg1 : f32
  } -> tensor<?x?x12x32xf32>
```

Here it's known that the tensor has static leading dimensions of `1x512` but because the static shape is not propagated past the `tensor.cast` the op remains dynamic.

This appears on inputs, which a linalg canonicalizer could fold in to update the types:
```mlir
  %widen = tensor.cast %arg0 : tensor<?x2x3xf32> to tensor<?x?x3xf32>
  linalg.generic .... ins(%widen : tensor<?x?x3xf32>)
->
  linalg.generic .... ins(%arg0 : tensor<?x2x3xf32>)
```

It can also appear on outputs with additional static information, which a linalg canonicalizer could propagate up by moving the cast to the corresponding input:
```mlir
  %init = linalg.init_tensor [%dim0, %dim1, 3] : tensor<?x?x3xf32>
  %out = linalg.generic .... outs(%init : tensor<?x?x3xf32>
  %narrow = tensor.cast %out : tensor<?x?x3xf32> to tensor<?x2x3xf32>
->
  %init = linalg.init_tensor [%dim0, %dim1, 3] : tensor<?x?x3xf32>
  %init_cast = tensor.cast %init : tensor<?x?x3xf32> to tensor<?x2x3xf32>
  %out = linalg.generic .... outs(%init_cast : tensor<?x2x3xf32>
->
  %match = arith.cmpi eq, %dim1, %c2 : index
  assert %match, "dims must match"  // to be propagated elsewhere for analysis/etc
  %init = linalg.init_tensor [%dim0, 2, 3] : tensor<?x2x3xf32>
  %out = linalg.generic .... outs(%init : tensor<?x2x3xf32>
```

The general idea is to use as much static information available as possible. `tensor.cast` is an op that either introduces information (dim dynamic -> static) or removes it (dim static -> dynamic).

/cc @MaheshRavishankar

**Comment by MaheshRavishankar** [comment]
The way to propagate this information is to use the indexing maps of the operands. Every tensor dimension that is accessed using the same `AffineExpr` has to have its dimensions matching. For example

```
%c0 = arith.constant 0 : index
%c1 = arith.constant 1 : index
%c2 = arith.constant 2 : index
....
%4 = linalg.generic {
    indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1)>, affine_map<(d0, d2)>],
    iterator_types = ["parallel", "parallel", "parallel"]}
    ins (%0, %1, %2 : tensor<4x5x6xf32>, tensor<4x?xf32>, tensor<4x?xf32>) outs(..) { ... }
```
Here `tensor.dim %0, %c0` , `tensor.dim %1, %c0` and `tensor.dim %2, %c0` are all of size `4` since they are all accessed by using the `d0` expression in the `indexing_maps` of the `generic` op. Using the same logic, 

- since `tensor.dim %0, %c1` is `5` and `tensor.dim %1, %c1` are both accessed using `d1` ->  `tensor.dim %1, %c1 == 5`
- since `tensor.dim %0, %c2` is `6` and `tensor.dim %2, %c1` are both accessed using `d2` ->  `tensor.dim %1, %c1 == 6`

So you could replace the above with

```
%c0 = arith.constant 0 : index
%c1 = arith.constant 1 : index
%c2 = arith.constant 2 : index
....
%5 = tensor.cast %1 : tensor<4x?xf32> into tensor.cast<4x5xf32>
%6 = tensor.cast %2 : tensor<4x?xf32> into tensor.cast<4x6xf32>
%7 = linalg.generic {
    indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1)>, affine_map<(d0, d2)>],
    iterator_types = ["parallel", "parallel", "parallel"]}
    ins (%0, %5, %6 : tensor<4x5x6xf32>, tensor<4x5xf32>, tensor<4x6xf32>) outs(..) { ... }
```

If `%1` and `%2` are then produced by a `tensor.cast`, they could fold away.

Same logic could be used to absorb `tensor.cast` as well. 
```
%5 = tensor.cast %1 : tensor<4x5xf32> into tensor.cast<4x?xf32>
%6 = tensor.cast %2 : tensor<4x6xf32> into tensor.cast<4x?xf32>
%7 = linalg.generic {
    indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1)>, affine_map<(d0, d2)>],
    iterator_types = ["parallel", "parallel", "parallel"]}
    ins (%0, %5, %6 : tensor<4x?x?xf32>, tensor<4x?xf32>, tensor<4x?xf32>) outs(..) { ... }
```
Looking at producers of `%5` and `%6` that are `tensor.cast` operations, you could fold those into the `linalg.generic` op and the propagate that information into the other oeprands of the `linalg.generic` operation. So you could rewrite this as
```
%7 = linalg.generic {
    indexing_maps = [affine_map<(d0, d1, d2) -> (d0, d1, d2)>, affine_map<(d0, d1)>, affine_map<(d0, d2)>],
    iterator_types = ["parallel", "parallel", "parallel"]}
    ins (%0, %1, %2 : tensor<4x5x6xf32>, tensor<4x5xf32>, tensor<4x6xf32>) outs(..) { ... }
```

(That explanation ran too long than what I anticipated. But the logic is fairly simple. I can clarify if this isnt clear).

FYI @d0k (you are probably looking for something similar to this as well)
Also @nicolasvasilache to confirm that this is fine.

**Comment by gprateek93** [comment]
Solved here: https://reviews.llvm.org/D118929
