### ISSUE TITLE
Contradictory diagnostics when putting [[maybe_unused]] after record declaration

### ISSUE THREAD

**Issue by aaronpuchert** [llvm/llvm-project#53404]
The following code is correctly rejected:
```c++
struct X {} [[maybe_unused]];
```
But the diagnostics are somewhat contradictory:
```
<stdin>:1:15: error: 'maybe_unused' attribute cannot be applied to types
struct X {} [[maybe_unused]];
              ^
<stdin>:1:15: warning: attribute 'maybe_unused' is ignored, place it after "struct" to apply attribute to type declaration [-Wignored-attributes]
```
The errors says the attribute is not applicable to types, the warning says that placing it after `struct` makes it a type attribute. Indeed
```c++
struct [[maybe_unused]] X {};
```
is accepted without error. So perhaps the error is wrong? The standard also [explicitly allows](https://eel.is/c++draft/dcl.attr.unused#2) the attribute on "the declaration of a class [and] a typedef-name" among others.

CC @AaronBallman.

**Comment by aaronpuchert** [comment]
That distinction was lost on me. First I was thinking of "'maybe_unused' attribute cannot be part of a [declaration](https://eel.is/c++draft/dcl.spec.general#1)/[type specifier sequence](https://eel.is/c++draft/dcl.type.general#1)", but that misses attributes on [pointers](https://eel.is/c++draft/dcl.ptr#1), [arrays](https://eel.is/c++draft/dcl.array#3), [functions](https://eel.is/c++draft/dcl.fct#1) and maybe more.

Though perhaps we can simply say "'maybe_unused' attribute cannot be applied to types, only declarations"?

And should we do something about the additional warning? After all why bother whether the attribute is ignored if it's a compiler error anyway?

**Comment by erichkeane** [comment]
Yeah, unfortunately the difference between a 'Type' and a 'Type declaration' are subtle.  A Type Declaration applies to that single declaration (and depending on the attribute, is inherited by later declarations).  

It doesn't do anything to change the type, but can at least "seem" that way as it gets moved around/etc.  These attributes are unnecessarily to the 'correctness' of a program, as they don't change anything about the program itself (though again, can sometimes be abused to appear so).

A Type attribute modifies the type itself.  In the case of a Function-Type-Attribute, you have things like 'calling convention', which does things like make two function pointers different.  On pointers themselves, we have 'address space' type attributes, which change the 'type' of the thing from `int*` to `int*-in-addr-space-N`.  This is an important distinction, as these two types are no longer compatible.

We ALSO have ones like `vector_size`, which create whole new (vector) types!  Despite being applied to an `int` or `float` type alias, these are actually completely new types.

In practice, the former is easier to implement/create/use, as the type itself doesn't change.  So comparisons, overloads, etc are all still the same and compatible.  The latter requires plumbing an entirely new type throughout the compiler.

>>Though perhaps we can simply say "'maybe_unused' attribute cannot be applied to types, only declarations"?

I agree a better error message is likely a good idea here.  I'm not sure I completely-like your wording of it, nor can I come up with better.  

>>And should we do something about the additional warning? After all why bother whether the attribute is ignored if it's a compiler error anyway?

This is a good point. I suspect it is more valuable/valid as a 'note' instead of as a warning.

**Comment by aaronpuchert** [comment]
I'm no longer convinced we need to change something in Clang. The difference is subtle, but the messages are all correct.
