### ISSUE TITLE
malloc alignment regressions

### ISSUE THREAD

**Issue by urnathan** [llvm/llvm-project#53540]
https://reviews.llvm.org/D100879 added smarts to annotate the known allocator functions with alignment information about their return values.  This has caused code generation regressions on x86_64 linux systems that use the jemalloc (and musl?) allocators.  I.e. https://bugzilla.mozilla.org/show_bug.cgi?id=1741454.  While the x86_64 ABI specifies allocators must return 16-byte aligned pointers, those allocators will return 8-byte aligned pointers /iff/ the size being allocated is 8 or fewer bytes.  Jemalloc does this for performance reasons -- it allocates from a pool of densly packed 8-byte objects, which gives it a 50% memory saving there and subsequent caching improvement.  I don't know performance numbers (jemalloc guys?)

I would be interested in what performance difference assuming 16-byte minimum alignment (as opposed to 8-byte) on the allocators gives clang's code generation.  Is there such data?

[I don't know why user code might want to allocate a ton of 8 byte objects and have individual 8-byte pointers to them, but that appears to be the case.)

Anyway,  clang's getNewAlign (clang/include/clang/Basic/TargetInfo.h) is documented thusly:
  /// Return the largest alignment for which a suitably-sized allocation with
  /// '::operator new(size_t)' or 'malloc' is guaranteed to produce a
  /// correctly-aligned pointer.

Notice the 'suitably-sized allocation' caveat.  Either poor wording, or getNewAlign is not guaranteeing smaller alignment for smaller allocations.  I have not audited all the uses of getNewAlign to see if they presume the value is a conditional guarantee or not.

D100879 is unconditionally using that alignment, regardless of the size of allocation.

If getNewAlign's documentation is incorrect, then it would seem linux systems need some more target-specific overrides, possibly creating a 'x86_64-FOO-linux' triple.  (IMHO such a new triple would be sad.)

Alternatively, a new target config 'getMinNewAlign' that returns the minimum alignment guarantee. (8 in this case), and use that for annotations?  (Perhaps also rename getNewAlign to getMaxNewAlign, as 'new alignment' is ambiguous on these systems?)

**Comment by fhahn** [comment]
cc @davidbolvansky

**Comment by davidbolvansky** [comment]
Please read the discussion in that patch and especially post by rjmccall:

“ Platforms are permitted to make stronger guarantees than the C standard requires, and it is totally reasonable for compilers to assume that malloc meets the target platform's documented guarantees. Arguably, libraries should not be replacing malloc if they fail to meet the platform's documented guarantees.”

—————-
“ code generation regressions”

Can Mozilla or anybody provide some real numbers / results?



——————
Other than that, you can implement check if alloc size is smaller than 16, use align 8. Or add option to clang to force certain alignment and getNewAlign will return this value.

**Comment by MaskRay** [comment]
@jyknight has an in-flight revert https://reviews.llvm.org/D118804 to fix the regression.

**Comment by davidtgoldblatt** [comment]
> https://reviews.llvm.org/D100879 added smarts to annotate the known allocator functions with alignment information about their return values. This has caused code generation regressions on x86_64 linux systems that use the jemalloc (and musl?) allocators. I.e. https://bugzilla.mozilla.org/show_bug.cgi?id=1741454.

I don't *think* this patch is restricted to the x86_64/Linux/GNU case; I believe it generates incorrect code for (e.g.) FreeBSD, where I can say a little more authoritatively that this isn't justifiable. (Sorry, I'm actually on parental leave right now and so don't easily have access to my work machine, or indeed a computer with a compiler on it).

> While the x86_64 ABI specifies allocators must return 16-byte aligned pointers

(as a nit, I don't think this is actually true? The ABI doc doesn't discuss the heap much at all as far as I remember. I could certainly be incorrect of course).

> , those allocators will return 8-byte aligned pointers /iff/ the size being allocated is 8 or fewer bytes. Jemalloc does this for performance reasons -- it allocates from a pool of densly packed 8-byte objects, which gives it a 50% memory saving there and subsequent caching improvement. I don't know performance numbers (jemalloc guys?)

I don't have the numbers easily at hand, but it was in the realm of 0.5%-1% savings in CPU and memory on the big server-y binaries I tested.

There are a couple benefits:
- The straightforward "use half as many bytes for the data" case.
- It allows mutex sharding by size class to split out the 8-byte case from the 16-byte case (this are two of the hottest size classes, and hence hottest locks).
- Size information is a useful hint for use; fragmentation tends to be lower the more that different allocations are segregated by use.

> I would be interested in what performance difference assuming 16-byte minimum alignment (as opposed to 8-byte) on the allocators gives clang's code generation. Is there such data?
> [I don't know why user code might want to allocate a ton of 8 byte objects and have individual 8-byte pointers to them, but that appears to be the case.)

Usually a user won't return `malloc(sizeof(int))` or whatever, of course. But something that happens super-frequently is they'll have a `std::vector<int>` that usually has <= 2 elements, or write `strdup(a_string_thats_usually_small)`. So the small allocations are a byproduct of users choosing simple abstractions rather than deliberately using the heap wastefully.

>Please read the discussion in that patch and especially post by rjmccall:
> “ Platforms are permitted to make stronger guarantees than the C standard requires, and it is totally reasonable for compilers to assume that malloc meets the target platform's documented guarantees. Arguably, libraries should not be replacing malloc if they fail to meet the platform's documented guarantees.”

FWIW, I'm not sure I think that the phrasing here is really meant to document a requirement glibc intends to impose on replacement mallocs, as opposed to just being informational about the glibc implementation. I'll poke the glibc maintainers about it and see what they say.

**Comment by tstellar** [comment]
Merged: f5f0bd8e3d972d040827c88adf1a9880ebcb821e
