### ISSUE TITLE
clang-13.0.0: PowerPC build target ignores -fno-builtin

### ISSUE THREAD

**Issue by dmlary** [llvm/llvm-project#53593]
Using clang 13.0.0 to compile for a powerpc target, the `-fno-builtin` flag is ignored.

```c
#include <stdio.h>

/* this define shouldn't matter, but exposes builtins being defined */
#define __alloca(s)     my_alloca(s)

int main(void) {
    printf("Hello World\n");
    return 0;
}
```

When compiling for powerpc target the `__alloca()` macro collides with the compiler built-in `__alloca()` definition:
```txt
$ clang -fno-builtin -Wall -Werror --target=powerpc64 hello.c -o hello
hello.c:2:9: error: '__alloca' macro redefined [-Werror,-Wmacro-redefined]
#define __alloca(s)     my_alloca(s)
        ^
<built-in>:389:9: note: previous definition is here
#define __alloca __builtin_alloca
        ^
1 error generated.
```

When compiling for x86_64 target the problem does not occur:
```txt
$ clang -fno-builtin -Wall -Werror --target=x86_64 hello.c -o hello
$ ./hello
Hello World
```

**Comment by efriedma-quic** [comment]
-fno-builtin doesn't affect macros or "__"-prefixed builtin functions at all; it only affects C library functions like printf.  This is by design.

On PowerPC targets, clang defines a bunch of additional macros for compatibility with IBM's compiler; __alloca is one of these. You can `#undef __alloca` or pass `-U__alloca` if you want. More generally, though, portable code should avoid defining macros and symbols prefixed with a double-underscore. Such identifiers are reserved for usage by the compiler and standard library.

**Comment by dmlary** [comment]
Is there a way to disable all of these compatibility macro definitions? I’m working with an old set of system include files that want to define all of these system macros themselves.

**Comment by efriedma-quic** [comment]
You mean all at once, as opposed to one-by-one?  No.  They're unconditionally defined for any ppc-linux target.

The complete list of macros I'm talking about is at https://github.com/llvm/llvm-project/blob/0d54457f8aed169dff8a668059979a2646afc3fc/clang/lib/Basic/Targets/PPC.cpp#L92 .  They're mostly unlikely to conflict with code that isn't ppc-specific.

**Comment by dmlary** [comment]
Haha, "mostly unlikely."  Here's the situation where I'm hitting the problem:

https://github.com/vocho/openqnx/blob/cc95df3543a1c481d4f8ad387e29f0d1ff0c87fe/trunk/lib/c/public/alloca.h#L52:L54

`-U__alloca` gets me past the duplicate `#define` problem, but even with `-fno-builtin`, the prototype for `__builtin_alloca()` is being declared, and it does not match the one in my system include files.  As they're the OS include files, I'm unable to modify them.

New question, is there a way to disable the function declarations for builtins?

**Comment by efriedma-quic** [comment]
Oh, that's a different issue.  No, there isn't any way to turn off builtin recognition for __builtin_*.  It hasn't come up in the past because user code is very unlikely to want to define their own identifiers named __builtin_*.  Such identifiers are reserved for the compiler, anyway.

As an hack, you could probably `-D__builtin_alloca=my__builtin_alloca`.  That said, I'm not sure that does what you want; how do you plan to implement alloca without calling the compiler builtin?

**Comment by dmlary** [comment]
Ok, thanks.

There's a crusty old object file I have to link against that contains custom built-ins, along with what I can only assume is some magic from 1998.  Honestly, I'm not directly using alloca, but the header file is included by a chain of other headers, so it is where I'm stuck.

Thank you for your help.
