### ISSUE TITLE
[X86] Should FeatureVBMI2 inherit from FeatureVBMI instead of FeatureBWI?

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#53659]
The VBMI ISAs are currently defined as:
```
def FeatureVBMI     : SubtargetFeature<"avx512vbmi", "HasVBMI", "true",
                      "Enable AVX-512 Vector Byte Manipulation Instructions",
                                      [FeatureBWI]>;
def FeatureVBMI2    : SubtargetFeature<"avx512vbmi2", "HasVBMI2", "true",
                      "Enable AVX-512 further Vector Byte Manipulation Instructions",
                                      [FeatureBWI]>;
```
Would it be better for FeatureVBMI2 to inherit from FeatureVBMI instead of FeatureBWI?

**Comment by phoebewang** [comment]
I'd take it as a least dependency rather than inheritance relationship in existing targets. For example, recently new AVX512 ISAs always have VL variants, but we never inherit `FeatureVLX` there.
AFAIU, we should make the features as independent as possible, so that we can control the codegen in a fine-grained way.

**Comment by RKSimon** [comment]
OK - closing as won't fix
