### ISSUE TITLE
libclang.so.13 being installed on 14.0.0 rc1

### ISSUE THREAD

**Issue by brooksdavis** [llvm/llvm-project#53684]
When packaging for FreeBSD I noticed that there's a lib/libclang.so.13 linked to libclang.so.14.0.0

**Comment by tstellar** [comment]
This is by design.  There was no ABI change for libclang between LLVM 13 and 14, so the soname was kept the same.

**Comment by brooksdavis** [comment]
Makes sense. I noticed because a substitution for an internal LLVM_MAJOR became a magic 13 in the packing list.

**Comment by foutrelis** [comment]
@tstellar Do you believe this has any potential to cause issues on Arch (and Fedora?) with llvm13-libs shipping an ld.so.conf.d file containing `/usr/lib/llvm13/lib`? From what I can tell, the `libclang.so.13` library in there (which links to `libLLVM-13.so`) has precedence over clang 14's `/usr/lib/libclang.so.13`. The latter links to `libLLVM-14.so` so they're not completely equivalent.

I imagine this would definitely be an issue if the new `libclang.so.13` was shipping `LLVM_14` versioned symbols. In such a case, could an application be linked to it (e.g. built in a chroot with only the new library) and then at runtime try to load the old `libclang.so.13` (if `clang13-libs` is installed) and fail due to missing versioned symbols?

To avoid this ambiguity, I'm thinking of excluding `libclang` and `c-index-test` from `LLVM_DISTRIBUTION_COMPONENTS` for the clang13 package but I'm not entirely sure if my understanding of all this is correct. 🐭

**Comment by tstellar** [comment]
@foutrelis I think having two versions of libclang.so.13 installed on your system (one linking with LLVM13 and one with LLVM14) is likely to cause issues.  I would recommend trying to avoid this.  Since this has been an issue for many people I'm wondering if we should revert this change and switch back to the soname matching the version number.
