### ISSUE TITLE
Header paths not correct for in-memory Clang ORC JIT compiler on macOS

### ISSUE THREAD

**Issue by gogins** [llvm/llvm-project#53793]
This is in the context of embedding the Clang front end and ORC Jit compiler into the 
Csound software sound synthesis language: https://github.com/gogins/clang-opcodes.

The project is a plugin for Csound that 
compiles C++ source code at run time and links it into the Csound process, 
which can call then into the compiled C++ code. My project adapts this example 
from an older tag in the LLVM repository: `https://github.com/llvm/llvm-project/tree/release/13.x/clang/examples/clang-interpreter`

My project works very well on Ubuntu Linux 20.04, but I have not been able to get it 
to work on macOS.

The issue appears to be that the LLVM software infers an incorrect resource directory from the 
binary module that is executing the compile process. This is possibly related to #50649 and #16284.

My system:
```
michaelgogins@Michaels-MacBook-Pro clang-opcodes % uname -a
Darwin Michaels-MacBook-Pro.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64
```

LLVM is version 13.0.1 installed using Homebrew at:

```
michaelgogins@Michaels-MacBook-Pro clang-opcodes % ls -ll /opt/homebrew/Cellar/llvm/13.0.1
total 24
-rw-r--r--    1 michaelgogins  admin   1807 Feb  5 12:43 INSTALL_RECEIPT.json
-rw-r--r--    1 michaelgogins  admin   4499 Jan 20 22:31 README.md
drwxr-xr-x    3 michaelgogins  admin     96 Jan 20 22:31 Toolchains
drwxr-xr-x  159 michaelgogins  admin   5088 Feb  5 12:43 bin
drwxr-xr-x   13 michaelgogins  admin    416 Jan 20 22:31 include
drwxr-xr-x  450 michaelgogins  admin  14400 Feb  5 12:43 lib
drwxr-xr-x    9 michaelgogins  admin    288 Jan 20 22:31 libexec
drwxr-xr-x    9 michaelgogins  admin    288 Jan 20 22:31 share
```

Please note, version 13.0.1 does not 
upgrade or replace Apple Clang but is istalled alongside it.

My system uses the Apple XCode development system with command line tools, but Apple's Clang uses LLVM 12 which 
is not optimal for my project.

I hypothesize that the issue is that, on Linux, LLVM and Clang provided by system 
packages either do not need to infer the resource directory, or do so in a way 
that is compatible with my project, but this does not seem to work on macOS.

I have attached a cut-down version of my project that reproduces the confusion 
of the resource directory. E.g.:
```
ResourceDir: /Users/michaelgogins/lib/clang/13.0.1.
In file included from /var/folders/tc/x44lyz_j7bn468tgvvb352t40000gn/T//clang_opcode_TICnQK.cpp:1:
In file included from /opt/homebrew/Cellar/llvm/13.0.1/include/c++/v1/iostream:36:
/opt/homebrew/Cellar/llvm/13.0.1/include/c++/v1/__config:1151:46: fatal error: cannot open file '/opt/homebrew/Cellar/llvm/13.0.1/include/c++/v1/pthread.h': No such file or directory
      (defined(__MINGW32__) && __has_include(<pthread.h>))
```
[clang_jit_test.zip](https://github.com/llvm/llvm-project/files/8054304/clang_jit_test.zip)

**Comment by lhames** [comment]
ORC's involvement here is incidental -- this is a clang search path issue.

@gogins -- If you `#include "pthread.h"` in a regular source file and try to compile that on the command line with clang-13 does it error out in the same way? If so then this seems like a clang or home-brew configuration issue. If the command-line tool works but the JIT doesn't then it's likely to do with how your JIT is configured.

**Comment by gogins** [comment]
No, compiling with command-line clang works fine for pthread.h. The issue arises when the clang front end is invoked from a program that has embedded the clang front end instead of running clang as a program. This is not a Homebrew issue. I do not believe this issue is caused by an incorrect invocation of the compiler front end, I have tried many many many alternative invocations.

It is very clear that the clang front end insists on constructing the resource directory in a wrong way, and using it in the wrong way. In my view the "resource directory" should not be used to construct header search paths in this context of embedding Clang, or, at least, there should be the option of turning off this method of determining header directories altogether. I tried to turn it off using all the compiler options that seemed likely to work, but that did not work.

It would be helpful if you would run my example and especially if you could supply compiler options (given as a string in the clang_jit_test.cpp file, not in a build script) that would work.

**Comment by gogins** [comment]
Thanks for your response. I agree that the clang invocation is
misconfigured -- but not by me, rather by code in the Clang front end,
perhaps in the Driver, CompilerInvocation, or CompilerInstance classes. I
don't think it's me because I tried every combination of header file paths
and compiler flags that I could think of. But I'd like to be wrong about
this and find some flags that work for this embedded use case.

Regards,
Mike

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by weliveindetail** [comment]
I agree with Lang, there is no connection to the JIT here. @gogins let's review your error message:
```
ResourceDir: /Users/michaelgogins/lib/clang/13.0.1.
In file included from /var/folders/tc/x44lyz_j7bn468tgvvb352t40000gn/T//clang_opcode_TICnQK.cpp:1:
In file included from /opt/homebrew/Cellar/llvm/13.0.1/include/c++/v1/iostream:36:
/opt/homebrew/Cellar/llvm/13.0.1/include/c++/v1/__config:1151:46: fatal error: cannot open file '/opt/homebrew/Cellar/llvm/13.0.1/include/c++/v1/pthread.h': No such file or directory
      (defined(__MINGW32__) && __has_include(<pthread.h>))
```

In the first line Clang dumped the path to your resource directory. I think that's fine and it has no connection to the following error diagnostic:
```
"cannot open file '[...]/pthread.h': No such file or directory"
in clang_opcode_TICnQK.cpp:1 --> iostream:36 --> __config:1151
```

Well, you include `iostream`, which needs `__config` and this one has an issue in line 1151. Interestingly, the `__config` that homebrew installed with llvm 13.0.1 on my system doesn't include `pthread.h` at all, but it has this last line from your error message:
```
(defined(__MINGW32__) && __has_include(<pthread.h>))
```

Any chance the issue originates from `__has_include(<pthread.h>)` here? But how would `defined(__MINGW32__)` evaluate true on macOS in the first place? Well, I am afraid there is a lot of pre-processor magic involved in the iostream and threading headers. If you want to use them, you will need to figure out how it works. Maybe for the beginning try and avoid them. Using `printf` is so much easier: no threading, no static init, no templates.

If you embed Clang as a library into your code, you have to configure it right. Getting this to work cross-platform is a big task. The issue here is only the tip of the iceberg.

After patching your repro for my system, I get the same error. Unfortunately, I won't find the time to debug it for you, but I wish you good luck. C++ JIT integration for Csound sounds great! :)

**Comment by gogins** [comment]
I submitted an issue to llvm. The first person did not understand the issue well and passed it on. The second person did understand the issue better, but not well enough, and said he would not debug it. It is not _my_ job to debug LLVM so I am closing this issue.

I will redo the opcodes not to embed the compiler but rather to shell out and run the compiler command and load a resulting plugin.

**Comment by weliveindetail** [comment]
Sorry, I just wanted to help all of us to understand your issue better. I am not a LLVM employee either.

**Comment by vgvassilev** [comment]
Hi @gogins, this seems like a frontend issue indeed. I looked at your attachment and it seems we can benefit from the recent changes in the infrastructure to reduce the code you have. You can take a look at https://github.com/llvm/llvm-project/blob/f037082714a0fd48568a1f10ef3e4db8919e1523/clang/unittests/Interpreter/ExceptionTests/InterpreterExceptionTest.cpp#L37-L46

The problem you describe is likely indeed due to the clang resource directory. The resource directory for clang is very important as it provides a bunch of builtin headers which clang uses. It is usually installed by clang and searched for on a set of locations relative to the binary. If you embed a clang instance then the resource directory is a problem. Incidentally, we had a test which had a similar setup where it needed to find the resource directory [here](https://github.com/llvm/llvm-project/commit/319ce98011742141dad8dd95a2f9de9c0449be5c#diff-a2d07e228a904a2d045f211fb5feb752d60da87835c943731a731ec3a567e603R53-R71). The best approach we could come up at the time is something similar to:
```c++
static std::string MakeResourcesPath() {
  // Dir is bin/ or lib/, depending on where BinaryPath is.
  void *MainAddr = (void *)(intptr_t)GetExecutablePath;
  std::string BinaryPath = GetExecutablePath(/*Argv0=*/nullptr, MainAddr);

  // build/tools/clang/unittests/Interpreter/Executable -> build/
  llvm::StringRef Dir = llvm::sys::path::parent_path(BinaryPath);

  Dir = llvm::sys::path::parent_path(Dir);
  Dir = llvm::sys::path::parent_path(Dir);
  Dir = llvm::sys::path::parent_path(Dir);
  Dir = llvm::sys::path::parent_path(Dir);
  Dir = llvm::sys::path::parent_path(Dir);
  SmallString<128> P(Dir);
  llvm::sys::path::append(P, Twine("lib") + CLANG_LIBDIR_SUFFIX, "clang",
                          CLANG_VERSION_STRING);

  return std::string(P.str());
}
```

I hope that helps. Thanks @lhames for the ping!

**Comment by dwblaikie** [comment]
> It is not my job to debug LLVM so I am closing this issue.

(just as an aside: It's no one's job to debug /this/ issue specifically, we're all here volunteering our time for this sort of thing - some of us are paid to work on LLVM for our day jobs, but that's generally to implement features/fix bugs that are relevant to our respective employers)

**Comment by vgvassilev** [comment]
@gogins, yes, that might be the easiest way to solve your resource-dir issue.

**Comment by vgvassilev** [comment]
Yes, the interpreter is basically clang. All of your JIT and Clang frontend setup is sunk under it.
