### ISSUE TITLE
Clang-format inserts space between static_cast<...> and expression that deferences

### ISSUE THREAD

**Issue by zhihaoy** [llvm/llvm-project#53876]
Sample:

```cpp
auto f = [](storage fn_, Args &&...args) {
  static_cast<T &> (*get<T>(fn_))(std::forward<Args>(args)...);
};
```

If you remove `*`, that space following `static_cast<T &>` disappears (correctly).

**Comment by mkurdej** [comment]
Minimal repro with LLVM style:
```
static_cast<T>(x)(y); // good
static_cast<T> (*x)(y); // bad
```

**Comment by mkurdej** [comment]
This might be harder than I thought (unless we special-case `static_cast` and its alike).
Clang-format gets confused about this because you can have as well:
```
using my_alias = some_return_type<T> (*function_pointer)(parameters);
```

Related code is in https://github.com/llvm/llvm-project/blob/331e8e4e27be5dd673898a89a7cf00e76903216a/clang/lib/Format/TokenAnnotator.cpp#L317-L327.

**Comment by zhihaoy** [comment]
_discarded-value expressions_ that start with casts without using their results are rare, `static_cast<T>` when `T` may be `void` is roughly the only use case. `std::function<void(int)> (*f)(3);` is most vexing parsing, so I guess special-casing isn't bad.

**Comment by mkurdej** [comment]
Hmm, the example I gave was wrong in fact. It should be:
```
using function_pointer_type = some_return_type<T> (*)(parameters);
```
otherwise one gets "error: type-id cannot have a name" or sth like this.

Or:
```
typedef some_return_type<T> (*function_pointer_type)(parameters);
```
But then we can recognize the typedef.

However, we can simply have as well:
```
some_return_type<T> (*function_pointer_variable)(parameters);
function_pointer_variable = &some_function;
return function_pointer_variable(args);

// cf. with
static_cast<T> (*function_pointer_variable)(arguments);
```
And this one is a somewhat difficult to distinguish I think.

Please note that clang-format has no knowledge of what types and variables (they are all identifiers), so things like *discarded-value expressions* is not something we can detect.

Anyway, I think that treating `_cast`s specially is the way to go.

**Comment by mkurdej** [comment]
Revision URI: https://reviews.llvm.org/D120140

**Comment by zhihaoy** [comment]
> _discarded-value expressions_ that start with casts without using their results are rare, `static_cast<T>` when `T` may be `void` is roughly the only use case. `std::function<void(int)> (*f)(3);` is most vexing parsing, so I guess special-casing isn't bad.

Oh, I see, this is not casting to `void`. It is forming something with a function call expression by calling a function template-like thing. So yes, it is general. But clang-format can't distinguish that from a class template.

**Comment by zhihaoy** [comment]
Yep, it works.

**Comment by mkurdej** [comment]
Reopening due to test failures in polly.
