### ISSUE TITLE
llvm-extract: expected top-level entity

### ISSUE THREAD

**Issue by akash-isu** [llvm/llvm-project#54068]
I compiling an OpenMP C code to IR using LLVM 11.0.1 and I want to extract a function from that IR.
However, when I do :
`llvm-extract --func=<func_name> <file.ll> -S`
it returns a **expected top-level entity** error at this line:
`source_filename = "filename.c".`

The previous lines are:
```
; __CLANG_OFFLOAD_BUNDLE____START__ openmp-nvptx64
; ModuleID = 'filename.c'
```

What might be causing this behavior and how do I resolve this?

**Comment by jhuber6** [comment]
The output you get currently when using OpenMP offloading uses a tool called `clang-offload-bundler` to pack the host and device code into a single file. If you want to extract the function from either one you'll need to either manually delete the offload bundle information, or use `-save-temps` instead. The output from `-save-temps` is larger because it will include CUDA's libdevice and other bitcode libraries along with it.

**Comment by akash-isu** [comment]
Thank you. It works. 
Just a follow up question. If I use -save-temps, there are 2 IR files generated: i)file-host-x86_64-unknown-linux-gnu.ll and file-openmp-nvptx64.ll. What is the use of each of these?

**Comment by jhuber6** [comment]
When we generate 

> Thank you. It works. Just a follow up question. If I use -save-temps, there are 2 IR files generated: i)file-host-x86_64-unknown-linux-gnu.ll and file-openmp-nvptx64.ll. What is the use of each of these?

When we generate offloading code we need to compile the code for two architectures, the host and the device we're offloading to. In your case you are compiling for an x86_64 host offloading execution to an nvptx64 device. Normally these are combined into the single file you saw to follow the compilation tradition of one output per file. For a more in-depth look there's some documentation [here](https://clang.llvm.org/docs/OffloadingDesign.html). It describes a newer approach that will be used for LLVM 15, but most of it is the same.

**Comment by akash-isu** [comment]
Thank you so much for the clarification.
