### ISSUE TITLE
[P0674R1] support bounded array in "make_shared"

### ISSUE THREAD

**Issue by nickhuang99** [llvm/llvm-project#54097]
Before clang13, the bounded array is supported by make_shared. i.e.
shared_ptr<int[1]> ptr=make_shared<int[1]>();

However, since clang13, it gives error (https://www.godbolt.org/z/o1aoMzjTY)

<pre><code> 
      error: static_assert failed due to requirement '!is_array&lt;int [1]&gt;::value' "make_shared&lt;T[]&gt; not supported"
      static_assert(!is_array&lt;_Tp&gt;::value, "make_shared&lt;T[]&gt; not supported");
      ^             ~~~~~~~~~~~~~~~~~~~~~`
</code></pre>

**Comment by davidbolvansky** [comment]
@ldionne

**Comment by davidbolvansky** [comment]
This is not libc++ issue. Error came from libstdc++ with Clang 13 and GCC 11.2 as well.


Output of x86-64 clang 13.0.1 (Compiler #1)
In file included from <source>:1:
In file included from /opt/compiler-explorer/gcc-11.2.0/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../include/c++/11.2.0/memory:77:
/opt/compiler-explorer/gcc-11.2.0/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../include/c++/11.2.0/bits/shared_ptr.h:860:7: error: static_assert failed due to requirement '!is_array<int [1]>::value' "make_shared<T[]> not supported"

Clang trunk and GCC trunk works fine, so I dont think there is anything to be fixed.  You should report this issue to GCC devs and maybe they could fix it for 11.3.

**Comment by davidbolvansky** [comment]
Or maybe there is something.. If you use -std=c++20 -stdlib=libc++ then compilation fails:

<source>:9:28: error: no matching function for call to 'make_shared'
    shared_ptr<int[1]> ptr=make_shared<int[1]>();
                           ^~~~~~~~~~~~~~~~~~~
/opt/compiler-explorer/clang-trunk-20220227/bin/../include/c++/v1/__memory/shared_ptr.h:961:17: note: candidate template ignored: requirement '!is_array<int[1]>::value' was not satisfied [with _Tp = int[1], _Args = <>]
shared_ptr<_Tp> make_shared(_Args&& ...__args)
                ^

**Comment by davidbolvansky** [comment]
cc @Quuxplusone

**Comment by Quuxplusone** [comment]
The syntax `std::make_shared<int[1]>()` is new in C++20 (overload 3 in https://en.cppreference.com/w/cpp/memory/shared_ptr/make_shared ). It was introduced by Peter Dimov's [P0674](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0674r1.html). Prior to C++20, all you're allowed to do is `std::make_shared<int[]>(1)` (and I bet that's what you meant to do anyway). libc++ trunk currently supports `std::make_shared<int[]>(1)` but not `std::make_shared<int[1]>()`.

@nickhuang99's https://www.godbolt.org/z/o1aoMzjTY shows merely that libstdc++11 didn't support `std::make_shared<int[1]>()` yet.

https://godbolt.org/z/6bvK3rvxv shows that libstdc++ trunk and MSVC trunk both support `std::make_shared<int[1]>()`, but libc++ trunk still doesn't.

There's a PR for P0674 support at https://reviews.llvm.org/D62641 . @ldionne has said it's "basically blocked on https://reviews.llvm.org/D114903" (which is a Clang compiler feature).

**Comment by philnik777** [comment]
The feature has been implemented.
