### ISSUE TITLE
Backport fix for mangling of aliases

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#54103]
/cherry-pick 54b909de682bfa4e3389b680b0916ab18c99952a

**Comment by tstellar** [comment]
@rnk What do you think about backporting this? https://github.com/llvm/llvm-project/commit/54b909de682bfa4e3389b680b0916ab18c99952a

**Comment by rnk** [comment]
I actually think this is somewhat risky to backport. It has the potential to really change behavior, it changes alias symbols in object files.

I see the motivation is to use this in Rust, which I presume enables the similar function merging pass, which generates these kinds of aliases. Instead of backporting this, should Rust pre-adopt the strategy outlined in https://github.com/llvm/llvm-project/issues/54090 for getting rid of IR mangling? Rust could create functions, and then, for those three annoying calling conventions on i*86-windows*, rename them using `Mangler::getNameWithPrefix`, using the special escape.

Or we could go forward with the backporting. The impact here is really very limited to papering over a Windows oddity, and there isn't nearly as much exotic usage of aliases on Windows as there are for example in glibc for Linux and other OSs.

**Comment by nikic** [comment]
@Amanieu Thoughts on that? I see that you are already calling into the mangler for inline asm sym support, so I guess it wouldn't be much of a stretch to also explicitly mangle the function names themselves on our side?

**Comment by Amanieu** [comment]
[Here](https://rust.godbolt.org/z/s1Es53ocv) is a reduced example of the Rust code that led to this bug. I encountered this in practice while working with generic fastcall functions which end up being called from a different codegen unit.

I think this should be backported since this is a real bug in LLVM that needs to be fixed either with my patch or by fixing `MergeFunctions` when it creates the alias.

Mangling the function names on our side would be awkward: we would need to first create the LLVM function with the unmangled name, call `LLVMRustGetMangledName` on that function and then change its name to `\01` + the mangled name.

**Comment by tstellar** [comment]
Merged: cdd8cca0c33c 8400036358c8 f8ca5fabdb54 d245bcf536a3
