### ISSUE TITLE
IR outliner behaves strangely on outlined functions without returns

### ISSUE THREAD

**Issue by ornata** [llvm/llvm-project#54124]
The following code crashes the IR outliner in asserts builds:

https://godbolt.org/z/TP1v9WYsr (1)

This was bugpointed from a larger program.

Further reduction gives us this:

https://godbolt.org/z/6Pav4hnfh (2a)
https://godbolt.org/z/j9fWsMGze (2b)

I'm not sure if (2a,b) are over-reduced, but the behaviour is strange. Hopefully they reflect what is going wrong in (1) as well.

In (2a,b), we have identical functions like this:

```
define void @fN() {
bb:
  br label %bb1
bb1:
  br label %bb1
}
```

_Without asserts_, these are outlined and we end up with

```
define void @fN() {
  call void @outlined_ir_func_0()
  ret void
}
```

This seems incorrect, because the original `@fN` _doesn't have a return_.

Also, it seems like the IR outliner misses the first candidate in this case. I would expect

```
define void @f1() {
 call void @outlined_ir_func_0()
}

define void @f2() {
  call void @outlined_ir_func_0()
}

define void @f3() {
  call void @outlined_ir_func_0()
}

define internal void @outlined_ir_func_0() {
  br label %bb_to_outline
bb_to_outline: 
  br label %bb1
bb1:
  br label %bb1
}
```

But instead we don't outline from `@f1` at all (on top of the existing issue with the added `ret` instructions)

**Comment by ornata** [comment]
@AndrewLitteken any ideas here?

**Comment by AndrewLitteken** [comment]
For the `ret` instructions, I suspect that's coming from the CodeExtractor.  If it can't find any exit blocks in the extracted region, it adds a return instruction under the assumption that it outlined the return function.  (See CodeExtractor.cpp:1390).

The assertion comes from the fact that the outliner uses return instructions to find the different output paths.  And since the CodeExtractor didn't find any exits, it didn't add any return instructions, so there aren't any to check for and set up.  This could likely be fixed by inserting a ret void instruction in the case where one does not exist in order to make everything line up properly.

The reason the first function isn't outlined looks like it is a quirk leftover from only outlining within a single basic block.  When that was the case, a found region of length one was not added to the list.  But since we now outline across basic blocks, in the case of a one instruction basic block, when nothing has been attempted to be outlined, or an illegal item was attempted to be outlined, it will not add it to the list since it does not think it is part of a long enough instruction string.  This can probably be rectified pretty simply by getting rid of the requirement that an instruction is only added to the instruction list if it is longer than one instruction.

**Comment by AndrewLitteken** [comment]
> This could likely be fixed by inserting a ret void instruction in the case where one does not exist in order to make everything line up properly.

Actually, this probably isn't right.  I think we might just need to remove that check and make sure that nothing else in the function expects return blocks.  But I am pretty sure that is limited to output handling, and if there are no exits, there will be no output handling.

**Comment by ornata** [comment]
> The reason the first function isn't outlined looks like it is a quirk leftover from only outlining within a single basic block. When that was the case, a found region of length one was not added to the list. But since we now outline across basic blocks, in the case of a one instruction basic block, when nothing has been attempted to be outlined, or an illegal item was attempted to be outlined, it will not add it to the list since it does not think it is part of a long enough instruction string.

I'm not sure if I follow. If each of these regions was being counted as one instruction, then why are two of the functions outlined from? I'd expect no outlining behaviour if that was true?

**Comment by AndrewLitteken** [comment]
Right now the module gets encoded as:

```
0 for second br in first function
illegal instruction denoting new function
0 for first br in second function
0 for second br in second function
illegal instruction denoting new function
0 for first br in third function
0 for second br in third function
```

The outliner iterates over each block separately, and has a flag for whether the previously seen instruction was valid for similarity matching, if it is set when another valid instruction is seen, it considers the block long enough to be added to the overall list.  But after this is done for the first time in the module, the flag remains set, so any instructions from a basic block, no matter the length, get added.

The reason the first `br` in the first function doesn't get added is because there is only one instruction in the first basic block.  So when it's done iterating over the single instruction in the block, it does not consider it long enough to add to the list, and doesn't.  But the next block, it sees the branch, and remembers the previous branch, considering it to be of valid length adds the second basic block to the list.

For the rest of the functions, the flag for long enough length is set, so it adds each basic block to the list.

I'm not sure we actually need this flag anymore as it serves as more a hinderance since we could be outlining one instruction basic blocks.

**Comment by ornata** [comment]
I see!

I think that you're right; the single instruction optimization isn't relevant anymore. For now I'd just drop it. There's probably a similar optimization for multi-block outlining, but right now, I think we're missing a lot of opportunities.

**Comment by AndrewLitteken** [comment]
first patch: https://reviews.llvm.org/D120786

**Comment by AndrewLitteken** [comment]
second patch for returns: https://reviews.llvm.org/D120868

**Comment by xgupta** [comment]
This is also fixed on trunk -https://godbolt.org/z/nErbernbb.
