### ISSUE TITLE
clang-format: LeaveAlone

### ISSUE THREAD

**Issue by kwk** [llvm/llvm-project#54137]
This issue is describing a vision that I have for `clang-format`, and a plan for how to proressively get there. Feel free to comment.

# Current state

Currently `clang-format` when applied to a file or a patch formats according to all [format style options](https://clang.llvm.org/docs/ClangFormatStyleOptions.html). You can [turn off formatting](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#disabling-formatting-on-a-piece-of-code) for a code section using comments or completely with `DisableFormat`ting. All of these options completely turn off formatting. There's no way to enable only a specific format style.

# Desired state

## Take existing format style and turn-off individual style options (first part)

Let's say I'd love to take a style like LLVM or Google and turn off the alignment of escaped newlines (see `AlignEscapedNewlines`). Right now, all values for this option (`DontAlign`, `Left`, `Right`) actually **do** something. But if my code looks like this:

```c
#define A \
  int aaaa;     \
  int b;   \
  int dddddddddd;
```

and I want to keep it this way, there's currently no way to tell `clang-format` to leave this alone except for adding code comments around such a block. I propose to add a fourth and possibly shared value to the list of possible options: `LeaveAlone` (the name is debatable, of course). 

## Start from scratch and only enable individual style options (second part)

Once all style options in clang format support a `LeaveAlone` value, then we could add a new style, that is also called `LeaveAlone`. When applied to a piece of code, it should produce no change whatsoever. In fact the behaviour is exactly like with `DisableFormat`, with the exception that you can manually toggle on some style options. 

# Pros

* Adaption of `clang-format` for big projects (think Linux Kernel) becomes easier because they can gradually develop their own style without a mass formatting all at once. It is hard to come to a conclusion in a project that has many maintainers with different opinions on style. But together with a basic style `BasedOnStyle: LeaveAlone`, they could utilize `InheritParentConfig` in subdirectories to gradually toggle on features from `clang-format`. 

# Cons or difficulties

* `clang-format` shines in conjunction with other tools that modernize code for example. Those tools then know how to format the newly added code according to your style. When disabling certain style options altogether, the formatting might end up not *correct*. But as I mentioned before, I think the idea is help adoption of `clang-format` until a style is fully defined.

* The performance of `DisableFormat` and `LeaveAlone` will differ even though the end result is the same. `DisableFormat` skips formatting while `LeaveAlone` would have to check every style option for a `LeaveAlone` setting before acting or skipping. 

* There are many options in `clang-format` that go together, like `ColumnLimit` options for alignments. This could lead to results that are not so easy to explain.

* A lot of tests for `clang-format` would need to be touched.

* My first idea in a test was to use `llvm::Optional<unsigned>` for a style option that accepts and `unsigned`. The problem was that during the parsing in the YAML subsystem into this field, a special overloaded function for `llvm::Optional` was called which I hadn't intended. I might give `std::optional` a try just to see if the idea itself would work but it is only avaiable in C++17.

# Plan to get to desired state

Let's say the `clang-format` maintainers agree that it's worth having a `LeaveAlone` setting for each style option and later a style that uses it for all option, then I'd approach this topic iteratively like so:

1. Write a *small* patch that shows end to end how to disable formatting of a specific style option.
2. Document that this style option can now be set to `LeaveAlone`.
3. Land the patch upstream
4. Pick a new style option and repeat with 1.

## Remark on implementation

In `clang::format::FormatStyle` we have enumerations and scalars. For enumerations, it should be a matter of adding a new `LeaveAlone = LeaveAloneConst` enumeration value. This can be optimized by using something like `llvm::Optional` but in the end, it's the formatting logic where most of the changes will happen, so I'd like to not focus on this detail so much in the beginning. Let's just assume, everywhere a style option is checked for a value, it first needs to be checked as in `isset(Style.AlignEscapedNewlines)` and only if this is `true`, the formatting conditions will proceed with their evaluation.

I really look forward to your comments on this idea.

**Comment by HazardyKnusperkeks** [comment]
The general idea is sound to me. The optional part is not to my liking.

The implementation will get tricky, I'm curious about the patches.

**Comment by mkurdej** [comment]
I share @mydeveloperday's opinion.
I prefer using my spare limited time for something that has tangible effects to many clang-format users instead of wasting it for a couple of "non-believers" that will (unfortunately but probably) never start using the tool anyway.

**Comment by mydeveloperday** [comment]
We should also realize that adding such an option has an impact on the rest of us and the work we have to do making it much more complex, Somehow we now always have to consider about what `LeaveAlone` means in the context of every new feature/bug fix we add. But for what? for those not willing to make any sacrifice themselves to even just use it? I just don't feel we owe those people anything.

**Comment by trixirt** [comment]
I am a clang-format true believer AND want the linux kernel project to use clang-format for all of the reasons why clang-format is great.  However when I tried, I got some valid, negative feedback.
https://lore.kernel.org/lkml/20220127151945.1244439-1-trix@redhat.com/

For a tool to be adopted by any large project concensus of the stakeholders that the tool is useful is needed.
In it's current form of all reformatting options enabled, there will always be something new to argue about. 
Is there some middle ground way where an agreed set of options could be use and expanded over time per  project?

**Comment by mydeveloperday** [comment]
This example shows the whole problem, their existing style is inconsistent with itself, if needed I can pull out (if need be) multiple examples of where they  are not even consistent in the same file.

There are also options (like `AlwaysBreakAfterDefinitionReturnType`) that it seems have not been using.

Why a space after the macro 

`MODULE_LICENSE ("GPL");`

but not here

`MODULE_VERSION(MEGARAID_MODULE_VERSION);`

They are definitely not consistent on their use of braces on single line if statements. or spacing between the 'if' and '('

To me this is just an unformatted file, and actually I don't see the "valid" negative, If there is an opinion it was horrible before, its now at worse differently horrible, but more likely its consistent.

Your are free to submit patches, but to be honest, I just don't see the need pessimise the structure of clang-format for teams that make no effort in this area, it likely is NOT that important to them or they would do something about it.

But by all means lets capture the "negative feedback" and make them into small pieces of work that improve clang-format for anyone.  I'd be interested to understand exactly what features are considered the deal breaker.

**Comment by trixirt** [comment]
The default behavior of  clang-format is to do something for every setting, not do something for every setting in the .clang-format.  In the steady state, a project's .clang-format will not change fast enough so the default will always be used.
 
The explicit settings in a .clang-format can be reviewed and agreed by a project.
The implicit settings will not.
Nearly no one will build top of tree clang and less will use top of tree clang-format.
And in released clang-format the changing of the default behavior from release to release means formatting is different depending on which clang-format is being used.

I am looking for a way for the default output of clang-format can be consistent from release to release.
This I believe means only the explicit settings in a .clang-format be changed.
Could this be done with a mega setting like 'OnlyExplicitSettings' defaulting to 'no' ?

**Comment by HazardyKnusperkeks** [comment]
> The default behavior of clang-format is to do something for every setting, not do something for every setting in the .clang-format. In the steady state, a project's .clang-format will not change fast enough so the default will always be used.
> 
> The explicit settings in a .clang-format can be reviewed and agreed by a project. The implicit settings will not. Nearly no one will build top of tree clang and less will use top of tree clang-format. And in released clang-format the changing of the default behavior from release to release means formatting is different depending on which clang-format is being used.

Usually a new clang-format version with new options does not format code different. New feature are always added with a default, that keeps the non configurable version.
An exception to that are bugs and the handling of new language features, which are basically also bugs when not handled correctly.

**Comment by trixirt** [comment]
Sorry, I do understand what you mean.
From a review of clang-format 6 through 14, it seems that
New formatting settings/features in clang-format by default reformat the code.
If the project's .clang-format does not add an explicit setting, the default will be used.

If this is true (i'm asking) then the project must follow the development branch of clang-format to change their .clang-format as new features are added or be ok with the default.

**Comment by mydeveloperday** [comment]
We cannot start a conversation talking about about clang-format 6, that is 2018, its not possible for us to have a conversation that spans 4 years of changes, but @HazardyKnusperkeks  is correct, by and large there have been very few features where we change the defaults. (I can think of one to do with ternary operators which was really slightly before the currently contributors time. but it wasn't that terrible. it basically formatter what wasn't formatted before. (well at least not well)

I want to kill the myth that we change defaults, everyone on this thread knows that I for one push back on any change that changes the unit tests for exactly this reason. 

Ok so does code have to be reformatted version to version, (yes), why because we fix bugs, but also where code wasn't previously covered by any form of default and was not part of any existing unit test. But ultimately if you see code changes version to version, its highly likely that this comes from us now covering cases that weren't covered before (sometimes for new C++ functionality like concepts, coroutines etc..), and were we can we add a "Leave" option for those new styles to try and leave the code alone. (but that isn't to cover bug fixes, its to not apply new formatting)

For example a  recent fix that shows how bug fixes change things was that BreakAfterReturnType it didn't work when the function had no parameters names (because it could identify it was a function)

i.e.
```
void foo(int){
}
```
formatted different from

```
void 
foo(int p){
}
```

The fix for this was to improve the method for identifying if something was a function declaration, its highly likely that also that change will have an impact on other places where we need to try and identify where its a function declaration, this is what we mean by changes not being orthogonal, we wouldn't be able to make a fix that only impacted the return type and only the return type and not the other code (and I wouldn't want us to either).

As I said this is a bug fix, we are not going to support the prior state of the bug, if you want that use an earlier version of clang-format until you are prepared to accept the fix!

I'm always amazed at the people who complain about this the most as it tends to be the people who either don't upgrade or aren't using clang-format and use it as some sort of an excuse not to upgrade or adopt. 

But the reality is I do this for my 4.5 million line code base, every release, and major release to major release I have to change ~ about 10 files and almost all of them show clang-format was misbehaving.

This is why I'm anti such a feature as this, I feel people will expect us to support buggy behaviour so they can go version to version and not change  their code, which I think defeats the whole purpose of clang-format.

I don't believe in all honesty that I can't currently support that form of functionality and hence your desire to "LeaveAlone" I think is fundamentally flawed as changes would leak in whether you liked it or not.

But again I ask, what is the negative feedback about what clang-format is doeing? what are the things that clang-format does that are wrong or doesn't do that prevents these people from upgrading. Because if its just version to version change then I don't think thats going away.

**Comment by ojeda** [comment]
> But again I ask, what is the negative feedback about what clang-format is doing? what are the things that clang-format does that are wrong or doesn't do that prevents these people from adopting. Because if its just version to version change then I don't think that is going away.

Concerning the kernel: when I introduced `.clang-format`, I picked a very old version as a start, but I will most likely be moving the file to track the minimum supported LLVM version in the kernel soon, which is currently LLVM 11.0.0.

One thing I am aware of that may prevent some projects from easily upgrading is that `clang-format`s errors on unknown options, thus one cannot take advantage of newer options without disrupting others. From a quick check, `clang-format` 13 still behaves like that.

**Comment by trixirt** [comment]
For any reformatter setting the behavior is to do the explicit setting or the implicit setting in default.  There is no 'do nothing' setting so generally each release reformats more that the last one did.

The implicit setting is a lack of choice and the problem.

**Comment by mydeveloperday** [comment]
> For any reformatter setting the behavior is to do the explicit setting or the implicit setting in default. There is no 'do nothing' setting so generally each release reformats more that the last one did.
> 
> The implicit setting is a lack of choice and the problem.

Give me an example where this happened, let’s talk about we’re it occurred and what could have been done, I’d like to work with an example otherwise I feel we are just surmising what happened

**Comment by mydeveloperday** [comment]
The mechanism that we use to say I don't understand this option is the same mechanism that we use to say you misspelled something! I think if we relax that rule we'll end up with more bugs that say clang format didn't format my braces only to find they spelt the option incorrectly

It would have to be noisy at best and warn every time, plus it would only be useful in likely 3 or 4 releases time. But it's possible feel free to submit a patch for this for discussion

**Comment by ojeda** [comment]
Definitely -- it should probably be optional, since it is really only useful for projects that use `clang-format` only to reformat pieces of code or only by code that does not get touched by many developers (otherwise you could get different formatting outputs depending on who runs the tool etc.). I also agree it would be only be useful in a few releases time.

For the kernel, it should be fine (if we upgrade the minimum LLVM from time to time), but I thought it was worth mentioning, since it can indeed prevent other projects from using newer options (unless they preprocess the file or similar).

**Comment by trixirt** [comment]
A hypothetical
I only want to have no white space in an if-condition
if ( flag )
->
if (flag)
And no other changes made.
How would I do that ?

**Comment by mydeveloperday** [comment]
SpaceBeforeParensOptions: Custom
   AfterControlStatements: true
SpacesInSquareBrackets: true

> And no other changes made.

what do you mean by no other changes? this isn't a smorgasbord you can't pick and choose, it needs to be part of your "format" for the whole file.

**Comment by mydeveloperday** [comment]
> Definitely -- it should probably be optional (if it got added at all), since it is really only useful for projects that use `clang-format` only to reformat pieces of code or only by code that does not get touched by many developers (otherwise you could get different formatting outputs depending on who runs the tool etc.). I also agree it would be only be useful in a few releases time.
> 
> For the kernel, we should be fine without it as long as we upgrade the minimum LLVM from time to time, but I thought it was worth mentioning, since it can indeed prevent other projects from using newer options (unless they preprocess the file or similar).

For new features, such a QualifierAlignment , InsertBraces, etc.. I run a private .clang-format file and the new binary, it means I'm correcting the code ahead of these becoming standard in my project.

**Comment by ojeda** [comment]
The issue I was talking about is that in some projects different people will run different `clang-format` versions, thus one cannot have newer options unless everybody agrees on a minimum version (or preprocesses the file somehow).

**Comment by kwk** [comment]
> The issue I was talking about is that in some projects different people will run different `clang-format` versions, thus one cannot have newer options unless everybody agrees on a minimum version (or preprocesses the file somehow).

@mydeveloperday by default clang-format errors on unknown style options in a `.clang-format` file? But what if we add a switch to the CLI binary that turns these errors into warnings? ... But the more I think about this it seems like a bad idea. It would mean that people can format a file with two different versions of `clang-format` and the result would be different each time, depending on which version you've picked. @ojeda that isn't desireable, is it?

**Comment by ojeda** [comment]
>  the result would be different each time, depending on which version you've picked. @ojeda that isn't desireable, is it?

I would say it depends on the project, as I was trying to convey above. If you have a project that wants to e.g. enforce automatic formatting, then it can definitely be a source of mistakes (though `.clang-format` could have an option to be explicit about the version targeted/allowed etc.).

On the other hand, if you have a project where clang-format is so far used as a tool to perform local reformatting only and/or only some folders follow clang-format and/or not many people maintain a given file (or they agree on a version), then ignoring unknown options may be better, because then users get the best formatting possible. This would work best if newer versions introduce flags with a default that maps the previous versions.

**Comment by kwk** [comment]
> > The issue I was talking about is that in some projects different people will run different `clang-format` versions, thus one cannot have newer options unless everybody agrees on a minimum version (or preprocesses the file somehow).
> 
> @mydeveloperday by default clang-format errors on unknown style options in a `.clang-format` file? But what if we add a switch to the CLI binary that turns these errors into warnings? ... But the more I think about this it seems like a bad idea. It would mean that people can format a file with two different versions of `clang-format` and the result would be different each time, depending on which version you've picked. @ojeda that isn't desireable, is it?

After giving this some thought it might be an idea to introduce a forward compatibility feature upon explicit request not by having a switch on the CLI binary `clang-format` but in the `.clang-format` file itself. Let's say the style option `Foo: Bar` is introduced in LLVM 18. Maybe not all your developers are using that version of LLVM version yet. Some may be on LLVM 16. But it's the setting that you want them to use in the future and you all agree on it. Wouldn't it be nice to allow for older version to ignore this unknown setting? I'm not saying to allow for all unknown settings to be ignored.

To clarify, with this `.clang-format`, the corresponding binary will error in LLVM 16:

```yaml
- Foo: Bar
```

But if we (just an idea) prefix the key or value a `!`, this will be ignored.

```yaml
- "!Foo": Bar
```

This `.clang-format` file would never be accepted by any `clang-format` binary on the other hand:

```yaml
- "!Foo": Bar
- AStyleOptionToBeDevelopedIn100YearsFromNow: SomeValue
```

See the difference?

This is still valid YAML btw.

If you get unexpected formatting results because of different LLVM versions you can go in the `.clang-format` file and find out that the setting causing trouble (`Foo: Bar`) maybe not available in your version LLVM. But it is explicitly marked as ignore-if-unknown and then you just have to live with it and accept that your version of LLVM is old ;)

On purpose I picked versions like 16 and 18 because such a change would require to sit before it's of any use.

I hope this makes any sense.

**Comment by kwk** [comment]
Apparently there already is a flag that one can use for ignoring unknown options.

```
$ clang-format --help

...

  --Wno-error=<value>            - If set don't error out on the specified warning type.
    =unknown                     -   If set, unknown format options are only warned about.
                                     This can be used to enable formatting, even if the
                                     configuration contains unknown (newer) options.
                                     Use with caution, as this might lead to dramatically
                                     differing format depending on an option being
                                     supported or not.
```

**Comment by mydeveloperday** [comment]
clang-format has a handful of regular contributors. (maybe ~7), we likely have millions of users, all of the contributors do this in our spare time.

Whilst these ideas above seem like they might help us get more users who are reluctant, I don't personally feel it's worth it, we have plenty of things to work on that will help our existing users, and would in time persuade those reluctant users to join as we closed their requirement gaps.

The problem with bringing on more cynical/ less flexible users is they are probably even more likely to complain also about the other existing issues and use that as justification for why they were reticent in the first place.

Personally, I want to think about moving things forward for the good of all, which means adding bug fixes and features for the things that are most beneficial to those people who are already using clang-format. It's more important to me that they remain users.

If you want to make a difference please think about becoming a regular contributor. You can influence much better from the inside. Your view of the above request would likely change with experience, and I for one don't think many of the current regular contributors are going to champion your idea so the onus is on you to bring it, implement it and support it long term.

We have 100's of open issues that need looking at and since moving to GitHub the speed they come in has increased to the point that it's greater than the speed they get resolved. This is only going one way.

GitHub issues reduced the barrier for entry for people to log issues but did almost nothing to reduce the barrier to get new contributors (although one or two have joined and our regular contributors I believe are more efficient)

Please review this list below and consider contributing on a regular basis, you clearly are passionate about clang-format and its use, and so I am sure your input would be valuable, but perhaps consider doing some small things first before you decide you are qualified to reinvent the whole ethos of clang-format for the reluctant few!

https://github.com/llvm/llvm-project/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+label%3A%22clang-format%22

**Comment by kwk** [comment]
> Please review this list below and consider contributing on a regular basis, you clearly are passionate about clang-format and its use, and so I am sure your input would be valuable, but perhaps consider doing some small things first before you decide you are qualified to reinvent the whole ethos of clang-format for the reluctant few!
> 
> https://github.com/llvm/llvm-project/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+label%3A%22clang-format%22

@mydeveloperday I hear ya! I've tackled this issue from the list https://github.com/llvm/llvm-project/issues/38995 with this patch https://reviews.llvm.org/D121370 and would be happy to get feedback on it.

I'm closing this issue now with no resolution but with the hope that we can improve clang-format for the existing user-base and one day, hopefully, it fits in the workflow of others. By all means, this was just an idea and the amount of anger it has produced was never my intention. I just followed along what you suggested to me and opened this issue as a base for discussion. I hope you see that I like clang-format.

**Comment by mkurdej** [comment]
> By all means, this was just an idea and the amount of anger it has produced was never my intention.

@kwk, that's certainly not anger that it produced, just a vivid reaction (there's a difference!) :).
I think that everyone would love to have clang-format with your proposed features, but for the moment it's too far from the current state of affairs to be realistic.

Anyway, thanks for contributing to clang-format!

**Comment by kwk** [comment]
> > By all means, this was just an idea and the amount of anger it has produced was never my intention.
> 
> @kwk, that's certainly not anger that it produced, just a vivid reaction (there's a difference!) :).

What a nice description. There were discussions on both sides and (Kernel and clang-format) and sitting in between wasn't fun at all. I ask for more understanding not feeling offended. That's what I can say to both sides. 

> I think that everyone would love to have clang-format with your proposed features,

Hey, good to know. My intention was to work towards it. I simply like making a feature request with a proposal to have something to talk about. But instead it yielded comments about *the non-believers*. Being sarcastic wasn't helpful here and completely contradictory to the initial request to establish a good working relationship. But I'm being realistic and moved on by submitting my other patch to clang-format as my symbol of commitment.

> but for the moment it's too far from the current state of affairs to be realistic.
> 
> Anyway, thanks for contributing to clang-format!

You're welcome.

**Comment by mydeveloperday** [comment]
> amount of anger

Definitely not anger, but I can understand some might not see it that way. (I apologise)

> about the non-believers. Being sarcastic wasn't helpful here

My apologies if people took offence, patches are always welcome and thank you for contributing.
