### ISSUE TITLE
LLVM_ENABLE_RUNTIMES and non-canonical triples don't match

### ISSUE THREAD

**Issue by rorth** [llvm/llvm-project#54196]
Between LLVM 14.0.0 rc1 and rc2, `test-release.sh` changed to configure with `-DLLVM_ENABLE_RUNTIMES=`.  This broke quite a number of tests on Solaris/amd64, which I usually build with `-triple amd64-pc-solaris2.11 -configure-flags " -DLLVM_HOST_TRIPLE=amd64-pc-solaris2.11"` to match the common name of the 64-bit x86 architecture on Solaris.

As it turns out, the introduction of `-DLLVM_ENABLE_RUNTIMES=` changes the directory
layout for the runtime libs.  Before, we had
```
./lib/clang/14.0.0/lib/sunos/libclang_rt.asan-x86_64.so
./lib/clang/14.0.0/lib/sunos/libclang_rt.asan-i386.so
```
while now there's
```
./lib/clang/14.0.0/lib/x86_64-pc-solaris2.11/libclang_rt.asan.so
./lib/clang/14.0.0/lib/i386-pc-solaris2.11/libclang_rt.asan.so
```
instead.

It seems `clang` only searches for the form of the triple passed during `cmake`, while the directories always use the canonical form of the triple, as can be seen like this:
```
$ ./bin/clang -print-runtime-dir
lib/clang/14.0.0/lib/sunos
$ ./bin/clang -print-runtime-dir -target x86_64-pc-solaris2.11
lib/clang/14.0.0/lib/x86_64-pc-solaris2.11
```
Obviously the two (configured triple and subdir used for runtime libs) need to be consistent.  Once could either use the configured triple for the subdir names or (more reliable because there can always be different non-canonical forms) always normalize the give triple when searching for libs.

Note that the issue is in no way Solaris-specific. I observe exactly the same issue on Linux/x86_64 with `target amd64-pc-linux-gnu` when configured for `x86_64-pc-linux-gnu`.

**Comment by DimitryAndric** [comment]
Yeah I've seen this too on FreeBSD. With e.g. 13.0.0, it looked like:

```
lib/clang/13.0.0/lib/freebsd/libclang_rt.asan-i386.so
lib/clang/13.0.0/lib/freebsd/libclang_rt.asan-x86_64.so
```

and now it is:

```
lib/clang/14.0.0/lib/i386-unknown-freebsd14.0/libclang_rt.asan.so
lib/clang/14.0.0/lib/x86_64-unknown-freebsd14.0/libclang_rt.asan.so
```

It does seem that `-print-runtime-dir` shows the right path:

```
% /share/dim/llvm/llvmorg-14.0.0-rc1-74-g4dc3cb8e3255-freebsd14-amd64-ninja-clang-rel-1/bin/clang -print-runtime-dir
/share/dim/llvm/llvmorg-14.0.0-rc1-74-g4dc3cb8e3255-freebsd14-amd64-ninja-clang-rel-1/lib/clang/14.0.0/lib/x86_64-unknown-freebsd14.0

% /share/dim/llvm/llvmorg-14.0.0-rc1-74-g4dc3cb8e3255-freebsd14-amd64-ninja-clang-rel-1/bin/clang -print-runtime-dir -m32
/share/dim/llvm/llvmorg-14.0.0-rc1-74-g4dc3cb8e3255-freebsd14-amd64-ninja-clang-rel-1/lib/clang/14.0.0/lib/i386-unknown-freebsd14.0
```

**Comment by rorth** [comment]
I think I understand now what's going on:
- With `LLVM_ENABLE_RUNTIMES`, `LLVM_ENABLE_PER_TARGET_RUNTIME_DIR` is set to `ON`.  `compiler-rt/cmake/Modules/CompilerRTUtils.cmake` (`get_compiler_rt_output_dir`) now appends `${target}` to the output directory.  `${target}` is determined using `get_compiler_rt_target` which replaces the architecture component of a triple by a canonical form (`i386`/`x86_64` in the x86 case).
-  `clang` doesn't match this behaviour, however: in `clang/lib/Driver/ToolChain.cpp` (`ToolChain::getRuntimePaths`) it just takes the triple as is instead of canonicalizing the architecture part.

I'm currently testing a patch which makes `clang` match what `compiler-rt` does.

**Comment by sztomi** [comment]
I've independently ran into this and opened a thread here: https://discourse.llvm.org/t/triple-quirks-for-finding-runtimes-how-to-improve-this/64078

There is also an adjacent use-case of representing the API-levels in android triples: https://discourse.llvm.org/t/handling-version-numbers-in-per-target-runtime-directories/62717

Having debugged this for a little while, I have a different analysis to the above. In short, I think the issue is that `clang -print-runtime-dir` and the CMake code don't agree on when to canonicalize the triple. `clang` always does, but CMake just appends the literal triple as it was passed to the build. That causes a hard to debug issue when clang tries to find the runtime and the _canonical_ triple differs from the _literal_ triple that was used during the build. The reason is that when the runtime is not found at the computed (new layout & based on the canonical triple) path, it will fall back to the old layout. It's also not there, since the build uses the new layout, but the error message will ultimately display the old layout path. Anyone without the additional context of the runtime directory layout change will be very confused. The only viable solution is symlinking the literal triples to the canonicalized forms in all places and it's hard to figure that out.

So I think the solution would be:

  * have CMake also use the canonicalized path. But there needs to be a way to tell the frontend to not use the fallback in this case when `clang -print-runtime-dir` is called, just print the desired runtime path, regardless of it existing
  * have clang _not_ use the canonicalized path for searching the runtime, or at least try the literal form of it before canonicalizing. I don't really know the full implications of this, but I also think there are some upsides. Canonical triples are sometimes a bit surprising, e.g. `armv7a-unknown-linux-androideabi` becomes `armv7a-unknown-linux-android` which doesn't sound like a viable triple (armv7 is always eabi on Android), but I might be wrong about that.

Additionally, it would be useful if there was some way to get some insight into the fallback mechanism, similarly to how library search paths can be printed (i.e. "we tried these paths, they didn't work; finally used this fallback"). But this is only a QoL improvement.

**Comment by rorth** [comment]
Right, my patch was primarily a hack, and even so it's incomplete without [D133407](https://reviews.llvm.org/D133407).  That said, it would have been better to just reopen this Issue (I hadn't even been aware that it's been closed) rather than spreading the discussion over several different Issues.  That just makes live harder...

**Comment by sztomi** [comment]
Sorry, I thought it was actually me intruding with the more general issue on a specific one, so I thought opening a new one is better. I don't mind either way, but closing that and moving discussion here might just add to the confusion.
