### ISSUE TITLE
Clang crash  starting with 6a605b97a2006

### ISSUE THREAD

**Issue by m-gupta** [llvm/llvm-project#54190]
@jmorse starting with 6a605b97a2006, we have noticed a clang crash when building Linux kernel in Chrome OS when asserts are enabled.
It still repros on ToT.

reduced test case :

[repro.zip](https://github.com/llvm/llvm-project/files/8182516/repro.zip)

Stack trace:
```
3.	Running pass 'Function Pass Manager' on module 'tlb-9e7172.c'.
4.	Running pass 'X86 DAG->DAG Instruction Selection' on function '@switch_mm_irqs_off'
 #0 0x00000000079e332a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /usr/local/disk2/llvm_monorepo/llvm-project/llvm/lib/Support/Unix/Signals.inc:565:11
 #1 0x00000000079e34db PrintStackTraceSignalHandler(void*) /usr/local/disk2/llvm_monorepo/llvm-project/llvm/lib/Support/Unix/Signals.inc:632:1
 #2 0x00000000079e1b9a llvm::sys::RunSignalHandlers() /usr/local/disk2/llvm_monorepo/llvm-project/llvm/lib/Support/Signals.cpp:97:5
 #3 0x00000000079e3bf5 SignalHandler(int) /usr/local/disk2/llvm_monorepo/llvm-project/llvm/lib/Support/Unix/Signals.inc:407:1
 #4 0x00007fbf83d87200 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x13200)
 #5 0x00007fbf8381c891 raise ./signal/../sysdeps/unix/sysv/linux/raise.c:50:1
 #6 0x00007fbf83806536 abort ./stdlib/abort.c:81:7
 #7 0x00007fbf8380641f get_sysdep_segment_value ./intl/loadmsgcat.c:509:8
 #8 0x00007fbf8380641f _nl_load_domain ./intl/loadmsgcat.c:970:34
 #9 0x00007fbf83815212 (/lib/x86_64-linux-gnu/libc.so.6+0x35212)
#10 0x00000000066286ee llvm::MachineFunction::salvageCopySSA(llvm::MachineInstr&) /usr/local/disk2/llvm_monorepo/llvm-project/llvm/lib/CodeGen/MachineFunction.cpp:0:5
#11 0x0000000006628d2d llvm::MachineFunction::finalizeDebugInstrRefs() /usr/local/disk2/llvm_monorepo/llvm-project/llvm/lib/CodeGen/MachineFunction.cpp:1209:23
#12 0x00000000096ced67 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) /usr/local/disk2/llvm_monorepo/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:658:7
```

**Comment by jmorse** [comment]
The firing assertion is at [0], and it's firing for completely legitimate reasons. That portion of code was designed to detect scenarios where values (for debug-info purposes) are being read from physregs. First I thought only arguments could be read directly from physregs (vs virtregs); then there were reads from constant physregs, landing-pad blocks, and the llvm.frameaddress intrinsic. Now it turns out you can read an arbitrary physreg at an arbitrary point in llvm-ir:

      %1 = tail call i64 @llvm.read_register.i64(metadata !7), !dbg !27
      call void @llvm.dbg.value(metadata i64 %1, metadata !20, metadata !DIExpression()), !dbg !26

Which is the representation of `register long a asm("rsp");` in the reproducer.

The solution is going to be just deleting those assertions: they were put there because of the (reasonable IMO) assumption that llvm-ir couldn't just read from physregs, and that it would be a reportable bug when that happened. As time has gone on it's turn out that simply isn't true.


[0] https://github.com/llvm/llvm-project/blob/6a605b97a2006bd391f129a606483656b7c6fb28/llvm/lib/CodeGen/MachineFunction.cpp#L1161

**Comment by jmorse** [comment]
(I suppose by "completely legitimate reasons" I mean "it's detecting exactly what I wanted it to detect", just it turns out I had an incomplete understanding).

**Comment by jmorse** [comment]
https://reviews.llvm.org/D121001
