### ISSUE TITLE
Please backport 7403c02f06d4c405215aa97452f1af18dfc02dc0 ([Hexagon] Fix crash with shuffle_vector of v128f16) to 14.x

### ISSUE THREAD

**Issue by androm3da** [llvm/llvm-project#54253]

**Comment by tstellar** [comment]
@kparzysz-quic What do you think about backporting this? https://github.com/llvm/llvm-project/commit/7403c02f06d4c405215aa97452f1af18dfc02dc0

**Comment by androm3da** [comment]
@tstellar is there a way to repeat the failing test on https://github.com/llvmbot/llvm-project/pull/123? It does not look like it's related to this commit.

**Comment by androm3da** [comment]
Ok, that makes sense.  So the failure cause is known and it would not help to repeat the test because it would/could fail again due to the known bug.  And IIUC this host compiler failure is not exposed by this cherry-pick, it's present in the baseline?

But should the PR be held until there's resolution of the Microsoft bug?  Or are we waiting for something else?

@kparzysz-quic nominated this commit for a cherry-pick to 14.x when I chatted with him -- he may have missed that notification earlier.

**Comment by tstellar** [comment]
@androm3da Right that test currently always fails.  I haven't had time to find a way to make it pass without disabling the whole Windows test run, and I've been waiting to land this re-org of the tests first: https://reviews.llvm.org/D120872  So for now I've just been manually inspecting the test logs.

This bug was submitted quite late in the process, but due to other delays I can fit it in given that @kparzysz-quic has approved it.

**Comment by tstellar** [comment]
Merged: 69ba522c58d0cf43097a08087b1b31d6edb46706
