### ISSUE TITLE
[ODS] Eliminate the default value from `arguments` and `results` in the `Op<>` tblgen class?

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#54255]
In an offline discussion, we were talking about whether or not "arguments" and "results" should be specified, even if an operation doesn't have them.  For example, should we have:

```
def FuncOp : FooOp<"func", ...> {
  let arguments = (ins);
  let results = (outs);
  let regions = (region SizedRegion<1>:$body);
}
def AddI32Op : FooOp<"add.i32"> {
  let arguments = (ins I32:$lhs, I32:$rhs);
  let results = (outs I32:$result);
}
def PrintI32Op : FooOp<"print.i32"> {
  let arguments = (ins I32:$value);
  let results = (outs);
}
```

Or go with the more minimal:

```
def FuncOp : FooOp<"func", ...> {
  let regions = (region SizedRegion<1>:$body);
}
def AddI32Op : FooOp<"add.i32"> {
  let arguments = (ins I32:$lhs, I32:$rhs);
  let results = (outs I32:$result);
}
def PrintI32Op : FooOp<"print.i32"> {
  let arguments = (ins I32:$value);
}
```

The MLIR codebase is a mix of the two approaches.

Speaking for myself, I pretty strongly prefer the first approach - where arguments/results are always specified, but where more exotic things like regions are present only when needed.  Although we (the LLVM/MLIR community) don't really have a strong set of principles that guide when a field is defaulted or not, there is a general sense of "don't default primary information about an operation": you want to force some people to think about certain properties of a tblgen declaration.

In the case of arguments/results, almost every op has them, and there are sometimes a *lot* of other stuff in the body of an op definition (e.g. FuncOp has lots of inline C++ stuff).  Having both of these present and at the top of the operation decalration (even when empty) makes it easier for me to understand what are the inputs, attributes, and results of the operation.

Further, it is very conventional for dialects to define their own `FooOp` subclass of `Op` that specifies a dialect.  If some dialect wanted to default these, they could do so in their local world.

What do others think?

-Chris

**Comment by River707** [comment]
I somewhat strongly prefer the latter. The absence of a `regions` or `successors` list has never made me question if the operation has them or not, same with `arguments` and `results`. To me the empty definitions feel superfluous.

You also can't really base what an op has based solely on its local op definition. Various dialects often define utility base classes for certain classes of operations, that may define arguments/results/etc. In all of those cases, you have to trace through the TableGen class hierarchy to find what the operation actually has.

As an aside, for defaults in a specific dialect, couldn't you do the same in the opposite case? i.e. could you not define:

```
let arguments = ?;
let results = ?;
```

in your dialect op base class to force an op to specify them?



For my actual thoughts on the change, it doesn't really matter much to me what the default is on the Op base class. Whether it's `(ins)`(empty) or `?`(unknown), it doesn't matter to me given that a dialect can do whatever they want for their local world. The main part of this that I would potentially take issue with is suggesting that we adopt this (always specifying even when empty) as the general recommended style for defining operations.

**Comment by lattner** [comment]
Right, what I'm trying to argue here is that there is a "difference in kind" between "arguments" and "regions" in terms of primality of "what makes an op".  Most ops don't have regions or successors, but most ops have arguments and result.

> For my actual thoughts on the change, it doesn't really matter much to me what the default is on the Op base class. Whether it's (ins)(empty) or ?(unknown), it doesn't matter to me given that a dialect can do whatever they want for their local world. The main part of this that I would potentially take issue with is suggesting that we adopt this (always specifying even when empty) as the general recommended style for defining operations.

Right, I am also more interested in "what is the right way to define ops - is it included or not", not so much how the implementation of that works.

To dig in a bit more, what principle do you see in terms of "what is required to be specified in a tblgen def?"   Given that almost everything can be defaulted, why don't we always do that?  Is minimalism the goal?

I'm also curious to know why you think there are so many ops in MLIR that redundantly specify these already.  Part of it is that we don't have a policy, but I think that there is more to it in terms of consistency between op definitions.

Has anyone else in the community noticed this?

-Chris

**Comment by River707** [comment]
> To dig in a bit more, what principle do you see in terms of "what is required to be specified in a tblgen def?" Given that almost everything can be defaulted, why don't we always do that? Is minimalism the goal?

I don't think minimalism is inherently the goal. For me, one core principle is not redundantly specifying the "default". The default in the cases of the fields being described has (since the beginning) implied "empty", so redefining a default assumption feels superfluous to me. Another (which applies to MLIR in general) is not paying the cost of something you don't use: "Why do I need to define something I don't have/use?". 

(As an aside, if we were to make some fields always required, I'd really likely start with the `summary`/`description` fields)

> I'm also curious to know why you think there are so many ops in MLIR that redundantly specify these already.

I didn't mean to imply there are a bunch of ops that redundantly specify these already (there aren't upstream AFAIK), the point I was trying to make is that you can't infer what an operation has just by looking at the op definition. For example, the Arithmetic dialect (along with various others) heavily uses base op classes that specify the arguments/results . If you look at the definition of a specific concrete operation, you can't see what the arguments/results are, you need to follow the class hierarchy. (e.g. AddIOp: https://github.com/llvm/llvm-project/blob/6564a70415df1eb1504bb271d0d958b456e22c64/mlir/include/mlir/Dialect/Arithmetic/IR/ArithmeticOps.td#L178)

> we don't have a policy, but I think that there is more to it in terms of consistency between op definitions.
This is a fairly important meta point, the docs for ODS are super crusty and old. They very desperately need an uplift, and likely an essential rewrite.

**Comment by lattner** [comment]
Ok, I'm not hearing any resonance here, I'm dropping it :-)
