### ISSUE TITLE
[X86] miscompile of overflow intrinsic + select in optnone functions

### ISSUE THREAD

**Issue by tetzank** [llvm/llvm-project#54369]
In functions marked with optnone, selecting a specific error value when an overflow happens leads to wrong assembler code.
One value in `select` needs to be 0, which leads to `xor reg, reg` clearing the overflow flag before the `cmov`.

The problem got introduced with LLVM 12, it seems.

https://godbolt.org/z/zG5rqM6zn
```
; optnone is important here
define i64 @adder(i64 %lhs, i64 %rhs) noinline optnone {
	%addresult = call {i64, i1} @llvm.sadd.with.overflow.i64(i64 %lhs, i64 %rhs)
	%errorbit = extractvalue {i64, i1} %addresult, 1
	;%errorval = select i1 %errorbit, i64 148, i64 42 ; fine
	%errorval = select i1 %errorbit, i64 148, i64 0 ; wrong, 0 => xor
	ret i64 %errorval
}

declare {i64, i1} @llvm.sadd.with.overflow.i64(i64 %a, i64 %b)

; wrong code since llvm 12
; adder:
;   add     rdi, rsi  # sets OF
;   seto    al        # reads OF
;   xor     eax, eax  # clears OF
;   mov     ecx, 148
;   cmovo   rax, rcx  # reads OF
;   ret
;
; working code in llvm 11
; adder:
;   xor     eax, eax
;   add     rdi, rsi  # sets OF
;   seto    cl        # reads OF
;   mov     ecx, 148
;   cmovo   rax, rcx  # reads OF
;   ret

```

**Comment by topperc** [comment]
This is a fast isel issue. It will also fail with -O0 instead of optnone. The fundamental issue is that the cmov and the alu op are being emitted separately by fast isel. The selection code for the cmov checks if the condition is an overflow op, but doesn't emit the code for the overflow. It then goes on and emits the select operands which generates the xor. Then the overflow op is visited and emits its code.

The easiest fix is to disable this attempted optimization and emit a test of the seto result register. That seto is currently dead.

Other fixes would be to emit the overflow op code when we emit the select. (This is probably hard to do since it has another result.) Or detect the operands of the select and don't do the optimization if the select will emit an xor.

**Comment by tetzank** [comment]
I think, zero initialization with `xor` should be seen as an optimization and done very carefully as it modifies the flags. If in doubt, use `mov reg, 0`. Sure, the opcode is larger, but it's safe.

**Comment by nikic** [comment]
I previously fixed a similar problem with phis in https://github.com/llvm/llvm-project/commit/7669455df49e6fc8ae7d9f4bd4ee95bb20e7eb6e.

**Comment by nikic** [comment]
Candidate patch: https://reviews.llvm.org/D122825
