### ISSUE TITLE
clang-tidy: cppcoreguidelines-explicit-virtual-functions: wrong space in fix

### ISSUE THREAD

**Issue by FStefanni** [llvm/llvm-project#54376]
Hi,

I am using clang-tidy 13.0.1.
The rule `cppcoreguidelines-explicit-virtual-functions` proposes to fix code as the followinf:
```c++
class ...
virtual int foo() override;
```
as:
```c++
class ...
 int foo() override;
```
but in performing the fix, it leaves an extra initial space as in the reported example, i.e., to be clearer, it removes `virtual`, whilst it should remove `virtual ` (regex: `virtual *`).

Regards.

**Comment by njames93** [comment]
Clang-tidy checks don't handle whitespace changes, to get the correct intended behaviour you should have a [https://clang.llvm.org/docs/ClangFormatStyleOptions.html](clang format configuration) in order to reformat fixes that are generated

**Comment by FStefanni** [comment]
Hi,

I really believe it should handle the simplest obvious cases, like the one here reported, so please consider the proposed improvement. 
As a side note, the fix for `misc-unused-parameters` does the opposite: adds an extra leading space, which is even more weird.

Regards.

**Comment by AaronBallman** [comment]
> I really believe it should handle the simplest obvious cases, like the one here reported, so please consider the proposed improvement. As a side note, the fix for `misc-unused-parameters` does the opposite: adds an extra leading space, which is even more weird.

We've considered the proposed improvement on a few occasions and always come to the same conclusion: clang-tidy fixes should not attempt to automatically fix formatting issues at the same time as issuing fixes. So I agree with @njames93 here. One problem which I remember: it doesn't scale well. The performance from running the formatting tool repeatedly after each check (where we know the range of lines to format) instead of only once at the end of running all the checks (where we wouldn't have that information unless we wrote it out to a side file, which comes with its own issues) was a very real issue.

Are you aware that clang-tidy can run clang-format automagically though? Specify `--format-style=<option>` and clang-format will be run for you (see https://clang.llvm.org/extra/clang-tidy/ for more details).
