### ISSUE TITLE
Missing support for _BitInt(N) in __builtin_dump_struct

### ISSUE THREAD

**Issue by davidbolvansky** [llvm/llvm-project#54504]
```
#include <stdio.h>

typedef struct bitintstruct {
	_BitInt(8) w;
} bts;

int main() {
	bts st = { 0 };
	__builtin_dump_struct(&st, &printf);
}

```

> bts {
> _BitInt(8) w : (nil)
> }

**Comment by davidbolvansky** [comment]
cc @AaronBallman

**Comment by AaronBallman** [comment]
FWIW, we don't support *most* types in __builtin_dump_struct (basically, we only support some integer types (not all), some float types (not all), void pointer, and string.

In order to fix this, we'd have to change the `dumpRecord()` implementation in `CGBuiltin.cpp` to note that it's a bit-precise integer type and cast it to either `intmax_t` or `uintmax_t` and use the `%jd` or `%ju` format specifier. This will only work for bit widths smaller than [u]intmax_t; the fallback for wider types would probably be to print a string "too large to print" or something.

**Comment by shafik** [comment]
Looks like this works since clang-15: https://godbolt.org/z/j51sP1KnT
