### ISSUE TITLE
Packed struct doesn't support i24 fields

### ISSUE THREAD

**Issue by igor84** [llvm/llvm-project#54514]
Under StructLayout constructor in DataLayout.cpp line 70 field size is added to total struct size like this:
```
StructSize += DL.getTypeAllocSize(Ty).getFixedValue();
```
Shouldn't this be replaced with:
```
if (ST->isPacked()) {
    StructSize += DL.getTypeStoreSize(Ty).getFixedValue();
} else {
    StructSize += DL.getTypeAllocSize(Ty).getFixedValue();
}
```

**Comment by efriedma-quic** [comment]
This is working as intended. A "packed" is packed in the C/C++ sense of packed.  Padding between members is removed, but not padding that's part of a member.  And even if we did want to change it, it would be very hard to change at this point due to bitcode compatibility.

clang uses `[3 x i8]` to represent packed bitfields, like `struct __attribute((packed)) S { int a:24; };`.
