### ISSUE TITLE
[clang] Forbidden implicit conversion of constraint expression to bool

### ISSUE THREAD

**Issue by pjgeorg** [llvm/llvm-project#54524]
clang (any version) currently accepts any expression that can be implicitly converted to bool in require-clause parenthesized expressions. I first thought this is correct and gcc is wrong in not accepting any constraint expression which does not have type bool.

Searching the C++ standard [[temp.constr.atomic]](https://eel.is/c++draft/temp.constr.atomic). The example given in [13.5.2.3.3](https://eel.is/c++draft/temp.constr#atomic-3) does indeed compile using clang although the standard clearly states that it is an error. gcc correctly reports the error "constraint expression does not have type 'bool'".

Link to example from C++ Standard in Compiler Explorer: https://godbolt.org/z/5zh6dcT8v

**Comment by erichkeane** [comment]
This is happening because SemaConcept.cpp ~336 (in calculateConstraintSatisfaction) does a contextual conversion to bool.  

The comment says:


             // Substitution might have stripped off a contextual conversion to
             // bool if this is the operand of an '&&' or '||'. For example, we
             // might lose an lvalue-to-rvalue conversion here. If so, put it back
             // before we try to evaluate.

Removing that block DOES result in the error message being correct (error: atomic constraint must be of type 'bool' (found 'S<int>')), but it also causes a bunch of asserts in situations where we assume the result is an 'integral type' (for the purposes of constant evaluation), so it seems we're at least missing some other check somewhere.

**Comment by erichkeane** [comment]
Patch here: https://reviews.llvm.org/D141954
