### ISSUE TITLE
[libc++-14] <ranges> header fails to define std::ranges::contiguous_range

### ISSUE THREAD

**Issue by Wentzell** [llvm/llvm-project#54765]
The code snippet

```cpp
#include <ranges>

template <std::ranges::contiguous_range R>
void f(R r){}
```

compiles successfully (using `-stdlib=libc++ -std=c++20`) with clang-13.0.1 and clang-trunk,
but fails to compile with clang-14.0.0

```
<source>:3:24: error: no type named 'contiguous_range' in namespace 'std::ranges'
template <std::ranges::contiguous_range R>
          ~~~~~~~~~~~~~^
<source>:4:8: error: unknown type name 'R'
void f(R r){}
       ^
2 errors generated.
Compiler returned: 1
```
See https://godbolt.org/z/1na3EaeEe

**Comment by DimitryAndric** [comment]
@ldionne maybe this has to do with commits add3ab7f4c8a7f25c2940889d397cbdc9f267666 and 3f43d803382d57e3fc010ca19833077d1023e9c9 just not making it into 14.0.0?

@Wentzell I'm assuming you are using the exact 14.0.0 release tag, not the `release/14.x` branch?

**Comment by Wentzell** [comment]
Yes this was using the exact 14.0.0 tag. I have not tried if the issue persists on 14.x

**Comment by Wentzell** [comment]
I can confirm that this issue persists with 14.0.1.

**Comment by philnik777** [comment]
@DimitryAndric No, this has nothing to do with the `span` stuff, but it's the same type of error.
It looks like `std::ranges::contiguous_range` is guarded under `_LIBCPP_HAS_NO_INCOMPLETE_RANGES`, but has already been shipped in libc++ 13.
@tstellar Is there still time for LLVM 14 patches? If that's the case I'll write a patch. Otherwise I think it's not yet widely used enough to matter very much, so I wouldn't change it for libc++15 again.

**Comment by var-const** [comment]
@tstellar What is the deadline for a patch to still be accepted for LLVM 14?

**Comment by tstellar** [comment]
@var-const Probably around June 1.  June 8 is the last planned 14.0.x release.

**Comment by DavidKeller** [comment]
@philnik777 Our code base is using these concepts since clang-13. So we're particularly interested in the fix.

Is this fix just a matter of removing the `_LIBCPP_HAS_NO_INCOMPLETE_RANGES` guard around the concept definitions ?

**Comment by philnik777** [comment]
No, the concepts require other parts of `ranges` and we'd like to keep the amount of available ranges-stuff low until we implement all of the one ranges proposal. I'll try to get the fix working in the next few days. I have been procrastinating on that a bit.

**Comment by DavidKeller** [comment]
Please let me know if I can be of any help.

**Comment by Wentzell** [comment]
@philnik777 Thank you for looking into this!

It seems the fix was committed to `main`. However the issue only ever showed for the llvm 14.0.x releases.
Shouldn't the fix go into the 14.x branch?

**Comment by philnik777** [comment]
@Wentzell The fix will go into the 14.x branch. This is also a fix for the libc++15 release, since I don't think we will complete the one ranges proposal in the libc++15 time frame. But we should get it done for libc++16. @ldionne or @tstellar (?) will put it in the 14.x branch. I don't know the process for this.

**Comment by Wentzell** [comment]
Thank you for clarifying!

**Comment by tstellar** [comment]
@ldionne Is this Ok to backport? https://github.com/llvm/llvm-project/commit/b177a90ce7b590dfce6479142f46fd1b9554a3b3

**Comment by tstellar** [comment]
Is someone able to backport this to a personal branch so we can create a pull request?
