### ISSUE TITLE
Multiple  aborts/crashes in JIT tests in a 32-bit LLVM run

### ISSUE THREAD

**Issue by msebor** [llvm/llvm-project#54844]
Running the LLVM test suite in a 32-bit build shows failures in the tests below.  Based on quickly skimming the stack traces and some of the source code some look expected but others might not be.  This is just to record these for future review and reference.
```
Failed Tests (14):
  LLVM :: ExecutionEngine/MCJIT/cross-module-sm-pic-a.ll
  LLVM :: ExecutionEngine/MCJIT/eh-lg-pic.ll
  LLVM :: ExecutionEngine/MCJIT/multi-module-sm-pic-a.ll
  LLVM :: ExecutionEngine/MCJIT/remote/test-global-init-nonzero-sm-pic.ll
  LLVM :: ExecutionEngine/MCJIT/remote/test-ptr-reloc-sm-pic.ll
  LLVM :: ExecutionEngine/MCJIT/stubs-sm-pic.ll
  LLVM :: ExecutionEngine/MCJIT/test-global-init-nonzero-sm-pic.ll
  LLVM :: ExecutionEngine/MCJIT/test-ptr-reloc-sm-pic.ll
  LLVM :: ExecutionEngine/OrcLazy/debug-descriptor-elf-minimal.ll
  LLVM :: ExecutionEngine/OrcLazy/debug-objects-elf-minimal.ll
  LLVM :: ExecutionEngine/OrcLazy/static-library-support.ll
  LLVM :: ExecutionEngine/RuntimeDyld/PowerPC/ppc64_elf.s
  LLVM :: ExecutionEngine/RuntimeDyld/PowerPC/ppc64_reloc.s
  LLVM :: ExecutionEngine/RuntimeDyld/X86/TLS.s
```
More details about the failures are in the attached [llvm-il32-test.log](https://github.com/llvm/llvm-project/files/8459934/llvm-il32-test.log).

**Comment by efriedma-quic** [comment]
The RuntimeDyld should be host-independent; there's no fundamental reason for the tests to fail, unless I'm misunderstanding something about the way llvm-rtdyld works.

The other tests seem to indicate MCJIT is failing to JIT native code; what exact target are you using?

(For reference, we do have some 32-bit buildbots running, but I think they're all ARM, configured with -DLLVM_TARGETS_TO_BUILD='ARM'.)

CC @lhames for llvm-rtdyld.

**Comment by lhames** [comment]
The first thing to note is that most of these failures are MCJIT and RuntimeDyld tests. Both systems are in maintenance mode and not receiving any attention beyond critical fixes.

The OrcLazy failures are more of a worry. We'll want to get them fixed, but the backtraces aren't included in the logs:

```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /ssd/build/llvm-gcc-ilp32/bin/lli --jit-linker=rtdyld --generate=__dump_jit_debug_objects /ssd/src/llvm/llvm/test/ExecutionEngine/OrcLazy/debug-objects-elf-minimal.ll
```

Could you try re-running the failed OrcLazy tests manually to see if you can get a trace?


--- Notes on the MCJIT and RuntimeDyld failures, just for completeness ---

All of the failing MCJIT tests use either the small code model, exceptions, or remote execution. None of those features is well supported in MCJIT, so I think the right thing to do with these tests is to add guards so that we only run them in configs where they seem to work.

The reason that I'm not suggesting fixing these features in MCJIT is that they're all better supported in ORC, so we're better off putting the development work into expanding the platforms where ORC is supported.

> ```
> LLVM :: ExecutionEngine/RuntimeDyld/X86/TLS.s
> ```

This is guarded by `# REQUIRES: x86_64-linux` -- I wouldn't have expected it to run on a 32-bit build. Maybe we need to tighten the guard up?

> ```
> LLVM :: ExecutionEngine/RuntimeDyld/PowerPC/ppc64_elf.s
> LLVM :: ExecutionEngine/RuntimeDyld/PowerPC/ppc64_reloc.s
> ```

These are both failing with `Relocation R_PPC64_REL24 overflow`. We should be able to fix them by using a slab allocator, but I'd also be happy just disabling the test on failing platforms.

**Comment by efriedma-quic** [comment]
> You mentioned 32-bit, but this looks like x86-64 ILP32 -- is that right? Could you share how your build is configured?
>
> Could you try re-running the failed OrcLazy tests manually to see if you can get a trace?

I just tried this myself.  I get the same failures just configuring LLVM with `-DLLVM_BUILD_32_BITS=On -DCMAKE_LIBRARY_PATH=/usr/lib32` on Ubuntu.  It looks like it's crashing trying to run 64-bit code (code containing a REX prefix) on 32-bit.  I think we somehow end up with the wrong host triple; in the CMake log, I see "LLVM host triple: x86_64-unknown-linux-gnu".  Probably that shouldn't happen... I'll try messing with it a bit more.

**Comment by msebor** [comment]
I'm using x86_64 running Fedora 35 Linux.  I configured with only `-DLLVM_BUILD_32_BITS=On`.  With `-DLLVM_HOST_TRIPLE=i686-pc-linux-gnu` the failures disappear.  I didn't explicitly `-DLLVM_DEFAULT_TARGET_TRIPLE` in the successful run but I found it also set to `i686-pc-linux-gnu` in `CMakeCache.txt`.  With it set to `x86_64-linux-gnu` all the `ExecutionEngine` tests are UNSUPPORTED.  (I have no idea if this is a valid setting or if the result is to be expected; I just tried it because that's the default target I wanted to configure for.)

In the meantime, I've added `-DLLVM_HOST_TRIPLE=i686-pc-linux-gnu` to my 32-bit build script.  Thanks for the hit!

**Comment by msebor** [comment]
That should have been "hint" above.

**Comment by efriedma-quic** [comment]
Closing as working.  Filed #54855 to follow up on the broken LLVM_BUILD_32_BITS.

**Comment by efriedma-quic** [comment]
> With it set to x86_64-linux-gnu all the ExecutionEngine tests are UNSUPPORTED.

I think all the JIT tests get disabled if the default target triple is different from the host; the tests assume that you're building a cross compiler, and therefore can't JIT native code.
