### ISSUE TITLE
No expected crash when attempting to modify string constant

### ISSUE THREAD

**Issue by dmantipov** [llvm/llvm-project#55039]
In the following program:
```
#include <stdio.h>

void f (char *a, char *b) {
  a[0] = 'A';
  b[0] = 'B';
}

int main (int argc, char *argv[]) {
  char a[] = "aaa";
  char *b = "bbb";

  f (a, b);
  printf ("%s %s\n", a, b);
  return 0;
}
```
an attempt to modify string constant `b` should cause crash. But this is not the case for `clang -O3`:
```
$ gcc test.c 
$ ./a.out 
Segmentation fault (core dumped)
$ gcc -O3 test.c 
$ ./a.out 
Segmentation fault (core dumped)
$ clang test.c 
$ ./a.out 
Segmentation fault (core dumped)
$ clang -O3 test.c 
$ ./a.out 
Aaa bbb
$ 
```
Version is:
```
$ clang -v
clang version 13.0.0 (Fedora 13.0.0-3.fc35)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/11
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/11
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```

**Comment by nikic** [comment]
There is no such thing as an "expected" crash: The store exhibits undefined behavior, so clang can optimize this code however it likes.

At worst, there is a lost optimization opportunity here. Rather than dropping the store, we could replace with unreachable in https://github.com/llvm/llvm-project/blob/0ecbb683a2faf0ec5bcb9eb472ebd9921cbe683a/llvm/lib/Transforms/InstCombine/InstCombineLoadStoreAlloca.cpp#L1372-L1376

I'm not entirely sure whether that would be legal, that depends on the precise semantics of `pointsToConstantMemory()`: Whether any store to the memory is UB, or whether only a store of a different value is UB.

**Comment by fhahn** [comment]
> At worst, there is a lost optimization opportunity here. Rather than dropping the store, we could replace with unreachable in

I suspect that the gain from turning it into `unreachable` would be relatively low.

I am going to close this issue as this is working as expected at the moment. Please feel free to re-open if we should use the issue to track any work with respect to turning it into unreachable.
