### ISSUE TITLE
lldb::SBType::GetFieldAtIndex returning static field members. 

### ISSUE THREAD

**Issue by siggi-alpheus** [llvm/llvm-project#55040]
I had a hiccup trying to figure the virtual pointer layout of [this class from google/glog](https://github.com/google/glog/blob/master/src/logging.cc#L433). The heuristic used in the [types.py](https://github.com/llvm/llvm-project/blob/main/lldb/examples/python/types.py) example looks for an initial field that starts at a pointer-size offset into the class to infer that the class has a virtual table pointer. When the first field of a class is static, it appears this heuristic will fail, as the static member returns a zero offset.

I haven't found any good way to identify or filter out static members, [it appears the data isn't there at all](https://github.com/llvm/llvm-project/blob/main/lldb/include/lldb/Symbol/Type.h#L346).
Maybe `SBTypeMember` needs an `IsStatic()` function, or perhaps `GetOffsetInBytes()` could return a sentinel value to indicate that the member does not have this pointer offset?

Here's what the "offending" code looks like:

```cpp
class LogFileObject : public base::Logger {
 public:
  LogFileObject(LogSeverity severity, const char* base_filename);
  ~LogFileObject();
...
 private:
  static const uint32 kRolloverAttemptFrequency = 0x20;

  Mutex lock_;
...
};
```

**Comment by jimingham** [comment]
How are you getting the type's elements?  The "fields" property on SBType doesn't include static fields, it's implementation uses the clang::RecordDecl::field_iterator which omits static members.  So you shouldn't need to tell whether an SBTypeMember is static or not in the SBType.members list, because it shouldn't have any entries for the static variables in a class.  It seems to me the problem is the opposite, I can't see how you would answer the question "What are the static members of class Foo"...

Jim

**Comment by siggi-alpheus** [comment]
There's something deeper going on here and I'm having trouble creating a minimized repro.
I'm using the C++ API, retrieving fields with `SBType::GetFieldAtIndex()`, and I'm definitely getting the static member that way. I can repro the same behaviour using the python API:
```
import lldb

d = lldb.SBDebugger.Create()
t = d.CreateTarget("bazel-bin/symbols/assay_types")

l = t.FindFirstType('google::(anonymous namespace)::LogFileObject')
for f in l.fields:
  print(str(f))
```
outputs: 
```
+0: (typedef gflags::uint32) kRolloverAttemptFrequency
+8: (class Mutex {
...
}) lock_
+56: (_Bool) base_filename_selected_
...
+200: (typedef google::glog_internal_namespace_::WallTime) start_time_
```

The DWARF has this:
```
0x000fac6d:         DW_TAG_member
                      DW_AT_name	("kRolloverAttemptFrequency")
                      DW_AT_decl_file	("/proc/self/cwd/external/com_github_google_glog/src/logging.cc")
                      DW_AT_decl_line	(455)
                      DW_AT_decl_column	(0x17)
                      DW_AT_type	(0x000f900b "const uint32")
                      DW_AT_declaration	(true)
                      DW_AT_const_value	(0x20)

0x000fac7c:         DW_TAG_member
                      DW_AT_name	("lock_")
                      DW_AT_decl_file	("/proc/self/cwd/external/com_github_google_glog/src/logging.cc")
                      DW_AT_decl_line	(457)
                      DW_AT_decl_column	(0x09)
                      DW_AT_type	(0x000f712f "Mutex")
                      DW_AT_data_member_location	(0x08)
```
I guess somehow filtering the static members is derailing for this particular type. I'll see if I can repro this in a local build in a debugger - or maybe this has been fixed already. I'm running V12:
```
$ lldb --version
lldb version 12.0.0
```

**Comment by jimingham** [comment]
Internally, lldb uses the presence of DW_AT_external to identify static members of a type.  For instance, 

class Foo {
  static int g_var = 0;
  int m_var;
};

produces:

0x00000045:   DW_TAG_class_type
                DW_AT_calling_convention	(DW_CC_pass_by_value)
                DW_AT_name	("Foo")
                DW_AT_byte_size	(0x04)
                DW_AT_decl_file	("/tmp/has_static.cpp")
                DW_AT_decl_line	(1)

0x0000004e:     DW_TAG_member
                  DW_AT_name	("g_var")
                  DW_AT_type	(0x000000000000008f "int")
                  DW_AT_decl_file	("/tmp/has_static.cpp")
                  DW_AT_decl_line	(6)
                  DW_AT_external	(true)
                  DW_AT_declaration	(true)

0x00000059:     DW_TAG_member
                  DW_AT_name	("m_var")
                  DW_AT_type	(0x000000000000008f "int")
                  DW_AT_decl_file	("/tmp/has_static.cpp")
                  DW_AT_decl_line	(7)
                  DW_AT_data_member_location	(0x00)

In the clang dwarf parser, we test this in ParseSingleMember:

  // Handle static members
  if (attrs.is_external && attrs.member_byte_offset == UINT32_MAX) {

In your case, it looks like the static variable is a const, so we have:

>                       DW_AT_const_value	(0x20)
rather than DW_AT_external.  I think that's why we aren't recognizing this as a static member though I didn't follow the parsing through to see where this DIE did get handled.  
Jim

**Comment by jimingham** [comment]
Sorry for being a little confusing.  A close observer would note that the class definition I quoted doesn't compile, since you have to define the static out of the class definition.  I was trying to see if defining the static inline would change the DWARF.  The actual DWARF was from a compilation that doesn't have the "= 0".  

But, then I tried:

class Foo {
  const static int g_var = 0;
  int m_var;
};

which does compile and would produce a const value like what you were seeing.  But with a recent clang, this produces:

0x00000063:     DW_TAG_member
                  DW_AT_name	("g_var")
                  DW_AT_type	(0x00000000000000a5 "const int")
                  DW_AT_decl_file	("/tmp/has_static.cpp")
                  DW_AT_decl_line	(6)
                  DW_AT_external	(true)
                  DW_AT_declaration	(true)
                  DW_AT_const_value	(0)

so it has the const value but also the external declaration, and not surprisingly g_var does NOT show up in the members list in the type.

Jim

**Comment by siggi-alpheus** [comment]
Interesting, I see my attempted repro has the `DW_AT_external` tag:
```
0x000023ed:     DW_TAG_member
                  DW_AT_name	("kZero")
                  DW_AT_decl_file	("/workspaces/thresher/repro.cc")
                  DW_AT_decl_line	(6)
                  DW_AT_decl_column	(0x19)
                  DW_AT_type	(0x000001c3 "const uint32_t")
                  DW_AT_external	(true)
                  DW_AT_accessibility	(DW_ACCESS_public)
                  DW_AT_declaration	(true)
                  DW_AT_const_value	(0x20)
```
Out of curiosity - is there a good reason why not to filter on the presence of the `DW_AT_data_member_location` tag?

**Comment by siggi-alpheus** [comment]
> Sorry for being a little confusing.

Not at all - thanks for taking a look and explaining things to me.

**Comment by jimingham** [comment]
> On Apr 22, 2022, at 11:43 AM, Sigurður Ásgeirsson ***@***.***> wrote:
> 
> 
> Interesting, I see my attempted repro has the DW_AT_external tag:
> 
> 0x000023ed:     DW_TAG_member
>                   DW_AT_name	("kZero")
>                   DW_AT_decl_file	("/workspaces/thresher/repro.cc")
>                   DW_AT_decl_line	(6)
>                   DW_AT_decl_column	(0x19)
>                   DW_AT_type	(0x000001c3 "const uint32_t")
>                   DW_AT_external	(true)
>                   DW_AT_accessibility	(DW_ACCESS_public)
>                   DW_AT_declaration	(true)
>                   DW_AT_const_value	(0x20)
> Out of curiosity - is there a good reason why not to filter on the presence of the DW_AT_data_member_location tag?
> 

That's a good question, but for one of our clang DWARF experts, of which I am not one...

Jim

**Comment by labath** [comment]
> Out of curiosity - is there a good reason why not to filter on the presence of the DW_AT_data_member_location tag?
> That's a good question, but for one of our clang DWARF experts, of which I am not one...

Adding some DWARF experts (@dwblaikie).

I think there is some confusion in the DWARF spec about the meaning of `DW_AT_external` in this context. The spec first says this:
```
A DW_AT_external attribute, which is a flag, if the name of a variable is visible outside
of its enclosing compilation unit.
```
which makes the attribute sound completely unrelated to static-ness. *However*, then it goes on (in an non-normative note) with:
```
The definitions of C++ static data members of structures or classes are represented by
variable entries flagged as external. Both file static and local variables in C and C++
are represented by non-external variable entries.
```
At first glance that may make sense, since the `static` keyword (the "usual" way of making something non-external) has a slightly different meaning in a class, so one cannot make a static member non-external that way. However, one can also make something non-external by putting it inside an anonymous namespace, and that method can be applied to static members as well.

So, I would expect that a static member inside an anonymous namespace does not have the external attribute. However, clang does not do that -- it still emits the attribute. OTOH, gcc does not emit the attribute, so I would be inclined to consider the clang behavior a bug, and try to determine static-ness based on the presence of the `DW_AT_data_member_location` (and `DW_AT_data_bit_offset`) attribute.

**Comment by dwblaikie** [comment]
re: @labath's reading. Yeah, that all sounds right - maybe some history about how the non-normative DWARF spec text could help, but I guess it was just loose language.

The GCC behavior probably comes from a simple implementation that inspects the linkage of the variable when deciding whether to put `DW_AT_external` on it, without consideration for member, etc.

Regardless of what the spec says, supporting what GCC does is probably a good idea - and yeah, it seems better to determine non-static members by the presence/absence of of `DW_AT_data_member_location` rather than `DW_AT_external`. (I guess in theory a data member might not have a location that can be expressed? (like a local or global variable can have no location) but in practice that seems to not be an issue?)

(as for the original question: Trying to determine if a class is dynamic/has virtual functions based on the offset of the first non-virtual member is probably not the best way to go - instead looking for the virtuality property on the class would be a good idea)

**Comment by siggi-alpheus** [comment]
> (as for the original question: Trying to determine if a class is dynamic/has virtual functions based on the offset of the first non-virtual member is probably not the best way to go - instead looking for the virtuality property on the class would be a good idea)

The example script [tests the `IsPolymorphicClass()`](https://github.com/llvm/llvm-project/blob/main/lldb/examples/python/types.py#L213) property too. Maybe that's a sufficient check to know that the class has a virtual table pointer at this pointer offset 0?

**Comment by dwblaikie** [comment]
> > (as for the original question: Trying to determine if a class is dynamic/has virtual functions based on the offset of the first non-virtual member is probably not the best way to go - instead looking for the virtuality property on the class would be a good idea)
> 
> The example script [tests the `IsPolymorphicClass()`](https://github.com/llvm/llvm-project/blob/main/lldb/examples/python/types.py#L213) property too. Maybe that's a sufficient check to know that the class has a virtual table pointer at this pointer offset 0?

Not sure that guarantees the offset/location of the vtable - I guess that might depend on the inheritance hierarchy, but I'm not sure. I think computing the offset as a side effect of inspecting fields is probably not ideal. 

In the DWARF itself there's a `DW_TAG_member` that's marked `DW_AT_artificial` and named "_vptr$<type name>" in the base of that virtual hierarchy (might not be the ultimate base - since the polymorphic class may derive from some non-polymorphic type). Maybe that field/properties are accessible through the LLDB API.

**Comment by siggi-alpheus** [comment]
> In the DWARF itself there's a `DW_TAG_member` that's marked `DW_AT_artificial` and named "_vptr$" in the base of that virtual hierarchy (might not be the ultimate base - since the polymorphic class may derive from some non-polymorphic type). Maybe that field/properties are accessible through the LLDB API.

That'd be ideal, though it looks as [though LLDB/Clang reconstructs](https://github.com/llvm/llvm-project/blob/09c2b7c35af8c4bad39f03e9f60df8bd07323028/lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp#L2836) the vtable layout of a class, rather than reading it from the symbols. I'll see if I can coax that info out of the API.

**Comment by siggi-alpheus** [comment]
> Not sure that guarantees the offset/location of the vtable - I guess that might depend on the inheritance hierarchy, but I'm not sure. I think computing the offset as a side effect of inspecting fields is probably not ideal.

@dwblaikie it looks like any class that `IsPolymorphic()` will have a vtable at offset zero. However, I find that Chrome uses [`[[no_unique_address]]`](https://en.cppreference.com/w/cpp/language/attributes/no_unique_address), leading to member variables that overlap the virtual table(!!!) in the symbols I'm working with.
I wonder whether/how LLDB copes with this...
