### ISSUE TITLE
Miscompile when compiling OpenSSL with clang-14 (x64)

### ISSUE THREAD

**Issue by paulidale** [llvm/llvm-project#55255]
Refer: openssl/openssl#18225 for an analysis of the problem encountered.

OpenSSL is failing when compiled with clang-14 unless the `-fno-strict-aliasing` option is set.  An executable is created but it is wrong.

The function that is failing is:

```c
static void nist_cp_bn_0(BN_ULONG *dst, const BN_ULONG *src, int top, int max)
{
    int i;

#ifdef BN_DEBUG
    (void)ossl_assert(top <= max);
#endif
    for (i = 0; i < top; i++)
        dst[i] = src[i];
    for (; i < max; i++)
        dst[i] = 0;
}
```

**Comment by nikic** [comment]
As I understand it, the relevant call would be https://github.com/openssl/openssl/blob/aff636a4893e24bdc686a00a13ae6199dd38d6aa/crypto/bn/bn_nist.c#L358-L359, which works on `buf.bn` and directly below that we have code reading from `buf.ui`, so that's likely where TBAA comes into it.

**Comment by nikic** [comment]
I expect that this is roughly equivalent to what is happening here:
```
#include <stdint.h>
#include <stdlib.h>

static void write_u64(uint64_t *ptr, uint64_t val) {
  *ptr = val;
}

static uint32_t read_u32(uint32_t *ptr) {
  return *ptr;
}

uint32_t test(size_t arg1, size_t arg2) {
  union {
    uint64_t bn[2];
    uint32_t ui[4];
  } buf;
  write_u64(&buf.bn[arg1], 42);
  return read_u32(&buf.ui[arg2]);
}
```
The separate functions are there to avoid giving the accesses omnipotent char TBAA.

Though I suspect that this must be UB, otherwise strict aliasing as a concept would be useless. @efriedma-quic or @zygoloid probably know the rules here...

**Comment by paulidale** [comment]
Thanks for the analysis.  It's going through a union which is supposed to work under strict aliasing.  Still, I'm by no means an expect and will wait to see...

**Comment by paulidale** [comment]
Looking at example 3 of 6.5.2.3 in [n1256](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf), it seems that passing a union member to a function prevents other union members from being considered aliased:

> The following is not a valid fragment (because the union type is not visible within function f):
> ```c
> struct t1 { int m; };
> struct t2 { int m; };
> int f(struct t1 *p1, struct t2 *p2)
> {
>       if (p1->m < 0)
>             p2->m = -p2->m;
>       return p1->m;
> }
> int g()
> {
>       union {
>             struct t1 s1;
>             struct t2 s2;
>       } u;
>       /* ... */
>       return f(&u.s1, &u.s2);
> }
> ```

This example isn't quite the same as what's going on here where only one field is passed to a function and the union is visible when changing fields.  The example is also about union fields that have a shared _common initial sequence_ which isn't the case.

Replacing the function call to `nist_cp_bn_0()` by a macro equivalent seems to fix things.  It seems rather odd that the function call provokes strict aliasing problem.  Still, could someone wiser in this comment please?

**Comment by paulidale** [comment]
@[nikic](https://github.com/nikic), that example looks close, although in our case there is no call to `read_u32()`, it code at the same level as the `write_u64()` call.  Changing your example to match (i.e. change `read_32()` to be a macro or manually inlined) and correct code is generated.

I'm confused :confused:

**Comment by paulidale** [comment]
I've reduced this case down to a more manageable example ([Compiler Explorer](https://godbolt.org/z/cfa5qeb3P)).  This version works, change the `#if 0` to `#if 1` and it fails.  I.e. calling a function fails but using a macro works.  Despite all union references being outside the function.

```c
#include <stdint.h>
#include <stdlib.h>

#define BN_ULONG uint64_t
#define NIST_INT64 uint64_t
#define BN_BITS2       (BN_BYTES * 8)
#define BN_BYTES        8
#define BN_NIST_192_TOP (192+BN_BITS2-1)/BN_BITS2

#if 0
static void nist_cp_bn_0(BN_ULONG *dst, const BN_ULONG *src, int top, int max)
{
    int i;

    for (i = 0; i < top; i++)
        dst[i] = src[i];
    for (; i < max; i++)
        dst[i] = 0;
}
#else
#define nist_cp_bn_0(dst, src_in, top, max) \
{                                           \
    int ii;                                 \
    const BN_ULONG *src = src_in;           \
                                            \
    for (ii = 0; ii < top; ii++)            \
        (dst)[ii] = src[ii];                \
    for (; ii < max; ii++)                  \
        (dst)[ii] = 0;                      \
}
#endif

int BN_nist_mod_192(BN_ULONG *r_d, const BN_ULONG *a_d)
{
    extern int top;
    union {
        BN_ULONG bn[BN_NIST_192_TOP];
        unsigned int ui[BN_NIST_192_TOP * sizeof(BN_ULONG) / sizeof(unsigned int)];
    } buf;

    nist_cp_bn_0(buf.bn, a_d + BN_NIST_192_TOP, top - BN_NIST_192_TOP, BN_NIST_192_TOP);

    NIST_INT64 acc;         /* accumulator */
    unsigned int *rp = (unsigned int *)r_d;
    const unsigned int *bp = (const unsigned int *)buf.ui;

    acc = rp[0];
    acc += bp[3 * 2 - 6];
    acc += bp[5 * 2 - 6];
    rp[0] = (unsigned int)acc;
    acc >>= 32;

    return 1;
}
```

Putting `dst` into a macro local variable and it fails again.

**Comment by nikic** [comment]
@paulidale I believe the relevant distinction here is not whether the code is in a separate function, but whether you're making an access directly on a union member, or through a pointer to a union member. See https://c.godbolt.org/z/exErzvj7z for a variant without separate functions, just storing pointers to the union members.

I don't think the "common initial sequence" part is applicable here, because the union members don't have a common initial sequence here. Footnote 82) seems more relevant:
```
If the member used to access the contents of a union object is not the same as the member last used to
store a value in the object, the appropriate part of the object representation of the value is reinterpreted
as an object representation in the new type as described in 6.2.6 (a process sometimes called "type
punning"). 
```
I'm guessing that while this allows you to reinterpret one pointer type to another pointer type through a union, doing mixed accesses through those pointers remains as undefined as it usually is.

What I'm not entirely clear on here is whether or not the code has UB if you do direct accesses (https://c.godbolt.org/z/63vdfMvv6) or whether clang just chooses to compile this more conservatively.

**Comment by paulidale** [comment]
Ah, that makes sense.  The inlined version doesn't convert the array to a pointer so it works.  Calling the function does such a conversion and doesn't.  Interesting, is passing the pointer to memcpy() worked, so there is a lack on consistency here.

I'm concerned (scared) about how many similar instances OpenSSL might contain.  Unions are used widely for type punning and no warning that undefined behaviour was being relied on has been seen.

**Comment by paulidale** [comment]
At this stage, I'm content to close this since the problem is with our code not LLVM.

**Comment by thesamesam** [comment]
Note that this code was introduced to fix a strict aliasing warning: https://github.com/openssl/openssl/commit/0985bd4f802e967a363d8e4403af41d69255977c. Compiler diagnostics aren't guaranteed (compilers aren't compliance checkers) and the point at which warnings are generated isn't always the same as the point at which optimisation is done.

That commit made the structure harder to introspect (but still incorrect) and then it ended up warning-no-more.

**Comment by paulidale** [comment]
We do do -fstrict-aliasing builds, it comes as part of -O2 and above.  This specific problem appeared with clang-14.  We might be able to turn on more strict aliasing warnings, and we should.  The original code _looks_ like it should work fine but runs afoul of something rather subtle IMO.

**Comment by SoapGentoo** [comment]
Enabling `-fstrict-aliasing` doesn't mean the compiler is guaranteed to break code that isn't valid, it just means the compiler will use type-based aliasing analysis (TBAA) to determine whether two pointers do not alias and use that for optimising out redundant store/load operations. Said differently, "is this program free of undefined behaviour [due to typepunning]" is turing complete, and passing `-fstrict-aliasing` will increase the likelihood of a compiler miscompiling your code (as Clang 14 did), but it's in no way a guarantee it will.

The [preferred way](https://gist.github.com/shafik/848ae25ee209f698763cffee272a58f8#what-is-type-punning) (most of the treatise is on C++, but applies to C just as well, since they share the same abstract machine) to perform type-punning on modern compilers is
1. `memcpy` ([GCC and Clang optimize this with compile-time size parameters](https://godbolt.org/z/bKd5aM64x))
2. reading/storing through a `union` (and not to pointers of the individual members, since that would make TBAA impossible)

All of these cases always boil down to people casting pointers around between incompatible types. Once you stop casting around pointers, these bugs all go away.

**Comment by thesamesam** [comment]
> We do do -fstrict-aliasing builds, it comes as part of -O2 and above. This specific problem appeared with clang-14. We might be able to turn on more strict aliasing warnings, and we should. The original code _looks_ like it should work fine but runs afoul of something rather subtle IMO.

(What I meant was that the _only_ thing you can do here is force it on for all builds, of all optimisation levels, to increase the chance of catching stuff via test suites. You also can't assume -O2 will always enable it depending on compiler (version and vendor). It's a good idea to test with various optimisation levels if you're not already anyway as it's a good way to expose UB.)

**Comment by fhahn** [comment]
> At this stage, I'm content to close this since the problem is with our code not LLVM.

Thanks, sounds good!
