### ISSUE TITLE
Unexpected "undefined reference" when using inline

### ISSUE THREAD

**Issue by pmor13** [llvm/llvm-project#55274]
```
inline void f(void)
{
}

int main(void)
{
  f();
}
```
leads to:
```
undefined reference to `f'
```
https://godbolt.org/z/W11hd1MTb

**Comment by lgxbslgx** [comment]
It seems not a bug and GCC produces the same error message.

Clang currently doesn't inline method `f(void)` because of the unprofitability which means that the symbol/reference `f` is still at the method `main`. Because the method `f(void)` doesn't have the `extern` function specifier, so it don't generate the native code for the method `f(void)`. Then in the object file, there is only a method `main` and no method `f(void)`. So when linking, the linker reports `undefined reference`.

What you need to do is adding the `extern` keyword to the method `f(void)` so that the compiler can generate the native code for the method `f(void)`. Such as:

```
extern inline void f(void)
{
}
```
Some related discussion: https://discourse.llvm.org/t/conditions-that-cause-clang-refuse-inlining-a-function/33582

**Comment by tbaederr** [comment]
> What you need to do is adding the `extern` keyword to the method `f(void)`

Since this is C and the function is implemented in the source file anyway, I think adding `static` is more appropriate and makes the example work as well.

**Comment by lgxbslgx** [comment]
> Since this is C and the function is implemented in the source file anyway, I think adding static is more appropriate and makes the example work as well.

Thanks the suggestion. Adding `static` can solve the issue as well.

**Comment by pmor13** [comment]
C11, 6.7.4 Function specifiers, Semantics, 7:
> If all of the file scope declarations for a function in a translation unit include the **inline function specifier without extern**, then the definition in that translation unit is an **inline definition**. An inline definition **does not provide an external definition** for the function, and does not forbid an external definition in another translation unit.

> It is **unspecified** whether a **call to the function uses the inline definition or the external definition**.

Hence, this issue can be resolved as "not a problem".

**Comment by terminatorul** [comment]
Is this behavior really necessary for a compiler in 2024 ?

Can clang please do something about this, like add a language extension for this case ?

Because it looks to me the only way to deal with this problem is to make sure every inline function is defined twice:
 - once in the header file with the single inline specifier
 - once in a source file, with the extern inline specifiers

This doesn't help anyone, and the duplicate definition is just a problem waiting to happen

Since the solution is to copy the behavior of the C++ language (where a single occurence of the "inline" specifier sticks to all the other declarations of that function,, and everything just works), is it possible for the C compiler to fix this behavior , and make it similar to C++ ?
