### ISSUE TITLE
LLVM PGO profile portability between operating systems

### ISSUE THREAD

**Issue by Kobzol** [llvm/llvm-project#55403]
Hi! The `rustc` project uses LLVM PGO extensively in CI to improve the performance on LLVM on Linux targets. We're currently trying to extend the usage of PGO also to OS X and Windows, but because of CI usage limitations, we cannot effectively run PGO instrumantation on CI.

What we're trying to do instead is to take a PGO profile file (created by executing instrumented LLVM and then merged with  `llvm-profdata`) from a Linux system and then using this profile to optimize LLVM built on a Windows system.

I wanted to ask whether something like this is supported at all. The corresponding versions of LLVM on Linux and Windows are the same (`14.0.2`), but I'm not sure how much are the profiles portable between different operating systems. So far when we have tried to apply the profiles, the build has worked, but we haven't seen any speedup, which is a bit suspicious (of course Linux and Windows will exercise different code paths, but if the target CPU architecture stays the same, we would expect that PGO would work - on Linux it gives ~15% speedup).

**Comment by ilovepi** [comment]
Hi, sorry no one picked this up. I ran across this looking for something else, and can shed some light here if its still relevant.

The profile data is platform agnostic. Where differences will show up is in how well the functions match between the Windows implementation and the Linux implementation. For instance, Chrome often uses PGO profiles from arm64 Linux to optimize new arm64 Mac builds of chrome. The profiles match well enough, because the code itself is closely matched.  

Profile matching is a bit complicated, but, ideally, the IR functions would hash the same, and therefore match exactly between both versions. It's possible that they won't, due to different code paths, includes, etc. There is also some limited support for partial matching, but in my experience those tend to work best only when new control flow paths are introduced or some are removed. Differences in ISA features may also be important in some cases, but I'm unsure how significant they are generally.  

I would not expect the same level of speedup when using these profiles, but YMMV. As I said, some projects don't have much platform sensitivity in the important parts of their code. If `rustc` is in this category, then they should provide a good improvement. IIRC there used to be some issue w/ PGO working w/ Rust code since compiler flags where part of the input to the hash appended to the function signature. I believe that was mostly fixed, but something similar may be happening between platforms to prevent matching.

Also note that there is https://github.com/llvm/llvm-project/tree/main/clang/utils/perf-training where you can add a corpus to train the compiler w/ quickly. Using a curated set of files to train w/ should produce better results, and only increase build-time over a normal 2-stage build slightly. What tends to be more important is getting coverage for the various different parts of the compiler, so that sanitizer and profiling configs have coverage in the corpus, as well as coverage for the various backends you care about. 

Since `rustc` pins LLVM, I would expect you can reuse the profile for a long time until you update the LLVM revision, so I'm unsure about its real impact on CI infrastructure. I'd suggest perhaps rethinking the profiling strategy if `rustc` usage of LLVM doesn't vary widely, which I expect would be the case between updating LLVM revisions. I don't know if that suggestion will be the right trade-off for you, but it's worth considering.

**Comment by Kobzol** [comment]
Thank you for your response! We have since managed to make PGO work on both Windows and OS X, so there's less need for us to share these profiles. But thank you for confirming that on a general level, they should be mostly compatible.

Caching the PGO (and BOLT) optimized LLVM builds is indeed a direction that we want to take to optimize our CI time.
