### ISSUE TITLE
[mlir] Crash when folding i1 reshape

### ISSUE THREAD

**Issue by d0k** [llvm/llvm-project#55440]
```mlir
func.func @test() -> tensor<1xi1> {
  %0 = arith.constant dense<true> : tensor<1x1xi1>
  %1 = "tosa.reshape"(%0) {new_shape = [1]} : (tensor<1x1xi1>) -> tensor<1xi1>
  return %1 : tensor<1xi1>
}
```

```console
$ mlir-opt -canonicalize reshape.mlir
mlir-opt: mlir/lib/IR/AttributeDetail.h:114: static mlir::detail::DenseIntOrFPElementsAttrStorage::KeyTy mlir::detail::DenseIntOrFPElementsAttrStorage::getKey(mlir::ShapedType, ArrayRef<char>, bool): Assertion `numElements != 1 && "splat of 1 element should already be detected"' failed.
```

This is a regression introduced by f21896f2c6dc6f4c2c3d0f192f7fefd178f5d5f7

**Comment by lattner** [comment]
I’ll take a look, thank you for the testcase!

**Comment by lattner** [comment]
I will continue looking at this tomorrow.  The root cause here is that:

```
DenseIntOrFPElementsAttr::getRaw(ShapedType type,
                                                   ArrayRef<char> data) {
  ...
  return Base::get(type.getContext(), type, data, isSplat);
```

After Base::get is done, the "getRawData()" on the newly returned attribute is set to 0x1 instead of 0xFF for a boolean splat value.  I'm not sure why it's dropping the high bits in the implementation, but that needs to be fixed somehow.  I'll investigate more tomorrow.

**Comment by d0k** [comment]
Thanks for looking. There is some dubious code in `DenseElementsAttributeStorage::construct` https://github.com/llvm/llvm-project/blob/main/mlir/lib/IR/AttributeDetail.h#L193
