### ISSUE TITLE
libcxx: `path::iterator` has wrong category

### ISSUE THREAD

**Issue by Imre-Palik-Firebolt** [llvm/llvm-project#55521]
According to https://en.cppreference.com/w/cpp/filesystem/path , `path::iterator` should fulfil the concept of _LegacyBidirectionalIterator_.  But it is tagger as `typedef input_iterator_tag iterator_category;`
This makes it impossible to call `std::prev()` on `path::iterator`, as `prev()` has the following check:
`_LIBCPP_ASSERT(__n <= 0 || __is_cpp17_bidirectional_iterator<_InputIter>::value,
                 "Attempt to prev(it, n) with a positive n on a non-bidirectional iterator");`

Changing the `typedef` in `path::iterator` to `typedef bidirectional_iterator_tag iterator_category;`, makes `std::prev()` great again.

**Comment by philnik777** [comment]
The `except` part is the problem here. I assume dereferencing two iterators that compare equal might not refer to the same address. This makes it not actually conform to the definition of a forward iterator, which means it's just an input iterator. This means that we can't advertise `path::iterator` as a bidirectional iterator. I haven't looked at the code, but I this that's what's going on here.

**Comment by Imre-Palik-Firebolt** [comment]
Still, `std::prev()` should work for `path::iterator`.
