### ISSUE TITLE
clang-tidy doesn't apply fixes for bugprone-argument-comment

### ISSUE THREAD

**Issue by sean-mcmanus** [llvm/llvm-project#55570]
I'm using clang-tidy 14.0.3 on Windows 11.

Use test.cpp
```cpp
void func1(bool foo);
void func2()
{
    func1(/*bar=*/true);  // variable name is 'foo', not 'bar'
}
```

and run `clang-tidy.exe --config="{Checks: 'bugprone-argument-comment'}" --fix <path>/test.cpp --`

Bug: The result has the warning
```
warning: argument name 'bar' in comment does not match parameter na
me 'foo' [bugprone-argument-comment]
    func1(/*bar=*/true);  // variable name is 'foo', not 'bar'
```
but no fix is applied. Using --export-fixes doesn't work either.

The docs at https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/list.html show bugprone-argument-comment as having a fix, but none is getting applied. If there is some reason the fix isn't available, it would be helpful to be able to discover the reason somehow.

**Comment by njames93** [comment]
The check uses a, somewhat arbitrary, heuristic to determine how close the name is to the intended name, if it's deemed to be too far, no fix would be offered. This is the intended behaviour.
```cpp
void func1(bool foo);
void func2(bool bar);
void baz(){
  func1(/*bar=*/true);
  func2(/*bat=*/true);
}
```
In this case the fix for `func2` would be emitted as a typo from `bat` to `bar` likely.
The fix for `func1` has much less confidence that you intended the comment to be `foo`, it could easily be likely that you were meant to call `func2`, or any other function for that matter. In this case offering the fix may hide a bug where you have called the wrong function.
