### ISSUE TITLE
libc++: search doesn't work for filesystem::path in version 14.0

### ISSUE THREAD

**Issue by carrotIndustries** [llvm/llvm-project#55683]
This code: https://gcc.godbolt.org/z/efYnd88oq

```c++
#include <filesystem>
#include <algorithm>

namespace fs = std::filesystem;
void test()
{
    fs::path p;
    fs::path b;
    std::search(p.begin(), p.end(), b.begin(), b.end());
}
```

Fails to compile with libc++ 14.0. The code compiles with clang 13 or clang 14 when using libstdc++.

**Comment by jwakely** [comment]
It's because `filesystem::path::iterator` has:

https://github.com/llvm/llvm-project/blob/f15c60218d5c88c9f32942bce119e7ac25cb6d73/libcxx/include/__filesystem/path_iterator.h#L45

And you can't use `std::search` with input iterators.

The standard is a bit vague here, it says:

> A `path::iterator` is a constant iterator meeting all the requirements of a bidirectional iterator (25.3.5.6)
except that, for dereferenceable iterators `a` and `b` of type `path::iterator` with `a == b`, there is no requirement
that `*a` and `*b` are bound to the same object. Its `value_type` is `path`.

With libstdc++ it's a forward iterator, because the `*a` and `*b` bound to the same object condition is true. For libc++ that condition isn't true, which means it doesn't meet the forward iterator requirements, and so saying it's an input iterator makes sense.

So I'm not sure this is actually a bug, it's a feature of libc++.

**Comment by philnik777** [comment]
What Jonathan guessed is indeed the case.
