### ISSUE TITLE
Abort when parsing ELF file using llvm-nm

### ISSUE THREAD

**Issue by sleicasper** [llvm/llvm-project#55712]
reproduce steps:
`llvm-nm --debug-syms ./poc`

This issue can be reproduced in llvm11, I didn't test it on latest version of llvm.

[poc.zip](https://github.com/llvm/llvm-project/files/8777455/poc.zip)

**Comment by PRESIDENT810** [comment]
I tested this case on both llvm11 and llvm12. For llvm11, llvm-nm will crash with `LLVM ERROR: Invalid data was encountered while parsing the file`, but for llvm12, llvm-nm will show `error: poc section [index 17] has a sh_offset (0x8018) + sh_size (0x108) that is greater than the file size (0xb28)`, which seems to be the correct behavior. So I think this problem is already fixed in later version of llvm.

**Comment by jh7370** [comment]
@sleicasper, could you give some more details of your issue, please? Which version of LLVM do you have installed? How did this file get generated? What platform is it targeting (this may be useful in case there's an error in little versus big endian encoding)?
