### ISSUE TITLE
Provide clang flag to opt out of `wasm-opt` when linking wasm?

### ISSUE THREAD

**Issue by TerrorJack** [llvm/llvm-project#55781]
Currently, when linking wasm, `clang` attempts to detect `wasm-opt` in the environment, and invokes it with certain flags based on current optimization level. [source](https://github.com/llvm/llvm-project/blob/940e290860894d274c986c88bea2dcc17f1e93c3/clang/lib/Driver/ToolChains/WebAssembly.cpp#L133)

This behavior is undesirable when user wants to customize when or how `wasm-opt` is run. It would be nice if a `clang` command line flag can be provided to opt-out of this behavior.

**Comment by corona10** [comment]
I would like to take look at this issue :)

**Comment by abrown** [comment]
cc: @sunfishcode, @sbc100, @tlively or anyone else who may have worked on this: what do you all think about retaining the `name` custom section by default in `wasm-opt` and only removing it when the optimization level is explicitly dialed up? This section is quite useful for populating backtraces, e.g., and I [was confused](https://bytecodealliance.zulipchat.com/#narrow/stream/206238-general/topic/.E2.9C.94.20why.20would.20the.20.60name.60.20custom.20section.20be.20missing.3F) when the `name` section magically disappeared in a build.

**Comment by sbc100** [comment]
I think the simplest thing would be to preserve it in all cases.  If folks want to strip it they can use `-Wl,--strip-debug` which already exists today.

I think it might be as simple as adding `-g` unconditionally to wasm-opt (although that might end up add a name section to the binary where non existed previously... I think we should fix that on the wasm-opt side if that is the case).

**Comment by sbc100** [comment]
In other words, let wasm-ld decide what debug into to include, and ask wasm-opt to do its best to preserve it.

**Comment by abrown** [comment]
Should I submit a change request to add `-g` unconditionally to the [driver](https://github.com/llvm/llvm-project/blob/940e290860894d274c986c88bea2dcc17f1e93c3/clang/lib/Driver/ToolChains/WebAssembly.cpp#L133)?

**Comment by aheejin** [comment]
Adding `-g` to the driver invocation in the clang driver is one way, and I think another way might be to just, change binaryen's behavior so that even without `-g` given, we preserve the debug info. I checked with `clang` and `llc` and they preserve the existing debug info without `-g` given.

For example, if I create `test.ll` using
```console
clang -g test.c -c -emit-llvm -o test.ll
```
And finish compiling `test.ll` to `test.o` using `clang -g` or `llc`,
```console
llc -filetype-obj test.ll -o test.o
```
```console
```

**Comment by aheejin** [comment]
Adding `-g` to the driver invocation in the clang driver is one way.

I think another way might be to just, change binaryen's behavior so that even without `-g` given, we preserve the debug info. I checked with `clang` and `llc` and they preserve the existing debug info without `-g` given.

For example, if I create `test.ll` using
```console
clang -g test.c -c -emit-llvm -o test.ll
```
And finish compiling `test.ll` to `test.o` using `clang -g` or `llc`,
```console
llc -filetype-obj test.ll -o test.o
```
```console
clang -c test.ll -o test.o
```
Even though the second `llc` and `clang` don't have `-g`, they preserve the debug info. But this changes binaryen's current behavior, so I can be unaware of potential consequences. Thoughts? @kripken

**Comment by kripken** [comment]
@aheejin Hmm, I think changing binaryen may be a little risky. It's a change to a long-existing user interface and the result could be people shipping name sections unnecessarily without noticing it (if they don't measure code size).

Also, there is a reason binaryen differs from `llc` - `llc`'s inputs all know if they have debug info or not, so it's natural to preserve debug info as it was in the input. But `wasm-opt` can also receive as input a wat file which doesn't say if it has debug info or not, so we need user input to tell us whether to emit a names section. It made more sense in the past when binaryen had a second input format without clear debug info (asm2wasm / asm.js), so I guess it's debatable. And also `clang` has mixed behavior, requiring `-g` for source files but preserving debug info on object files automatically IIUC.

Still, for the reasons in the first paragraph I think it's better not to change binaryen here. Instead, could clang pass `-g` to `wasm-opt` when it received `-g` itself?

**Comment by abrown** [comment]
@kripken, I also was thinking along the lines of "conditionally pass `-g` along" but I couldn't figure out how this might work when `wasm-ld` is used directly. I don't see that it has a `-g` flag to pass along &mdash; were you thinking we should add one?

**Comment by sbc100** [comment]
Its in the clang driver linked above: https://github.com/llvm/llvm-project/blob/940e290860894d274c986c88bea2dcc17f1e93c3/clang/lib/Driver/ToolChains/WebAssembly.cpp#L133

wasm-ld never calls wasm-opt itself.. its something that run after wasm-ld.

**Comment by sbc100** [comment]
Also, I think its has to be unconditional since wasm-ld will produce debug info based on input object files, and not based on the `-g` flag passed to clang at link time.  In fact, I think clang ignores `-g` at link time.

Assuming `wasm-opt -g` means `don't strip debug info, but also don't generate any` then I think its fine to make it unconditional.

**Comment by kripken** [comment]
> Assuming `wasm-opt -g` means don't strip debug info, but also don't generate any then I think its fine to make it unconditional.

Unfortunately that's not true. Binaryen IR doesn't mention the presence or lack of debug info. That is, having or not having a names section is something the wasm binary format has, but not the text format, and not Binaryen IR which abstracts over both the text and binary format. Atm `wasm-opt -g` will emit a name section using the names used in the IR (which, if there wasn't a names section, will be things like `$0`).

But if there isn't a better solution, then adding that might be ok. We already have `hasFeaturesSection`, and could add `hasNamesSection` + handling for it.

**Comment by kripken** [comment]
(But if we did that, we'd need to add a new flag for it, likely, because of the breaking change issue from before - we don't want wasm-opt to start emitting the names section in new ways compared to what it did before.)

**Comment by sbc100** [comment]
I new option sounds reasonable.  Something like `--preserver-debug-info`... on the other hand we could make the default and add `--strip-debug`?

**Comment by kripken** [comment]
Looks like `wasm-opt` already has `--strip-debug` actually (which also strips the SourceMapURL and DWARF sections).

`--preserve-debug-info` sounds reasonable. (Or `-g?` :wink: )

**Comment by sbc100** [comment]
The problem with `-g` is that it could mean "generate debug sections" even when the include file doesn't contain them... do we ever want wasm-opt to do that?  Perhaps that should be the rare/opt-in thing?

**Comment by sbc100** [comment]
OK, how about this:  Why don't we do what `wasm-ld` does and preserve debug sections unless `--strip-debug` is passed?     But only add new names section if `-g` is passed?    No new option needed, no clang change needed.

**Comment by kripken** [comment]
> The problem with -g is that it could mean "generate debug sections" even when the input file doesn't contain them... do we ever want wasm-opt to do that?

It's probably rare, but an example use case of generating debug info when there was none before is: `wasm-opt --name-types -g` which will give wasm GC types useful stable names. Without stable names, they can get reordered during opts and the indexes mean nothing, and debugging is a total mess.

> Why don't we do what wasm-ld does and preserve debug sections unless --strip-debug is passed? 

My main concern there is that it's a breaking change for users. They had an existing workflow that does not emit a names section, and now it does. This is worrying because names sections are silent bloat and the user might not realize they are starting to ship larger wasm files for no reason.

That idea might be simpler overall, but it's also riskier. in contrast I think `--preserve-debug` has few downsides.

**Comment by dschuff** [comment]
> > The problem with -g is that it could mean "generate debug sections" even when the input file doesn't contain them... do we ever want wasm-opt to do that?

I can't think of any reason we want wasm-opt to do that.

> 
> It's probably rare, but an example use case of generating debug info when there was none before is: `wasm-opt --name-types -g` which will give wasm GC types useful stable names. Without stable names, they can get reordered during opts and the indexes mean nothing, and debugging is a total mess.

This involves the user passing an explicit flag though, so if `--name-types` means "generate new names and create a name section for them" then I think it's fine if `-g` without that flag always preserves but never generates new names. Probably in order for this to work we'd need to track which IR names came from the user and which were autogenerated by the parser, but that doesn't sound too terrible to do. 

> 
> > Why don't we do what wasm-ld does and preserve debug sections unless --strip-debug is passed?
> 
> My main concern there is that it's a breaking change for users. They had an existing workflow that does not emit a names section, and now it does. This is worrying because names sections are silent bloat and the user might not realize they are starting to ship larger wasm files for no reason.
> 
> That idea might be simpler overall, but it's also riskier. in contrast I think `--preserve-debug` has few downsides.

I agree that this isn't great. IMO it's slightly mitigated by the fact that wasm-opt users are expected to be toolchain developers who are driving wasm-opt with some kind of frontend (as opposed to "end" users developing apps). This means there are fewer direct users, and they will be updating their wasm-opt version explicitly, and (it seems to me) more likely to notice behavior changes than an end user (and maybe it's easier for us to warn them). But there's still some risk.

**Comment by kripken** [comment]
Fair point, yeah, it's mostly toolchain people that are relevant here. I agree that reduces the risk.

I don't feel super-strongly if everyone else disagrees with me. But I would prefer not to emit a name section by default in any mode, just because of that risk of silent bloat. I'd rather people need to opt-in to get something that has such a risk, using `-g` or a new `--preserve-debug`.

**Comment by sbc100** [comment]
Either of those sounds reasonable to me, as long as (one their own) they don't introduce a name section where there was none before.

**Comment by yamt** [comment]
IMO, it's simpler just to remove the automatic wasm-opt invocation.
as a user, my honest impression is that it's a rather surprising than useful. (it took a few hours for me to figure out that binaryen installation has silently affected my build.)
if a user wants to run wasm-opt, he can always do that by himself.

**Comment by ncruces** [comment]
Count me in as another user annoyed by this. Just wasted a hours of my life trying to recreate the optimized-with-debug binary I used to have, only to discover that it's "lost" because I added `wasm-opt` to path.

**Comment by zeux** [comment]
In addition to problems with features (see https://github.com/WebAssembly/wasi-sdk/issues/254, this happens on WASI-20 as well at least for meshoptimizer), when using WASI-SDK it's very surprising that the linker can call wasm-opt from the system installation (eg if Emscripten is installed system-wide) instead of using a bundled version. `wasm-opt` should be opt-in, or simply removed, otherwise the builds are not hermetic.

**Comment by jeaiii** [comment]
Yet another victim of this. I happened to install the wasm-opt locally to see what it does...little did I know it was being called on my machine by my clang toolchain. It feels unacceptable to call external programs by default just because they exist. We require deterministic builds across our machines. Only by chance did I enable -v and to my surprise I saw it was calling wasm-opt while investigating linker scripts

**Comment by sbc100** [comment]
> Yet another victim of this. I happened to install the wasm-opt locally to see what it does...little did I know it was being called on my machine by my clang toolchain. It feels unacceptable to call external programs by default just because they exist. We require deterministic builds across our machines. Only by chance did I enable -v and to my surprise I saw it was calling wasm-opt while investigating linker scripts

I think I understand where you are coming from, and I think we do need to solve this, but I'm also wonder if there is precedent for clang doing this.   For example, is this fundamentally different from clang calling the GNU linker (`/usr/bin/ld`) from the PATH?   Do you consider that non-hermetic/non-deterministic too?

**Comment by TerrorJack** [comment]
wasm-opt may or may not be deterministic, afaik this is not documented in the binaryen repo. The real annoyance here is I may want to invoke `wasm-opt` at a different timing (e.g. after pre-initialization with `wizer`), or not run it at all to fasten the dev cycle, or run it with different levels and passes. And none of this is supported in clang, it's a huge annoyance tbh.

**Comment by kripken** [comment]
> wasm-opt may or may not be deterministic, afaik this is not documented in the binaryen repo.

It is deterministic (in fact we have a determinism fuzzer running constantly) but good point that it should be documented, I'll add that.

**Comment by zeux** [comment]
> I think I understand where you are coming from, and I think we do need to solve this, but I'm also wonder if there is precedent for clang doing this. For example, is this fundamentally different from clang calling the GNU linker (`/usr/bin/ld`) from the PATH? Do you consider that non-hermetic/non-deterministic too?

When using WASI SDK, the linker that gets invoked is invoked from WASI-SDK, and wasm-opt is invoked from the system, if installed system-wide, and not at all otherwise. That makes it different because the behavior of WASI-SDK depends on the presence or absence of externally installed and unrelated tool.

**Comment by sbc100** [comment]
I guess it doesn't solve the wider issue, but perhaps wasi-sdk should bundle a version of wasm-opt that clang could/should always prefer?

**Comment by ncruces** [comment]
I'd like to point out that it's not just wasting cycles, or non-determinism.

There are configs that the current system simply does not support, like my above example of producing an optimized binary with debug info, which is quite simply impossible with `wasm-opt` on the path.

**Comment by jeaiii** [comment]
> I think I understand where you are coming from, and I think we do need to solve this, but I'm also wonder if there is precedent for clang doing this. For example, is this fundamentally different from clang calling the GNU linker (/usr/bin/ld) from the PATH? Do you consider that non-hermetic/non-deterministic too?

@sbc100 I think calling the linker is different since it will fail if not found, can be skipped with -c, and is installed with llvm. If it ever chooses gnu over wasm-ld (how does it choose? what if that changes? wasm-ld is included with the clang that I use (wasm-opt was not), so do I have to worry it might call gnu if it happens to be installed, or am I safe there?) then I would say it is also non-hermetic which opens the door to being non-deterministic. clang does not fail if wasm-opt is not found, so how do I ensure it ran (or not) in a CI environment short of parsing the -v output? 

I am actively looking for a solution, as in literally today. Should I manipulate the path so clang can't find wasm-opt if it happens to exist? (how exactly does it find it?), or should I call each stage of the process directly (hopefully wasm-ld doesn't auto call wasm-opt)? Probably the later, but there goes our simple compile stage...as I'm only compiling one cpp

**Comment by sbc100** [comment]
clang with a wasm target will never call GNU ld (GNU ld has no wasm support so there would be no point).   I was only thinking of the default clang for desktop setup that does default to calling GNU ld (a tool which is not shipped with llvm or clang).

wasm-ld does not invoke wasm-opt, or any other binary, no.

I'm not denying there is problem here, just trying to understand that shape of it.

**Comment by jeaiii** [comment]
ah, I was wondering why it would ever call GNU ld for wasm. It is surprising that clang/llvm depends on GNU ld in this way for other platforms. I can see it from an tool evolution standpoint. Okay, so compile with -c, then call wasm-ld, and then wasm-opt if I want to. Thanks for the info.

**Comment by pelletier** [comment]
This confused me today as well. I was inspecting the line number extraction of inlined calls in our profiler. The dwarf ranges didn't make sense, but they worked in our CI. Eventually, I realized wasm-opt was being run when on the path, which was the case on my machine, but not on our build container.

In my opinion, wasm-opt should never be invoked by the driver. If folks want to use it, they can set it up as part of their build system. Not being able to produce correct wasm modules with `-O3 -g` if wasm-opt happens to be on the PATH of the build machine makes things needlessly difficult.

**Comment by julian-smith-artifex-com** [comment]
This issue is also causing problems with `--enable-bulk-memory`, as described here: https://github.com/pyodide/pyodide/issues/4048

**Comment by TerrorJack** [comment]
Sorry but it doesn't seem to me https://github.com/llvm/llvm-project/commit/89d5635f0a834e53ac5446c6d6ea38d9166b2a55 closes this ticket at all. `--keep-section` is *not* a way to opt-out the invocation of `wasm-opt` when `-O` is enabled!

**Comment by tlively** [comment]
@sbc100, did you mean to close this?

**Comment by tlively** [comment]
`-all` wouldn't be quite right because it would allow wasm-opt to introduce new uses of features that were not intended to be allowed. If we want wasm-opt to be able to do the right thing without specifically enabling features on the command line and without a target features section, we'll need to add a new flag to wasm-opt that lets it infer the allowed features from the input module.

**Comment by RReverser** [comment]
> `-all` wouldn't be quite right because it would allow wasm-opt to introduce new uses of features that were not intended to be allowed.

I thought it only affected validation?

If not, maybe `-n` (aka `--no-validation`) at least? Normally code produced by the linker should be valid anyway, so presumably validation isn't necessary, but it would allow cases like this one to pass.

**Comment by tlively** [comment]
It's not just validation. The features affect what optimizations are run and what the optimizations are allowed to do as well.

Skipping validation might help, but without e.g. the sign-ext feature being set, wasm-opt will not perform optimizations that introduce sign extension instructions. I wouldn't be surprised if some optimizations hit assertion failures if the features don't match the module, too.

**Comment by mh4ck-Thales** [comment]
I stumbled on this bug too. Having the behavior (and even the good working) of clang with frequently used flags such as `-g` or `-O` depend on the presence of `wasm-opt` on the machine, which is a binary unrelated to the LLVM project and not distributed with LLVM or LLVM-based toolchain such as `wasi-sdk` AFAIK, is a big problem. 

I believe that there are two problems here, that may be separated in two issues if you find it relevant. The first one is that clang compiling to Wasm and calling `wasm-opt` breaks some flags / features (`-g`, `-O`, and others). This issue can be tracked in https://github.com/llvm/llvm-project/issues/64909. The second one is that clang can use or not `wasm-opt` without any warnings and produce potentially different outputs, or that one may want to use `wasm-opt` with specific flags on the "clang without wasm-opt" output, and that can't be achieved right now. 

Regarding these two problems, I think that the easiest solution would be to remove the `wasm-opt` call for now, or at least put it behind an opt-in flag. But I don't know if that can be considered as a breaking change or a regression.

If removing the default call for `wasm-opt` is not possible, then add an opt-out flag so that the people having trouble with `wasi-opt` can just opt out without having to tweat their PATH or whatever. Also, add a warning / info message that tells the clang user if `wasm-opt` was used or not, and the exact path if so.

Once correct support for passing flags from clang to `wasm-opt` if implemented, and a way to distribute `wasm-opt` alongside LLVM (be it in `wasi-sdk` or somewhere else) is introduced, it can be added back as the default.

Finally, I'll put some questions here in order to better understand the situation around `wasm-opt` and maybe help taking future decisions:

- Why add `wasm-opt` in the clang driver in the first place? Shouldn't this work be done by llvm-opt directly?
- Is `wasm-opt` related to LLVM / a LLVM project in any way, or is it a completely external tool that was added in here for its interesting features?
- Can we implement `wasm-opt` interesting features directly into LLVM?

**Comment by kripken** [comment]
@mh4ck-Thales 

> Is wasm-opt related to LLVM / a LLVM project in any way, or is it a completely external tool that was added in here for its interesting features?

`wasm-opt` is part of [Binaryen](https://github.com/WebAssembly/binaryen#tools) and entirely separate from LLVM. It is an optimizer that can make wasm files smaller and faster (on LLVM output it typically helps by 15% or so).

> Can we implement wasm-opt interesting features directly into LLVM?

In theory yes, but it would be a large amount of both initial and ongoing effort, so I doubt it. That effort can't be deduplicated because from the wasm side it makes sense to add new optimizations in `wasm-opt` which is a standalone, modular tool that any toolchain can use (not only LLVM), which benefits the entire wasm ecosystem.

(Personally I agree with you on the main matter here that the current `clang` behavior is surprising, but I defer to `clang` people on how to fix that.)

**Comment by mh4ck-Thales** [comment]
@kripken thanks for the clarifications. I understand that technically, `wasm-opt` is a great addition to the `clang` workflow and greatly improves the final Wasm binary. I also get that most of the work addressing Wasm-specific optimizations are directly towards `wasm-opt` instead of the internal LLVM optimizer (which makes sense). This builds towards the argument of keeping `wasm-opt` and finding a way to distribute it alongside LLVM, as a third-party but necessary dependency. 

I'm curious though to know if there is any kind of overlap between LLVM optimization features and the ones of `wasm-opt`, and if that's the case is there an interest to try and avoid the overlap somehow to save time on big binaries (and if the benefit is worth the trouble).

I hope that we can all agree on a solution soon, and accept a patch accordingly.

**Comment by whitequark** [comment]
I've hit this issue a number of times recently. The two problematic outcomes for me were:

1. `wasm-opt` corrupts DWARF debug information, therefore making the backtraces useless.
2. Even on a non-LTO build, `wasm-opt` can take 10-20 minutes to complete on a recent laptop building for example Clang, which makes incremental workflows impossible.

**Comment by sunfishcode** [comment]
I'm also in favor of having a flag to disable wasm-opt. If someone could submit a patch, I'd review it.
