### ISSUE TITLE
some dkms modules are failing to compile with llvm-git

### ISSUE THREAD

**Issue by ptr1337** [llvm/llvm-project#55820]
Hey, 

Actually since llvm 15 has started to land into main, the issue was there. 
I did actually compile following commit: d951ca5439bb8726cfe1ceb2d12e220f29fe5125
llvm-14 and llvm-13 are fine. 

I did attached a make log from the nvidia-dkms module, which is failing.

[make.log](https://github.com/llvm/llvm-project/files/8818912/make.log)

Regards.

**Comment by tbaederr** [comment]
This is a change from @AaronBallman, but you might have to adjust the C standard used if you want to use clang 15.

**Comment by ptr1337** [comment]
> This is a change from @AaronBallman, but you might have to adjust the C standard used if you want to use clang 15.

Could you show me the commit, so I can revert this for my usage for now ?

**Comment by tbaederr** [comment]
I think it's 7d644e1215b376ec5e915df9ea2eeb56e2d94626 but I haven't tested if reverting that would fix your problem.

**Comment by AaronBallman** [comment]
Based on what I'm seeing in the log file attached, this is likely not a bug but due to behavioral changes in Clang to address a long-standing failure to appropriately handle functions without prototypes. These were never a best practice in ISO C as they were introduced as being deprecated into C89, and they were ultimately removed for C2x. This necessitated two changes: 1) start warning people more aggressively that they are using a deprecated feature and that their code *will* break when upgrading to the latest C standard, 2) Do the same for implicit function declarations; those were supported in C89 but removed in C99 (without deprecation) and they used a function without a prototype and thus would break in C2x.

You may also need to update your configure scripts to not rely on implicit function declarations. Some older scripts would use an implicit declaration to test for a feature, so the new diagnostic may cause them to report that a feature is not supported when it actually is.

**Comment by ptr1337** [comment]
I close it. Ive patched the KBUILD from nvidia and I got it working until thy sort their stuff out.
thanks for the help
