### ISSUE TITLE
Shouldn't emit "evstdd" for ppc32 and is the case for "-fpic"

### ISSUE THREAD

**Issue by UmeshKalappa0** [llvm/llvm-project#55857]
Please refer the sample @
https://godbolt.org/z/fdPj1Gb7f

because of this our unwinding is  restoring the invalid  R30 (GLOABL_OFFSET_TABLE) in the offset sp(32) and which is incorrect .
i.e
.cfi_offset r30, -32
   evstdd 30, 32(31)   

and why this redundant inst only for -fpic.

**Comment by UmeshKalappa0** [comment]
Was hoping the integrated assembler  (needs to be fixed ) to error out like readelf i.e

readelf -wf libexception_so.so.1  | grep bad
readelf: Error: Unfeasibly large register number: 1230
readelf: Error: Unfeasibly large register number: 1230
readelf: Error: Unfeasibly large register number: 1230
readelf: Error: Unfeasibly large register number: 1230
readelf: Error: Unfeasibly large register number: 1230
readelf: Error: Unfeasibly large register number: 1230
readelf: Error: Unfeasibly large register number: 1230
readelf: Error: Unfeasibly large register number: 1230
readelf: Error: Unfeasibly large register number: 1230
readelf: Error: Unfeasibly large register number: 1230
readelf: Error: Unfeasibly large register number: 1230
  DW_CFA_offset: bad register: r31 at cfa-4
  DW_CFA_offset: bad register: r30 at cfa-8
  DW_CFA_offset_extended: bad register: r1230 at cfa-32
  DW_CFA_offset: bad register: r31 at cfa-4
  DW_CFA_offset: bad register: r30 at cfa-8
  DW_CFA_offset_extended: bad register: r1230 at cfa-32
  DW_CFA_offset: bad register: r30 at cfa-8
  DW_CFA_offset_extended: bad register: r1230 at cfa-32
  DW_CFA_offset: bad register: r31 at cfa-4
  DW_CFA_offset: bad register: r30 at cfa-8
  DW_CFA_offset_extended: bad register: r1230 at cfa-32
  DW_CFA_offset: bad register: r31 at cfa-4
  DW_CFA_offset: bad register: r30 at cfa-8
  DW_CFA_offset_extended: bad register: r1230 at cfa-32
  DW_CFA_offset: bad register: r31 at cfa-4
  DW_CFA_offset: bad register: r30 at cfa-8
  DW_CFA_offset_extended: bad register: r1230 at cfa-32
  DW_CFA_offset: bad register: r31 at cfa-4
  DW_CFA_offset: bad register: r30 at cfa-8
  DW_CFA_offset_extended: bad register: r1230 at cfa-32
  DW_CFA_offset: bad register: r31 at cfa-4
  DW_CFA_offset: bad register: r30 at cfa-8
  DW_CFA_offset_extended: bad register: r1230 at cfa-32
  DW_CFA_offset: bad register: r31 at cfa-4
  DW_CFA_offset: bad register: r30 at cfa-8
  DW_CFA_offset_extended: bad register: r1230 at cfa-32
  DW_CFA_offset: bad register: r31 at cfa-4
  DW_CFA_offset: bad register: r30 at cfa-8
  DW_CFA_offset_extended: bad register: r1230 at cfa-32
  DW_CFA_offset: bad register: r31 at cfa-4
  DW_CFA_offset: bad register: r30 at cfa-8
  DW_CFA_offset_extended: bad register: r1230 at cfa-32

**Comment by nemanjai** [comment]
I am not sure why this is a problem. The way this was implemented from the start was that SPE registers are super-registers of GPR registers. So if a callee-saved GPR is modified, the corresponding SPE register needs to be spilled. With `-fpic`, the address of the GOT is placed into the LR and then moved into a GPR (r30 is selected as a callee-saved register is needed). So the spill of the SPE register r30 needs to happen.
The implementation seems a bit strange (since we spill r30 with `stw` as a 32-bit register and then again with `evstdd` as a 64-bit register).
This was all implemented by @chmeeedalf and I think he needs to chime in here in terms of what the ABI requires.

**Comment by chmeeedalf** [comment]
Saving with evstdd in addition to stw is a bug that I was never able to sort out.  Since r30 is used as a pointer in the ABI, it should not be treated as an SPE register.  This was happening with all registers, but I think someone else was able to fix spilling and only spill the SPE registers (still non-optimal, gcc would only save SPE registers when the upper register is needed).

**Comment by UmeshKalappa0** [comment]
@chmeeedalf  and @nemanjai 
>>gcc would only save SPE registers when the upper register is needed
This is something we are looking too and CFA encoding issue i.e "Error: Unfeasibly large register number: 1230"

**Comment by chmeeedalf** [comment]
> @chmeeedalf and @nemanjai
> 
> > > gcc would only save SPE registers when the upper register is needed
> 
> This is something we are looking too and CFA encoding issue i.e "Error: Unfeasibly large register number: 1230"

That error is due to the DWARF numbering of the SPE upper half identifiers.  Per the "Power Architecture 32-bit ABI supplicant", SPE high parts are DWARF numbers 1200-1231.  GCC and GDB map them internally to something sane.

**Comment by UmeshKalappa0** [comment]
Review raised :https://reviews.llvm.org/D127495
