### ISSUE TITLE
Warn when two headers have the same header guard.

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#5586]
|  |  |
| --- | --- |
| Bugzilla Link | [5214](https://llvm.org/bz5214) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |

## Extended Description 
I've often copied an existing header to start a new file, forgotten to update the header guard, and then been very confused when lots of declarations are missing. It'd be really nice if clang would warn about this.

**Comment by gwelymernans** [comment]
I don't think that will be feasible. It's not certain how we could identify between a header guard and code that simply `#ifdef`'s the file under specific conditions. It would probably be better to have editors auto-generate those guards when creating a new file (which mine does, because vim rules!).
