### ISSUE TITLE
Clang gives an error when using recursion in a concept

### ISSUE THREAD

**Issue by s2s-k** [llvm/llvm-project#55875]
MSVC: https://godbolt.org/z/M9YKEq6df
Clang: https://godbolt.org/z/rMM61PKKx

`error: use of undeclared identifier 'IsAnyType'`

I think the compiler gives this error for no reason, because "IsAnyType" has already been declared. Also, Microsoft's compiler compiles this code well.

**Comment by JoeLoser** [comment]
I think this is an MSVC bug. Note that GCC rejects the code as well. This is because you can't have recursive concepts. GCC and Clang are correct to reject this code, though the error message could be improved to state something to the effect of not allowing recursive concepts.

**Comment by s2s-k** [comment]
> BTW, there's no need for using recursion at all in this concept since we can use fold expressions. See https://godbolt.org/z/7YE483o5r for an example.

Yes, I know about fold-expressions. I noticed that it's possible to write this using a fold-expression after I originally wrote it.

> I think this is an MSVC bug. Note that GCC rejects the code as well.

But still, that moment seemed weird to me. I don't know what the standard says about it. But from my point of view, this code looks logical and should compile.

**Comment by JoeLoser** [comment]
> But still, that moment seemed weird to me. I don't know what the standard says about it. But from my point of view, this code looks logical and should compile.

"Looks logical" and "should compile" don't always overlap. :)

This [StackOverflow answer](https://stackoverflow.com/a/61921635/1289140) gives a good explanation of why it's not allowed. Additionally, instead of fold expressions, more generally speaking, concepts can be written in terms of type traits which can be recursive. See [this StackOverflow answer](https://stackoverflow.com/a/56741596/1289140) for an example.

**Comment by s2s-k** [comment]
> good explanation of why it's not allowed

The case they're talking about there is completely different than it is here. Recursion here is controlled with an expression in the ternary operator that will sometime become false. Consequently, infinity is out of the question. Also, the expression here is complete because the conditions are known at the time of compilation.

_Also, you can catch me on the point that the ternary operator is not a `constexpr` and so the last `IsAnyType` in the ternary operator will not have any arguments when unpacking the pattern, so the compiler should have given an error... But that's not true either. Since it is a `concept`, it's possible [to make "mistakes" in expression](https://godbolt.org/z/fb86G6eTT)._

**Comment by s2s-k** [comment]
@JoeLoser btw, what do you think of this code?

MSVC: https://godbolt.org/z/YvcPov3Te
Clang: https://godbolt.org/z/h9K7d61v8

`error: pack expansion used as argument for non-pack parameter of concept`

This mistake looks very ridiculous. Will someone explain to me what it means?

**Comment by shafik** [comment]
The original code is reject by clang/gcc/edg/MVSC: https://godbolt.org/z/rc49hEzcd now

The new example is rejected by gcc/clang and accepted by edg/MSVC: https://godbolt.org/z/jrs75nahY

Not sure who is correct, but we should probably open a second bug report for this since it looks like a different problem and does not look related to the original one.
