### ISSUE TITLE
clang-tidy incorrect hiccp-multiway-path-covered warning

### ISSUE THREAD

**Issue by kin4stat** [llvm/llvm-project#55885]
clang-tidy incorrectly handles the hiccp-multiway-path-covered

example code:
```cpp
if ((uMsg == WM_SYSKEYDOWN || uMsg == WM_KEYDOWN || uMsg == WM_LBUTTONDOWN || uMsg == WM_RBUTTONDOWN || uMsg ==
            WM_MBUTTONDOWN) == false) return ProcResultType::kNone;
// some code

switch (uMsg) { // potential uncovered code path; add default case[hiccp-multiway-path-uncovered]
case WM_SYSKEYDOWN:
case WM_KEYDOWN:
    // some code
    break;
case WM_LBUTTONDOWN:
   // some code
    break;
case WM_RBUTTONDOWN:
    // some code
    break;
case WM_MBUTTONDOWN:
    // some code
    break;
}
```

Version:
```
LLVM (http://llvm.org/):
  LLVM version 14.0.0
  Optimized build.
  Default target: x86_64-pc-windows-msvc
  Host CPU: alderlake
```

**Comment by kin4stat** [comment]
uMsg has a UINT type(windows api), but in this case it doesn't really matter, because the condition above checks all the necessary conditions before the switch. Also, clang-cl optimizes this design into one switch case with default case

here is MRE:
https://godbolt.org/z/Ez35j1dfE

**Comment by JonasToth** [comment]
Thanks for clarifying.

The check does not track the possible values of `uMsg` in your case, nor does it in any other case. The check is only concerned about the type of value and if the `switch` exhausts the possible values this type can hold. This is only possible with the static analyzer and not within clang-tidy checks.

Your godbolt example shows that quite well: `val` should be an `enum` with the macro values being the enumerators (at least under the hicpp coding standard and in idiomatic C++ as well). This makes the intention of code crystal clear, whereas the `unsigned` type leaves from for interpretation.

A way around this would be a `default` case that has `__builtin_unreachable();` or an equivalent method to show that this code path should not exist.
Otherwise, only silencing with `NOLINT` is possible.

IMHO this issue can not be resolved in `clang-tidy`. Tracking the early exit due to limiting to specific values and then using `switch` requires the static analyzer functionality and the check implements the coding standard. The `switch` statements are required to be exhaustive _on the type_.
I close the issue for now because of that. If you disagree or want to implement a similar version of the check in the static analyzer (or someone else), you could reopen or better make a new issue and reference it.
