### ISSUE TITLE
Lldb failed connect port (android)

### ISSUE THREAD

**Issue by SilasMo** [llvm/llvm-project#55954]
I currently dont have a pc. I have two rooted devices `Arm64` host device with Debian rootfs and the device to be debugged which contains the lldb-server binary `armv7`. I am trying to remote debug my android device using lldb. I pulled the `lldb-server` binary from àndroid ndk24 and put it in `/data/local/tmp`. Installed `Debian` `Sid` on `Another term` and `apt` installed `lldb`. 

I then wifi hotspoted the client device(one with `lldb-server`) using the host with the linux rootfs.

The commands i ran on server device
```shell
./data/local/tmp/lldb-server platform --listen "*:2000"  --server
```
Checked using `netstat` and the lldb-server had bound to all addresses(`0.0.0.0:2000`)

On host(client `lldb`) device in `debian sid` terminal i ran:
```shell
apt install lldb
lldb
platform select remote-android
platform connect connect://192.168.201.132:2000
```
Then i get `error failed connect port`.

I have used `Gdb` using the same machines on the same network and it worked nicely. I have tried installing `lldb` on `debian buster` but same result and even ran the `lldb-server` binary on the host(device with `debian sid`) but same result. Right now im stuck here. How do I solve this? 

Help will be greatly appreciated. Thank you.

**Comment by SilasMo** [comment]
This is output from lldb-server 
```
u0_a103@goyave3g:/ $ su
root@goyave3g:/ # cd /data/local/tmp
root@goyave3g:/data/local/tmp # .lldb-serverr
tmp-mksh: .lldb-serverr: not found
127|root@goyave3g:/data/local/tmp # ./lldb-server
Usage:
  ./lldb-server v[ersion]
  ./lldb-server g[dbserver] [options]
  ./lldb-server p[latform] [options]
Invoke subcommand for additional help
root@goyave3g:/data/local/tmp # ./lldb-server v
lldb version 12.0.9 (/buildbot/src/android/llvm-r416183/out/llvm-project/lldb revision c935d99d7cf2016289302412d708641d52d2f7ee)
  clang revision c935d99d7cf2016289302412d708641d52d2f7ee
  llvm revision c935d99d7cf2016289302412d708641d52d2f7ee
root@goyave3g:/data/local/tmp #
```

**Comment by mark2185** [comment]
I'm doing something similar, maybe it's the same issue, at least the symptoms are the same.

I _can_ connect to a `lldb-server` on a _local_ `android` device, I cannot do the same with a remote one whose `adb` port `5037` is forwarded to the local machine. 

Setup:
- local `linux` machine with `lldb version 14.0.6`
- remote `linux` machine (`docker` container)
  - port `22` is exposed
  - `adb` is started on port `5038`
  - an android device is connected to it ( visible through `adb -P 5038 devices`)

Steps to reproduce:
- on remote server:
  - `adb -P 5038 push ./lldb-server /data/local/tmp`
  - `adb -P 5038 shell /data/local/tmp/lldb-server v`
```
  version 14.0.1 (/buildbot/src/android/llvm-toolchain/out/llvm-project/lldb revision    8671348b81b95fc603505dfc881b45103bee1731)
  clang revision 8671348b81b95fc603505dfc881b45103bee1731
  llvm revision 8671348b81b95fc603505dfc881b45103bee1731
```
  -  `adb -P 5038 shell /data/local/tmp/lldb-server platform --listen "*:4444"`

- on local machine
  - `adb kill-server` (just to be sure)
  - `ssh -C -L5037:localhost:5038 user@remote-machine`
  - `adb devices` (prints out the correct device)
  - `lldb`
  - `lldb$> platform select remote-android`
  - `lldb$> platform connect connect://localhost:4444` (which works when running everything locally)
  - `error: Failed to connect to port`


**Note**: I started typing this up for the setup I had above, but I realised that I cannot even connect to the `lldb-server` from the `container` the `android device` is actually plugged into. 
So, exactly the same steps as I do locally, but I get `error: Failed to connect to port` (I even tried `adb forward tcp:4444 tcp:4444`, but to no avail, or using the `device serial ID` instead of `localhost`, but the result is the same)

I tried using the prebuilt `lldb-server` from `android studio` itself, both the `armeabi` and `arm64-v8a` binaries, but nothing changed.

What else can I provide?

**Comment by SilasMo** [comment]
@mark2185 Hi. Its been a long time since I opened the issue.

 Yes the `platform select remote-android` command is the one thats not openly documented enough as to how

**Comment by SilasMo** [comment]
Hi @mark2185 . Its been almost 2 years since i opened the issue but I finally solved it. 

The `remote-android` plugin is not well documented enough on how it really connects to the `lldb-server`. When you select the `remote -android` plugin, lldb connects to the adb server using port 5037 which in turn to the currently attached android device. This then requires the client machine to have adb installed and the adb server running on port 5037 during the entire debugging session  for all this to work.

I also got it to work on android using termux:

- install [LADB](https://play.google.com/store/apps/details?id=com.draco.ladb) app from playstore and allow it to run in background unrestricted battery in settings
- open LADB and connect it to you android device(check using `adb devices`)
- start `lldb-server` in platform mode in either android or adb shell e.g  `lldb-server p --server --listen "*:2000"`
- open `lldb` in termux and run continue normal remote debugging.
- `platform select remote-android` 
- `platform connect connect://127.0.0.1:2000`


Cheers

**Comment by SilasMo** [comment]
Hi @mark2185 . Its been almost 2 years since i opened the issue but I finally solved it. 

The `remote-android` plugin is not well documented enough on how it really connects to the `lldb-server`. When you select the `remote-android` plugin, lldb connects to the adb server using port 5037 which in turn to the currently attached android device. This then requires the client machine to have adb installed and the adb server running on port 5037 during the entire debugging session  for all this to work.

I also got it to work on android using termux:

- install [LADB](https://play.google.com/store/apps/details?id=com.draco.ladb) app from playstore and allow it to run in background unrestricted battery in settings
- open LADB and connect it to you android device(check using `adb devices`)
- start `lldb-server` in platform mode in either android or adb shell e.g  `lldb-server p --server --listen "*:2000"`
- open `lldb` in termux and continue normal remote debugging.
- `platform select remote-android` 
- `platform connect connect://127.0.0.1:2000`


Cheers

**Comment by mark2185** [comment]
Hey @SilasMo, I guess this is one of the issues I forgot to update - I managed to figure it out, a patch for setting the `gdbserver` and `platform` ports on the host's side (where the `android` device is plugged in) landed in `llvm17` so now you can go one (server) hop further if you need to.

I've posted a writeup [here](https://markusicluka.bearblog.dev/debugging-a-truly-remote-android-device/#fnref-6) if you're interested.

**Comment by dyglcc** [comment]
same issue when use lldb 19.1,adb forward worked well ,but use the ip direct failed

**Comment by SilasMo** [comment]
What I understood was for remote android debugging to work conditions are:

1. adb installed and running(i mean adb server started on port 5037) on the machine that has lldb client. **Specifically port 5037 no other**
2. adb client can be connected over tcpip on any port e.g 5555 or 5556.
3. start lldbserver om android on port e.g 2000 and forward that port to local via lldb
4. Now connect adb to the android device e.g `adb connect x.x.x.x:5555` and forward port 2000 to local
5. And `lldb platform select remote-android` and `platform connect://localhost:2000`


**NB ADB server should always run on port 5037 no other.**
