### ISSUE TITLE
The FP16C intrinsics shall be included in emmintrin.h

### ISSUE THREAD

**Issue by ackelcn** [llvm/llvm-project#55986]
Intel Intrinsics Guide introduces that the FP16C intrinsics are defined in `emmintrin.h`:
https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#othertechs=FP16C&expand=1711&ig_expand=2133

```h
__m128 _mm_cvtph_ps (__m128i a)
```

Synopsis

```h
__m128 _mm_cvtph_ps (__m128i a)
#include <emmintrin.h>
```

Instruction: `vcvtph2ps xmm`, `xmm`
CPUID Flags: FP16C

However, clang defines them in `immintrin.h`:

```h
#if !defined(_MSC_VER) || __has_feature(modules) || defined(__F16C__)
#include <f16cintrin.h>
#endif
```

It is strange when programmers read the intel manual, but cannot find them in the said .h file. Indeed, I notice that some programmers have to workaround this issue:
https://github.com/jack603047588/meigen/commit/5c642950a5d0232ebdfa6b460b4515e6e2b8828d

```c
#if defined(EIGEN_COMP_CLANG)
#if EIGEN_COMP_CLANG
  // Workaround for clang: The FP16C intrinsics for clang are included by
  // immintrin.h, as opposed to emmintrin.h as suggested by Intel:
  // https://software.intel.com/sites/landingpage/IntrinsicsGuide/#othertechs=FP16C&expand=1711
```

**Comment by phoebewang** [comment]
Thanks for reporting this. I think it's a problem of intrinsics guide rather than compiler. Only ICC supports the usage of  `#include <emmintrin.h>` https://godbolt.org/z/6P1Khzbjq
Since intrinsics guide has become the reference for several compilers, we should make the information more general. I'll close this and update intrinsics guide.
