### ISSUE TITLE
[lld/macho] LLD should force-load with -ObjC  when the library is passed via LC_LINKER_OPTION and explicitly

### ISSUE THREAD

**Issue by tapthaker** [llvm/llvm-project#56059]
Assuming that `main.o` has an `LC_LINKER_OPTION: -lfoo` as a load command and the library foo is written in Objective-C. 

Then the following command should import all `Objective-C` symbols in `libfoo.a`

```
lld main.o -ObjC -L <search-path>  -lfoo -o main
```

**Comment by tapthaker** [comment]
I am trying to fix this in https://reviews.llvm.org/D127941

**Comment by PRESIDENT810** [comment]
I encountered the same problem (see https://github.com/llvm/llvm-project/issues/56440) here. If -ObjC flag should be applied to libraries introduced by LC_LINKER_OPTION then my case can also be solved. However this seems to contradict to @int3's commit (https://reviews.llvm.org/D112756). I'm not sure which is correct behavior for lld. 

I inspected ld64's code a little bit, and personally I think ld64's behavior is to conform to options passed in command line:
In `InputFiles::addLinkerOptionLibraries`:
```cpp
ld::File* reader = this->makeFile(info, true);
ld::archive::File* archiveReader = dynamic_cast<ld::archive::File*>(reader);
```
And in `InputFiles::makeFile`:
```cpp
archOpts.forceLoadThisArchive	= info.options.fForceLoad;
archOpts.forceLoadAll			= _options.fullyLoadArchives();
archOpts.forceLoadObjC		= _options.loadAllObjcObjectsFromArchives();
```
It seems that the flags passed in command line do affect how libraries from LC_INKER_OPTION are loaded. If this is the right behavior, then mine case and @tapthaker 's case can be linked and run successfully.

**Comment by int3** [comment]
@PRESIDENT810 if you patch @tapthaker's diff, does it fix your build? My commit definitely mimics ld64's behavior for the test cases I added, so I think there's probably something more subtle going on

**Comment by PRESIDENT810** [comment]
> @PRESIDENT810 if you patch @tapthaker's diff, does it fix your build? My commit definitely mimics ld64's behavior for the test cases I added, so I think there's probably something more subtle going on

My apology. I misunderstood ld64's code. Actually all libs from LC_LINKER_OPTION goes into `InputFiles._searchLibraries`, which will be used when resolving undefined symbols; whereas what -ObjC affects are `InputFiles._inputFiles`, which will be used when we build initial atoms. That explains why ld64 behaves differently than lld. Because even though ld64 will add libraries from LC_LINKER_OPTION to `InputFiles._searchLibraries`, it will still add libraries from command line args it into `InputFiles._inputFiles` and load its members based on -all_load or -ObjC flag. lld does not distinguish libraries from LC_LINKER_OPTION and command line, so when a library is lazy-loaded from LC_LINKER_OPTION first, it will be saved in loadedArchives and prohibit the same library from command line being loaded, even with -all_load / -ObjC flag. Sorry for my previous misinterpretation!

I tried @tapthaker 's patch and it seemed to fail the test introduced by https://reviews.llvm.org/D128025. His implementation will save the lazy-loaded archive without -force_load flag in lazyLoadedArchives, and then save the one with -force_load flag in forceLoadedArchives, then force load symbols from this archive. This violates the test because
> If an archive has already been loaded w/o -force_load earlier in the command line, a later -force_load argument will not have an effect.
