### ISSUE TITLE
unable to lower constant ptrtoint of string literal for i386-linux: error: expected relocatable expression

### ISSUE THREAD

**Issue by andrewrk** [llvm/llvm-project#56400]
Reduction:

```llvm
source_filename = "test"
target datalayout = "e-m:e-p:32:32-p270:32:32-p271:32:32-p272:64:64-f64:32:64-f80:32-n8:16:32-S128"
target triple = "i386-unknown-linux-unknown"

%os.linux.io_uring_sqe = type { i8, i8, i16, i32, i64, i64, i32, i32, i64, i16, i16, i32, [2 x i64] }


@os.linux.io_uring.test.openat__anon_60060 = internal unnamed_addr constant [21 x i8] c"test_io_uring_openat\00", align 1
@0 = private unnamed_addr constant %os.linux.io_uring_sqe { i8 18, i8 0, i16 0, i32 -100, i64 0, i64 ptrtoint ([21 x i8]* @os.linux.io_uring.test.openat__anon_60060 to i64), i32 438, i32 524354, i64 858993459, i16 0, i16 0, i32 0, [2 x i64] zeroinitializer }, align 4
```

Reproduction:

```console
[nix-shell:~/Downloads/zig/build-release]$ ~/local/llvm14-debug/bin/clang -c reduced.ll -target i386-linux-unknown
<unknown>:0: error: expected relocatable expression
error: cannot compile inline asm
1 error generated.
```

Confirmed that it occurs in:
 * LLVM 13.0.1
 * LLVM 14.0.6

Downstream issue: https://github.com/ziglang/zig/issues/12014

**Comment by andrewrk** [comment]
This also reproduces for 32-bit ARM.

**Comment by BertalanD** [comment]
Smaller reduction:

```llvm
target triple = "i386-unknown-linux-unknown"

@str = internal unnamed_addr constant [4 x i8] c"foo\00", align 1
@strAddr = internal unnamed_addr constant i64 ptrtoint ([4 x i8]* @str to i64)
```

Assigning an address to a 64-bit constant value on a 32-bit platform translates to the following directive in assembly:
```asm
.quad	str&4294967295
```

This is not a relocatable expression because of the bitwise and. Removing it from the assembly file manually leads to us crashing here:
https://github.com/llvm/llvm-project/blob/3decc2f04d63d924239acf739144a5f0e9119c70/llvm/lib/Target/X86/MCTargetDesc/X86ELFObjectWriter.cpp#L232-L237

The ideal solution would likely be to emit assembly code like this when pointers are zero-extended in constant expressions:
```
.long str
.long 0
```

**Comment by nikic** [comment]
I'm not sure we want to support this, because it would require blessing zext as a relocatable expression, which is not aligned with current direction.

The "bag of bytes with relocations" representation for this constant would be something along the lines of `{ ptr @str, i32 0 }`, which should be about how Rust emits it (probably with `i32 0` replaced by `[4 x i8] zeroinitializer`.)

**Comment by andrewrk** [comment]
@nikic I am satisfied with this, however, can the issue then be to have proper error reporting? As is, the current error message does not tell where the problem is in the LLVM IR. I had to use llvm-reduce to find the problem.

**Comment by nikic** [comment]
@andrewrk That should be possible. We currently have this odd bit of code in `lowerConstant()`:
https://github.com/llvm/llvm-project/blob/31049b3d2bcf01ed9b4cc83494899d16d0d9a7ff/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp#L2813-L2818
Which doesn't make a whole lot of sense if we don't support `and` as a relocatable expression. Possibly we can error directly at that point.

**Comment by nikic** [comment]
I've put up https://reviews.llvm.org/D130366 for the better error reporting.
