### ISSUE TITLE
ML pretrained models are insufficiently opensource.

### ISSUE THREAD

**Issue by Hello1024** [llvm/llvm-project#56432]
A build of LLVM with the ML optimizations enabled will by default include pretrained machine learning models made by Google:

https://github.com/llvm/llvm-project/blob/main/llvm/lib/Analysis/CMakeLists.txt#L8

That URL will be downloaded and included in the binary.

For a FOSS project, it's important that compiled-in files also meet the letter and spirit of the license, and it appears that unfortunately (and perhaps unintentionally) this file doesn't meet that test.

Specifically, it's a binary file built with an unpublished method, using closed source code operating on a closed source dataset.  There is available an open source tool, but this file is not produced with it, and it does not produce files with comparable performance.

Details here:
https://github.com/google/ml-compiler-opt/releases/tag/inlining-Oz-v1.1

Calling on LLVM maintainers (and the code author, @jacob-hegna ) to decide the correct course of action to take next.

**Comment by mtrofin** [comment]
Thanks for pointing this out, this was an oversight, sorry.

To make sure I understand: 1) you set the cmake option `TENSORFLOW_AOT_PATH` to wherever the `tensorflow` pip package is installed, and 2) also specified `LLVM_INLINER_MODEL_PATH` (and/or `LLVM_RAEVICT_MODEL_PATH`) to `"download"` - because in the absence of 2, the default behavior is to generate a for-test only model (using a checked in script and no corpus)

When setting either of those to 'download', we download a model from a URL. The URL needs to be specified via `LLVM_INLINER_MODEL_CURRENT_URL` or `LLVM_RAEVICT_MODEL_CURRENT_URL` respectively. If those URLs are not specified, by default we pick those reference models you mentioned.

We should probably not have those URLs default to anything. Currently, projects like Fuchsia generate their own model (using their own corpus and the tools at https://github.com/google/ml-compiler-opt); I guess we could link Fuchsia's models - they'd have the desirable properties (published method, from open source code and corpus); the thinking is that other projects would want to do something similar to Fuchsia, and the zipped models are there as a convenience / reference only.

Interim, I'll send a patch shortly to remove the default. Thanks again for pointing this out!

**Comment by Hello1024** [comment]
I personally still really support having the closed source model made freely available by the way, especially while it outperforms opensource ones, and I think it might be appropriate to have the URL in there as an option for a user to choose, as long as they are aware that it isn't FOSS.

Looking for maintainers opinions here - I'm just an unrelated party....

**Comment by mtrofin** [comment]
Agreed - the closed source models continue being available, I think the important thing is not automatically defaulting to them. (https://reviews.llvm.org/D129342). Folks wishing to use them may do so; and we can subsequently offer FOSS-friendly defaults (like I mentioned, the Fuchsia inlining one is readily available for example)

**Comment by dtcxzyw** [comment]
Fixed by 24c6c3527089ad1a02390fcef339f34adacb2686.
