### ISSUE TITLE
const volatile variables are placed in the wrong section

### ISSUE THREAD

**Issue by jemarch** [llvm/llvm-project#56468]
Hello.

clang version 15.0.0 (https://github.com/llvm/llvm-project.git d3dd6e57fe84e90cadcdc78fa71d632f6573f156) places  `const volatile' variables like:

  const volatile int foo = 0;

in the .rodata section.  According to the C18 specification[1]:

  6.7.3 Type qualifiers / 5 The properties associated with qualified
  types are meaningful only for expressions that are lval-values [note
  135]

  135)The implementation may place a const object **that is not
  volatile** in a read-only region of storage. Moreover, the
  implementation need not allocate storage for such an object if its 
  address is never used.

Accordingly, GCC places such variables in the .data section.

Note that this is causing practical difficulties: the kernel's bpftool is generating different skeleton headers for BPF code compiled from LLVM and GCC, because the names of the containing sections get reflected.  For details on this please see [2].

Thanks!

[1] https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2310.pdf
[2] https://lore.kernel.org/bpf/87fsj8vjcy.fsf@oracle.com/T/#me726127e166f97fd50f09b647a604f176f809c63

**Comment by jemarch** [comment]
ping

**Comment by jemarch** [comment]
ping^2

**Comment by nickdesaulniers** [comment]
cc @AaronBallman @erichkeane

**Comment by AaronBallman** [comment]
The footnote cited isn't a normative requirement (I can't see any normative requirements that say we can't put a `const volatile` object into a read only section), so it's debatable just how much of a bug this is from a standards conformance perspective. I will have to inquire on the WG14 reflectors to see if there's something I've missed but I believe that C17 6.7.3p5 is meant to point out that only lvalue are qualified; rvalues are not because lvalue conversion strips the qualifiers. I think the footnote is mostly a nod towards the fact that `volatile` qualified objects may change their value in ways unknown to the compiler so storing it in a read-only section of memory is a bit questionable. But I'm curious if the committee tells me I've missed something there.

However, interop with GCC may be compelling enough on its own. While poking around, I came up with: https://reviews.llvm.org/D131012

**Comment by anakryiko** [comment]
This will break many BPF applications (see https://reviews.llvm.org/D131012#3695110). I also elaborated a bit on systemd issue that triggered this discussion (https://github.com/systemd/systemd/pull/24164#issuecomment-1203207372). We very explicitly rely on `const` variables being in .rodata section. We use `volatile` to prevent compiler optimizations with inlining variable value in the code, because in BPF app's use these constant values are provided from user-space before BPF programs are "finalized" and loaded into kernel.

So if there are no violation here, please consider not changing these. We'd rather BPF backend for GCC to use this convention (if they are unwilling to change it across all architectures).

**Comment by jemarch** [comment]
@AaronBallman Thanks for looking into this.  A clarification from WG14 would be useful indeed.

**Comment by AaronBallman** [comment]
I've asked on the WG14 reflectors and will report back once I hear something.

However, I'm a bit confused about the report now that I look at the assembly generated instead of the LLVM IR: https://godbolt.org/z/9sEnfMjYK  That sure looks like Clang and GCC are both putting `ConstVolatile` into the same section as `NonConst`.

**Comment by jemarch** [comment]
I see in that output that for GCC:

  .globl ConsVolatile
  .data
  [...]

i.e. ConstVolatile is defined in .data, not .rodata.

**Comment by AaronBallman** [comment]
Oohhhhhh! TIL how to read that. I thought each variable would specify `.section` specifically, I didn't realize they were a running list of options. Thanks! :-) (FWIW, it took me a while to realize I needed to read from the bottom up, too.)

**Comment by jemarch** [comment]
At first read I also missed the `.data' and was like wtf.  It is easy to miss :)

**Comment by AaronBallman** [comment]
The responses I've been getting back on the WG14 reflectors are not indicating that there's any normative requirement. It sounds like the sentiment is generally that the footnote is trying to tell you that objects which are `const` qualified but not `volatile` qualified can be assumed to not change value. Based on that sentiment from the committee, we're under no obligation to make a change here for conformance to C.

**Comment by jemarch** [comment]
Ok, this is very good to know.  Thanks for checking.

I will convey this info to the other GCC developers in [1]  and see if we can reach consensum.  No normative obligation + one known breaking platform (BPF) is enough reason for me to push for a change in GCC.

[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=25521

**Comment by jemarch** [comment]
FYI
https://gcc.gnu.org/pipermail/gcc-patches/2022-August/599348.html

**Comment by jemarch** [comment]
The patch is now in GCC, and now both compilers behave the same way regarding `const volatile' objects:

https://gcc.gnu.org/pipermail/gcc-patches/2022-September/602501.html

So I am closing this issue.
