### ISSUE TITLE
[SystemZ] What 'funnel' double shifts does SystemZ support?

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#56495]
I'm still looking at the SystemZ regression in D77804 - and it might be useful for shift expansion if we lowered to funnel shifts.

I can't find an ISA document describing them but I noticed that SystemZ has 'SLDL' and 'SRDL' FR128 opcodes that MIGHT be i64 double shifts of some kind?

CC @uweigand @JonPsson

**Comment by uweigand** [comment]
You can find the ISA docs here for example:
https://linux.mainframe.blog/zarchitecture-principles-of-operation/

SLDL and SRDL are 128-bit shifts on pairs of i64 registers.    Not sure how this is related to D77804, though - the one regression I've looked at there is code that is just a no-op in the end and should simply be optimized out completely?

**Comment by RKSimon** [comment]
Its one of many things I've been trying, not to generate funnel shifts as final codegen but create more complex nodes that avoid multiple uses of some values.

Its very annoying as until very recently that regressed codegen was horrible, but a earlier patch in this series managed to get lucky and give decent code.

**Comment by uweigand** [comment]
> SLDL and SRDL are 128-bit shifts on pairs of i64 registers

Sorry, that is actually incorrect - I didn't check and misremembered.  Those two instructions actually perform **64-bit** shifts, it's just that those 64 bits are split across two registers.  These instructions were used to perform 64-bit shifts back in the days when we had only 32-bit general purpose registers - today you'd never use them since we have 64-bit single-register shift instructions instead.

There is no corresponding 128-bit register pair shift instruction.  The only way to directly get a 128-bit shift would be in a vector register via the vector instruction set.

**Comment by RKSimon** [comment]
Thanks @uweigand - I'm going to add test coverage on systemz for the funnel shift intrinsics just to keep track of the codegen quality, but I don't think this is going to help D77804
