### ISSUE TITLE
the "operator delete" selection does not follow c++ spec

### ISSUE THREAD

**Issue by chumarshal1** [llvm/llvm-project#56505]
```cpp
/*
 * (c) Copyright 2017-2019 by Solid Sands B.V.,
 *     Amsterdam, the Netherlands. All rights reserved.
 *     Subject to conditions in the RESTRICTIONS file.
 */
#include <cstddef>
#include <iostream> 

class My_Class 
{
public:
    int a;
    int b;
    ~My_Class(){};
};

void operator delete[]( void* ptr                   ) noexcept {
    std::cout << "====delete with 1 parameters======" << std::endl;
    ::operator delete(ptr);
}

void operator delete[]( void* ptr, std::size_t size ) noexcept {
    std::cout << "====delete with 2 parameters======" << std::endl;
    ::operator delete(ptr);
}

int main()
{
   My_Class* pobj = new My_Class[2];
   delete[] pobj;
}

```

```console
# The clang result is:
====delete with 1 parameters======
# But gcc result is:
====delete with 2 parameters======
```

I think clang does not follow c++ spec as follow: 
https://cplusplus.github.io/CWG/issues/1788.html

**Comment by shafik** [comment]
If I understand correctly clang does not support this by default but we use `-fsized-deallocation` to enable this. See the discussion in [C++14: Disable sized deallocation by default due to ABI breakage](https://reviews.llvm.org/D8467).

Although it looks like enabling this by default is being worked on in [Enable sized deallocation by default in C++14 onwards](https://reviews.llvm.org/D112921) but from the last update there are some challenges.

**Comment by h-vetinari** [comment]
Now that https://github.com/llvm/llvm-project/pull/90373 landed, this can probably be closed?
