### ISSUE TITLE
`reverse_iterator::iterator_concept ` should not use `__is_cpp17_random_access_iterator`

### ISSUE THREAD

**Issue by hewillk** [llvm/llvm-project#56504]
https://github.com/llvm/llvm-project/blob/a17c90daf2e7c3b1817ec29ad6648ce89b927f9a/libcxx/include/__iterator/reverse_iterator.h#L72-L75
It should be `random_access_iterator` right?

```cpp
#include <ranges>

using I = std::ranges::iterator_t<decltype(std::views::iota(0, 1))>;
using C = std::reverse_iterator<I>::iterator_concept;
static_assert(std::same_as<C, std::random_access_iterator_tag>);
```
https://godbolt.org/z/913YbbGfj

**Comment by dwblaikie** [comment]
sounds right (ie: the bug sounds correctly diagnosed/described and a code change is required to fix libc++) to me

**Comment by dwblaikie** [comment]
Hmm, actually, maybe not? According to cppreference:
```
iterator_concept | If Iter models std::random_access_iterator, this is std::random_access_iterator_tag. Otherwise, this is std::bidirectional_iterator_tag
```

Maybe cppreference is wrong? Not sure.


Yeah, at least N4860 version of C++20 seems to align with that ^:
"The member typedef-name iterator_concept denotes
(1.1) — random_access_iterator_tag if Iterator models random_access_iterator, and
(1.2) — bidirectional_iterator_tag otherwise."

**Comment by dwblaikie** [comment]
Oh, sorry, I think I'm just all around a bit confused. Ignore those comments... no doubt someone else has more context here.
