### ISSUE TITLE
llvmlite build.sh fails at benchmark_register

### ISSUE THREAD

**Issue by sirfz** [llvm/llvm-project#56511]
Apologies for the lack of details (didn't copy the error message) but the error had something to do with "numeric_limits" not being part of stdlib.

OS: Ubuntu 22.04
g++: (Ubuntu 11.2.0-19ubuntu1) 11.2.0

Fixed it by adding
```
include <limits>
```
in `utils/benchmark/src/benchmark_register.h`

~~I can submit a PR if that's a proper fix.~~

Edit: the file isn't part of the source so not sure where it's generated and whether it's part of llvm or llvmlite (please close if irrelevant)

**Comment by ZhongRuoyu** [comment]
You probably have run into this error, while building LLVM 11 or earlier:

```plaintext
In file included from /usr/src/llvm-project/llvm/utils/benchmark/src/benchmark_register.cc:15:
/usr/src/llvm-project/llvm/utils/benchmark/src/benchmark_register.h: In function 'void AddRange(std::vector<T>*, T, T, int)':
/usr/src/llvm-project/llvm/utils/benchmark/src/benchmark_register.h:17:30: error: 'numeric_limits' is not a member of 'std'
   17 |   static const T kmax = std::numeric_limits<T>::max();
      |                              ^~~~~~~~~~~~~~
/usr/src/llvm-project/llvm/utils/benchmark/src/benchmark_register.h:17:46: error: expected primary-expression before '>' token
   17 |   static const T kmax = std::numeric_limits<T>::max();
      |                                              ^
/usr/src/llvm-project/llvm/utils/benchmark/src/benchmark_register.h:17:49: error: '::max' has not been declared; did you mean 'std::max'?
   17 |   static const T kmax = std::numeric_limits<T>::max();
      |                                                 ^~~
      |                                                 std::max
In file included from /usr/include/c++/11/algorithm:62,
                 from /usr/src/llvm-project/llvm/utils/benchmark/include/benchmark/benchmark.h:175,
                 from /usr/src/llvm-project/llvm/utils/benchmark/src/internal_macros.h:4,
                 from /usr/src/llvm-project/llvm/utils/benchmark/src/check.h:8,
                 from /usr/src/llvm-project/llvm/utils/benchmark/src/benchmark_register.h:6,
                 from /usr/src/llvm-project/llvm/utils/benchmark/src/benchmark_register.cc:15:
/usr/include/c++/11/bits/stl_algo.h:3467:5: note: 'std::max' declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
```

The file was not generated; if you checkout branch `release/11.x`, you will find the file at [`llvm/utils/benchmark/src/benchmark_register.h`](https://github.com/llvm/llvm-project/blob/release/11.x/llvm/utils/benchmark/src/benchmark_register.h). The missing `#include` was later fixed in commit b498303066a63a203d24f739b2d2e0e56dca70d1 and made available from release 12 on. So, you may directly apply this patch to your source:

```bash
wget -O- "https://github.com/llvm/llvm-project/commit/b498303066a63a203d24f739b2d2e0e56dca70d1.patch" | git apply
```

As for why this header can no longer be found at `llvm/utils/benchmark/src/benchmark_register.h`: it was later moved to [`third-party/benchmark/src/benchmark_register.h`](https://github.com/llvm/llvm-project/blob/main/third-party/benchmark/src/benchmark_register.h), in commit c6f7b720ecfa6db40c648eb05e319f8a817110e9. As you can tell from the commit message, this was because there were duplicated copies of the same library the source tree, used by llvm and libcxx respectively.
