### ISSUE TITLE
Get message from clang-tidy when use [[maybe_unused]] variable. 

### ISSUE THREAD

**Issue by dasfex** [llvm/llvm-project#56586]
Let check out this code:
```cpp
int f([[maybe_unused]] int n) {
  return n;
}
```
If ```n``` was unused and not market with ```[[maybe_unused]]``` attribute, there is a good action to point on this. 
But if ```n``` used and marked with this attribute you only pollute code with this attribute. So it can be removed. 
My point is that we should have one from two states: 
- unused variable with attribute;
- used variable without attribute.

**Comment by njames93** [comment]
One of the motivating reasons for the `maybe_unused` attribute is for suppressing warnings that are build dependent, like asserts.
Based on build configurations the variable could either be used or unused.
Because clang-tidy can't see all possible build configurations, we can't confidently know whether the variable is actually unused for certain configurations.
For this reason we shouldn't be removing this attribute.
