### ISSUE TITLE
flag set from SVE svwhilelt intrinsic not reused in loop

### ISSUE THREAD

**Issue by yuyichao** [llvm/llvm-project#56591]
Ref gcc bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106340

The LLVM sve autovectorizer does not seem to be emitting VLA style code so I can't directly compare manually written code to automatically vectorized code like in the gcc bug report. At least the code emitted for the manual version are similar.

I expect the following code to be compiled to efficient vla style assembly code
```c++
void set2(uint32_t *__restrict__ out, size_t m)
{
    auto svelen = svcntw();
    auto v = svdup_u32(1);
    if (m != 0) {
        auto pg = svwhilelt_b32(0ul, m);
        for (size_t i = 0; i < m; i += svelen, pg = svwhilelt_b32(i, m)) {
            svst1(pg, &out[i], v);
        }
    }
}
```

And the code LLVM emits is
```asm
        cbz     x1, .LBB1_3
        mov     x8, xzr
        cntw    x9
        whilelo p0.s, xzr, x1
        mov     z0.s, #1
.LBB1_2:
        st1w    { z0.s }, p0, [x0, x8, lsl #2]
        add     x8, x8, x9
        whilelo p0.s, x8, x1
        cmp     x8, x1
        b.lo    .LBB1_2
.LBB1_3:
        ret
```

which is almost identical to the gcc autovectorized code (since the c++ source is written this way...) except that the `cmp` and `b.lo` can simply be replaced with a conditional branch using the result of the `whilelo` instruction.

In the longer term, I would also expect source code like the following to work as well

```c++
void set3(uint32_t *__restrict__ out, size_t m)
{
    auto svelen = svcntw();
    auto v = svdup_u32(1);
    for (size_t i = 0; i < m; i += svelen) {
        auto pg = svwhilelt_b32(i, m);
        svst1(pg, &out[i], v);
    }
}
```

Currently, the loop transformation splits the cmp and the pairing whilelt making the flag from whilelt unusable.

**Comment by sdesmalen-arm** [comment]
> The LLVM sve autovectorizer does not seem to be emitting VLA style code so I can't directly compare manually written code to automatically vectorized code like in the gcc bug report

The LLVM Auto-vectorizer emits VLA style code, but uses a different style. It favours an unpredicated-vector body loop + scalar epilogue over having a single predicated vector body loop. Using a single predicated loop is possible but not yet enabled by default. We're currently working to make that a default. See https://godbolt.org/z/Y6rs8fYPf for example, where it gets enabled through a command-line flag.

> [...] the cmp and b.lo can simply be replaced with a conditional branch using the result of the whilelo instruction

For your ACLE example, if you want it to use the result from the `whilelo` to avoid the `cmp`, why don't you just write your loop differently so that it matches your intent, i.e.:
```
  svbool_t pg;
  for (size_t i = 0; svptest_first(svptrue_b32(), pg = svwhilelt_b32(i, m)); i += svelen)
    svst1(pg, &out[i], v);
```
That will remove the redundant compare and use the condition flags from the whilelo to branch back/out of the loop.

Just note that at the moment there is a bug where we emit a redundant `ptest` instruction after the `whilelo`, but we have two patches to fix that ([D129851](https://reviews.llvm.org/D129851) and [D129852](https://reviews.llvm.org/D129852)).

**Comment by paulwalker-arm** [comment]
As @sdesmalen-arm's example shows, the way the ACLE enables predicate based control flow is through the use of the svptest builtins.  Whereby the compiler will figure out based its operands whether an actual ptest instruction is required.

**Comment by yuyichao** [comment]
Thanks. I can confirm that using the ptest intrinsic creates the right code (and in fact in this case is correctly skipping the ptest instruction for me). I somehow only found the assembly guide and the list of acle intrinsics before this so I didn’t know what the expected source code patterns is.

The syntax is still a bit harder to read than the alternative IMO but I guess thats more on ARM than compilers…
