### ISSUE TITLE
[Flang] Intrinsic: selected_real_kind not yet implemented

### ISSUE THREAD

**Issue by UsmanNadeem** [llvm/llvm-project#56600]
Looks like it should be supported in F90+ ( https://gcc.gnu.org/onlinedocs/gfortran/SELECTED_005fREAL_005fKIND.html )
Source code I am trying to compile: https://github.com/numpy/numpy/blob/main/numpy/f2py/tests/src/kind/foo.f90

**Comment by PeixinQiao** [comment]
Thanks for the issue. I am working on it. Patch will come soon this week.

**Comment by PeixinQiao** [comment]
https://reviews.llvm.org/rG57e3fa38154309308b928dc13ef1181e7eb3e19a

Please try with current main for your application. @UsmanNadeem

**Comment by UsmanNadeem** [comment]
@PeixinQiao 

The code builds fine but it looks like the runtime output is incorrect.

I haven't had time to investigate it yet but I am attaching output, let me know what you think:

```
FAILED numpy/f2py/tests/test_kind.py::TestKind::test_all - AssertionError: selectedrealkind(0): expected 4 but got 2

E           AssertionError: selectedrealkind(0): expected 4 but got 2
E           assert 2 == 4
E            +  where 2 = <fortran function selectedrealkind>(0)
E            +  and   4 = selected_real_kind(0)
```

**Comment by PeixinQiao** [comment]
The result is expected. https://github.com/llvm/llvm-project/blob/main/flang/docs/IntrinsicTypes.md. This is because `real(2)` is supported in F18.

But there is compitability issue for this. There are some workloads getting `real(4)` from `selected_real_kind(0)`. I will post this to the F18 community on slack for discussion.

@UsmanNadeem You can skip this error by changing the code from `selected_real_kind(0)` into `selected_real_kind(4)` for now.

**Comment by PeixinQiao** [comment]
According to the discussion in the community, the expected result of `selected_real_kind(0)` is 2. The other compilers such as `gfortran` or `ifort` output `4` since they don't support `real(2)`. The `real(2)` should be supported according to the Fortran 2018 standard. There is another solution provided by Peter and I quote as `If the user code just wants to find the default kind of REAL, KIND(0.) is the portable correct solution.`.

**Comment by klausler** [comment]
Closing, as the concern was resolved without further response.
