### ISSUE TITLE
llvm build crash

### ISSUE THREAD

**Issue by frank-pian** [llvm/llvm-project#56792]
Description:
The GCC compilation process crashes.
![crash](https://user-images.githubusercontent.com/8214804/181698336-9a1999b8-7676-4ab7-bda1-9d9e02634e75.gif)

Version: 
ubuntu 22.04
cmake 3.22.1
gcc 11.2.0
LLVM 14.0.6

Step:
1. cmake -DCMAKE_BUILD_TYPE="Debug" -DLLVM_INCLUDE_BENCHMARKS=OFF ..
2. make -j8

**Comment by BertalanD** [comment]
Building LLVM (and most other things) with debug info is quite resource hungry. To me, it looks like you ran out of memory while linking. I've found that some of these might help:
- Build with `-DCMAKE_BUILD_TYPE=RelWithDebInfo` or `Release`. This will produce smaller object files, so you won't run out of memory easily; but is slower to compile.
- Use the LLD linker, which generally has a lower memory footprint: `-DLLVM_USE_LINKER=lld`.
- Use Ninja instead of make (pass `-GNinja` to CMake), which supports limiting the number of link jobs that run concurrently: `-DLLVM_PARALLEL_LINK_JOBS=1`.
- If you do want to enable debug information: `-DLLVM_USE_SPLIT_DWARF=ON`
- 
More information: https://llvm.org/docs/GettingStarted.html#common-problems

**Comment by fhahn** [comment]
Thanks @BertalanD! This is unlikely to be an issue in LLVM.
