### ISSUE TITLE
[clang-tidy] cert-dcl58-cpp crashes with friend declaration

### ISSUE THREAD

**Issue by VReichelt** [llvm/llvm-project#56902]
Running the `cert-dcl58-cpp` check with the following code crashes clang-tidy:

```cpp
struct A
{
  friend struct B;
};

struct B;

template<typename> struct T {};

T<B> b;
```

Here's the corresponding stack trace:
[Stacktrace.txt](https://github.com/llvm/llvm-project/files/9250727/Stacktrace.txt)

The crash happens since a week or two.

**Comment by VReichelt** [comment]
Most likely caused by commit 0e95921bc303a206cc6ae1c21ee90ec223bf9e78

**Comment by balazske** [comment]
The problem is likely a bug in AST matcher or other code, not in the checker.

**Comment by njames93** [comment]
> The problem is likely a bug in AST matcher or other code, not in the checker.

The stack trace says that the crash happened during AST matching. So the likely culprit is the new matcher added in the aforementioned patch. Though only a debug build would confirm that.

**Comment by balazske** [comment]
The new matcher reveals an existing problem in ASTMatcher or clang code. An AST matcher should not cause a crash. The problem is related to how the record type in `FriendDecl` is stored in the AST, or how the `ParentMapContext` is populated (https://discourse.llvm.org/t/ast-parent-of-class-in-a-friend-declaration/64275). In the example code, if line `struct B` (line 6) is moved to the first line, the crash do not happen.

**Comment by njames93** [comment]
The stack trace says that the crash occured in the new matcher, hasAnyTemplateArgumentIncludingPack, added in the aforementioned patch. Though you are correct that the root cause is the handling of a friend declaration not having a parent node.

**Comment by balazske** [comment]
https://reviews.llvm.org/D131686 adds the example code here to the tests. The parent revision D131685 is a fix for the problem.

**Comment by balazske** [comment]
Problem is fixed, test was added.
