### ISSUE TITLE
Backport ORC patches for silencing warnings when building for Windows to 15.x

### ISSUE THREAD

**Issue by mstorsjo** [llvm/llvm-project#56918]
The commits "[ORC] Fix a warning about an unused variable on Windows. NFC." and "[ORC] Actually propagate memory unmapping errors on Windows" both fix warnings and also fixes a case where errors aren't propagated properly.

**Comment by mstorsjo** [comment]
/cherry-pick 46196db4d305267a5d53ee642debaf408b0821a9 46bc1b5689e417d870c57a8d16044a55549673fa

**Comment by weliveindetail** [comment]
@mstorsjo Interesting. I wonder why we didn't see them when the original patch landed on mainline: https://reviews.llvm.org/D128544 There was some back-and-forth due to platform issues, but we didn't find these specific warnings. Aren't regular Windows bots running with `-Werror`?

Thanks for fixing that!

**Comment by mstorsjo** [comment]
> @mstorsjo Interesting. I wonder why we didn't see them when the original patch landed on mainline: https://reviews.llvm.org/D128544 There was some back-and-forth due to platform issues, but we didn't find these specific warnings. Aren't regular Windows bots running with `-Werror`?

I think the regular Windows bots only build with MSVC (and I don't know if `-Werror` or the MSVC equivalent `/WX` is enabled in that configuration) - I ran into these warnings with Clang. I tried to have a look at the buildbot logs, and I saw some rebuilds of those files that didn't trigger warnings, so I presume that MSVC doesn't warn about it.
