### ISSUE TITLE
Dynamic initializers not optimized away when using #pragma init_seg

### ISSUE THREAD

**Issue by zmodem** [llvm/llvm-project#56922]
Consider:

```console
$ cat /tmp/a.cc
#pragma init_seg(lib)

struct S {
  S(int x) : x_(x) {}
  int x_;
};

S s{42};

$ clang -target i686-pc-win32 -O2 -S -emit-llvm -o - /tmp/a.cc
```

With the `pragma` commented out, Clang will optimize the initialization of `s`:

```llvm
@"?s@@3US@@A" = dso_local local_unnamed_addr global %struct.S { i32 42 }, align 4
```

but with the `pragma` intact, it gets initialized dynamically:

```llvm
@"?s@@3US@@A" = dso_local local_unnamed_addr global %struct.S zeroinitializer, align 4
@__cxx_init_fn_ptr = private constant ptr @"??__Es@@YAXXZ", section ".CRT$XCL"
@llvm.used = appending global [1 x ptr] [ptr @__cxx_init_fn_ptr], section "llvm.metadata"

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn writeonly
define internal void @"??__Es@@YAXXZ"() #0 {
entry:
  store i32 42, ptr @"?s@@3US@@A", align 4, !tbaa !3
  ret void
}
```

**Comment by aeubanks** [comment]
I believe this is also causing miscompiles with `#pragma init_seg(lib)` vs `#pragma init_seg(user)`

https://docs.microsoft.com/en-us/cpp/preprocessor/init-seg?view=msvc-170 says that constructors under `#pragma init_seg(lib)` should run before `#pragma init_seg(user)`. We represent `init_seg(user)` as an entry in `@llvm.global_ctors`, but `init_seg(lib)` as 
```
@llvm.used = appending global [1 x ptr] [ptr @__cxx_init_fn_ptr], section "llvm.metadata"
@__cxx_init_fn_ptr = private constant ptr @"??__Ea@@YAXXZ", section ".CRT$XCL"
```

we ignore `init_seg(lib)` constructors in globalopt while evaluating things in `@llvm.global_ctors`
e.g. in https://godbolt.org/z/hGE48vz6e, `g` will be set to 5 instead of 6 at runtime

**Comment by aeubanks** [comment]
I wonder if we can put `init_seg(lib)` and `init_seg(compiler)` constructors in `llvm.global_ctors` and use some hardcoded priority for them that's lower than anything a user could specify. e.g. `1` for `compiler` and `2` for `lib`. Then we'd have to update object file creation to recognize those priorities and put them in the right section.

This would fix the miscompiles and give us the optimization for free.

**Comment by aeubanks** [comment]
@rnk

**Comment by rnk** [comment]
Fundamentally, we are dealing with a leaky portability abstraction over how ELF initializers and COFF initializers are ordered.

There are many possible solutions to this problem. I believe there is already a mapping from the init_priority integer field to strings, but we never attempt to map strings to integers. Not every string will be representable with an integer, because the string can be arbitrarily long.

The most straightforward solution is probably to do what Arthur is suggesting, but I would pick integers in the middle of the 0-65535 range so that other initializers can be ordered before and after the special cases of library and user. The existing integer to string mapping needs to be updated to take this into account.

Alternatively, we could try for a more complete, more invasive solution. One straightforward idea would be to say that the type of global_ctors on COFF is just different, the i32 should actually be some kind of string proxy, an i8* to a global character array. Not having a consistent portable representation makes life hard for middleend transforms (globalopt) that need to deal with both forms, and is backwards incompatible. Or, we could store some kind of mapping from integers to strings on the side in metadata. This would greatly complicate the task of merging global_ctor arrays, but it's more backwards compatible.  GlobalOpt could remain unaware of the metadata.

While it's worth considering the more complete solutions, I think the straightforward one is probably the way to go, but I'm concerned that we will have to continually revisit it since it's incomplete. We are already revisiting the integer to string mapping which was added to support `__attribute__((init_priority()))`.
