### ISSUE TITLE
[ELF] Support --package-metadata

### ISSUE THREAD

**Issue by abrachet** [llvm/llvm-project#56959]
gold has added support for the new flag in https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=701821154b110230f52a0367e120ecc51f490e56 ld.lld should have it too

**Comment by MaskRay** [comment]
I am not thrilled with the option. When jansson is available and enabled at configure time, binutils tries to validate whether the input is valid JSON.
Fortunately this is optional, otherwise ld just pulls in a JSON dependency (and size bloat) for very minor justification.
The option is quite ad-hoc for a very specific task before demonstrating its value is as high as build ID.

That said, the proposer has done a fair share of work by adding this to several linkers, so I guess having it in ld.lld is probably fine.

**Comment by abrachet** [comment]
Fixed in dbd04b853b680b0a383e5f58edf3643364f67bdf

**Comment by nikic** [comment]
@MaskRay Thoughts on including this in the LLVM 15 release? Looks like Fedora 37 is going to use this flag.

/cherry-pick dbd04b853b680b0a383e5f58edf3643364f67bdf

**Comment by MaskRay** [comment]
LGTM
