### ISSUE TITLE
[flang] SELECTED_REAL_KIND folding bug on aarch64

### ISSUE THREAD

**Issue by PeixinQiao** [llvm/llvm-project#57273]
```f90
program main
  integer, parameter :: K = selected_real_kind(16)
  real(K) :: my_x = 3.14159265358979
  interface
    subroutine c_func(b)
      integer, parameter :: K = selected_real_kind(16)
      real(K) :: b
    end
  end interface
  call c_func(my_x)
end
```
```console
$ flang-new -fc1 -emit-llvm fortran_main023.f90
$ cat fortran_main023.ll 
; ModuleID = 'FIRModule'
source_filename = "FIRModule"
target triple = "aarch64-unknown-linux-gnu"

@_QFECk = internal constant i32 10
@_QFEmy_x = internal global x86_fp80 0xK4000C90FDB0000000000

declare ptr @malloc(i64)

declare void @free(ptr)

define void @_QQmain() !dbg !3 {
  call void @c_func_(ptr @_QFEmy_x), !dbg !7
  ret void, !dbg !9
}

declare void @c_func_(ptr)
```
The expected type size for variable `my_x` is 128 bit instead of 80 bit on aarch64.

**Comment by PeixinQiao** [comment]
@klausler Can you take a look at this?

**Comment by klausler** [comment]
Your driver needs to control the enabling of the various kinds of intrinsic types according to targeting information from the command line.  At present, all supportable kinds are enabled in lib/Evaluate/target.cpp in the constructor for TargetCharacteristics.

**Comment by PeixinQiao** [comment]
Got it. Thanks @klausler . I see the TODO in TargetCharacteristics.

It seems that the target info has been supported in the frondend (under flang/lib/Frontend), either through `--target=<value>` option or get the machine target using `llvmModule.getTargetTriple()`. @banach-space Is this right?

**Comment by banach-space** [comment]
Thanks for bringing this up, @PeixinQiao! 

> It seems that the target info has been supported in the frondend (under flang/lib/Frontend), either through --target=<value> option or get the machine target using llvmModule.getTargetTriple(). @banach-space Is this right?

That's correct. It's configured in various places, e.g. [here](https://github.com/llvm/llvm-project/blob/e5e93b6130bde96d7e14851e218c5bf055f8a834/flang/lib/Frontend/FrontendActions.cpp#L559-L564). The actual value used depends on the flags used (e.g. `--target`) and whether the input module contains a triple (this is only relevant when consuming MLIR and LLVM IR files).

Currently, the driver (i.e. the logic in "flang/lib/Frontend") will only use the triple to configure:
* [LoweringBridge](https://github.com/llvm/llvm-project/blob/e5e93b6130bde96d7e14851e218c5bf055f8a834/flang/lib/Frontend/FrontendActions.cpp#L147-L151) when generating an MLIR file, and
* [TargetMachine](https://github.com/llvm/llvm-project/blob/e5e93b6130bde96d7e14851e218c5bf055f8a834/flang/lib/Frontend/FrontendActions.cpp#L575-L578), when generating LLVM BC or assembly/machine-code files.

However, there's no logic to configure "TargetCharacteristics" (i.e. the stages before lowering to MLIR). That's mostly because `--target` predates "TargetCharacteristics" and you seem to be the first person to identify a case in which this is a problem :)

I'm a bit distracted with other things these days, but will happily review any driver patches should anyone volunteer to implement this.

**Comment by PeixinQiao** [comment]
@banach-space Thanks for the info. I am busy with others these two weeks. I will try to come back to take a look at this two weeks later.

**Comment by PeixinQiao** [comment]
https://reviews.llvm.org/D134021
