### ISSUE TITLE
Set output location of `-ftime-trace` in command line

### ISSUE THREAD

**Issue by martinlicht** [llvm/llvm-project#57285]
The .json file produced by `-ftime-trace` should be at a location that can be controlled by command line. 

A possible command line option could be `-ftime-trace-path=/path/to/file`.

The compilation process then produces `file.json` at `/path/to/`, possibly with a time tag, `file-abc123.json`. If no path is provided, just produce the .json file at the default location.

Example application: I use clang via MinGW-w64 and the .json files are located in the /tmp/ directory. That directory itself is located at a somewhat obscure place in the Windows file system. Putting them in the project directory, for example, not only helps keeping track of them. It also greatly simplifies the cleaning process, since you don't risk cleaning out .jsons that aren't in the project.

**Comment by MaskRay** [comment]
Clang Driver has the problem (auxiliary output files go to a temporary directory, ignoring `-o` when compilation and linking is performed in one invocation) for many options.

I have https://reviews.llvm.org/D149193 to address the `-gsplit-dwarf` problem (it somehow has complexity due to offloading). https://maskray.me/blog/2023-04-25-compiler-output-files
