### ISSUE TITLE
Missed optimization for signed nonnegative number modulo 16

### ISSUE THREAD

**Issue by tczajka** [llvm/llvm-project#57472]
```c++
int foo(int x) {
    return x >= 0 ? x % 16 : 42;
}
```

This is equivalent to `x >= 0 ? x & 15 : 42`.

However, clang 14.0.0 compiles this to something like:
`x >= 0 ? x - ((x >= 0 ? x : x + 15) & -16) : 42`

Note that the second `x >= 0` is completely redundant.

https://godbolt.org/z/4Ee3sbbWs

**Comment by rotateright** [comment]
We missed a context-aware strength-reduction in IR:
https://alive2.llvm.org/ce/z/QZrSZu

**Comment by nikic** [comment]
This is something of a recurring problem, where optimizations that would happen with a branch fail to happen in select form. One typical way to fix such issues is to do the fold in IPSCCP, which runs before select formation.

It would be nice to have some more general solution to this, so that CVP folds can somehow make use of select conditions if the instruction is only used in a select arm.

**Comment by rotateright** [comment]
I haven't looked at SCCP much before, but it seems like a straightforward enhancement. We already do a sext->zext transform there.

**Comment by rotateright** [comment]
I didn't see that commit from @BaoshanPang before I self-assigned this. I already drafted a similar patch. Do you want to continue or should I?

**Comment by BaoshanPang** [comment]
@rotateright You can take it.

**Comment by rotateright** [comment]
Fixed after:
fe1f3cfc2669

**Comment by rotateright** [comment]
Re-opening - the patch was reverted ( 27e7db54eb2f ) because it triggered an assert on a bot.

**Comment by rotateright** [comment]
I haven't seen any problems with the 2nd try ( 85b289377bff14790f40 ), so closing again.
