### ISSUE TITLE
[AMDGPU][MC][GFX11] Unclear limitations for operands of v_mad_i64_i32 and v_mad_u64_u32

### ISSUE THREAD

**Issue by dpreobra** [llvm/llvm-project#57610]
AMD documentation has no description of limitations specific to these instructions. SP3 also accepts any combination of legal operands for these instructions. However, comments in llvm code seem to require that `dst` and `src2` do not overlap. There is a comment which is even more specific:

https://github.com/llvm/llvm-project/blob/211efaa1ce8164cc27f96acdee7777969e2a2bcf/llvm/test/CodeGen/AMDGPU/mad_64_32.ll#L7

Unfortunately, the way this limitation is specified caused assembler to reject instructions with any dst and src intersection.

My question is: what are actual limitations which should be enforced by assembler? Current limitations look like an overkill to me. 
Added @Sisyph for awareness.

**Comment by jayfoad** [comment]
Does this also affect instructions like V_MQSAD_U32_U8 which had a similar constraint even before GFX11?

**Comment by dpreobra** [comment]
`v_mad_i64_i32` seems to be different - it is an old opcode existed before GFX11 which has some new and unclear limitations. I have already heard complaints from my colleagues who write shaders. They use this instruction and assemble it with SP3 without any problems. In their code, `dst` and `src2` overlap, but shaders work fine.

**Comment by jayfoad** [comment]
Right, in GFX11 the result is marked as earlyclobber to avoid a possible hardware bug when it partially overlaps with one of the source operands. I did not realise that this earlyclobber is detected and enforced in the assembler. This does seem unfortunate, because it is an overly-conservative fix:
- It rejects all overlaps, when in fact complete overlap would be OK. Only partial overlap is problematic.
- The hardware bug does not always happen. It depends on the exact sequence of instructions preceding the v_mad.

**Comment by dpreobra** [comment]
Thanks for the detailed answer!
When operands have different size, is it a partial overlap or not? For example:

    v_mad_u64_u32  v[0:1], vcc, v0, v2, v[3:4] 
    v_mad_u64_u32  v[0:1], vcc, v1, v2, v[3:4]

**Comment by jayfoad** [comment]
I'm really not sure. I think it's safest to assume that operands with different sizes count as a partial overlap - but maybe that is too conservative.

**Comment by jayfoad** [comment]
> Unfortunately, the way this limitation is specified caused assembler to reject instructions with any dst and src intersection.

Right, but only because of AMDGPUAsmParser::validateEarlyClobberLimitations (added in https://reviews.llvm.org/D34003). How about removing this function?

> Current limitations look like an overkill to me.

Right, but we *want* to be able to use earlyclobber to avoid codegen bugs, even if it is overkill. We can't make it exact because the exact conditions to trigger a hardware bug are complicated, and perhaps not fully known.

**Comment by dpreobra** [comment]
> How about removing this function?

Well, I think the checks are useful, especially when the documentation is incomplete. But maybe assembler should only issue warnings in these cases.

Regarding `v_mad_i64_i32` and `v_mad_u64_u32`: I could relax limitations on these instructions in the assembler. However, it looks like the corresponding HW bug is not well understood and behavior depends on context. In this situation I'd have preferred to leave the checks as is for now.

**Comment by jayfoad** [comment]
> However, it looks like the corresponding HW bug is not well understood and behavior depends on context. In this situation I'd have preferred to leave the checks as they are for now.
I think that is exactly wrong. If there is doubt, the assembler should err on the side of allowing you to assemble stuff. Otherwise it becomes useless as a tool for testing/diagnosing/working-around hardware bugs, and we will annoy the users.

**Comment by dpreobra** [comment]
Fixed by commit https://github.com/llvm/llvm-project/commit/5c7ee894f8039902b9cd6da3db39b43819ca3996.
