### ISSUE TITLE
libcxx is compiled without debug support

### ISSUE THREAD

**Issue by jonmeow** [llvm/llvm-project#57637]
I'm trying to build using ubuntu, apt, libc++, and debug mode, but it seems to be getting built without support enabled (I think `LIBCXX_ENABLE_DEBUG_MODE_SUPPORT` must be turned off). Can `LIBCXX_ENABLE_DEBUG_MODE_SUPPORT` be enabled on builds?

A simple repro should be making a `test.cpp` that includes something (e.g., `#include <string>`) then running:
```shell
clang++ '-stdlib=libc++' -g '-D_LIBCPP_DEBUG=1' test.cpp
```

I particularly noticed this on apt; for example, please see:
https://github.com/carbon-language/carbon-lang/runs/8259658371?check_suite_focus=true

The particular error there is:
```console
/usr/lib/llvm-15/bin/../include/c++/v1/__debug:24:5: error: "Enabling the debug mode now requires having configured the library with support for the debug mode"
```

**Comment by chandlerc** [comment]
Just to make it fully clear, this is specific to the https://apt.llvm.org/ overlay of Debian packages of LLVM-15.

**Comment by philnik777** [comment]
Just enabling the debug mode would mean that everything built with that libc++ is using the debug mode. If we want to support packaging the debug mode we would probably have to add some flag to clang and ship multiple dylibs.
CC @ldionne

**Comment by chandlerc** [comment]
> Just enabling the debug mode would mean that everything built with that libc++ is using the debug mode. If we want to support packaging the debug mode we would probably have to add some flag to clang and ship multiple dylibs. CC @ldionne

My understanding was that the libc++ debugging infrastructure was designed so that while you have to build in the supporting infrastructure, it isn't used unless the user code has `_LIBCPP_DEBUG=1`. And my understanding was the reason it isn't always built in is for binary size reasons? But I may have the wrong idea here.

To be clear about what I think the actual use case is: we'd like to be able to build our C++ code against the apt.llvm.org Debian installs of libc++ with the `_LIBCPP_DEBUG=1` level of debugging checks enabled. Happy for us to install any additional package variations from apt.llvm.org and/or pass any additional compile or link flags to get that effect if needed. =]

**Comment by philnik777** [comment]
That was the case, but changed in https://llvm.org/D122941. AFAIK there is currently no nice way to have both a debug-enabled and a normal dylib side by side on a single system. You'd have to tell clang to link against the correct dylib and add the correct includes yourself, which isn't exactly a great user experience. I think the plan was to add something like `-fsanitize=library`, but I don't think that has materialized yet.

**Comment by chandlerc** [comment]
> That was the case, but changed in [llvm.org/D122941](https://llvm.org/D122941). AFAIK there is currently no nice way to have both a debug-enabled and a normal dylib side by side on a single system. You'd have to tell clang to link against the correct dylib and add the correct includes yourself, which isn't exactly a great user experience.

I mean, it seems like a better experience to me than being unable to get even the most basic asserts out of libc++...

And I don't think this should require separate *includes*, just a separate library.

Anyways, if it is truly impossible to build the DSO and archive (this is a Linux bug, so not about dylibs, but DSOs) that support both debug builds and non-debug builds, I think it would be good to get both installed and teach Clang to link against the correct one.

Even better would be to change at least the basic libc++ debugging mode sufficiently that you *can* build a DSO and archive (and maybe even a dylib) that supports either. They don't need to be fully ABI compatible -- I'm happy for all of my application to have to consistently use the same set of flags, but I can't realistically rebuild the standard library...

**Comment by philnik777** [comment]
> > That was the case, but changed in [llvm.org/D122941](https://llvm.org/D122941). AFAIK there is currently no nice way to have both a debug-enabled and a normal dylib side by side on a single system. You'd have to tell clang to link against the correct dylib and add the correct includes yourself, which isn't exactly a great user experience.
> 
> I mean, it seems like a better experience to me than being unable to get even the most basic asserts out of libc++...

You can enable simple assertions by defining `_LIBCPP_ENABLE_ASSERTIONS=1`. You only need a different library for the iterator debugging utilities.

> And I don't think this should require separate _includes_, just a separate library.

Well, kind-of. You need a different `__config_site` for the debug library and AFAIK you can only achieve that through `-nostdinc++ -isystem path/to/libcpp_includes -isystem path/to/__config_site`.

> Anyways, if it is truly impossible to build the DSO and archive (this is a Linux bug, so not about dylibs, but DSOs) that support both debug builds and non-debug builds, I think it would be good to get both installed and teach Clang to link against the correct one.

I use dylib, DSO and DLL somewhat interchangeably since it's pretty much the same concept. No disagreement that we should teach clang to link against the correct DSO, dylib or DLL correctly. I don't know what the current status on adding a flag is though. I only know that something was planned.

> Even better would be to change at least the basic libc++ debugging mode sufficiently that you _can_ build a DSO and archive (and maybe even a dylib) that supports either. They don't need to be fully ABI compatible -- I'm happy for all of my application to have to consistently use the same set of flags, but I can't realistically rebuild the standard library...

As I said above, (and sorry for the confusion) the assertions are separate from the debug mode now. Just add `-D_LIBCPP_ENABLE_ASSERTIONS=1` and all the assertions that don't have a massive amount of overhead or ABI implications get enabled.

**Comment by jonmeow** [comment]
Thanks for the explanation! After discussing, I think we'll be good with -D_LIBCPP_ENABLE_ASSERTIONS=1.
