### ISSUE TITLE
libpgmath dependency

### ISSUE THREAD

**Issue by ggouaillardet** [llvm/llvm-project#57736]
I am facing a similar problem with `flang-new` built from the `llvm-project-15.0.0.src.tar.xz` tarball on `aarch64`:

```console
$ cat test.f90 
program foo

    complex :: c
    c = 2.0
    write(*,*) sqrt(c)

end program
$ flang-new test.f90 -L/opt/llvm-15.0.0/lib
/opt/binutils-2.38/bin/ld: /tmp/test-f595ae.o: in function `_QQmain':
/home/rist/r00018/./test.f90:5: undefined reference to `__fc_sqrt_1'
flang-new: error: linker command failed with exit code 1 (use -v to see invocation)
```

A workaround is to manally build `libpgmath` and add it to the link command line

```console
$ flang-new test.f90 -L/opt/llvm-15.0.0/lib -L$HOME/local/libpgmath/lib -lpgmath
$
```

One disturbing (at least for me) part is that `libpgmath` is not part of the `llvm-project-15.0.0.src.tar.xz` tarball.

Should `libpgmath` be part of LLVM 15 (and `flang-new` automatically links to it)?

This issue has been discussed in #57670 and #57602 and it is best to follow up in its own ticket.

**Comment by banach-space** [comment]
Thanks for posting!

I've updated the title as this problem **is not** specific to:
* `flang-new` (it's not a driver problem - the dependency on `libpgmath` is a design limitation that affects all of LLVM Flang, irrespective of what driver is used),
* LLVM 15 - this dependency has been present since the inception of LLVM Flang,
* packaging - LLVM should not be packaged/shipped with external dependencies.

My main point being - LLVM Flang should not depend on external libraries.

**Comment by kiranchandramohan** [comment]
`pgmath` is not required now.
