### ISSUE TITLE
libcxx 15.0.1 fails tests when using clang-16 

### ISSUE THREAD

**Issue by mgorny** [llvm/llvm-project#57845]
When building libcxx 15.0.1 using clang-16, there's a lot of warnings like:

```console
[564/565] Building CXX object libcxx/src/CMakeFiles/cxx_static.dir/locale.cpp.o
In file included from /home/mgorny/git/llvm-project/libcxx/src/locale.cpp:16:
In file included from /home/mgorny/git/llvm-project/build-cxx/include/c++/v1/algorithm:1709:
In file included from /home/mgorny/git/llvm-project/build-cxx/include/c++/v1/__debug:16:
In file included from /home/mgorny/git/llvm-project/build-cxx/include/c++/v1/type_traits:421:
In file included from /home/mgorny/git/llvm-project/build-cxx/include/c++/v1/__functional/invoke.h:17:
/home/mgorny/git/llvm-project/build-cxx/include/c++/v1/__type_traits/decay.h:30:8: warning: keyword '__decay' will be made available as an identifier for the remainder of the translation unit [-Wkeyword-compat]
struct __decay {
       ^
In file included from /home/mgorny/git/llvm-project/libcxx/src/locale.cpp:16:
In file included from /home/mgorny/git/llvm-project/build-cxx/include/c++/v1/algorithm:1709:
In file included from /home/mgorny/git/llvm-project/build-cxx/include/c++/v1/__debug:16:
In file included from /home/mgorny/git/llvm-project/build-cxx/include/c++/v1/type_traits:511:
/home/mgorny/git/llvm-project/build-cxx/include/c++/v1/__type_traits/make_signed.h:42:8: warning: keyword '__make_signed' will be made available as an identifier for the remainder of the translation unit [-Wkeyword-compat]
struct __make_signed {};
       ^
In file included from /home/mgorny/git/llvm-project/libcxx/src/locale.cpp:16:
In file included from /home/mgorny/git/llvm-project/build-cxx/include/c++/v1/algorithm:1709:
In file included from /home/mgorny/git/llvm-project/build-cxx/include/c++/v1/__debug:16:
In file included from /home/mgorny/git/llvm-project/build-cxx/include/c++/v1/type_traits:512:
/home/mgorny/git/llvm-project/build-cxx/include/c++/v1/__type_traits/make_unsigned.h:44:8: warning: keyword '__make_unsigned' will be made available as an identifier for the remainder of the translation unit [-Wkeyword-compat]
struct __make_unsigned {};
       ^
3 warnings generated.
```

Since tests use `-Werror` this causes them to fail.

**Comment by tru** [comment]
Do we support this setup? I think the recommended setup is to always pass Libc++ as a runtime since they are tied to the current version of clang it ships with?

@ldionne might have some thoughts.

**Comment by mgorny** [comment]
I have no idea. I always thought libc++ is actually less tightly bound to clang version than compiler-rt is.

**Comment by mordante** [comment]
libc++ officially supports the same Clang version and the two previous releases. So for libc++15 we support Clang 15, 14, and 13.
These warnings are due to Clang 16 implementing some type traits, which were originally implemented in libc++.
(They are still implemented in libc++ since not all supported compilers have these builtins.)

It seems possible to port the changes made for libc++16 back to libc++15. Whether we want to backport these changes is up to @ldionne.

**Comment by ldionne** [comment]
As @mordante says, this is technically not supported officially. In fact, I would argue this specific use case would be pretty difficult to support in a formal way, since we'd have to be forward-compatible to any future change in Clang, which isn't realistic. Also, Clang 16 is technically not a thing since it has not been released yet -- it's really more like Clang trunk.

Now, that being said, we could cherry-pick the corresponding changes back to libc++ 15 as a quality of life improvement. I'm not against that, but I'm a bit worried that we'd break something else since we haven't really tested that setup. For example, do these changes depend on something that was not present in Clang 15? If so, this might be a no-go.

Another question: @mgorny, I'm curious to understand why you're trying to compile an older libc++ with a newer Clang -- what's the motivation?

**Comment by tru** [comment]
I will remove this from the 15.x milestone. And reading the last comment from @ldionne maybe it should be closed.

**Comment by ldionne** [comment]
Closing as NAD based on what I said above, @mgorny please reopen if you disagree with the explanation above about being forward compatible.

**Comment by mgorny** [comment]
> Another question: @mgorny, I'm curious to understand why you're trying to compile an older libc++ with a newer Clang -- what's the motivation?

Ah, sorry, missed this earlier. I'm switching between testing LLVM main and LLVM 15.0.x releases. We used not to enforce matching clang version in Gentoo previously, so I've ended up using clang 16 (i.e. the newest version installed) when testing the next 15.0.x release.

We're now forcing matching clang version, so that's not really a problem anymore.
