### ISSUE TITLE
lld ignores other arguments when `-V` is passed

### ISSUE THREAD

**Issue by luke-jr** [llvm/llvm-project#57859]
`lld -V <anything>` results in the expected behaviour of `-V` with everything else ignored, exiting with 0.

It appears GNU ld will run `-V` and then proceed as normal with the rest of the command line. cmake appears to (sometimes?) rely on this behaviour presently ([cmake issue 23969](https://gitlab.kitware.com/cmake/cmake/-/issues/23969)).

I'm not sure if lld wants to imitate ld's behaviour or this is a works-as-intended.

**Comment by luke-jr** [comment]
This breaks `gcc -v` ("Print (on standard error output) the commands executed to run the stages of compilation.  Also print the version number of the compiler driver program and of the preprocessor and the compiler proper.")

**Comment by luke-jr** [comment]
Looks like a trivial fix:

```diff
--- a/lld/ELF/Driver.cpp
+++ b/lld/ELF/Driver.cpp
@@ -531,9 +531,7 @@ void LinkerDriver::linkerMain(ArrayRef<const char *> argsArr) {
 
   // The behavior of -v or --version is a bit strange, but this is
   // needed for compatibility with GNU linkers.
-  if (args.hasArg(OPT_v) && !args.hasArg(OPT_INPUT))
-    return;
-  if (args.hasArg(OPT_version))
+  if ((args.hasArg(OPT_v) || args.hasArg(OPT_version)) && !args.hasArg(OPT_INPUT))
     return;
 
   // Initialize time trace profiler.
```

**Comment by MaskRay** [comment]
> This breaks gcc -v ("Print (on standard error output) the commands executed to run the stages of compilation. Also print the version number of the compiler driver program and of the preprocessor and the compiler proper.")

Can you be more specific which part of `gcc -v` breaks? (Please summarize your CMake issue discussion). `gcc -v` doesn't pass `-v` to the linker.

I can confirm that without an input, both `-v` and `--version` exit without producing an output, but it's unclear what is a required behavior. And there is something weird like:
```
% ld.bfd -v -v --version --version
GNU ld (GNU Binutils for Debian) 2.38.90.20220713
GNU ld (GNU Binutils for Debian) 2.38.90.20220713
GNU ld (GNU Binutils for Debian) 2.38.90.20220713
Copyright (C) 2022 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```
ld(1) merely says:
```
       -v
       --version
       -V  Display the version number for ld.  The -V option also lists the supported emulations.
```

I think we can still make the suggested change since it doesn't seem to increase complexity.

**Comment by luke-jr** [comment]
`gcc -v` passes `-V` (uppercase, alias for `--version`) to lld (at least on ppc64le).

**Comment by MaskRay** [comment]
> `gcc -v` passes `-V` (uppercase, alias for `--version`) to lld (at least on ppc64le).

Thanks. So it seems that for many targets (e.g. Many *-freebsd, powerpc*) GCC have such a default LINK_SPEC `%{v:-V}`, i.e. `gcc -v` passes `-V` to ld.
This seems a convincing argument to emulate this behavior, even if it is weird.
We have to treat `-V` and `--version` differently since `--version` needs to stop processing from the GNU ld behavior (if any project relies upon this behavior, it's probably libtool or autotools).

**Comment by robertmaynard** [comment]
To be clear this isn't a freebsd/powerpc quirk. Commands invocations like `g++ source.cpp -Xlinker -V` should be valid on all platforms for linking when you also want to get verbose link output ( done since `-V` gives more info compared to `-v` with ld).

**Comment by MaskRay** [comment]
> To be clear this isn't a freebsd/powerpc quirk. Commands invocations like `g++ source.cpp -Xlinker -V` should be valid on all platforms for linking when you also want to get verbose link output ( done since `-V` gives more info compared to `-v` with ld).

Whether driver `-v` should forward `-V` to as/ld is debatable. https://sourceware.org/pipermail/binutils/2022-September/123031.html "The more flags like  this we force pass to the additional tools the more likely we are to have problems when that tool is not from the GNU toolchain."

I agree with that opinion doing this is just unnecessary.
