### ISSUE TITLE
PPC64 segfault using ifunc with -static and -pie

### ISSUE THREAD

**Issue by adalava** [llvm/llvm-project#57851]
While investigating a problem with ifunc on FreeBSD/PPC64 kernel I came with a example code[1] that crashes with segmentation fault on FreeBSD. The key appears to be the combination of `-static` and `-pie` flags. The binary works if linked with GNU BFD (`-fuse-ld=bfd`)

On Linux PPC64 the binary works fine, but clang isn't actually producing a PIE binary, and it warns that -pie argument is not being used.

Results:

| Build command | Result |
|---------|-----------|
| CC=clang CFLAGS="-fuse-ld=lld" make && ./ifunc2_static | OK |
| CC=clang CFLAGS="-pie -fuse-ld=lld" make && ./ifunc2_static | SEGFAULT |
|CC=clang CFLAGS="-pie -fuse-ld=bfd" make && ./ifunc2_static | OK |

I'm always availabe on IRC as adalava and I'll be happy to do any test or provide a FreeBSD VM. Thanks!

[1] https://people.freebsd.org/~alfredo/tmp/ifunc-crash.tar.gz

**Comment by MaskRay** [comment]
This issue is invalid.

Using `-Bdynamic` with `-static` is incorrect: it links against libc.so while the used crt file does not expect non-IRELATIVE dynamic relocations.
In driver options, `-static` overrides `-pie` so you get a `-Wunused-command-line-argument` warning.
I believe early static PIE systems (OpenBSD, musl) actually made `-static -pie` mean static PIE, but upstream GCC made a decision to use `-static-pie` instead
and keep the `-static -pie => -static` status quo. Clang emulates its behavior while giving a useful warning.

On Linux, this command produces a working executable: `bmake CC='clang --target=powerpc64le-linux-gnu' LDFLAGS=-fuse-ld=lld _CFLAGS='-g -Xlinker --discard-locals'`
