### ISSUE TITLE
The `v8a` feature should be enabled by default on aarch64

### ISSUE THREAD

**Issue by adamgemmell** [llvm/llvm-project#57904]
The `TTBR0_EL2` register is [locked](https://github.com/llvm/llvm-project/blob/76fd4bf675b5ceeeca0e4e15cf15d89c7acf4947/llvm/lib/Target/AArch64/AArch64SystemOperands.td#L920) behind `el2vmsa` when it should be available on all aarch64 platforms. This has been [noticed](https://github.com/rust-lang/rust/issues/97724) in Rust which does not currently enable the feature by default or expose a stable way to enable it, though I feel here is a better place to solve the issue.

The `v8a` [feature](https://github.com/llvm/llvm-project/blob/76fd4bf675b5ceeeca0e4e15cf15d89c7acf4947/llvm/lib/Target/AArch64/AArch64.td#L496), added about a year ago, seems to want to represent features enabled on ARM v8.0 processors, but these features should really be enabled by default if this is the case.

**Comment by lenary** [comment]
just for context: the AArch64 backend now supports both v8-r and v8-a, which have significant overlap. For this reason, the backend cannot always assume that it has v8-a, because you might be compiling for v8-r. The same goes for disassembly.

In fact, disassembly is harder because v8-a and v8-r have some conflicts in their system register name/encoding space, so you have to know if you're aiming for r-profile or a-profile when disassembling. We recently added functionality to objdump to turn on all features, but this was probably incorrectly designed because it does indeed switch on everything, across both A and R profile, even though there are conflicts.

**Comment by adamgemmell** [comment]
Thanks @oToToT!
