### ISSUE TITLE
Enhancement: diagnose declaration or definition of reserved identifiers to avoid undefined behavior

### ISSUE THREAD

**Issue by pmor13** [llvm/llvm-project#57913]
This code:
```c
void __x(void);
```
compiled with:
```shell
-std=c11 -pedantic -Wall -Wextra
```
leads to:
```console
<nothing>
```
instead of:
```console
warning: declaration of reserved identifier `__x`
```
Per C11, 7.1.3 Reserved identifiers, 2:
> If the program declares or defines an identifier in a context in which it is reserved (other than as allowed by 7.1.4), or defines a reserved identifier as a macro name, the **behavior is undefined**.

Hence, the enhancement is: diagnose declaration or definition of reserved identifiers (all possible cases, see C11, 7.1.3 Reserved identifiers) to avoid undefined behavior.

@AaronBallman Any comments / ideas / thoughts?

**Comment by AaronBallman** [comment]
This is what `-Wreserved-identifier` already does (there are some edge cases though, like we miss reserved macro names defined on the command line): https://godbolt.org/z/f3z7aPKTs

**Comment by pmor13** [comment]
Wow! Excellent! Does it cover all possible use cases? Why `-Wreserved-identifier` is not part of `-Wall` or `-Wextra`?

**Comment by AaronBallman** [comment]
>  Does it cover all possible use cases?

It gets most of them, but not all (like I mentioned above, we miss macros defined via `-D` on the command line).

> Why -Wreserved-identifier is not part of -Wall or -Wextra?

Chattiness of the diagnostic in practice. The real trouble is just how many bajillions of header guards are out there that do `#define __MY_FANCY_HEADER_H__` without realizing that's a reserved identifier. Another big problem are third-party libraries that hide implementation details behind things like `namespace __details`. Those sorts of situations are valid to diagnose of course (they are hitting the UB of using a reserved identifier), but they're also the kinds of situations where the user getting the diagnostic can't actually address the diagnostic because it's triggered from code they don't own.

**Comment by pmor13** [comment]
@AaronBallman A quick relevant question. 

In https://eel.is/c++draft/lex.name I see:
>  Each identifier that **contains** a double underscore __ or begins with an underscore followed by an uppercase letter is reserved to the implementation for any use.

Why "contains" and not "begins"? Where this "contains" came from? Is it a typo?

Here is C:
> All identifiers that **begin** with an underscore and either an uppercase letter or another
underscore are always reserved for any use.

**Comment by rymiel** [comment]
It's not a typo. C++ is allowed to pick the rules it wants for the language, that's what the standard outlines. It was simply chosen to make those rules broader in the C++ standard

**Comment by AaronBallman** [comment]
> Why "contains" and not "begins"? Where this "contains" came from? Is it a typo?

It's not a typo, C++ really does mean "contains". The first C++ compiler (CFront) would name mangle namespaces using `__`, so:
```
namespace Foo {
struct Bar {
  int i;
};
}
```
would mangle as `Foo__Bar`. When C++ was standardized, it had to go with "contains" instead of "begins with" so that CFront could continue to be a conforming implementation. Even though CFront is no longer a thing, some C++ implementations still support this mangling format.

**Comment by pmor13** [comment]
Wow! Thanks. I didn't know that `Foo__Bar` is reserved in C++. TIL.

**Comment by pmor13** [comment]
@EugeneZelenko I think that this issue can be closed as "not a problem". I didn't know that `-Wreserved-identifier` exist.

**Comment by EugeneZelenko** [comment]
@zygoloid: I added relevant label, since workaround exists already.
