### ISSUE TITLE
#undef fails to undefine commandline preprocessor directives

### ISSUE THREAD

**Issue by ryao** [llvm/llvm-project#57954]
In OpenZFS, we define preprocessor directives to provide API depreciation warnings. These are set in an automake file like this:

```
AM_CPPFLAGS_NOCHECK += -D"strncpy(...)=__attribute__((deprecated(\"strncpy(3) is deprecated. Use strlcpy(3) instead!\"))) strncpy(__VA_ARGS__)"
```

That is actually the latest (proposed) deprecation warning. Due to portability issues, we initially wanted to provide an exception to the proposed deprecation policy in one of our test cases by doing `#undef`. This worked on GCC, but failed to work with Clang, where the `#undef` was ignored.

I made a minimal test case based on the depreciation warning:

```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#undef strncpy

int main()
{
        char buf[256];
        char hello[] = "hello world\n";

        strncpy(buf, hello, sizeof(buf));

        printf("%s", buf);

        return 0;
}
```

```shell
gcc -D"strncpy(...)=__attribute__((deprecated(\"strncpy(3) is deprecated. Use strlcpy(3) instead\!\"))) strncpy(__VA_ARGS__)" hello.c
```
works fine.

```shell
clang -D"strncpy(...)=__attribute__((deprecated(\"strncpy(3) is deprecated. Use strlcpy(3) instead\!\"))) strncpy(__VA_ARGS__)" hello.c
```
breaks.

This was discovered in openzfs/zfs#13876. We have since changed the code to avoid the need to bypass the deprecation warning, but I am filing this because I feel it is a bug.

This issue was detected by the FreeBSD system clang on FreeBSD stable/13 amd64 in our continuous integration infrastructure. It was reproduced on my local Gentoo Linux machine that uses Clang version 14.0.6.

**Comment by kiwixz** [comment]
Clang is working as expected here, you need to move the undef above function declaration (the `<string.h>` include) to hide the warning.

**Comment by ryao** [comment]
Why does the CPP understand C function declarations? I thought that the CPP should not have any concept of those.

**Comment by AaronBallman** [comment]
> Why does the CPP understand C function declarations? I thought that the CPP should not have any concept of those.

It doesn't.

The reason Clang behaves the way it does is because you're redefining the macro before including the header, which means the declaration you get out of the header is:
```
extern char *__attribute__((deprecated("strncpy(3) is deprecated. Use strlcpy(3) instead!"))) strncpy(char *__restrict __dest, const char *__restrict __src, size_t __n) __attribute__ ((__nothrow__ )) __attribute__ ((__nonnull__ (1, 2)));
```
Undefining the macro after including the header doesn't help because the declaration has still been changed. So from the compiler's perspective, the function is still marked as being deprecated (though I'm shocked that this code compiles given how deeply weird that declaration ends up being).

It's worth noting that what you're doing is undefined behavior (see C2x 6.2.4p8 and 7.1.3p1). Your code could run into problems for C standard libraries which define their function interfaces as macros. The `#undef` isn't an issue (you're explicitly allowed to undefine library interfaces to get to an actual function), but the `#define` is.

**Comment by ryao** [comment]
> It's worth noting that what you're doing is undefined behavior (see C2x 6.2.4p8 and 7.1.3p1).

It was not my idea. My idea was to use a perl script to catch it. Other people had the idea when I was not looking, put it into place and wanted me to use it too.

That said, while I do not have access to the standard, the standard seems to be overzealous in declaring things to be undefined. It declares making your own headers with the same names as system headers as undefined too, but the people building the system need to do that to make the system library headers in the first place (and we have `#include_next` to handle the various needs associated with that).

> Your code could run into problems for C standard libraries which define their function interfaces as macros.

In that case, wouldn't there be a compiler error from the macro definitions colliding? I assume -Werror is in use.

The original goal is to make builds fail if someone tries to write a patch using `strncpy()` because it is prone to being used incorrectly. As far as I can tell, this will achieve that.

> Undefining the macro after including the header doesn't help because the declaration has still been changed.

Now I am confused how this worked with GCC. :/

That said, I have since switched the code to use `snprintf()` instead of `strncpy()`, so the software builds without a problem. As long as no one uses `strncpy()`, it should continue to build.

**Comment by AaronBallman** [comment]
> That said, while I do not have access to the standard,

FWIW, you can get the latest draft at: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3054.pdf (and this draft should be rather close to what is finally published). You can find other drafts at: https://www.open-std.org/jtc1/sc22/wg14/www/projects

> the standard seems to be overzealous in declaring things to be undefined.

This is not one such case IMO. Presuming you can reach into the C standard library and change its declarations is a pretty dangerous thing to expect to work in general.

> In that case, wouldn't there be a compiler error from the macro definitions colliding? I assume -Werror is in use.

If you have `-Wmacro-redefined` enabled (which it is by default), then yes.

> The original goal is to make builds fail if someone tries to write a patch using strncpy() because it is prone to being used incorrectly. As far as I can tell, this will achieve that.

It does something useful for you in GCC and doesn't work quite as well as you'd want in Clang; who knows what it will do with any other C compiler (because it's UB) or another C standard library (like musl).

Another approach you could take that would work the way you want in Clang (and isn't UB) is to redeclare the C Standard Library function but add the attribute to it: https://godbolt.org/z/rW797sfTK

> I am now confused how GCC does not have a build failure here. :/

FWIW, I was also pretty surprised by the GCC behavior. Passing `-E` shows that they do munge the declaration in `string.h` the same way Clang is doing.

**Comment by ryao** [comment]
> FWIW, you can get the latest draft at: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3054.pdf (and this draft should be rather close to what is finally published). You can find other drafts at: https://www.open-std.org/jtc1/sc22/wg14/www/projects

I do not see how 6.2.4p8 applies. That refers to runtime modification of temporary data structures. What is happening in the example code is build time modification of a function definition to ensure that runtime is impossible.

I also do not see a conflict with 7.1.3p1 since we are not attempting to use it to mean something else at runtime but instead want it to never be used period.

> This is not one such case IMO. Presuming you can reach into the C standard library and change its declarations is a pretty dangerous thing to expect to work in general.

Not if the purpose is to cause a build failure.

> It does something useful for you in GCC and doesn't work quite as well as you'd want in Clang; who knows what it will do with any other C compiler (because it's UB) or another C standard library (like musl).

This works fine with musl. It also works fine with FreeBSD’s libc and MacOS’ libc.

That said, undefined behavior refers to runtime behavior, not compile time behavior. The way that this is designed is intended to ensure that runtime never happens when that function is used, which is what we want and thus it is not undefined behavior.

> FWIW, I was also pretty surprised by the GCC behavior. Passing -E shows that they do munge the declaration in string.h the same way Clang is doing.

My guess is that the function declaration’s annotation is evaluated when type checking is done on a function call. No function call means no evaluation.

**Comment by ryao** [comment]
I am closing this as there is nothing left to do here.

**Comment by AaronBallman** [comment]
> > FWIW, you can get the latest draft at: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3054.pdf (and this draft should be rather close to what is finally published). You can find other drafts at: https://www.open-std.org/jtc1/sc22/wg14/www/projects
> 
> I do not see how 6.2.4p8 applies. That refers to runtime modification of temporary data structures. What is happening in the example code is build time modification of a function definition to ensure that runtime is impossible if it is used. Since runtime is impossible, this does not apply.

Yeah, that was me and my fat fingers, I'm sorry about that! I meant 6.4.2 (Identifiers), not 6.2.4 (Storage duration of objects).

> I also do not see a conflict with 7.1.3p1 since we are not attempting to use it to mean something else at runtime but instead want it to never be used period.

"All identifiers with external linkage in any of the following subclauses (including the future library directions) and errno are always reserved for use as identifiers with external linkage."

`strncpy` is an identifier with external linkage.

"Each identifier with file scope listed in any of the following subclauses (including the future library directions) is reserved for use as a macro name and as an identifier with file scope in the same name space if any of its associated headers is included."

`strncpy` is one such identifier and you are including the associated header.

> > This is not one such case IMO. Presuming you can reach into the C standard library and change its declarations is a pretty dangerous thing to expect to work in general.
> 
> Not if the purpose is to cause a build failure.
> 
> That said, this is not a case where the standard claims undefined behavior.

I disagree.

> That said, undefined behavior refers to runtime behavior, not compile time behavior. The way that this is designed is intended to ensure that runtime never happens when that function is used and thus it is not undefined behavior.

This is incorrect. Undefined behavior is not limited to just runtime effects. See Clause 4p2 and 3.4.3p1.

**Comment by ryao** [comment]
> Yeah, that was me and my fat fingers, I'm sorry about that! I meant 6.4.2 (Identifiers), not 6.2.4 (Storage duration of objects).

Applying this to anything other than runtime would be overreach by the specification. I would not regard it as undefined behavior since it does not run.

> This is incorrect. Undefined behavior is not limited to just runtime effects. See Clause 4p2 and 3.4.3p1.

3.4.3p1 refers to runtime. It is software. It cannot have behavior if it does not run. Thus the behavior cannot be undefined when there is no behavior. I suppose you could call it whatever you want as a technicality, but that is the same as calling all polar bears in Antarctic purple or whatever other color you want. Yes, it is technically true, but there are no polar bears in Antarctica, so it does not matter and arguing about what color the non-existent polar bears are is ridiculous.

Honestly, you are not helping your case by trying to take appeals to authority with the specification, since I am not reading anything in the specification to make this undefined behavior. I had previously been open to changing the build system to use a perl script to scan the code to create build failures at build time when these functions are used, but I am not going to do that now since I am now convinced that this is a perfectly fine thing to do.

**Comment by AaronBallman** [comment]
> > Yeah, that was me and my fat fingers, I'm sorry about that! I meant 6.4.2 (Identifiers), not 6.2.4 (Storage duration of objects).
> 
> Applying this to anything other than runtime would be overreach by the specification. I would not regard it as undefined behavior since it does not run.
> 
> > This is incorrect. Undefined behavior is not limited to just runtime effects. See Clause 4p2 and 3.4.3p1.
> 
> I do not see a connection with 4p2 and as far as I can tell, 3.4.3p1 refers to runtime. This is software. Software cannot have behavior if it does not run. Thus the behavior cannot be undefined when there is no behavior. I suppose you could call it whatever you want as a technicality, but that is the same as calling all polar bears in Antarctica purple or whatever other color you want. Yes, it is technically true, but there are no polar bears in Antarctica, so it does not matter and arguing about what color(s) the non-existent polar bears are is ridiculous. It is better to think that the non-existent polar bears have no attributes of any kind so that we do not waste time thinking about them.
> 
> In order to convince me that this should be different, you would need to demonstrate that when the code is allowed to compile, the result can misbehave. However, compiling this code requires that this function not be used and when it is not used, there is no effect by the function prototype declaration. Yet, misbehavior would require that the function is used, plus some unknown side effect. The function cannot both be used and not used, so this is not a problem.

I'm explaining how I believe WG14 interprets the words in the standard around what is and isn't UB for reserved identifiers. We went over this area of the standard recently when we adopted [WG14 N2625 "What we think we reserve"](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2625.pdf) for C2x, so it's still pretty fresh in my mind. You're free to disagree with my understanding of how WG14 interprets this area of the standard, but so far I'm not convinced by your reading of the standard. Note, Clang does not yet fully implement this paper as part of `-Wreserved-identifier`. We're still missing the functionality specific to this case (handling reserved and potentially reserved library identifiers) and we have an issue catching reserved macros from the command line as well. However, it's an off-by-default diagnostic, so even if we had it fully implemented you may still have missed the warning.

Your belief that there's no such thing as compile time UB is not supported by the standard. Clause 4p2 applies because it doesn't say anything about only applying to runtime behavior. UB does not have to have runtime effects, it can have compile time effects as well. As some examples from 6.10 (preprocessing directives), "The execution of a non-directive preprocessing directive results in undefined behavior." -- this UB is explicitly for implementation extensions but it is a compile time UB. Also, for the token pasting operator: "If the result is not a valid preprocessing token, the behavior is undefined." -- this UB is not for implementation extensions but because different implementations behave differently and the C standard didn't want to break users by mandating implementations change. But it's a compile-time UB just the same. Other examples exist, this is not an exhaustive list of compile-time UB.

Regardless, I think we both consider this issue to be closed in terms of Clang's behavior and now we're discussing the C standard instead. If you still think we're interpreting the standard incorrectly, one option is for you to file a [clarification request with WG14](https://www.open-std.org/jtc1/sc22/wg14/www/contributing).

**Comment by ryao** [comment]
We compile with -Wall -Werror. If Clang begins to complain about the current approach, we will be forced to change it.

That said, I think this is splitting hairs right now when I have many far more important issues to tackle that actually cause runtime problems. :/

**Comment by erichkeane** [comment]
One good example of 'undefined behavior that doesn't make it to runtime' is C++'s "one definition rule", which typically affects link-time.  Depending on the violation type/style, this rule typically results in:

1- A compile-time error (redefinition of...)
2- A link-time error (duplicate symbols errors)
3- Runtime 'oddities'.
4- Absolute chaos.

While 'undefined behavior' is not particularly well named (as you point out), as used it is a catch-all for 'the resulting compilation/program isn't specified here, so anything could happen'.  A valid response to detected-UB is to diagnose.  A second valid response to UB is to emit a program that does the wrong thing.

**Comment by ryao** [comment]
> While 'undefined behavior' is not particularly well named (as you point out), as used it is a catch-all for 'the resulting compilation/program isn't specified here, so anything could happen'. A valid response to detected-UB is to diagnose. A second valid response to UB is to emit a program that does the wrong thing.

Is there any possible way that the macro definition here would cause the wrong thing to be emitted by the toolchain as a binary, especially when the function is not used (which is the the purpose of the macro definition)?

If not, then as long as it builds when expected to build and fails when expected to fail to build, this is a cleanup opportunity at the lowest possible priority that I can imagine. :/

**Comment by erichkeane** [comment]
@ryao: Yes, in some implementations (ours included!) a number of standard library functions are implemented as builtins that either emit code directly, or via certain system calls.  Defining it to only 'sometimes' match that definition could cause inlined versions of this function to not 'do the right thing'.

On some platforms where the standard library is less-tested because of this (IIRC, there was a memcpy bug a few years ago in GCC where the memcpy implementation 'didn't work at all', and no one knew because it was being replaced by an intrinsic implementation, which DID work right), you might end up with an untested/not correct version of this function (if, for example, your define messes with the detection for that 'intrinsic').

ANOTHER problem it can cause is in cases where the library is written as: 
``` 
    #ifndef strncpy
    #define strncpy(..) whatever
    #else
    // something else
    #endif
```

To result in a strange/different/weird version to be there.  I'm aware of similar issues when using the Intel math.h version, which takes advantage of the macro being defined/not defined (after an include_next) to replace it with our custom version (and the detection decides between this being a C-ish macro implementation or a declaration implementation).

**Comment by ryao** [comment]
> Yes, in some implementations (ours included!) a number of standard library functions are implemented as builtins that either emit code directly, or via certain system calls. Defining it to only 'sometimes' match that definition could cause inlined versions of this function to not 'do the right thing'.

This is now a medium priority item.

> On some platforms where the standard library is less-tested because of this (IIRC, there was a memcpy bug a few years ago in GCC where the memcpy implementation 'didn't work at all', and no one knew because it was being replaced by an intrinsic implementation, which DID work right), you might end up with an untested/not correct version of this function (if, for example, your define messes with the detection for that 'intrinsic').

We have eliminated usage of `strncpy()` from our codebase, so being given the wrong `strncpy()` would not be a concern for us.

> ANOTHER problem it can cause is in cases where the library is written as:

Multiple macro definitions cause a warning to be emitted, which becomes a build failure thanks to -Werror, so this is not a concern for us.

**Comment by erichkeane** [comment]
> > Yes, in some implementations (ours included!) a number of standard library functions are implemented as builtins that either emit code directly, or via certain system calls. Defining it to only 'sometimes' match that definition could cause inlined versions of this function to not 'do the right thing'.
> 
> This is now a medium priority item.
> 
> > On some platforms where the standard library is less-tested because of this (IIRC, there was a memcpy bug a few years ago in GCC where the memcpy implementation 'didn't work at all', and no one knew because it was being replaced by an intrinsic implementation, which DID work right), you might end up with an untested/not correct version of this function (if, for example, your define messes with the detection for that 'intrinsic').
> 
> We have eliminated usage of `strncpy()` from our codebase, so being given the wrong `strncpy()` would not be a concern for us.
> 
> > ANOTHER problem it can cause is in cases where the library is written as:
> 
> Multiple macro definitions cause a warning to be emitted, which becomes a build failure thanks to -Werror, so this is not a concern for us.

The problem isn't necessarily a 'redefinition'.  You might find that the library (which is what the Intel Math.h does) actually does:

```
   #ifdef strncpy
       #undef strncpy
       #define strncpy(intels version)
   #endif
```

But yes, that is likely a tougher to find concern.

**Comment by ryao** [comment]
> The problem isn't necessarily a 'redefinition'. You might find that the library (which is what the Intel Math.h does) actually does:

Being a core system component, we do not really use other libraries very much, so this is less of a concern for us.

Also, I suspect that our CI would still catch things just by virtue of using both Clang and many different versions of GCC, but I am already sufficiently convinced that this should be revisited.

At the moment, I am leaning toward making CodeQL catch the functions we do not want used in our codebase at pull request time.
