### ISSUE TITLE
Debug flags not propagated correctly for OpenMP with offload-lto

### ISSUE THREAD

**Issue by markdewing** [llvm/llvm-project#57990]
When targeting the nvidia backend, using -foffload-lto with -g will result in `ptxas fatal   : Optimized debugging not supported`

The options to clang `-g -O2 -foffload-lto -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda` will produce the error. From the verbose output, the options passed to ptxas are ` -m64 -v -O2 --gpu-name sm_61 -g` (input and output files removed for clarity)

Without `-foffload-lto`, the debug option gets translated to `-lineinfo` for ptxas.

Passing a more restricted debug flag at the original command line, like `-gline-tables-only` or `-gline-directives-only` doesn't work - they still get translated into `-g` for ptxas.

I think the issue is at the clang-linker-wrapper stage - all the debug flags get converted to a single `--device-debug` option, which sends `-g` to ptxas.

**Comment by jhuber6** [comment]
In the driver we degrade `-g` to `-gline-tables-only` on the device if optimizations are present. It seems the linker wrapper isn't currently respecting this. One problem is that the linking phase during LTO doesn't need to include `-g`, also LTO defaults to `O2` so in order to use debug the user will need to specify `O0` for the link job. I should be able to work around it in the simple case as above.
