### ISSUE TITLE
TOT changes break parsing of some CXXMethodDecl parameters

### ISSUE THREAD

**Issue by glevner** [llvm/llvm-project#58040]
We use `clang::ASTConsumer` to parse the declarations of C++ methods, to determine their parameters. Our code works in release branches 11 to 15 of LLVM/Clang, but something at the top-of-tree has broken it.

Consider the following C++ code fragment:

```
namespace fur {
  // alias for type defined elsewhere
  using Quat = MQuaternion;

  class Isometry {
  public:
    Isometry(const Quat& r);
  };
}
```

We parse this code using an `ASTFrontendAction` and examine the `CXXRecordDecl` for the constructor and its parameters. Using the release/15.x branch, a dump of the parameter looks like this:

```
LValueReferenceType 0x2d55130 'const fur::Quat &'
`-QualType 0x2d55111 'const fur::Quat' const
  `-TypedefType 0x2d55110 'fur::Quat' sugar
    |-TypeAlias 0x2d55088 'Quat'
    `-UsingType 0x2d55050 'Autodesk::Maya::OpenMaya20220000::MQuaternion' sugar
      |-UsingShadow 0x1e73290 'MQuaternion'
      `-RecordType 0x1e22b00 'class Autodesk::Maya::OpenMaya20220000::MQuaternion'
        `-CXXRecord 0x2d4f5d8 'MQuaternion'
```

Its type is `const fur::Quat &`, as we would expect. But using top-of-tree, the dump is different:

```
LValueReferenceType 0x1adf240 'const Quat &'
`-QualType 0x1adf211 'const Quat' const
  `-ElaboratedType 0x1adf210 'Quat' sugar
    `-TypedefType 0x1adf1f0 'fur::Quat' sugar
      |-TypeAlias 0x1adf140 'Quat'
      `-ElaboratedType 0x1adf100 'MQuaternion' sugar
        `-UsingType 0x1adf0d0 'Autodesk::Maya::OpenMaya20220000::MQuaternion' sugar
          |-UsingShadow 0xbbe940 'MQuaternion'
          `-RecordType 0xb6e1b0 'class Autodesk::Maya::OpenMaya20220000::MQuaternion'
            `-CXXRecord 0x1ad8f28 'MQuaternion'
```

An `ElaboratedType` has insinuated itself in there, and the type `const Quat &` is now missing its namespace.

**Comment by mizvekov** [comment]
You are likely seeing the effects of https://reviews.llvm.org/D112374

See the discussion in there for more context, but it's likely that your project was relying on a Clang bug.

Your comments don't make this exactly clear, but it seems that your project was relying on the parameter of the constructor in that example to be printed with a nested name specifier.

But observe that:
* The type was written without any nested name specifiers.
* The type printer will by design and default, print types as written, as best as we can recover from what is represented in the AST. Other behavior is non-default and necessitates configuring explicitly with different policies.

In case you disagree and have other arguments / more information, please reopen.

**Comment by glevner** [comment]
Hi Matheus,

If that was a bug, it was a very convenient and longstanding one! Can you
suggest the "correct" way of doing what we do, then? I need to take the
declaration of a function/method, which may or may not be in a namespace,
and transcribe it to the global namespace (or an unrelated namespace, in
any case). That is, I need to describe its parameter types and return type
outside of its namespace.

Thanks,
Geoff

**Comment by mizvekov** [comment]
It may have been convenient, but it probably only worked for simple cases where there is maximum one level of nesting.

A test case such as:
```
namespace fur {
  namespace bar {
    // alias for type defined elsewhere
    using Quat = MQuaternion;
  }
  class Isometry {
  public:
    Isometry(const bar::Quat& r);
  };
}
```
Would print the parameter only qualified with `bar`, as written, instead of as `fur::bar:Quat`, as you probably expected.

I think what you want, if I got that right, can be achieved by using the `QualTypeNames` module, specifically `clang::TypeName::getFullyQualifiedName`.

**Comment by glevner** [comment]
Yes, that is exactly what I needed, and I think I would never have found it
without your help. Thank you!
