### ISSUE TITLE
[AArch64] memcmp can be optimized when the result is tested for [in]equality with 0 

### ISSUE THREAD

**Issue by vfdff** [llvm/llvm-project#58061]
* test case: https://godbolt.org/z/1Wxdhch7a
```
bool f(char *a)
{
    char t[] = "0123456789012345678901234567890";
    return __builtin_memcmp(a, &t[0], sizeof(t)) == 0;
}
```

* this issue is first reported for gcc, while the llvm also has a significant room for improvement，expected assemble should be similar to the sequence used in GLIBC memcmp (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104611):
```
	ldp	data1, data3, [src1, 16]
	ldp	data2, data4, [src2, 16]
	cmp	data1, data2
	ccmp	data3, data4, 0, eq
	b.ne	L(return2)
```

**Comment by efriedma-quic** [comment]
I see two differences between what LLVM generates and your suggested sequence:

- Your suggested sequences uses ccmp instead of xor+or to do multiple compares.  That's 4 instructions for a 32-byte compare, instead of 7 or 8 instructions.
- Your suggested sequence uses adrp+add+ldp instead of mov+movk to load constants.  That's 4 instructions to load 4 64-bit constants instead of 16, assuming there isn't a more efficient way to compute any of the constants.  (Whether this is worthwhile depends on the exact constants involved, and might depend on whether the target supports mov/movk fusion, like cortex-a57.)

**Comment by vfdff** [comment]
candidate patch https://reviews.llvm.org/D136244 for the 1st issue

**Comment by vfdff** [comment]
This issue is similar to https://github.com/llvm/llvm-project/issues/56543

**Comment by vfdff** [comment]
* the 1st issue fixed with **armv8-a clang (trunk)**, while it is not for **armv8-a clang (trunk, all architechtural features)**, I don't have idea about the difference between them.

**Comment by vfdff** [comment]
Oh, Thanks. it is jutst the cache issue.

**Comment by peterwaller-arm** [comment]
I understand this issue is solved, so closing, please reopen if I'm mistaken.
