### ISSUE TITLE
[Format] Always line break on member access in concept

### ISSUE THREAD

**Issue by JohelEGP** [llvm/llvm-project#58130]
No `.clang-format`.

Input and expected output:
```C++
template <X S>
concept C = S.m;
```

Actual output:
```C++
template <X S>
concept C = S
.m;
```

Parenthesizing the member access results in no extra line break:
```C++
template <X S>
concept C = (S.m);
```

Very similar to https://github.com/llvm/llvm-project/issues/55898.

**Comment by rymiel** [comment]
Looking at this bug, the previous linked one, my previous fix, and cross-referencing it with the C++ standard it has occured to be that the real bug here (and in the previous case) is that concept definitions and requires clauses use the same parsing code despite technically being different grammar productions

requires clauses are very strict, requiring parentheses for most things that aren't simple conjunction or disjunction (https://eel.is/c++draft/temp.pre#nt:requires-clause)

![image](https://user-images.githubusercontent.com/53803019/193991049-6a20993d-23ab-4d51-9f33-37a3cf854915.png)

where as concept definitions allow basically any expression possible (https://eel.is/c++draft/temp.concept#nt:concept-definition)

![image](https://user-images.githubusercontent.com/53803019/193991123-67e4bd6a-e0f2-43ad-9759-58dfa91f2e9b.png)
![image](https://user-images.githubusercontent.com/53803019/193991166-a8e4778a-164e-4228-9bfe-7dcf2f7e1c21.png)

While I could fix this the same way I fixed the previous bug, you would always be able to find new expressions that would break it by just following the chain of valid C++ expressions.

@HazardyKnusperkeks as the author of the constraint-expression parsing code, do you have any opinions? I also noticed the following comment, implying that there is no way in UnwrappedLineParser to "just parse a normal expression" that concept definitions could be "diverted to"?

https://github.com/llvm/llvm-project/blob/d330731f94c4ffedc2250933f7d467bf658603d6/clang/lib/Format/UnwrappedLineParser.cpp#L2403-L2404

**Comment by rymiel** [comment]
Patch: https://reviews.llvm.org/D140339
