### ISSUE TITLE
Consider using thousands-separator for large numeric values in diagnostics

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#58228]
Consider:

```console
array.cpp:21:15: error: constexpr variable 'm' must be initialized by a constant expression
constexpr int m = 100'000 * 1'000'000;
              ^   ~~~~~~~~~~~~~~~~~~~
array.cpp:21:27: note: value 100000000000 is outside the range of representable values of type 'int'
constexpr int m = 100'000 * 1'000'000;
                          ^
```
Since the diagnostics are going to be read by humans, I think it could be useful to use a thousands-separator when displaying large values, in this case `100000000000`.

I'm not sure if a local-dependent one or simply a programming language dependent one make more sense.

**Comment by snprajwal** [comment]
Hi @tbaederr, I would like to take this up! I did some digging, and saw that this particular diagnostic is being emitted in three specific lines:
```
clang/lib/AST/ExprConstant.cpp:2533
clang/lib/AST/Interp/InterpState.cpp:53
clang/lib/AST/Interp/Interp.h:128
```

How would you recommend fixing this? Wrap the `Value` being passed in a function that formats it with commas and returns a string?

**Comment by tbaederr** [comment]
I'm not sure what the best way of fixing it is, without looking into a fix myself. I think a first step would be to ask a few other contributors who frequently work on diagnostics if using a thousands separator in such cases is even a good step forward.

The CodeOwners.rst doesn't list anyone for diagnostics specifically, but let's ping @AaronBallman and @MaskRay

**Comment by AaronBallman** [comment]
Paging @cjdb as well.

Having some visual distinction makes sense to me, but we'd have to figure a few things out:

1) At what point do we use a separator?
2) Do we hard-code a separator like `,`, do we use the user's locale-based digit separator, or do we use a C and C++ `'` digit separator?
3) Are there circumstances under which we do *not* want to use the digit separators even if the diagnostic is printing a large numerical value? (If this is a general thing, then the diagnostic engine can handle formatting; if it's a per-diagnostic thing, we might need to make a new diagnostic flag encoding for it.)

**Comment by cjdb** [comment]
> At what point do we use a separator?

I suggest as soon as we reach the locale's indicator (so for English, it'd be every 3 digits, but apparently there are some other locales that do it per _two_ digits).

> Do we hard-code a separator like `,`, do we use the user's locale-based digit separator, or do we use a C and C++ `'` digit separator?

I'd prefer to hardcode `'` since it's for C and C++ diagnostics. It's one less context switch to make for those using digit separators in code already.

> Are there circumstances under which we do _not_ want to use the digit separators even if the diagnostic is printing a large numerical value?

Not necessarily a concern, but we ought to at least have one test in place to ensure that strings usually aren't impacted (there are a few situations where it may be worthwhile).

**Comment by AaronBallman** [comment]
> I suggest as soon as we reach the locale's indicator (so for English, it'd be every 3 digits, but apparently there are some other locales that do it per _two_ digits).

That was my thinking initially as well, but I also think we should use `'` as a digit separator and because that's locale-independent, I was thinking we wouldn't want to fall back on asking the locale *anything*. However, performance is not a big concern here given that we've already decided we need to emit the diagnostic, so going back to the locale isn't the end of the world. But it might be weird to see `12'34'56` in one install and `123'456` in another. That also makes test coverage locale-sensitive on the CI bots.

> I'd prefer to hardcode ' since it's for C and C++ diagnostics. It's one less context switch to make for those using digit separators in code already.

That's my thinking. I think it's probably worth avoiding the testing problems and say we'll always use `'` as the separator and we'll break every three digits for a decimal value, every four digits for a binary number, every two for a hex number, and every three digits for an octal number. WDYT?

> Not necessarily a concern, but we ought to at least have one test in place to ensure that strings usually aren't impacted (there are a few situations where it may be worthwhile).

Agreed, but I think there are at least two situations that could get awkward:

1) When the integer value is surrounded in single quotes in the diagnostic already. e.g., `initialization priority '123'456' is invalid, must be between 0 and 1024`
2) (Perhaps) when we're printing a numeric value that doesn't correspond to a value in source. e.g., `attribute requires exactly 1'2 arguments`

However, it's possible that the behavior we get here with digit separators is fine because we'd never elect to print the separator due to the values being low anyway.

**Comment by snprajwal** [comment]
Another possible approach would be to use underscores as the separator, and like @AaronBallman said, stick to three digits for consistency's sake. This is currently what Rust does, and has the benefit that it is very unlikely for `_` to clash with and bungle something.

**Comment by AaronBallman** [comment]
Using `_` would solve the "we already use single quotes in diagnostic wording" problem, but the trouble there is: it's not syntactically valid in any of the languages Clang supports, so I would expect the separators to be jarring in that case. I suppose there's also some minor risk with conflicting with a UDL. e.g., `123_EFF` could technically be treating `_EFF` as a UDL in C++.

**Comment by snprajwal** [comment]
Hmm this issue would be particularly annoying for hex values, would you want to implement this only for decimal/float values currently?

**Comment by AaronBallman** [comment]
> Hmm this issue would be particularly annoying for hex values, would you want to implement this only for decimal/float values currently?

I think it's useful for large hex values. `0xFFFFFFFFFFFFFFF` is harder to read than `0xFFF'FFFF'FFFF'FFFF`

**Comment by snprajwal** [comment]
In that case, are we back to square one with using `,` as the separator? It's fairly readable, and the UDL conflict is mitigated. What do you think?

**Comment by AaronBallman** [comment]
I think my preference is for using `'` instead. It's also readable, no UDL conflicts, it's the separator used by all of the languages Clang supports. No matter what separator we pick, we're going to have the problem of needing to look at the diagnostics to decide whether the `%N` to be replaced wants to use digit separators or not. (I'm presuming we're coming up with a generic mechanism for the diagnostic engine when it prints integers and that we'll add a qualifier to say 'do the replacement'/'do not do the replacement' that can be used in the .td files.)

**Comment by snprajwal** [comment]
Sounds good, is there anything specific I should know/take a look at before I give this a shot?

**Comment by AaronBallman** [comment]
I think you'll want to modify around https://github.com/llvm/llvm-project/blob/main/clang/lib/Basic/Diagnostic.cpp#L982 (and the same for unsigned integers) to handle the formatting. You'll want to look through the .td files to spot things like `'%0'` where the value passed in might be large (so the single quotes will be confusing) or like `%0` where the value passed in should definitely not be formatted; that should help decide whether we want digit separators by default or explicitly opt-in.

**Comment by AryanGodara** [comment]
Can I try and work on this issue? (I am an outreachy applicant, and was reading through the conversation here and wanted to try it out)

**Comment by chaitanyav** [comment]
@AryanGodara Please assign the issue to yourself, if you are working on it.

**Comment by sopyb** [comment]
Hey, @AaronBallman. Since pull request #80939 addressed the issue at hand, could you please close this issue? I'd hate for others, like myself, to spend time reading through it only to find it's already resolved.

Thanks in advance.

**Comment by tbaederr** [comment]
Fixed by https://github.com/llvm/llvm-project/pull/80939
