### ISSUE TITLE
Miscompilation on i686 windows with opaque pointers + LTO

### ISSUE THREAD

**Issue by glandium** [llvm/llvm-project#58718]
(For some reason, it doesn't happen outside LTO)
This function call: https://searchfox.org/mozilla-central/rev/2809416b216b498ec3d8b0e65c25a135f4f5f37d/js/src/frontend/Parser.cpp#537-538
(declaration in: https://searchfox.org/mozilla-central/rev/2809416b216b498ec3d8b0e65c25a135f4f5f37d/js/src/frontend/ErrorReporter.h#111-112)
ends up compiled as:
```asm
movl    %edi, 4(%ebx)
movl    %esi, (%ebx)
movl    12(%ebp), %ecx
movl    %ecx, 8(%ebx)
movl    $32, 12(%ebx)
movl    %eax, 16(%ebx)
movl    -56(%ebp), %eax
movl    %eax, 20(%ebx)
pushl   %ebx
calll   0x14f73040
```
(where `%ebx` has a copy of `%esp`)
The same code, compiled with opaque pointer disabled, is compiled as:
```asm
movl    %edi, 4(%ebx)
movl    %esi, (%ebx)
movl    12(%ebp), %ecx
movl    %ecx, 8(%ebx)
movl    $32, 12(%ebx)
movl    %eax, 16(%ebx)
movl    -56(%ebp), %eax
movl    %eax, 20(%ebx)
calll   0x14faf0a0
```
Note the `push` is not there.

At the IR level, it looks like this (with opaque pointers):
```ll
 %46 = alloca inalloca <{ ptr, %"class.mozilla::UniquePtr.84", i32, i32, ptr, ptr }>, align 4
  %47 = load ptr, ptr %7, align 4
  %48 = call noundef ptr @"?DeclarationKindString@frontend@js@@YAPBDW4DeclarationKind@12@@Z"(i8 noundef zeroext %2) #7
  %49 = getelementptr inbounds <{ ptr, %"class.mozilla::UniquePtr.84", i32, i32, ptr, ptr }>, ptr %46, i32 0, i32 1
  store ptr %25, ptr %49, align 4
  store ptr %0, ptr %46, align 4
  %50 = getelementptr inbounds <{ ptr, %"class.mozilla::UniquePtr.84", i32, i32, ptr, ptr }>, ptr %46, i32 0, i32 2
  store i32 %3, ptr %50, align 4
  %51 = getelementptr inbounds <{ ptr, %"class.mozilla::UniquePtr.84", i32, i32, ptr, ptr }>, ptr %46, i32 0, i32 3
  store i32 32, ptr %51, align 4
  %52 = getelementptr inbounds <{ ptr, %"class.mozilla::UniquePtr.84", i32, i32, ptr, ptr }>, ptr %46, i32 0, i32 4
  store ptr %48, ptr %52, align 4
  %53 = getelementptr inbounds <{ ptr, %"class.mozilla::UniquePtr.84", i32, i32, ptr, ptr }>, ptr %46, i32 0, i32 5
  store ptr %47, ptr %53, align 4
  call void (ptr, ...) @"?errorWithNotesAt@ErrorReportMixin@frontend@js@@QBAXV?$UniquePtr@VJSErrorNotes@@U?$DeletePolicy@VJSErrorNotes@@@JS@@@mozilla@@IIZZ"(ptr nonnull inalloca(<{ ptr, %"class.mozilla::UniquePtr.84", i32, i32, ptr, ptr }>) %46)
```
For some reason, after `GlobalOptPass`, the call is transformed to:
```ll
  call void (ptr, ...) @"?errorWithNotesAt@ErrorReportMixin@frontend@js@@QBAXV?$UniquePtr@VJSErrorNotes@@U?$DeletePolicy@VJSErrorNotes@@@JS@@@mozilla@@IIZZ"(ptr nonnull %46)
```
(it lost the `inalloca`)
and it's when starting to lower to assembly that the push is inserted, presumably because it now thinks it's calling the function as if `%46` was the first argument and the vararg was empty.

The reason it requires LTO is probably that LTO brings in the full declaration of `errorWithNotesAt` and that has an effect on the `Function` the passes see.

Cc: @nikic

**Comment by glandium** [comment]
The inalloca removal presumably comes from https://github.com/llvm/llvm-project/blob/bcedeefa40a4759c40379d957f38da2b10a14f63/llvm/lib/Transforms/IPO/GlobalOpt.cpp#L2006-L2015

**Comment by nikic** [comment]
Do you have a standalone reproducer for this? It's not completely obvious to me that dropping the inalloca is what causes the miscompile here, as long as it gets consistently dropped from both the function and call-sites. (And in that vein, that code doesn't seem to relate to opaque pointers, so it's not clear how they come into this.)

**Comment by glandium** [comment]
In case it wasn't clear: disabling opaque pointers does fix it.

It's end of day here, I don't know the llvm-lto2 tool well enough to try to reproduce with some minimal IR before I sign off. So the best I can do for now is to give you a reproducer from a complete build of Firefox (I haven't reduced linker flags either). 

https://drive.google.com/file/d/10QDQ3WRZmR17X-BfudkOJnqs5dVs2_1V/view?usp=sharing
The link command is in the `command` file. It should work on any OS.
The broken function is `?reportRedeclaration@?$GeneralParser@VFullParseHandler@frontend@js@@_S@frontend@js@@AAEXVTaggedParserAtomIndex@23@W4DeclarationKind@23@UTokenPos@23@I@Z`.

**Comment by rnk** [comment]
Thanks for the report! I think this is a reduced example:
https://gcc.godbolt.org/z/c9sMxbG4q

This transform is incorrect in the presence of varargs. You can see in this example how the caller sets up the third argument as part of the inalloca struct instead of passing it as a distinct argument. The callee follows the normal conventions for va_start, and it reads off the end of the argument list.

The plan was that preallocated would fix this as well as other issues because it would allow flexible function prototypes. Inalloca inherently requires that all arguments passed in memory be allocated as part of a single struct alloca. It effectively splits the call operation in two: one step to allocate all stack arguments, and one step to complete the call.

+@aeubanks

**Comment by aeubanks** [comment]
This didn't pop up before because previously the vararg call was a call of the bitcasted function. The bitcast was necessary to match up pointee types of the pointer argument.

It sounds like there's some weird interaction between inalloca and varargs? Does the backend specially know how to treat inalloca and varargs? Because normally the varargs would be passed as separate arguments.

https://reviews.llvm.org/D137182

**Comment by rnk** [comment]
> It sounds like there's some weird interaction between inalloca and varargs? Does the backend specially know how to treat inalloca and varargs? Because normally the varargs would be passed as separate arguments.

The backend doesn't really know anything. Variadic arguments are normally handled by reading memory past the end of the argument pack. The same is true when inalloca is in use. The callee is effectively looking past the end of the expected struct and reading from the larger inalloca struct provided by the caller.

**Comment by rnk** [comment]
Thinking a bit more about this class of errors, I think what changed was that `hasAddressTaken` previously guarded against function calls with mismatched prototypes. Should we be worried about other kinds of prototype mismatch with inalloca? I think the answer can be "no", since prototype mismatch is basically UB, but these kinds of issues do tend to crop up every so often.
