### ISSUE TITLE
with  -mcpu=cortex-a9 ,the clang won't generate the vmla or any fused insts . 

### ISSUE THREAD

**Issue by UmeshKalappa0** [llvm/llvm-project#58779]
Here the sample 
 https://godbolt.org/z/jW656584Y

**Comment by DavidSpickett** [comment]
I cut the example down a bit and made a comparison with another cpu: https://godbolt.org/z/ob9bdMdov

You can see that the a9 doesn't use mla/mls but the a15 does. This is due to the backend giving the a9 `FeatureHasVMLxHazards`.

This feature is checked here https://github.com/llvm/llvm-project/blob/fac26edae504555e383032fafd7921cb9d9a2022/llvm/lib/Target/ARM/ARMISelDAGToDAG.cpp#L489

I suggest reading the original commit: https://github.com/llvm/llvm-project/commit/62c7b5bf76e795b4ab1c8a62b1aa4215fb964c3b

And seeing if you can match that up with the cortex-a9 technical manuals. Or even better, try the a15 codegen and see what performance you get.
