### ISSUE TITLE
 [OpenMP] complex reduction failure

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#58774]
Reproducer code https://github.com/ye-luo/openmp-target/blob/master/tests/complex/complex_reduction.cpp
```console
$ clang++ -fopenmp -fopenmp-targets=nvptx64 -O3 complex_reduction.cpp && ./a.out
Testing real
Testing float
Testing double
Testing complex
Testing float
Testing double
$ clang++ -fopenmp -fopenmp-targets=nvptx64 -O3 -ffast-math complex_reduction.cpp && ./a.out
Testing real
Testing float
Testing double
Testing complex
Testing float
Testing double
wrong reduction value check(0,0) correct value (4950,-4950)
hierarchical parallelism wrong reduction value check(450,-450) correct value (4950,-4950)
```
Seems specific to `-ffast-math`
Regression caused by b756096b0cbef0918394851644649b3c28a886e2

**Comment by ssahasra** [comment]
@ye-luo , can you please check with the following revised commit? The commit also contains a new lit test to exercise the problem. I'll submit to the LLVM main branch once you confirm that this change causes no new failures in your tests.

https://github.com/ssahasra/llvm-project/tree/ovo-issue-with-aa

@jdoerfert The root cause: When merging to Access objects, I was calling reset() on the content, but it needs to be set to nullptr instead. The latter means that the content was determined to be unknown. Also added an assertion to getWrittenValue() to catch this quickly.

**Comment by ye-luo** [comment]
@ssahasra could you update the original patch on Phabricator. Easier for me making test. Thanks.

**Comment by ssahasra** [comment]
Done. https://reviews.llvm.org/D136526

**Comment by ye-luo** [comment]
@jdoerfert Broken again by f6e3a89cc0b3b31de30ce68a4fcae44aa15daaa2

**Comment by ye-luo** [comment]
Implemented a lit test. d3ebce93622e7d46d87dcf18bfbe6d40b8345956
