### ISSUE TITLE
Divergence analysis for SimpleLoopUnswitch

### ISSUE THREAD

**Issue by Peakulorain** [llvm/llvm-project#58808]
Since LoopUnswitch requires Divergence Analysis to ensure correctness(pls see [https://bugs.llvm.org/show_bug.cgi?id=48819](https://bugs.llvm.org/show_bug.cgi?id=48819)), many GPU backends have optimizations for NonTrivial unswitch turned off by default. so is someone in the community introducing Divergence Analysis to improve SimpleLoopUnswitchPass? I'm asking this question because llvm-15 currently has many loop cases that cannot be optimized by SimpleLoopUnswitchPass.

**Comment by aeubanks** [comment]
@alinas 
See https://discourse.llvm.org/t/rfc-re-implement-non-trivial-simpleloopunswitch-with-functionpass/62937/3 for discussion around this.
Do you have measurable regressions caused by this? Some people who complained about this in the past later said that they had resolved their regressions with other changes.

**Comment by Peakulorain** [comment]
> Do you have measurable regressions caused by this? Some people who complained about this in the past later said that they had resolved their regressions with other changes.

Thanks so much. [https://reviews.llvm.org/D109762](https://reviews.llvm.org/D109762) can perfectly solve my problems. My regression was on llvm-15, but the community's main branch has fixed this, I'll use this patch to solve my problem。
