### ISSUE TITLE
[OpenMP] -Wl,--no-undefined-version

### ISSUE THREAD

**Issue by MaskRay** [llvm/llvm-project#58858]
When linking `libomp.so`, `exports_so.txt` has non-existent/undefined symbols which cause errors to `ld --no-undefined-version`. There appears to be other problems in OpenMP.

If lld defaults to `--no-undefined-version` (https://reviews.llvm.org/D135402), in a `LLVM_ENABLE_LLD=on` build, `ninja check-openmp` has link failures about `libomp.so` with version script errors. openmp should fix the version scripts not to have exact patterns which refer to non-existent symbols. It's a latent bug with GNU ld build as well.

**Comment by jhuber6** [comment]
I think the solution is to either use multiple version scripts, or just rely on wildcards. I'm not very familiar with `libomp` myself, maybe @jpeyton52 or @vzakhari can help.

**Comment by vzakhari** [comment]
@jhuber6, I am not familiar with `libomp` as well, but I agree with you that probably the best way is to use "multiple" version scripts.  I guess the current version script may be preprocessed according to `USE_DEBUGGER`, `USE_ITT_BUILD` and `KMP_USE_MONITOR` build settings with a CMake custom command (`add_custom_command`).  This will require changing `#` comments to C/C++ style comments, though.

Alternatively, the addition of `-Wl,--undefined-version` may be controlled with CMake's `check_linker_flag` so that it is only added to linker options for `lld` and not used with `ld` (meaning that undefined symbols will be still be there, but will be ignored).

**Comment by vzakhari** [comment]
Also @JonChesterfield suggest a viable alternative in https://reviews.llvm.org/D135402#3917463:
> For openmp defining different symbols in release and debug, that's nasty - suggest we define functions that do nothing for the release build.

**Comment by jpeyton52** [comment]
I've posted https://reviews.llvm.org/D138049 to cleanup the OpenMP runtime library problems which arise from the --no-undefined-version linker flag. This approach takes the dummy symbol route instead of multiple export scripts.
