### ISSUE TITLE
[avr] Wrong code using R1 for avrtiny core family.

### ISSUE THREAD

**Issue by sprintersb** [llvm/llvm-project#58875]
Compile the following C code
```c++
char func (long xx)
{
    return xx > 1;
}
```
with `--target=avr -Os -save-temps -mmcu=attiny40`. This will spit out
```console
*.s:18:11: error: invalid register on avrtiny
        cpc     r23, r1
                     ^
*.s:23:11: error: invalid register on avrtiny
        mov     r24, r1
                     ^
```
A correct code is to use `__zero_reg__` instead of `r1`.

**Comment by benshi001** [comment]
This bug is fixed by https://github.com/llvm/llvm-project/commit/5527b215160cf202431881df3be59ed5c8dabb25, please try the newest main branch of clang/llvm.

**Comment by sprintersb** [comment]
In ISR without call, it might be better to initialize `__zero_reg__` by means of `ldi r17,0` instead of `clr r17` because the latter clobbers SREG whereas the former doesn't affect SREG.

For example, in one of your test cases, there's no more need to save / restore SREG if  `ldi r17,0` is used.

**Comment by aykevl** [comment]
@sprintersb yes, correct. The patch I wrote (5527b215160cf202431881df3be59ed5c8dabb25) is purely for correctness, not for optimization. A future patch might change the prologue to use `ldi` instead of `clr` (actually `eor`). But that would only actually work once the frame lowering code _also_ omits saving of SREG if it's not clobbered (whereas currently it unconditionally saves SREG).
