### ISSUE TITLE
c++20 clang choses incorrect operator== overload

### ISSUE THREAD

**Issue by tiagomacarios** [llvm/llvm-project#58948]
In C++20 Clang will choose the incorrect overload for this code. The overload should be ambiguous (see MSVC).

https://godbolt.org/z/rox1z1Txa
```cpp
namespace N {

struct C;
struct B;

struct A {
    bool fun(A, B, C);
    bool operator==(A const&) const;
    bool operator!=(A const&) const;
};

struct B : A {};

struct C : A {
    bool operator==(C const&) const;
    bool operator!=(C const&) const;
    C(const B&);
};
}  // namespace N

namespace N {
bool A::fun(A a, B b, C c) { return b == c; }
}  // namespace N
```

**Comment by usx95** [comment]
This is working as intended since [p2468](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2468r2.html)
Remove the `operator!=(C const&) const;` to see the expected ambiguity https://godbolt.org/z/bTbPoK1Kd
Adding a matching `!=` disables reversing arguments and using `bool operator==(C const&) const;`
