### ISSUE TITLE
Regression with clang-format 14 & 15 

### ISSUE THREAD

**Issue by OldBragon** [llvm/llvm-project#59066]
The line
```cpp
LongClassName<AnotherLongClassName>{param}->longFunctionName(param0, param1);
```
is formatted to:
```cpp
LongClassName<AnotherLongClassName> { param } -> longFunctionName(param0, param1);
```
with Clang 13 and the attached configuration file, and formatted to:
```cpp
    LongClassName<AnotherLongClassName>
    {
        param
        } -> longFunctionName(param0, param1);
```
with Clang 14 & 15.

Reproduced with https://clang-format-configurator.site/
Thanks
[clang-format.txt](https://github.com/llvm/llvm-project/files/10042646/clang-format.txt)

**Comment by rymiel** [comment]
FWIW, clang-format-16 will now format it to the following:
```cpp
LongClassName<AnotherLongClassName>
{
    param
} -> longFunctionName(param0, param1);
```
as part of 1fa115b569797f64988f3d8ddd8baa05574aafa3.
The difference between 15 and 16 is intentional, as it was a fix as part of 1fa115b569797f64988f3d8ddd8baa05574aafa3. I cannot comment if the listed change is a "regression", I predict it is unlikely to be "reverted".

**Comment by HazardyKnusperkeks** [comment]
But this is not part of a requires clause, is it?

**Comment by rymiel** [comment]
That's what the commit was intended to fix, but it actually affects all braced blocks (sort of discussed in https://reviews.llvm.org/D134626). My bad, I should have probably worded the commit better
