### ISSUE TITLE
clang-format is tripped up by non-semicolon-terminated top-level macros

### ISSUE THREAD

**Issue by schuelermine** [llvm/llvm-project#59072]
## Input files:

bar.h
```c
#define define_bar(baz)\
    void bar() {\
        baz();\
    }
```

foo.c
```c
#include "bar.h"

void foo() {

}

define_bar(foo)

void foam() {
    
}
```

## Expected output:

foo.c
```c
#include "bar.h"

void foo() {}

define_bar(foo)

void foam() {}
```

## Actual output:

foo.c
```c
#include "bar.h"

void foo() {}

define_bar(foo)

    void foam() {}
```

**Comment by rymiel** [comment]
Note that the definition of the macro does not matter, as clang-format does not preprocess files, and thus cannot distinguish between macros and regular calls.

Your best bet is to use the `StatementMacros` config option:

```sh
$ clang-format foo.c --style='{StatementMacros: ["define_bar"]}'
#include "bar.h"

void foo() {}

define_bar(foo)

void foam() {}
```

I don't think this issue is actionable without an explicit configuration like above

**Comment by schuelermine** [comment]
Ok
