### ISSUE TITLE
Clang should consider removing the `-fcoroutines-ts` flag

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#59110]
Libc++ is removing its implementation of the Coroutines TS since we have been shipping the real Coroutines for 2 releases now. Without the libc++ implementation, the Clang `-fcoroutines-ts` flag is arguably dead weight, so I think we should consider removing it. That will also help with avoiding confusion by users.

CC @AaronBallman @erichkeane for awareness since this may be perceived as a breaking change.

**Comment by ldionne** [comment]
> Can libc++ delay removal by one release, or is there something pushing the timeline to be faster?

We can delay, but can we agree to issue the warning starting in LLVM 16 and to remove it in LLVM 17? I agree it will provide a better user experience if we do it that way, but I don't want to keep this code around forever (and keep rebasing it).

**Comment by ChuanqiXu9** [comment]
From what I can see, there are close-sourced use cases about coroutines which uses `-std=c++14/17 + -fcoroutines-ts`. I understand that we should maintain a better language ecosystem. I just feel it may be a little bit hurry to remove the option in one release. For example, the libcxx kept the experimental coroutine header for 2 releases and remove it in the next release. So I feel like it would be better to issue the warning for 2 releases and remove it in the next release.

**Comment by AaronBallman** [comment]
> We can delay, but can we agree to issue the warning starting in LLVM 16 and to remove it in LLVM 17? I agree it will provide a better user experience if we do it that way, but I don't want to keep this code around forever (and keep rebasing it).

I also don't want to keep the code around forever, so I'm fine with starting to warn now and removing in LLVM > 16. Whether it's 17 or not kind of depends on how disruptive the removal is. Have you checked in with `clang-vendors` to see if this will disrupt any major distros or downstreams? On the assumption that it's not disruptive, I'm fine with removing in LLVM 17. But that we're already getting folks asking for a bit more time than that makes me think LLVM 18 might also be a possibility once we know more.

> From what I can see, there are close-sourced use cases about coroutines which uses -std=c++14/17 + -fcoroutines-ts

Do you know if something is preventing those use cases from dropping the `-fcoroutines-ts` flag and relying on the standard support?

**Comment by ChuanqiXu9** [comment]
> > We can delay, but can we agree to issue the warning starting in LLVM 16 and to remove it in LLVM 17? I agree it will provide a better user experience if we do it that way, but I don't want to keep this code around forever (and keep rebasing it).
> 
> I also don't want to keep the code around forever, so I'm fine with starting to warn now and removing in LLVM > 16. Whether it's 17 or not kind of depends on how disruptive the removal is. Have you checked in with `clang-vendors` to see if this will disrupt any major distros or downstreams? On the assumption that it's not disruptive, I'm fine with removing in LLVM 17. But that we're already getting folks asking for a bit more time than that makes me think LLVM 18 might also be a possibility once we know more.
> 
> > From what I can see, there are close-sourced use cases about coroutines which uses -std=c++14/17 + -fcoroutines-ts
> 
> Do you know if something is preventing those use cases from dropping the `-fcoroutines-ts` flag and relying on the standard support?

To be honest, I didn't see a blocking issues really. I just feel it is more friendly to keep it a warning longer (the same period as we kept <experimental/coroutine> header).

**Comment by ChuanqiXu9** [comment]
> My thought on it is; the purpose of a TS implementation is to be unstable/not likely to stick around at all. The expectation of the experimental headers is "these could disappear and change at any moment".
> 
> The fact we are giving ANY notice is, IMO, a kindness.
> 
> The purpose behind that policy, is otherwise implementations are less likely to implement a TS. If you told me implementing a TS (or accepting said TS from a committee) meant supporting it for 5 years, I'd be instantly discouraged from doing so.
> 
> That said, I'm tempted to have us issue a warning as error in 16 saying it will be going away in 17, and back off if it is overly disruptive to customers (W-a-E to increase the number of reports we get back).

Oh, it looks like we have a misunderstanding here. Currently there is only one coroutine implementation instead of a TS implementation and one for the C++20 coroutine implementation. Both`-fcoroutines-ts` and `-std=c++20` would trigger the same implementation.

It is different from modules TS. Currently there are two code paths for modules TS and C++20 Modules. And there shouldn't be any one use `-fmodules-ts`. So it makes sense to remove the `-fmodules-ts` more quickly. But for the coroutines TS problem, we can think about the higher problems only and there is no implementation divergence.

**Comment by erichkeane** [comment]
My understanding is that there IS implementation burden for having the flag, which is why Louis is encouraging us to remove the flag (that is, there is implementation divergence already, but in the library).

**Comment by ChuanqiXu9** [comment]
Yeah, all of us here agree that we should remove it. The only problem is how quick it should be. My opinion is that we should warn for it for a longer time. It is more friendly to users. (If there is already a policy, we should follow it. And if there isn't one, I think we can try to propose one.)

**Comment by AaronBallman** [comment]
We don't have a policy that applies to all TSes because we need to be flexible due to TSes having different amount of maintenance cost and different timelines for rolling into the IS (if ever). e.g., if a TS is around for a decade before being rolled into an IS, we might need to keep TS-related bits for a long time. But if the TS is around for a year or two before being rolled into an IS, we might be able to pull the TS-related bits sooner.

In terms of coroutines, it's been out since ~2014 which is under a decade but is still a decent amount of time for folks to have built up code around it that might be hard to migrate. To me, I think 1-2 releases is a good deprecation period but we shouldn't need more than 2 releases. I don't have a strong feeling on whether we wait 1 or 2 releases, but I think it should depend on how much burden we're placing on @ldionne for supporting the library bits coupled with user feedback about how disruptive the change is.

As a concrete proposal for this case, how about we deprecate it with a warning diagnostic in Clang 16 and claim it will be removed in Clang 17. If we get significant user feedback, we leave it open to removing in Clang 18 instead but upgrade to using a warning-as-error in Clang 17 to signal the growing urgency to update code/build scripts. Would that work for everyone?

**Comment by erichkeane** [comment]
That seems reasonable to me.

**Comment by ChuanqiXu9** [comment]
> We don't have a policy that applies to all TSes because we need to be flexible due to TSes having different amount of maintenance cost and different timelines for rolling into the IS (if ever). e.g., if a TS is around for a decade before being rolled into an IS, we might need to keep TS-related bits for a long time. But if the TS is around for a year or two before being rolled into an IS, we might be able to pull the TS-related bits sooner.
> 
> In terms of coroutines, it's been out since ~2014 which is under a decade but is still a decent amount of time for folks to have built up code around it that might be hard to migrate. To me, I think 1-2 releases is a good deprecation period but we shouldn't need more than 2 releases. I don't have a strong feeling on whether we wait 1 or 2 releases, but I think it should depend on how much burden we're placing on @ldionne for supporting the library bits coupled with user feedback about how disruptive the change is.
> 
> As a concrete proposal for this case, how about we deprecate it with a warning diagnostic in Clang 16 and claim it will be removed in Clang 17. If we get significant user feedback, we leave it open to removing in Clang 18 instead but upgrade to using a warning-as-error in Clang 17 to signal the growing urgency to update code/build scripts. Would that work for everyone?

I feel this is reasonable. Thanks!

**Comment by ChuanqiXu9** [comment]
This is removed in https://github.com/llvm/llvm-project/commit/6ed67ccba7e4699e9e42302f2f9b7653444258ba
