### ISSUE TITLE
[RISCV] Expected<T> must be checked before access or destruction on LLJIT lookup

### ISSUE THREAD

**Issue by dkurt** [llvm/llvm-project#59139]
The following exception appears when I do LLJIT's lookup on RISC-V only. x86 works fine.

```
Expected<T> must be checked before access or destruction.
Expected<T> value was in success state. (Note: Expected<T> values in success mode must still be checked prior to being destroyed).
```

Also, there is no such problem on 15.0.2 but there is on main branch. Localized that error appears somewhere here:

https://github.com/llvm/llvm-project/blob/8f104b806a2837f36463277f7d9162f53b595ebd/llvm/lib/ExecutionEngine/Orc/Core.cpp#L2263-L2264

**Comment by dkurt** [comment]
So this is mostly a methodological question. After upgrade from 15.0.2 to 16.0.0 there is an incompatible change which added a new `Expected` check. How it can be found? LLVM in Debug takes too much memory and cannot be easily compiled on an every machine.

**Comment by jrtc27** [comment]
You can enable assertions independently from debug info

**Comment by dkurt** [comment]
@jrtc27, I did by `-DLLVM_ENABLE_ASSERTIONS=ON`, however assertion message does not contain useful information to detect a template class:
```
Expected<T> must be checked before access or destruction.
Expected<T> value was in success state. (Note: Expected<T> values in success mode must still be checked prior to being destroyed).
```

**Comment by lhames** [comment]
Some thoughts:

* Debug builds are the best option. If at all possible you should use a debug build to track this down. I usually (a) get a backtrace from the crash, and (b) put a breakpoint on `ErrorInfoBase` and re-run to identify the original error (crashes may be due to a cascade of errors, so this helps find the root cause).

* How complex is your `LLJIT` config, and how complex is your JIT'd program? You may be able to reproduce the failure under `lli` or `llvm-jitlink` and debug there.

* printf and debug logging (which should be enabled when assertions are on) are fallback solutions -- you can try to infer where things went off the rails by where the debug info cuts out, but it's hit-and-miss.

**Comment by jrtc27** [comment]
> LLVM in Debug takes too much memory and cannot be easily compiled on an every machine.

That shouldn't be true with a performant linker. GNU ld (bfd) is atrocious at linking LLVM with debug info, but using LLD or even gold should be much more manageable, especially in combination with BUILD_SHARED_LIBS to cut down on the amount linked at once.

**Comment by dwblaikie** [comment]
(re: building on lower-spec'd machines: Yeah, using lld or gold is a good start - if it's still a struggle, it may be due to not having enough memory for many parallel link jobs (assume each linker's going to use about 1GB of memory) - https://llvm.org/docs/GettingStarted.html#common-problems discusses using `-DLLVM_PARALLEL_LINK_JOBS` to reduce the number of parallel links, which may help)

**Comment by dkurt** [comment]
Thanks, @dwblaikie, @jrtc27, @lhames! With both -DLLVM_PARALLEL_LINK_JOBS=1 and  -DBUILD_SHARED_LIBS=ON i were able to compile LLVM in Debug. Will try solve the problem locally and put an update here. Let's close this issue.
