### ISSUE TITLE
lld linking errors for ARM

### ISSUE THREAD

**Issue by Hermann-Core** [llvm/llvm-project#59143]
**Hi. please help me. there's 2 days i still dont get the solution. How can i pass these linkers errors ? with gcc it worked without any issue. now i dont know why it not works with lld**
```console
ld.lld: error: undefined symbol: _init
referenced by init.c:40 (/Volumes/data/jenkins/workspace/GNU-toolchain/arm-12-mpacbti/src/newlib-cygwin/newlib/libc/misc/init.c:40)
             libc_a-init.o:(__libc_init_array) in archive /Applications/ArmGNUToolchain/12.2.mpacbti-bet1/arm-none-eabi/bin/../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libc.a
clang-16: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make: * [build/TimerSTM32.elf] Error 1
```

**And this**
```console
"/usr/local/bin/ld.lld" build/main.o build/gpio.o build/stm32f7xx_it.o build/system_stm32f7xx.o build/hw_desc_comT02_stm32f7.o build/hw_desc_timer_f746.o build/stm32f7xx_ll_gpio.o build/stm32f7xx_ll_rcc.o build/stm32f7xx_ll_utils.o build/stm32f7xx_ll_exti.o build/startup_stm32f746xx.o -Map=build/TimerSTM32.map --cref --gc-sections -Bstatic -T STM32F746ZGTx_FLASH.ld -L/Applications/ArmGNUToolchain/12.2.mpacbti-bet1/arm-none-eabi/bin/../arm-none-eabi/lib/thumb/v7e-m+fp/hard -L/Applications/ArmGNUToolchain/12.2.mpacbti-bet1/arm-none-eabi/bin/../arm-none-eabi/lib -L/usr/local/lib/clang/16/lib/baremetal -lc -lm -lgcc -o build/TimerSTM32.elf
ld.lld: error: STM32F746ZGTx_FLASH.ld:56: memory region not defined: RAM
 _estack = ORIGIN(RAM) + LENGTH(RAM);    /* end of RAM */
                 ^
clang-16: error: ld.lld command failed with exit code 1 (use -v to see invocation)
make: *** [build/TimerSTM32.elf] Error 1
```

**Here are my makefile and linker script**
[files.zip](https://github.com/llvm/llvm-project/files/10072492/files.zip)

**Comment by smithp35** [comment]
If you have questions in the future, please can you ask them in https://discourse.llvm.org/ this helps keep the issues reserved for bug reports.

For your linker script I think this is because RAM has been used before it has been defined. 
`
/* Highest address of the user mode stack */
_estack = ORIGIN(RAM) + LENGTH(RAM);    /* end of RAM */
/* Generate a link error if heap and stack don't fit into RAM */
_Min_Heap_Size = 0x200;      /* required amount of heap  */
_Min_Stack_Size = 0x400; /* required amount of stack */

/* Specify the memory areas */
MEMORY
{
RAM (xrw)      : ORIGIN = 0x20000000, LENGTH = 320K
FLASH (rx)      : ORIGIN = 0x8000000, LENGTH = 1024K
}
`
Can you try moving 
`
/* Highest address of the user mode stack */
_estack = ORIGIN(RAM) + LENGTH(RAM);    /* end of RAM */
`
After the MEMORY command.

The undefined symbol `_init` is probably a result of the  `-nostartfiles` command line option. The startup files include objects like crti.o that have a definition of `_init` 

By convention `_init` is a function that is run between the _preinit_array and _init_array initialisation code. My understanding is that is largely a historical curiosity with _init_array being preferred. I think you should be able to provide a dummy `_init` function in Assembly or C if you don't want to use the C-libraries startup files. See https://stackoverflow.com/questions/13734745/why-do-i-have-an-undefined-reference-to-init-in-libc-init-array for more details.

If this answer is satisfactory, please can you close the issue. Would be happy for follow up questions on Discourse.

**Comment by Dr-Itachi** [comment]
> 

Thanks. The solution for the the linker script worked. I dont know if it's a bug with CubeMX but this file was generated by it and worked without issue with the gnu toolchain. It's illogic

**Comment by Dr-Itachi** [comment]
For the second case I'm afraid with the consequences for doing that but after commenting out the call of __init_array in the startup assembly file i finally get passed the linking stage. I thought the outputs files should be less than GCC's ones but it's not the case do i need something to do to optimize the binaries ? Also something is wrong with my generated binary. look at these images
![Capture d’écran 2022-11-23 à 11 17 55](https://user-images.githubusercontent.com/65020150/203527309-3306d2c5-343d-4957-a7d8-ac78dceba12b.png)

![Capture d’écran 2022-11-23 à 11 15 39](https://user-images.githubusercontent.com/65020150/203527748-f01cc893-b7c6-4663-90b4-b2e27592b1fb.png)

**Comment by Dr-Itachi** [comment]
> 

many thanks for your response. for the binary it seems like it prints the same binary size regardless of the size of the input elf file. I just use the command llvm-objcopy -O binary -S <elf file> same command as with arm-none-eabi-objcopy.
