### ISSUE TITLE
OpenMP program hangs after last parallel

### ISSUE THREAD

**Issue by mikaoP** [llvm/llvm-project#59190]
This code does not end when executing with `export KMP_HOT_TEAMS_MAX_LEVEL=0`. The number of threads on each parallel is not relevant
```cpp
// t1.c
int main() {                                                                                                                                            
    #pragma omp parallel num_threads(2)                                                                                                                 
    {                                                                                                                                                   
    }                                                                                                                                                   
    #pragma omp parallel num_threads(3)                                                                                                                 
    {                                                                                                                                                   
        #pragma omp task                                                                                                                                
        {}                                                                                                                                              
    }                                                                                                                                                   
} 
```
Execute command: `clang -fopenmp t1.c -o t1 && ./t1`

I suspect this is related with https://github.com/llvm/llvm-project/issues/56307

**Comment by shiltian** [comment]
All the worker threads (let's assume thread 0 is the primary thread, and thread 1 and 2 are worker threads) are waiting at:
```
 __kmp_fork_barrier(gtid, KMP_GTID_DNE);
```
This barrier is hit after each worker thread finishes their parallel region. Meanwhile the primary thread is waiting at
```
      kmp_flag_32<false, false> flag(
          RCAST(std::atomic<kmp_uint32> *,
                &task_team->tt.tt_unfinished_threads),
          0U);
      flag.wait(this_thr, TRUE USE_ITT_BUILD_ARG(itt_sync_obj));
```
That indicates that, the completion of the second parallel region doesn't trigger the decrement of `task_team->tt.tt_unfinished_thread`, such that the primary thread thought the worker threads are still working, but apparently they have moved on.

The root cause of that is the inconsistent task state. All the worker threads get destroyed after the first parallel region by `__kmp_free_team`, where `th.th_task_state` is reset to zero. The task state of the primary thread is not. When the second parallel region starts, every thread (primary + workers) calls `__kmp_task_team_sync`. However, because the two worker threads have state 0 while the primary thread have state 1, this leads to the problem that worker threads and primary thread are not using the same task team. As a consequence, the track of unfinished threads `tt_unfinished_threads` are actually not the same one.
