### ISSUE TITLE
"[UpdateTestChecks] Auto-generate stub bodies for unused prefixes" doesn't work reliably

### ISSUE THREAD

**Issue by LebedevRI** [llvm/llvm-project#59220]
@mtrofin 

Try running the update script on the affected test in this commit and running lit on it afterwards:
https://github.com/llvm/llvm-project/commit/8a85fa68c720161ecb865eaac5761ae66c0ee8c1#commitcomment-91226555

**Comment by mtrofin** [comment]
Sorry about this - I only patched `update_llc_test_checks` to be aware of "unused" prefixes, I have the fix for `update_test_checks` ready in a bit. 

The "common" module is I think ripe for some refactoring to avoid needing to touch every tool every time we need to do fixes like this, I'll try to find some time to do it. 

https://reviews.llvm.org/D138836

**Comment by mtrofin** [comment]
I think we can close this - [255e7e1](https://github.com/llvm/llvm-project/commit/255e7e1c21eeb57b26585836a2e2d5a7f39e3cf3) addressed it.
