### ISSUE TITLE
[MLIR Core] `AsmPrinter` can print value range but does something weird (minor foot gun)

### ISSUE THREAD

**Issue by lattner** [llvm/llvm-project#59334]
Minor bug I noticed, but this compiled for a `custom<>` in an operation:

```cpp
static void printMyCustomThing(AsmPrinter &p, Operation *op, ValueRange operands) {
  // simplified...
  p << '(' << operands << ')';
}
```

but it only printed the types for the operands, not the SSA value.  The bug was that I should have passed in `OpAsmPrinter` instead of `AsmPrinter` baseclass, but this seems like a violation of the liskov substitution principle - it seems like the code above shouldn't compile, it shouldn't change behavior based on what level of type is specified.

**Comment by wpmed92** [comment]
@joker-eph Is someone working on it? If not, I'd be happy to tackle this.

**Comment by joker-eph** [comment]
Please do! Thanks :)

**Comment by wpmed92** [comment]
I reproduced this behaviour by modifying [lib/Dialect/Test/TestDialect.cpp L707](https://github.com/llvm/llvm-project/blob/8d2e0c16e691797f11a713a5601dc01e50d8734a/mlir/test/lib/Dialect/Test/TestDialect.cpp#L707) to
```cpp
static void printCustomOptionalOperand(AsmPrinter &printer, Operation *,
                                       ValueRange optOperand) {
  // if (optOperand)
    printer << "(" << optOperand << ") ";
}
```

After building mlir, the failure of [test/IR/traits.mlir](https://github.com/llvm/llvm-project/blob/8d2e0c16e691797f11a713a5601dc01e50d8734a/mlir/test/IR/traits.mlir#L547) will reveal the bug:

Instead of the expected 
```mlir
test.oilist_custom private(%arg0, %arg1 : i32, i32) reduction (%arg1) nowait
```
 the output will be 
 ```mlir
test.oilist_custom private(%arg0, %arg1 : i32, i32) reduction (i32) nowait
```

The problem is that in case of using `AsmPrinter` instead of `OpAsmPrinter` above, the following `<<` overload will be selected:
[OpImplementation.h#L305](https://github.com/llvm/llvm-project/blob/8d2e0c16e691797f11a713a5601dc01e50d8734a/mlir/include/mlir/IR/OpImplementation.h#L305)
```cpp
template <typename AsmPrinterT>
inline std::enable_if_t<std::is_base_of<AsmPrinter, AsmPrinterT>::value,
                        AsmPrinterT &>
operator<<(AsmPrinterT &p, const TypeRange &types) {
  llvm::interleaveComma(types, p);
  return p;
}
```
This is because `ValueRange` will be implicitly converted to `TypeRange`, thus the types of the operands will be printed out instead of the SSA values.

**Comment by lattner** [comment]
Great detective work!

**Comment by wpmed92** [comment]
Thank you! This has been mitigated in this patch: https://reviews.llvm.org/D144833

**Comment by unterumarmung** [comment]
I guess this is resolved?
