### ISSUE TITLE
Failure to form vwadd.wv when wide operand has additional use

### ISSUE THREAD

**Issue by topperc** [llvm/llvm-project#59345]
This test case should form `vwadd.wv` but doesn't

```ll
define <vscale x 2 x i32> @quux(<vscale x 2 x i8> %arg, <vscale x 2 x i32> %arg1, i32 signext %arg2) {
bb:                                                                              
  %tmp = call <vscale x 2 x i32> @llvm.vp.sext.nxv2i32.nxv2i8(<vscale x 2 x i8> %arg, <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i32 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 %arg2)
  %tmp3 = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> %arg1, <vscale x 2 x i32> %tmp, <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i32 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 %arg2)
  %tmp4 = call <vscale x 2 x i32> @llvm.vp.merge.nxv2i32(<vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i32 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i32> %tmp3, <vscale x 2 x i32> %arg1, i32 %arg2)
  ret <vscale x 2 x i32> %tmp4                                                   
}                                                                                
                                                                                 
; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)      
declare <vscale x 2 x i32> @llvm.vp.sext.nxv2i32.nxv2i8(<vscale x 2 x i8>, <vscale x 2 x i1>, i32) #0
                                                                                 
; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)      
declare <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i1>, i32) #0
                                                                                 
; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)      
declare <vscale x 2 x i32> @llvm.vp.merge.nxv2i32(<vscale x 2 x i1>, <vscale x 2 x i32>, <vscale x 2 x i32>, i32) #0
                                                                                 
attributes #0 = { nocallback nofree nosync nounwind willreturn memory(none) }
```

The issue appears to be that `%arg1` has 2 uses so the algorithm adds the `vp.merge` to the worklist but it's not a `widenable` instruction. The formation of `vwadd.wv` only affects the `vp.sext` so we only need to consider it's uses.

I think there's an ordering issue between the worklist management and determining which strategy we are going to use.

CC: @qcolombet

**Comment by qcolombet** [comment]
> I think there's an ordering issue between the worklist management and determining which strategy we are going to use.

Make sense. I don't have time at the moment to look at it, but I will give it a try in a few weeks if you didn't beat me at it.

**Comment by qcolombet** [comment]
Hi @topperc,

Here is a quick fix for this issue. [folding.patch](https://github.com/llvm/llvm-project/files/10375104/folding.patch)

Essentially, it pushes to the worklist the users of the operands that are extended only when the extension is actually needed, whereas previously we would push all users.

I'm not super satisfied with the patch, because it would make backtracking and applying another pattern even harder, but I don't think we want to do that anytime soon anyway.

<digression>
What I'm taking about is let say we have two instructions A and B to match and both have two possible patterns, resp. (Pat1, Pat2) and (Pat3, Pat4).

Right now if we match A with Pat1 but then failed to match B with either Pat3 or Pat4, we don't try to match A with Pat2 even if that might have allowed to apply one of B's patterns. In other words Pat1 + (Pat3 or Pat4) is a fail but Pat2 + (Pat3 or Pat4) is a match.

Essentially, we stick to the first working pattern and don't try the other alternatives.
</digression>

Anyhow, I haven't committed the change because at least in this particular example the codegen is kind of weird because we end up with two ADD instructions (one for the actual ADD and one for the MERGE as far as I can tell).
Hence, I didn't know if it is actually an improvement.

Feel free to commit if you like what you see :).

**Comment by topperc** [comment]
Thanks @qcolombet. I'll look into fixing the extra vadd.vi from the merge. We should be able to use a tail undisturbed vwadd.wv to remove it.
