### ISSUE TITLE
[PGO] Questions regarding PGO usage with LTO, counter overflows

### ISSUE THREAD

**Issue by vient** [llvm/llvm-project#59506]
Hi, I'm compiling Clang with PGO+LTO. My baseline is compiling profiled compiler without LTO, gathering profiles on our code base, then compiling PGO+LTO Clang.

I'm researching why PGO does not affect lld as much as clang, and some questions arose:
1. May it be meaningful to compile profiled compiler with LTO? In other words, if my final version uses LTO, may profiles become more accurate if they are gathered with LTO compiler?
2. Profiles obtained from LTO compiler generate tons of `counter overflow` warnings in llvm-profdata — can it decrease profile quality since a lot of counters are saturated? I suppose it can because my current LTO profiles produce worse quality PGO+LTO compiler. Can counter size be increased?
3. Are all llvm binaries instrumented when using `LLVM_BUILD_INSTRUMENTED=IR`? Is is possible to check if binary is instrumented?
6. LLVM warned me about insufficient counters until I added `-Xclang -mllvm -Xclang -vp-counters-per-site=256` to `CMAKE_{C,CXX}_FLAGS` — is it normal and expected?

**Comment by vient** [comment]
3. It seems that all binaries are instrumented, but you need to set LLD_IN_TEST=1 to get lld profiles from PGO/BOLT.

**Comment by vient** [comment]
@aaupov Hi, I saw you were the last to make changes in clang/cmake/caches. Sorry for pinging, I have a question: isn't LLD_IN_TEST=1 missing from Clang PGO/BOLT builds? I did not find it used anywhere in repo.

**Comment by aaupov** [comment]
> @aaupov Hi, isn't `LLD_IN_TEST=1` missing from Clang PGO/BOLT builds? You said me about it in #59059 but I do not see it used anywhere in the repo.

`LLD_IN_TEST` is only needed to collect **BOLT** instrumentation profile from lld. Clang-BOLT doesn't cover lld.

**Comment by vient** [comment]
Oh, right, when I see "Clang" I think of "Clang + LLD" which is wrong from projects perspective.

**Comment by vient** [comment]
Still don't know definitive answer to 1 but in my tests profiling LTO build produced worse PGO+LTO builds. With that, everything is somewhat answered.

**Comment by aaupov** [comment]
> Still don't know definitive answer to 1 but in my tests LTO profiles performed worse than non-LTO ones, even when no counter overflow occurred. With that, everything is somewhat answered.

I'm not 100% sure if it's the same issue but I observed lower performance of Clang built with LTO+PGO than with just PGO on some architectures, pre-BOLT. See [Optimizing Clang with BOLT using CMake](https://llvm.org/devmtg/2022-11/slides/Lightning15-OptimizingClangWithBOLTUsingCMake.pdf), slide 4. For example, on Broadwell Clang built with PGO shows 16.6% speedup over baseline bootstrapped Clang, while LTO+PGO shows 12.9%. Even applying BOLT on top of LTO+PGO doesn't get LTO+PGO config to parity with PGO. I didn't study the reason closely but it could be due to more aggressive inlining happening with LTO actually making the performance worse, especially on older microarchitectures.

**Comment by vient** [comment]
In my case (profiling on codebase to compile it in the future) adding PGO definitely speeds up Clang compared to just LTO but my targets are x86-64-v3 at least. BOLT then speeds it up even more
