### ISSUE TITLE
-mcpu=cortex-m33 does not set -munaligned-access

### ISSUE THREAD

**Issue by taralx** [llvm/llvm-project#59560]
Cortex-M33 is ARMv8-M Mainline, which supports unaligned access unless explicitly disabled. It appears to be correct in ARM.td, but as you can see below the output depends on the flag being explictly passed.

Test case:
```c
int ttt(short a[2], short b[2]) {
  return (int)a[0] * (int)b[0] + (int)a[1] * (int)b[1];
}
```

Output with `clang --target=arm-none-eabi -mcpu=cortex-m33 -O3 -S -o- testcase.c`:
```asm
	ldrsh.w	r2, [r0]
	ldrsh.w	r0, [r0, #2]
	ldrsh.w	r3, [r1, #2]
	ldrsh.w	r1, [r1]
	muls	r0, r3, r0
	smlabb	r0, r1, r2, r0
	bx	lr
```

Output with `clang --target=arm-none-eabi -mcpu=cortex-m33 -munaligned-access -O3 -S -o- testcase.c`:
```asm
	ldr	r0, [r0]
	ldr	r1, [r1]
	movs	r2, #0
	smlad	r0, r1, r0, r2
	bx	lr
```

Version: Homebrew clang version 15.0.6

**Comment by lenary** [comment]
This is due to the following code, which has a long comment: 

https://github.com/llvm/llvm-project/blob/2c5d49cffc1f2db52e5119bdbb44f0b10a678fb7/clang/lib/Driver/ToolChains/Arch/ARM.cpp#L808-L832

In short, if you were using an OS like linux in your triple, then clang wouldn't assume that you need `-mno-unaligned-access`. 

Looking at your example in [Compiler Explorer](https://godbolt.org/z/cj6rKqKPa), GCC (for the `none` OS) follows the same choices, so presumably the comment is fairly up to date. GCC for linux seems more pessimistic than clang in this instance.

I'm not in total agreement that all v8m.mainline cores support unaligned access. Rule JLGS says "unaligned accesses are only supported if the main extension is implemented", which seems to have the opposite implication: if you have unaligned accesses, you have main, not the other way around. Though I also see that `CCR.UNALIGN_TRP` resets to 0 if the main extension is implemented, which would seem to be the opposite implication direction to RJLGS.

In ARM.td, we don't have a feature for "Supports Unaligned Access", we only have `FeatureStrictAlign` which is the opposite. Given the complex logic in the driver, this seems wise.

**Comment by taralx** [comment]
I think you have the right of it. Rule JLGS doesn't govern here, but rule MHCM does -- it delegates to `CCR.UNALIGN_TRP`, which has to reset to zero in mainline implementations. Additional support is in the implementation of `MemU`, which also delegates to `CCR.UNALIGN_TRP` for mainline implementations.

**Comment by davemgreen** [comment]
I had noticed this recently and created an internal ticket for changing the default. (I'm not sure when this will be tackled though). The exact CPU shouldn't matter, the important part is that the v7m architecture and beyond can support unaligned access, and it makes a better default than assuming they are unsupported. They usually get enabled in the bootcode without much hassle.

Both GCC and Arm's downstream embedded armclang compiler use -munaligned-access by default. I'm not sure why this was not done upstream but it would make sense to do so. Clangs default should be the same, where users can opt out by using -mno-unaligned-access.
