### ISSUE TITLE
Cannot include header containing import of module from global module fragment

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#59688]
I believe the following is a valid set of source files

```cpp
// a.cpp
export module a;
```

```hpp
// b.hpp
import a;
```

```cpp
// c.cpp
module;
#include <b.hpp>
export module c;
```

But Clang rejects with

```console
b.hpp:2:1: error: module imports cannot be in the global module fragment
import a;
```

**Comment by ChuanqiXu9** [comment]
Oh odd. I **remembered**  `import` are not allowed in GMF. But when I check the spec just now, I failed to find such sentences...

**Comment by ChuanqiXu9** [comment]
BTW, I am curious if such uses reflect any practical use cases?

**Comment by iains** [comment]
I have a patch to fix this already - it just needs re-testing (will deal with it this week).

It seems that the use cases are not so many .. but I have seen one other example (which prompted me to write the patch)

IMO the title of '[cpp.import] (15.5 "Header Unit importation" is misleading since actually the third case listed corresponds to a named module (AFAICS).

**Comment by iains** [comment]
FWIW: I believe by
https://eel.is/c++draft/cpp.import#3
the example header cannot be used **after** the "export module Foo;" line.

**Comment by davidstone** [comment]
There are several practical use cases for this.

1) Incremental adoption. Without this ability, module adoption can start at only a single point and move outward. For instance, if I have a dependency chain `a -> b -> c -> d -> e`, if I modularize `c` I cannot convert headers in `a` to modules until I modularize all headers in `b`, and I cannot convert any headers to modules in `e` until I modularize all of `d`. In practice this has meant that I just picked a library and had to modularize the whole thing to be able to test anything, and then move on to the second library which I had to modularize entirely.
2) I'm not sure how this bug interacts with header units (since I'm using CMake for my test projects, and it doesn't support header units yet), but one thing I cannot do with just modules and headers with the current behavior is modularize anything that is used in an exported macro. If my macro references some function `f`, that `f` must be accessible through `#include` only, otherwise the header my users need to include to get the macro will have an `import` in it.
3) Related to above, but there are some ADL-related patterns that do not translate to modules. If a library uses those ADL patterns, then either the things they use or their users cannot be converted to use modules.

**Comment by iains** [comment]
https://reviews.llvm.org/D140927

**Comment by ChuanqiXu9** [comment]
> 

I see your point. I just feel like the use cases are not so flexible since the import-declarations need to appear before all other declarations in the declaration-seq. (I'm not arguing we shouldn't fix this)

**Comment by iains** [comment]
As commented in the patch, I think that the GMF is special in that it is permitted to contain pp-imports of named modules ( [cpp.import] case 3) but the constraint on ordering with decls does not take force until the start of the module purview:

https://eel.is/c++draft/basic.link#1
and 
https://eel.is/c++draft/module#import-1

a module unit declaration-seq follows the 'module Foo;' introducer of the module unit and the PMF follows that - the second link above specifically calls out the declaration-seq + the PMF.    So AFAICT this constraint **_only_** applies in the module purview.

(as noted those constraints were what originally created this bug, since I missed the implication of the third case mentioned in the first link - since the title of the section is "header unit importation")

perhaps we need to clarify this ... ?

**Comment by ChuanqiXu9** [comment]
My understanding **was** that we can have multiple `declaration-seq` in a module unit.

([basic.link]p1: https://eel.is/c++draft/basic.link#nt:translation-unit says that a normal unit is consisted of `declaration-seq`. But for a module unit, it is consisted of `global-module-fragment`, `declaration-seq` and `private-module-fragment`. And from https://eel.is/c++draft/module.global.frag#nt:global-module-fragment and https://eel.is/c++draft/module.private.frag#nt:private-module-fragment, we can find there can be other `declaration-see` in global-module-fragment and `private-module-fragment`.)

Then the wording is:

> In a module unit, all module-import-declarations shall appear before all other declarations in **the declaration-seq of the translation-unit** and of the private-module-fragment (if any).

I thought `**the declaration-seq of the translation-unit**` would include the `declaration-seq` in the global module fragment. Since it is clearly that the GMF is part of the module unit. But now I agree with you since here is `of the private-module-fragment` followed. So I think the intention may be the same with your understandings.

(I strongly agree we should clarify this)

**Comment by iains** [comment]
If we are correct (and I suspect if we are not then modules would be useless with GMFs since a major point of a GMF is to contain decls), perhaps an editorial adjustment of  s/`the declaration-seq of the translation-unit`/`the declaration-seq of the module-unit`/ would help avoid confusion.

**Comment by iains** [comment]
I suppose to progress this, we need to post the question to core - I will try to do that (unless someone chimes in here with an authoritative answer).

**Comment by iains** [comment]
hmm now I come to write the mail to core, I am again confused :(

----

[cpp.pre] 
says that pp-import may appear in the global module fragment or in any part of the module purview (i.e. in any group).

pp-import is a pre-processor directive.

but .. 
https://eel.is/c++draft/cpp#pre-3
says that the global module fragment shall not contain a pp-directive at the **start** of phase-4.

I do not think that this can be intended .. since directives are processed in stage-4, we would not be able to have a HU or a named module in the GMF.

**Comment by ChuanqiXu9** [comment]
BTW, I am also confused about [cpp.import]p3: https://eel.is/c++draft/cpp#import-3

> If a [pp-import](https://eel.is/c++draft/cpp#nt:pp-import) is produced by source file inclusion (including by the rewrite produced when a #include directive names an importable header) while processing the [group](https://eel.is/c++draft/cpp#nt:group) of a [module-file](https://eel.is/c++draft/cpp#nt:module-file), the program is ill-formed[.](https://eel.is/c++draft/cpp#import-3.sentence-1)

If I don't misread, it looks like it is saying that we can't include a file containing `import-declarations`. If it is the case, the motivation example is not valid.

**Comment by iains** [comment]
> BTW, I am also confused about [cpp.import]p3: https://eel.is/c++draft/cpp#import-3
> 
> > If a [pp-import](https://eel.is/c++draft/cpp#nt:pp-import) is produced by source file inclusion (including by the rewrite produced when a #include directive names an importable header) while processing the [group](https://eel.is/c++draft/cpp#nt:group) of a [module-file](https://eel.is/c++draft/cpp#nt:module-file), the program is ill-formed[.](https://eel.is/c++draft/cpp#import-3.sentence-1)
> 
> It looks like it is saying that we can't include a file containing `import-declarations`. If it is the case, the motivation example is not valid. Another explanation is that the `group` of the `module file` doesn't contain the `group` in the [pp-global-module-fragment:](https://eel.is/c++draft/cpp#nt:pp-global-module-fragment).
> 
> A related question is that if it is allowed to produce a `pp-import` by source file inclusion while processing the group of a `[pp-private-module-fragment:](https://eel.is/c++draft/cpp#nt:pp-private-module-fragment)`? It would be odd if it is valid.

Once again I think that this restriction ([cpp.import]p3: https://eel.is/c++draft/cpp#import-3) only applies in the module purview - but we can also ask for clarification here too.

**Comment by iains** [comment]
actually, that means it applies in an even more restricted set of conditions than the module purview (since the PMF is not included in the 'group' of the module-file).

**Comment by iains** [comment]
to the first question - the reply from core says that the reading of https://eel.is/c++draft/module#import-1 should not apply it to the GMF (which was how we now all understood it, so that's good).

So (as far as this bug goes) I think that https://reviews.llvm.org/D140927 should fix it.

We might well have found other things that we need to check (on the way) but they could be handled in separate PR(s), right?

**Comment by ChuanqiXu9** [comment]
> We might well have found other things that we need to check (on the way) but they could be handled in separate PR(s), right?

Yeah, sure.

**Comment by davidstone** [comment]
Resolved by https://reviews.llvm.org/D140927
