### ISSUE TITLE
Clang unable to compile <ranges> in libstdc++

### ISSUE THREAD

**Issue by gandyli** [llvm/llvm-project#59727]
https://godbolt.org/z/c16Ehhzaj

**Comment by royjacobson** [comment]
I think it boils down to this not working:

https://godbolt.org/z/d5T6xzEhv
```
template <class T>
concept C1 = true;

template <class T>
concept C2 = __is_same(T, int);

template <C1 T>
struct my_class {
};

template <C1 T>
requires C2<T>
struct my_class<T> {
    class Inner;
};

template <C1 T>
requires C2<T>
struct my_class<T>::Inner {};
```

Which is very similar in spirit to other overload/specialization matching bugs that we have with concepts.

**Comment by jdrouhard** [comment]
The godbolt link in https://github.com/llvm/llvm-project/issues/59727#issuecomment-1366571439 compiles fine in clang trunk, but this one reproduces the issue seen in gcc 13 `<ranges>`:

https://godbolt.org/z/csozden6e

**Comment by jdrouhard** [comment]
This appears to be a bug in gcc that caused template constraints to not be rechecked in out-of-class definitions of constrained class template member functions. The lack of a diagnostic allowed an out-of-class function definition with mismatched constraints compared to the primary class template to sneak in to `<ranges>`. Both have been fixed in upstream gcc/libstdc++ so this issue can be closed.

Ref https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109111
Ref https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96830
