### ISSUE TITLE
clang appends an extra string to Grub2 making it not work with MBR systems

### ISSUE THREAD

**Issue by immolo** [llvm/llvm-project#59793]
Using Gentoo with clang on a MBR system I have come across an extra string the content `/lib/ld-linux.so.2` is being added to `/usr/lib/grub/i386-pc/diskboot.img` and `/usr/lib/grub/i386-pc/boot.img` taking it over 512 bytes meaning it can't be used on a MBR system.

You can use `truncate` to remove the extra string then it will install and boot correctly but I am highlighting this here in hopes of a better fix.

Steps to reproduce in Gentoo:

1. Use a clang stage3 on MBR system.
2. emerge -va sys-boot/grub
3. grub-install /dev/sda

Error:

`Installing for i386-pc plaftorm.`
`grub-install: error: diskboot.img size must be 512 bytes.`

I'm not really sure what files I can attach to help debugging this one but if you can think of any please ask for them.

**Comment by dwblaikie** [comment]
probably reducing this further would be helpful, if you're interested - finding, for instance, one object file that differs in the way that matters (like - replace most of the build with GCC objects, see if you can add just one clang object and get the bad behavior - then provide the repro command for that one compilation rather than the whole build - and try to reduce the compilation (source code and the compilation command line) down to the minimal needed to reproduce the issue/difference with gcc)

**Comment by immolo** [comment]
Happy to try this one but reducing is the one skill I'm still struggling to
grasp so if you know a good resource on this one to share then it will be a
huge help in spending this up and help me submit better reports in the
future.

Thanks for the hints already though BTW!

**Comment by dwblaikie** [comment]
> Happy to try this one but reducing is the one skill I'm still struggling to
grasp so if you know a good resource on this one to share then it will be a
huge help in spending this up and help me submit better reports in the
future.

Oh, sure - so I don't know anything about the kernel build, maybe you have more context there already - but I'd consider starting by introducing an  unresolved or duplicate symbol (edit a file to call a function that's declared-but-not-defined, or add an extra definition of an existing function to another source file) and that'll cause the link to fail.

Presumably the build will print the link command line (it might be using a response file - in which case you'll need to gather/edit/look at the response file as well, not just the actual command line) for you and you can look at what's being linked in.

If you have a build with GCC and a separate build with Clang, you could try copying one file from the Clang build into the GCC build (maybe create a separate hybrid build, so you still have the GCC build in a pristine state to copy files back over from to get back to the GCC build/good state) and run the link command to see if it the resulting linked binary has the problem you've observed.

If copying one file over doesn't reproduce the issue, try bisecting (copy half the files over, see if it fails, if it does, halve the files, etc) - there might be some generic bisect tool that you could power with a list of files or something to rapidly get down to the necessary file or files.

Once you're down to one file, I'd introduce some source error (like a reference to a variable that isn't declared) and rerun the build to force the build to print the compilation command. (might have to do this separately for Clang and GCC, since the build system might use slightly different command lines for them based on feature detection of the compiler).

Then you could try using a compiler reduction tool (like creduce, cvise, etc) to simplify the source down while maintaining the invariant that GCC produces a "good" file and Clang produces a "bad" one (you'll need to be able to describe both these property tests in the form of a shell script or other automation). When you've got the simplest example - that'll be the bug to file.

(hmm, it's possible this is an error with the linker, and not with the compiler - in that case the investigation might be different, looking at how the linker is invoked, what it does... )

**Comment by immolo** [comment]
This was solved in Grub as further investigation by the patch creator found where the issue was coming from.

https://lists.gnu.org/archive/html/grub-devel/2023-01/msg00085.html

@dwblaikie Thanks for your help as it did help me rule out clang faster :)
