### ISSUE TITLE
[clang] IntegerLiteral::getEndLoc is equal to IntegerLiteral::getBeginLoc

### ISSUE THREAD

**Issue by Febbe** [llvm/llvm-project#59926]
This is the issue to the bug, detected by @v1nh1shungry in that [phab](https://reviews.llvm.org/D141058). 

For example, having a 
```
auto i = 1024;
         ^
```
Both IntegerLiteral::getBeginLoc and IntegerLiteral::getEndLoc will return the Loc at the arrow.
That is what I would expect:

```
auto i = 1024;
         ^~~~^
```

**Comment by tbaederr** [comment]
> This is the issue to the bug, detected by @v1nh1shungry in that [phab](https://reviews.llvm.org/D141058/).

Dead link?

**Comment by v1nh1shungry** [comment]
https://reviews.llvm.org/D141058

without the trailing '/'

The discussion is here: https://reviews.llvm.org/D141058#inline-1363530

**Comment by AaronBallman** [comment]
This doesn't seem like a bug to me. In Clang, source ranges can either be token source ranges or character source ranges (and token source ranges are more common). With a token source range, the location points at the starting character of the token, so I would expect the source range for an integer literal to have the same begin and end `SourceLocation` value because there's only one token in the literal. It sounds to me like the clang-tidy check should be using a character source range instead (where the source locations point to a particular character in the source): https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Basic/SourceLocation.h#L253

**Comment by v1nh1shungry** [comment]
I see. Thank you for the detailed explanation, Aaron!
