### ISSUE TITLE
__attribute__((cold)) causes unaligned functions with optimization

### ISSUE THREAD

**Issue by pogo59** [llvm/llvm-project#59974]
The "cold" attribute suppresses function alignment if I compile with optimization.
```
$ cat t.cpp
#ifdef BAD
#define COLD __attribute__((cold))
#else
#define COLD
#endif
COLD int a() { return 1; }
$ clang -S t.cpp -o - -O1 | grep p2align
        .p2align        4, 0x90
$ clang -S t.cpp -o - -O0 | grep p2align
        .p2align        4, 0x90
$ clang -S t.cpp -o - -O1 -DBAD | grep p2align
$ clang -S t.cpp -o - -O0 -DBAD | grep p2align
        .p2align        4, 0x90
```

**Comment by efriedma-quic** [comment]
Why is this a problem? There isn't any general requirement on x86 that functions are aligned.

**Comment by pogo59** [comment]
Well, it's weird and unexpected, and undocumented, for function alignment to be 16-byte for nearly everything but 1-byte for a cold function.  Also our debugger wants 16-byte aligned functions to allow edit-and-continue to work.

**Comment by efriedma-quic** [comment]
The way LLVM works is that there's a "preferred" alignment and a "minimum" alignment for functions.  Most functions get the preferred alignment; functions marked optsize (-Os/-Oz/cold attribute/etc.) get the minimum alignment.  On x86, the "preferred" alignment is 16, and the "minimum" alignment is 1.  The "preferred" alignment isn't documented anywhere because it isn't a guarantee, just a reasonable default.

You can enforce 16-byte alignment with -falign-functions=16.

I'm not sure why exactly 16 was originally chosen for the preferred alignment; it appears to go back to 956e8379.  I'd guess it's because instruction fetching on x86 CPUs fetched 16 byte aligned chunks.  I think that's still true to some extent.

**Comment by RKSimon** [comment]
CC @RKSimon

**Comment by pogo59** [comment]
Thanks for the info @efriedma-quic I was not aware of -falign-functions=16.
It sounds like this behavior is intentional, and we can alert our users.
