### ISSUE TITLE
[mlir][ods] Allow parameters to be default constructible

### ISSUE THREAD

**Issue by Mogball** [llvm/llvm-project#60178]
Attribute and type parameters in custom parsers are populated with `FailureOr<T> &` because the parser does not assume they are default constructible. This is cumbersome and ugly. Parameters in TableGen should be markable as `defaultConstructible` so that we can pass a `T &` instead.

**Comment by zero9178** [comment]
I think instead of requiring to mark it within TableGen, ODS should just generate code making use of https://en.cppreference.com/w/cpp/types/is_default_constructible if possible to let the C++ compiler be the source of truth. 
With the negative effect ofc of the generated code being less readable and more complex.

**Comment by zero9178** [comment]
Candidate patch: https://reviews.llvm.org/D142301
