### ISSUE TITLE
`misc-throw-by-value-catch-by-reference.MaxSize: '-1'` generated by `clang-tidy-16 --dump-config` crashes it when it parses the config again

### ISSUE THREAD

**Issue by KOLANICH** [llvm/llvm-project#60217]
```bash
apt list clang-tidy-16
```

```
clang-tidy-16/unknown,now 1:16~++20230117111205+2156d33b49b8-1~exp1~20230117111257.1042 amd64 [installed]
```

```yaml
---
Checks:          'misc-*'
CheckOptions:
  misc-throw-by-value-catch-by-reference.MaxSize: '-1'
...

```

```console
0.      Program arguments: clang-tidy-16 --dump-config
 #0 0x00007f1223bbffa6 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0xfbffa6)
 #1 0x00007f1223bbe190 llvm::sys::RunSignalHandlers() (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0xfbe190)
 #2 0x00007f1223bc077b (/usr/lib/llvm-16/bin/../lib/libLLVM-16.so.1+0xfc077b)
 #3 0x00007f1222655f90 (/lib/x86_64-linux-gnu/libc.so.6+0x3bf90)
 #4 0x000055e9a1462a4c clang::tidy::ClangTidyContext::diag(llvm::StringRef, llvm::StringRef, clang::DiagnosticIDs::Level) (/usr/lib/llvm-16/bin/clang-tidy+0x14a4a4c)
 #5 0x000055e9a1462dc6 clang::tidy::ClangTidyContext::configurationDiag(llvm::StringRef, clang::DiagnosticIDs::Level) (/usr/lib/llvm-16/bin/clang-tidy+0x14a4dc6)
 #6 0x000055e9a1461854 clang::tidy::ClangTidyCheck::OptionsView::diagnoseBadIntegerOption(llvm::Twine const&, llvm::StringRef) const (/usr/lib/llvm-16/bin/clang-tidy+0x14a3854)
 #7 0x000055e9a0a5b274 clang::tidy::misc::ThrowByValueCatchByReferenceCheck::ThrowByValueCatchByReferenceCheck(llvm::StringRef, clang::tidy::ClangTidyContext*) (/usr/lib/llvm-16/bin/clang-tidy+0xa9d274)
 #8 0x000055e9a09bda24 (/usr/lib/llvm-16/bin/clang-tidy+0x9ffa24)
 #9 0x000055e9a1461c6b clang::tidy::ClangTidyCheckFactories::createChecks(clang::tidy::ClangTidyContext*) const (/usr/lib/llvm-16/bin/clang-tidy+0x14a3c6b)
#10 0x000055e9a14555ff clang::tidy::getCheckOptions(clang::tidy::ClangTidyOptions const&, bool) (/usr/lib/llvm-16/bin/clang-tidy+0x14975ff)
#11 0x000055e9a07e3fbd clang::tidy::clangTidyMain(int, char const**) (/usr/lib/llvm-16/bin/clang-tidy+0x825fbd)
#12 0x00007f122264118a __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#13 0x00007f1222641245 call_init ./csu/../csu/libc-start.c:128:20
#14 0x00007f1222641245 __libc_start_main ./csu/../csu/libc-start.c:368:5
#15 0x000055e9a07e0751 _start (/usr/lib/llvm-16/bin/clang-tidy+0x822751)
```

**Comment by ealcdan** [comment]
The problem is here:

https://github.com/llvm/llvm-project/blob/16c8709cf61b0787cb3e4e283e158d9f86d8d6d5/clang-tools-extra/clang-tidy/ClangTidyCheck.cpp#L138

That line is executed when the Option is an integer, whether it is signed or not:

https://github.com/llvm/llvm-project/blob/16c8709cf61b0787cb3e4e283e158d9f86d8d6d5/clang-tools-extra/clang-tidy/ClangTidyCheck.h#L353

And that's where the overflow is happening, because these checkers are setting the default value to 2^64-1:

https://github.com/llvm/llvm-project/blob/d98086036a62e4e9c912c3b15bf16893d3df41da/clang-tools-extra/clang-tidy/misc/ThrowByValueCatchByReferenceCheck.cpp#L25

Would adding a new "store" function that is enabled if the value type is unsigned (std::is_unsigned) that ultimately calls llvm::utostr be a good solution?

**Comment by PiotrZSL** [comment]
Yes it would be a good solution, because now we read as unsigned, but store as signed.

**Comment by ealcdan** [comment]
I have been able to reproduce the failure in 87a8e22475364b79d43515159de1b7947554d868, i'll try to fix the issue then build a tested patch.

**Comment by ealcdan** [comment]
The problem is for plugins that, by design, decided to set the type of certain options as unsigned integers (I can see why that would be done to a "MaxSize" option, as negative sizes don't have any meaning). The issue then is that unsigned integer options are not supported, neither when dumping nor when parsing. As I understand it, it is reasonable that Clang-Tidy does not support passing a negative integer value to an unsigned integer option, but it is a bug if --dump-config generates such an invalid configuration.
