### ISSUE TITLE
[flang] Compilation error of sign intrinsic function in function named sign

### ISSUE THREAD

**Issue by ohno-fj** [llvm/llvm-project#60227]
```
Version of flang-new : 16.0.0(77f2f34d696b77fe5bf05afbe7386966b6bcc8ba)
```

`Sign` intrinsic function in a function named sign results in a compilation-time error.

The following are the test program, flang-new, gfortran and ifort compilation result.

`snggg865_.f90`:
```f90
module mod
  interface sign
     module procedure sign
  end interface sign
contains
  function sign (a1, a2, a3) result (data_sign)
    real, intent (In):: a1, a2, a3
    real:: data_sign
    data_sign = + sign (a1, a3)
  end function sign
end module mod

program main
  use mod
  !  write(6,*) "sign(2.0, 1.0,1.0) = ", sign(2.0, 1.0,1.0)
  if (abs(sign(2.0, 1.0,1.0)-2.0)>0.0001) write(6,*) "NG+"
end program main
```

```console
$ flang-new -flang-experimental-exec snggg865_2.f90
error: Semantic errors in snggg865_2.f90
./snggg865_2.f90:9:19: error: Dummy argument 'a3=' (#3) is not OPTIONAL and is not associated with an actual argument in this procedure reference
      data_sign = + sign (a1, a3)
                    ^^^^^^^^^^^^^
$
```

```console
$ gfortran snggg865_2.f90
snggg865_2.f90:9:22:

     data_sign = + sign (a1, a3)
                      1
Error: There is no specific function for the generic 'sign' at (1)
snggg865_2.f90:14:6:

   use mod
      1
Fatal Error: Can't open module file 'mod.mod' for reading at (1): No such file or directory
compilation terminated.
$
```

```console
$ ifort snggg865_2.f90
$
```

**Comment by klausler** [comment]
This bug is valid; 15.5.5.2 in Fortran 2018 shows that this call should have resolved to the intrinsic function `sign`.

**Comment by luporl** [comment]
The compilation error in flang-new can also be reproduced with this source:

```fortran
function sign(a1, a2, a3) result (data_sign)
  real, intent (In):: a1, a2, a3
  real:: data_sign

  data_sign = + sign (a1, a3)
end function
```

**Comment by klausler** [comment]
I think now that 15.5.5.2 does not apply here; ignore my earlier comment.  Within the function `sign`, the fact that it has a function result with a distinct name means that its name, `sign`, is available for use for recursive references within the function.  Further, the presence of the name `sign` in the scope of the function hides the generic name in the outer scope.  So the attempted reference to `sign` resolves only to that specific function, and fails due to the argument mismatch.

See Fortran 2018 15.5.5.1 paragraph 4: "A procedure name is established to be only specific in a scoping unit if it is established to be specific and not established to be generic. It is established to be specific if that scoping unit contains a module subprogram, internal subprogram, or statement function statement that defines a procedure with that name".

So the compiler is working correctly.  I wish more other Fortran compilers agreed, but this case seems unusually clear-cut in the standard.
