### ISSUE TITLE
incorrect handling of placemarker tokens in __VA_OPT__ 

### ISSUE THREAD

**Issue by sorokin** [llvm/llvm-project#60268]
Consider this code:
```cpp
#define M(x, ...)  __VA_OPT__(Q ## x) ## R
M(, 1)
```
Preprocessing of it produces `Q R` in Clang and `QR` in other compilers. I believe this behavior of Clang is incorrect because concatenation of `Q ## x` should produce a non-placemarker token which should then be concatenated with `R`.

**Comment by shafik** [comment]
This does look like a bug we can see the following example from [cpp.subst p4](https://eel.is/c++draft/cpp.subst#4):

```cpp
#define H4(X, ...) __VA_OPT__(a X ## X) ## b
H4(, 1)             // replaced by a b
```

but I believe that works b/c concatenating two placemarkers results in a single placemarker while concatenating a non-placemarker and placemarker should result in a non-placemarker according to [cpp.concat p3](https://eel.is/c++draft/cpp.concat#3):

> ... concatenation of two placemarkers results in a single placemarker preprocessing token, and concatenation of a placemarker with a non-placemarker preprocessing token results in the non-placemarker preprocessing token[.](https://eel.is/c++draft/cpp.concat#3.sentence-2) ...

CC @hubert-reinterpretcast who was the author of `p1042r1`

**Comment by hubert-reinterpretcast** [comment]
> Preprocessing of it produces `Q R` in Clang and `QR` in other compilers. I believe this behavior of Clang is incorrect because concatenation of `Q ## x` should produce a non-placemarker token which should then be concatenated with `R`.

That's exactly right.

**Comment by shafik** [comment]
I wanted to look at an example where clang does the right thing e.g.:

```cpp
#define H2(X, Y, ...) __VA_OPT__(X ## Y) __VA_ARGS__

int main() {
  H2(a, b, c) ;
}
```

and it looks like in this case different from the bug is that clang does not eat the `##`. So when I break in `Preprocessor::EnterMacro(...)` and examine the contents of `TokLexer->Tokens` in the bug case `##` is not present.

It looks like the offending line of code is in `TokenLexer::ExpandFunctionArguments()`:

```cpp
// If the expansion of __VA_OPT__ ends with a placeholder, eat any
          // following '##' token.
          if (VCtx.endsWithPlaceholder() && I + 1 != E &&
              Tokens[I + 1].is(tok::hashhash)) {
            ++I;
          }
```

and commenting out the `++i` does indeed seem to fix the bug. It looks like cb1beee76f520 brought in the change. I think removing this is the right thing to do but I need to test some more.

**Comment by shafik** [comment]
PR: https://reviews.llvm.org/D142604
