### ISSUE TITLE
clang tagged pointer optimization

### ISSUE THREAD

**Issue by fjadvanova** [llvm/llvm-project#60294]
Clang (testet with version 13 and 14) with optimization (O1 or greater) breaks pointer tagging.

```cpp
#include <stdio.h>
#include <stdint.h>

struct TestStruct {
    TestStruct(int ii) : i(ii) {}
    int i;

    bool hasFlag() const { return reinterpret_cast<intptr_t>(this) & Flag; }
    TestStruct* removeFlag() { return reinterpret_cast<TestStruct*>(reinterpret_cast<intptr_t>(this) & ~Flag); }

    static const intptr_t Flag = 1;
};


int main() {
    TestStruct *a = new TestStruct(42);

    intptr_t i = reinterpret_cast<intptr_t>(a);
    i = i | TestStruct::Flag;
    TestStruct *b = reinterpret_cast<TestStruct*>(i);

    TestStruct *c = b->removeFlag();

    printf("b->hasFlag()=%s\n", b->hasFlag() ? "true" : "false");
    // without optimization b->hasFlag()=true
    // with    optimization b->hasFlag()=false
    printf("a=%p b=%p c=%p\n", a, b, c);
    // without optimization a == c && b != c
    // with    optimization a != c && b == c

    return 0;
}
```

**Comment by EugeneZelenko** [comment]
Could you please try 15 or `main` branch? https://godbolt.org should be helpful.

**Comment by fjadvanova** [comment]
https://godbolt.org/z/Tenz71GMh

**Comment by fjadvanova** [comment]
Issues is also in 15

**Comment by fjadvanova** [comment]
Thank you for your answer.
can you show where in the spec it says that the this pointer must have alignment greater or equal to 4

**Comment by zero9178** [comment]
Sure!

It doesn't say so explicitly but it is implied through a few steps (and your case is more directly mentioned as invalid).
Draft: https://www.open-std.org/JTC1/SC22/WG21/docs/papers/2020/n4849.pdf

11.4.2§2 (Page 259) says:
> If a non-static member function of a class X is called for an object that is not of type X, or of a type derived
from X, the behavior is undefined.

In your code, the object pointed to by `b`  is not a valid object of type `TestStruct` or a derived class of it, making the code immedaite undefined behaviour. 
Therefore clang is allowed to assume that the `this` pointer points to a valid object of type `TestStruct`, since any calls where this is not the case are UB. Since valid objects of type `TestStruct` and derived must also have at least the alignment requirement of `TestStruct` (otherwise it'd not be a valid object of that type), clang also assumes that the pointer must have the same alignment requirement as `TestStruct`.

**Comment by fjadvanova** [comment]
Thank you
