### ISSUE TITLE
[flang] problem with multiple allocation

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#60303]
Original test code:
https://github.com/gcc-mirror/gcc/blob/master/gcc/testsuite/gfortran.dg/multiple_allocation_1.f90

For sake of simplicity, I modified the original test code:
```console
$ cat multiple_allocation_1_modify.f90
program alloc_test
  implicit none
  integer :: i
  integer, allocatable :: a(:)

  allocate(a(4))
  allocate(a(3),stat=i)
  print *, size(a)

end program
```

Result (gfortran vs flang-new)
```console
$ gfortran multiple_allocation_1_modify.f90
$ ./a.out
           4

$ flang-new -flang-experimental-exec multiple_allocation_1_modify.f90
$ ./a.out
 3
```

**Comment by jeanPerier** [comment]
Thanks for the bug report. I think lowering should insert a call to "AllocatableCheckAllocated" runtime [declared here](https://github.com/llvm/llvm-project/blob/e4d9a5e616f38fca05200a766711ba9b1605f57f/flang/include/flang/Runtime/allocatable.h#L42) when error recovery is present and the allocate-object is an allocatable. This should probably be inserted here in lowering: https://github.com/llvm/llvm-project/blob/7531c87183822cf8931496a757a09779e24aeac0/flang/lib/Lower/Allocatable.cpp#L368


Standard reference:
Fortran standard 9.7.4 point 1 says (F2018 point 6): _"each allocate-object that was not successfully allocated or deallocated shall retain its previous allocation status or pointer association status."_

Note that if other less trivial things go wrong (say there is no more memory to allocate), the descriptor bounds will still be modified, but the allocatable address will remain the same. That's because the descriptor is modified in place while preparing the allocation, so if a failure is caught late, it will be reported, but the bounds, length parameter and dynamic type might still be modified.

**Comment by k-arrows** [comment]
https://github.com/llvm/llvm-project/pull/77386

**Comment by klausler** [comment]
The fix has been merged into llvm-project/main.
