### ISSUE TITLE
Building lldb-instr fails with undefined reference to symbol when building with BUILD_SHARED_LIBS=ON

### ISSUE THREAD

**Issue by KyleFromKitware** [llvm/llvm-project#60314]
Building lldb-instr fails with the following error when I build with `BUILD_SHARED_LIBS=ON`:

```console
: && /usr/bin/c++ -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -fdiagnostics-color -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-stringop-truncation -g -Wl,-rpath-link,<redacted>/./lib tools/lldb/tools/lldb-instr/CMakeFiles/lldb-instr.dir/Instrument.cpp.o -o bin/lldb-instr  -Wl,-rpath,"\$ORIGIN/../lib"  -lpthread  lib/libclangCodeGen.so.17git  lib/libclangTooling.so.17git  lib/libclangFrontend.so.17git  lib/libclangSerialization.so.17git  lib/libclangAST.so.17git  lib/libclangRewrite.so.17git  lib/libclangLex.so.17git  lib/libclangBasic.so.17git  -Wl,-rpath-link,<redacted>/lib && :
/usr/bin/ld: tools/lldb/tools/lldb-instr/CMakeFiles/lldb-instr.dir/Instrument.cpp.o: undefined reference to symbol '_ZNK4llvm15SmallVectorBaseIjE5emptyEv'
/usr/bin/ld: <redacted>/./lib/libLLVMSupport.so.17git: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

I suspect lldb-instr is missing some library dependency.

**Comment by KyleFromKitware** [comment]
The following patch seems to fix it:

```patch
diff --git a/lldb/tools/lldb-instr/CMakeLists.txt b/lldb/tools/lldb-instr/CMakeLists.txt
index a1bbd7e2b7c9..9e9a757c4329 100644
--- a/lldb/tools/lldb-instr/CMakeLists.txt
+++ b/lldb/tools/lldb-instr/CMakeLists.txt
@@ -12,3 +12,8 @@ add_lldb_tool(lldb-instr
     clangTooling
 
   )
+target_link_libraries(
+  lldb-instr
+  PRIVATE
+    LLVMSupport
+  )
```

Shall I submit this?

**Comment by JDevlieghere** [comment]
This is probably the result of e12a950d90f88aeddaa97d6e7c8fd0bfedc42f73. Let's make sure that if we undo that we don't break the Xcode build in the process.

**Comment by KyleFromKitware** [comment]
That looks like it is almost certainly the cause, considering what the fix looks like.

**Comment by KyleFromKitware** [comment]
I'm also investigating if this might be a CMake bug, I'll report here when I know more.

**Comment by KyleFromKitware** [comment]
I just tried building on Xcode with the commit before e12a950 and it built fine, even with two references to `libLLVMSupport.a`. @jimingham could you please tell me how to reproduce the build that failed without e12a950?

**Comment by JDevlieghere** [comment]
I was able to reproduce the issue too. Here's what I did:

Perform a standalone build of LLVM+Clang:
```
$ cmake ../llvm-project/llvm \
    -G Ninja \
    -DCMAKE_BUILD_TYPE='RelWithDebInfo' \
    -DLLVM_ENABLE_ASSERTIONS:BOOL=ON \
    -DLLVM_ENABLE_PROJECTS='llvm;clang'
$ ninja
```

Perform a standalone build of LLDB:

```
$ cmake ../llvm-project/lldb  \
    -C../llvm-project/lldb/cmake/caches/Apple-lldb-Xcode.cmake \
    -DLLVM_DIR=<absolute path to standalone llvm build>/lib/cmake/llvm \
    -DClang_DIR=<absolute path to standalone llvm build>/lib/cmake/clang
$ cmake --build .
```

**Comment by KyleFromKitware** [comment]
@JDevlieghere What version of Xcode are you using? I just tried this with Xcode 12.2 and it built fine.

**Comment by JDevlieghere** [comment]
I'm using Xcode 14.2

**Comment by aheejin** [comment]
I'm having this problem too. It looks the CL (https://reviews.llvm.org/D142241) descrpition says having `CLANG_LIBS` and `LINK_COMPONENTS Support` within a single file is a problem, but there are many files in lldb that use both:
```
./lldb/source/Core/CMakeLists.txt
./lldb/source/Plugins/TypeSystem/Clang/CMakeLists.txt
./lldb/source/Plugins/LanguageRuntime/ObjC/AppleObjCRuntime/CMakeLists.txt
./lldb/source/Plugins/LanguageRuntime/RenderScript/RenderScriptRuntime/CMakeLists.txt
./lldb/source/Plugins/ExpressionParser/Clang/CMakeLists.txt
./lldb/source/Plugins/Platform/MacOSX/CMakeLists.txt
./lldb/source/Plugins/SymbolFile/DWARF/CMakeLists.txt
./lldb/source/Plugins/SymbolFile/NativePDB/CMakeLists.txt
./lldb/source/Plugins/SymbolFile/PDB/CMakeLists.txt
```

I'm not familiar with Xcode build. Are these other files fine with Xcode? If so, what's the difference between `lldb-instr/CMakeLists.txt` and those files?

**Comment by aheejin** [comment]
cc @jimingham

**Comment by aheejin** [comment]
Gentle ping.

**Comment by aheejin** [comment]
I have a CL that reverts the change: https://reviews.llvm.org/D145181

I kept asking why this is a problem, in many places so far:
- Comment on the original CL: https://reviews.llvm.org/D142241#4116206
- LLVM discourse: https://discourse.llvm.org/t/build-shared-libs-on-doesnt-work-with-lldb-instr/68793
- New CL description: https://reviews.llvm.org/D145181
- Here: https://github.com/llvm/llvm-project/issues/60314#issuecomment-1452783518

None of these got any answers so far. I've been building LLVM + LLDB using `-DBUILD_SHARED_LIBS=ON` for many years because that option reduces link time a lot, and that doesn't work anymore.

Can I go ahead and commit my reverting change? Is that the only way I can get an answer?

**Comment by JDevlieghere** [comment]
Hi Heejin,

> I have a CL that reverts the change: https://reviews.llvm.org/D145181
> 
> I kept asking why this is a problem, in many places so far, over a month:
> 
> * Comment on the original CL: https://reviews.llvm.org/D142241#4116206
> * LLVM discourse: https://discourse.llvm.org/t/build-shared-libs-on-doesnt-work-with-lldb-instr/68793
> * New CL description: https://reviews.llvm.org/D145181
> * Here: [Building lldb-instr fails with undefined reference to symbol when building with BUILD_SHARED_LIBS=ON #60314 (comment)](https://github.com/llvm/llvm-project/issues/60314#issuecomment-1452783518)
> 
> None of these got any answers so far. 

Posting the same thing in multiple places is not going to help. It just creates more noise. Especially if the comment is not particularly constructive. I understand this issue is Xcode/macOS specific and not everyone has access to that platform, so you probably need some help from us. I think you raised a good point about other places that are doing something similar and I don't know why that works. I suspect it has something to do with those things building static libraries vs `lldb-instr` which is an executable. 

Probably the best next step if for someone that can reproduce the issue (like @jimingham or myself) to compare the linker invocations. At the same time I'm curious if both of you are using the same linker (`lld`?) and if that might have something to do with it. Something you could try is seeing if the same thing happens with `gold` or the `bfd`.

> I've been building LLVM + LLDB using `-DBUILD_SHARED_LIBS=ON` for many years because that option reduces link time a lot, and that doesn't work anymore.

I understand it's frustrating that this configuration is broken. As I explained in the patch you put up, reverting the change will break another configuration. We need a solution that works for both. 

> Can I go ahead and commit my reverting change? Is that the only way I can get an answer?

Please take a look at the [LLVM Code-Review Policy and Practices](https://llvm.org/docs/CodeReview.html). Among other things, it explains that a week is a good cadence to ping. People can be busy, or they can be out sick or on vacation (like I was during the second half of February).

**Comment by aheejin** [comment]
> > Can I go ahead and commit my reverting change? Is that the only way I can get an answer?
> 
> Please take a look at the [LLVM Code-Review Policy and Practices](https://llvm.org/docs/CodeReview.html). Among other things, it explains that a week is a good cadence to ping. People can be busy, or they can be out sick or on vacation (like I was during the second half of February).

I understand that, but I also would like to point out that the first day I commented on the original CL was Feb 9. So I'm not sure if it's accurate to say I didn't wait for a week.

And I'd also like to note that commits that break the build are often reverted by others to fix the build. In this case I think the difference is this combination of build is not tested in our CI and has relatively fewer users, which is the reason I asked.


> I think you raised a good point about other places that are doing something similar and I don't know why that works. I suspect it has something to do with those things building static libraries vs `lldb-instr` which is an executable.
> 
> Probably the best next step if for someone that can reproduce the issue (like @jimingham or myself) to compare the linker invocations. At the same time I'm curious if both of you are using the same linker (`lld`?) and if that might have something to do with it. Something you could try is seeing if the same thing happens with `gold` or `bfd`.

Thanks for the pointer. I'm using lld, and given that I didn't tweak any configurations on that part, I think that's the default setting. I can try changing it to `gold` and see what happens.

**Comment by JDevlieghere** [comment]
Given that Kyle couldn't reproduce the issue with Xcode 12.2, I tried reproducing this again with Xcode 14.3 beta 3 to investigate this further. But to my surprise, I'm not able to reproduce the original issue anymore. Either a newer Xcode or a newer CMake fixed (or hides) the issue. I asked Jim to do the same and he doesn't encounter it anymore either. I'm not confident this won't pop up again in the future, but as this no longer breaks our workflow, I don't mind reverting the original patch. 

I can revert the patch or Heejin or Kyle can land their revert if they want.

**Comment by aheejin** [comment]
That sounds good! Thanks for investigating this.

**Comment by xtemp09** [comment]
Will the fix be ported to 16.X branch? Can't wait to compile 16.0.X without manually fixing the source.
