### ISSUE TITLE
[Clang] [Concepts] Regression between 15.x and trunk: satisfaction of constraint depends on itself

### ISSUE THREAD

**Issue by JoeLoser** [llvm/llvm-project#60323]
https://godbolt.org/z/vEb55MGrM is a reproducer that occurs at least in 0d6b26b4d3e3991da16f5b7f53e397b0051e8598 and on current trunk, but did not occur in 7520d187cf0dedcf5085f71bc1a5472c75cc8dbb as far as I can tell.  It would be good to fix this and get it into LLVM 16 before the release.

The bug here seems to be that Clang is looking at the textual form of the requires-clause and deciding that "requires { go(t); } depends on requires { go(t); }"; but the two requires-clauses are in different class scopes, where the word go refers to completely different member functions.

Explicitly specifying which `go` we're referring to by using `this` is a workaround as you can see in https://godbolt.org/z/Gccahddnf

**Comment by shafik** [comment]
CC @erichkeane

**Comment by erichkeane** [comment]
Aaron showed me this... its on my list.

**Comment by erichkeane** [comment]
Hrmph... The work to prevent us from infinite-looping here checks the current expression/args against a stack of expressions/args we've seen before.  We have to do so before the expression is instantiated because the recursion is caused by the act of instantiating (that is, instantiating a constraint expression causes its constraints to be evaluated).

Unfortunately, when the constraint expression is an unresolved call expression with the same name, they 'look' the same at that point.  I have a couple of ideas of what might be possible to relax this check at the expense of making the recursive check a little less accurate (or at least, take a little longer to catch), but hopefully will fix this too.

**Comment by JoeLoser** [comment]
> Hrmph... The work to prevent us from infinite-looping here checks the current expression/args against a stack of expressions/args we've seen before. We have to do so before the expression is instantiated because the recursion is caused by the act of instantiating (that is, instantiating a constraint expression causes its constraints to be evaluated).
> 
> Unfortunately, when the constraint expression is an unresolved call expression with the same name, they 'look' the same at that point. I have a couple of ideas of what might be possible to relax this check at the expense of making the recursive check a little less accurate (or at least, take a little longer to catch), but hopefully will fix this too.

Thanks for the quick fix, Erich!  Can we also backport this for the 16 release, please?  

CC: @Quuxplusone

**Comment by erichkeane** [comment]
I've put up the request to cherry-pick it here to 16.0 here: https://github.com/llvm/llvm-project/issues/60341

Note: You might not get a response from your CC, he's been banned from participating in the LLVM Community.
