### ISSUE TITLE
[Flang] SimplifyIntrinsics reports unexpected assertion `rank > 0 && "rank cannot be zero"' failed.

### ISSUE THREAD

**Issue by sscalpone** [llvm/llvm-project#60356]
```console
% cat f.f90
function mc(m)
    logical(4) :: m(:,:,:)
    mc = Count(m)
end
```
```console
% flang f.f90
f18: /proj/build/llvm/Linux_x86_64/flang/lib/Optimizer/Transforms/SimplifyIntrinsics.cpp:173: void genReductionLoop(fir::FirOpBuilder&, mlir::Type, mlir::func::FuncOp&, InitValGeneratorTy, BodyOpGeneratorTy, unsigned int): Assertion `rank > 0 && "rank cannot be zero"' failed.
Aborted
```

**Comment by sscalpone** [comment]
Perhaps related to https://github.com/llvm/llvm-project/commit/7d2e198729df14a7e025d44ae8aa21ce14be9baa

**Comment by Leporacanthicus** [comment]
I'll take a look on Monday.

**Comment by sscalpone** [comment]
Verified

**Comment by Leporacanthicus** [comment]
We are looking at why this is actually hitting the assert (the number of dimensions should be 3 in this case). It has to do with how we're trying to find the "originating array", the problem is really to find a good way to find the properties of the input, without additional runtime.

Thanks to @SachaBallantyne for the fix, by the way.
