### ISSUE TITLE
Possible incorrect code generation when using variable templates

### ISSUE THREAD

**Issue by jonas-eschmann** [llvm/llvm-project#60373]
Hello,

I'm encountering an issue with member variables not being initialised properly after moving from GCC to Clang. I managed to boil it down to the following minimal example:

```cpp
template <typename T>
struct A{
    int x = 10;
};

template <typename T>
struct B{
    A<T> a;
};

template <typename T>
A<T> a;

template <typename T>
auto aa = a<T>;

template <typename T>
B<T> b = {
    aa<T>
};

int main(){
    return b<float>.a.x;
}
```

[Same example on the compiler explorer](https://godbolt.org/z/5aG8TWzTx)

I'm expecting it to return `10` (which GCC does) but Clang returns `0`

Best regards!
Jonas

**Comment by shafik** [comment]
@erichkeane wdyt? There is a lot going on, MSVC seems to agree with clang but I am not sure if I am missing something subtle here.

**Comment by royjacobson** [comment]
Looks wrong to me as well.

**Comment by erichkeane** [comment]
I have no idea here :)  I find myself wondering if there is some sort of non-guaranteed initialization order happening here?  If you look at the assembly, `a<float>` IS initialized to be 10, though all the otherse are zero-init'ed.  Its a bit confusing why it wouldn't be `10` for the result here, but I have no idea whether it is something the standard is unclear about (particularly because MSVC agrees with us).

**Comment by royjacobson** [comment]
Ah, that explains it. If you look at the global guard variable guards I think it's pretty clear :)

BTW, if you make `a<T>` a `constexpr` var you get the expected result.

**Comment by shafik** [comment]
It looks like this changed recently and now output the expected value in trunk: https://godbolt.org/z/z3GeohMxv
