### ISSUE TITLE
Sanitizer test regressions (mostly ASAN)

### ISSUE THREAD

**Issue by mgorny** [llvm/llvm-project#60394]
I've noticed them around the beginning of January (I'm sorry for not reporting earlier), they don't seem to related to any change in LLVM (i.e. once they started appearing, they happened with older versions as well):

```
Failed Tests (39):
  AddressSanitizer-i386-linux :: TestCases/printf-2.c
  AddressSanitizer-i386-linux :: TestCases/printf-3.c
  AddressSanitizer-i386-linux :: TestCases/printf-5.c
  AddressSanitizer-i386-linux :: TestCases/strcat-overlap.cpp
  AddressSanitizer-i386-linux :: TestCases/strcpy-overlap.cpp
  AddressSanitizer-i386-linux :: TestCases/strncat-overlap.cpp
  AddressSanitizer-i386-linux :: TestCases/strncpy-overflow.cpp
  AddressSanitizer-i386-linux :: TestCases/strncpy-overlap.cpp
  AddressSanitizer-i386-linux-dynamic :: TestCases/printf-2.c
  AddressSanitizer-i386-linux-dynamic :: TestCases/printf-3.c
  AddressSanitizer-i386-linux-dynamic :: TestCases/printf-5.c
  AddressSanitizer-i386-linux-dynamic :: TestCases/strcat-overlap.cpp
  AddressSanitizer-i386-linux-dynamic :: TestCases/strcpy-overlap.cpp
  AddressSanitizer-i386-linux-dynamic :: TestCases/strncat-overlap.cpp
  AddressSanitizer-i386-linux-dynamic :: TestCases/strncpy-overflow.cpp
  AddressSanitizer-i386-linux-dynamic :: TestCases/strncpy-overlap.cpp
  AddressSanitizer-x86_64-linux :: TestCases/printf-2.c
  AddressSanitizer-x86_64-linux :: TestCases/printf-3.c
  AddressSanitizer-x86_64-linux :: TestCases/printf-5.c
  AddressSanitizer-x86_64-linux :: TestCases/strcat-overlap.cpp
  AddressSanitizer-x86_64-linux :: TestCases/strcpy-overlap.cpp
  AddressSanitizer-x86_64-linux :: TestCases/strncat-overlap.cpp
  AddressSanitizer-x86_64-linux :: TestCases/strncpy-overflow.cpp
  AddressSanitizer-x86_64-linux :: TestCases/strncpy-overlap.cpp
  AddressSanitizer-x86_64-linux-dynamic :: TestCases/printf-2.c
  AddressSanitizer-x86_64-linux-dynamic :: TestCases/printf-3.c
  AddressSanitizer-x86_64-linux-dynamic :: TestCases/printf-5.c
  AddressSanitizer-x86_64-linux-dynamic :: TestCases/strcat-overlap.cpp
  AddressSanitizer-x86_64-linux-dynamic :: TestCases/strcpy-overlap.cpp
  AddressSanitizer-x86_64-linux-dynamic :: TestCases/strncat-overlap.cpp
  AddressSanitizer-x86_64-linux-dynamic :: TestCases/strncpy-overflow.cpp
  AddressSanitizer-x86_64-linux-dynamic :: TestCases/strncpy-overlap.cpp
  DataFlowSanitizer-x86_64 :: custom.cpp
  DataFlowSanitizer-x86_64 :: origin_unaligned_memtrans.c
  MemorySanitizer-X86_64 :: chained_origin_memcpy.cpp
  MemorySanitizer-X86_64 :: chained_origin_memmove.cpp
  ThreadSanitizer-x86_64 :: exceptions.cpp
  ThreadSanitizer-x86_64 :: fiber_longjmp.cpp
  ThreadSanitizer-x86_64 :: signal_longjmp.cpp
```

Gentoo Linux amd64
Kernel: 6.1.8-gentoo-dist
glibc: 2.36-r7
systemd: 252.5 (testing is done in nspawn container)

Full log (2.5M): [sys-libs:compiler-rt-sanitizers-16.0.0_rc1:20230130-193656.log](https://github.com/llvm/llvm-project/files/10539390/sys-libs.compiler-rt-sanitizers-16.0.0_rc1.20230130-193656.log)

**Comment by vitalybuka** [comment]
I guess it's not a regression, but something changed in glibc.

**Comment by mgorny** [comment]
I thought that it was maybe the kernel but 5.15.90 fails the same (unless it was a kernel change backported to 5.15 ;-)).

**Comment by mgorny** [comment]
I have seen the same set of failures on 2023-01-12 (on top of 6dc85bd3fde7df2999fda07e9e9f2e83d52c6125) but almost all tests passed on 2023-01-08 (with the same commit). I did not upgrade glibc during that period.

**Comment by mgorny** [comment]
I see the same failures outside the nspawn container, so it's not that either. I've checked install logs for the aforementioned period and I don't see anything obvious that could have caused this — so most likely it was some kernel change that was backported to 5.15. Unfortunately, I don't have the old kernel binpkgs around anymore.

**Comment by thesamesam** [comment]
Posted https://reviews.llvm.org/D143322. We may want to file another bug for the remaining 3 issues I get (no idea if mgorny gets them yet).

**Comment by mgorny** [comment]
I can confirm that the patch fixes all test failures for me.

**Comment by MaskRay** [comment]
For posterity, the issues were due to Gentoo's `-D_FORTIFY_SOURCE=2` in a configuration file.

When `_FORTIFY_SOURCE` is enabled, some library functions are redirected to `*_chk`.
Interceptors don't provide `*_chk` (with an exception <https://reviews.llvm.org/D40951>), so we just end up with fewer detected errors (e.g. asan, tsan) or false positives (msan).

Added this to my https://maskray.me/blog/2023-01-08-all-about-sanitizer-interceptors

**Comment by tru** [comment]
I am guessing this fix should be picked into the release branch as well? Run the cherry-pick command in that case, reopen until we have decision on that.

**Comment by thesamesam** [comment]
Ah, I filed a separate issue for that: https://github.com/llvm/llvm-project/issues/60533.

**Comment by tru** [comment]
Ah nice I just merged that one as well. Thanks for the fix!

**Comment by thesamesam** [comment]
Thank you!

**Comment by mstorsjo** [comment]
Unfortunately, this fix in 8ab762557fb057af1a3015211ee116a975027e78, flat out disabling any default config files, break other potential use cases.

In llvm-mingw, I set a bunch of custom defaults for the mingw cross compilation targets (`-rtlib=compiler-rt -unwindlib=libunwind -stdlib=libc++ -fuse-ld=lld`). These defaults could in theory be set in a couple different ways:
- The options can be passed explicitly by using a wrapper script/executable - this is what I currently do
- The options can be hardcoded in Clang by building clang with options like `-DCLANG_DEFAULT_RTLIB=compiler-rt`. This is terrible, as this Clang binary can't be used for any other targets where these options don't fit.
- The options could be set in target specific config files, so that any way that clang (or related tools like clangd, clang-scan-deps etc) is invoked for such a target, it picks up these right defaults

I tried switching llvm-mingw over to the third option, in https://github.com/mstorsjo/llvm-mingw/commit/6939aee0c0eb6fe0ce8b1f82f53b05b03aa4226c and https://github.com/mstorsjo/llvm-mingw/commit/4bff0298c5189b9eec5591a702db009b01291288. However, then running the compiler-rt tests fail, because of `CLANG_NO_DEFAULT_CONFIG=1` from 8ab762557fb057af1a3015211ee116a975027e78 - see e.g. https://github.com/mstorsjo/llvm-mingw/actions/runs/11319240849/job/31483785448.


So for the cases where the system Clang uses a global config that adds an extra option that we want to skip (to make a more "vanilla" compilation), like Gentoo's `-D_FORTIFY_SOURCE=2`, running tests with `CLANG_NO_DEFAULT_CONFIG=1` works fine. But the compiler default config files can also be essential options for the compiler to work at all - and then this env variable is breaking things.

I'm not entirely sure how to best deal with this. I mean, I guess we could add an option, for when configuring compiler-rt for running tests, for the user to pick whether to override clang config files or not. But this is rather obscure...

Or should we have some sort of cmake configure level test, to see whether the compiler still works if we set `CLANG_NO_DEFAULT_CONFIG=1`, and only set it in the testsuite if seems to work and not break the compiler?

**Comment by mstorsjo** [comment]
> I'm not entirely sure how to best deal with this. I mean, I guess we could add an option, for when configuring compiler-rt for running tests, for the user to pick whether to override clang config files or not. But this is rather obscure...
> 
> Or should we have some sort of cmake configure level test, to see whether the compiler still works if we set `CLANG_NO_DEFAULT_CONFIG=1`, and only set it in the testsuite if seems to work and not break the compiler?

I posted a PR that tries to fix this now, in https://github.com/llvm/llvm-project/pull/113491.

**Comment by thesamesam** [comment]
I'm sorry that I missed your earlier comment!
