### ISSUE TITLE
[flang] Compiler emits incorrect arguments for CHARACTER type in llvm

### ISSUE THREAD

**Issue by MucTepDayH16** [llvm/llvm-project#60395]
```console
flang-new version 17.0.0 (https://github.com/llvm/llvm-project.git 3af9dfe464446da8e9acea45681df28b18583370)
Target: x86_64-unknown-linux-gnu
```

Given the following code `a.f`:
```fortran
      SUBROUTINE AR(TRANSA,TRANSB,LDA)
      CHARACTER TRANSA,TRANSB
      INTEGER LDA

      PRINT *, TRANSA, TRANSB, LDA

      END
```

Building with `flang-new -c a.f -emit-llvm -S` produce this llvm ir:
```ll
...
define void @ar_(ptr %0, ptr %1, ptr %2, i64 %3, i64 %4) {
  %6 = insertvalue { ptr, i64 } undef, ptr %1, 0
  %7 = insertvalue { ptr, i64 } %6, i64 %4, 1
  %8 = insertvalue { ptr, i64 } undef, ptr %0, 0
  %9 = insertvalue { ptr, i64 } %8, i64 %3, 1
  %10 = extractvalue { ptr, i64 } %9, 0
  %11 = extractvalue { ptr, i64 } %9, 1
  %12 = extractvalue { ptr, i64 } %7, 0
  %13 = extractvalue { ptr, i64 } %7, 1
  %14 = call ptr @_FortranAioBeginExternalListOutput(i32 -1, ptr @_QQcl.2F726F6F742F6C617061636B2D72656C656173652F612E6600, i32 5)
  %15 = call i1 @_FortranAioOutputAscii(ptr %14, ptr %10, i64 1)
  %16 = call i1 @_FortranAioOutputAscii(ptr %14, ptr %12, i64 1)
  %17 = load i32, ptr %2, align 4
  %18 = call i1 @_FortranAioOutputInteger32(ptr %14, i32 %17)
  %19 = call i32 @_FortranAioEndIoStatement(ptr %14)
  ret void
}
...
```

Arguments `%3` and `%4` denote the lengths or CHARACTER arguments and are unused, but this is not what expected in case of single CHARACTER as in arguments in `a.f`. It is also depicted in `_FortranAioOutputAscii` call, where the value `i64 1` is passed as length. Seem like flang interprets CHARACTER type as string of length 1, but not the single character. This leads to unsound function signatures in ffi. For example, it is expected for `dgemm_` subroutine from BLAS to receive `13 x ptr` as arguments, but flang generate function with `13 x ptr` and `2 x i64` for it, since in has two `CHARACTER` arguments.

**Comment by jeanPerier** [comment]
Hi, thanks for opening the issue.

Can you be more specific by what you mean by "This leads to unsound function signatures in ffi.". Did you run into runtime/compilation issues ?

> Seem like flang interprets CHARACTER type as string of length 1, but not the single character.

Indeed, as far as I know, `CHARACTER` is absolutely equivalent to `CHARACTER(LEN=1)`. The standards says in 7.4.4.2 point 4. (Fortran 2018 ISO standard draft N2162): _"If the length is not specified in a char-selector or a * char-length, the length is 1."_.

For the rational, fortran characters scalars are always passed as address + length, even when the length is a constant that is known inside the subprogram (like here, with length one), because in Fortran 77 with implicit interface, it is not known on implicit call site if the function expects a CHARACTER(*) or a CHARACTER(1).

Most if not all compiler follow the same calling convention (it is a goal of flang to be interoperable with gfortran compiled code on F77 code like here).

If you look at how gfortran calls "AR", it is passing to extra integer "1" arguments: https://godbolt.org/z/q8MT4cM6d.

The only place where CHARACTER(LEN=1) acquire some special passing convention compared to other characters is when using CHARACTER(1), VALUE in a BIND(C) interface (but that is a Fortran 2018 feature that require explicit interfaces). In this case, the character value is passed in register without an extra length argument.

**Comment by MucTepDayH16** [comment]
I've got it. I just thought that I can use blas and lapack built with flang in C. There are some explanation in original LAPACK repo about these arguments so I just have to use modified headers. Thanks, I'll close this issue
