### ISSUE TITLE
[C++20] [Modules] Failed to export declarations within language linkage

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#60405]
Here is the reproducer:

```c++
//--- M.cppm
export module M;
export extern "C++" foo() {}

//--- Use.cpp
import M;
int Use() { foo() }
```

The above reproducer is expected to be accepted but clang rejects it since clang feel all the things in global module is invisible outside the module unit. But this is not correct.

**Comment by iains** [comment]
So for this:
```
export module A;
export int foo () { return 0; }
export extern "C++" int bar () { return 2; }
```

we have the following AST:

```
|-ExportDecl 0x13d855750 </scratch/12-mon/llvm-main/p.cpp:4:1, col:31> col:1 imported in A
| `-FunctionDecl 0x13d8556a0 <col:8, col:31> col:12 imported in A hidden foo 'int ()' linkage-extern VisibleWhenImported
|   `-CompoundStmt 0x13d904928 <col:19, col:31>
|     `-ReturnStmt 0x13d904918 <col:21, col:28>
|       `-IntegerLiteral 0x13d9048f8 <col:28> 'int' 0
|-ExportDecl 0x13d8555d8 <line:6:1, col:44> col:1 imported in A
| `-LinkageSpecDecl 0x13d855580 <col:8, col:44> col:15 imported in A.<global> C++
|   `-FunctionDecl 0x13d8554d0 <col:21, col:44> col:25 imported in A.<global> hidden bar 'int ()' linkage-extern ReachableWhenImported
|     `-CompoundStmt 0x13d904970 <col:32, col:44>
|       `-ReturnStmt 0x13d904960 <col:34, col:41>
|         `-IntegerLiteral 0x13d904940 <col:41> 'int' 2
```
So the question is how to approach this; where (or whether) we should update the visibility (or whether it would be better to special-case this when processing candidate decls).

**Comment by ChuanqiXu9** [comment]
Yeah, the root problem for this is that I confused the idea about "global module" and "global module fragment". Currently, there is no idea about "global module" in clang now.

When I implement `extern "C++"` in modules, I attach all the declarations in `extern "C++"` to "global module fragment". But this is not consistent with the spec. The spec says the declarations in `extern "C++"` are attached to "global module" instead of "global module fragment". This is the root problem. The key differences are that the declarations in "global module fragment" is not visible to other units and the declarations in "global module fragment" can be discarded. But it is not true for declarations in "global module".

Although we can close the issue report by setting the visibility for declarations inside the export decl, it should be better to solve the root problem.

**Comment by iains** [comment]
Yes, OK I see your point .. but also:

https://eel.is/c++draft/module#unit-6

We also have the situation in https://eel.is/c++draft/module#interface-5 (exported using declarations)

This case seems somewhat similar to the exported using declaration - so that I wonder if we really need some completely new mechanism?

**Comment by ChuanqiXu9** [comment]
> We also have the situation in https://eel.is/c++draft/module#interface-5 (exported using declarations)
>
> This case seems somewhat similar to the exported using declaration - so that I wonder if we really need some completely new mechanism?

As a user, do I **really** need the mechanism? No. But as language implementors, we (the compiler developers more than us) still need to implement this in the end of the day. So I registered the issue to give a note.

Also it is necessary to move declarations in `extern "C++"` out of `global module fragment`, if we want to discard declarations in GMF.

> Yes, OK I see your point .. but also:
>
> https://eel.is/c++draft/module#unit-6

Yeah, https://eel.is/c++draft/module#unit-7.2.2 says the declarations in the language linkage should be attached to the global module. But [module.unit]p6 says: "The [global module](https://eel.is/c++draft/module#def:module,global) is the collection of all [global-module-fragment](https://eel.is/c++draft/module#nt:global-module-fragment)s and all translation units that are not module units[.](https://eel.is/c++draft/module#unit-6.sentence-1)". So the wording looks conflicting.

**Comment by iains** [comment]
> > We also have the situation in https://eel.is/c++draft/module#interface-5 (exported using declarations)
> > This case seems somewhat similar to the exported using declaration - so that I wonder if we really need some completely new mechanism?
> 
> As a user, do I **really** need the mechanism? No. But as language implementors, we (the compiler developers more than us) still need to implement this in the end of the day. So I registered the issue to give a note.

OK - let us see what design would come out of this.
 
> Also it is necessary to move declarations in `extern "C++"` out of `global module fragment`, if we want to discard declarations in GMF.

We should **not** be trying to discard an exported GMF declaration (in the same way that we should not discard the GMF entry that is referred to by a using declaration), at least that is my understanding (and my draft GMF decl elision patch should comply).

**Comment by ChuanqiXu9** [comment]
> We should not be trying to discard an exported GMF declaration (in the same way that we should not discard the GMF entry that is referred to by a using declaration), at least that is my understanding (and my draft GMF decl elision patch should comply).

Yes. As implementors, we are able to workaround such things. What I am worrying is the bigger inconsistence of the implementation and the wording. From https://eel.is/c++draft/module.global.frag#3, I can't find any words saying that we shouldn't discard things they are exported. I know there are already many inconsistences. But it is still a little bit scary to me.
(I wouldn't argue if you feel I worry too much things )

**Comment by iains** [comment]
So, after reading core's response, I think we have a reasonable implementation (the C++ linkage entity is placed in the GMF) but the bug is that we only make it reachable and not visible.

Since we can tell that this is the case of an exported C++ linkage entity, we can make it visible.

I agree that I did not find exact wording that specifies this specific case as one in which the GMF entry is not elided (for the optional GMF decl elision) - but I think it is covered by https://eel.is/c++draft/module.global.frag#3.1 / https://eel.is/c++draft/module.global.frag#3.2 since "contains an id-expression" applies (since "contains" != "is").

**Comment by ChuanqiXu9** [comment]
> So, after reading core's response, I think we have a reasonable implementation (the C++ linkage entity is placed in the GMF) but the bug is that we only make it reachable and not visible.

I don't think so. The discussion in core is about whether [module.unit]p6 is conflicting with [module.unit]p7. The discussion is not about whether the declarations in language linkage is part of the global module fragment.

It will be extremely odd that we can discard the declarations in the language linkage. Since if we define an entity in language linkage in the module purview, it implies that we want a definition with normal language linkage. And it makes no sense to discard such declarations.

> I agree that I did not find exact wording that specifies this specific case as one in which the GMF entry is not elided (for the optional GMF decl elision) - but I think it is covered by https://eel.is/c++draft/module.global.frag#3.1 / https://eel.is/c++draft/module.global.frag#3.2 since "contains an id-expression" applies (since "contains" != "is").

[module.global.frag]p3 is about whether a declaration D is decl-reachable to another declaration S. (If we think the declaration in the language linkage belongs to the GMF). It is possible that the declaration 'D' in the language linkage is not decl-reachable to any other declaration S in the same TU.

I suggest we should start an another thread for:
(1) Whether the declarations in the language linkage belongs to GMF or not.
(2) If the declarations in the language linkage is discardable per [module.global.frag].

**Comment by iains** [comment]
> > So, after reading core's response, I think we have a reasonable implementation (the C++ linkage entity is placed in the GMF) but the bug is that we only make it reachable and not visible.
> 
> I don't think so. The discussion in core is about whether [module.unit]p6 is conflicting with [module.unit]p7. The discussion is not about whether the declarations in language linkage is part of the global module fragment.

As I read it, the response  was clarifying the difference between attachment to a module, c.f. the purview in which it appears.

-- so we have a language linkage declaration that appears in the the module purview but it *is* attached to the global module.   In terms of clang's implementation (at present) we signify attachment to the global module by placing the decl into the GMF,  I we are proposing to change that, we will need a way to specify the global module that is distinct from the GMF (and somehow signify that current decls in the GMF are attached to it - since in the absence of any other factor, decls are attached the module for the purview in which they appear).

> It will be extremely odd that we can discard the declarations in the language linkage. Since if we define an entity in language linkage in the module purview, it implies that we want a definition with normal language linkage. And it makes no sense to discard such declarations.

Absolutely agreed.

> > I agree that I did not find exact wording that specifies this specific case as one in which the GMF entry is not elided (for the optional GMF decl elision) - but I think it is covered by https://eel.is/c++draft/module.global.frag#3.1 / https://eel.is/c++draft/module.global.frag#3.2 since "contains an id-expression" applies (since "contains" != "is").
> 
> [module.global.frag]p3 is about whether a declaration D is decl-reachable to another declaration S. (If we think the declaration in the language linkage belongs to the GMF). It is possible that the declaration 'D' in the language linkage is not decl-reachable to any other declaration S in the same TU.
> 
> I suggest we should start an another thread in wg21 for: (1) Whether the declarations in the language linkage belongs to GMF or not.

IMO the language requirements are already specified - what we are debating here is how to implement this in clang (and whether what we currently do is an acceptable engineering solution).

> (2) If the declarations in the language linkage is discardable per [module.global.frag].

Yes, perhaps we should ask for clarification of this (even though we both agree that elision of any such decl would not make sense).   Perhaps that just falls out of the comment above (that we **signify** attachment to the global module in our implementation by  placing it in the GMF)

**Comment by ChuanqiXu9** [comment]
> edit: and remembering that the global module is made up of all GMFs + non modular units (so that something being part of the global module is reasonably represented by it being present in some GMF) ... Imagine that we have multiple GMFs for one TU (one for themodule; ...and one for each export "C++" .... 

OK. The note works for me. 

> Yes, perhaps we should ask for clarification of this

Yeah, I think this is still necessary.

**Comment by iains** [comment]
I would like to spell out the design concerns here (so that we can be sure what we are deciding about).

1. Currently, we have a single pointer in a decl that records the module "ownership". 
2. We do not specify whether "ownership" means "attachment" or "purview" (or the empty case of not belonging to any module).
3. For the majority of decls this is not important, since they are attached to the same module as the purview in which they appear.
4. For a (believed to be be) small set of cases the attachment is to a different module than the purview in which they appear.

- A) It would seem (to me, at least) a very big hammer to add an extra pointer to every decl to cater for case (4).
- B) We could decide that the "ownership" pointer always means "attached" and handle the cases (4) specially as needed [assuming that we always have some mechanism to disambiguate them]
- C) We could invent some escape mechanism that allows us to indirect a pair of pointers from the "ownership" such that we could specify the "attachment" and lexical "purview" separately.
- 

As noted above, the GM is made up of GMFs so that we can signify "attachment" to the GM by placing a decl in **a** GMF.
Since there is nothing special about one GMF c.f. any other, we do not need to make multiple GMFs per TU to cater for this, we can simply append a new decl to an existing GMF.

From my reading, a language ,linkage export is not part of "**the**" GMF (even though as just mentioned we can place it in **a** GMF to indicate attachment), so that, even if not covered by other rules in https://eel.is/c++draft/module.global.frag#3 I do not think there is any reason we would expect to consider it as a candidate for elision.

**Comment by iains** [comment]
@Bigcheese This is the discussion about how to represent module purview C++ language linkage exports ( I realise that there is a lot of importance in the difference in the EN_xx language separation of "**a** thing" and "**the** thing" )

**Comment by ChuanqiXu9** [comment]
Thanks for the written-up!

> A) It would seem (to me, at least) a very big hammer to add an extra pointer to every decl to cater for case (4).
> B) We could decide that the "ownership" pointer always means "attached" and handle the cases (4) specially as needed [assuming that we always have some mechanism to disambiguate them]
> C) We could invent some escape mechanism that allows us to indirect a pair of pointers from the "ownership" such that we could specify the "attachment" and lexical "purview" separately.
edit : but, of course, default to using a single pointer, otherwise we fall back into the very big hammer case.

Basically agreed. But C looks not necessary for me. Do you mean we need it for implementing `extern "C++"`? I have other ideas.

> As noted above, the GM is made up of GMFs so that we can signify "attachment" to the GM by placing a decl in a GMF.
Since there is nothing special about one GMF c.f. any other, we do not need to make multiple GMFs per TU to cater for this, we can simply append a new decl to an existing GMF.

I feel it is not bad to have multiple GMFs in one TU. It is straight forward and consistent with the spec.

BTW, I feel a little bit odd for the wording "we can simply append a new decl to an existing GMF". Since we can't iterate declarations in a module. But this might not be important to this thread.

> From my reading, a language ,linkage export is not part of "the" GMF (even though as just mentioned we can place it in a GMF to indicate attachment), so that, even if not covered by other rules in https://eel.is/c++draft/module.global.frag#3 I do not think there is any reason we would expect to consider it as a candidate for elision.

Fully agreed.

---

My design in brain is that we can introduce another ModuleKind "GeneralGlobalModuleFragment" (Or any other name). (Maybe we need to rename module kind `GlobalModuleFragment` to `TheGlobalModuleFragment`.) And each language linkage block corresponds to a `GeneralGlobalModuleFragment`. (Or all the language linkage block refers to the same `GeneralGlobalModuleFragment`, this doesn't matter).

Then we can introduce `Module::isGlobalModule()`. Its definition should be `Kind == GlobalModuleFragment || Kind == GeneralGlobalModuleFragment;`. Then things should work after we replace a lot of `Module::isGlobalModuleFragment()` with `Module::isGlobalModule()`.

And for your discarding patch, it will be easy for you to check "the" global module fragment.

**Comment by iains** [comment]
> Thanks for the written-up!
> 
> > A) It would seem (to me, at least) a very big hammer to add an extra pointer to every decl to cater for case (4).
> > B) We could decide that the "ownership" pointer always means "attached" and handle the cases (4) specially as needed [assuming that we always have some mechanism to disambiguate them]
> > C) We could invent some escape mechanism that allows us to indirect a pair of pointers from the "ownership" such that we could specify the "attachment" and lexical "purview" separately.
> > edit : but, of course, default to using a single pointer, otherwise we fall back into the very big hammer case.
> 
> Basically agreed. But C looks not necessary for me. Do you mean we need it for implementing `extern "C++"`? I have other ideas.

No, it is not necessary in the case of C++ language exports, we can always disambiguate them.  I was wondering (and asked Jens) about enumerating the "other cases" he mentioned in the core reflector reply where the lexical module purview is not the same as the attachment (TBH, the only case I can think of at the moment is module partitions, and we already handle that case specially). 

> > As noted above, the GM is made up of GMFs so that we can signify "attachment" to the GM by placing a decl in a GMF.
> > Since there is nothing special about one GMF c.f. any other, we do not need to make multiple GMFs per TU to cater for this, we can simply append a new decl to an existing GMF.
> 
> I feel it is not bad to have multiple GMFs in one TU. It is straight forward and consistent with the spec.

OK. .. I would be inclined not to make extra sub-modules unless there is some good reason to do so (but this is not a demand ... just a suggestion).

> BTW, I feel a little bit odd for the wording "we can simply append a new decl to an existing GMF". Since we can't iterate declarations in a module. But this might not be important to this thread.
> 
> > From my reading, a language ,linkage export is not part of "the" GMF (even though as just mentioned we can place it in a GMF to indicate attachment), so that, even if not covered by other rules in https://eel.is/c++draft/module.global.frag#3 I do not think there is any reason we would expect to consider it as a candidate for elision.
> 
> Fully agreed.
> 
> My design in brain is that we can introduce another ModuleKind "GeneralGlobalModuleFragment" (Or any other name). (Maybe we need to rename module kind `GlobalModuleFragment` to `TheGlobalModuleFragment`.) And each language linkage block corresponds to a `GeneralGlobalModuleFragment`. (Or all the language linkage block refers to the same `GeneralGlobalModuleFragment`, this doesn't matter).
> 
> Then we can introduce `Module::isGlobalModule()`. Its definition should be `Kind == GlobalModuleFragment || Kind == GeneralGlobalModuleFragment;`. Then things should work after we replace a lot of `Module::isGlobalModuleFragment()` with `Module::isGlobalModule()`.

OK - do we have enough space in the enum for an extra type?
(perhaps we do since we dropped the old header-module one)

> And for your discarding patch, it will be easy for you to check "the" global module fragment.

right.

**Comment by ChuanqiXu9** [comment]
> OK - do we have enough space in the enum for an extra type?

Currently we have 7 module kinds in ModuleKind. So it will be exactly good to add another one.

**Comment by ChuanqiXu9** [comment]
Sent https://reviews.llvm.org/D144367
