### ISSUE TITLE
[mlir] Can't use `applyOpPatternsAndFold` on a top-level op

### ISSUE THREAD

**Issue by mikeurbach** [llvm/llvm-project#60462]
I'm working on pulling in the latest changes to MLIR in a downstream project, and I believe I've hit a snag with the recent change here: https://github.com/llvm/llvm-project/commit/977cddb95eac67a6dc6680a7d0fadee81114de11.

Specifically, we have this call to `applyOpPatternsAndFold`, where `getOperation()` returns an `mlir::ModuleOp`: https://github.com/llvm/circt/blob/f80e0f6e67bd915ff5f1ddb90905a20f609a9ef1/lib/Conversion/SCFToCalyx/SCFToCalyx.cpp#L1230-L1234

`applyOpPatternsAndFold` will look for a `scope` within which to apply the rewrite: https://github.com/llvm/llvm-project/blob/ffa2a647c6a9dd2fab13a5e1bd4832b5b200d908/mlir/lib/Transforms/Utils/GreedyPatternRewriteDriver.cpp#L595-L598

`findCommonAncestor` goes through the fast path, since we only have one op to rewrite: https://github.com/llvm/llvm-project/blob/ffa2a647c6a9dd2fab13a5e1bd4832b5b200d908/mlir/lib/Transforms/Utils/GreedyPatternRewriteDriver.cpp#L561-L563

However, for our case, the `mlir::ModuleOp` is the outermost level of the IR, so this returns null. Note that in the non-fast path, `findCommonAncestor` asserts that it found a `Region`, but in this path, null can be returned.

This is all existing logic, which seemed to work fine. But the above patch to the `GreedyPatternRewriteDriver` also added this assertion, which now fires for the code I linked from CIRCT: https://github.com/llvm/llvm-project/blob/ffa2a647c6a9dd2fab13a5e1bd4832b5b200d908/mlir/lib/Transforms/Utils/GreedyPatternRewriteDriver.cpp#L127

I'm curious what the path forward should be. Should we remove the assertion? Is there a better way to handle this? It seems like using the existing drivers to run patterns on the outermost op(s) in the IR won't work.

For this specific pass in CIRCT, we can probably adjust how we are rewriting the IR, but in general this seems to pose a restriction that perhaps we don't need.

cc @matthias-springer

**Comment by joker-eph** [comment]
How is your situation different from the Canonicalizer? 

See here: https://github.com/llvm/llvm-project/blob/2c46051aa9d30dc1740f2183ceb45a235b994cc3/mlir/lib/Transforms/Canonicalizer.cpp#L60-L61 ; `getOperation()` can also be a top-level `ModuleOp` here.

**Comment by mikeurbach** [comment]
I just tried the `applyPatternsAndFoldGreedily` API, which indeed avoids the assertion about scope being set. But it is actually applying patterns within each `Region` of the supplied `Operation`: https://github.com/llvm/llvm-project/blob/4461ffdf295853f985d2dad832309346c82c18e1/mlir/include/mlir/Transforms/GreedyPatternRewriteDriver.h#L104-L113

In my case, I actually want to rewrite the `ModuleOp` itself, but using that API my pattern never matches the `ModuleOp` itself. So I guess I should rephrase the issue as `applyOpPatternsAndFold` can't be used on a top-level operation.

Is this an intended limitation of this API? I see this documentation: https://github.com/llvm/llvm-project/blob/4461ffdf295853f985d2dad832309346c82c18e1/mlir/include/mlir/Transforms/GreedyPatternRewriteDriver.h#L123-L127

Maybe we can gate the assertion around some `GreedyRewriteConfig` flag to only assert the scope exists if it's needed?

**Comment by mikeurbach** [comment]
> Maybe we can gate the assertion around some GreedyRewriteConfig flag to only assert the scope exists if it's needed?

I took a quick look, and we don't even need to necessarily check flags. If I move the assertion about `config.scope` being set to right here, the one place where it is actually read, my use-case works as before: https://github.com/llvm/llvm-project/blob/4461ffdf295853f985d2dad832309346c82c18e1/mlir/lib/Transforms/Utils/GreedyPatternRewriteDriver.cpp#L271

**Comment by mikeurbach** [comment]
FWIW, I've just changed the pass in CIRCT to mutate the IR without a pattern, since this is a very trivial pattern that just updates the ModuleOp in place. So, this is not a high-priority issue for me, but I am curious if this is something the infrastructure should support.

**Comment by matthias-springer** [comment]
Two issues here:

First, the naming of the functions is still a bit confusing.
* `LogicalResult applyPatternsAndFoldGreedily(Operation *op, ...)`: Applies patterns to all ops contained inside `op`.
* `LogicalResult applyPatternsAndFoldGreedily(Region &region, ...)`: Applies patterns to all ops contained inside `region`.
* `LogicalResult applyOpPatternsAndFold(ArrayRef<Operation *> ops, ...)`: Applies patterns to all specified ops.

`applyPatternsAndFoldGreedily` should be something like `applyPatternsToAllContainingOpsAndFoldGreedily`. But that name is very long. `applyOpPatternsAndFold` should also have the `Greedily` part in its name since they use the same driver and essentially do the same thing. Just the initial list of ops is seeded differently. Or we could drop the `Greedily` from both names to make them shorter.

Second, I did not think of top-level ops when adding `scope`. It can be specified in the GreedyRewriteConfig. If not specified, it is inferred from the list of ops by taking the first common enclosing op as a scope. There is no such op for top-level ops, which is why even after `config.scope = findCommonAncestor(ops);`, the scope is `nullptr`.

So I think the right thing to do is to remove the assertion and to make the scope optional in the GreedyRewriterDriver. (This does not allow users to skip the scope entirely, we will still try to infer a scope if none was provided in config.)

**Comment by matthias-springer** [comment]
https://reviews.llvm.org/D143151
