### ISSUE TITLE
[lld] Revised reallocation behavior for a new target

### ISSUE THREAD

**Issue by orgads** [llvm/llvm-project#60485]
I'm trying to modify the behavior of the symbols relocation in lld for a new target I develop.

I want the linker to set the symbol value to its index in the (output) section instead of its address.

For example, if I have:
```
  [(.text) add=0, main=163, exit=311]
  [(.data) value=532, result=702]
```

I want the output of the reallocation to be:
```
  [(.text) add=0, main=1, exit=2]
  [(.data) value=0, result=1]
```

(What I need is not to change the actual address, but the references to those symbols)

How can I implement that?

CC @mstorsjo

**Comment by mstorsjo** [comment]
> How can I implement that?

Hmm, well, lld is essentially 4 different linkers with somewhat similar style/structure, so exactly how to achieve this, I guess it depends on which one of the existing lld linkers you're basing your work on - I'm primarily familiar with the COFF one. There, most of this logic happens within `SectionChunk::applyRelocation` in lld/COFF/Chunks.cpp. Then depending on the actual relocation type, a different value is written to the target. So if you want a relocation which means "symbol index" instead of "symbol address", you'd add a new relocation type and use that. I think...

CC @MaskRay who is more familiar with the ELF part of the linker, if that's what you're working with.

**Comment by MaskRay** [comment]
Better use https://discourse.llvm.org/ for questions so that this site can focus on its main work: issue tracking.

> I want the linker to set the symbol value to its index in the (output) section instead of its address.

A lot of details are missing from the description, e.g. whether you are developing a new object file format.
For ELF, such a drastic change for a new architecture is certainly infeasible.
