### ISSUE TITLE
std::ifstream eof difference between libc++ and libstdc++11

### ISSUE THREAD

**Issue by morozyto** [llvm/llvm-project#60507]
Hi!

I have got this code:
```cpp
#include <fstream>
#include <vector>

int main() {
    const std::string path = "/tmp/some_random_path"; // this file do not exist before running of program
    std::ofstream file_output(path);
    std::ifstream file_input(path, std::ios::in | std::ios::binary);
    file_input.peek();
    if (!file_input.eof()) {
        return 1;
    }
    std::vector<char> data = {'a', 'b', 'c'};
    file_output.write(data.data(), static_cast<long>(data.size()));
    file_output.flush();
    file_input.clear();
    file_input.peek();
    if (file_input.eof()) {
        return 2; // libc++
    }
    return 0; // libstdc++11
}
```

I tried to compile it with againt libstdc++11 (`clang++ main.cpp`) and against libc++ (`clang++ -stdlib=libc++ main.cpp`). I expect success return code for both libc++ and libstdc++11, but libc++ eof flag is not updated. Is it valid?

My specs:
```console
Ubuntu Description: Ubuntu 20.04.4 LTS Release: 20.04 Codename: focal
Ubuntu clang version 15.0.7
Target: x86_64-pc-linux-gnu 
Thread model: posix
InstalledDir: /usr/bin 
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10 
Selected multilib: .;@m64
```

**Comment by mordante** [comment]
This doesn't look like a bug. You open the same file twice and use a different position for reading and writing. This seems to violate
https://eel.is/c++draft/input.output#filebuf.general-3.3
"A joint file position is maintained for both the input sequence and the output sequence[.](https://eel.is/c++draft/input.output#filebuf.general-3.3.sentence-1)"

Since filebufs are allowed to cache it's easy to write an example that fails with libstdc++ and libc++
https://godbolt.org/z/1WG4hKGoa
