### ISSUE TITLE
Missing vector type conversion in `ConvertIndexToLLVM`?

### ISSUE THREAD

**Issue by dcaballe** [llvm/llvm-project#60614]
The following IR reached the MLIR to LLVM translation pass in our pipeline with an `index` type that is not lowered before the lowering to the LLVM dialect (see `%1 = llvm.mlir.constant(dense<[0, 1, 2]> : vector<3xindex>) : vector<3xi32>`):

```mlir
  llvm.func @_iota_dim1_dispatch_0_generic_2x3(%arg0: !llvm.ptr<struct<"iree_hal_executable_environment_v0_t", (ptr<i32>, ptr<func<i32 (ptr<func<i32 (ptr<i8>, ptr<i8>, ptr<i8>)>>, ptr<i8>, ptr<i8>, ptr<i8>)>>, ptr<ptr<func<i32 (ptr<i8>, ptr<i8>, ptr<i8>)>>>, ptr<ptr<i8>>, struct<"iree_hal_processor_v0_t", (array<8 x i64>)>)>> {llvm.align = 16 : i64, llvm.noalias}, %arg1: !llvm.ptr<struct<"iree_hal_executable_dispatch_state_v0_t", (i32, i32, i16, i16, i32, i32, i16, i8, i8, ptr<i32>, ptr<ptr<i8>>, ptr<i32>)>> {llvm.align = 16 : i64, llvm.noalias}, %arg2: !llvm.ptr<struct<"iree_hal_executable_workgroup_state_v0_t", (i32, i32, i16, i16, i32, ptr<ptr<i8>>, i32)>> {llvm.align = 16 : i64, llvm.noalias}) -> vector<3xf32> {
    %0 = llvm.mlir.constant(0 : i32) : i32
    %1 = llvm.mlir.constant(dense<[0, 1, 2]> : vector<3xindex>) : vector<3xi32>
    %2 = llvm.load %arg2 : !llvm.ptr<struct<"iree_hal_executable_workgroup_state_v0_t", (i32, i32, i16, i16, i32, ptr<ptr<i8>>, i32)>>
    %3 = llvm.extractvalue %2[0] : !llvm.struct<"iree_hal_executable_workgroup_state_v0_t", (i32, i32, i16, i16, i32, ptr<ptr<i8>>, i32)> 
    %4 = llvm.mlir.undef : vector<3xi32>
    %5 = llvm.insertelement %3, %4[%0 : i32] : vector<3xi32>
    %6 = llvm.shufflevector %5, %4 [0, 0, 0] : vector<3xi32> 
    %7 = llvm.add %6, %1  : vector<3xi32>
    %8 = llvm.sitofp %7 : vector<3xi32> to vector<3xf32>
    llvm.return %8 : vector<3xf32>
  }
```

It looks like there is a missing type conversion for vectors in `ConvertIndexToLLVM`, since the `index` type is not lowered when I run `mlir-opt --convert-index-to-llvm repro.mlir`. Is there any other pass that should take care of this?

Also, it we run `mlir-translate` on this example, we end up generating code that is incorrect. The [0, 1, 2] constant term in the addition above is turned into [0, 0, 1]:

```ll
define <3 x float> @_iota_dim1_dispatch_0_generic_2x3(ptr noalias align 16 %0, ptr noalias align 16 %1, ptr noalias align 16 %2) {
  %4 = load %iree_hal_executable_workgroup_state_v0_t, ptr %2, align 8
  %5 = extractvalue %iree_hal_executable_workgroup_state_v0_t %4, 0
  %6 = insertelement <3 x i32> undef, i32 %5, i32 0
  %7 = shufflevector <3 x i32> %6, <3 x i32> undef, <3 x i32> zeroinitializer
  %8 = add <3 x i32> %7, <i32 0, i32 0, i32 1>
  %9 = sitofp <3 x i32> %8 to <3 x float>
  ret <3 x float> %9
}
```

I wonder if we should prevent any index type to be translated directly to LLVM to avoid this kind of silent errors.

@Mogball, @River707, @ftynse, @joker-eph

**Comment by Mogball** [comment]
The index dialect and its passes don't deal with vectors. Can you provide the input IR that becomes this invalid LLVM IR? We should also have the verifier of `LLVM::ConstantOp` reject the IR you've shown.

**Comment by dcaballe** [comment]
Thanks for the quick response! The input IR is `mhlo.iota` op:

```
  func.func @iota_dim1() {                                                                                                                                                                       
    %0 = "mhlo.iota"() {iota_dimension = 1 : i64} : () -> tensor<2x3xf32>                                                                                                                        
    check.expect_almost_eq_const(%0, dense<[[0.000000e+00, 1.000000e+00, 2.000000e+00], [0.000000e+00, 1.000000e+00, 2.000000e+00]]> : tensor<2x3xf32>) : tensor<2x3xf32>                        
    return                                                                                                                                                                                       
  }
```

that we lower to a linalg.generic op like this:

```
        %7 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} outs(%extracted_slice : tensor<1x3xf32>) attrs =  {__internal_linalg_transform__ = "1", lowering_config = #iree_codegen.lowering_config<tile_sizes = [[2, 3], [1, 16], [0, 0]]>} {                                                                                    
        ^bb0(%out: f32):                                                                                                                                                                         
          %8 = linalg.index 1 : index                                                                                                                                                            
          %9 = affine.apply affine_map<(d0, d1) -> (d0 + d1)>(%arg1, %8)                                                                                                                         
          %10 = arith.index_cast %9 : index to i32                                                                                                                                               
          %11 = arith.sitofp %10 : i32 to f32                                                                                                                                                    
          linalg.yield %11 : f32                                                                                                                                                                 
        } -> tensor<1x3xf32>                                                                                                                                                                     
```

and we are now able to vectorize:

```
      %6 = scf.for %arg2 = %c0 to %c2 step %c1 iter_args(%arg3 = %5) -> (tensor<2x3xf32>) {                                                                                                      
        %7 = vector.broadcast %arg1 : index to vector<3xindex>                                                                                                                                   
        %8 = arith.addi %7, %cst : vector<3xindex>                                                                                                                                               
        %9 = arith.index_cast %8 : vector<3xindex> to vector<3xi32>                                                                                                                              
        %10 = arith.sitofp %9 : vector<3xi32> to vector<3xf32>                                                                                                                                   
        %11 = vector.broadcast %10 : vector<3xf32> to vector<1x3xf32>                                                                                                                            
        %12 = vector.transfer_write %11, %arg3[%arg2, %c0] {in_bounds = [true, true]} : vector<1x3xf32>, tensor<2x3xf32>                                                                         
        scf.yield %12 : tensor<2x3xf32>                                                                                                                                                          
      }
```

Per `linalg.index 1 : index`, the dimension one of the generic op is vectorized and a `vector<3xindex>` is generated. I'm attaching the full dump here: https://gist.github.com/5bb03bb41a21007c2202ff35f770ece5. We also have some other ops failing because of this.

I haven't been following the Index dialect but we need a way to represent and handle vector of indices. They are common not only for this case but also for gather/scatter operations and also for cases where the indices are part of general computation (e.g., pre-computation of indices that are stored and used later on).

Hopefully this helps!

**Comment by ftynse** [comment]
Hmm, the index type is the type of an attribute, not in the value type. That is likely why it doesn't get converted. We (used to?) have plenty of cases along the lines of `llvm.mlir.constant(0 : index) : i64` that were handled alright by the translation without preliminary type conversion. `vector<...x index>` may be special because we didn't allow for it when the translation was first written.

**Comment by Mogball** [comment]
We can either reject `vector<Nxindex>` in `LLVM::ConstantOp` or make the translation tolerant to it like it is for scalars. To me, this seems like a bug in one of the LLVM lowerings in your pipeline. I checked out the dump but it seems to be truncated.

**Comment by dcaballe** [comment]
If you click on the "Raw" view you should be able to see the full dump. Something that I forgot to mention is that these tests all work if the index size is 64 bits so this must be a small corner case somewhere in the translation. The translation does happen for 32-bits but we generate the wrong constant.

**Comment by banach-space** [comment]
Hey, I'm trying to help @dcaballe with this one as it's effectively blocking https://reviews.llvm.org/D143429 (and which I need for https://reviews.llvm.org/D141998).

> Also, it we run mlir-translate on this example, we end up generating code that is incorrect. The [0, 1, 2] constant term in the addition above is turned into [0, 0, 1]:

I've narrowed this down to the raw-data extraction in [convertDenseElementsAttr](https://github.com/llvm/llvm-project/blob/d5ea1b22cba345e4fc0d42085a8c366407c7265b/mlir/lib/Target/LLVMIR/ModuleTranslation.cpp#L206): https://github.com/llvm/llvm-project/blob/d5ea1b22cba345e4fc0d42085a8c366407c7265b/mlir/lib/Target/LLVMIR/ModuleTranslation.cpp#L274-L281

IIUC, it assumes that the size of each element in the attribute is `i32` rather than `index` and that's because `innermostLLVMType` is used for calculating the raw data: https://github.com/llvm/llvm-project/blob/d5ea1b22cba345e4fc0d42085a8c366407c7265b/mlir/lib/Target/LLVMIR/ModuleTranslation.cpp#L212

For scalar attributes we either truncate or extend: https://github.com/llvm/llvm-project/blob/d5ea1b22cba345e4fc0d42085a8c366407c7265b/mlir/lib/Target/LLVMIR/ModuleTranslation.cpp#L316-L319

Anyway, apologies if that's too much low-level detail - I appreciate that this will be obvious to some people.

@Mogball ,
> We can either reject vector<Nxindex> in LLVM::ConstantOp or make the translation tolerant to it like it is for scalars.
Given that this would be fine:
```mlir
 %1 = llvm.mlir.constant(1 : index) : vector<3xi32>
```
shouldn't `vector<Nxindex>` be accepted and correctly translated as well? @ftynse , I see that you wrote most of that code (e.g. [convertDenseElementsAttr](https://github.com/llvm/llvm-project/blob/d5ea1b22cba345e4fc0d42085a8c366407c7265b/mlir/lib/Target/LLVMIR/ModuleTranslation.cpp#L205-L285)) - would extending the translation to correctly handle vectors of `index` be feasible?

Btw, `vector<3xindex>` is introduced in `LinalgStrategyVectorizePass` (it's there in the dump if you press "raw"). To avoid this, should `index` types be translated as some pre-processing stage before the vectorizer? Still, it's counterintuitive to me that scalars would be fine wheres vectors would be unsupported in the translation.

Thank you,
-Andrzej

**Comment by dcaballe** [comment]
Thanks for looking into this @banach-space!

```
 unsigned aggregateSize = denseElementsAttr.getType().getShape().back() * 
                          (innermostLLVMType->getScalarSizeInBits() / 8); 
 constants.reserve(numAggregates); 
 for (unsigned i = 0; i < numAggregates; ++i) { 
   StringRef data(denseElementsAttr.getRawData().data() + i * aggregateSize, 
                  aggregateSize); 
   constants.push_back(buildCstData(data)); 
 } 
```
Yes, it looks like a `vector<3xindex>` is processed as a single aggregate of 24 bytes. I don't know the storage of an index type but that's probably where the problem is. The aggregate size should be computed based on the storage size of an index type and then be sign-extended or truncated to the LLVM size. However, I'm not sure what the best way to do that from a `DenseElementsAttr` is.

**Comment by ftynse** [comment]
> I see that you wrote most of that code (e.g. [convertDenseElementsAttr](https://github.com/llvm/llvm-project/blob/d5ea1b22cba345e4fc0d42085a8c366407c7265b/mlir/lib/Target/LLVMIR/ModuleTranslation.cpp#L205-L285)) - would extending the translation to correctly handle vectors of index be feasible?

Yes, I think it's the correct short-term solution. We don't have it because `vector<...xindex>` was not allowed by the IR (it was a first-class IR thing back then) when the translation was written.

The longer-term solution, I believe, is to have an "index materialization" pass that replaces `index` subtype in aggregate types with the appropriate integer type defined by the data layout. This should combine with lowering the Index dialect operations. Note that there is currently a lowering to the LLVM dialect, but I somehow feel it may target Arith instead. 

> Yes, it looks like a vector<3xindex> is processed as a single aggregate of 24 bytes. I don't know the storage of an index type but that's probably where the problem is.

We have the data layout subsystem that lets you query size and alignment properties of `index`. The storage of `index` is not hard, but the storage of `vector<3xindex>` is. LLVM will round that up to 4 elements.

**Comment by ftynse** [comment]
https://reviews.llvm.org/D143993 should fix the immediate problem.
