### ISSUE TITLE
error: Opaque pointers are only supported in -opaque-pointers mode

### ISSUE THREAD

**Issue by dbl001** [llvm/llvm-project#60664]
I am trying to build the project 'pocl' on MacOS Ventura 13.2.

https://github.com/pocl/pocl/issues/1173

I get this error running 'make'.
```console
% make
[  0%] Built target sleef_config_skylake
[  0%] Linking & optimizing SLEEF for skylake: /Users/davidlaxer/pocl/build/lib/kernel/host/skylake/sleef.bc
/Users/davidlaxer/llvm-project/build/bin/llvm-link: /Users/davidlaxer/pocl/build/lib/kernel/host/skylake/spir_wrapper_256bit.ll.bc: error: Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM15.0.0git' Reader: 'LLVM 15.0.0git')
/Users/davidlaxer/llvm-project/build/bin/llvm-link: error:  loading file '/Users/davidlaxer/pocl/build/lib/kernel/host/skylake/spir_wrapper_256bit.ll.bc'
make[2]: *** [lib/kernel/host/skylake/sleef.bc] Error 1
make[1]: *** [lib/kernel/host/CMakeFiles/kernel_host_skylake.dir/all] Error 2
```

I tried building 'llvm' with
```shell
cmake -DLLVM_ENABLE_RTTI=ON ../llvm
```
Any suggestions?

**Comment by asl** [comment]
This seems to be a genuine pocl issue. Pocl is not a part of LLVM project, so please report the problem elsewhere.

**Comment by badger200** [comment]
This is an ongoing issue still: https://github.com/llvm/llvm-project/issues/55377

I experience it too. The problem is they made a change in clang-15 on opaque pointers in LTO and there seems to be no way to revert to the prior behavior. 

Workarounds include:
- disabling LTO
- Compiling with clang-14

**Comment by dbl001** [comment]
When I build llvm from source, it did not build clang or clang++.
Is it supposed to?  Did I miss some configuration parameter?

cmake in 'pocl' is using llvm-config, llvm-link, llvm-as, opt, et. from the llvm-project/build/bin (source I built), but it's picking up clang and clang++ from my /usr/bin directory.

**Comment by dbl001** [comment]
I build llvm, clang, clang++ etc. with
```
$ cmake -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -DCLANG_DEFAULT_CXX_STDLIB=libc++ -DLLVM_BUILD_LLVM_DYLIB=ON -DBUILD_SHARED_LIBS=ON  ../llvm
```

**Comment by badger200** [comment]
@dbl001 I edited my above comment to include the fix I discovered: `-Wl,-mllvm,--opaque-pointers`

Also I initially had a lot of trouble compiling Clang too, they offer a separate clang source tarball and I assumed that's all I needed, however ultimately I realized it's useless without the llvm source. I don't know why they keep pretending these are separate projects, I'm not aware of any other compiler using the LLVM system aside from Clang.

Anyway from then on, I always just:
- download the big llvm-project-xxx.SRW.tar.xz and unpack it
- `mkdir build` inside that new dir 
- `ccmake ..` inside the new build dir (because ccmake's ncurses GUI is so much nicer! Baffling I'm apparently the only person in the world who uses it..)
- under LLVM_PROJECTS add: clang (I also like to add lld,lldb,clang-tools-extra)
- Configure ccmake and it will generate a huge list of new clang-specific options. Adjust to taste.
- generate, then make!
