### ISSUE TITLE
Simplify "X ? 1U << std::countr_zero(X) : 0" to "X & -X"

### ISSUE THREAD

**Issue by kazutakahirata** [llvm/llvm-project#60799]
Compile:

```cpp
// clang -std=c++20 -march=skylake -O2
#include <bit>

unsigned blsi_human_readable(unsigned X) {
  return X ? 1U << std::countr_zero(X) : 0;
}
```

I get:

```ll
  %2 = icmp eq i32 %0, 0
  %3 = tail call i32 @llvm.cttz.i32(i32 %0, i1 false) #3, !range !5
  %4 = shl nuw i32 1, %3
  %5 = select i1 %2, i32 0, i32 %4
```
```asm
  f3 0f bc c7                tzcnt  %edi,%eax
  b9 01 00 00 00             mov    $0x1,%ecx
  c4 e2 79 f7 c1             shlx   %eax,%ecx,%eax
  0f 42 c7                   cmovb  %edi,%eax
```

We could transform this into:

```cpp
unsigned blsi_optimal(unsigned X) {
  return X & -X;
  // %2 = sub i32 0, %0
  // %3 = and i32 %2, %0
  //
  // c4 e2 78 f3 df             blsi   %edi,%eax
}
```

Proof: https://alive2.llvm.org/ce/z/C2eFaF

**Comment by rotateright** [comment]
We don't need to match the guard for a zero input to convert the cttz+shl alone:
https://alive2.llvm.org/ce/z/qv3E9e

**Comment by rotateright** [comment]
Removing the guard of the zero input is safe here and in #60801 because there's no chance for poison to leak through where it did not in the original code. However, it is not safe in general:
https://alive2.llvm.org/ce/z/Cr8PL2

So we do not get the simplification with the general transform in "simplifyWithOpReplaced".
Three potential options to fix this:
1. There's a possible missed generalization with "simplifyWithOpReplaced" - we don't check "isGuaranteedNotToBeUndefOrPoison" for the false value of the select when trying the replacement. In the minimal source example here, we have 'noundef' on the input argument, so that would probably work, but it's not a universal fix.
2. We can add the "and" sequences of these 2 bugs to the approved list of patterns in "simplifyWithOpReplaced" ( https://reviews.llvm.org/D99027 ).
3. We can freeze the other operand of the "and" as part of a specialized pattern match: https://alive2.llvm.org/ce/z/s_PbhD (we have added something like that already for "mul" patterns).

@nikic - any preference?

**Comment by rotateright** [comment]
The mul transform is here:
https://github.com/llvm/llvm-project/blob/708eb1b96d9a36f9c0182b7d53c492059778fa35/llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp#L746

**Comment by nikic** [comment]
I think I'd go for option 2 for now, and then maybe add 3 later if we have other motivating cases.

**Comment by rotateright** [comment]
The IR should be ideal now, and we get the ideal x86 asm too for the "-march" options that I tried. 

A more complicated example might still not be ideal (I noticed that x86 codegen didn't always produce the expected BMI asm with the cmp+select still in place). Please file another issue if you find more problems.
