### ISSUE TITLE
[flang][OpenMP] Compilation error of DO directive in OpenMP program with variables of integer*1

### ISSUE THREAD

**Issue by ohno-fj** [llvm/llvm-project#60870]
```
Version of flang-new : 17.0.0(3e0866bf616bf7b293cec93d06d030dd11d7911f)
```

`DO` directive in OpenMP program with variables of `integer*1` is compile-time error.
`integer*2` has the same result. However, `integer*4` and `integer*8` have no problem with compilationn.

The following are the test program, flang-new, GFortran and ifort compilation result.

`omp_PARALLEL_DO_i1_008_2.f90`:
```f90
program main
  integer*1 i,ia
  integer*1 :: ioff=70
  integer*1 :: loop=50
  ia = 0
!$omp parallel
!$omp do schedule(static)
  do i=1+ioff, loop+ioff
     if (i.eq.loop+ioff) ia = i
  end do
!$omp end do
!$omp end parallel
  if (ia.eq.loop+ioff) then
     write(6,*)'OK'
  else
     write(6,*)'NG'
  endif
  stop
end program main
```

```console
$ flang-new -flang-experimental-exec -fopenmp omp_PARALLEL_DO_i1_008_2.f90
error: loc("/home/users/ea01/ea0178/CT/fort/tp/reproducer_OpenMP/fomp_add00/omp_PARALLEL_DO_i1_008_2.f90":8:3): 'arith.cmpi' op requires all operands op have the same type
error: verification of lowering to FIR failed
$
```

```console
$ gfortran -fopenmp omp_PARALLEL_DO_i1_008_2.f90
$
```

```console
$ ifort -qopenmp omp_PARALLEL_DO_i1_008_2.f90
$
```

**Comment by kiranchandramohan** [comment]
In https://github.com/flang-compiler/f18-llvm-project/pull/1256 we fixed the type of the worksharing loop to match what the OpenMP runtime would expect. A temporary is created (since worksharing loop variable indexes are private by default) where the value of the index variable is stored. This should ideally match the original variable's type. While the `mlir::Value` corresponding to the loop can continue to be what the runtime expects, the temporary should be created with the original variable's type and appropriate converts should be inserted while storing the index variable.

https://github.com/llvm/llvm-project/blob/d0e95fec65b7ac68021e956a3da74aa8d42e699f/flang/lib/Lower/OpenMP.cpp#L511

Note: It will be good to re-check what the runtime expects.

**Comment by luporl** [comment]
https://reviews.llvm.org/D156803
