### ISSUE TITLE
[preprocessor] "error: invalid token in macro parameter list" with `-CC`

### ISSUE THREAD

**Issue by carsonRadtke** [llvm/llvm-project#60887]
```c
#1 "bad.c"
#define MACRO_W_COMMENT(/**/x) (x)

int main() { return MACRO_W_COMMENT(0); }
```

The above source generates the preprocessor output with `-E` just fine, but when I ask the preprocessor to preserve comments in macros with `-CC`, it fails with:
```console
$ clang-15 -E -CC bad.c
bad.c:1:25: error: invalid token in macro parameter list
#define MACRO_W_COMMENT(/**/x) (x)
                        ^
1 error generated.
```

I would expect the comment not to affect the generation of the preprocessed output and generate something like:
```c
# 1 "/app/example.cpp"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 417 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "/app/example.cpp" 2
# 1 "bad.c"

int main() { return (0); }
```

**Comment by EugeneZelenko** [comment]
Could you please try 16 or `main` branch? https://godbolt.org should be helpful.

**Comment by shafik** [comment]
Confirmed: https://godbolt.org/z/vcvoe8n93

I think this is a indeed a bug. We are generating this diagnostic in `Preprocessor::ReadMacroParameterList(...)` and it looks like we just are not handling this case in the `switch`, I think we just need to add a case for `tok::comment` but I could be missing something here.

**Comment by shafik** [comment]
Actually, after digging more it looks like the better option is to replace the `while` loop call to `LexUnexpandedToken(...)` with `LexUnexpandedNonComment(...)`.

**Comment by shafik** [comment]
PR: https://reviews.llvm.org/D144511

**Comment by TheInferentialImp** [comment]
The reason why the preprocessor fails to preserve the comments in the macro with the -CC option is because the comment is placed before the macro argument identifier. This syntax is used to explicitly indicate that the macro argument has no name.

However, according to the C and C++ standards, the comment in a macro definition is not part of the replacement token. Therefore, in this case, the comment is not considered part of the argument list, which makes the preprocessor fail to parse the macro definition when the -CC option is used.

To make the preprocessor preserve comments in the macro with the -CC option, the comment should be placed after the argument identifier, like this:

`#define MACRO_W_COMMENT(x/**/) (x)`
