### ISSUE TITLE
[C++20] [Modules] Constrained friend causes "definition with same mangled name as another definition"

### ISSUE THREAD

**Issue by davidstone** [llvm/llvm-project#60890]
Given the following valid set of files:

```cpp
export module a;
 
export template<typename T>
struct a {
	friend void aa(a) requires(true) {
	}
};
```

```cpp
export module b;

import a;

struct b {
	a<int> m;
};
```

```cpp
export module c;

import a;

struct c {
	void f() const {
		aa(a<int>());
	}
};
```

```cpp
import a;
import b;
import c;

void d() {
	aa(a<int>());
}
```

And compiling with

```shell
clang++ -std=c++20 -x c++-module --precompile -c a.cpp -o a.pcm
clang++ -std=c++20 -fmodule-file=a=a.pcm -x c++-module --precompile -c b.cpp -o b.pcm
clang++ -std=c++20 -fmodule-file=a=a.pcm -x c++-module --precompile -c c.cpp -o c.pcm
clang++ -std=c++20 -fmodule-file=a=a.pcm -fmodule-file=b=b.pcm -fmodule-file=c=c.pcm -c d.cpp -o /dev/null
```

Fails with

```console
In file included from d.cpp:1:
a.cpp:5:14: error: definition with same mangled name '_ZW1a2aaS_1aIiE' as another definition
        friend void aa(a) requires(true) {
                    ^
a.cpp:5:14: note: previous definition is here
1 error generated.
```

Note that changing the order of importing `b` and `c` in `d.cpp` causes the issue to go away.

Tested with 70d78e035801a35c95c55384621724b0ef8ecb35, but has existed for much longer.

**Comment by ChuanqiXu9** [comment]
Some notes for developers:

The require clause of **used** function will be replaced with the evaluated version (https://github.com/llvm/llvm-project/blob/efae3174f09560353fb0f3d528bcbffe060d5438/clang/lib/Sema/SemaConcept.cpp#L664-L665). In module 'b', the friend function is instantiated but not used so the require clause of the friend function is `(true)`. However, in module 'c', the friend function is used so the require clause is `true`. So deserializer classify these two function to two different functions instead of one. Then here is the bug report.

Why does 'friend' key word here matter? Since the unused member functions of the template class wouldn't be instantiated. But 'friend' function is not member functions.
