### ISSUE TITLE
AIX cross compile on linux using integrated-as: XCOFFAsmParser directive not yet supported

### ISSUE THREAD

**Issue by matt-sm** [llvm/llvm-project#61011]
I'm trying to do a cross compile with: 
Ubuntu clang version 15.0.7
Target: powerpc-ibm-aix

By creating a sysroot I was able to successfully optimize and produce a .s file, but in assembly get this error:

```console
$ "/usr/lib/llvm-15/bin/clang" -cc1as -triple powerpc-ibm-aix -filetype obj -main-file-name hello.cpp -target-cpu pwr7 -fdebug-compilation-dir=/home/matt/code/hello_cpp -dwarf-version=3 -mrelocation-model pic -mrelax-all --mrelax-relocations -o hello.o hello.s
clang -cc1as: fatal error: error in backend: XCOFFAsmParser directive not yet supported!
```

Which is here: https://github.com/llvm/llvm-project/blob/main/llvm/lib/MC/MCParser/XCOFFAsmParser.cpp

Just wondering if I'm missing something and/or if there is a plan to support this use case?

**Comment by nemanjai** [comment]
The integrated assembler is not yet supported on AIX. The code must be compiled to assembly and the system assembler must be used to assemble the code to an object file. If you are looking to produce object files for AIX, you have to provide an assembler that understands XCOFF.
@cebowler Can you comment on the timeline for when integrated assembler support is expected to be provided?

**Comment by chenzheng1030** [comment]
Support AIX assembly syntax in LLVM AsmParser is in our radar. And that needs quite a big effort which is currently not working on.

To cross compile a standalone XCOFF object, could you please make the LLVM generate object directly instead of generating an assembly file? AIX recently switched to integrated assembler, so with latest CLANG driver, you should be able to generate a XCOFF object on Linux just with `clang -target powerpc-ibm-aix`.

But do you have any workable linker on Linux for XCOFF objects? I don't think LLVM lld supports XCOFF, so after generating the XCOFF objects on Linux, without AIX native linker, you can not get a successfully linking.

**Comment by brad0** [comment]
@matt-sm Is this issue still relevant? Do you want to see how things fare with 18 depending on your usage?

**Comment by matt-sm** [comment]
Yes this can be closed.

**Comment by brad0** [comment]
Thanks.
