### ISSUE TITLE
string_view(ptr, len) should assert len <= PTRDIFF_MAX

### ISSUE THREAD

**Issue by davidben** [llvm/llvm-project#61100]
Comparing libc++'s `std::string_view` to Abseil's `absl::string_view` and Chromium's `base::StringPiece`, we broadly have parity with `_LIBCPP_ASSERT` except for one place:

`absl::string_view(ptr, len)` checks `len <= std::numeric_limits<difference_type>::max()`:
https://github.com/abseil/abseil-cpp/blob/1d07cfede2d0153ebfa23543ffcc08faf55b4539/absl/strings/string_view.h#L202
https://github.com/abseil/abseil-cpp/blob/1d07cfede2d0153ebfa23543ffcc08faf55b4539/absl/strings/string_view.h#L603

Chromium `base::StringPiece(ptr, len)` takes a `base::CheckedNumeric<size_t>` and asserts the value fits:
https://chromium-review.googlesource.com/c/chromium/src/+/4021423

Bringing `base::CheckedNumeric<size_t>` in is clearly a bit much, but I think the Abseil check is functionally equivalent to the Chromium one: negative values will convert to some value between `PTRDIFF_MAX` and `SIZE_MAX`, and no allocation can be larger than `PTRDIFF_MAX` or pointer arithmetic doesn't work. Could we add an equivalent check to `std::string_view`?

**Comment by philnik777** [comment]
I don't think that's a good idea. Consider a system with a 16-bit bus. It's quite reasonable to just have a lot of static data, and then have a `string_view` to that data. Even if the data is more then 32k the `string_view` works just fine. Adding the `assert` would unnecessarily break this hypothetical program without any obvious benefit.

**Comment by davidben** [comment]
What is the size of `std::string_view::difference_type` (aka `ptrdiff_t`) in such a hypothetical system? Is it `int16_t`? If it's `int16_t`, I don't believe a single buffer can exceed 32k without problems. Specifically, pointer arithmetic will not work.

See also:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67999
https://sourceware.org/legacy-ml/libc-alpha/2019-04/msg00225.html

**Comment by philnik777** [comment]
> What is the size of `std::string_view::difference_type` (aka `ptrdiff_t`) in such a hypothetical system? Is it `int16_t`? If it's `int16_t`, I don't believe a single buffer can exceed 32k without problems. Specifically, pointer arithmetic will not work.
> 
> See also: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67999 https://sourceware.org/legacy-ml/libc-alpha/2019-04/msg00225.html

On my hypothetical system `ptrdiff_t` would be `int16_t`. For my example you wouldn't need any pointer arithmetic though, at least none that would subtract the pointers. Such a system also wouldn't allocate the memory dynamically, but have it baked into the binary.

**Comment by davidben** [comment]
Even using `std::string_view` itself involves pointer arithmetic. For instance, `std::string_view::end()` in libc++ is implemented by adding the pointers. While not the same type, `std::vector` actually doesn't even store the length, but start/end pointers.
https://github.com/llvm/llvm-project/blob/main/libcxx/include/vector#L545-L546

Per this comment, merely adding the pointer is already UB in Clang if the length doesn't fit in ptrdiff_t, not just subtraction.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67999#c5

C++20 even provides `std::ssize()`, which further implies such a buffer is not allowed.
https://en.cppreference.com/w/cpp/iterator/size

I don't think a `int16_t` `ptrdiff_t` can reasonably support > 32k buffers.

**Comment by philnik777** [comment]
> Even using `std::string_view` itself involves pointer arithmetic. For instance, `std::string_view::end()` in libc++ is implemented by adding the pointers. While not the same type, `std::vector` actually doesn't even store the length, but start/end pointers. Seems to me that would have been a perfectly valid `std::string_view` implementation. https://github.com/llvm/llvm-project/blob/main/libcxx/include/vector#L545-L546
> 
> Per this comment, merely adding the pointer is already UB in Clang if the length doesn't fit in ptrdiff_t, not just subtraction. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67999#c5
> 
> C++20 even provides `std::ssize()`, which further implies such a buffer is not allowed. https://en.cppreference.com/w/cpp/iterator/size
> 
> I don't think a `int16_t` `ptrdiff_t` can reasonably support > 32k buffers.

Even if it is technically UB, AFAICT it still probably works, since a lot of algorithms use `!=` instead of `<` (i.e. the addition would wrap around and would still iterate to the end). I just don't see that it actually catches anything meaningful. It's not like this will catch normal OOB errors or something similar. If your size is completely wrong it's about a 50/50 chance on most systems that an assert like this would trigger. So, from my point of view, the assert either triggers on code that is probably fine, or isn't exactly the most useful assert in the world. Enabling ASAN is _much_ more likely to catch anything this assert would ever catch.

**Comment by davidben** [comment]
To be clear, the goal is hardening checks in release builds. It's, sadly, pretty easy to accidentally pass a negative length to `string_view`, after which you get a buffer overflow. So ASan isn't sufficient for the kinds of projects that want to enable hardening checks in a release build, like a web browser.

If we're agreed this hypothetical 16-bit architecture that wants to use over half its address space on one buffer is UB, it seems a `_LIBCPP_ASSERT` is exactly the thing to add here, no? We should check easy-to-check cases of UB when assertions are on. If this hypothetical 16-bit architecture wants to skirt around UB, it can build without those checks.

The assertion could even be gated on `sizeof(ptrdiff_t) >= 4`, though I think that's silly. (Does LLVM support any 16-bit architectures?)

**Comment by zygoloid** [comment]
`std::string_view` is fundamentally unable to model strings whose size does not fit in a `std::ptrdiff_t`. For example, it is required that `s.end() - s.begin()` returns a `std::ptrdiff_t` representing the number of elements in the string, which is not possible if that number doesn't fit in `ptrdiff_t`. As such, it seems entirely reasonable for it to assert on construction if given a size that doesn't fit in that type.

While there are ways that a region of memory larger than the maximum value representable in a `ptrdiff_t` might be useful and usable in certain scenarios (eg, embedded 16-bit devices, or accessing a >2GB allocated memory region in a 32-bit database application), such allocations require very specialized and careful handling, and it is not reasonable to expect a general-purpose facility such as libc++'s `std::string_view` to be able to handle them.

Checking for negative values seems especially valuable, given that the erroneous cases (eg, a size of -1) are very close to the valid and common cases (eg, a size of 0), so that a minor arithmetic error can result in a `string_view` whose (unsigned) `size()` is very large, for example allowing out-of-bounds memory reads which might be important from a security perspective.

It seems to me that this check is both correct and useful.

**Comment by frederick-vs-ja** [comment]
> On my hypothetical system `ptrdiff_t` would be `int16_t`.

This is (re)allowed by [WG14-N2808](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2808.htm) in C23, but C++ hasn't made such change. (So using `int16_t` as `ptrdiff_t` is non-conforming in C++11 and later at this moment.)

Should we report an LWG issue like [LWG3828](https://cplusplus.github.io/LWG/issue3828) or waiting for the rebasing paper onto C23 (which is likely to be accepted for C++26 IMO)?


> Per this comment, merely adding the pointer is already UB in Clang if the length doesn't fit in ptrdiff_t, not just subtraction.
> https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67999#c5

This seems non-conforming, should we report a CWG issue (see [cplusplus/CWG](https://github.com/cplusplus/CWG))? [CWG2013](https://cplusplus.github.io/CWG/issues/2013.html) is related, but it only talks about subtraction.


> For example, it is required that `s.end() - s.begin()` returns a `std::ptrdiff_t` representing the number of elements in the string, which is not possible if that number doesn't fit in `ptrdiff_t`.

I guess this is not required in `basic_string_view` itself. Although most standard algorithms and range adaptors effectively require this.

**Comment by davidben** [comment]
I uploaded https://reviews.llvm.org/D145981 to add the assertion. (First contribution and first time using the tools, so apologies if I set something up wrong!)
