### ISSUE TITLE
[libc++] `std::declval` gives wrong result for `cv void`

### ISSUE THREAD

**Issue by fsb4000** [llvm/llvm-project#61232]
@frederick-vs-ja found that `std::declval` works wrongly for the code example:

```c++
#include <utility>
#include <type_traits>

int main() {
    static_assert(std::is_same_v<decltype(std::declval<const void>), const void () noexcept>);
    static_assert(std::is_same_v<decltype(std::declval<volatile void>), volatile void () noexcept>);
}
```

https://gcc.godbolt.org/z/rc483sWPo

**Comment by shafik** [comment]
It looks like libstdc++ is also doing the same thing, have you also filed a bug there as well? 

I have to look up the wording to see what we expect here.

**Comment by fsb4000** [comment]
Yes, I did https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109049

**Comment by fsb4000** [comment]
It looks like they don't want to fix that.

Should we file a LWG issue to fix the C++ standard instead?

**Comment by frederick-vs-ja** [comment]
I've mailed to LWG Chair to request legitimation of libc++ and libstdc++'s current strategy.

**Comment by EricWF** [comment]
The provided reproducer is not well-defined. 
I agree with Jonathan Wakely's position on the libstdc++ bug that was filed.

There's a defect in the standard here, but the defect is that the standard fails to explicitly call out this example as being ill-formed because it depends on the exact signature of `declval` which is an implementation detail. As Wakely points out, there is already language which disallows formation of a pointer/reference to the function, and that should be extended to include inspecting the exact type.
