### ISSUE TITLE
[C++20] [Modules] Add escape hatch for using modules with reserved names

### ISSUE THREAD

**Issue by mordante** [llvm/llvm-project#61446]
According to the Standard modules named `std` (and some variations) are reserved for the implementation. While implementing the module `std` in libc++ ([P2465](https://wg21.link/P2465)) Clang considers the code ill-formed due to the usage of a reserved module name. @ChuanqiXu9 provided a work-around by using `# 1 __FILE__ 1 3` in the `.cppm` file. This works. but feels quite fragile. When this line is not on line 1 the diagnostics will show the wrong line number, which is expected. (I ran into that several times, therefore I now have them at line 1.)

It would be great to have a way to tell Clang a specific module is part of the implementation and thus is allowed to use reserved names. For example using a compiler switch (to disable this diagnostic) or something like `#pragma system_file`. I'm not sure what the easiest solution in Clang is. For now this is an issue for libc++, but I expect the same issue will occur when libstdc++ implements its `std` module. (I don't know whether GCC will issue a diagnostic when using reserved module names.)

@AaronBallman I understood from @ChuanqiXu9 that you were involved in the discussion regarding the current behaviour.

Note this is not a blocker for libc++, but it's inconvenient.

**Comment by ChuanqiXu9** [comment]
Some background information: @mordan is implementing std modules in https://reviews.llvm.org/D144994. This is a big patch which is over 10000 lines of codes. So the requirement is understandable to me.

For perspective of the implementation, the easiest solution may be to add a flag for this (like `-fstd-modules` or `-freservered-modules` or `-fsystem-modules`, etc). I understand that we (the clang developers) don't want additional flags these days. Since we don't like dialects. But std modules may be an important feature to be an exception.

BTW, although currently we choose to implement std modules by the standard conforming styles, we are not sure if we can always do the standard conforming things. I mean, the language spec allows the implementation to do any hacks for std modules. And it should worth to add a flag to tell the compiler "oh, we are in the special mode".

**Comment by ChuanqiXu9** [comment]
@mordante it looks I didn't understand your problem enough. E.g., if we want to put the line number directives in other lines like 24 line, we should be able to put `# 24 __FILE__ 1 3` in 24 line.

(But this is still a workaround, of course)

**Comment by iains** [comment]
I think it might be essential to have this escape hatch once we perform the proper checking for "only textual inclusion" in the GMF (right now, code can get away with non-conforming GMF content).

Using a pragma to allow the "stdxxx" seems a clean way to do this.

**Comment by mordante** [comment]
> @mordante it looks I didn't understand your problem enough. E.g., if we want to put the line number directives in other lines like 24 line, we should be able to put `# 24 __FILE__ 1 3` in 24 line.

Yes that was what your original code did. After I added copyright headers it turned out the line number in the diagnostics was off. (I understand why they were off.)

**Comment by mordante** [comment]
Using the system header pragma was my first suggestion in the meeting we had yesterday. @ChuanqiXu9 thought there would be issues to implement this properly. So if this is easy to do I would be happy with this solution.

Personally I prefer a pragma over a compiler flag.

**Comment by ChuanqiXu9** [comment]
`#pragma clang system_header` should work. My concern is that the semantics is not consistent. Because the *.cppm files are not headers and they shouldn't be included. 

A cc1 flag works for me. I prefer a flag than a pragma since I think the compiler is allowed to perform special semantics for the GMF in std modules too. For example, the contents in the GMF are allowed to be discarded with certain rules. But we properly don't want to discard things from the GMF of std modules.

> I think it might be essential to have this escape hatch once we perform the proper checking for "only textual inclusion" in the GMF (right now, code can get away with non-conforming GMF content).
>
> Using a pragma to allow the "stdxxx" seems a clean way to do this.

I don't understand why this is related to the checking for "only textual inclusion" in the GMF?

**Comment by iains** [comment]
> `#pragma clang system_header` should work. My concern is that the semantics is not consistent. Because the *.cppm files are not headers and they shouldn't be included.

The pragma could be named "clang standard_library_module" and then it would applicable anywhere without confusion.

> A cc1 flag works for me. I prefer a flag than a pragma since I think the compiler is allowed to perform special semantics for the GMF in std modules too. For example, the contents in the GMF are allowed to be discarded with certain rules. But we properly don't want to discard things from the GMF of std modules.

we just have already so many modules flags, although a cc1 one case is better, since it's not supposed to be user-facing.

> > I think it might be essential to have this escape hatch once we perform the proper checking for "only textual inclusion" in the GMF (right now, code can get away with non-conforming GMF content).
> > Using a pragma to allow the "stdxxx" seems a clean way to do this.
> 
> I don't understand why this is related to the checking for "only textual inclusion" in the GMF?

I was thinking that dealing specially with #N ... lines embedded in a file that has not actually been pre-processed could make the handling of this much more complex in the preprocessor (we should maybe try to find some time to implement that diagnostic soon and see how much fallout we get).

**Comment by ChuanqiXu9** [comment]
> > `#pragma clang system_header` should work. My concern is that the semantics is not consistent. Because the *.cppm files are not headers and they shouldn't be included.
> 
> The pragma could be named "clang standard_library_module" and then it would applicable anywhere without confusion.
> 
> > A cc1 flag works for me. I prefer a flag than a pragma since I think the compiler is allowed to perform special semantics for the GMF in std modules too. For example, the contents in the GMF are allowed to be discarded with certain rules. But we properly don't want to discard things from the GMF of std modules.
> 
> we just have already so many modules flags, although a cc1 one case is better, since it's not supposed to be user-facing.

I understand that both of us may be PTSD with the modules flags. But I think we (including other possible future developers) possibly have to add other flags someday due the different requirement. Because modules are so complex. (But we should be serious about the new flags of course) 


Back to the specific topic, I still prefer a cc1 option. It is easy and innocent. And it looks much better than pragma personally. (I feel the pragma system is complex too)

> we should maybe try to find some time to implement that diagnostic soon and see how much fallout we get).

Maybe. The priority for this is a little bit low for me. Since it looks not helpful and can't reject the real harmful code. My understanding for the intention is to speedup the scanning and make the code prettier. (Maybe I am wrong).

**Comment by davidstone** [comment]
Given that clang will want to be able to compile libstdc++ and Microsoft's standard library, and that they probably won't add a clang pragma into their source, doesn't that force us to use a compiler flag?

**Comment by iains** [comment]
of course the other compilers will face this issue too - perhaps it's an idea for the 'vendors' to agree a common course of action - that makes life easier for users and build systems alike. (we could agree on a common pragma or command line flag).

**Comment by dwblaikie** [comment]
yeah, since any build system for a project that wants to "import std" may need the ability to build a pcm, however we need to build a pcm for the standard library /probably/ is a real driver flag, and ideally a portable one with gcc too (see the bloomberg stuff about module metadata files that might include flags for how to build a system-installed module, etc)

**Comment by dwblaikie** [comment]
Perhaps this is more like the `--sytem-header-prefix` sort of flags?

**Comment by mordante** [comment]
> yeah, since any build system for a project that wants to "import std" may need the ability to build a pcm, 

s/may/will/ ;-) As discussed on [discourse](https://discourse.llvm.org/t/rfc-about-the-default-location-for-std-modules/69191/29) libc++ will not ship binary BMIs. (At least not until there are portable BMIs.)

Libc++ will document how users and build systems can create libc++ BMIs. I intend to reach out to major build system vendors once we have something usable.

> of course the other compilers will face this issue too - perhaps it's an idea for the 'vendors' to agree a common course of action - that makes life easier for users and build systems alike. (we could agree on a common pragma or command line flag).
> 
> edit: will bring this up at the "modules bi-weekly meeting" which has representation from a number of places including MS.

Thanks for bringing this up with other compiler writers too!

**Comment by ChuanqiXu9** [comment]
@AaronBallman  according to the conclusion of "modules bi-weekly meeting", we prefer to turn the diagnostic off by default now and discuss if we should mark we're implementing a std module by an attribute or a pragma in the future.

We prefer to turn the diagnostic off by default temporarily now since we feel the current behavior is more strict than the requirement of the spec. Since the spec said "no diagnostic is required". And we think it is not harmful for users to not warning this temporarily. Because we assume anyone who is trying to implement std modules understands that he is doing the non-standard thing.

**Comment by AaronBallman** [comment]
Errr, I can hold my nose and live with that decision if the group thinks it's best, but it is a regression and should be treated as such. We diagnose reserved identifiers and this is a reserved identifier. We have plenty of experience with what happens when we don't diagnose reserved identifiers and know that failing to diagnose on this means users will use this identifier in their code. The longer we fail to diagnose, the harder it will be on us.

What are the chances that "in the future" means "within the Clang 17 release cycle"?

**Comment by dwblaikie** [comment]
What other reserved identifiers do we diagnose? 

I didn't think we caught, say, defining random stuff in the `std` namespace, or using the double-under or under-upper reserved names, for instance?

**Comment by AaronBallman** [comment]
> What other reserved identifiers do we diagnose?
> 
> I didn't think we caught, say, defining random stuff in the `std` namespace, or using the double-under or under-upper reserved names, for instance?

https://godbolt.org/z/s1Kbr1hcs

We've been improving diagnostics in this area for the past few releases (largely because the standards bodies started complaining that it's hard to claim names are actually reserved when nobody warns on their use), and more work is still to be done now that the C standard has clarified some things in https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2625.pdf

**Comment by ChuanqiXu9** [comment]
> We have plenty of experience with what happens when we don't diagnose reserved identifiers and know that failing to diagnose on this means users will use this identifier in their code. The longer we fail to diagnose, the harder it will be on us.

Understood. Personally I feel it won't be so painful for modules since the frequency that users declare a module unit is much less than a random identifiers.

> What are the chances that "in the future" means "within the Clang 17 release cycle"?

We don't make it clearly. But I guess it may not be in the Clang17 release cycle. So we want to get an agreed solution within the big 3 compiler's implementors. And given the current situation for modules, we think the priority for such limitations may not be too high.

**Comment by mordante** [comment]
> > What other reserved identifiers do we diagnose?
> > I didn't think we caught, say, defining random stuff in the `std` namespace, or using the double-under or under-upper reserved names, for instance?
> 
> https://godbolt.org/z/s1Kbr1hcs

Interesting, I hadn't seen this diagnostic before. Maybe a stupid question, but why does is the module code not use the same diagnostic when encountering reserved names? Disabling this diagnostic would be trivial for build systems/libc++.

**Comment by dwblaikie** [comment]
I was thinking of this mostly around just the `std` named module - it doesn't seem important to protect that (or even the numbered versions to any great degree) to me - because you can have only one in your entire program. If someone decides to violate the rule & then can't use the real std module - well, their module is the std module as far as we're concerned and that's OK to me? I don't see the need to have an extra switch that says "no, really, I'm making the std module, it's called std, I know that".

But given the reserved space is wider - yeah, I can see the value in checking it. But equally, given the need for all implementations to be able to build, in every project, a new BMI/PCM/etc for the standard library's modules - equally we can't have a cc1 flag for this, we need a real compiler supported flag to say "I'm building a standard library module". Yes/no/maybe?

And I think the existing warning flag's probably the right one, maybe sliced out as a subset jus tfor module names?

**Comment by AaronBallman** [comment]
> But given the reserved space is wider - yeah, I can see the value in checking it. But equally, given the need for all implementations to be able to build, in every project, a new BMI/PCM/etc for the standard library's modules - equally we can't have a cc1 flag for this, we need a real compiler supported flag to say "I'm building a standard library module". Yes/no/maybe?
> 
> And I think the existing warning flag's probably the right one, maybe sliced out as a subset jus tfor module names?

So would the idea be that we issue the diagnostic as a warning under some new group (`-Wreserved-module-identifier`?) that's grouped under `-Wreserved-identifier`? Or would we issue the diagnostic as an error that can be downgraded into a warning (that we don't ever expect to upgrade to be error-only in the future)?

Given:
> I was thinking of this mostly around just the std named module - it doesn't seem important to protect that (or even the numbered versions to any great degree) to me - because you can have only one in your entire program. If someone decides to violate the rule & then can't use the real std module - well, their module is the std module as far as we're concerned and that's OK to me? I don't see the need to have an extra switch that says "no, really, I'm making the std module, it's called std, I know that".

and that our existing `-Wreserved-identifier` diagnostics are all regular warnings, I am leaning towards a warning-only diagnostic. It sounds like the cure is worse than the disease to issue an error (that just means users are going to have to find this diagnostic the hard way and likely disable it entirely anyway).

**Comment by iains** [comment]
the reasoning around suggesting a pragma or attribute to suppress this in the sources is exactly this; that, essentially, all end users importing `std` as a named module will need to build it (since we are accepting that the provision of pre-built BMIs is such a narrow case as to be negligible).

As you say, the cure would indeed be worse than the disease if we make them chase around to find some diagnostic-suppressing flag to do that.

There is an opportunity to try and make the pragma/attribute named the same for at least the implementations that have discussed - but as @dwblaikie pointed out there are actually very few "users" of the pragma/attribute - i.e. the library writers  and those who accommodate building foreign libraries on each implementation.

once we have something like that in place, the diagnostic can default to "on" and it will do something reasonable.

**Comment by dwblaikie** [comment]
> As you say, the cure would indeed be worse than the disease if we make them chase around to find some diagnostic-suppressing flag to do that.

Sure enough - though, I think we're in the situation where we're expecting to have to ship config files to users including flags that describe how to build a given module? Or is there some level of support expected to be feasible without that?

I wouldn't be averse to an attribute either. I guess currently the reserved identifier warnings are disabled in system headers, and I think there's a pragma for system headers as well as a path-based classification, so I guess a pragma for "system module" would be OK too?

**Comment by ChuanqiXu9** [comment]
> the reasoning around suggesting a pragma or attribute to suppress this in the sources is exactly this; that, essentially, all end users importing std as a named module will need to build it (since we are accepting that the provision of pre-built BMIs is such a narrow case as to be negligible).

Yeah. Because we're assuming that the std modules will be built frequently by the users, the new flags are not welcomed. And we need to provide a method for the module writers to tell that they are implementing a reserved modules. Both pragma and attribute can achieve this. Personally I prefer attribute since it is more of morden and  we haven't implement attributes for modules yet. This can be a chance.

> Sure enough - though, I think we're in the situation where we're expecting to have to ship config files to users including flags that describe how to build a given module? Or is there some level of support expected to be feasible without that?

I think the current direction is the first one - we need to ship metadata for the modules.

> I wouldn't be averse to an attribute either. I guess currently the reserved identifier warnings are disabled in system headers, and I think there's a pragma for system headers as well as a path-based classification, so I guess a pragma for "system module" would be OK too?

It may be OK to have a pragma for "system modules". I am just wondering that if it may be redundant after someday we implement the attribute. I feel the attribute may be the future for modules since I saw some interesting proposals like:

```
export module safe_module [[safe_cpp]];
```

At least it looks interesting to me. And to be honest, I feel the pragma system looks a little bit old to me... (just personally)

---

> So would the idea be that we issue the diagnostic as a warning under some new group (-Wreserved-module-identifier?) that's grouped under -Wreserved-identifier?

I prefer this direction personally.

>  I'd feel more comfortable if we had a line in the sand like "if the other implementations don't have an agreed upon solution by the time Clang 17 ships, then we'll implement whatever we want for Clang 18." (or whatever schedule seems reasonable to us all). Would that be reasonable?

Yeah, I think it is reasonable and more workable direction.

**Comment by mordante** [comment]
> > As you say, the cure would indeed be worse than the disease if we make them chase around to find some diagnostic-suppressing flag to do that.
> 
> Sure enough - though, I think we're in the situation where we're expecting to have to ship config files to users including flags that describe how to build a given module? Or is there some level of support expected to be feasible without that?

Initially yes this is exactly how we (libc++) will ship modules. However we will reach out to build system vendors like CMake and ask them to add support to build the `std` module using their build system. At that point it's invisible which invocations are needed to build the `std`. So only early adapters and build systems need to be aware of these details.

> > But given the reserved space is wider - yeah, I can see the value in checking it. But equally, given the need for all implementations to be able to build, in every project, a new BMI/PCM/etc for the standard library's modules - equally we can't have a cc1 flag for this, we need a real compiler supported flag to say "I'm building a standard library module". Yes/no/maybe?
> > And I think the existing warning flag's probably the right one, maybe sliced out as a subset jus tfor module names?
> 
> So would the idea be that we issue the diagnostic as a warning under some new group (`-Wreserved-module-identifier`?) that's grouped under `-Wreserved-identifier`? Or would we issue the diagnostic as an error that can be downgraded into a warning (that we don't ever expect to upgrade to be error-only in the future)?

I would be fine with a warning. I would suggest to add the `DiagGroup` `ReservedIdentifier` to the `DiagGroup` `Extra` or at least to `Most` that way the diagnostic has a higher probability of being visible. Until a few days ago I was unaware of this diagnostic in Clang. I wouldn't object against the `DiagGroup` `All` either when the Clang developers feel comfortable with that.

**Comment by AaronBallman** [comment]
Okay, it sounds like we've got a path forward then. I'll downgrade the current error into a warning (only) so that should ease the pain immediately, and we'll wait to hear back what kind of feature to add (attribute/pragma/whatever) from the modules vendor discussions, and go from there.

**Comment by AaronBallman** [comment]
I put up https://reviews.llvm.org/D146986 for review to address this, we can discuss details there.
