### ISSUE TITLE
Miscompile in (lshr (ctlz x) C)

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#61549]
here's a function:
```llvm
define i35 @f(i35 %0) {
  %2 = srem i35 1, %0
  %3 = call i35 @llvm.ctlz.i35(i35 %2, i1 false)
  %4 = lshr i35 %3, 5
  ret i35 %4
}

declare i35 @llvm.ctlz.i35(i35, i1 immarg) #0
```
when passed `8` as an argument, it should return `1` because:
```ll
%2 = 1
%3 = 34
%4 = 1
```
however, when compiled to AArch64 by latest llc we get:
```asm
_f:
	mov	w8, #1 
	sbfx	x9, x0, #0, #35
	sdiv	x10, x8, x9
	msub    x8, x10, x9, x8
	eor	x0, x8, #0x1
	ret
```
and this returns `0` for the same input, verified using this driver:
```c
unsigned long f(unsigned long);

#include <stdio.h>

int main(void) {
  unsigned long res = f(8UL);
  printf("%lu\n", res);
}
```

cc @nunoplopes

**Comment by lenary** [comment]
This is fun https://godbolt.org/z/n478qsq3G
- `llc --mtriple=aarch64` does indeed generate the code you show.
- `clang --target=aarch64` (with your input as a `.ll` file) does not quite generate the same assembly. It generates an `mul;subs` pair instead of the `msub`, and it will squash it to `mov x0, #1` at any optimisation level except `-O0`.
- This is not an issue with globalisel, but this example doesn't work with globalisel anyway: if you try `llc --mtriple=aarch64 --global-isel` with the input you get an assertion failure: `unable to legalize instruction: %4:_(s35) = G_CTLZ %3:_(s35)`.

---

Looking further at this miscompile, it's coming from SelectionDAG, where the builder constructs a DAG that looks like:
```
Initial selection DAG: %bb.0 'f:'
SelectionDAG has 14 nodes:
  t0: ch,glue = EntryToken
  t7: i35 = Constant<5>
              t2: i64,ch = CopyFromReg t0, Register:i64 %0
            t3: i35 = truncate t2
          t5: i35 = srem Constant:i35<1>, t3
        t6: i35 = ctlz t5
      t9: i35 = srl t6, Constant:i64<5>
    t10: i64 = any_extend t9
  t12: ch,glue = CopyToReg t0, Register:i64 $x0, t10
  t13: ch = AArch64ISD::RET_FLAG t12, Register:i64 $x0, t12:1
```

Which matches the LLVM IR pretty closely, which then goes through an initial DAGCombine stage to become:
```
Optimized lowered selection DAG: %bb.0 'f:'
SelectionDAG has 11 nodes:
  t0: ch,glue = EntryToken
            t2: i64,ch = CopyFromReg t0, Register:i64 %0
          t3: i35 = truncate t2
        t5: i35 = srem Constant:i35<1>, t3
      t14: i35 = xor t5, Constant:i35<1>
    t10: i64 = any_extend t14
  t12: ch,glue = CopyToReg t0, Register:i64 $x0, t10
  t13: ch = AArch64ISD::RET_FLAG t12, Register:i64 $x0, t12:1
```

Which I think points to the bug, being in DAGCombiner here: https://github.com/llvm/llvm-project/blob/main/llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp#L10307-L10342

I'm not sure this is valid for non-power-of-two data sizes. The value of `Known` here is that the bottom bit is unknown, and the rest of the bits are all known to be zero. This effectively says that `t5` is known to be either `0` or `1` (as an unsigned value). This gives `t6` the value of either `35` or `34` respectively, which both give `t9` the value of `1`.

As I said above, if you pass this to `clang -O1`, then this seems to all get folded away into the correct "return 1". I looked for an equivalent fold InstCombine there and it correctly has an additional requiring the bitwidth to be a power of two: https://github.com/llvm/llvm-project/blob/d7b4b76956e2da8b251c4e6121624477e1491211/llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp#L1201-L1212

When I added an `isPowerOf2_32(OpSizeInBits)` to the condition in the DAGCombiner, it generates a sequence of instruction that looks correct to me -- the `eor` is replaced with `clz x8, x8; sub x8, x8 #29; ubfx x0, x8, #5, #30` (where the sub is needed to convert the 64-bit clz's return value into its 35-bit equivalent, and the ubfx is doing the shift).

On this basis, I'm going to remove the backend:AArch64 label as I think this will affect all SelectionDAG-based backends, even though you found the bug with AArch64. I've also added the `llvm:optimizations` label on that basis.

---

One piece of meta-feedback I do have is to be careful about blindly linking the output of IR files with nonstandard width arguments/returns to the output of clang-compiled C code. Clang thinks the LLVM IR signature for `f` in the driver is `declare i64 @f(i64 noundef)`, which does not match the signature in the LLVM IR example - In general I think you end up needing to add `zeroext` and `signext` on arguments that are passed in registers to make this match up, though I'm not entirely sure what is needed for this example.

**Comment by lenary** [comment]
Here are a sequence of patches:
- https://reviews.llvm.org/D147515 Updates a GlobalISel test so that the next change is more specific
- https://reviews.llvm.org/D147516 Ensures GlobalISel can legalise non-power-of-two ctlz
- https://reviews.llvm.org/D147517 Adds your example above as a testcase for both SelectionDAG and GlobalISel
- https://reviews.llvm.org/D147518 is the DAGCombiner fix itself, showing the update to your testcase

**Comment by lenary** [comment]
@EugeneZelenko the main bug reported here affects *all* backends because it is in the DAGCombiner, I just tested it via AArch64 because that was how it was originally reported (and no existing tests were affected by the pessimisation). The GlobalISel crash is AArch64-only, but that isn't the source of the miscompile itself. Does this change the principle by which you tag this?
