### ISSUE TITLE
Question: How does clang assume alignment for extern C arrays?

### ISSUE THREAD

**Issue by knzivid** [llvm/llvm-project#61592]
I am trying to investigate why I hit a segmentation fault in C++. I am pretty certain this is a bug in my code. But I wanted to know why Clang behaves differently compared to GCC here. I am a beginner to reading assembly, please correct me if I made any false assumptions :)

Consider the snippet (https://www.godbolt.org/z/PKroaEKoo)

```cpp
#include <cstdint>
#include <string>

using T = unsigned char;

template<size_t n>
int asString(const T (&t)[n])
{
    return std::string(t, t + n).at(0);
}

extern T data[14717];

int main()
{
    return asString(data);
}
```

Here, `data` comes from an object file generated through a binutils derivative. The alignment of data is not explicitly specified.

```console
$ readelf --sections --symbols data.o --wide
There are 5 section headers, starting at offset 0x3a70:

Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
  [ 1] .data             PROGBITS        0000000000000000 000040 003981 00  WA  0   0  1
  [ 2] .symtab           SYMTAB          0000000000000000 0039c8 000048 18      3   1  8
  [ 3] .strtab           STRTAB          0000000000000000 003a10 00003d 00      0   0  1
  [ 4] .shstrtab         STRTAB          0000000000000000 003a4d 000021 00      0   0  1
```

When I look at the generated assembly, this is unrolled into `movups`. In the internal binary I am investigating, I do see a mix of `movaps` and `movups` where the string constructor is called. The extern C array is copied using `movaps` here to `xmm`.

```asm
0x00215090      movaps   xmm0,   xmmword [rcx + rsi - 0x50]
0x00215095      movaps   xmm1,   xmmword [rcx + rsi - 0x40]
0x0021509a      movups   xmmword [rax + rsi - 0x50],  xmm0
0x0021509f      movups   xmmword [rax + rsi - 0x40],  xmm1
0x002150a4      movaps   xmm0,   xmmword [rcx + rsi - 0x30]
0x002150a9      movaps   xmm1,   xmmword [rcx + rsi - 0x20]
0x002150ae      movups   xmmword [rax + rsi - 0x30],  xmm0
0x002150b3      movups   xmmword [rax + rsi - 0x20],  xmm1
0x002150b8      movaps   xmm0,   xmmword [rcx + rsi - 0x10]
0x002150bd      movaps   xmm1,   xmmword [rcx + rsi]
0x002150c1      movups   xmmword [rax + rsi - 0x10],  xmm0
0x002150c6      movups   xmmword [rax + rsi],  xmm1
0x002150ca      add      rsi,    0x60
0x002150ce      cmp      rsi,    0x39b0                     ; case.0x553b30.2 ; case.0x553b30.2 ; case.0x553b30.2
0x002150d5      jne      0x215090                           ; likely       
```

**Question 1**: How does Clang know to choose `movaps` vs `movups`? According to [this SO answer](https://stackoverflow.com/a/61197816), "the x86-64 System V ABI requires that static arrays of 16 bytes or larger be aligned by 16". Using [movaps](https://www.felixcloutier.com/x86/movaps) with an XMM register also requires 16 byte alignment. Are these the only constraints?

**Question 2**: Even though the minimal example uses `movups`, my internal binary uses a mix of `movups` and `movaps`. Do you have any suggestions on how to go about debugging this? Both my internal binary and Godbolt are essentially the same code.

**Question 3**: In the Godbolt example, changing `using T = char` defers to a `memcpy`. Does this mean marking the extern C array as `unsigned char` produce better code or is this influenced by something else? I understand "better" here is subjective, and I want to understand the reasons behind the difference in generated code.

**Comment by frederick-vs-ja** [comment]
I have no idea on Question 1 and 2, but I think I can make some explanation for Question 3.

This is probably resulted from the design of libstdc++ (IIUC Godbolt configures Clang to use libstdc++ by default).

In libstdc++ (see [`<bits/basic_string.h>`](https://github.com/gcc-mirror/gcc/blob/573dbd5175dbf16a3b4551ec55800febf0d1b617/libstdc%2B%2B-v3/include/bits/basic_string.h)), iterator-pair constructor of `string` eventually executes `_S_copy_chars`. If the iterators are `basic_string`'s iterators or pointer to the character type (`const char*` in the example), `_S_copy` is executed, which may in turn execute `traits_type::copy`. Otherwise (e.g. when the iterator is `const unsigned char*`), it always performs per-element `traits_type::assign`.

When the specialization is `std::string`, the `traits_type` is `std::char_traits<char>` (see [`<bits/char_traits.h>`](https://github.com/gcc-mirror/gcc/blob/573dbd5175dbf16a3b4551ec55800febf0d1b617/libstdc%2B%2B-v3/include/bits/char_traits.h)). And then we can find that libstdc++'s `std::char_traits<char>::copy` may call `memcpy` via `__builtin_memcpy` at runtime.

Theoretically, per-element `std::char_traits<char>::assign` in this case in the loop may also be replaced with a `memcpy` call, but Clang currently doesn't do this in `basic_string` construction with given compiler options. Perhaps this is because of that the conversion from `unsigned char` to `char` make the analysis for contiguous storage difficult.

**Comment by jyknight** [comment]
Q1: Yes, Clang ccan assume 16-byte alignment of the global due to the ABI specification. If you are writing data 16 bytes or longer using an external tool, you should ensure it's also 16-byte aligned to be ABI-compliant. If you were writing data of some other non-char type, it would also need to also be aligned according to the type's alignment.

Q2: Whether it emits `movups` or `movaps` in a particular case isn't really important -- what's important is that the actual data alignment must adhere to the requirements. However, I'll note that in your existing example, `asString` isn't inlined into `main`. If you give 'asString' internal linkage via putting "static" before it, it's more likely to be inlined, and, in fact is, in this example. And when inlined, the compiler can see that it's operating on the global `data`, and will thus emit `movaps`.
