### ISSUE TITLE
LLVM_ENABLE_PROJECTS & LLVM_ENABLE_RUNTIMES should be disjoint, yet openmp is listed in both?

### ISSUE THREAD

**Issue by bjodah** [llvm/llvm-project#61649]
I'm building llvm from source, and I'm a bit confused by the documentation of the cmake options:

From https://llvm.org/docs/CMake.html, emphasis (bold) is mine
<dl>
<dt>LLVM_ENABLE_PROJECTS:STRING</dt>
<dd>Semicolon-separated list of projects to build, or all for building all (clang, lldb, lld, polly, etc) projects. This flag assumes that projects are checked out side-by-side and not nested, i.e. clang needs to be in parallel of llvm instead of nested in llvm/tools. This feature allows to have one build for only LLVM and another for clang+llvm using the same source checkout. The full list is: clang;clang-tools-extra;cross-project-tests;libc;libclc;lld;lldb;<b>openmp</b>;polly;pstl</dd>
<dt>LLVM_ENABLE_RUNTIMES:STRING</dt>
<dd>Build libc++, libc++abi, libunwind or compiler-rt using the just-built compiler. This is the correct way to build runtimes when putting together a toolchain. It will build the builtins separately from the other runtimes to preserve correct dependency ordering. If you want to build the runtimes using a system compiler, see the [libc++ documentation](https://libcxx.llvm.org/BuildingLibcxx.html). Note: the list <b>should not have duplicates with LLVM_ENABLE_PROJECTS</b>. The full list is: compiler-rt;libc;libcxx;libcxxabi;libunwind;<b>openmp</b> To enable all of them, use: LLVM_ENABLE_RUNTIMES=all</dd>
</dl>

I get the impression that openmp runtime is perhaps different from the openmp "compiler"? Either way I think the docs could be improved here, would you agree?

**Comment by DimitryAndric** [comment]
This is a historical left-over. At some point, the 'runtimes' were introduced, and at the time you could build some of the components both as a 'project' or as a 'runtime'. Doing the former would give you a warning about "building component foo as a project is now deprecated", to give the user some time to adjust their build scripts.

However, at a later point in time, some of the components were actively removed from the possible projects list, i.e. libcxx, compiler-rt, etc. It looks like openmp is now the only one left that supports both "modes", so that is probably the reason it is in both lists.

I expect that at some point, the openmp folks will delete the projects entry, and then there should be no more duplicates.

**Comment by jhuber6** [comment]
This is also true for the `libc` project as far as I'm aware @sivachandra. For OpenMP, the runtimes method is only relevant when building the GPU runtime. So, we decided explicitly support both methods for convenience. Using runtimes and projects implies different builds, I personally don't see a problem with supporting these different configurations. For `libc`, I'm working on an implementation for the GPU that requires the runtimes method, but otherwise `libc` should be able to be built with a sufficiently new `GCC` as far as I'm aware.

**Comment by sivachandra** [comment]
> This is also true for the `libc` project as far as I'm aware @sivachandra.

From the user's point of view, it is not required anymore as including the libc project into the list of runtimes automatically includes it in the list of enabled projects automatically: https://github.com/llvm/llvm-project/blob/main/llvm/CMakeLists.txt#L175
