### ISSUE TITLE
[clang] Availability attribute only triggers on the second use of a variable

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#61815]
```shell
cat <<EOF | clang++ -xc++ - -fsyntax-only
template <class _ValueType = int>
class __attribute__((unavailable)) polymorphic_allocator { };

void f() {
    polymorphic_allocator<void> a;
    polymorphic_allocator<void> b;
}
EOF
```

This fails with:

```console
<stdin>:6:5: error: 'polymorphic_allocator<void>' is unavailable
    polymorphic_allocator<void> b;
    ^
<stdin>:2:36: note: 'polymorphic_allocator<void>' has been explicitly marked unavailable here
class __attribute__((unavailable)) polymorphic_allocator { };
                                   ^
1 error generated.
```

In reality, it should have failed on the first usage of `polymorphic_allocator<void>`, which is when declaring `a`.

Also on Godbolt: https://godbolt.org/z/aEsfjcdT1

**Comment by shafik** [comment]
It looks like the first time through parsing `f()` when we parse the declaration of `a` we don't have the complete type for the `ClassTemplateSpecializationDecl` but the next time around we do.

I don't see any obvious place to fix this in the parsing but I am not super familiar with this part but I was able to modify `Decl::getAvailability(....)` to fix this, I noticed we had a carve out for `FunctionTemplateDecl` so I added one for `ClassTemplateSpecializationDecl` like so:

```cpp
if (auto *FTD = dyn_cast<FunctionTemplateDecl>(this))
    return FTD->getTemplatedDecl()->getAvailability(Message, EnclosingVersion,
                                                    RealizedPlatform);
  else if (auto *CTSD = dyn_cast<ClassTemplateSpecializationDecl>(this))
    return CTSD->getSpecializedTemplate()->getTemplatedDecl()->getAvailability(Message, EnclosingVersion,
                                                    RealizedPlatform);
```

I don't know if this is the right way or if this indicates a parsing design issue that was worked around before and I am just adding another work-around.

@AaronBallman wdyt?

**Comment by shafik** [comment]
CC @zygoloid who may also know the answer to this as well

**Comment by zygoloid** [comment]
The problem here is that this diagnostic is produced before we require `polymorphic_allocator<void>` to be a complete type -- and indeed in similar examples we never require it to be a complete type. For example:

```
extern polymorphic_allocator<void> x;
```

... should presumably warn, but doesn't instantiate the class template definition.

Most attributes are only instantiated with the class template definition, rather than being instantiated with the declaration. There's a flag on the attribute definition in `Attr.td` to indicate that the attribute should instead be instantiated with the declaration. Bizarrely, this attribute is called `MeaningfulToClassTemplateDefinition` and its doc comment is backwards too... Setting that to `1` for the `Unavailable` attr definition should fix this.

**Comment by shafik** [comment]
Yup, that does it, adding `let MeaningfulToClassTemplateDefinition = 1;` fixes this issue.

**Comment by AaronBallman** [comment]
> Surprisingly, this flag is called `MeaningfulToClassTemplateDefinition` and its doc comment is backwards too... Setting that to `1` for the `Unavailable` attr definition should fix this.

Whoops, looks like we got the naming wrong there -- that came in through https://reviews.llvm.org/D31245

**Comment by shafik** [comment]
PR: https://reviews.llvm.org/D147495
