### ISSUE TITLE
Clang will ignore using declarations from qualified name lookups when handling declarators

### ISSUE THREAD

**Issue by ChuanqiXu9** [llvm/llvm-project#62174]
See https://godbolt.org/z/8eef5nsEs and the text form is:

```cpp
namespace lib {
    namespace impl {
        template <class>
        inline constexpr bool test = false;
    }
    using impl::test;
}

struct foo {};

template <>
inline constexpr bool lib::test<foo> = true;

static_assert(lib::test<foo>);
```

GCC will accept this but Clang will reject this.

**Comment by ChuanqiXu9** [comment]
I sent https://reviews.llvm.org/D148506 as a ad-hoc patch.

**Comment by Endilll** [comment]
I think GCC behaves correctly, and Clang doesn't:

0. `test` on line 12 is a qualified name ([basicl.lookup.qual/2.4.5](http://eel.is/c++draft/basic.lookup#qual.general-2.4.5)).
1. `test` has to undergo a qualified name lookup in the lookup context of `lib` from the point where it appears ([basicl.lookup.qual/3](http://eel.is/c++draft/basic.lookup#qual.general-3.sentence-2)).
2. Qualified name lookup is a _search_ in associated scope ([basicl.lookup.qual/3](http://eel.is/c++draft/basic.lookup#qual.general-3.sentence-1)).
3. Search is a _single search_, because `lib` is not a class or class template ([class.member.lookup/1](http://eel.is/c++draft/basic.lookup#class.member.lookup-1.sentence-1)).
4. Single search finds all declarations in `lib` that precede the point where `test` appears, taking into account using declarations whose terminal name is not dependent ([basic.lookup.general/3](http://eel.is/c++draft/basic.lookup#general-3)).
5. Name `test` on line 6 is not dependent ([temp.dep.type/5](http://eel.is/c++draft/temp.dep.type#5)), which means it should be found.

Most of this wording comes from [P1787R6](https://wg21.link/p1787r6). I hope this helps!
