### ISSUE TITLE
[OpenMP][Doc] perl is required to build openmp but not mentioned on docs

### ISSUE THREAD

**Issue by raigorx** [llvm/llvm-project#62289]
https://github.com/llvm/llvm-project/blob/acc4abea2e6a1d561bba40c60c04ad181b345999/openmp/runtime/cmake/config-ix.cmake#L224

**Comment by ppenzin** [comment]
I've done some digging, it is used for two things:

- `kmp_i18n_*.inc` - those are generated from the sole file, `openmp/runtime/src/i18n/en_US.txt`
- `libomp.def` _on Windows_

For `i18n` one of the `.inc` files produces an enum which is supposed to match strings in the other one. It might be possible to nuke the script and refactor the code to use a single include. @alexey-bataev what do you think?

Have not looked not Windows-only script yet. There are a few more perl scripts in the same directory, haven't checked for references to them in the build files.

**Comment by alexey-bataev** [comment]
> I've done some digging, it is used for two things:
> 
> * `kmp_i18n_*.inc` - those are generated from the sole file, `openmp/runtime/src/i18n/en_US.txt`
> * `libomp.def` _on Windows_
> 
> For `i18n` one of the `.inc` files produces an enum which is supposed to match strings in the other one. It might be possible to nuke the script and refactor the code to use a single include. @alexey-bataev what do you think?
> 
> Have not looked not Windows-only script yet. There are a few more perl scripts in the same directory, haven't checked for references to them in the build files.

I think, it would be good to rework this and use python instead of perl

**Comment by ppenzin** [comment]
Do we need this error definition file format (input to the script) for anything else? Would redefining the messages via a set of macros in a header fit into the preferred coding approach? Tablegen might be an option too, though that won't work for standalone builds.

**Comment by jhuber6** [comment]
> Do we need this error definition file format (input to the script) for anything else? Would redefining the messages via a set of macros in a header fit into the preferred coding approach? Tablegen might be an option too, though that won't work for standalone builds.

Not that I'm aware of, maybe @jpeyton52 has some more context, but I think it's just an error code + description pair.

**Comment by ppenzin** [comment]
Yes, that is what it is. Do you know if anyone downstream redefine that to change error language?

**Comment by jpeyton52** [comment]
For context, the Perl scripts for generating the two `kmp_i18_*.inc` files come from the initial import (circa 2013) from the Intel OpenMP runtime library which did support limited internationalization through message catalogs. Much of the internationalization Perl script machinery wasn't imported to LLVM because internationalization of messages / message catalogs wasn't cared for though the default English messages were still needed. It was simplest to keep the generation of the `kmp_i18_*.inc` files.

The host runtime started out with quite a few Perl scripts. I remember trimming the number of Perl scripts down to 4 at some point.

I'd much rather just convert these Perl scripts to Python3 scripts. Python3 is `REQUIRED` for LLVM development (despite LLVM's own documentation suggesting it is optional solely to enable lit testing).

- https://llvm.org/docs/GettingStarted.html#software
- https://github.com/llvm/llvm-project/blob/main/llvm/CMakeLists.txt#L915
