### ISSUE TITLE
[clang] MemProfContextDisambiguation.cpp(2019,29): function cannot access 'AllocTypeCloningPriority' - Visual Studio 17 2022

### ISSUE THREAD

**Issue by jonathan-haubrich** [llvm/llvm-project#62321]
Compiling clang on Windows using `cmake -G "Visual Studio 17 2022"` results in the following error:
```
llvm-project\llvm\lib\Transforms\IPO\MemProfContextDisambiguation.cpp(2019,29): error C23
26: 'bool CallsiteContextGraph<ModuleCallsiteContextGraph,llvm::Function,llvm::Instruction *>::identifyClones::<lambda_
1>::operator ()(const std::shared_ptr<CallsiteContextGraph<ModuleCallsiteContextGraph,llvm::Function,llvm::Instruction
*>::ContextEdge> &,const std::shared_ptr<CallsiteContextGraph<ModuleCallsiteContextGraph,llvm::Function,llvm::Instructi
on *>::ContextEdge> &) const': function cannot access 'AllocTypeCloningPriority' [C:\Users\dweller\source\repos\llvm-pr
oject\build\lib\Transforms\IPO\LLVMipo.vcxproj]
```

It appears this might be caused by a bug related to lambdas, captures, and c-style arrays in more recent versions of MSVC / cl. See here: https://developercommunity.visualstudio.com/t/c2326-compiler-error-when-explicitly-capturing-a-c/1085499

A simple fix / workaround is to explicitly capture AllocTypeCloningPriority in the lambda rather than using the implicit capture default.

On line `2010` of `MemProfContextDisambiguation.cpp` changing `[&](` to `[&AllocTypeCloningPriority](` resulted in clang compiling successfully.

Version info:
```
Microsoft Visual Studio Community 2022
Version 17.3.5
VisualStudio.17.Release/17.3.5+32922.545
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA977
Microsoft Visual C++ 2022

Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31630 for x64
```

**Comment by teresajohnson** [comment]
Is this happening before or after 969268831b9e409dd66af10c12fe17431e09b70f, which I committed about 30 mins ago?

That was to fix an issue reported by this lambda capture specifically for MSVC 2022, where it apparently had a problem with that array being constexpr. See https://reviews.llvm.org/D140949#inline-1438809.

@aganea indicated it built ok with the constexpr switched to just const. Please confirm whether the problem exists before or after 969268831b9e409dd66af10c12fe17431e09b70f.

When it was previously constexpr, I couldn't add an explicit capture because clang-14 complained that a lambda capture of a constexpr wasn't needed. However, if I didn't put a default & capture then other compilers complained with different errors.

**Comment by jonathan-haubrich** [comment]
Yeah that is the same issue. I was getting the error on main branch, not that commit. I can test, but it's probably safe to close this issue.

**Comment by teresajohnson** [comment]
Sounds good!
