### ISSUE TITLE
[Sema]Is this an interger constant expression?

### ISSUE THREAD

**Issue by erickq** [llvm/llvm-project#62420]
In llvm17, the expression `(int)(double)(1.7f)` is an interger constant expression?

**Comment by shafik** [comment]
Are you asking about C or C++? Is there any more context that you can fill in?

As far as I can tell this is a constant expression in both C and C++ but I may be missing some subtle issues.

**Comment by erickq** [comment]
![image](https://user-images.githubusercontent.com/12108571/235036912-ab2e908e-95b6-4dd9-ab15-9d78e33c66e4.png)

@shafik Thank you. My colleague encountered this problem while running the supertest test suite. It seems that after llvm17, this expression is considered an interger constant expression.

**Comment by shafik** [comment]
So this looks like C and section `6.6 Constant expressions` p6 says (*emphasis mine*):

> An integer constant expression127) shall have integer type and shall only have operands that are integer
> constants, enumeration constants, character constants, sizeof expressions whose results are integer
> constants, _Alignof expressions, and `floating constants that are the immediate operands of casts.`
> `Cast operators in an integer constant expression shall only convert arithmetic types to integer types`,
> except as part of an operand to the sizeof or _Alignof operator.

Seems to allow that but @AaronBallman is our C conformance code owner so he should confirm that I am not missing something here.

**Comment by AaronBallman** [comment]
It is not an integer constant expression because of the cast to `double` because that's not converting an arithmetic type to an integer type. Even if the type doesn't change (e.g., `(int)(double)1.0`), it's not an ICE. However, we fold it as an integer constant expression, same as GCC: https://godbolt.org/z/oooYa19fq

That said, the C committee made a change in C23 to say that you can never extend the definition of an integer constant expression (https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2713.htm), which I submitted a paper asking the committee to walk back due to how much code it breaks (https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3125.pdf). The committee hasn't considered this later paper yet, but it will be discussed at the national body comment review meeting in a few months.

**Comment by shafik** [comment]
Note both clang and gcc provide a diagnostic using `-pedantic`: https://godbolt.org/z/zbevr7bsh

```c
struct A {
  int y : (int)(double)10.f;
};

static_assert((int)(double)10.f);
```

Diagnostic from clang:

```console
<source>:2:11: warning: expression is not an integer constant expression; folding it to a constant is a GNU extension [-Wgnu-folding-constant]
  int y : (int)(double)10.f;
          ^~~~~~~~~~~~~~~~~
<source>:5:34: warning: no newline at end of file [-Wnewline-eof]
static_assert((int)(double)10.f);
                                 ^
<source>:5:15: warning: expression is not an integer constant expression; folding it to a constant is a GNU extension [-Wgnu-folding-constant]
static_assert((int)(double)10.f);
              ^~~~~~~~~~~~~~~~~
3 warnings generated.
Compiler returned: 0
```

**Comment by erickq** [comment]
Thank you very much@shafik  @AaronBallman
