### ISSUE TITLE
Constexpr variable with non-trivial constexpr destructor can generate global/exit-time destructor warnings

### ISSUE THREAD

**Issue by pkasting** [llvm/llvm-project#62436]
```c++
struct S {
  constexpr ~S() {}  // Intentionally not =default so as to be non-trivial
};
constexpr S s;
```
Compiling with `-std=c++20 -Wglobal-constructors -Wexit-time-destructors` triggers both those warnings (see https://godbolt.org/z/9xbKK4Gr1). This seems overly pessimistic; per https://en.cppreference.com/w/cpp/language/constexpr, "If a variable has constant destruction, there is no need to generate machine code in order to call destructor for it, even if its destructor is not trivial.", and indeed there seems to be no generated destructor call here despite the warnings. So I think the warnings are being emitted erroneously.

**Comment by tbaederr** [comment]
Both of these are emitted in `Sema::FinalizeVarWithDestructor()` in `lib/Sema/SemaDeclCXX.cpp`.

_If_ this can simply be ignored for `constexpr` variables, this should be easy to fix.

**Comment by danakj** [comment]
I believe that sentence is talking about inside try blocks, since exceptions can not be thrown in constexpr expressions. It's part of this statement:
> Even though try blocks and inline assembly are allowed in constexpr functions, throwing exceptions or executing the assembly is still disallowed in a constant expression.

So that if a constexpr function is evaluated in a constant expression, the destructors do not need to be generated at `throw`. 

 Constexpr objects are destroyed and can have non-trivial destructors since C++20, they need to run generally.

**Comment by danakj** [comment]
Chatted offline with pkasting. Here's the spec from c++20:

> 7 An object a is said to have constant destruction if:
> (7.1) — it is not of class type nor (possibly multi-dimensional) array thereof, or
> (7.2) — it is of class type or (possibly multi-dimensional) array thereof, that class type has a constexpr destructor,
> and for a hypothetical expression E whose only effect is to destroy a, E would be a core constant
> expression if the lifetime of a and its non-mutable subobjects (but not its mutable subobjects) were
> considered to start within E.

Here the `S` has constant destruction as its destructor does not do anything to make it not evaluate as a core constant expression.

Then, as the variable was initialized at compile time, it does not need to be destroyed at runtime. I agree with Peter's analysis and these checks are incorrect. No machine code should be generated for the destructor.

In fact, it would seem that to do otherwise can introduce bugs. If the destructor has `if (std::is_constant_evaluated())` which evals to `false` when the destructor was run, it may try to clean things up that do not match with the constructor which was run in a constant expression and thus would have seen `if (std::is_constant_evaluated())` eval to true.

**Comment by shafik** [comment]
I am looking at the check in `Sema::FinalizeVarWithDestructor` and it looks like:

```cpp
if (!VD->hasGlobalStorage()) return;

  // Emit warning for non-trivial dtor in global scope (a real global,
  // class-static, function-static).
  Diag(VD->getLocation(), diag::warn_exit_time_destructor);

  // TODO: this should be re-enabled for static locals by !CXAAtExit
  if (!VD->isStaticLocal())
    Diag(VD->getLocation(), diag::warn_global_destructor);
```

should be moved into the block before:

```cpp
// If the destructor is constexpr, check whether the variable has constant
  // destruction now.
  if (Destructor->isConstexpr()) {
```

that block as added in 2b4fa5348ee15 by @zygoloid it feels like this was overlooked in that change.

**Comment by pkasting** [comment]
https://reviews.llvm.org/D149713
