### ISSUE TITLE
[Flang] Default initialize module variables to zero [527.cam4_r failure]

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#62432]
The cam4 spec2017 benchmark is failing since module variables are initialized as `undef`. This can cause not well-defined behaviour to happen if the module variable is used in an `if` statement. Use the `zeroinitializer` to fix the issue.

A simple reproducer is:
```f90
module simple
logical :: async_interf
contains
  subroutine one
    print *, "one = ", async_interf
    if (async_interf) then
      print *, "Inside async"
    end if
  end subroutine
end module
program mn
use simple
call one()
end program
```
The code above will print the following result with Flang when compiled with LTO and O2.
```console
one = F
Inside async 
```
The LLVM IR generated marks the module variable `async_interf` as undefined.
```ll
 @_QMsimpleEasync_interf = local_unnamed_addr global i32 undef
```
The variable being marked as undef makes the if comparison pointless and optimisation either remove the if check or hoists the code outside the if.

**Comment by Leporacanthicus** [comment]
For simple types, this is trivial to fix - 3-4 lines of code-change and a few tests that needs changing.  I haven't fixed tests yet, but I've got the basic simple types working.

Aggregate types shouldn't be too hard, but need some changes in CodeGen.cpp, the ZeroOpConversion currently doesn't support aggregate types.

**Comment by sscalpone** [comment]
Does standard Fortran support initializing module variables?

For the record, I support statically allocating module variables with zeros and not marking them as undef, which I consider to be the expected default behavior for Fortran.

**Comment by tschuett** [comment]
At least Flang should warn about the access of the uninitialised variable. GCC supports for security reasons: `-ftrivial-auto-var-init=choice`
https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-ftrivial-auto-var-init

**Comment by kiranchandramohan** [comment]
> Does standard Fortran support initializing module variables?
I don't think the standard prescribes anything here. This is processor dependent. But gfortan and Classic Flang initializes these variables to zero.

> For the record, I support statically allocating module variables with zeros and not marking them as undef, which I consider to be the expected default behavior for Fortran.
OK. We discussed this a bit in the last technical call on April 17th. @jeanPerier was also recommending zero-initialization but also suggested we could do something (like poison in llvm) to trigger some runtime debug for uninitialized values.


> At least Flang should warn about the uninitialised variable. GCC supports for security reasons: `-ftrivial-auto-var-init=choice`
> https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-ftrivial-auto-var-init

There is also `-Wuninitialized`. Not sure whether the `auto` here refers to stack-allocated variables which might not apply to the case of module variables.

> Story: My plan was to initialise `async_interf` with true, I forgot, and Flang secretly initialises the variable with `0` ?!?
If you print it out, you are likely to get `false`. But the internal LLVM IR representation is `undef` which can cause some transformations to apply.

**Comment by tschuett** [comment]
I am inclined to follow the C/C++ standards. Never initialise uninitialised variables. It can cause surprising behaviour.  Why zero, you could use patterns or random values.

Warn about all initialised variables.

The lifetime of the module variables ends when the modules ends. It is like a local variable (auto).

**Comment by vzakhari** [comment]
I think the LTO is doing a legal thing for the example in the description: if this module is the only one that the LTO sees, then it is obvious that the variable has undefined value and it can be optimized in any way.

I wonder what is the code closure (list of modules) in cam that causes the problem.

**Comment by Leporacanthicus** [comment]
> I am inclined to follow the C/C++ standards. Never initialise uninitialised variables. It can cause surprising behaviour. Why zero, you could use patterns or random values.
> 
> Warn about all uninitialised variables.
> 
> The lifetime of the module variables ends when the modules ends. It is like a local variable (auto).

From Fortran 2008 onwards, module globals have an implicit SAVE attribute, which makes them similar to static variables in C or C++. 

See 8.5.16.4 on page 106 in this:
https://j3-fortran.org/doc/year/18/18-007r1.pdf

Based on that, and the fact that flang is aiming to be a F2018 compatible compiler, I'd say zero initializing is fair and as expected for a C or C++ programmer. And from other code that I've seen, that's what programmers expect - assuming they expect anything. 

Agreed, pre-2008, the behaviour of module globals [and various other things also covered by the 4 section in the above paragrapph] were not guaranteed to remain from one use [1] of a module to the next - I believe the motivation for that behaviour was the ability to have overlays in some compilers, mainly those for 16-bit computers - like the PDP-11 I used at school and early PCs and similar machines.

So, zero-initialization is reasonable here. It is also the default in a few other compilers, so there is a precedent. For example in gfortran [without extra flags]:
```
__simple_MOD_async_interf:
	.zero	4
```

**Comment by Leporacanthicus** [comment]
> I think the LTO is doing a legal thing for the example in the description: if this module is the only one that the LTO sees, then it is obvious that the variable has undefined value and it can be optimized in any way.
> 
> I wonder what is the code closure (list of modules) in cam that causes the problem.

I think the real problem is that we have some code that is along the lines of:

```
module A
logical a_variable
...
subroutine sub
    if (a_variable) then 
      ... 
    end if
end sub
''''
Somwehere else there's another module:
```
module b

 use a, only a_variable
 
... 

subroutine do_stuff(logical x)
...
    x = .false.
    if (something) then
       x = .true.
   end if
....
end subroutine do_stuff

subroutine do_work
...
   do_stuff(a_variable)
...
end do_work
```

[This is actually quite simplified still - it's inside a struct and there's also an array of them, I think]. 

So whilst the variable is indeed initalized, the linker/optimizer isn't quite "following the flow", so it doesn't understand that the variable does indeed get initialized. 

So, I agree that the linker is not doing anything wrong. I'm not convinced there's any other way than "initialize the variable" to fix it.

**Comment by tschuett** [comment]
The C and C++ standard forbids to initialize uninitialized variables! Maybe Fortran is different.

But it would be an amazing user experience, if you could give a detailed warning.
- `a_variable` is uninitialized
- `if(a_variable)` reads an uninitialized variable (`a_variable`).
With line and column numbers and code.

**Comment by Leporacanthicus** [comment]
> The C and C++ standard forbids to initialize uninitialized variables! Maybe Fortran is different.
> 
> But it would be an amazing user experience, if you could give a detailed warning.
> 
> * `a_variable` is uninitialized
> * `if(a_variable)` reads an uninitialized variable (`a_variable`).
>   With line and column numbers and code.

And in my example, the variable IS initialized, just not in module a - it is done by module b [we assume that do_work does gets called at some point].

As I've already written: from Fortran 2008 onwards: there is an implied SAVE on the module-wide variable, which means that in C terms, it's a static or global variable, a static is a global variable that doesn't have it's name available to other translation units. It is, in C and C++, initialized to zero on all standards compliant implementations of C, and has been like that for a VERY long time. Fortran doesn't specify that these values should or shouldn't be initialized, that's an implementation detail. It makes sense to followi the standard of C global variables, which ARE initialized to zero according to the C standard (and C++ just copy-pasted that part). 

For variables local to a function, it would definitely be possible to determine that a variable is not initialized (or "May not be initialized" in cases where branches are involved).

When it's a global variable, you can't know at compilation time - it MAY be possible to determine for some cases with LTO, but there's lots of problems trying to achieve this - it would be valid to not initialize some variable if it never gets used - for example some optional functionality.

I do not believe anyone is arguing that the code in Spec-2017 is actually not initializing this variable - although the simple example here is minimized to show the problem.

**Comment by Leporacanthicus** [comment]
Yes, you are missing that these are to all intents and purposes global variables. The variables we are changing are not `auto` storage. They are, in C terms, `static` storage, which according to the C standard are always initialized to zero [if not explicitly initializes of course]. See above about "implicit SAVE", I even linked the standards document - that means the variable has the same lifetime as the whole program. Whilst that was not guaranteed in earlier Fortran specifications - up to 2003, it is now. It was then "implementation defined" how it worked, so you can't rely on any specific behaviour across different compilers.

Yes, the simple example is showing the effect of reading a global value that is uninitialized. The REAL code is complex, and the LTO-linker just doesn't understand that the code in another module actually DOES set the value, and then compiles the code in the original module as if it was never set, even though it has been set (to false). If you have access to SPEC-2017 source code, feel free to analyze the cam4 behavioru on `ios%async_interface` - it is being read in lots of places, and it is set in two places. Which happens before the calls to the code that reads it. Just, because the code is complicated, LTO-linker doesn't understand what happens and says "Uh, this is undefined, I'll just remove this if-statement and execute the code inside always".  There is possibly soemthing we could do to fix LTO, but it seems like an awkward solution. 

Also note that the code I'm editing to fix this is in flang/lib/Lower/ConvertVariable.cpp, in the function `defineGlobal` - it is a global variable in this compiler. I would not take this approach if the code was reading an uninitialized local variable.

**Comment by tschuett** [comment]
That was a surprise. From the C++ standard:
`[Note 1: Objects with static or thread storage duration are zero-initialized, see 6.9.3.2. —end note]`

**Comment by tschuett** [comment]
Due to the uncertainty by the external linkage, you could still warn that:
`if (async_interf) then`
may read an uninitialized value.

**Comment by Leporacanthicus** [comment]
Thanks for all the thoughts, I think we need to discuss this some more. I wrote a long reply, but I think I need to discuss with my team before actually replying.

**Comment by Leporacanthicus** [comment]
I have to apologise. The problem is really just that "we don't initialize globlas to zero, so LTO does it's job and says undefined - removes the if as it is completely entitled to do". 

I misunderstood my colleague's notes on what was actually going wrong, and looked at a different part of the code. 

The ACTUAL problem is that we have:

```
module a
logical a_variable

subroutine sub_one
...
   logical a_variable    ! Yes, shadowing the global.
   
    a_variable = .false. 
    ...
    if (something) then
        a_variable = .true. 
    end if
   ...
end subroutine

subroutine sub_two
...
    if (a_variable) then
       call do_stuff_that_will_not_work
   end if
....
end subroutine

end module
```

So, the variable is never set. Nothing to do with flang-new or the compiler - it's a bug in Spec-2017. Unfortunately, there's no way to fix this, since modifying Spec is not allowed. It HAPPENS to work in other compilers, because other compilers, apparently, don't treat unset global variables as true.

If I comment out the shadowing variable, everything works correctly.

I'm not sure what we can do here. It's clearly not a flang bug. But we want this benchmark to run on flang, but modifyiung the source of the benchmark, as far as I know is a BIG NO! So, we'll have to live with "this benchmark doesn't work, becasue we set global variables to undef". And yes, I agree, we should not change the compiler to fix this. At the same time, we want the benchmark to work. Impossible to solve.

**Comment by tschuett** [comment]
Thank you for your detailed analysis:
```
#include <stdio.h>

extern bool a_variable;

void important() {
  bool a_variable;  // shadows global a_variable
  a_variable = false;

  if (a_variable)
    printf("");

  a_variable = true;
}

void evenMoreImportant() {
  if (a_variable) // <-- reads uninitialized a_variable 
    printf("");
}
```
In this example, Clang gives **no** warnings.


I have some interest in which warnings should Flang give in the benchmark to help users and what methods Flang provides to find issues.

**Comment by vzakhari** [comment]
Thank you for the follow-up, Mats!
I think the consensus is that zero-initializing the module variables will save users a lot of trouble with their non-conformant programs, so I guess we can proceed with the implementation.  At the same time, I think we should also propose the source patch to spec.org.  SPEC CPU 2017 is the current version benchmark package, so correctness patches will be accepted.

I can prepare the patch if you give me some pointers: the variable name and the places where it is read and where it is supposed to be set (but is shadowed by a local).

**Comment by Leporacanthicus** [comment]
Some more digging about to report:

1. The problem is really that the compiler can determine that "nothing sets this". It ONLY happens when using -flto - or at least, I can't make it happen when -flto isn't being used. The actual flag is false, it just removes the condition - I'm assuming this is a direct result of "undef is always true" (or something like that).
2. In gfortran, even with -flto, it doesn't remove the check of the flag. I'm not 100% sure if this is simply less aggressive detection of undefined, or that gfortran simply doesn't say it's undefined in the first place, "because globals aren't undefined" or some such.

@vzakhari thanks for the supporting notes. I will see if I can come up with a compiler patch that solves this sort of thing.

**Comment by Leporacanthicus** [comment]
<snip code sample>
> In this example, Clang gives **no** warnings.
> 
> I have some interest in which warnings should Flang give in the benchmark to help users and what methods Flang provides to find issues.

I think this is a separate subject. It's RELATED, but it needs its own ticket. In this ticket, we're trying to deal with the general treatment of global (module) variables and what they should be initialized to - zero or undef. Feel free to raise a ticket for this.

And like I said before, the detection of uninitialized global variables can be quite tricky - it certainly requires "whole program analysis", since a variable may declared in one module, and filled in in a different module. Or there may be code to fill it in, but that code is never called. Both of these will cause false results - positive or negative - when analyzing individual moduels.

**Comment by tschuett** [comment]
Totally agreed. However, it would be awesome if Flang gets well-known for great warnings.

For the C/C++ story, there is a [Discourse](https://discourse.llvm.org/t/clang-warnings-on-uninitialized-variables/70353/10) thread.

**Comment by Leporacanthicus** [comment]
I'll leave this open for a few more days, I'm seriously considering covering other types, except derived types that is a further complication. See review comments on the subject. 

See also this two-year old thread:
https://discourse.llvm.org/t/zero-initialization-for-globals-with-common-linkage/1762/2

**Comment by kiranchandramohan** [comment]
The `cam4` issue is fixed by https://reviews.llvm.org/D149877.

**Comment by thtsikas** [comment]
In my view, this is not a satisfactory fix. In the first place, there is nothing to "fix" since the example is non-conforming. Faced with a program with no interpretation within the Fortran rules, and no identifiable numbered constraint that is violated, we can only implement some form of extension. 

This extension would be described as an addition to 19.6.3 **Variables that are initially defined**, para 1, list item 7
(7) scalar non-allocatable, non-pointer variables of intrinsic type LOGICAL, INTEGER, REAL that have the SAVE attribute.

Provided this description correctly identifies what we intended and implemented, and amended until it does, I argue that it is of greater benefit if this extension were placed under control of a user-selectable switch (most conveniently in the form of a command-line option). By testing the behaviour of the resulting executable program under both settings, a user has a means of discovering logic errors in their program. Hardwiring the extension in, as we do now, means that such errors will only be discovered when the program is ported to a new environment. I argue that this is a disservice to users and decades of experience have shown that to be the case.
