### ISSUE TITLE
manual popcnt has unnecessary cmove since clang 16.0.0

### ISSUE THREAD

**Issue by y21** [llvm/llvm-project#62450]
Code:
```c
int popcnt(int x) {
    int cnt = 0;
    while (x) {
        cnt++;
        x &= x - 1;
    }
    return cnt;
}
```

On x86-64 clang 16.0.0 as well as trunk (17.0.0 d7fa92126cc398b993f301273816739b23ed8740) with `-O -march=haswell` compiles to:
```asm
popcnt:                                 # @popcnt
        popcnt  eax, edi
        cmove   eax, edi
        ret
```
(Note the unnecessary cmove)

On clang 15.0.0 with the same options:
```asm
popcnt:                                 # @popcnt
        popcnt  eax, edi
        ret
```

[Reproducer](https://godbolt.org/z/fbMEvxjKd)

**Comment by nikic** [comment]
We probably need to switch the select value equivalence fold to perform operand replacement ignoring poison flags/metadata and then drop them, rather than the current hack of trying to drop and restore flags (which doesn't cover the metadata case).

**Comment by pcordes** [comment]
In case it helps, the extra `cmove` has come and gone in recent clang versions:

* Clang 10: not present (good)
* Clang 11, 12: present (bad)
* Clang 13, 14, 15: not present (good)
* Clang 16, 17-trunk: present (bad)

This happens even with `-march=znver1` so it's (hopefully) unrelated to an attempt to mitigate the false output dependency in Sandybridge-family before Ice Lake.

(Related: lzcnt/tzcnt have a false output dependency that's fixed in Skylake.  And `bsf` / `bsr` have a *true* output dependency on Intel and AMD CPUs which even the normally-cautious GCC doesn't bother to avoid. https://stackoverflow.com/questions/21390165/why-does-breaking-the-output-dependency-of-lzcnt-matter discusses `popcnt` as well since it's the same hardware execution unit)

**Comment by nikic** [comment]
Proof: https://alive2.llvm.org/ce/z/eny5hd
