### ISSUE TITLE
[BUG?]the length of key cause diffrent result when using llvm::ScopedHashTable

### ISSUE THREAD

**Issue by 95833** [llvm/llvm-project#62453]
```cpp
#include "iostream"
#include "llvm/ADT/SmallString.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/ADT/ScopedHashTable.h"

llvm::ScopedHashTable<llvm::StringRef, std::string> symbolTable;

void declare(std::string key, std::string val)
{
    symbolTable.insert(key, val);
}

int main()
{
    llvm::ScopedHashTableScope<llvm::StringRef, std::string> varScope(symbolTable);
    declare("short_key_is_0", "123");
    llvm::errs() << symbolTable.count("short_key_is_0") << "\n";  

    declare("long_long_long_long_long_long_long_long_long_long_long_long_key_is_1", "123");
    llvm::errs() << symbolTable.count("long_long_long_long_long_long_long_long_long_long_long_long_key_is_1") << "\n";

    declare("short_key_is_0", "123");
    llvm::errs() << symbolTable.count("short_key_is_0") << "\n";
    return 0;
}
```
building will output 0 1 0,  how to fix it?

**Comment by EugeneZelenko** [comment]
@95833: Please elaborate.

**Comment by dwblaikie** [comment]
I'm guessing what's happening is that you're creating pointers to dangling std::string's, that's why the long string "works" sort of, but the short ones don't. (the long one will get heap allocated when the string literal is copied into a std::string in the `declare` call (that buffer will be deallocated at the end of `declare` but at least probably not immediately overwritten), but the short ones will use the short string optimization into the stack space for the parameter which will get overwritten at subsequent calls) 

Try this with msan, valgrind, etc.
