### ISSUE TITLE
-frelaxed-template-template-args: "error: pack expansion used as argument for non-pack parameter of alias template" with constrained alias template

### ISSUE THREAD

**Issue by ecatmur** [llvm/llvm-project#62529]
Motivation:
```c++
#include <boost/hana/type.hpp>
template<class> requires(true) using U = int;
auto t = boost::hana::template_<U>(boost::hana::type_c<char>);
```
Reduced:
```c++
template<class> requires(true) using U = int;
template<template<typename ...> class, class> struct S {};
template<class T> S<U, T> f();
auto t = f<int>();
```
compiled with `-frelaxed-template-template-args` gives:
```console
<source>:2:31: error: pack expansion used as argument for non-pack parameter of alias template
template<template<typename ...> class, class> struct S {};
```
(we need `-frelaxed-template-template-args` for other reasons)
Workaround: use `std::enable_if_t` to constrain alias template instead.

**Comment by shafik** [comment]
CC @cor3ntin 

Also some context: https://discourse.llvm.org/t/why-frelaxed-template-template-args-is-added-back/65727

**Comment by mizvekov** [comment]
I believe clang is correct in rejecting it, per [CWG1430](https://cplusplus.github.io/CWG/issues/1430.html), which is still open, but has consensus on rejection.

The bug is not diagnosing it, which is an oversight in the pre-P0522 implementation of template template parameter matching, which is still used as a fast path in the post-P0522 implementation. This fast path is purposefully skipped when the argument template is constrained.
