### ISSUE TITLE
[C++20] [Modules] Workaround for builtin initializers

### ISSUE THREAD

**Issue by onelumin** [llvm/llvm-project#62541]
A.cppm:
```C++
export module A;

export namespace A {
    void foo();
}
```

A.cpp:
```C++
module A;

namespace A {
    void foo() {}
}
```

C.cpp:
```C++
import A;

int main() {
    A::foo();
}
```

Build:
```
clang++ -std=c++2b A.cppm --precompile -o A.pcm
clang++ -std=c++2b -fmodule-file=A=A.pcm -c A.cpp -o A.o
clang++ -std=c++2b C.cpp -fmodule-file=A=A.pcm A.o
```

**Comment by dwblaikie** [comment]
I think it's safe to say a build system couldn't/wouldn't/shouldn't need to know about the contents of the A.cppm file - clang should behave the same regardless and so the build system should expect to/require a .o file for every cpp/cppm file and link them all together. (to avoid naming collisions, build systems generally use a more fully qualified object file name, like a.cppm.o - since this could come up without modules, with a.c, a.C, a.cxx, a.cpp, etc... )

As an optimization, clang might be able to avoid adding extra code to these object files when it's not needed - but you shouldn't depend on that for build correctness.
