### ISSUE TITLE
`clang -dumpconfig` is not matching stated architecture of the release

### ISSUE THREAD

**Issue by thorsten-klein** [llvm/llvm-project#62582]
Hello,
I am using release [clang+llvm-16.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz](https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.0/clang+llvm-16.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz)

If I run `clang -dumpmachine` I get `x86_64-unknown-linux-gnu`.
Additionally also a folder `lib/x86_64-unknown-linux-gnu` is existing. 
I would expect it to be `lib/x86_64-linux-gnu` instead.

The issue I face: The directory is by default specified in `ld` command:
```shell
ld -L/bin/../lib/x86_64-unknown-linux-gnu
```
Older CMake versions (e.g. 3.21.3) take the `CMAKE_LIBRARY_ARCHITECTURE` from the first `-L` directory of the linker command. As a result `CMAKE_LIBRARY_ARCHITECTURE` will always be `x86_64-unknown-linux-gnu` when using clang (instead of `x86_64-linux-gnu` on Ubuntu). CMake's `find_library` will not find libraries anymore which are placed under `/usr/lib/x86_64-linux-gnu`. This means: clang16 does not work with those cmake versions (Note: with newer cmake versions it is fixed, e.g. 3.26.3)

PS: I have also submitted an issue to CMake: https://gitlab.kitware.com/cmake/cmake/-/issues/24884

**Comment by MaskRay** [comment]
Always having the "vendor" part when printing the target triple is intentional as it makes the output format more uniform (https://reviews.llvm.org/D110663).
To the best of my knowledge, GCC compiled from source and most non-Debian derivative distributions also always have the "vendor" part.
However, Debian and its derivatives deviate by omitting the "vendor" part (usually "unknown").
