### ISSUE TITLE
Clang ignores preprocessor directives when modularized headers are mixed with nonmodularized headers

### ISSUE THREAD

**Issue by alanzhao1** [llvm/llvm-project#63043]
This was found when I was attempting to find a minimal reproduction for https://crbug.com/1430962. It is likely that these two bugs have the same or at least a similar root cause.

Repro steps:

I have commit 1cf5188c72902e85e85095d788f5dfa138c320f8 checked out.

All of these files are in the same directory.

```cpp
// nonmod.h
#ifndef NONMOD_H_
#define NONMOD_H_

int foo() {
#ifdef FOO_RET_1
  return 1;
#else
  return 0;
#endif
}

#endif  // NONMOD_H_
```

```cpp
// mod.h
#ifndef MOD_H_
#define MOD_H_

#include "nonmod.h"

#endif  // MOD_H_
```

```
// module.modulemap
module mod {
  export *
  header "mod.h"
}
```

```cpp
// translation_unit.cc
#define FOO_RET_1
#include "nonmod.h"
#include "mod.h"
```

Expected behavior:

When compiling `translation_unit.cc` with modules enabled, `foo()` should return 1.

Actual behavior:

`foo()` correctly returns 1 when compiled with `-fno-modules` but `foo()` incorrectly returns 0 when compiled with `-fmodules`:

```sh
# All commands are run in the same directory where the files are saved.

# With modules
$ ~/src/llvm-project/build-debug/bin/clang++ -c -S -emit-llvm -o - -fno-modules translation_unit.cc

# extra lines removed...

; Function Attrs: mustprogress noinline nounwind optnone uwtable
define dso_local noundef i32 @_Z3foov() #0 {
entry:
  ret i32 1
}

# ...

$  ~/src/llvm-project/build-debug/bin/clang++ -c -S -emit-llvm -o - -fmodules translation_unit.cc

# extra lines removed...

; Function Attrs: mustprogress noinline nounwind optnone uwtable
define dso_local noundef i32 @_Z3foov() #0 {
entry:
  ret i32 0
}

# ...
```

**Comment by zygoloid** [comment]
You have an ODR violation, for two different reasons:

1) `foo` is not declared `inline`, and is defined in two translation units (the header module for `mod.h` and `translation_unit.cc`).
2) (If `foo` were declared `inline`) `foo` has multiple definitions that are not equivalent. Because there is more than one definition, Clang will in practice pick one arbitrarily.

**Comment by alanzhao1** [comment]
> foo is not declared inline, and is defined in two translation units (the header module for mod.h and translation_unit.cc).

Interesting - so does this mean that modularizing a header file makes that header file introduces a new translation unit? My current understanding is that:

* If `translation_unit.cc` is compiled *without* header modules, then there should be only one TU.
* If compiled without modules, the header guards should prevent the ODR violation

I find this surprising because it looks like enabling `-fmodules` causes Clang to interpret my example code in a different (and possibly nonstandard?) way. Is this correct?

**Comment by zygoloid** [comment]
That's not exactly right. Enabling `-fmodules` isn't what's causing a difference in behavior here; the difference comes from specifying that `mod.h` should be handled as a header module -- in particular, that's a misconfiguration in this case, because `mod.h` does not have modular semantics, because its behavior is intended to depend on macros leaking into the header from outside.

The semantic effects of modules are described [in clang's documentation](https://clang.llvm.org/docs/Modules.html#module-semantics).
