### ISSUE TITLE
BOLT and LBR collection on AMD Epyc Milan (zen3)

### ISSUE THREAD

**Issue by ss7pro** [llvm/llvm-project#63077]
I am trying to get BOLT running on zen3 but I'm running into the issues while collecting performance profile. I'm unable to collect data using -e events and needs to revert to -e cpu/branch/brs.

```
tomasz@m1:~$ sudo perf record -b -e cycles:u  -a sleep 1

Error:

The sys_perf_event_open() syscall returned with 22 (Invalid argument) for event (cycles:u).

/bin/dmesg | grep -i perf may provide additional information.

tomasz@m1:~$ sudo perf record -b -e cpu/branch-brs/  -c 1000037  -a sleep 1

[ perf record: Woken up 1 times to write data ]

[ perf record: Captured and wrote 1.898 MB perf.data (518 samples) ]


tomasz@m1:~$ 
```

@aaupov

**Comment by aaupov** [comment]
Please use branch-brs event if it works. That's not something that BOLT controls. However, you may want to report the issue to the kernel mailing list because the documentation says it can be used with any event:

https://lwn.net/Articles/877245/#:~:text=BRS%20can%20be,c%201000037%20test
> BRS can be used with any sampling event. However, it is recommended to use
the RETIRED_BRANCH event because it matches what the BRS captures. For
convenience, a pseudo event matching the branches captured by BRS is
exported by the kernel (branch-brs):

> $ perf record -b -e cpu/branch-brs/ -c 1000037 test

**Comment by ss7pro** [comment]
It's a documentation error. Kernel code allows only specific event for branch sampling: https://github.com/torvalds/linux/blob/457391b0380335d5e9a5babdec90ac53928b23b4/arch/x86/events/amd/brs.c#L135
