### ISSUE TITLE
[OpenMP] runtime segfault with target tasks

### ISSUE THREAD

**Issue by ye-luo** [llvm/llvm-project#63093]
```
$ clang++ -fopenmp -march=native -fopenmp-targets=x86_64-pc-linux-gnu test_target_task.cpp
$ clang++ -fopenmp -march=native --offload-arch=sm_80 test_target_task.cpp
$ OMP_NUM_THREADS=4 ./a.out
*** stack smashing detected ***: terminated
Segmentation fault (core dumped)
```
Doesn't really matter offload to gpu or host.

reproducer `test_target_task.cpp`
```
#include <vector>

int main()
{
  #pragma omp parallel
  {
    std::vector<int> avec(16384);
    auto* a = avec.data();
    #pragma omp target teams distribute nowait map(a[:16384])
    for(int i = 0; i < 128; i++)
    {
      #pragma omp parallel for
      for(int j = 0; j < 128; j++)
      { a[i * 128 + j] = j; }
    }
  }
}
```

**Comment by jdoerfert** [comment]
And this is not a stack overflow? Uname doesn't fix it, right?

**Comment by ye-luo** [comment]
I changed the reproducer to use heap.
When I use taskwait at the end of the parallel, the test pass.
The implicit barrier should clear all the pending tasks but it somehow goes wrong.

**Comment by shiltian** [comment]
It is test issue. The implicit barrier only guarantee that all children tasks have to be done before it proceed. However, the implicit barrier is *after* the execution of the body of a parallel region. Here is a stack variable `avec` and its corresponding heap memory. Its lifetime is only within the body of the parallel region. It will be released after the execution of the body. At this moment, the target tasks are still running, and after the execution of the target region, there is an implicit D2H memcpy for the point `a`. Since `avec` might have been released, `a` becomes a dangling pointer and all the memcpy becomes UD. If you add `map(to: a[:16384])`, there will be no issue.

**Comment by ye-luo** [comment]
> It is test issue. The implicit barrier only guarantee that all children tasks have to be done before it proceed. However, the implicit barrier is _after_ the execution of the body of a parallel region. Here is a stack variable `avec` and its corresponding heap memory. Its lifetime is only within the body of the parallel region. It will be released after the execution of the body. At this moment, the target tasks are still running, and after the execution of the target region, there is an implicit D2H memcpy for the point `a`. Since `avec` might have been released, `a` becomes a dangling pointer and all the memcpy becomes UD. If you add `map(to: a[:16384])`, there will be no issue.

You are right. There is a scope issue. I need to figure out a more precise reproducer for my exact issue.
