### ISSUE TITLE
[Flang] Miscomparison in 649.fotonik3d_s (OpenMP version)

### ISSUE THREAD

**Issue by kiranchandramohan** [llvm/llvm-project#63143]
The fotonik speed benchmark when compiled with OpenMP at `O3` gives a miscomparison now.

```console
*** Miscompare of pscyee.out; for details see
    /home/pop2/spec-2017/benchspec/CPU/649.fotonik3d_s/run/run_base_refspeed_mytest-64.0000/pscyee.out.mis
0002:    8.93206724662593E-52  8.93312290368238E-52  8.93417832626705E-52
         9.44523780957191E+15  9.44517651664593E+15  9.44511519359890E+15
                            ^
```

Note: There are portability issues mentioned in the Spec page (https://www.spec.org/cpu2017/Docs/benchmarks/649.fotonik3d_s.html). But the non-OpenMP version passes with llvm/flang. So there is likely an OpenMP codegen issue.

**Comment by wangbyby** [comment]
How many threads do you use？
I also found miscompare in 644.nab with `threads=4` ,`size=test`
And O0 would run success.

**Comment by wangbyby** [comment]
@kiranchandramohan Oh, thanks.
And if you close openmp, what would happen?

**Comment by shivaramaarao** [comment]
could not get reduced testcase. But, the issue seems to be part of the code in UPML.f90 as below.
2816 !
2817 ! Update the fields on the boundary between Yee and PML.
2818 ! (Note that Ez(1,1,:) are excluded from this block since these fields
2819 ! were updated in Block 1).
2820 j = 1
2821 #if (defined(_OPENMP) || defined(SPEC_OPENMP)) && !defined(SPEC_SUPPRESS_OPENMP) && !defined(SPEC_AUTO_SUPPRESS_OPENMP)
2822 !$OMP DO
2823 #endif
2824 do k=1,nz
2825   do i=1,nx
2826
2827     Dxold = Dx_jlow(i,j,k)

Here j is initialized to 1 at line 2820. but that value is not getting propagated into do loop
if we print j value inside the loop, it shows -11 at some iterations. sometimes it shows 1 as well. looks like some copying issue of private variables for OMP DO constructs inside parallel region.

**Comment by wangbyby** [comment]
@shivaramaarao  What arch you use? Maybe it releated to arch?

**Comment by shivaramaarao** [comment]
@wangbyby  I used x86 arch. I believe the issue is reproducible with ARM as well.

**Comment by kiranchandramohan** [comment]
Thanks @shivaramaarao for investigating this.

The variable `j` is private to the Parallel region. But it is also a loop index of sequential loops (these should be privatised according to the standard), and also the loop index of some OpenMP Do Loops (which also should be privatised). I am assuming something is going wrong in the interaction of all these different privatisations.

@DavidTruby recently fixed one issue here. But he said he also noticed something else. 
https://github.com/llvm/llvm-project/pull/68723
