### ISSUE TITLE
[PowerPC] call to _mcount emitted by -pg needs to be emitted BEFORE function prolog

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#63220]
From an LKML thread: https://lore.kernel.org/llvm/20230609034501.407971-1-naveen@kernel.org/

```
Ftrace on ppc32 expects a three instruction sequence at the beginning of
each function when specifying -pg:
	mflr	r0
	stw	r0,4(r1)
	bl	_mcount

This is the case with all supported versions of gcc. Clang however emits
a branch to _mcount after the function prologue
```
Example: https://godbolt.org/z/8r83PKorK

As a result, support for function tracing is being disabled in the linux kernel for ppc32 when built with clang.

cc @nemanjai @nemanja-ibm

**Comment by chenzheng1030** [comment]
@nickdesaulniers Hi thanks for reporting this issue. Does this issue still matter? If so, maybe I can make a fix.

**Comment by nickdesaulniers** [comment]
Probably. cc @nathanchance who can follow up.

**Comment by chenzheng1030** [comment]
On PPC, there is a codegen improvement that moves `stw` away from its feeder `mflr` because `mflr` might have long latency. This will break the expected instructions.

Must these three instructions be in the sequence in the description? What's the relationship between this task and the -fpatchable-function-entry support on ppc32? In https://lore.kernel.org/llvm/20230609034501.407971-1-naveen@kernel.org/, it says "This can be re-enabled
later if clang picks up support for -fpatchable-function-entry on ppc32.", so we can also fix this by supporting -fpatchable-function-entry on ppc32?

@nickdesaulniers @nathanchance

**Comment by rnav** [comment]
Yes, adding support for `-fpatchable-function-entry` would be the right way to address this. Support for that was introduced in the kernel with the below commit:
https://lore.kernel.org/linuxppc-dev/68586d22981a2c3bb45f27a2b621173d10a7d092.1687166935.git.naveen@kernel.org/

Support for that is being discussed in #57031

**Comment by chenzheng1030** [comment]
https://github.com/llvm/llvm-project/pull/92997 is created for this issue.
