### ISSUE TITLE
flang sometimes fails to compile gfortran test is_iostat_end_eor_1 on AArch64 buildbots

### ISSUE THREAD

**Issue by DavidSpickett** [llvm/llvm-project#63263]
In the following builds, https://github.com/llvm/llvm-test-suite/blob/main/Fortran/gfortran/regression/is_iostat_end_eor_1.f90 fails to compile with this error:
```
error: Semantic errors in /home/tcwg-buildbot/worker/clang-aarch64-sve-vls/test/test-suite/Fortran/gfortran/regression/is_iostat_end_eor_1.f90
/home/tcwg-buildbot/worker/clang-aarch64-sve-vls/test/test-suite/Fortran/gfortran/regression/is_iostat_end_eor_1.f90:7:28: error: No explicit type declared for 'iostat_end'
    if ((.not. is_iostat_end(IOSTAT_END)) .or. is_iostat_end(0)) STOP 1
                             ^^^^^^^^^^
/home/tcwg-buildbot/worker/clang-aarch64-sve-vls/test/test-suite/Fortran/gfortran/regression/is_iostat_end_eor_1.f90:8:28: error: No explicit type declared for 'iostat_eor'
    if ((.not. is_iostat_eor(IOSTAT_EOR)) .or. is_iostat_end(0)) STOP 2
```

Selection of examples:
https://lab.llvm.org/buildbot/#/builders/179/builds/6396
https://lab.llvm.org/buildbot/#/builders/179/builds/6262
https://lab.llvm.org/buildbot/#/builders/179/builds/6231
https://lab.llvm.org/buildbot/#/builders/184/builds/4299
https://lab.llvm.org/buildbot/#/builders/184/builds/4283
https://lab.llvm.org/buildbot/#/builders/197/builds/6532
https://lab.llvm.org/buildbot/#/builders/176/builds/2666

The failure happens intermittently across 1 and 2 stage bots, SVE and non-SVE, vector length agnostic and vector length specific.

In each build there is no obvious change that could have caused it.

**Comment by DavidSpickett** [comment]
@luporl Can you take a look please?

I am new to fortran so most importantly, is this error ever valid? I tried it with gfortran and it was fine: https://godbolt.org/z/bEfj8f8nz

**Comment by luporl** [comment]
The problem is that there is a conflict between these tests:
- is_iostat_end_eor_1.f90
- iso_fortran_env_1.f90

iso_fortran_env_1.f90 defines an iso_fortran_env module, that gets created in the current dir as iso_fortran_env.mod.
is_iostat_end_eor_1.f90 uses iso_fortran_env module, but it expects the standard one.
Thus, if is_iostat_end_eor_1.f90 is built before iso_fortran_env_1.f90, it gets the standard module and builds correctly, otherwise it gets the other test's module, fails to find iostat_end and iostat_eor in it, and the result is the error you reported.

Fortunately, patch https://reviews.llvm.org/D152307 already addresses it. It's already accepted and should land soon.
I've run the test-suite with it and can confirm it fixes this issue, by building each test on a separate dir.

**Comment by DavidSpickett** [comment]
No failures seen since the patch landed.
