### ISSUE TITLE
libc++ basic_string __default_init() is worse than initializing to empty string literal

### ISSUE THREAD

**Issue by Eisenwave** [llvm/llvm-project#63509]
See https://godbolt.org/z/n1We41MKh

I believe the issue lies here:
https://github.com/llvm/llvm-project/blob/10b1f58cba4f7e32134a8e50e97b402f81572a5a/libcxx/include/string#L1691-L1692

Initializing to an empty string literal will only initialize a `__short` representation, whereas the default constructor initializes an entire `__rep`, which requires 24 zero bytes.

```diff
-__r_.first() = __rep();
+__r_.first().__s = __short();
```
Would this solution work, or is there any reason to *always* zero the entire string memory in the default constructor?

**Comment by philnik777** [comment]
`__short` is exactly as large as `__rep` in most cases, so your diff is actually a no-op most of the time. The reason we don't just initialize exactly what is required is that it doesn't actually make a performance difference in most cases and allows the compiler to `memset` instead of generating a much less efficient loop for arrays.
