### ISSUE TITLE
Clang should call `__riscv_flush_icache` for `__builtin___clear_cache` on Linux RISC-V (w/ libgcc?)

### ISSUE THREAD

**Issue by alexrp** [llvm/llvm-project#63551]
Context: https://github.com/dotnet/runtime/pull/88039

TL;DR:

Clang unconditionally emits a call to `__clear_cache` (from libgcc/compiler-rt) for `__builtin___clear_cache`. This is fine in general, but does not work out well when targeting Linux RISC-V w/ libgcc in particular because that function is just empty, leading to all sorts of subtle bugs in JIT-like programs.

That libgcc function is empty because GCC actually emits a call to `__riscv_flush_icache` when targeting Linux RISC-V. Clang should likely do the same, at least when targeting libgcc.

**Comment by asb** [comment]
Ping @kito-cheng - any insight on this from the gcc side very helpful, as that might point towards the best fix.

**Comment by kito-cheng** [comment]
Yes, that should call glibc, since we need some system info to did the cache operations right, like cache line size.
Also cache operations are not mandatory for risc-v, it's added by extension, so that's really need kernel to do that sometimes.

The libgcc's dummy one is used for those systems didn't provide those function especially embedded system.

**Comment by alexrp** [comment]
This seems to be fixed as of https://github.com/llvm/llvm-project/pull/93481, so closing.
