### ISSUE TITLE
How to send pull request notices to a mailing list?

### ISSUE THREAD

**Issue by pogo59** [llvm/llvm-project#63578]
Phabricator allows subscribing llvm-commits, cfe-commits, etc., so that new reviews and comments on existing reviews go to the appropriate mailing list(s). How do we achieve the same effect for pull requests?

**Comment by EugeneZelenko** [comment]
Pull requests have labels like issues, so notifications should work in same way.

**Comment by pogo59** [comment]
My impression was that the labels auto-subscribed the members of the associated list, which is impractical for lists the size of llvm-commits. Maybe I'm wrong about how that works.

Currently, when a new issue gets created, it also gets emailed to llvm-bugs regardless of labels or subscribers. That's more like what we want for PRs, except it should email every update not just when the PR is created.

**Comment by tstellar** [comment]
There is a webhook we have that emails the commit lists every time there is a push event.  It looks like we can set up something similar to email the commits lists on pull request events too. 

The webhook for commit emails is a python script that parses the json payload data from the event, formats it and sends the email off.  If someone wants to take a try at another python script for parsing and formatting pull request events, we can get that installed for the repo.  It doesn't even need the email sending code, because we can copy that from the existing script.

**Comment by tstellar** [comment]
Here is the script I mentioned in my previous comment: https://github.com/llvm/llvm-admin/blob/main/AWS/Lambda/CommitEmailer/commit_emailer.py

**Comment by nikic** [comment]
This has been implemented.
