### ISSUE TITLE
Clang 16.0.0 incorrectly eliminates fetch_or on a atomic that was qualified with volatile

### ISSUE THREAD

**Issue by raphaelsc** [llvm/llvm-project#63692]
Reproducer: https://godbolt.org/z/G93dhsdMa

We can see that GCC 13.1 keeps the lock or, whereas Clang doesn't.

**Comment by nikic** [comment]
"atomicrmw volatile or" is still present in IR, so this is a backend issue.

**Comment by DimitryAndric** [comment]
Godbolt shows that older clang versions also do the same. I went back to clang 10.0.

**Comment by raphaelsc** [comment]
> Godbolt shows that older clang versions also do the same. I went back to clang 10.0.

Yes, I did the same and ruled it out as being a regression.

**Comment by omern1** [comment]
This seems to be done on purpose, `lowerAtomicArith` in X86IselLowering eliminates the `AtomicLoadOr` because the RHS argument is 0 and has no effect on the value being produced. 

Changing the C++ code such that the RHS argument is 1 results in the `atomicrmw or` instruction being preserved: https://godbolt.org/z/ebbojM8zT.

**Comment by raphaelsc** [comment]
> ```
> t4: i8,ch = AtomicLoadOr<(volatile load store monotonic (s8) on %ir.start.04)> t0, t3, Constant:i8<0>
> ```
> 
> This seems to be done on purpose, `lowerAtomicArith()` in `X86IselLowering` eliminates the `AtomicLoadOr` because the RHS argument is 0 resulting in the same value being produced.
> 
> Changing the C++ code such that the RHS argument is 1 results in the `atomicrmw or` instruction being preserved: https://godbolt.org/z/ebbojM8zT.
> 

But that's expected since bitwise OR with a RHS of 1 can change the state of data, therefore it cannot be optimized out. Whereas bitwise OR with a RHS of 0 won't change the data, therefore "dead code", but usage of volatile should have kept it as the author wants to keep it for whatever reasons.

@omern1 It seems to me that the problem in clang is that it's only taking into account the volatile-ness of RHS, but not the volatile-ness of LHS of the expression. If I change the code to make 0 volatile qualified, then clang generate the code.

**Comment by omern1** [comment]
> But that's expected since bitwise OR with a RHS of 1 can change the state of data, therefore it cannot be optimized out. Whereas bitwise OR with a RHS of 0 won't change the data, therefore "dead code", but usage of volatile should have kept it as the author wants to keep it for whatever reasons.

The bug is in LLVM's X86 backend so changing the C++ code in that way causes Clang to produce different IR which sidesteps the issue during legalization in LLVM, but you're correct about the bitwise or with 0 being treated as unnecessary.

I've got a patch up for this here based on my understanding of what the [langref](https://llvm.org/docs/LangRef.html#volatile-memory-accesses) says about volatile memory accesses: https://reviews.llvm.org/D154609.

**Comment by avikivity** [comment]
I see fetch_and, fetch_add, and fetch_xor suffer from the same problem.

**Comment by phoebewang** [comment]
> I see fetch_and, fetch_add, and fetch_xor suffer from the same problem.

I checked all fetch_and, fetch_add, and fetch_xor will generate load instruction.

**Comment by omern1** [comment]
> > I see fetch_and, fetch_add, and fetch_xor suffer from the same problem.
> 
> I checked all fetch_and, fetch_add, and fetch_xor will generate load instruction.

Yup, they're expanded in the `atomic-expand` pass during the middle end which replaces them with equivalent instructions, not an issue.
