### ISSUE TITLE
Function definition goes to .h only and the definition in '.c' is not located until it is manually opened in nvim.

### ISSUE THREAD

**Issue by weiyshay** [llvm/llvm-project#63862]
Hi,
I am using clangd as my LSP in neovim and it seems like that the definition goes to .h only and the definition in '.c' is not located until it is manually opened.

versions:
nvim: 0.8.3
clangd: 16.0.2

I search around and it seems that it's been resolved by replacing the 'compile_flags.txt' with 'compile_commands.json', while
I am still encountering this after that. 

Any idea on how to debug? The 'compile_commands.json' was generated using 'bear make' and seems good.
```  
#wc compile_commands.json
  4144330   4273816 126228837 compile_commands.json
```

Reference post:
https://neovim.discourse.group/t/clangd-lsp-jump-to-definition-takes-me-to-h-file/2153/1

**Comment by sam-mccall** [comment]
It will work if the project gets indexed, the compile_commands.json helps because it lists the files to index.

Clangd logs to stderr, adding `-log=verbose` will add more. That should tell you whether indexing is happening.

(I think neovim writes this output into an lsp.log file, it does wrap it in a bunch of formatting that makes it hard to read though.)

**Comment by weiyshay** [comment]
Hi Sam,
Thanks for your feedback. I read the log and it seems that the project(linux kernel) has been indexed correctly, but 
the symbol '__request_region()' is not jumped before I open the source file. I pasted the lsp log as well.

Before opening 'resource.c':
![image](https://github.com/llvm/llvm-project/assets/99458445/00b8ef39-5b4a-44af-8eb8-180adcdd6018)

After opening 'resource.c', jumping works:
![image](https://github.com/llvm/llvm-project/assets/99458445/9def09a1-0b92-4573-ab44-82c873535798)

Lsp log:
![image](https://github.com/llvm/llvm-project/assets/99458445/f89bea9c-fbb3-42be-be4c-45c9527fb225)

**Comment by sam-mccall** [comment]
Ahh, this is https://github.com/clangd/clangd/issues/1680

`__request_region()` isn't formally a valid name for use in user code, it's reserved for the implementation.
Such symbols aren't indexed because they're usually implementation details of the standard library etc.

But some projects use them anyway, and I think we'll add an option to allow them to be indexed.
(Going to close this one as it's tracked elsewhere)

**Comment by weiyshay** [comment]
Great to know & thank your very much!
