### ISSUE TITLE
C++ LLDB API: lldb::SBThread StepInstruction() stuck on "__kernel_clock_gettime" function

### ISSUE THREAD

**Issue by aadityasinha10** [llvm/llvm-project#63923]
I have written C++ LLDB API code in which I am attaching LLDB debugger to a remote Android camera HAL process and I am stepping through at the instruction level after a breakpoint is hit. I am printing the name of the function at the current frame each time I step through at the instruction level.

LLDB steps through the instructions fine until it reaches the function `__kernel_clock_gettime` where it seems to be getting stuck in some sort of a loop and stops making further progress. I checked until 100,000 iterations of the `StepInstruction()` function. The HAL process works fine without the debugger attached, so I'm not sure what could be causing this to happen. Does anyone have any idea why this could be happening? Any help with this would be greatly appreciated. Thank you.

In the below screenshots, the number before the `#` represents the iteration number of the `StepInstruction()` function:
<img width="917" alt="lldb_screenshot_1" src="https://github.com/llvm/llvm-project/assets/58428456/e6b7949d-8fd1-4ec7-b951-7c5a99b91e4a">

<img width="923" alt="lldb_screenshot_2" src="https://github.com/llvm/llvm-project/assets/58428456/670ab9ce-ea94-4ea9-8185-3c4d8fa90f88">

**Comment by jimingham** [comment]
Most CPU architectures have some instructions (usually involving some kind of atomicity) that can't be executed if the processor is in "single-step mode".  If the system reaction to being asked to do this is to do nothing - which seems to be a common response - then you will get stuck there.  The solution is to put a breakpoint on the next instruction & continue (*).  x86_64 also has "repeat" prefixes" that make stepping over one instruction take as many stepi-s as the repeat count.

Anyway, if you show us what instructions you were stepping over we might be able to say more.

Jim

(*) lldb could be taught to be aware of these instructions and handle stepping over them.  Doing that hasn't risen to the top of anybody's queue yet because those instructions mostly show up in lower-level code that people tend not to step through (and certainly not stepi through).

Jim

**Comment by aadityasinha10** [comment]
Thank you for your help.
