### ISSUE TITLE
[clang] Missing checksums in DWARF information

### ISSUE THREAD

**Issue by omern1** [llvm/llvm-project#63955]
### Header file:
```c
// file.h
int init() {
  return 44;
}
int g = init();
```
### Source file:
```c
// file.cpp
// clang -g -c -gdwarf-5 -xc++ file.cpp
#include "file.h"
#include <limits.h>
```

### Steps to reproduce:
- Compile the files above with the specified options.
- `llvm-dwarfdump -debug-line file.o`

The dwarfdump output will show that there are no MD5 checksums in the DWARF data which should be present.

**Comment by pogo59** [comment]
Minimal reproducer:
```
int init() {
  return 44;
}
int g = init();
```
The IR has two DIFile records, one for the compile-unit and one attached to the DISubprogram for the artificial initialization function that will end up initializing `g`. The DIFile attached to the compile-unit has an MD5 checksum, the one attached to the DISubprogram does not.

In DWARF v5, all files have the same characteristics. If any file in the file list does not have an MD5 checksum, we don't emit any checksums. v5 doesn't have a way to signal that a particular file does not have a checksum.

The bug is that the second DIFile record doesn't have a checksum on it. This is a Clang codegen/debug-info problem.

**Comment by pogo59** [comment]
It looks like the artificial initialization function is created with a default-constructed SourceLocation, which isn't a terrible idea. It's an artificial function, after all.
This invalid location ends up being passed to CGDebugInfo::getOrCreateFile(), which is willing to use the CU's main filename if the Loc is invalid. (This filename is retrieved from the DICompileUnit.) The next step is to do a lookup in DIFileCache with the filename. A lookup using the CU's filename fails, when a filename from the SourceLocation succeeds. Even though they look like exactly the same filename. More on this below.

If the lookup fails, then getOrCreateFile goes on to compute a checksum. However, the path through the code for an invalid SourceLocation doesn't try to come up with a FileID, and without a valid FileID, the checksumming fails. Hence, we get a new DIFile with no checksum.

Q1. Why does the DIFileCache lookup fail? If that worked, we'd find the existing DIFile and not have this duplicate hanging around.

A1. Because it's a `DenseMap<const char *, TrackingMDRef>` meaning the key is a _pointer_ not a _string_. Apparently SourceLocation uses the same actual string for all the locations in a given file (which is nice), but this pool (managed by Clang) is quite reasonably not shared with the debug info metadata (managed by LLVM). The latter is where we get the (pointer to the) filename when the original SourceLocation is invalid. Because the pointer is different, the cache lookup fails, and getOrCreateFile quite reasonably assumes it needs to create a new DIFile.

Q2. Why is there no FileID? If we had that, we'd compute the right checksum even without a DIFileCache hit.

A2. The FileID type is closely integrated with Clang's source management. There is no straightforward way to turn an arbitrary character string (such as the filename saved in the debug info metadata for the CU) into a FileID, so far as I can tell. Granted I'm not at all familiar with this area and spent only an hour or so looking.

Q3. So what do we do?

A3. The obvious choice is to change DIFileCache into a StringMap. Then the lookup would be based on the string content, not the string address, and the lookup should succeed even if it's using a filename managed by LLVM instead of Clang. The downside is that StringMap will make yet another copy of the filename, but in practice it shouldn't be a huge gob of memory for that.

If nobody else comes up with a better idea, I might take a crack at it.
