### ISSUE TITLE
[DebugInfo] Missing (unused) types with -fstandalone-debug

### ISSUE THREAD

**Issue by jmorse** [llvm/llvm-project#63999]
Consider this program:

    struct Type
    {
        enum { Unused };
        int value = 0;
    };
    int main()
    {
        Type t;
        return t.value;
    }

The enumeration type isn't used anywhere and clang doesn't allocate any storage for it -- which is fine. However, the name "Unused" is still technically a name in the type that could be addressed by some other piece of C++.

In DWARF however, we don't describe that name at all. Using `-O2 -g -c -fstandalone-debug` doesn't produce a DW_TAG_enumeration_type inside the type Type. This is a slight surprise to me: I was under the impression that -fstandalone-debug is supposed to emit all the debug-info that can be emitted, regardless of optimisations or space-saving reductions, as if there was going to be no other DWARF produced for the final program. Do other people have similar expectations, i.e., even though "Unused" is optimised out of struct Type completely, we should still describe it as a name in the type with -fstandalone-debug?

Implementing this feels tricky though. I see in `CGDebugInfo::CreateTypeDefinition` that we would normally collect the enum data into the DICompositeType via CollectRecordFields, however because the enum doesn't have a field it doesn't get an element in the DICompositeType. As far as I understand it, DICompositeType doesn't have a field for "names that are in this type but not used by anything".

**Comment by dwblaikie** [comment]
Working as intended. If you want unused types you're looking for `-fno-eliminate-unused-debug-types` ( https://reviews.llvm.org/D80242 )

**Comment by dwblaikie** [comment]
`-fstandalone-debug` is, yes, "compile this as if no other part of the program is compiled with debug info" (ie: remove all homing strategies) - but with or without `-fstandalone-debug`, we still don't emit totally unused types - the goal in either mode is to emit all referenced types. So you can print out the members in some variable of a certain type, you can cast to a pointer if the program casts to that pointer type, etc.

If you need unreferenced debug info, because that's just so massive (like every object that includes <string> gets a copy of the debug info for std::string, just by the inclusion, without even having a string variable... ) it's not even been on the radar until recently - because the kernel folks want to do some ABI analysis on types, even when they're otherwise unreferenced. So that's how we got that flag.

**Comment by jmorse** [comment]
Cool, thanks for the tip -- that all makes a lot of sense.

**Comment by pogo59** [comment]
AFAICT `-fno-eliminate-unused-debug-types` doesn't apply to enums?

**Comment by dwblaikie** [comment]
> AFAICT -fno-eliminate-unused-debug-types doesn't apply to enums?

I'd be fine classifying that as a bug.

**Comment by pogo59** [comment]
Filed #64160 for that bug.
