### ISSUE TITLE
Incorrect Values or Device Errors when Using Zero-Copy with CUDA cuSparse Runtime Libraries

### ISSUE THREAD

**Issue by K-Wu** [llvm/llvm-project#64316]
zero-copy triggers device error or causes error results in some of the rows/columns
reproducer: RUNNOT: statements in the .mlir files in the revision D155352
Related revision: https://reviews.llvm.org/D155352

**Comment by Artem-B** [comment]
We could use some additional details here.

If the issue is specific to cuSparse (e.g. other calls that use zero-copy work), then it's NVIDIA's problem.
If the issue is specific to zero-copy implementation in MLIR, then it's an MLIR issue and, may potantially be narrowed down to NVPTX back-end issue in LLVM, if it turns out the problem is in MLIR-generated GPU code.
If it involves CUDA source compilation, then it would be a CUDA issue.

**Comment by aartbik** [comment]
Yeah, this got tabled for a while. But planning to look into this soon now.

**Comment by aartbik** [comment]
This is "fixed" by removing the code ;-)
But we plan to reintroduce zero-cost copies back soon in a new format.
