### ISSUE TITLE
Backport 60b98363c7ed0a549be4d51ee07c32dc2bf47d2f to LLVM 17

### ISSUE THREAD

**Issue by statham-arm** [llvm/llvm-project#64412]
Commit 60b98363c7ed0a549be4d51ee07c32dc2bf47d2f hardens switch jump tables against being used as JOP gadgets, in the presence of branch target enforcement using Arm BTI or similar systems.

**Comment by smithp35** [comment]
From https://reviews.llvm.org/D155485 we (Arm) would like to get this into LLVM 17 so that we can recommend that developers for the forthcoming cortex-m85 which is the first 32-bit CPU to have BTI, use LLVM 17. The specific change is safe, in that it just prevents the compiler from optimising out a switch statement.
