### ISSUE TITLE
[LLD] Evaluation of DEFINED linker script directive produces wrong output

### ISSUE THREAD

**Issue by edward-jones** [llvm/llvm-project#64600]
The following linker script causes unexpected behaviour when `APPLE` is not defined by any input objects. The unexpected output is that `APPLE` will resolve to '1' instead of '2'.

```
APPLE = DEFINED (APPLE) ? 1 : 2;
```

It appears that when the symbol is first processed it is added to the symbol table with the expected value, however LLD reevaluates symbol assignments, and during these subsequent evaluations of the expression the `DEFINED` now returns 1 as `APPLE` has been inserted in the symbol table.

**Comment by finchky** [comment]
I have run into a similar issue. I think it has to do with when the symbol being set is the same symbol being checked by DEFINED. 

Building off the original example when `APPLE` is not defined:

Scenario 1: 
`APPLE = DEFINED (APPLE) ? APPLE : 2;`
This evaluates to 0 instead of 2

Scenario 2:
`ORANGE = DEFINED (APPLE) ? APPLE : 2;`
This correctly evaluates to 2

**Comment by MaskRay** [comment]
Created #65866
