### ISSUE TITLE
[mlir][spirv] Inconsistent error message when building `BitFieldMessage` op.

### ISSUE THREAD

**Issue by Colloportus0** [llvm/llvm-project#64765]
```console
src.mlir:2:3: error: 'spirv.BitFieldInsert' op operand #1 must be 8/16/32/64-bit integer or vector of 8/16/32/64-bit integer values of length 2/3/4/8/16, but got 'vector<2xi1>'
  toy.gen
  ^
src.mlir:2:3: note: see current operation: %238 = "spirv.BitFieldInsert"(%81, %192, %80, %80) : (vector<2xi32>, vector<2xi1>, i32, i32) -> vector<2xi1>
```

The above error message is inconsistent with the doc: 
```
     The type of Base and Insert must be the same as Result Type.
```
If I have understood correctly, the error message should be like:
```
 op operand #1 must be the same type as #2
```

**Comment by kuhar** [comment]
Hi @Colloportus0,

I looked at how we implement the verification for `spirv.BitFieldInsert` and it's based on ODS. We put constraints on operand and return types and then check the extra trait that `AllTypesMatch`.

Because `BitFieldInsert` requires integers or vectors of integers, while `i1` is not considered an integer type in SPIR-V (https://registry.khronos.org/SPIR-V/specs/1.2/SPIRV.html#OpTypeBool), the current error message seems correct to me.

I will go ahead and close this issue.

**Comment by Colloportus0** [comment]
> [mlir][spirv] Fix description formatting in BitOps. NFC.

thanks for your explanation, now I understand :-)
