### ISSUE TITLE
Accept /branch: and /cherry-pick: commands

### ISSUE THREAD

**Issue by tbaederr** [llvm/llvm-project#64803]
This is implemented in `llvm/utils/git/github-automation.py`.

People can't write `/cherry-pick: foobar`, because the colon breaks the script. The same is true for `/branch`.

**Comment by PranavReddyP16** [comment]
Hey, I'm new to llvm and fairly competent with python. I'd love to take this up. I think I see the issue in the file mentioned. What is the expected behaviour here exactly? Currently, I see that the implemented regex does not support having colons in the command, only lowercase letters and hyphens. Are colons the only thing we are looking to support or is there anything else?

**Comment by tbaederr** [comment]
Only colons is fine for now.

**Comment by Shanchax** [comment]
Hi , is the issue still open. I am fairly new to LLVM, but decently proficent in Python and would like to try to resolve this issue. Can this issue be assigned to me please? Thanks.

**Comment by Sh0g0-1758** [comment]
Hello, I looked at the issue and I believe I can solve it. Can you please assign me the issue, @tbaederr.

**Comment by Sh0g0-1758** [comment]
@tstellar @tbaederr, I have updated the code for two issues that I have been working on. I have tried my level best to solve them. Please do suggest changes in it. Also I have checked the regex expression with and without colon. It is working fine.

**Comment by Sh0g0-1758** [comment]
![Screenshot from 2024-01-21 16-55-32](https://github.com/llvm/llvm-project/assets/114918019/9dd32836-b013-4ef9-a3ac-00bb5b0435f4)
I hope this is the required changes. I will raise a PR for the same once approved. I changed the regex to take account for `:` now.

**Comment by Sh0g0-1758** [comment]
@tbaederr, I have created a PR for this issue. Please review it.
