### ISSUE TITLE
Assertion failed: (isRepresentableByInt64() && "Too many bits for int64_t"), function getExtValue, file APSInt.h, line 99.

### ISSUE THREAD

**Issue by dcci** [llvm/llvm-project#64876]
```
% cat red.cpp 
#include <string>
int a { strncmp(0, 0, -511LL) }
```

```
 % xcrun ./clang red.cpp 
Assertion failed: (isRepresentableByInt64() && "Too many bits for int64_t"), function getExtValue, file APSInt.h, line 99.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
```

**Comment by dcci** [comment]
cc: @Teemperor

**Comment by dcci** [comment]
Slightly better example that compiles:

```
#include <string.h>
void patatino() { strncmp(0, 0, -511LL); }
```

**Comment by EugeneZelenko** [comment]
Slightly modified reproducer (proper header): https://godbolt.org/z/M14z83r8o

**Comment by shafik** [comment]
It look like this was implemented via e151bab2fcecb

@zygoloid  I am wondering why use `N.getExtValue()` as opposed to `N.getZExtValue()` which would avoid this particular case but not the case where the number of bits is > 64.

https://github.com/llvm/llvm-project/blob/86ed8cb8fabe7716b9046317231f861fee5f126a/clang/lib/AST/ExprConstant.cpp#L12384

It looks like the fix is to add a diagnostic checking the number of active bits, it looks like we might need this in some other places as well.

**Comment by rjmccall** [comment]
The size parameter of the sized comparison routines is always a `size_t`, so the argument expression will have been converted to that.  If the target's `size_t` is a 64-bit type, then since it's always unsigned, there will be argument values that can't be expressed as an `int64_t` and therefore will trigger this assertion.  So yes, we should get this value with `getZExtValue()` instead, if we're okay with making an unportable assumption about the max size of the target's `size_t` (which this is far from the only instance of).  I'm sure this is just an oversight.

**Comment by shafik** [comment]
There are a bunch of other cases we should cover as well when we land a fix:

```cpp
void f() {
  __builtin_strncmp(0, 0, -511LL); 
  __builtin_memcmp(0, 0, -511LL); 
  __builtin_bcmp(0, 0, -511LL); 
  __builtin_wmemcmp(0, 0, -511LL);
  __builtin_memchr((const void*)0, 1, -511LL);
  __builtin_wmemchr((const wchar_t*)0, 1, -511LL);
}
```

**Comment by zygoloid** [comment]
This was broken by 0a89825a289d149195be390003424adad026067f; this code was relying on `getExtValue` producing the actual value if it fits in 64 bits regardless of signedness, as it used to prior to that change.

Changing to `getZExtValue` seems fine to me.
