### ISSUE TITLE
LLVM build errors in Ubuntu 14.04 

### ISSUE THREAD

**Issue by lipeng28** [llvm/llvm-project#64943]
Hi There

I applied the following command to build llvm-project-16.0.0:
cmake -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles" ../llvm && make 
and I encountered the following errors, do you have any idea on why this happened?

/home/xx/Clang/llvm-project-16.0.0.src/llvm/lib/Support/BLAKE3/blake3_avx512_x86-64_unix.S:2242: Error: operand type mismatch for `vpxord'

/home/xx/Clang/llvm-project-16.0.0.src/llvm/lib/Support/BLAKE3/blake3_avx512_x86-64_unix.S:2243: Error: operand type mismatch for `vprord'
...

The environment I relied on is:
Ubuntu 14.04 X86_64
GCC version 9.4 
cmake version 3.27.3

Thanks
Peng

**Comment by DimitryAndric** [comment]
You seem to have a strange system, as Ubuntu 14.04 is very old, but gcc 9.4 is a bit more recent? Ubuntu 20.04 comes with gcc 9.4, but not with cmake 3.27.3, so I would have to guess that you manually installed these toolchain components?

In any case, the problem seems to be your assembler, which does not accept the blake3 assembly files. Do you have any idea which assembler is being used?

**Comment by lipeng28** [comment]
Yes, I manually installed gcc 9.4, and cmake 3.27.3. Since llvm-projects compilation requires gcc >= 7 version

**Comment by lipeng28** [comment]
GNU assembler (GNU Binutils for Ubuntu) 2.24

**Comment by DimitryAndric** [comment]
This was fixed in 2014 with https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=b28d1bda54728d10ae189a323c343b6d76f94b8e so after binutils 2.24. You should upgrade to a newer binutils.

That said, is there any particular reason you are using a very old Linux distribution for your builds? If you do, you are very likely to run into lots of issues, since most llvm maintainers use more up-to-date distributions.

**Comment by lipeng28** [comment]
Thanks Dimitry, ubuntu 20.04 should be a better choice.
