### ISSUE TITLE
different symbol versioning behaviour between LLD and GNU bfd ld

### ISSUE THREAD

**Issue by kraj** [llvm/llvm-project#65017]
I am having an issue where lld does not accept a symbol like `xvz@@` in objects, it errors out

```
ld.lld: error: sv_lib_v2.o: symbol xyz@@ has undefined version
```

whereas GNU linker is happy to accept a symbol like that.

Second issue I also see is that behaviour is different if I remove the above symbol. It links the attachedf test fine though
but runtime behaviour is different.

```
% ./a.sh
Using LLD
v2 xyz
Usng BFD LD
v2 xyz
```
[test.zip](https://github.com/llvm/llvm-project/files/12447193/test.zip)

**Comment by kraj** [comment]
@MaskRay you have done some work on this diagnostic in lld  via https://reviews.llvm.org/D92260

**Comment by MaskRay** [comment]
Thank you for the reproduce. It's useful.

> I am having an issue where lld does not accept a symbol like xvz@@ in objects, it errors out

I think an empty version name is an intended use case. GNU ld may do something with it, but we should not rely on the behavior.

> Second issue I also see is that behaviour is different if I remove the above symbol. It links the attachedf test fine though but runtime behaviour is different.

This difference is related to whether the linker picks `xyz` (lld) or `xyz@@VER_2` (GNU ld) as the definition.

```
% readelf -W --dyn-syms libsv.so | grep xyz
     7: 0000000000001759    22 FUNC    GLOBAL DEFAULT   13 xyz@VER_1
     8: 000000000000176f    22 FUNC    GLOBAL DEFAULT   13 xyz@@VER_2
     9: 0000000000001785    22 FUNC    GLOBAL DEFAULT   13 xyz
```

When an object defines a default version symbol `xyz@@VER_2`, an unversioned `xyz` should not appear in the symbol table.
If it occurs, I think glibc's rtld behavior will be dependent on the order of the two symbols, which is brittle.

`libsv.so` has `xyz` just because `__asm__(".symver xyz_new_nover,xyz@");`

I consider `__asm__(".symver xyz_new_nover,xyz@");` an "undefined behavior".
Perhaps future Clang can report warnings on the case or even reject the use cases.
