### ISSUE TITLE
[flang] [hlfir] execution time comparison between with/without -flang-experimental-hlfir

### ISSUE THREAD

**Issue by k-arrows** [llvm/llvm-project#65038]
Consider the following code:
(only "explicit DO loops" part from https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52473#c10)
```console
$ cat testme.f90
module kinds
  integer, parameter :: sp = selected_real_kind(6) ! Single precision
  integer, parameter :: dp = selected_real_kind(15) ! Double precision
end module kinds

module replacements
  use kinds
contains
  subroutine cshift_sp_3_v1 (array, shift, dim, res)
    integer, parameter :: wp = sp
    real(kind=wp), dimension(:,:,:), intent(in), contiguous :: array
    integer, intent(in) :: shift, dim
    real(kind=wp), dimension(:,:,:), intent(out), contiguous :: res
    integer :: i,j,k
    integer :: sh, rsh
    integer :: n
    res = 0
    if (dim == 1) then
       n = size(array,1)
       sh = modulo(shift, n)
       rsh = n - sh
       do k=1, size(array,3)
          do j=1, size(array,2)
             do i=1, rsh
                res(i,j,k) = array(i+sh,j,k)
             end do
             do i=rsh+1,n
                res(i,j,k) = array(i-rsh,j,k)
             end do
          end do
       end do
    else if (dim == 2) then
       n = size(array,2)
       sh = modulo(shift,n)
       rsh = n - sh
       do k=1, size(array,3)
          do j=1, rsh
             do i=1, size(array,1)
                res(i,j,k) = array(i,j+sh, k)
             end do
          end do
          do j=rsh+1, n
             do i=1, size(array,1)
                res(i,j,k) = array(i,j-rsh, k)
             end do
          end do
       end do
    else if (dim == 3) then
       n = size(array,3)
       sh = modulo(shift, n)
       rsh = n - sh
       do k=1, rsh
          do j=1, size(array,2)
             do i=1, size(array,1)
                res(i,j,k) = array(i, j, k+sh)
             end do
          end do
       end do
       do k=rsh+1, n
          do j=1, size(array,2)
             do i=1, size(array,1)
                res(i,j, k) = array(i, j, k-rsh)
             end do
          end do
       end do
    else
       stop "Wrong argument to dim"
    end if
  end subroutine cshift_sp_3_v1
end module replacements

program testme
  use kinds
  use replacements
  implicit none
  integer, parameter :: wp = sp  ! Working precision
  INTEGER, PARAMETER :: n = 200
  real(kind=wp) :: a(n,n,n), b(n,n,n)
  integer i, j, k
  real t1, t2

  print *,"Testing explicit DO loops"
  call random_number(a)
  do k = 1,3
     call cpu_time ( t1 )
     do j = 1, 100
        call cshift_sp_3_v1 (a, 1, k, b)
     end do
     call cpu_time ( t2 )
     write ( *, * ) 'Dim = ', k, ' Elapsed CPU time = ', t2-t1
  end do

end program testme
```

Result (on my WSL2, with flang-new which I recently built)
```console
$ flang-new -Ofast testme.f90
$ ./a.out
 Testing explicit DO loops
 Dim =  1  Elapsed CPU time =  .5384389
 Dim =  2  Elapsed CPU time =  .5455937
 Dim =  3  Elapsed CPU time =  .51351356
$ flang-new -Ofast -flang-experimental-hlfir testme.f90
$ ./a.out
 Testing explicit DO loops
 Dim =  1  Elapsed CPU time =  7.887358
 Dim =  2  Elapsed CPU time =  7.938386
 Dim =  3  Elapsed CPU time =  7.9478416
```

I would like to know what methods can be taken to understand the reasons for these kinds of performance differences.

**Comment by tblah** [comment]
The method I used to understand this was to manually compare the FIR generated via HLFIR vs that generated via FIR. These can be generated with `bbc -emit-fir -hlfir testme.f90` and `bbc -emit-fir testme.f90`. I pass the result through `fir-opt --CSE --canonicalize` to make the IR easier to read.

Looking at the generated IR I see a few differences
- HLFIR uses the assign runtime function for `res = 0`, whereas FIR uses a loop nest (unlikely to be the culprit as it is outside of the loops)
- HLFIR uses fir.array_coor to access array elements via Fortran indices, whereas FIR uses fir.coordinate_of via 0-based indices. This shouldn't affect performance because fir.array_coor is eventually lowered to roughly the same generated code, but it does lead to a lot of churn in the IR
- FIR casts access to `res` inside the innermost loops to a 1D array. HLFIR does not do this, continuing with 3D indexing. I wonder if this could lead to the LLVM vectoriser assuming the HLFIR array accesses are not sequential. Significant performance improvements were seen in SPEC2017 after the introduction of the FIR loop versioning pass, which does roughly the same thing (although later on in compilation, so I don't think that pass is the culprit here). If I had to guess, this is the source of the performance problem, but I haven't confirmed it.

Would you like to work on this or should I pick it up?

**Comment by k-arrows** [comment]
Thank you for your comments.

I'd like to leave it up to you or the community to find the cause of this performance difference. But when I encounter similar situations in the future, I want to be able to make some suggestions and investigate this kind of performance difference. I won't go into details, but I work in the HPC industry and believe that when Flang becomes popular, there will certainly be situations like that (i.e., some kind of performance study).

At the moment I don't think I have enough basic skills for this kind of problem. For now, I'll start by using `bbc` or `fir-opt`. (Maybe I should start with a smaller program.)

**Comment by tblah** [comment]
In the long run, I expect the lowering directly to FIR (not via HLFIR) will go away some time after HLFIR is enabled by default. That would make the "why is this slow" question a bit harder because you wouldn't have a similar "right" answer to compare against.

But the principals are the same. You would look at the MLIR at different stages of compilation to see if anything looks wrong (for example creating unnecessary array temporaries).

It can help to look at different points through the processing of the MLIR, and having a good grasp of what each operation means. FIR is documented here https://flang.llvm.org/docs/FIRLangRef.html. HLFIR doesn't have pretty HTML documentation currently, but you can see the source of the same information here https://github.com/llvm/llvm-project/blob/main/flang/include/flang/Optimizer/HLFIR/HLFIROps.td and some design documentation (slightly out of date) here https://github.com/llvm/llvm-project/blob/main/flang/docs/HighLevelFIR.md.

To get HLFIR immediately after lowering from the parse tree, use `bbc -emit-hlfir file.f90`. You can use `fir-opt` to run passes to see how those transform the IR (the pass pipeline(s) run by flang-new are maintained here https://github.com/llvm/llvm-project/blob/main/flang/include/flang/Tools/CLOptions.inc#L234). `bbc -emit-fir -hlfir` jumps straight to the FIR you get after the passes that convert HLFIR into FIR.

It can sometimes also be useful to look at the generated LLVM IR generated at the very end of the flang pipeline. This can be done with `flang-new` or `tco`.

**Comment by k-arrows** [comment]
I tried again using the flang-new I built last night and the difference in performance has gone:
```console
$ flang-new -Ofast testme.f90
$ ./a.out
 Testing explicit DO loops
 Dim =  1  Elapsed CPU time =  .5564932
 Dim =  2  Elapsed CPU time =  .54389166
 Dim =  3  Elapsed CPU time =  .5151148
$ flang-new -Ofast -flang-experimental-hlfir testme.f90
$ ./a.out
 Testing explicit DO loops
 Dim =  1  Elapsed CPU time =  .5342459
 Dim =  2  Elapsed CPU time =  .5395036
 Dim =  3  Elapsed CPU time =  .5032953
```

I also don't see any difference in the vectorization of the loop:
```console
$ flang-new -Ofast -Rpass testme.f90 2> fir.txt
$ cat fir.txt | grep "vectorized"
tmp/testme.f90:54:14: remark: vectorized loop (vectorization width: 4, interleaved count: 2) [-Rpass=loop-vectorize]
tmp/testme.f90:61:14: remark: vectorized loop (vectorization width: 4, interleaved count: 2) [-Rpass=loop-vectorize]
tmp/testme.f90:43:14: remark: vectorized loop (vectorization width: 4, interleaved count: 2) [-Rpass=loop-vectorize]
tmp/testme.f90:38:14: remark: vectorized loop (vectorization width: 4, interleaved count: 2) [-Rpass=loop-vectorize]
tmp/testme.f90:27:14: remark: vectorized loop (vectorization width: 4, interleaved count: 2) [-Rpass=loop-vectorize]
tmp/testme.f90:24:14: remark: vectorized loop (vectorization width: 4, interleaved count: 2) [-Rpass=loop-vectorize]
tmp/testme.f90:27:14: remark: vectorized loop (vectorization width: 4, interleaved count: 2) [-Rpass=loop-vectorize]
$ flang-new -Ofast -flang-experimental-hlfir -Rpass testme.f90 2> hlfir.txt
$ cat hlfir.txt | grep "vectorized"
tmp/testme.f90:54:14: remark: vectorized loop (vectorization width: 4, interleaved count: 2) [-Rpass=loop-vectorize]
tmp/testme.f90:61:14: remark: vectorized loop (vectorization width: 4, interleaved count: 2) [-Rpass=loop-vectorize]
tmp/testme.f90:43:14: remark: vectorized loop (vectorization width: 4, interleaved count: 2) [-Rpass=loop-vectorize]
tmp/testme.f90:38:14: remark: vectorized loop (vectorization width: 4, interleaved count: 2) [-Rpass=loop-vectorize]
tmp/testme.f90:27:14: remark: vectorized loop (vectorization width: 4, interleaved count: 2) [-Rpass=loop-vectorize]
tmp/testme.f90:24:14: remark: vectorized loop (vectorization width: 4, interleaved count: 2) [-Rpass=loop-vectorize]
tmp/testme.f90:27:14: remark: vectorized loop (vectorization width: 4, interleaved count: 2) [-Rpass=loop-vectorize]
```

I will close this issue. I would like to thank @tblah for many suggestions.

**Comment by tblah** [comment]
It looks to me like the change was because the `hlfir.assign` is now converted to a loop nest (as in the FIR lowering). It is surprising to me that the assign runtime was so slow before. The HLFIR body of the working loops still uses 3D indexing, while FIR does 1D indexing.

I suspect the change is from @vzakhari's work: https://reviews.llvm.org/rGe60dc8ed7eec4287f0db85e52d45e27bd4c8bbde
