### ISSUE TITLE
[Clang][OpenMP] Compilation Aborted (core dumped)

### ISSUE THREAD

**Issue by ajarmusch** [llvm/llvm-project#65155]
Getting an Aborted (core dumped) from compiling with clang. You can reproduce the core dump with the attached reduced.ll file using ```opt -p globalopt reduced.ll```

reduced.ll:
```
; ModuleID = 'reduced.bc'
target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8"
target triple = "amdgcn-amd-amdhsa"

@x = internal global i32 poison

; Function Attrs: norecurse
define amdgpu_kernel void @__omp_offloading_10306_92b48f5_test_uses_allocators_large_cap_l31(i32 %0) #0 {
entry:
  store i32 %0, ptr @x, align 4
  ret void
}

attributes #0 = { norecurse }
```

**Comment by jdoerfert** [comment]
The code is semi-valid, we should not crash. The reason is that we replace the AS(0) global with one in AS(5), due to the data layout. This is a good beginner issue as one "simply" needs to add a AS cast before the RAUW operation in processGlobal (globalsopt pass).

That all said, we need to find out when the AS(0) global was added in the first place and fix that as well.

**Comment by arsenm** [comment]
One does not simply introduce new addrspacecasts without target knowledge
