### ISSUE TITLE
static compound literal

### ISSUE THREAD

**Issue by alejandro-colomar** [llvm/llvm-project#65190]
Hi,

I was experimenting to see if I could change the lifetime of a compound literal used within a function definition, to make it have static storage duration, instead of automatic.

I'm not sure if ISO C allows this, but it seems GCC does, experimentally.

```c
$ cat foo.c 
#include <string.h>
#include <stdio.h>

char *foo(void);

char *foo(void)
{
	return (static char []){"foo"};
}

int main(void)
{
	puts(memset(foo(), 'g', 2));
}
```
```sh
$ gcc-13 -Wall -Wextra foo.c 
$ ./a.out
ggo
```
```c
$ clang-16 -Weverything foo.c 
foo.c:8:10: error: expected expression
        return (static char []){"foo"};
                ^
1 error generated.
```

But Clang complains about it.  Would you mind supporting this syntax?

**Comment by shafik** [comment]
Looking at 6.5.2.5 Compound literals, it says:

> The value of the compound literal is that of an unnamed object initialized by the initializer list. If
the compound literal occurs outside the body of a function, the object has static storage duration;
otherwise, it has automatic storage duration associated with the enclosing block.

That seems to say this is not allowed.

CC @AaronBallman

**Comment by AaronBallman** [comment]
This is a C23 feature: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3038.htm and we don't yet implement it (https://clang.llvm.org/c_status.html). It's on the list of things we need to do to complete C23 support, but it will be a while before we get to it because I think it's going to require a fairly significant refactoring of our existing compound literal support in C.

So yes, this is allowed by ISO C in C23 and later.

I'm going to close the issue given that we already track the status of the implementation on the c_status page.
