### ISSUE TITLE
Clang 16 - Serie of std::vector::push_back(U8) poorly generated code

### ISSUE THREAD

**Issue by Scr3amer** [llvm/llvm-project#65607]
Hello everyone,

I was playing around with Godbolt and noticed some weird behaviour of clang++ (g++ seems cleaner)

An example is better than a thousand word so just compare the output of -O3 and no optimisation:

https://godbolt.org/z/Y3qeYx5xd

I just feel O3 could be way cleaner than that. **It actually happens also with O1 and O2.**
I dont get why we see the same values repeated over and over again like : 9223372036854775807

PS: I am nowhere close to be a compiler programmer so I don't even know how to help you with it or if it is normal behaviour of the compiler. Just wanted to notify and see what you guys think.

Cheers,
Scr3am

**Comment by fhahn** [comment]
The reason the the unoptimized build looks 'cleaner' is because it doesn't inline the `push_back` logic and just calls the functions. Godbolt hides library functions by default, so it doesn't show the code for the non-inlined functions. If you adjust the filter, you can see that without optimizations, much more code is generated: https://godbolt.org/z/b6a11TTvr

AFAICT things are working as expected, so I am going to close the issue for now.
