### ISSUE TITLE
[clang] Issues with determining valid constant expressions in `cxx2b`

### ISSUE THREAD

**Issue by antoniofrighetto** [llvm/llvm-project#66262]
C++23 permits a variable of non-literal type to be defined in a constant expression scope, but clang seems to have a hard time handling it. The following code does not compile with `-std=cxx2b` on latest clang:
```cpp
struct A { int y; };
struct B : virtual public A {};
struct X : public B {};

constexpr void foo() {
  X x;
  x.B::y = 1;
}
```
Godbolt: https://godbolt.org/z/rTdaf545e.

**Comment by cor3ntin** [comment]
I tentatively believe Clang to be correct (diagnostic could be improved though)

- A is an aggregate
- B isn't an aggregate and has a defaulted destructor that cannot be constexpr because it has a virtual base
- X has also a constructor that cannot be constexpr
- The allowances for non-literal types still requires constexpr constructors https://eel.is/c++draft/expr.const#2.2

Ditto for destructor

https://eel.is/c++draft/dcl.constexpr#3

> A function is [constexpr-suitable](https://eel.is/c++draft/dcl.constexpr#def:constexpr-suitable)  if the function is a constructor or destructor, its class does not have any virtual base classes[.](https://eel.is/c++draft/dcl.constexpr#3.sentence-1)

https://eel.is/c++draft/dcl.fct.def.default

> An implicitly-defined ([[dcl.fct.def.default]](https://eel.is/c++draft/dcl.fct.def.default)) default constructor performs the set of initializations of the class that would be performed by a user-written default constructor for that class with no [ctor-initializer](https://eel.is/c++draft/class.base.init#nt:ctor-initializer) ([[class.base.init]](https://eel.is/c++draft/class.base.init)) and an empty [compound-statement](https://eel.is/c++draft/stmt.block#nt:compound-statement)(https://eel.is/c++draft/class.ctor#class.default.ctor-4.sentence-2) If that user-written default constructor would be constexpr-suitable ([[dcl.constexpr]](https://eel.is/c++draft/dcl.constexpr)), the implicitly-defined default constructor is constexpr[.](https://eel.is/c++draft/class.ctor#class.default.ctor-4.sentence-3)


https://eel.is/c++draft/expr.const#5.3

> An expression E is a [core constant expression](https://eel.is/c++draft/expr.const#def:expression,core_constant) unless the evaluation of E, following the rules of the abstract machine ([[intro.execution]](https://eel.is/c++draft/intro.execution)), would evaluate one of the following: 
> - an invocation of a non-constexpr function;

@shafik for a second pair of eyes
