### ISSUE TITLE
Link to libclang library successfully, but runtime error

### ISSUE THREAD

**Issue by 1234567845246** [llvm/llvm-project#66580]
I successfully linked to libclang with no error, but there was an error at runtime.I found the file liclang,so.18git with libclang.so
![image](https://github.com/llvm/llvm-project/assets/73998443/e5658155-68e6-42ee-a9ce-d084954a1d28)
Here's some information about clang
![image](https://github.com/llvm/llvm-project/assets/73998443/645795eb-bf71-4466-82eb-1df9f12ec427)

**Comment by 1234567845246** [comment]
I tried putting libclang.so in the same directory as the source code and running it again, but this error still occurred

**Comment by smcpeak** [comment]
The problem is the shared library isn't in the loader search path.  See [Linux error while loading shared libraries: cannot open shared object file: No such file or directory](https://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s), which for me is the first hit when googling the error message.
