### ISSUE TITLE
[clang-tidy] misc-include-cleaner doesn't understand associated headers

### ISSUE THREAD

**Issue by Tyranisaur** [llvm/llvm-project#67140]
Apologies if this is covered in documentation somewhere, but I ran into this issue while enabling the misc-include-cleaner check in clang-tidy, which was added in version 17.

The most pressing issue is that when `file.cpp` consists only of 
`#include "file.h"` 
The `misc-include-cleaner emits` a warning that `file.h` is unused. This construction is made specifically so that `file.h` is compiled on its own in at least one translation unit. The practice of doing so is recommended by John Lakos in his book and in his talks he has held. See https://github.com/Bloomberg/BDE/wiki/physical-code-organization#component-design-rules 

Additionally, the guideline appears to suggest that within a `file.h` + `file.cpp` pair, it is sufficient to include some header in only the header file.

Trying to follow the documentation, from https://releases.llvm.org/17.0.1/tools/clang/tools/extra/docs/clang-tidy/checks/misc/include-cleaner.html it seems like this clang-tidy check is based on the corresponding functionality in clangd. Following that chain, the clangd documentation suggests that "Include What You Use"-pragmas are supported https://clangd.llvm.org/design/include-cleaner#iwyu-pragmas. And finally, the docmentation for these pragmas suggests that there exists a specific pragma that can be used to declare that a header file should be treated as associated with the main file of the translation unit. https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-associated I tried to apply this pragma in some instances, but it doesn't appear to have had any effect.

Without this sorted out, it seems like this check might be a bit too noisy for our use. However, the documentation suggests that this check only applies to main implementation files, so maybe this is working as intended so far?

**Comment by sam-mccall** [comment]
Indeed include-cleaner doesn't have special treatment for associated headers. The flavor of IWYU it's designed to implement isn't the one described by BDE. It'd be useful for us to document it...

> when file.cpp consists only of
> #include "file.h"
> This construction is made specifically so that file.h is compiled on its own in at least one translation unit

This makes sense. We've mostly used include-cleaner with build systems that validate header files on their own as translation units without the need for a stub `*.cpp` file, and with projects that don't bother with this at all.
But this doesn't seem like a difficult pattern to recognize and support.

> Additionally, the guideline appears to suggest that within a file.h + file.cpp pair, it is sufficient to include some header in only the header file.

This is probably a case where we have to disagree with those guidelines. This is a complicated rule that makes the code less uniform and inhibits automated refactoring. It requires tools to understand library/component boundaries - it looks like BDE's answer is to rigidly prescribe the structure of a component, but we don't get to assume BDE is being followed. (Or recommend it - that rigidity seems like a poor tradeoff to me).

> the clangd documentation suggests that "Include What You Use"-pragmas are supported

It lists which pragmas are supported, and `associated` isn't currently one of them.
Exact IWYU compatibility isn't a goal, e.g. `friend` is too complicated and will probably never be supported.
But if we add support for associated headers, we should support the `associated` pragma too.

> However, the documentation suggests that this check only applies to main implementation files, so maybe this is working as intended so far?

Hmm, a few different answers to this:

- when **clangd** documentation talks about "main file", it means the file open in the editor, whether it is a header or not. We only produce warnings for open files.
- similarly, when run as a clang-tidy check, include-cleaner only analyzes the main file that clang-tidy was run on, whether that's a header or an implementation file. This is different than many clang-tidy checks that look for dubious code patterns anywhere in the translation unit.
- many ways of running clang-tidy will only run it on implementation files, not headers. For example, if you use run-clang-tidy.py to conusme `compile_commands.json`, and your build system does not include compile commands for headers in `compile_commands.json` (most don't), then you'll never run the check on headers
- cleaning up headers requires more care/testing than implementation files, because removing unused includes can break other TUs that are transitively relying on them. (The tool will happily do it, just a consideration when choosing workflow)
- I'm not sure what *specific* doc you're referring to, but this has evolved a bit and I'm sure some of the docs are out-of-date...

I'll try to hack together something for associated header support
