### ISSUE TITLE
lld does not accept `-relax`

### ISSUE THREAD

**Issue by rui314** [llvm/llvm-project#67219]
ld.lld accepts only `--relax` and `--no-relax` and reports `-relax` and `-no-relax` as unknown options. I think this is not consistent with the manual that says any option except the ones start with `o` can be lead either a single dash or double dashes.

**Comment by dtcxzyw** [comment]
Some one-dash long options are rejected by lld after e20a215992dc685ed843b1023143f914edbb1211.
Please refer to https://lists.llvm.org/pipermail/llvm-dev/2020-May/141416.html and https://reviews.llvm.org/D79371.
@MaskRay

**Comment by MaskRay** [comment]
> Some one-dash long options are rejected by lld after https://github.com/llvm/llvm-project/commit/e20a215992dc685ed843b1023143f914edbb1211.
Please refer to [lists.llvm.org/pipermail/llvm-dev/2020-May/141416.html](https://lists.llvm.org/pipermail/llvm-dev/2020-May/141416.html) and [reviews.llvm.org/D79371](https://reviews.llvm.org/D79371).

Exactly. Some older options (e.g. `-shared` and `--shared`) allow both forms to be compatible with packages in the wild. Otherwise, we should avoid single dash long options to catch typos as we deliberately don't implement GNU ld's grouped short options. Note that newer GNU ld long options only support `--` as well.

**Comment by rui314** [comment]
Then don't you want to update this paragraph of the man page?

     Many options have both a single-letter and long form.  When using the
     long form options other than those beginning with the letter o may be
     specified using either one or two dashes preceding the option name.  Long
     options beginning with o require two dashes to avoid confusion with the
     -o path option.
