### ISSUE TITLE
std::vector is changed when copy-assignment in vec.insert(pos, const_value) throws

### ISSUE THREAD

**Issue by leni536** [llvm/llvm-project#67367]
version: clang 17.0.1
flags: `-stdlib=libc++ -std=c++20 -O2`

## Observed behavior

```cpp
#include <vector>
#include <iostream>

struct S {
    S() = default;
    S(const S&) = default;
    S(S&&) = default;
    S& operator=(const S&) {
        throw 42;
    }
    S& operator=(S&&) = default;
};

int main() {
    std::vector<S> v;
    v.reserve(4);
    v.emplace_back();
    const S s;

    std::cout << v.size() << '\n';
    try {
        v.insert(v.begin(), s);
    } catch (...) {
        std::cout << "exception\n";
    }
    std::cout << v.size() << '\n';
}
```

This program prints:
```
1
exception
2
```

https://godbolt.org/z/4hqsPr137

## Expected behavior

https://timsong-cpp.github.io/cppwp/n4868/container.requirements.general#11.1
> if an exception is thrown by an `insert()` or `emplace()` function while inserting a single element, that function has no effects.

Therefore the size of the vector shouldn't change either.

## Notes

This is caused by moving the elements in the vector before copy assigning the value to be inserted to the moved-from element at the requested position.

https://github.com/llvm/llvm-project/blob/62f5636838ac80ebe8db9c31cdf9c5566db8f0c9/libcxx/include/vector#L1763

**Comment by philnik777** [comment]
https://eel.is/c++draft/vector.modifiers#2 is relevant here. Specifically, `If an exception is thrown other than by the copy constructor, move constructor, assignment operator, or move assignment operator of T or by any InputIterator operation there are no effects.` Since your example throws from the copy constructor, `insert` is not in general exception-safe. There is the exception `If an exception is thrown while inserting a single element at the end and T is Cpp17CopyInsertable or is_nothrow_move_constructible_v<T> is true, there are no effects`, which requires that there is no effect when inserting at the end of the vector, but the requirements for that exception are not met.

**Comment by leni536** [comment]
It doesn't throw from the copy constructor though, it throws from copy assignment.

**Comment by philnik777** [comment]
Yes, sorry. It's the `assignment operator`, so the argument itself is still valid.

**Comment by leni536** [comment]
Well, this might be a wording issue, but the wording `If an exception is thrown other than by the copy constructor, move constructor, assignment operator, or move assignment operator of T or by any InputIterator operation there are no effects.` doesn't actually specify what happens when the exception is thrown from assignment. So the "unless otherwise specified" wording at https://timsong-cpp.github.io/cppwp/n4868/containers#container.requirements.general-11 could be triggered.

I assume this isn't the intent, so I will take this to LWG, or maybe it flies as an editorial issue.
