### ISSUE TITLE
llc doesn't output anything when used with `-stop-after`/`-stop-before`

### ISSUE THREAD

**Issue by danilaml** [llvm/llvm-project#67567]
https://github.com/llvm/llvm-project/blob/9eeb0293e27c0f1b44304fd9681dcd88fd9edc0a/llvm/docs/MIRLangRef.rst#mir-testing-guide

Uses this command as an example to produce `.mir`:
`llc -stop-after=machine-cp bug-trigger.ll > test.mir`

However, when I try it, `llc` produces empty stdout. I have to pass an output file explicitly for it to work, i.e.
`llc -stop-after=machine-cp bug-trigger.ll -o test.mir`

Creating an issue, because I'm not sure if this was an intentional change (in which cases the docs need to be updated) or not (in which case it needs to be fixed).

**Comment by danilaml** [comment]
Hm, looks like it's been the case since at least ~2016.

**Comment by JOE1994** [comment]
It seems it's been like this at least since 2010 ( 7ba6f22b47487d30cccf99672116b19b244f546f )
If the input file name fed to `llc` is `foo.ll` with no output filename set explicitly, `OutputFilename` is set to `foo.s`.

https://github.com/llvm/llvm-project/blob/7ba6f22b47487d30cccf99672116b19b244f546f/llvm/tools/llc/llc.cpp#L127-L196

OTOH, the MIR testing guide section was written in 2015 by ea788c4bf8ac19b62afb07bf0851b80ec765a8c9 .

It seems the documentation was written with a mistake but wasn't corrected ever since.

I'll create a PR to update the "MIR testing guide" documentation section.

**Comment by JOE1994** [comment]
Oh documention was already fixed last year by https://github.com/llvm/llvm-project/commit/dabf8490a9ad0b8bcfd21f74b1f76ba5cdb493c9 👍 👍
