### ISSUE TITLE
Bug with aggregate initialization with a parenthesized list of values

### ISSUE THREAD

**Issue by gbMattN** [llvm/llvm-project#68198]
As of c++20, you can use a parenthesized list to initialize a dynamic array, but the following code
```
int test_it (void) {
    
    double *ptr;
    ptr=new double[](1,2,3);

    return 0;
}

int main(void) {
    return test_it();
}
```
Gives the error
```
paren.cpp:4:9: error: array 'new' cannot have initialization arguments
    4 |     ptr=new double[](1,2,3);
      |         ^            ~~~~~
1 error generated.
```
This was built on Ubuntu 22.04 using the main branch of llvm at time of reporting (75f295c2455131993f9c945320736b84c5fcf99c) with the -stdc++20 flag.
It builds successfully on up to date versions of GCC  (from 11.1)

**Comment by Destroyerrrocket** [comment]
Could I take a look into this issue? I know it is not labeled as a good first issue, but I have some experience with Clang Parse/Sema steps (I worked on the Ompss@FPGA port to LLVM: https://github.com/bsc-pm-ompss-at-fpga/llvm/commits/799b0ac6309f53ded105561521f2c7ee5b88f6b7/?author=Destroyerrrocket) And this seems to also maybe involve some codegen, which I'd love to learn about.

**Comment by Destroyerrrocket** [comment]
Seems like it will actually be a lot simpler, since clang already implements brace initialization, and based on the spec the behavior should be the same between () and {} in this case?

If the type-id or new-type-id denotes an array type of unknown bound (9.3.4.5), the new-initializer shall not be
omitted; the allocated object is an array with n elements, where n is determined from the number of initial
elements supplied in the new-initializer (9.4.2, 9.4.3).

**Comment by shafik** [comment]
This does not look trivial, we are failing in `isLegalArrayNewInitializer(...)` but just making that pass is not sufficient. 

CC @alanzhao1 who implemented `p0960r3` via http://108.170.204.19/D141546

**Comment by alanzhao1** [comment]
Will take a look at this tomorrow.

**Comment by alanzhao1** [comment]
The reason why this crashes if we hav `isLegalArrayNewInitializer(...)` unconditionally `return true` is because [`CodeGenFunction::EmitNewArrayInitializer`](https://github.com/llvm/llvm-project/blob/5930725c891b60f5fb94058c6c08a55a2e03d83e/clang/lib/CodeGen/CGExprCXX.cpp#L992) wasn't implemented for `CxxParenListInitExpr`.

I'm currently working on this.

**Comment by shafik** [comment]
> The reason why this crashes if we hav `isLegalArrayNewInitializer(...)` unconditionally `return true` is because [`CodeGenFunction::EmitNewArrayInitializer`](https://github.com/llvm/llvm-project/blob/5930725c891b60f5fb94058c6c08a55a2e03d83e/clang/lib/CodeGen/CGExprCXX.cpp#L992) wasn't implemented for `CxxParenListInitExpr`.

Yeah, that was my first take on digging into it a bit.

> I'm currently working on this.

Thank you!
