### ISSUE TITLE
Compute v_madmk with all constant operands at compile time

### ISSUE THREAD

**Issue by kosarev** [llvm/llvm-project#68315]
The output for the `llvm/test/CodeGen/AMDGPU/amdgpu-codegenprepare-idiv.ll` test currently reads like we fail to fold the `v_madmk_f32` instruction despite all operands being constant. See a related discussion in <https://reviews.llvm.org/D74435#inline-1549598>.
```
define amdgpu_kernel void @udiv_i64_oddk_denom(ptr addrspace(1) %out, i64 %x) {
...
; GFX9-LABEL: udiv_i64_oddk_denom:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    v_mov_b32_e32 v0, 0x4f176a73
; GFX9-NEXT:    v_mov_b32_e32 v1, 0x4f800000
; GFX9-NEXT:    v_madmk_f32 v0, v1, 0x438f8000, v0
```

**Comment by jayfoad** [comment]
I guess this is because AMDGPUCodeGenPrepare generates IR that could be simplified, but is not?

**Comment by Pierre-vh** [comment]
This is due to `LowerUDIVREM64`, it has no special handling for a constant RHS. It emits a FMAD_FTZ and that's never folded
```
Creating new node: t59: f32 = FMAD_FTZ ConstantFP:f32<2.870000e+02>, ConstantFP:f32<4.294967e+09>, ConstantFP:f32<2.540336e+09>
``` 
I assume we can either implement constant folding for that opcode, or add special handling for a constant RHS in that lowering function.

**Comment by Pierre-vh** [comment]
I checked a bit more and if we emit FMA instead, everything gets folded because FMA can be constant folded by the DAG. FMAD cannot be constant folded (seems like APFloat doesn't implement it?) and neither can FMAD_FTZ. 

On constant operands, we could perhaps emit a FMUL + FADD instead of a FMAD, so we allow constant folding (or we just add some combine to do FMAD-> FMUL+FADD if all constant operands?). Not sure what to do about FMAD_FTZ.

I'm not well versed in floating point magic so not sure any of this works in practice though

**Comment by jayfoad** [comment]
FMAD is defined to behave exactly like a separate FMUL and FADD so we could easily add generic constant folding for it.

I think the definition of FMAD_FTZ is "the same as FMAD except you are allowed (not required) to flush denormals to zero", so for constant folding purposes it could probably be treated the same as FMAD, but I am not 100% sure about all that.
