### ISSUE TITLE
CUDA code compile error: no member named 'max' in namespace 'std'

### ISSUE THREAD

**Issue by zhiweij1** [llvm/llvm-project#68859]
```c++
#include <cuda_runtime.h>

const float FP8_E4M3_MAX = 480.0f;
__global__ void foo() {
  float max = -10000.f;
  float quant_ptr = std::max(max / FP8_E4M3_MAX, 1.0f / 32.f);
}
```

This code can be built by nvcc: https://godbolt.org/z/WTx1fToEP
But cannot be built with clang: https://godbolt.org/z/sqYz9oYPE

**Comment by Artem-B** [comment]
If you need `std::max` please do include `<algorithm>`, as one would normally do in C++ source file. https://godbolt.org/z/Khhe3cnqv

https://en.cppreference.com/w/cpp/algorithm/max

**Comment by zhiweij1** [comment]
Hi @Artem-B , nvcc does not need this include directive. Should clang keep similar behavior like nvcc.

Furthermore, I think the `<algorithm>` is implicitly included in `<cuda_runtime.h>` (or other files included in `<cuda_runtime.h>`), why the include directive is inactive when using clang? Should it be fixed?

**Comment by zhiweij1** [comment]
Can we add "#include <algorithm>" in file `https://github.com/llvm/llvm-project/blob/main/clang/lib/Headers/__clang_cuda_runtime_wrapper.h` just like https://github.com/llvm/llvm-project/blob/main/clang/lib/Headers/__clang_hip_runtime_wrapper.h#L145 ?

**Comment by Artem-B** [comment]
We can, but I do not think that it would be the right thing to do. 

Including correct headers, regardless of whatever CUDA headers pull in themselves, is the source file's own responsibility.

We're trying to do as little 'magic' in the pre-included headers as possible. Basically, those are the headers we *must* include in order to make cuda_runtime.h usable with clang. Beyond that, exactly matching NVCC on the includes it happens to pull in is not a goal for clang. If we were to do that, then we'd have to mimic the include set for each of the CUDA versions clang can work with. That's not maintainable.
