### ISSUE TITLE
[Clang] some warnings not shown using mingw headers

### ISSUE THREAD

**Issue by snylonue** [llvm/llvm-project#68995]
```C
#include <stdio.h>

int main() {
    int i;
    scanf("%f", &i);
    printf("%d", i, i ,2);

    return 0;
}
```

```
clang -Wall .\warn.c
.\warn.c:5:5: warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use      _CRT_SECURE_NO_WARNINGS. See online help for details. [-Wdeprecated-declarations]
    scanf("%f", &i);
    ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt\stdio.h:1275:20: note: 'scanf' has been explicitly marked deprecated here
    _Check_return_ _CRT_INSECURE_DEPRECATE(scanf_s)
                   ^
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\vcruntime.h:355:55: note: expanded from macro
      '_CRT_INSECURE_DEPRECATE'
        #define _CRT_INSECURE_DEPRECATE(_Replacement) _CRT_DEPRECATE_TEXT(    \
                                                      ^
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\vcruntime.h:345:47: note: expanded from macro
      '_CRT_DEPRECATE_TEXT'
#define _CRT_DEPRECATE_TEXT(_Text) __declspec(deprecated(_Text))
                                              ^
.\warn.c:5:17: warning: format specifies type 'float *' but the argument has type 'int *' [-Wformat]
    scanf("%f", &i);
           ~~   ^~
           %d
.\warn.c:6:21: warning: data argument not used by format string [-Wformat-extra-args]
    printf("%d", i, i ,2);
           ~~~~     ^
3 warnings generated.
```

```
clang -Wall --target=x86_64-w64-mingw32 .\warn.c

```
FYI, gcc generates warnings with the same header.
```
 gcc -Wall .\warn.c
.\warn.c: In function 'main':
.\warn.c:5:13: warning: format '%f' expects argument of type 'float *', but argument 2 has type 'int *' [-Wformat=]
    5 |     scanf("%f", &i);
      |            ~^   ~~
      |             |   |
      |             |   int *
      |             float *
      |            %d
.\warn.c:6:12: warning: too many arguments for format [-Wformat-extra-args]
    6 |     printf("%d", i, i ,2);
      |        
      
```

My environment:
```
clang --version
clang version 16.0.6
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Users\snylo\scoop\apps\llvm\current\bin
```
edit: the latest release (17.0.2) also has the problem.
```
clang --version
clang version 17.0.2
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Users\snylo\scoop\apps\llvm\current\bin
```
```
gcc --version
gcc.exe (MinGW-W64 x86_64-msvcrt-posix-seh, built by Brecht Sanders) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
system: windows 11
Both are installed via `scoop` (`llvm` and `mingw-winlibs` package)

**Comment by alvinhochun** [comment]
This does not happen on Compiler Explorer with the default MinGW Clang (UCRT), but it does if `__USE_MINGW_ANSI_STDIO=1` is defined: https://godbolt.org/z/Mzsqqrnod

My guess is it may have something to do with you using a MSVCRT toolchain, and it is probably an issue with the mingw-w64 headers instead of Clang.

CC @mstorsjo

**Comment by snylonue** [comment]
After setting `"-D__USE_MINGW_ANSI_STDIO=0"`, the warning is triggered properly.

```
clang -Wall --target=x86_64-w64-mingw32 -D__USE_MINGW_ANSI_STDIO=0 .\warn.c
.\warn.c:5:17: warning: format specifies type 'float *' but the argument has type 'int *' [-Wformat]
    scanf("%f", &i);
           ~~   ^~
           %d
.\warn.c:6:21: warning: data argument not used by format string [-Wformat-extra-args]
    printf("%d", i, i ,2);
           ~~~~     ^
2 warnings generated.
```


The `Go to Definition` jumps to different declaration (using clangd).

![image](https://github.com/llvm/llvm-project/assets/48825598/c853c522-25f7-4ece-87f2-ec23503e5c1c)

> My guess is it may have something to do with you using a MSVCRT toolchain

FYI, on another machine without msvc, and with gcc (installed here: https://winlibs.com) only, clangd doesn't give these warnings.
I can install clang on that machine and test it if you think necessary.

I'm not familiar with compilers and C language. Can you tell me where I should report this issue if it does nothing with clang?

**Comment by mstorsjo** [comment]
The issue is that when targeting msvcrt, it defaults to `-D__USE_MINGW_ANSI_STDIO=1` as long as compiling in C99 mode. With that flag enabled, it uses this declaration of `scanf`: https://github.com/mingw-w64/mingw-w64/blob/v11.0.1/mingw-w64-headers/crt/stdio.h#L302-L304 This has got explicit `__attribute__((__format__ (gnu_scanf, 1, 2)))`, but clang doesn't recognize the `gnu_scanf` format. When that flag isn't enabled, it instead uses this declaration: https://github.com/mingw-w64/mingw-w64/blob/v11.0.1/mingw-w64-headers/crt/stdio.h#L520-L521, which uses `__attribute__((__format__ (__MINGW_SCANF_FORMAT, 1, 2)))`, where `__MINGW_SCANF_FORMAT` expands to plain `scanf` for clang: https://github.com/mingw-w64/mingw-w64/blob/v11.0.1/mingw-w64-headers/crt/stdio.h#L249-L258

So the `__USE_MINGW_ANSI_STDIO=1` case would need to use `scanf` instead of `gnu_scanf` when running on Clang. Or Clang should learn to recognize the `gnu_scanf` format.

**Comment by snylonue** [comment]
I don't think clang need to support this special case, closing this issue.

BTW, does using ucrt help with this problem and how should I use it?

**Comment by h-c-mueller** [comment]
Please reopen this issue.
Rationale: This is no special case, since `-D__USE_MINGW_ANSI_STDIO=1` is _required_ if long double is used in `printf` or `scanf`.
This behavior is observed with `CLANG32` and `CLANG64`, both using ucrt (ref. https://www.msys2.org/docs/environments).
Ucrt assumes long double has the same binary representation as double, but MinGW-w64 uses extended precision for long double. So ucrt's printf and scanf family functions are incompatible with MinGW-w64's long double type.
Clang with `-D__USE_MINGW_ANSI_STDIO=1` does _not_ emit warnings for -Wformat, if the wrong format specifiers are used.

```
clang --version
clang version 18.1.4
Target: i686-w64-windows-gnu
Thread model: posix

```
```
clang --version
clang version 18.1.4
Target: x86_64-w64-windows-gnu
Thread model: posix
```

**Comment by mstorsjo** [comment]
This is primarily an issue with the mingw-w64 headers.

Secondly, Clang could of course implement the `gnu_scanf`/`ms_scanf`/`gnu_printf`/`ms_printf` format attributes. But even within GCC, the difference between the two has been reduced lately. Also, currently the mingw-w64 headers already knows and respects that Clang doesnt implement these format attributes - it's just not done completely/consistently.

**Comment by h-c-mueller** [comment]
Thank you for the information. So I assume that this is still being worked on. As an end user, I'll just wait.

**Comment by mstorsjo** [comment]
This issue should have been fixed in the latest mingw-w64 headers, in https://github.com/mingw-w64/mingw-w64/commit/3599f2fca7ec5c68aab5cea21a6794ab53d930d6. This version should also be available in the latest version of packages in msys2 now.
