### ISSUE TITLE
Incompatible operand types on ternary with identical types marked matrix_type

### ISSUE THREAD

**Issue by SewerDweller** [llvm/llvm-project#69008]
This should speak for itself: https://godbolt.org/z/aYn4EM5cY

**Comment by shafik** [comment]
CC @AaronBallman may know the best person to help with this.

**Comment by AaronBallman** [comment]
The code works in C++ because the C++ code path has a catch-all for when the types are identical, whereas the C code path only checks for identical types in some circumstances. So https://github.com/llvm/llvm-project/blob/5e1c2bf3e6fca35ee0445b2a81d47e8576024186/clang/lib/Sema/SemaExpr.cpp#L9146 needs to be updated accordingly, it seems.
