### ISSUE TITLE
Missed optimization: excessive register zeroing

### ISSUE THREAD

**Issue by dvyukov** [llvm/llvm-project#69338]
```
void foo(unsigned* dst, const unsigned* src, unsigned size) {
	unsigned idx1 = size > 16 ? 1 : 0;
	dst[idx1] = src[idx1];
	unsigned idx2 = size > 24 ? 2 : 0;
	dst[idx2] = src[idx2];
}
```

[clang generates](https://godbolt.org/z/GErr3Tox4):
```
 xor    eax,eax
 cmp    edx,0x11
 setae  al
 mov    ecx,DWORD PTR [rsi+rax*4]
 mov    DWORD PTR [rdi+rax*4],ecx
 xor    eax,eax
 cmp    edx,0x19
 setae  al
 mov    ecx,DWORD PTR [rsi+rax*8]
 mov    DWORD PTR [rdi+rax*8],ecx
 ret
```

The second `xor eax,eax` is excessive: high bytes are already zero.

**Comment by topperc** [comment]
`setae al` is implemented on recent Intel CPUs as read eax, update byte 0, write eax.

This means setae eax is dependent on the last write of eax that came before it.

The extra xor eax, eax makes the setae depend on the xor which is free instead of on the previous setae.

It might not matter in this particular example, but could add up in a longer sequence.

**Comment by dvyukov** [comment]
Oh, I see, thanks.
