### ISSUE TITLE
Help on How to debug LLVM JIT, on Aarch64

### ISSUE THREAD

**Issue by Thrrreeee** [llvm/llvm-project#69594]
I attempted to debug the examples in the LLVM JIT project using the LLDB debugging tool, specifically LLJITDumpObjects.cpp. However, I encountered an issue when I reached the statement 'int Result = Add1(42);.' At this point, it automatically jumps to the assembly code of the Add1 function, making it challenging for me to comprehend the step-by-step process of how JIT compiles the Add1 module in real-time. 
Here are my steps：
[https://github.com/llvm/llvm-project/blob/main/llvm/examples/OrcV2Examples/LLJITDumpObjects/LLJITDumpObjects.cpp](url)
I compile the file using the following command:
```shell
clang++ -g LLJITDumpObjects.cpp `llvm-config --cxxflags --ldflags --system-libs --libs core orcjit native`  -O3 -o LLJITDumpObjects
``` 

Then I set a breakpoint at 'int Result = Add1(42)' , I use LLDB for debugging.
```c++
// Look up the JIT'd function, cast it to a function pointer, then call it.
  auto Add1Addr = ExitOnErr(J->lookup("add1"));
  int (*Add1)(int) = Add1Addr.toPtr<int(int)>();
  int Result = Add1(42);
  outs() << "add1(42) = " << Result << "\n";
``` 
When I choose to step into this statement,then assembly code for the 'Add1' function appears:
![image](https://github.com/llvm/llvm-project/assets/72311224/aacb2a8f-010e-4f07-ab82-c83405ec7343)
So during my debugging process, I have no way of knowing how JIT operates.

**Comment by dtcxzyw** [comment]
https://llvm.org/docs/DebuggingJITedCode.html may help.

**Comment by weliveindetail** [comment]
This may help as well: https://weliveindetail.github.io/blog/post/2022/11/27/gdb-jit-interface-101.html#troubleshooting

**Comment by Thrrreeee** [comment]
> This may help as well: https://weliveindetail.github.io/blog/post/2022/11/27/gdb-jit-interface-101.html#troubleshooting

thank you for your help, it is useful for me to understand JIT.

**Comment by Thrrreeee** [comment]
> This may help as well: https://weliveindetail.github.io/blog/post/2022/11/27/gdb-jit-interface-101.html#troubleshooting

I would like to inquire about how LLVM is debugged in an engineering context when dealing with JIT. I've noticed that in my example runs, whenever I call a JIT-compiled function, the debugger immediately jumps to the assembly code of that function without showing how the JIT compiles it step by step. Do I need to add some code for this? My main goal is to observe how the JIT compiles the provided LLVM IR incrementally.

**Comment by lhames** [comment]
Hi @Thrrreeee,

> My main goal is to observe how the JIT compiles the provided LLVM IR incrementally.

It helps to separate out the problem:

1. How does user code get into the compiler when you reach a stub? Answer: A "resolver" function saves and restores register state around calls into the compiler. You can find the assembly for the resolver functions in OrcABISupport.cpp.
2. How is the code for the function compiled? Answer: By copying it out into its own module, then compiling that single-function module as normal.
3. How does control return to the compiled function? The resolver function restores register state and then "returns" to the compiled function, rather than the original caller. (The compiled function will return to the originally caller instead).

So the compilation step is basically the same as what the `llc` tool is doing, but the specific invocation (if you want to step through it in a debugger) happens here: https://github.com/llvm/llvm-project/blob/f16b7c62acebc6731d80565b3994452333443ffa/llvm/lib/ExecutionEngine/Orc/CompileUtils.cpp#L53
