### ISSUE TITLE
Casting away const in plain C leads to a segmentation fault

### ISSUE THREAD

**Issue by White-Pack** [llvm/llvm-project#69791]
On my 32-bits VM...
![image](https://github.com/llvm/llvm-project/assets/148591479/b584467d-459f-430d-b6dd-e6f7313ebd01)

While using the C compiler...
![image](https://github.com/llvm/llvm-project/assets/148591479/32128f5c-3323-4dd3-b34c-1bcdf95ec32f)

I could cleanly compile [bug.zip](https://github.com/llvm/llvm-project/files/13058990/bug.zip) as follows:
![image](https://github.com/llvm/llvm-project/assets/148591479/1f27a76f-e853-4c65-b34c-138ad7a4f3b5)

Nevertheless I get an unexpected segmentation fault:
![image](https://github.com/llvm/llvm-project/assets/148591479/e06bf17d-85ce-44b0-baa2-5f67a171f8a9)

**Comment by DimitryAndric** [comment]
This is because the compiler puts `h` in the `.rodata` segment, and that is because you specifically asked for the object to be read-only. At runtime the dynamic linker maps this segment into memory, and marks it read-only. If you attempt to write to any object in that segment, you get a segfault.

If you cast away const, you have to ensure that the object you are writing to is actually writable. So as far as I can see, the behavior you are seeing is completely expected, and reproduces on any modern OS.
