### ISSUE TITLE
InstCombine:dubious optimization of a - a * 0.0 when a might be inf

### ISSUE THREAD

**Issue by jayfoad** [llvm/llvm-project#70561]
InstCombine optimizes:
```
define float @f(float %a) {
bb:
  %z = fmul float %a, 0.0
  %r = fsub reassoc nsz float %a, %z
  ret float %r
}
```
to:
```
define float @f(float %a) {
bb:
  ret float %a
}
```
This seems dubious to me because if %a is inf, the result should be nan. There are no "ninf" or "nnan" flags in the code. Is there something about the "reassoc" and "nsz" flags that somehow allows this optimization?

**Comment by jayfoad** [comment]
See these cases in `InstCombinerImpl::visitFSub`:
```
    // (X * C) - X --> X * (C - 1.0)
    // X - (X * C) --> X * (1.0 - C)
```
If X can be infinite and C is 0 then they will give the wrong result. I am not sure whether the `reassoc` flag should allow this. My feeling is it should mean "allow reassociation to change the precision of the result", and you should have to add `ninf` or `nnan` if you additionally want to allow reassociation to give different results for inf/nan cases.

**Comment by jcranmer-intel** [comment]
I would say that only `nnan`, `ninf`, and `nsz` have clear semantics for flags; I'm not sure anyone has well-reasoned semantics for any of the other flags, let alone anything formally verifiable.

Part of the problem is that `fast` is understood as a general instruction to use algebraic transformations that would be legal if floats were real numbers but are not legal under floating-point rounding modes, and at the same time, it's strictly a conjunction of several individual flags, so every desired transformation has to get shoehorned into one or a few of these flags.

Nevertheless, I think it could be reasonably understood that the `reassoc` flag includes license to freely apply the associative and distributive law to floating-point arithmetic. We should be able to transform `(X + Y) + Z` to `X + (Y + Z)` even if `X + Y` would overflow to infinity and `Z` is negative infinity, even though this changes the result from NaN to negative infinity. For a similar reason, `X * Y + X * Z` should be generically transformable to `X * (Y + Z)`, again without recourse to the potential values of `X`, `Y`, and `Z`.  `Y` and `Z` being constants instead of variables of unknown value shouldn't change the legality analysis.

**Comment by jayfoad** [comment]
Thanks! That all makes perfect sense to me and I will close this issue accordingly.

Incidentally most of the reassociations in `InstCombineAddSub.cpp` are guarded by `hasAllowReassoc && hasNoSignedZeros`. Based on your explanation the `hasNoSignedZeros` part is not necessary. I had a look into the history of this. It comes from [D45453](https://reviews.llvm.org/D45453) where various points were made:
* @wjristow pointed out that Clang will only set the `reassoc` FMF if you compile with `-fassociative-math -fno-signed-zeros -fno-trapping-math`.
* @spatel-gh seems to say that these transformations _should_ be guarded by additional FMF checks, but only `nsz` is needed because: "We're confident that this code only deals with fadd/fsub, so { nnan , ninf , arcp , afn , contract } shouldn't be in play." This does not make sense to me.

**Comment by arsenm** [comment]
There are a number of places that I think have an overly aggressive interpretation of reassoc. I don't believe it should be allowed to reassociate unless the touching instructions are both marked reassoc
