### ISSUE TITLE
[flang] Don't generate mul constant expressions

### ISSUE THREAD

**Issue by nikic** [llvm/llvm-project#71507]
Flang currently generates mul constant expressions:
```
[npopov@fedora llvm-project]$ git grep "mul (" flang
flang/test/Fir/alloc.fir:// CHECK: call ptr @malloc(i64 mul (i64 ptrtoint (ptr getelementptr (i32, ptr null, i32 1) to i64), i64 100))
flang/test/Fir/alloc.fir:// CHECK: %[[mul2:.*]] = mul i64 mul (i64 ptrtoint (ptr getelementptr (i8, ptr null, i32 1) to i64), i64 9), %[[mul1]]
flang/test/Fir/alloc.fir:// CHECK: %[[prod2:.*]] = mul i64 mul (i64 ptrtoint (ptr getelementptr (i16, ptr null, i32 1) to i64), i64 3), %[[prod1]]
flang/test/Fir/alloc.fir:// CHECK: %[[a:.*]] = mul i64 mul (i64 ptrtoint{{.*}} 15), %[[e1]]
flang/test/Fir/alloc.fir:// CHECK: %[[mul:.*]] = mul i64 mul (i64 ptrtoint (ptr getelementptr ([3 x [10 x i16]], ptr null, i32 1) to i64), i64 4), %[[e]]
flang/test/Fir/alloc.fir:// CHECK: %[[a:.*]] = mul i64 mul (i64 ptrtoint (ptr getelementptr (i16, ptr null, i32 1) to i64), i64 12), %[[len]]
flang/test/Fir/box.fir:  // CHECK: insertvalue { ptr, i64, i32, i8, i8, i8, i8, [2 x [3 x i64]] } %{{.*}}, i64 mul (i64 ptrtoint (ptr getelementptr (float, ptr null, i32 1) to i64), i64 200), 7, 0, 2
flang/test/Fir/box.fir:  // CHECK: insertvalue { ptr, i64, i32, i8, i8, i8, i8, [2 x [3 x i64]] } %{{.*}}, i64 mul (i64 ptrtoint (ptr getelementptr (float, ptr null, i32 1) to i64), i64 30000), 7, 1, 2
flang/test/Fir/embox.fir:// CHECK: [i64 1, i64 5, i64 mul (i64 ptrtoint (ptr getelementptr (i32, ptr null, i32 1) to i64), i64 2)]] }, ptr %[[a3]], 0
flang/test/Fir/embox.fir:  // CHECK: insertvalue {[[descriptorType:.*]]} { ptr undef, i64 mul (i64 ptrtoint (ptr getelementptr (i8, ptr null, i32 1) to i64), i64 2), i32 20180515, i8 2, i8 40, i8 0, i8 0
```
Support for these will be dropped imminently.

The root problem is that you're generating sizeof constant expressions. You should stop doing that and directly produce sizes according to the used DataLayout. Possibly you forgot to pass down the DataLayout somewhere?

**Comment by jeanPerier** [comment]
Hi @nikic, thanks for reporting this. Can you provide a bit more context about why this is depreciated (RFC, documentation links...), I find it convenient to use these sizeof expressions to leave target dependent aspects up to LLVM when possible.

**Comment by nikic** [comment]
> Can you provide a bit more context about why this is depreciated (RFC, documentation links...), I find it convenient to use these sizeof expressions to leave target dependent aspects up to LLVM when possible.

The mul expressions in particular will be removed as part of https://discourse.llvm.org/t/rfc-remove-most-constant-expressions/63179. You can test this bit by reapplying https://github.com/llvm/llvm-project/commit/0a362f12ec60a49a054befec8620a8e69523af54 and checking whether flang tests pass.

Ability to express sizeof constant expressions will go away with https://discourse.llvm.org/t/rfc-replacing-getelementptr-with-ptradd/68699.

More generally, support for DataLayout-independent modules has been removed from LLVM something like twenty years ago, and remaining holdovers of the old model get slowly removed over time.

**Comment by jeanPerier** [comment]
Thanks for the links, they are very instructive. I will update the flang codegen.

**Comment by jeanPerier** [comment]
Hi @nikic, after some experiments, it turns out that what you are requesting is in my opinion a step backward in flang.

We will need to introduce target dependent tests for a lot of our LLVM IR code generation step that will only be runnable when the relevant target are available. Currently, the code generation only uses target llvm::Triple info that can be used from any host. 
But it seems there is no way to get the llvm::DataLayout for a target without creating an llvm::TargetMachine which:

1. restricts the targets for which the code generation pass can be run/tested to the ones for which the llvm::Target available on the host (while there was no such restriction before, which helps debugging problems people are facing on exotic architectures we do not have necessarily have access to).

2. is a bit convoluted to deal with in the middle of an MLIR pass (I do not want to call llvm::InitializeAllTargets in the middle of an MLIR pass that may be threaded). To clarify, the target DataLayout is available somewhere in a nice end-to-end compilation flow, but flang is tested modularly, and so far there was no need to have access to the DataLayout when translating FIR MLIR dialect to LLVM IR, which allowed some level of target independent testing (most FIR tests can be run on any host provided a target triple argument). The pass could take a datalayout string argument but I would love to just get it from the target triple instead of risking passing a datalayout that is just wrong for that target triple.

So while I agree that it is pointless to aim at the LLVM IR produced from Fortran to be target independent (just like C, Fortran has features that require some target knowledge in semantics), I still find that removing these target independent aspects makes modular testability harder (for front-ends at least. It obviously likely makes LLVM life easier).

If the llvm direction is to remove the remaining bits of target independence in LLVM IR, would it be possible to first expose a way to create llvm::DataLayout for a target triple without requiring the availability of an llvm::Target (I have no idea of the implications here)?

**Comment by nikic** [comment]
It sounds like those tests should just use the default data layout (or some data layout, not necessarily corresponding to any specific target). That's how LLVM middle-end tests are normally written.

You might want to have a test that ensures that flang is passing down the correct data layout for the target (if you don't have this already), but there shouldn't be a need to test a specific target for FIR to LLVM IR lowering, if I understand correctly.

**Comment by jeanPerier** [comment]
Thanks for the advice, that sounds OK.

I have a draft https://github.com/jeanPerier/llvm-project/tree/jpr-datalayout-2, but I am hitting an issue in MLIR because MLIR uses `unsigned` for the type sizes its data layout representation (https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/Interfaces/DataLayoutInterfaces.h), and that is simply too small for some of the Fortran code out there (some indexing operation/allocation would now silently be generated completely wrong due to integer overflow).

I opened https://github.com/llvm/llvm-project/issues/72678.

**Comment by nikic** [comment]
@jeanPerier Thanks for working on this! I see that the PR has been merged -- I was wondering is left to do to avoid the generation of constant expressions in the alloc.fir/box.fir/embox.fir tests, now that data layout is present.
