### ISSUE TITLE
C++23 range formatters are not available by #include <print>

### ISSUE THREAD

**Issue by dangelog** [llvm/llvm-project#71925]
Testcase against clang trunk:

https://gcc.godbolt.org/z/c1PYs1nxG
```c++
#include <vector>
#include <print>
// #include <format>

int main() {
    std::vector<int> v{1, 2, 3};
    std::println("{}", v);
}
```

This doesn't compile; one must include `<format>` to get the range formatters.

I'm not sure how to read the Standard here. In principle, the `std::formatter` specializations for ranges are in `<format>` (https://eel.is/c++draft/format.syn) but that doesn't sound user-friendly.

**Comment by mordante** [comment]
You read the Standard correctly and this is indeed required. Other vendors do not use granularized headers like libc++ does so they probably will include `<format>`. MSVC STL does and libstc++ has not implemented the `print` header.

I still think from a QoI perspective it would be good to include `<format>` from `<print>`.

**Comment by dangelog** [comment]
If we go down this path, could one state that `formatter` specializations for any builtin language/library type are "technically" only in `<format>`? That makes including `<print>` alone pretty useless...

Is this just QoI, or should I raise an issue in L(E)WG asking for `<print>` to either include `<format>` or at least guarantee that the library specializations of `formatter` are available from either header?

**Comment by mordante** [comment]
I had considered filing an LWG issue, but decided it was not really worth it. Based on how other implementations structure their headers they will not run into this issue.

If I'd filed an issue and LWG closes it with NAD I still would want to fix it in libc++.

**Comment by ldionne** [comment]
Personally, I would like to see a LWG issue filed here. We shouldn't add transitive includes and start "promising" these transitive includes as an extension when it's so easy for the Standard to require that this works reliably.

**Comment by mordante** [comment]
Other implementations without granularized headers will work out of the box, they need to include format. If I had noticed this during development I would have added format too. So I see this as a QoI. 

I agree we should be careful with transitive includes. But I feel this swings the pendulum a bit too much in the other direction.

**Comment by ldionne** [comment]
I understand that you view this as QoI, but concretely we're promising something to our users without the Standard requiring it, which makes this an extension. We both agree that this extension makes for a better library, but what I am asking is for it to be standardized so it's not an extension anymore. We should expect LWG to say "yes, that's a no brainer" and then we can proactively fix this.

**Comment by mordante** [comment]
I started writing an LWG-issue. While doing so I became convinced our current `print` implementation is non-conforming, so I abandoned the LWG-issue. The example posted by @dangelog should work:

[[ostream.formatted.print]/2](http://eel.is/c++draft/ostream.formatted.print#2)
```
Effects: Equivalent to: print(os, "{}\n", format(fmt, std::forward<Args>(args)...));
```

[[print.fun]/4](http://eel.is/c++draft/print.fun#4)
```
print(stream, "{}\n", format(fmt, std::forward<Args>(args)...));
```
per [[format.syn]](http://eel.is/c++draft/format.syn) `format` is specified to work for a range
```
  // [format.range.fmtmap], [format.range.fmtset], [format.range.fmtstr], specializations for maps, sets, and strings
  template<ranges::input_range R, class charT>
	requires (format_kind<R> != range_format::disabled) &&
			 formattable<ranges::range_reference_t<R>, charT>
  struct formatter<R, charT> : range-default-formatter<format_kind<R>, R, charT> { };
```

This means the PR I created needs updating too.

**Comment by kraj** [comment]
The fix for this issue to include <format> is having an interesting side-effect with clang-18/libc++ compiling elfuitls. elfutils builds a program called `stack` and in that directory compiles another c++ source file where it uses `-I.` via cmdline and the compile fails because it includes the file named `stack` from current dir (.) and not from libc++ system headers. I think this fix here is not the casue of it but unearths a latent issue which did not show up in older clang releases.

a simple reproducer is
 
```c++
#include <iostream>
```
cp /usr/bin/ls stack

clang++  -c-I. a.cpp

results in errors like below

```
In file included from ../../elfutils-0.191/src/srcfiles.cxx:50:
In file included from /mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/elfutils/0.191/recipe-sysroot/usr/include/c++/v1/iostream:44:
In file included from /mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/elfutils/0.191/recipe-sysroot/usr/include/c++/v1/istream:170:
In file included from /mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/elfutils/0.191/recipe-sysroot/usr/include/c++/v1/ostream:189:
In file included from /mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/elfutils/0.191/recipe-sysroot/usr/include/c++/v1/format:195:
In file included from /mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/elfutils/0.191/recipe-sysroot/usr/include/c++/v1/__format/container_adaptor.h:25:
./stack:1:1: error: expected unqualified-id

```

**Comment by mordante** [comment]
Thanks for the info. I can reproduce it; I did use a less dangerous `stack` file ;-) This only happens when you add the `-I.` without it it does not try to pick up `stack`. I wonder whether the compiler should search the std lib includes before the manually added include dirs. @AaronBallman is this a Clang bug?

**Comment by AaronBallman** [comment]
`-I` is documented to search the specified paths before the system paths (https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-I-dir), so that's not a bug.

Note, there is `-iquote` that could perhaps be used instead of `-I` because that should only apply to quoted includes of the file, not angle bracket includes.

**Comment by mordante** [comment]
Thanks @AaronBallman! Then it seems elfutils needs to fix its build scripts.
