### ISSUE TITLE
[MemProf] Assert failed in MemProfContextDisambiguation::applyImport

### ISSUE THREAD

**Issue by lifengxiang1025** [llvm/llvm-project#72094]
I met an error when try to use MemProf:

> bool llvm::MemProfContextDisambiguation::applyImport(llvm::Module&): Assertion `CB->getCalledFunction()' failed.

After debugging, I found `mayHaveMemprofSummary` returned true but `assert(CB->getCalledFunction())` failed.
The `CalledFunction` in `mayHaveMemprofSummary` is nullptr unitl:
```
  if (auto *GA = dyn_cast<GlobalAlias>(CalledValue)) {
    assert(!CalledFunction &&
           "Expected null called function in callsite for alias");
    CalledFunction = dyn_cast<Function>(GA->getAliaseeObject());
  }
```
`CB->getCalledFunction()` is nullptr so it caused assert failed while CalledValue's aliasee is not nullptr so it pass `mayHaveMemprofSummary`.
So I think there may be a bug to be fixed.

**Comment by lifengxiang1025** [comment]
@teresajohnson

**Comment by teresajohnson** [comment]
Yeah, that is a bug. I had encountered that not long ago and it is fixed in a local clone where I have been working on the indirect call handling. I will send that fix for review separately. I need to create a small test case, and will do that and send for review as soon as I can. The fix btw is to replicate the handling from ModuleSummaryAnalysis above where that code calls mayHaveMemprofSummary, specifically the code that looks through pointer casts and aliases, and use the resulting function: https://github.com/llvm/llvm-project/blob/9aefa5cb679a6f42a0d343c93a25a66b0374b3c6/llvm/lib/Analysis/ModuleSummaryAnalysis.cpp#L375-L387
