### ISSUE TITLE
Static variable inside inline function emitted in a different section group than the function

### ISSUE THREAD

**Issue by smeenai** [llvm/llvm-project#72361]
We ran into an interesting crash when upgrading from C++17 to C++20. We had an inline function being compiled into some object files built with C++17 and some built with C++20. This inline function has a `static const std::string` variable, which becomes constexpr in C++20. A simplified version is as follows (the `[[clang::nodestroy]]` generates shorter code but the issue also exists without it):

```
inline const std::string &get() {
    [[clang::no_destroy]] static const std::string empty;
    return empty;
}
```

The generated code for C++17 and C++20 can be seen in https://godbolt.org/z/evo95T1dj. In C++17, the string object is zero-initialized at runtime, so the object is stored in writable memory. (It's stored in `.bss`, so I don't know why the runtime zero-initialization is necessary, but I digress.) In C++20, the string object is stored as a bunch of zero bytes in the read-only section `.rodata` and not initialized at runtime.

The crash arose because the linker ended up picking `get` from a C++17 object but `get::empty` from a C++20 object. This meant that `get`'s runtime initialization was trying to write to read-only memory, which of course segfaulted. I haven't dug into how this particular linker selection ended up occurring (it was in an LTO build, which might have complicated things), but as far as I understand, since Clang is emitting `get` and `get::empty` in different COMDAT section groups, it's valid for the linker to mix and match them like this. On the other hand, if Clang had emitted `get::empty` in the same section group as `get`, the linker would have had to pick or discard both of them as a unit, so the bad mixing couldn't have occurred. Is this understanding correct, and if so, what's the reason for Clang using two different section groups here?

CC @rnk and @MaskRay

**Comment by rnk** [comment]
I think the comdat behavior is correct and intentional, if we put static locals in the same comdat group as the function, that would break inlining. Inlining effectively clones the function body and generates new references to the static local from outside the comdat group.

Static locals in inline functions are extremely ABI-fragile, and typically it's not a win to inline these functions. I would generally recommend sinking inline functions like this out of headers.

**Comment by smeenai** [comment]
You're right. My specific problem, after looking more into it, turned out to be related to inlining as well. I don't think this technically counts as an ODR violation (since the source tokens are the same in all TUs), so it was kinda surprising to have it blow up like this, but I guess it's fragile regardless.

**Comment by dwblaikie** [comment]
Yeah, I think th ecomdat behavior is correct - but it still seems like there's a bug here? Like I think we want to/would expect to support having an inline function with a static local compiled with C++17 and C++20 and get correct behavior... 

If we can't support that, seems important to document and maybe warn/break/something in this situation - otherwise that's pretty subtle/easy to trip over.

**Comment by rnk** [comment]
I think you are right, that is the bug: There is an ABI incompatibilty between C++17 and C++20 due to the constexpr-ification of std::string. Maybe route to libc++? It seems like an unfixable problem, however.

**Comment by dwblaikie** [comment]
> I think you are right, that is the bug: There is an ABI incompatibilty between C++17 and C++20 due to the constexpr-ification of std::string. Maybe route to libc++? It seems like an unfixable problem, however.

Tagging libc++.

As for fixes, /maybe/ there's room for an ABI fix - if the object is const initialized, then the global flag that tracks its initialization should be already set as "initialized" - and that flag should be in the same comdat group as the global itself and so should get picked together?

So I guess what I'm suggesting is a clang change - that we always emit a guard variable (const value 1) for comdat constexpr variables.

Is that feasible? Would it need to be opt-in with an attribute insntead (that'd be unfortunate - it'd mean other people's code would still silently break, even if we fixed libc++ std::string with the attribute)

**Comment by dwblaikie** [comment]
> The only other "fix" I could think of would be to somehow make it so that `std::string` is constant initialized in all Standard modes, but this would only solve the problem for default construction. Unless we can basically apply `Making std::string constexpr` in all Standard modes as a DR, but I'm 99% certain that's impossible due to missing core language features in `constexpr`.

Which wouldn't address the shipped situation, yeah? (like I have some code already compiled with c++17 and I'm linking it into my new C++20 code) but the ABI fixes I'm suggesting wouldn't help there either, I guess... or maybe they would? Hmm, nope - if we created a new comdat group for the static+guard, the old code would keep its static+guard and new code would get a new one, so inlined copies of the inline function could diverge/end up with two versions of the variable which would be bad.

Yeah, maybe we're solidly in "no way to make this backwards compatible" territory? Probably... but then still potentially worth trying to find a "I compile my code fresh, some in C++17 and some in 20, and it should still work together" solution.

**Comment by dwblaikie** [comment]
Yeah, any case of making a ctor constinit-able across versions. (hmm, what do we do if we /optimize/ code to the point where it's constinit? I guess we still put it in a writable section to ensure it can be redundantly initialized if it gets picked up by a less optimized version of the ctor? Or do we avoid it in some other way?)

(Hmm, if we optimize out the initialization, we still emit the whole guard acquire/release/etc - and the only thing it guards is `llvm.invariant.start.p0` call... at least it doesn't modify the global object, so there's no actual race, etc... wonder if we could optimize that a bit more somehow)

If we did put the variable, guard, and function in the same comdat, at least they'd be discarded by the linker if using `--gc-sections` maybe? Or is there some other way to say "if you keep 1A, you need to keep 1B as well" but you can discard 1A even if you do keep 1B or something.. I 'm not sure.

**Comment by ldionne** [comment]
I'll just drop a thought out there -- ABIs in C++ have always been difficult and tricky to keep stable. That was true in the C++03 era, and I feel like it's becoming significantly more true in a world where WG21 has rolling releases every 3 years and as a result 7 different standard versions that can all be used at the same time in a program.

I'm just saying this because I've been exposed to 2-3 subtle ABI breaks that root cause to different behavior in different Standard versions in the past 48h, and I've definitely noticed that this was getting harder and harder to get right in the past 5 years. I'm not sounding the alarm, but at some point we might *need* some kind of meta-solution to this because it seems like just doing our best to keep the ABI stable isn't sufficient -- we're still escaping a few "bugs" like this.

Maybe limiting the extent to which one can mix and match different standard versions would help make this problem more tackle-able? I don't know, this is just food for thought and I'll stop now to avoid hijacking this thread any more.

**Comment by shafik** [comment]
CC @AaronBallman @erichkeane @cor3ntin 

I think it may be worth tracking ABI issues like someplace. Do we know if this issue is coming up w/ other implementations as well?

**Comment by AaronBallman** [comment]
> CC @AaronBallman @erichkeane @cor3ntin
> 
> I think it may be worth tracking ABI issues like someplace.

At the very least, we should add the `ABI` label to issues so we can collect them all in one place. But it might be worth considering having an LLVM Dev Conf round table discussion on the topic?

> Do we know if this issue is coming up w/ other implementations as well?

I'm not certain.

**Comment by dwblaikie** [comment]
We could take it up on the itanium abi github repo/file an issue there to discuss it.

> Maybe limiting the extent to which one can mix and match different standard versions would help make this problem more tackle-able? 

Be interesting to see what other implementations do (especially MSVC I guess, since GCC's likely closer to us/likely has similar problems - though, equally, if they don't have the same problems that's more directly applicable to us) - my understanding was MSVC does/used to do hard ABI breaks (linker failures) for mismatched MSVC versions of C++, but I didn't think they had any breaks between language versions. So maybe they'd deal with this by just language-version-backporting any constexpr ctors - that way they'd be consistent across language versions & without MSVC-version-back-compat they woludn't have to worry about old code compiled against the previous non-constexpr ctor. but that's a rough situation for Itanium/linux/gcc/clang that haven't had that sort of breakage policy. (& maybe I misunderstand/misremember some of these details)

**Comment by rnk** [comment]
I agree that C++ ABI stability has always been hard, and it's getting harder.

I think the best fix we could implement is to provide a new attribute annotating a class or constructor to say "this type was previously not constexpr-constructible, please generate code in a way that is compatible", and then use that attribute in libc++ when the stable ABI is requested. This is, however, an extremely niche feature! Without the explicit annotation, I don't think the compiler should conservatively generate code for vague linkage constexpr globals with the assumption that there could be some non-constexpr version of this global in the final link. That would greatly pessimize a lot of new constexpr globals. 

The "do nothing" alternative should be to document that there is a C++20 ABI break for vague linkage globals of types that are constexpr-constructible in C++20, such as string and any others. Going forward, users who care about ABI stability should audit their ABI boundary for vague linkage globals, such as static locals in inline functions, static data members of class templates, inline global variables, etc.

**Comment by rprichard** [comment]
I also ran into this same problem recently, https://discourse.llvm.org/t/mixing-c-17-and-c-20-std-string-causes-segfault-writing-to-rodata/77974.

My current workaround, https://r.android.com/3010579, assumes that the compiler won't see through the non-constexpr `EmptyString() {}` constructor to move the variable into `.rodata`. I reasoned that the compiler couldn't do this, because if it did, then different Clang versions would be ABI-incompatible, but I'm not sure that's actually a reasonable expectation. Moving the variable to be not inlined may also work but with its own downsides.

**Comment by dwblaikie** [comment]
> I also ran into this same problem recently, https://discourse.llvm.org/t/mixing-c-17-and-c-20-std-string-causes-segfault-writing-to-rodata/77974.
> 
> My current workaround, https://r.android.com/3010579, assumes that the compiler won't see through the non-constexpr `EmptyString() {}` constructor to move the variable into `.rodata`. I reasoned that the compiler couldn't do this, because if it did, then different Clang versions would be ABI-incompatible, but I'm not sure that's actually a reasonable expectation. Moving the variable to be not inlined may also work but with its own downsides.

Looks like a reasonable workaround, and seems robust to me - the frontend's ~never going to look at that ctor and see through it & do something novel, and the backend's not going to move the section the data goes in after optimizations, I don't think. You could make it a tiny bit more robust, at the cost of some portability/macros/etc by adding `__attribute__((optnone))` to the ctor, perhaps.
