### ISSUE TITLE
Can't use UDL of `std::string` with `import std;`

### ISSUE THREAD

**Issue by JohelEGP** [llvm/llvm-project#72427]
With <https://libcxx.llvm.org/Modules.html#using-in-external-projects>,
the following program fails:
```C++
export module main;
import std;
using namespace std::string_literals;
```
```
main.cpp:3:22: error: missing '#include <string>'; 'string_literals' must be declared before it is used
    3 | using namespace std::string_literals;
      |                      ^
/home/johel/Documents/C++/Forks/llvm/libcxx-std-modules/include/c++/v1/string:4387:20: note: declaration here is not visible
 4387 |   inline namespace string_literals
      |                    ^
1 error generated.
```

**Comment by ChuanqiXu9** [comment]
I am wondering if this is a libc++'s issue. I've checked that in modules/std/string.inc, only the namespace `std::literals` and `std::literals::string_literals` are exported and `std::string_literals` are not mentioned. @mordante

**Comment by JohelEGP** [comment]
`using namespace std::literals::string_literals;` fails equally.

**Comment by ChuanqiXu9** [comment]
> `using namespace std::literals::string_literals;` fails equally.

Got it. I'll try to take a look.

**Comment by ChuanqiXu9** [comment]
After I took more experiment in the library level, I feel this is a library issue more.

First, it is not a problem to `using namespace std::literals;`. Since there are multiple use `inline namespace literals` inside *.inc under `build/_deps/std-src/std`.

Then for `std::literals::string_literals`, it is guarded by `#if` directives in string.inc:

```
// TODO MODULES is this a bug?
#if _LIBCPP_STD_VER >= 23
  using std::operator""s;
#else
  inline namespace literals {
    inline namespace string_literals {
      // [basic.string.literals], suffix for basic_string literals
      using std::literals::string_literals::operator""s;
    } // namespace string_literals
  }   // namespace literals
#endif
```

It looks like the `#else` branch is not taken since I added an `#error` directive but the std module still compiles.

Finally, I add the namespaces manually in std.inc:

```
inline namespace literals {
    inline namespace string_literals {}
  }
```

Then `using std::literals::string_literals;` compiles too.


For `std::string_literals`, since it doesn't appear in any place under `build/_deps/std-src/std`, so I believe it is not exported.
