### ISSUE TITLE
AArch64 miscompile of i1 arithmetic with global isel

### ISSUE THREAD

**Issue by regehr** [llvm/llvm-project#72475]
Here's a function that should always return true:
```llvm
define i1 @f(i1 %0) {
  %2 = shl i1 true, %0
  %3 = select i1 %0, i1 true, i1 %2
  ret i1 %3
}
```
if %0 is true then it returns true (select blocks poison from its not-selected operand, so the intermediate poison value is not relevant here).

if %0 is false then it returns a not-shifted true value, so it returns true this time too. 

the SDAG backend gives:
```
_f:                              
	mov	w0, #1
	ret
```

on the other hand llc with global isel gives:
```
_f: 
	and	w8, w0, #0x1
	mov	w9, #1               
	lsl	w8, w9, w8
	and	w0, w8, #0x1
	ret
```
this returns 0 when the input is 1

cc @hatsunespica

**Comment by topperc** [comment]
I spent some time looking at this. Here's what I found.

Both SelectionDAG and GlobalISel will turn `select i1 %0, i1 true, i1 %2` into an OR which removes the poison blocking property.

ComputeKnownBits for `shl i1 true, %0` says that the result is known to be 1. Because GISel turned the the select into OR, this causes ComputeKnownBits to think the OR is unnecessary and it gets deleted. Leaving just the shift.

Type legalization promotes the shift to i32 by zero extending the shift amount.

The only reason SelectionDAG doesn't hit this issue is because i1 shifts are deleted in SelectionDAG::getNode so computeKnownBits is never called on it.
