### ISSUE TITLE
clang-tidy crash with bugprone-unchecked-optional-access

### ISSUE THREAD

**Issue by t-b** [llvm/llvm-project#74083]
Version: 17.0.6
OS: Debian Linux

clang-tidy crashed and told me to report a bug. I'm attaching the stackdump 
[stack-dump-clang-tidy.txt](https://github.com/llvm/llvm-project/files/13527791/stack-dump-clang-tidy.txt).

**Comment by rsniezek** [comment]
Also have the same crash on the same clang-tidy version, on nixOs. Cannot post backtrace due to legal reasons but here is obfuscated snippet:
`Error running '/nix/store/vywd60v5l52qwlb2ydcnfv29jqyw4l31-clang-tools-17.0.6/bin/clang-tidy': PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0. Program arguments: /nix/store/vywd60v5l52qwlb2ydcnfv29jqyw4l31-clang-tools-17.0.6/bin/clang-tidy -extra-arg=--target=x86_64-linux-gnu -p <path to cmake build dir containing compile_commands.json> --extra-arg-before=--driver-mode=g++ <name of tested file.cpp>
1. <eof> parser at end of file
2. ASTMatcher: Processing 'bugprone-unchecked-optional-access' against:`

**Comment by ymand** [comment]
Do either of you have a repro or a stack trace from a non-opt build? We just recently fixed a crash which might be the same as this one: https://github.com/llvm/llvm-project/pull/84138

Can one or both of you try to repro at HEAD?

**Comment by t-b** [comment]
I'll have a look.

**Comment by t-b** [comment]
No crash with `Debian clang version 18.1.6 (++20240518023133+1118c2e05e67-1~exp1~20240518143227.130)`, thanks for the fix.
