### ISSUE TITLE
Windows `build-id` is non-deterministic

### ISSUE THREAD

**Issue by vszakats** [llvm/llvm-project#74238]
Tried to enable the CET hardening option with
  `clang -fuse-ld=lld -Xlinker -Xlink=-cetcompat -Wl,-s test.c`
for Windows (I used llvm-mingw 20231128 with LLVM 17.0.6). This
automatically enabled a `build-id` segment (normally suppressed by `-Wl,-s`),
which is in turn different for each, otherwise bit-by-bit identical, build. It
suggests that the `build-id` is a random value, not a deterministic hash of
the output like it is for example on Linux.

Is there a way to enable both this hardening feature _and_ making 
reproducible builds on Windows? If not, would it be possible to make
`build-id` deterministic, or disable it with CET?

**Comment by mstorsjo** [comment]
> Tried to enable the CET hardening option with `clang -fuse-ld=lld -Xlinker -Xlink=-cetcompat -Wl,-s test.c` for Windows (I used llvm-mingw 20231128 with LLVM 17.0.6). This automatically enabled a `build-id` segment (normally suppressed by `-Wl,-s`), which is in turn different for each, otherwise bit-by-bit identical, build. It suggests that the `build-id` is a random value, not a deterministic hash of the output like it is for example on Linux.
> 
> Is there a way to enable both this hardening feature _and_ making reproducible builds on Windows? If not, would it be possible to make `build-id` deterministic, or disable it with CET?

I'm not entirely able to reproduce the basic assumptions for the issue here; if I link an executable with `clang -fuse-ld=lld -Wl,-s test.c`, where the output doesn't contain any build id, the output executable differs each time as well. So even without the `-cetcompat` option, the output isn't reproducible.

If we link two such executables, and run `llvm-readobj --file-headers` on them, and diff the output, I get this diff:
```diff
@@ -1,12 +1,12 @@
  
-File: hello1.exe 
+File: hello2.exe
 Format: COFF-x86-64
 Arch: x86_64 
 AddressSize: 64bit 
 ImageFileHeader {
   Machine: IMAGE_FILE_MACHINE_AMD64 (0x8664)
   SectionCount: 7 
-  TimeDateStamp: 2023-12-04 22:19:03 (0x656E5057) 
+  TimeDateStamp: 2023-12-04 22:19:08 (0x656E505C)
   PointerToSymbolTable: 0x0
   SymbolCount: 0
   StringTableSize: 0
```

Thus, even without a build id, the output file contains a timestamp.

On the MinGW linker interface, this timestamp can be overridden by passing `-Wl,--no-insert-timestamp`.

If producing an executable that contains a build id, the build id section also contains a copy of the same timestamp. If we use `--no-insert-timestamp` to force the timestamp to zero, I get reproducible output even without `-Wl,-s`, and even with `-Wl,-Xlink,-cetcompat`.

Thus, I can't reproduce the aspect of the bug that `-cetcompat` or the build id would be more unreproducible than the main PE header itself, which itself is unreproducible out of the box.

On the lld-link interface level (which the LLD mingw linker driver calls internally), this behaviour can be controlled with the option `-timestamp:<n>` (which is what `--no-insert-timestamp` does), or `-Brepro` (which sets the timestamp to a reproducible hash, so the field does change for each unique build) - i.e. you can pass `-Wl,-Xlink,-Brepro` when linking via the mingw linker interface. There's no proper linker option hooked up for this on the malingw interface right now, but if there's an existing precedent for such an option from GNU ld, we could add it.

Ideally, LLD would also respect the https://reproducible-builds.org/docs/source-date-epoch/ `SOURCE_DATE_EPOCH` environment variable for setting timestamps, but currently it doesn't.

See https://github.com/llvm/llvm-project/blob/llvmorg-17.0.6/lld/COFF/Writer.cpp#L1998-L2026 for the logic for setting the timestamp field in the PE header and in the buildid section.

**Comment by vszakats** [comment]
@mstorsjo Thanks for your reply.

I wasn't aware of the `--no-insert-timestamp` option, and also missed that
`build-id` is in fact a copy of the timestamp.

To add some context, the PE header timestamp issue is a decade+-old one, and
I'm resetting it post-build as part of the build process. Also reset it for these tests
while trying to localize the issue. I apologize for leaving this fact out from the report.
(FWIW I'm resetting it to reference timestamp (aka `SOURCE_DATE_EPOCH`)
coming from the source code, instead of zero, to be on the safe side.)

I can confirm `--no-insert-timestamp` works, and I'm happy to use it to work this
around, but, that leaves the question why CET is force-enabling `build-id`? Is it
required for CET to work correctly? Is it safe to use a zero `build-id`? If that's 
the case, does CET need to add a `build-id`?

If it needs a unique `build-id`, I'd go with `-Wl,-Xlink,-Brepro` or possibly
`-Wl,-Xlink,-timestamp:<n>` for the least amount of friction.

Thanks for the useful pointers, I'm looking into them!

**Comment by mstorsjo** [comment]
> @ZequanWu is this related to recent changes?

No, I don't think so.

> I wasn't aware of the `--no-insert-timestamp` option, and also missed that `build-id` is in fact a copy of the timestamp.
> 
> To add some context, the PE header timestamp issue is a decade+-old one, and I'm resetting it post-build as part of the build process. Also reset it for these tests while trying to localize the issue. I apologize for leaving this fact out from the report. (FWIW I'm resetting it to reference timestamp (aka `SOURCE_DATE_EPOCH`) coming from the source code, instead of zero, to be on the safe side.)

Right, I see! Yeah that was kinda vital context for understanding the scope of the bug report :-)

Strictly speaking, I guess whatever tool you use for resetting the PE header timestamp could/should be extended to also update the corresponding timestamp in the build id section? (It can either be in a separate section, or somewhere in `.rdata` - in either case it's pointed to by the debug directory in the PE header.)

> I can confirm `--no-insert-timestamp` works, and I'm happy to use it to work this around, but, that leaves the question why CET is force-enabling `build-id`? Is it required for CET to work correctly? Is it safe to use a zero `build-id`? If that's the case, does CET need to add a `build-id`?
> 
> If it needs a unique `build-id`, I'd go with `-Wl,-Xlink,-Brepro` or possibly `-Wl,-Xlink,-timestamp:<n>` for the least amount of friction.

Looking at a2923b2a1e4536dd14e93bed5c1306e0e54d5304, it looks like CET is signaled via extended DLL characteristics which are included in the debug directory. So the ID/timestamp contents of the build id isn't really relevant, it just needs to exist.

And secondly, even if you use `--no-insert-timestamp` to set a zero timestamp, that's only for the timstamp field, the build ID also has an actual ID field (which is a hash of the binary unless you're creating a real PDB), which still would be nonzero.

**Comment by vszakats** [comment]
> Strictly speaking, I guess whatever tool you use for resetting the PE header timestamp could/should be extended to also update the corresponding timestamp in the build id section? (It can either be in a separate section, or somewhere in `.rdata` - in either case it's pointed to by the debug directory in the PE header.)

Rather than extending my patching, I think I can rely on `--no-insert-timestamp`
to zero out everything it knows about and myself patching the "main" timestamps
to the stable reference one.

Finding it in other places, esp. inside segment content, seems like a separate
undertaking altogether :)

This produces reproducible, CET-enable output in my tests:
```
x86_64-w64-mingw32-clang -fuse-ld=lld -fcf-protection=full -Xlinker -Xlink=-cetcompat \
  -Wl,--no-insert-timestamp test.c
```

I'm post-processing it with [`pefile`](https://pefile.readthedocs.io/en/latest/modules/pefile.html) via [this script](https://github.com/curl/curl-for-win/blob/78b35d85183b7aaf752a0e2ea737bdea1cdf3b6f/_peclean.py#L27-L35) to retrofit the reference timestamp.

Alternatively this, that gets the debug timestamps correct too, but needs to
be set on a per-target basis to have each target's reference timestamp right:
```
x86_64-w64-mingw32-clang -fuse-ld=lld -fcf-protection=full -Xlinker -Xlink=-cetcompat \
  "-Wl,-Xlink,-timestamp:$(TZ=UTC stat -f '%m' test.c)" test.c  # BSD stat
```

> Looking at [a2923b2](https://github.com/llvm/llvm-project/commit/a2923b2a1e4536dd14e93bed5c1306e0e54d5304), it looks like CET is signaled via extended DLL characteristics which are included in the debug directory. So the ID/timestamp contents of the build id isn't really relevant, it just needs to exist.
> 
> And secondly, even if you use `--no-insert-timestamp` to set a zero timestamp, that's only for the timstamp field, the build ID also has an actual ID field (which is a hash of the binary unless you're creating a real PDB), which still would be nonzero.

Thanks!

Unless you spot some fault in my approach (or something to improve!), 
I think we can close this.
