### ISSUE TITLE
[Flang][OpenMP] Incorrect execution result of using statement function in task construct

### ISSUE THREAD

**Issue by ohno-fj** [llvm/llvm-project#74273]
```
Version of flang-new : 18.0.0(770dc47659d41a5ca7b7daf5b3134c900ca8c33d)
```

When `statement function` is used within `task` construct, such as in an attached program, the value of the variable (iaa) used in `statement function` does not look like `firstprivate` after `task` construct ends.
If a function is used directly instead of `statement function`, the value of the variable is correct.

The following are the test program, Flang-new, Gfortran and ifort compilation/execution result.

:
```fortran
program main
  integer prv
  if(i)=ifun(iaa)
  prv=1; iaa=1; ii=1
!$omp parallel shared(prv)
!$omp task default(firstprivate)
  prv = prv + 1
  ii=if(ii)
!  ii=ifun(iaa)  ! OK if not statement function
!$omp end task
  write(6,*) "prv = ", prv, " iaa = ", iaa
  if (iaa.ne.1) write(6,*) "NG : iaa = ", iaa
!$omp end parallel
end program main

function ifun(j)
  j=100; ifun=1
end function ifun
```

```
$ export OMP_NUM_THREADS=2; flang-new -fopenmp snf_emski_omp_01_2.f90; ./a.out
 prv =  1  iaa =  1
 prv =  1  iaa =  100
 NG : iaa =  100
$
```

```
$ export OMP_NUM_THREADS=2; gfortran -fopenmp snf_emski_omp_01_2.f90; ./a.out
 prv =            1  iaa =            1
 prv =            1  iaa =            1
$
```

```
$ export OMP_NUM_THREADS=2; ifort -qopenmp snf_emski_omp_01_2.f90; ./a.out
 prv =            1  iaa =            1
 prv =            1  iaa =            1
$
```

**Comment by kiranchandramohan** [comment]
Implementation of task constructs is not complete. Issues are expected. There is a review of firstprivatisation for tasks.

**Comment by luporl** [comment]
This issue is likely happening because the use of `iaa`, inside the task construct, is hidden in the `statement function`'s expression.
Because of this, the collection of default symbols to privatize in lowering is missing the `iaa` variable.

A possible way to handle this case, without changing the current implementation too much, would be to locate `statement functions` in OpenMP constructs and add their non-argument references to the list of symbols to be privatized.
