### ISSUE TITLE
wasm-ld will introduce `memcpy` for const char* copy when `--target=wasm32 -nostdlib`

### ISSUE THREAD

**Issue by HerrCai0907** [llvm/llvm-project#74278]
```c
extern int foo(const char *payloadPtr, int payloadSize);

void _start() {
  const char msg[] = "_________________________________________________________________________________________________"
                     "____________________";
  foo(msg, sizeof(msg));
}
```
It will be compiled as following which introduce `env::memcpy`
```
  (import "env" "memcpy" (func $memcpy (type 0)))
  (import "env" "foo" (func $foo (type 1)))
```

**Comment by sbc100** [comment]
I'm pretty sure this isn't the linker doing this, but the compiler.   If you build the source file to a `.o` I believe you will see the call the memcpy.    If you build with `-nostdlib` then its up to you to define things that would otherwise be defined by compiler-rt, including memcpy.   
From the gcc man page:

```
       The compiler may generate calls to "memcmp", "memset", "memcpy" and "memmove".
       These  entries  are  usually  resolved by entries in libc.  These entry points
       should be supplied through some other mechanism when this option is specified.
```

**Comment by sbc100** [comment]
I don't think `-fno-builtin` effects the use of `memcpy` in cases like this.

Building the above code with `-fno-builtin` still generated a called to an imported memcpy function in the object file.
