### ISSUE TITLE
[ThinLTO] Possible missed import of functions for indirect-call-promotion when linkage-name differs from mangled-name for local-linkage functions 

### ISSUE THREAD

**Issue by minglotus-6** [llvm/llvm-project#74565]
[Global identifiers](https://github.com/llvm/llvm-project/blob/41507fe595d0fa3d81e151d70431d51897f8d14d/llvm/lib/IR/Globals.cpp#L144-L166) has the format `[filename:]<mangled-name>`, and its MD5 hash are known as GUIDs to compute the import of referenced symbols in ThinLTO.

When the referenced symbols is a callee of indirect call (whether the callee is in the same IR module as caller, or from a different IR module), the reference edge comes from PGO profiles as the MD5 hash of IRPGO function names, which has the format `[filename;]<linkage-name>` ([more details](https://github.com/llvm/llvm-project/blame/fe051934cbb0aaf25d960d7d45305135635d650b/llvm/lib/ProfileData/InstrProf.cpp#L278-L302))

[PR/74008](https://github.com/llvm/llvm-project/pull/74008) would update the delimiter to be `;`, but it doesn't fix the case when `<mangled-name>` and `<linkage-name>` are different. Note `[filename;]` prefix exists for local-linkage functions only, while the difference of `<mangled-name>` and `<linkage-name>` _might_ exist for external functions according to the [Mangler](https://github.com/llvm/llvm-project/blob/9bad6cb7fc571821bfacc8926a8a7f5d147ce540/llvm/lib/IR/Mangler.cpp#L119) impl.
 
Looking at the code ([Mangler](https://github.com/llvm/llvm-project/blob/06c5c27e44757e4917f7d7c995720ae8a2d3b1f9/llvm/lib/ProfileData/InstrProf.cpp#L307) used to compute IRPGO names), `<linkage-name>` (e.g., considering [linkage](https://github.com/llvm/llvm-project/blob/cf1a979ccfa722c3f9fce28c66c13a222990eac4/llvm/lib/IR/Mangler.cpp#L123-L127) and [calling-convention](https://github.com/llvm/llvm-project/blob/cf1a979ccfa722c3f9fce28c66c13a222990eac4/llvm/lib/IR/Mangler.cpp#L148-L166)) and `<mangled-name>` (e.g., emitted by Clang for C++) _could_ be different. This difference means possible missed import of functions as indirect-call-promotion callees (or when reference edge needs to be deduced from raw profiles using a similar approach to ICP).

Create this issue so the missed import issue (and thereby missed opt) is tracked.

**Comment by minglotus-6** [comment]
> Could you create a small test case of the missed ICP callees? It would really help me understand the problem.

Test case Transforms/PGOProfile/thinlto_indirect_call_promotion.ll in [PR/74008](https://github.com/llvm/llvm-project/pull/74008) showcases one type of missed function import when semicolon/colon cause MD5 hash differences between pgo func names and global identifiers. Hopefully this showcases the problem how missed imports happens.

The key thing in getting a test case here is to get a executable (thereby raw profiles) where a function's `linkage-name` differs from `mangled-name`, which would cause a missed import.

Some findings while trying to do construct a test case:
- Getting an indirect callee with specially-handled MS functions would be a start step (inferring from [mangler implementation](https://github.com/llvm/llvm-project/blob/13b88265088329decd15449e3b2461a6177174b2/llvm/lib/IR/Mangler.cpp#L119-L185)). 
- Clang frontend uses [private linkage](https://github.com/llvm/llvm-project/blob/13b88265088329decd15449e3b2461a6177174b2/llvm/include/llvm/IR/GlobalValue.h#L56) mainly for global variables (not functions), so it'd be tricky to get a C++ executable with private-linkage function IR (from my attempt to reverse-engineer how to do so, so take this with a grain of salt).

I'm wondering if you come across source code examples where IR functions are generated with private linkage (therefore difference between mangled name and linkage-name) in objective-c++ or swift (for the function-ordering use case). If yes, that could be a start to construct the test case.

> Also, I think you have some typos that I'm a bit confused about: "...it doesn't fix the case when and are different", "while the difference of and might exist".

Fixed it now (It seems content inside a pair of angled bracket (i.e., < >) won't render but surrounding them with backticks would.)

**Comment by ellishg** [comment]
> Fixed it now (It seems content inside a pair of angled bracket (i.e., < >) won't render but surrounding them with backticks would.)

Ah I see. I hope you don't mind I fixed this in other areas too.

**Comment by minglotus-6** [comment]
>  I fixed this in other areas too.

Of course not. Thanks for the correction!

**Comment by minglotus-6** [comment]
I took another attempt only to find out it isn't very practical to synthesis an executable that contains functions with [specific microsoft-faststdcall-mangling](https://github.com/llvm/llvm-project/blob/185302530847a28f44e48a67a79fd4eba048a1c7/llvm/lib/IR/Mangler.cpp#L158-L160), on many (x86-64 or arm64) windows machines.

Here are some uninteresting details and how I come to this finding
- The `\01` prefix is added for a simple function from MinGW clang (https://godbolt.org/z/49Kxq95q9) and this `\01` prefix is supposed to [prevent](https://github.com/llvm/llvm-project/blob/185302530847a28f44e48a67a79fd4eba048a1c7/llvm/lib/IR/Mangler.cpp#L152) IRMangler from further name mangling.  Functions compiled for some 32-bit windows machine (https://godbolt.org/z/vW61KaPjb) doesn't have `\01` prefix but not sure how easy it is to access these machines (not familiar myself) 
- Looking at clang/lib/AST/Mangle.cpp, `\01` prefix will be added iff target-specific UserLabelPrefix is not empty ([source code](https://github.com/llvm/llvm-project/blob/185302530847a28f44e48a67a79fd4eba048a1c7/clang/lib/AST/Mangle.cpp#L155-L170)).
- Looking at clang/lib/Basic/Targets/X86.h and clang/lib/Basic/Targets/AArch64.cpp, quite many windows 64-bit targets sets the UserLabelPrefix to non-empty strings (examples for [x86_64darwin](https://github.com/llvm/llvm-project/blob/185302530847a28f44e48a67a79fd4eba048a1c7/clang/lib/Basic/Targets/X86.h#L934) and [arm64](https://github.com/llvm/llvm-project/blob/185302530847a28f44e48a67a79fd4eba048a1c7/clang/lib/Basic/Targets/AArch64.cpp#L1464)), meaning functions compiled for these machines would have the `\01` prefix and will not be mangled by IR Manger :(

**Comment by ellishg** [comment]
Based on our discussion in https://github.com/llvm/llvm-project/pull/74008#discussion_r1416305096 it seems like one solution could be to change `GlobalValue::getGlobalIdentifier()` to use linkage names like we do in `InstrProf::getIRPGOFuncName()`. But we can't use `Mangler().getNameWithPrefix()` directly because this callsite does not have the `GV`.
https://github.com/llvm/llvm-project/blob/d6fbd96e5eaf3e8acbf1b43dce7a311352907567/llvm/lib/Bitcode/Reader/BitcodeReader.cpp#L6763

It does, however, have the linkage. After briefly looking at `Mangler::getNameWithPrefix()`, I suspect that we can cover 99% of cases with this info.
https://github.com/llvm/llvm-project/blob/1638657dce0ca03c7d5cd9dfc23bf31485b4ac43/llvm/lib/IR/Mangler.cpp#L119-L184

So my main question is: are we ok with changing the behavior of `GlobalValue::getGlobalIdentifier()` to use linkage names?

**Comment by minglotus-6** [comment]
I think changing `GlobalValue::getGlobalIdentifier` to use linkage names makes sense. The existing callers use `getGlobalIdentifier` to get a unique name (and sometimes compute a GUID from the name), but they don't depend on the name being `<mangled-name>`.

**Comment by ellishg** [comment]
I had hoped that we could pass a `DataLayout` to `GlobalValue::getGlobalIdentifier()` so we can get the `<linkage-name>`. Unfortunately this seems very difficult because the callsite at `ModuleSummaryIndexBitcodeReader::setValueGUID()` does not have a way to access a `DataLayout`, even though we do save the TargetTriple a bit up the callstack in `ThinLTOCodeGenerator`.

**Comment by ellishg** [comment]
I'm not sure of a good path forward, but I'll list some options I can think of.
1. We change `GlobalValue::getGlobalIdentifier()` to use a linkage name instead of a mangled name. Like I said above, this requires accessing the `DataLayout` from `ModuleSummaryIndexBitcodeReader::setValueGUID()` somehow.
2. We intercept the value profile function name before we compute the GUID and convert the linkage name to a mangled name. GUIDs would remain the same, but global identifiers in IRPGO profiles would still use linkage names.
3. We revert IRPGO profiles back to using mangled names. `llvm-profdata order` would stop working because profiles don't record function linkage types and we won't be able to convert mangled names to linkage names. This is required because `lld`/`ld64` expects linkage names to be passed via `--symbol-ordering-file`/`-order-file`.
  3 a. A workaround could be to teach `lld`/`ld64` to ignore some prefixes (`_`, `l_`, etc) in the orderfile, but I'm not sure if this would break existing use cases.
  3 b. We could also add an option for IRPGO to use linkage names instead of mangled names and users would have to understand that this breaks value profiling.
