### ISSUE TITLE
[driver] clang++ should accept -R argument (at least on FreeBSD)

### ISSUE THREAD

**Issue by yurivict** [llvm/llvm-project#7478]
|  |  |
| --- | --- |
| Bugzilla Link | [7106](https://llvm.org/bz7106) |
| Version | 2.7 |
| OS | FreeBSD |
| CC | @DougGregor |

## Extended Description 
I got this warning:
clang: warning: argument unused during compilation: '-R/usr/local/binutils/2.20/lib'

gcc accepts -R and passes it to linker (as -rpath parameter?)
clang++ should do the same.

**Comment by widberg** [comment]
Four years after this issue was opened, commit https://github.com/llvm/llvm-project/commit/3be1cb294f328f03afcb9c9e039b078a8643d0d9 added the `-R` flag for enabling remarks. In GCC `-R` appears to be equivalent to `-Wl,rpath=` on `freebsd2.2*`, `freebsd*`, `netbsd*`, some `openbsd*`s, and `solaris*` according to [GCC's config.rpath](https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=config.rpath;h=4dea75957c2b81f963186d84aad76dfe1ce5195c;hb=HEAD). Since Clang already has a different use for `-R`, `-Wl,rpath=` is supported by both Clang and GCC to pass an `rpath` argument to the linker, and `-R` support isn't consistent across platforms on GCC I'm not sure what value there is in leaving this issue open.

**Comment by MaskRay** [comment]
Thanks for the detailed analysis. `-R` on FreeBSD is perhaps a legacy option that has been cleaned up and has long been irrelevant.
