### ISSUE TITLE
ld.lld linker error on gz_intmax like symbol not defined

### ISSUE THREAD

**Issue by lonewolf73** [llvm/llvm-project#75056]
Hello everyone!

I have ubuntu 22.04 LTS with : 
1) **Android SDK**        -->   **release 8.1.0 (AndroidVersion.ApiLevel=27);** 
2) **Android NDK**       -->   **release 26.1.1090912**5
3) **sources of vlc library** 

trying to compile vlc library returns error on : 

```
[1/15] Linking C shared library libzlib.so.1.2.13
FAILED: libzlib.so.1.2.13
: && /usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android27-clang -fPIC -g -O2 -fPIC -fdata-sections -ffunction-sections -funwind-tables  -fstack-protector-strong -no-canonical-prefixes -DNDEBUG  -I/home/dev/projects/libvlcjni/buildsystem/vlc/contrib/aarch64-linux-android/include -g -O2 -O2 -g -DNDEBUG  -L/home/dev/projects/libvlcjni/buildsystem/vlc/contrib/aarch64-linux-android/lib  -Wl,--version-script,"/home/dev/projects/libvlcjni/buildsystem/vlc/contrib/contrib-android-aarch64-linux-android/zlib/zlib.map" -shared -Wl,-soname,libzlib.so.1 -o libzlib.so.1.2.13 CMakeFiles/zlib.dir/adler32.o CMakeFiles/zlib.dir/compress.o CMakeFiles/zlib.dir/crc32.o CMakeFiles/zlib.dir/deflate.o CMakeFiles/zlib.dir/gzclose.o CMakeFiles/zlib.dir/gzlib.o CMakeFiles/zlib.dir/gzread.o CMakeFiles/zlib.dir/gzwrite.o CMakeFiles/zlib.dir/inflate.o CMakeFiles/zlib.dir/infback.o CMakeFiles/zlib.dir/inftrees.o CMakeFiles/zlib.dir/inffast.o CMakeFiles/zlib.dir/trees.o CMakeFiles/zlib.dir/uncompr.o CMakeFiles/zlib.dir/zutil.o   && :
ld.lld: error: version script assignment of 'local' to symbol 'gz_intmax' failed: symbol not defined
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

where if I do a grep on gz_intmax I can see it's present in : 

```
vlc/contrib/contrib-android-aarch64-linux-android/zlib/zlib.map:    gz_intmax;
vlc/contrib/contrib-android-aarch64-linux-android/zlib/gzguts.h:unsigned ZLIB_INTERNAL gz_intmax OF((void));
vlc/contrib/contrib-android-aarch64-linux-android/zlib/gzguts.h:#  define GT_OFF(x) (sizeof(int) == sizeof(z_off64_t) && (x) > gz_intmax())
vlc/contrib/contrib-android-aarch64-linux-android/zlib/zconf.h.in:#    define gz_intmax             z_gz_intmax
vlc/contrib/contrib-android-aarch64-linux-android/zlib/vlc_build/zconf.h:#    define gz_intmax             z_gz_intmax
vlc/contrib/contrib-android-aarch64-linux-android/zlib/gzlib.c:unsigned ZLIB_INTERNAL gz_intmax()
vlc/contrib/contrib-android-aarch64-linux-android/zlib/zconf.h.included:#    define gz_intmax             z_gz_intmax
vlc/contrib/contrib-android-aarch64-linux-android/zlib/zconf.h.cmakein:#    define gz_intmax             z_gz_intmax
vlc/contrib/contrib-android-aarch64-linux-android/freetype/src/gzip/ftzconf.h:#    define gz_intmax             z_gz_intmax
vlc/contrib/contrib-android-aarch64-linux-android/freetype/src/gzip/gzguts.h:unsigned ZLIB_INTERNAL gz_intmax OF((void));
vlc/contrib/contrib-android-aarch64-linux-android/freetype/src/gzip/gzguts.h:#  define GT_OFF(x) (sizeof(int) == sizeof(z_off64_t) && (x) > gz_intmax())
```

so as like as I followed the discussion inside comment on _LLD --no-undefined-version_  , is that error I am getting related to _--no-undefined-version_ ? If yes, where I could add _--undefined-version_ to revert to old behavior? 

Thanks! 
Cheers!

**Comment by DimitryAndric** [comment]
It is likely that the actual existence of `gz_intmax` in any of your object files is dependent on configuration, compile flags, environment, platform, or something else. If the symbol does not exist, lld complains about it by default. If you don't care about those missing symbols, add `-Wl,--undefined-version` to your linker flags. If you do care about those missing symbols, either implement them (exercise left for the reader), or delete them from the linker version script.

**Comment by mtl1979** [comment]
`gz_intmax` is not needed or defined in zlib for modern compilers. It has been very common practice to use just one symbol map or version script for all environments, as using separate for each toolchain/configuration combination would exponentially increase the effort to keep them all updated and synchronized.

There is chicken and egg dilemma when checking the sanity of toolchain and creating customized symbol map or version script as it would require testing the toolchain (specifically linker) twice, once with dummy version, and then with the real one.

As VLC already patches the zlib sources, it would be best solution to just strip the symbol definition from the version script.

Biggest problem with zlib since early days has been that it's supposed to support very old compilers and toolchains, so it really does very little effort to support all the intricacies of modern toolchains (especially for 64-bit targets). That is also why few years ago forks were started that focus on supporting modern toolchains instead.
