### ISSUE TITLE
[Offload] Create a PR to move /openmp/libomptarget to /offload

### ISSUE THREAD

**Issue by jdoerfert** [llvm/llvm-project#75124]

**Comment by sylvestre** [comment]
FYI, it caused a few regressions:
https://github.com/llvm/llvm-project/issues/90707
https://github.com/llvm/llvm-project/issues/91881
https://github.com/llvm/llvm-project/issues/91819
https://github.com/llvm/llvm-project/issues/90769
https://github.com/llvm/llvm-project/issues/90708

It has been blocking updating apt.llvm.org since it landed
