### ISSUE TITLE
[CUDA]attribute inherit in template function specialization

### ISSUE THREAD

**Issue by yuyuyu-atri** [llvm/llvm-project#75292]
```
template <typename T>

__device__ T f()
{

  return 1;
  
};

template <>

__host__ int f<int>()

{

  return 0;
}
```
`nvcc` can compile the code above, but `clang` will report an error `"no function template matches function template specialization"`.
`f()`  will have both `__host__` and `__device__` attributes for `int` but only `__host__` for other types in nvcc.
Is it possible to correspond to `nvcc`?

**Comment by Neumann-A** [comment]
Isn't that documented in https://llvm.org/docs/CompileCudaWithLLVM.html and is related how the function signature is different for clang compared to nvcc? ([described here https://llvm.org/docs/CompileCudaWithLLVM.html#id13](https://llvm.org/docs/CompileCudaWithLLVM.html#overloading-based-on-host-and-device-attributes))
```
template <typename T>
__device__ T f()
```
is simply unrelated to 
```
template <>
__host__ int f<int>()
```
for clang since the template function signature is completly different.

Doesn't just adding:
```
template <typename T>
__host__ T f()
```
fix it for clang?

**Comment by yuyuyu-atri** [comment]
> Isn't that documented in https://llvm.org/docs/CompileCudaWithLLVM.html and is related how the function signature is different for clang compared to nvcc? ([described here https://llvm.org/docs/CompileCudaWithLLVM.html#id13](https://llvm.org/docs/CompileCudaWithLLVM.html#overloading-based-on-host-and-device-attributes))
> 
> ```
> template <typename T>
> __device__ T f()
> ```
> 
> is simply unrelated to
> 
> ```
> template <>
> __host__ int f<int>()
> ```
> 
> for clang since the template function signature is completly different.
> 
> Doesn't just adding:
> 
> ```
> template <typename T>
> __host__ T f()
> ```
> 
> fix it for clang?

Sorry for that I didn't search the document carefully. Now I get it. Thanks.
