### ISSUE TITLE
[early-cse] Assertion failed: BitWidth == RHS.getBitWidth() && !LHS.hasConflict() && !RHS.hasConflict() && "Operand mismatch"

### ISSUE THREAD

**Issue by RKSimon** [llvm/llvm-project#75505]
Reduced from https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=64842
```ll
define void @vselect1(i32 %a.coerce, i32 %c.coerce) {
entry:
  %0 = bitcast i32 %a.coerce to <2 x i16>
  %I3 = insertelement <2 x i16> %0, i16 -1, i1 false
  %E1 = extractelement <2 x i16> %I3, i1 false
  %I1 = insertelement <2 x i16> poison, i16 %E1, i1 false
  %B24 = mul <2 x i16> %I3, %I1
  %1 = bitcast <2 x i16> %B24 to i32
  %B12 = sdiv i32 %c.coerce, %c.coerce
  %B16 = lshr i32 %B12, %1
  store i32 %B16, ptr poison, align 4
  ret void
}
```

**Comment by nikic** [comment]
Reduced:
```llvm
define i32 @test(<2 x i16> %a, i32 %b) {
  %mul = mul <2 x i16> %a, <i16 -1, i16 poison>
  %bc = bitcast <2 x i16> %mul to i32
  %lshr = lshr i32 %b, %bc
  ret i32 %lshr
}
```
The problem is that https://github.com/llvm/llvm-project/blob/11141bc68adc311afad1ff130e4fbbd1e3062e05/llvm/lib/Analysis/ValueTracking.cpp#L1836 will produce a conflict if all demanded elements are poison.

This would be easy enough to fix, but at this point I'm thinking we may be better off removing all of these conflict assertions. Conflicting known bits have a well-defined meaning of representing a poison value, we should just accept that.
