### ISSUE TITLE
Freestanding components of the C++ standard library should be buildable when libc isn't available

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#77373]
In order to do this, we need to:

* reach consensus on what "freestanding" means
* describe a policy document (assignee: @cjdb)
* make changes to libc++, libc++abi, and possibly Clang to support

**Comment by ldionne** [comment]
Some folks seem to equate freestanding with "not having a C library". That isn't how I see things -- Freestanding is for when there is no significant runtime support available (for example, `printf` isn't there). However, there's no reason why even a kernel environment wouldn't provide a `<stddef.h>` header with stuff like `size_t` or even `<string.h>` with an implementation of `memcpy`. For me, freestanding is not a distinction between "there's a C library or there isn't" -- it's a distinction between "I have a lot of runtime support" and "I don't".

I believe the only thing we'd achieve by making libc++ not require a C library in Freestanding mode is that it would be more user friendly for vendors to create a libc++ for Freestanding, since they wouldn't need to build a C library first. But then there could be an issue in case a platform does have a C library in Freestanding mode, and libc++ tries to implement stuff like `<stddef.h>` itself instead.

Overall, I think that providing an easy way to build LLVM libc for freestanding environments, and then making sure that libc++ works on top of that, would be a better alternative. Just my .02, curious to hear what folks think.

**Comment by trcrsired** [comment]
i've checked libstdc++. they haven't yet provided cerrno in freestanding.
```
$ ls
algorithm  backward  bitset   compare    cstdalign  cstddef  cxxabi.h   expected    generator         limits  numbers   ranges            source_location  tuple        typeinfo  version
array      bit       cfloat   concepts   cstdarg    cstdint  debug      ext         initializer_list  memory  numeric   ratio             span             type_traits  utility   x86_64-elf
atomic     bits      climits  coroutine  cstdbool   cstdlib  exception  functional  iterator          new     optional  scoped_allocator  string_view      typeindex    variant
```

**Comment by trcrsired** [comment]
My definition is the libcxx headers need an option to be built without libc. Not the runtime part.

C imports just define them as extern "C" functions

**Comment by cjdb** [comment]
> Some folks seem to equate freestanding with "not having a C library". That isn't how I see things -- Freestanding is for when there is no significant runtime support available (for example, `printf` isn't there). However, there's no reason why even a kernel environment wouldn't provide a `<stddef.h>` header with stuff like `size_t` or even `<string.h>` with an implementation of `memcpy`. For me, freestanding is not a distinction between "there's a C library or there isn't" -- it's a distinction between "I have a lot of runtime support" and "I don't".

I largely agree with this take. I renamed the issue to say "libc" as opposed to "C standard library", since libc is an artefact of engineering processes, and the C standard library is what ships with a C implementation. libc++ is a part of "the implementation", as is libc, but they're separate due to a separation of concerns. I don't agree with the sentiment that freestanding is not having a C standard library.

> I believe the only thing we'd achieve by making libc++ not require a C library in Freestanding mode is that it would be more user friendly for vendors to create a libc++ for Freestanding, since they wouldn't need to build a C library first. But then there could be an issue in case a platform does have a C library in Freestanding mode, and libc++ tries to implement stuff like `<stddef.h>` itself instead.
> 
> Overall, I think that providing an easy way to build LLVM libc for freestanding environments, and then making sure that libc++ works on top of that, would be a better alternative. Just my .02, curious to hear what folks think.

If we go down this path, then perhaps we could have a config option such as `RUNTIMES_BUILD_FREESTANDING` that builds both llvm-libc and libc++ in freestanding mode, and forces libc to be built prior to libc++.

I think `clang++ -ffrestanding` is also a reasonable approach. We could require the implementation to have a freestanding libc implementation in order for this to work. That would require some coordination with other parts of the implementation so that the headers are correct, and we might need something like `libc_freestanding.a`, but I see a path forward there.

**Comment by ldionne** [comment]
@trcrsired 
> My definition is the libcxx headers need an option to be built without libc. Not the runtime part.

As mentioned by @jyknight, this doesn't work. Being freestanding and needing to build + link against a `libc++.a` library are two independent things. Proper usage of libc++ requires linking against a built library (either `libc++.so` or `libc++.a`), regardless of whether we're in freestanding mode or not. For example, we have external instantiations of `std::sort` in the built library and your code won't work if you try to use some forms of `std::sort(...)` without linking against the built library.

Since we mostly seem to agree about the fact that removing the dependency on a C Standard Library is a non-goal, I am not certain what action item(s) this issue tracks. @cjdb Do you have something in mind when you mention removing the dependency on "libc" as opposed to a "C Standard Library"? I think we already don't have a dependency on any particular C library implementation -- we just need some implementation to be available.

**Comment by trcrsired** [comment]
> @trcrsired
> 
> > My definition is the libcxx headers need an option to be built without libc. Not the runtime part.
> 
> As mentioned by @jyknight, this doesn't work. Being freestanding and needing to build + link against a `libc++.a` library are two independent things. Proper usage of libc++ requires linking against a built library (either `libc++.so` or `libc++.a`), regardless of whether we're in freestanding mode or not. For example, we have external instantiations of `std::sort` in the built library and your code won't work if you try to use some forms of `std::sort(...)` without linking against the built library.
> 
> Since we mostly seem to agree about the fact that removing the dependency on a C Standard Library is a non-goal, I am not certain what action item(s) this issue tracks. @cjdb Do you have something in mind when you mention removing the dependency on "libc" as opposed to a "C Standard Library"? I think we already don't have a dependency on any particular C library implementation -- we just need some implementation to be available.

I have previously addressed the std::sort issue in libc++ by implementing a patch that disables it when operating in a freestanding environment, as it is a unique issue specific to libc++. Providing headers unconditionally is necessary to avoid circular dependency issues, such as how one could utilize freestanding C++ to implement a custom libc.

The coverage of libc poses a challenge, as it is an integral part of an operating system, and libcxx cannot feasibly support all existing operating systems. There are over 50 diverse libc implementations, some of which are crafted in C++. Some the libcs are even unusable by a C++ compiler (like libcs in PDP11) since they were written in K&R C. Without the provision of headers, implementing hosted features becomes impractical. If you just provide headers, at least they have a chance to use C++ to rewrite that part to make it work.

You are not solving the issues, or people won't have hacks like cxxshim (https://github.com/managarm/cxxshim) which is totally non standardized, but they have to because even std::addressof, std::move are not provided. Rewriting things like std::move creates tons of issues for portability issues. (Ben Craig mentioned that before)

It appears that the developers of libcxx may not have personally encountered these issues or possess a deep understanding of them. This is acceptable, and that's why individuals with the requisite expertise can contribute to maintaining this aspect of the codebase.

**Comment by jyknight** [comment]
"Freestanding" has an actual definition in the standards now, which I thought was what we were discussing.

But, I think you may be asking about something more minimal than the standardized "Freestanding" mode -- just the core language support functions. Such a mode may indeed be useful, but someone would have to define it, since it's not defined by the standard.

And libc++ already has work to do in order to implementing the standardized freestanding mode.

**Comment by nickdesaulniers** [comment]
> There are over 50 diverse libc implementations I knew, some of which are crafted in C++

Such as llvm's own [libc](https://libc.llvm.org/) or Android's Bionic [libc](https://android.googlesource.com/platform/bionic/+/refs/heads/main/)

This is already possible today to implement a libc in other languages, such as C++, though doing so typically involves avoidance of C++'s std library.

This dir contains re-implementations of useful parts of the C++ standard library that are used in llvmlibc:
https://github.com/llvm/llvm-project/tree/main/libc/src/__support/CPP

Notice how the codebase intentionally avoids the use of the C++ std library, while making use of C++ language features and providing its own implementation of similar-ish functionality to the std library when necessary.

> That isn't how I see things -- Freestanding is for when there is no significant runtime support available (for example, printf isn't there).
> While "freestanding" was formerly colloquially defined as "no runtime libraries required", it's now a standardized concept, and certainly does require a set of library functions.

I find GCC's [docs](https://gcc.gnu.org/onlinedocs/gcc/Standards.html) on this helpful.

> The ISO C standard defines (in clause 4) two classes of conforming implementation. A conforming hosted implementation supports the whole standard including all the library facilities; a conforming freestanding implementation is only required to provide certain library facilities ...
> The standard also defines two environments for programs, a freestanding environment, required of all implementations and which may not have library facilities beyond those required of freestanding implementations, where the handling of program startup and termination are implementation-defined; and a hosted environment ...
> GCC requires the freestanding environment provide memcpy, memmove, memset and memcmp.

---
> i've checked libstdc++. they haven't yet provided cerrno in freestanding.

Where are you running `ls` (it's unclear from your comment).  Are you pointing to some notion that libstdc++ has but libc++ does not?

---

Taking a step back, @trcrsired can you tell us a little more about your use case?

It sounds like you're trying to use the C++ standard library while compiling with `-ffreestanding`?  In that case, I'd imagine perhaps there are some parts of the standard library that are header-only and don't actually require linking against any library to provide implementations?

> My definition is the libcxx headers need an option to be built without libc. Not the runtime part.

I suspect that the result would be an incomplete C++ standard library.  How does iostream interact with the platform in that case, for example?

Doesn't libc++ currently depend on locale information from the libc? I'm trying to remember why `DLIBCXX_HAS_MUSL_LIBC` is a thing.

**Comment by ldionne** [comment]
@cjdb 
> Good question. The problem---as reported in Discord---led me to believe that libc++ looks for the existence of _a_ libc, which you seem to agree is the case. The chatter from @jyknight to here has convinced me that we might not need to do much at all.

We require a C Standard Library to exist underneath so we can `#include_next` some of its headers, which are required to define things such as `size_t`, `memcpy` and some more. We don't actually require that much from such a library, but we do require a bit.

> Before closing this issue, I'd like to discuss whether it would be good to get `-ffreestanding` to define a `__FREESTANDING__` macro that all implementations can use. That would give everyone a common vocab.

This is already the case, although it's done a bit differently. Clang defines `__STDC_HOSTED__` to `1` all the time, but if you pass `-ffreestanding` then it defines it to `0` instead. That is how we set the `_LIBCPP_FREESTANDING` macro in `__config`, although that macro is barely used if at all.

@trcrsired 
> It appears that the developers of libcxx may not have personally encountered these issues or possess a deep understanding of them. This is understandable, and that's why individuals with the requisite expertise can contribute to maintaining this aspect of the codebase.
> 
> Every time I talked about this issue, it seems that some of the libcxx devs behave quite angry for some reasons. I do not know why, probably because they do not work in those environments directly. However, now it is at least better since we can have discussion now.

I have personally done the work to set up libc++ on various "unusual" platforms, all of which don't implement a full C Standard Library. I have set it up on platforms where there is no underlying operating system, including a kernel environment. I think I am quite familiar with the problems you are mentioning, however we seem to disagree on the way to get there. You want to avoid shipping a `libc++.a` library, and I think that's completely misguided, since the existence of such a library is both orthogonal to being freestanding and is necessary for libc++ to function properly. You want to just "declare" the C library functions like `memcpy`, and I think that's just a hack that will move compilation errors to link time.

We do want to support freestanding, and in fact I remember having various discussions with @philnik777 where we discussed ways of getting there. However, here and in the past you've been pushing for your specific way of getting there, and so far most of us have thought that it wasn't the right way, hence the push back. I don't think anybody's angry (at least I am not), but we're also not going to do something wrong just because someone really really wants us to.

Concretely, I see the following possibilities in the domain of "C / C++ library intersection" w.r.t. freestanding:
1. Libc++ requires a freestanding C Standard Library underneath it in order to implement a Freestanding C++ Standard Library. This can be fulfilled however the user wants, including using llvm-libc or a custom C library.
2. Libc++ implements a Freestanding C Standard Library itself, so that it doesn't require any "external" C Standard Library in order to work in Freestanding mode.

If you see other options, please let me know. IMO, option (1) is vastly superior because we don't want to be in the business of implementing a C Standard Library, other folks already do it way better than we could.

**Comment by ldionne** [comment]
The other aspect of the Freestanding question (and IMO the only aspect that requires serious discussion and design), is how to enable only the parts that we want in Freestanding mode. Today, libc++ has various "knobs" that allow carving out parts of the library. For example, we have notions for `_LIBCPP_HAS_NO_LOCALIZATION`, `_LIBCPP_HAS_NO_RANDOM_DEVICE`, `_LIBCPP_HAS_NO_FILESYSTEM`, etc. An interesting question is whether Freestanding can be expressed as an intersection of these "carve-outs", or whether we need something else.

So, for example, is it sufficient to define Freestanding as `_LIBCPP_HAS_NO_LOCALIZATION + _LIBCPP_HAS_NO_FILESYSTEM + ...`? If not, are we just missing a few knobs for that to be the case? If that's the case, then we have a pretty easy path towards supporting Freestanding. Otherwise, if there's too much of an impedance mismatch between the two, we may have to `#ifdef _LIBCPP_FREESTANDING` around the code base, and we'll have to think about how to structure our code for that to be workable. We'll also have to think about how to deal with it in the test suite so that we can have a conformance test suite that works for freestanding environments.

**Comment by cjdb** [comment]
> @cjdb
> 
> > Good question. The problem---as reported in Discord---led me to believe that libc++ looks for the existence of _a_ libc, which you seem to agree is the case. The chatter from @jyknight to here has convinced me that we might not need to do much at all.
> 
> We require a C Standard Library to exist underneath so we can `#include_next` some of its headers, which are required to define things such as `size_t`, `memcpy` and some more. We don't actually require that much from such a library, but we do require a bit.
> 
> > Before closing this issue, I'd like to discuss whether it would be good to get `-ffreestanding` to define a `__FREESTANDING__` macro that all implementations can use. That would give everyone a common vocab.
> 
> This is already the case, although it's done a bit differently. Clang defines `__STDC_HOSTED__` to `1` all the time, but if you pass `-ffreestanding` then it defines it to `0` instead. That is how we set the `_LIBCPP_FREESTANDING` macro in `__config`, although that macro is barely used if at all.

Excellent, thanks for clearing that up @ldionne! I don' think there's much else to do besides ensuring that we're meeting the minimum freestanding requirements at the very least (if we can achieve more: great).

@trcrsired without having a clearer idea of your use-case, it's very difficult to understand your position. Could you please answer @nickdesaulniers' questions before continuing?

**Comment by ldionne** [comment]
I would be tempted to close this issue in favour of a general "implement Freestanding in libc++" issue, since that would define the task more precisely. Does anyone think this issue needs to stay open?

**Comment by cjdb** [comment]
I'm happy with that direction. It doesn't prematurely end the discussion, and refocuses it so that we can identify issues and move forward on a design. My only request is that we consider whether it should be a GitHub issue or a Discourse forum post (no need to discuss that).

**Comment by ldionne** [comment]
I went for an issue for now -- once we have a solution in mind to propose, we should probably go through a Discourse RFC first, but I think the right medium to track this work item at this point is a Github issue.
https://github.com/llvm/llvm-project/issues/78350

**Comment by ldionne** [comment]
Also, the valuable discussion here isn't lost since the two issues are linked.
