### ISSUE TITLE
Builtin type traits can't handle abominable function types as arguments

### ISSUE THREAD

**Issue by AMP999** [llvm/llvm-project#77585]
https://godbolt.org/z/9bb351bad
```
using RQ = int() &;
using CQ = int() const;

template<class T>
constexpr bool tc() { return __is_trivially_copyable(T); }
static_assert(!tc<RQ>()); // OK
static_assert(!tc<CQ>()); // OK

static_assert(!__is_trivially_copyable(RQ)); // Clang error
static_assert(!__is_trivially_copyable(CQ)); // Clang error

static_assert(!__is_trivially_copyable(int() &)); // EDG+Clang error
static_assert(!__is_trivially_copyable(int() const)); // EDG+Clang error
```
This parser limitation was clearly known when the tests for `__has_unique_object_representations` were added in https://reviews.llvm.org/D39064 , but it never explicitly came up during the code review. However, if we fixed the parser limitation, then we could simplify those tests to check the trait directly instead of going through @erichkeane's helper template in PR https://github.com/llvm/llvm-project/pull/77584.

**Comment by erichkeane** [comment]
@cor3ntin as well, since I see he's done some review on 77584:

So the helper templates are intended to emulate (at least slightly) how those builtins are used, so I don't really know if the patch to remove them gains us much.  I don't believe I actually KNEW about the abominable function types limitation here.
