### ISSUE TITLE
[D145982] [libc++] Implement std::gcd using the binary version

### ISSUE THREAD

**Issue by ldionne** [llvm/llvm-project#77648]
This issue tracks picking up https://reviews.llvm.org/D145982 from the Phabricator archive.

**Comment by AdvenamTacet** [comment]
I played a little with the benchmark from the Phabricator to [test also bigger numbers](https://quick-bench.com/q/RJQUZU2imNJNaRBsdaV3XBRSJVQ) in gcd. Performance gain is consistent.

But I think, we should add random tests to [gcd test](https://github.com/llvm/llvm-project/blob/a1dc813f759955ddbcf9b12ed052dfc8a07fdf4a/libcxx/test/std/numerics/numeric.ops/numeric.ops.gcd/gcd.pass.cpp) - 1000 times taking ranom numbers or numbers from a range and comparing with a naive implementation. Just because this implementation is prone to be bugged during a refactor.

**Comment by serge-sans-paille** [comment]
@AdvenamTacet : will do!

**Comment by AdvenamTacet** [comment]
I looked at the algorithm closer and described a problem with it in [PRs comment](https://github.com/llvm/llvm-project/pull/77747#issuecomment-1897848756). I don't think we should change gcd algorithm to that one.

If I made a mistake in benchmarks, please let me know. 

Example of too big performance hit:
https://quick-bench.com/q/pA3seH2pCZjP7WMeIGnUhUXJmrQ
