### ISSUE TITLE
delete on new[] in llvm libc?

### ISSUE THREAD

**Issue by trcrsired** [llvm/llvm-project#77976]
https://github.com/llvm/llvm-project/blob/5794854213375017f52914afbae09a12b9a33e06/libc/src/__support/File/file.cpp#L366

https://github.com/llvm/llvm-project/blob/5794854213375017f52914afbae09a12b9a33e06/libc/src/__support/File/file.h#L223

Is it a bug? The delete deletes new[] which should not happen. It should use delete[].

I would suggest not to use new/delete in libc because they introduce a dependency on C++ runtime. Just use malloc and free.

Also, i think the definition of FILE struct stdio in llvm libc is suboptimal. It needs 3 pointers for input, 3 pointers for output. Also another 6 for wchar_t. (which is what C++ std::streambuf does)

https://github.com/bminor/glibc/blob/db57da5be27a0887ce5131c071e2240f5c17aae1/libio/bits/types/struct_FILE.h#L54
Glibc is a good example.

The bufsize needs to be increased to 8192 too.

Can someone who writes the code come here and addresses those issues?

**Comment by michaelrj-google** [comment]
New is implemented here: 
https://github.com/llvm/llvm-project/blob/main/libc/src/__support/CPP/new.h
https://github.com/llvm/llvm-project/blob/main/libc/src/__support/CPP/new.cpp

Using new/delete instead of malloc/free has some semantic benefits (e.g. the `AllocChecker` makes detecting allocation errors simpler).

There is work being done on redesigning the FILE data structure already, I'm planning on writing a new RFC after I have a complete design.

**Comment by michaelrj-google** [comment]
Closing for now
