### ISSUE TITLE
[LWG 3865] [libcxx] implemented as a defect report despite status "C++23"

### ISSUE THREAD

**Issue by Eisenwave** [llvm/llvm-project#78093]
See https://cplusplus.github.io/LWG/lwg-defects.html#3865.

This issue was implemented outside of C++23 mode (https://godbolt.org/z/zPT6Tj7co) despite the issue's "C++23" status, as if it was a defect report that applies retroactively.
```cpp
#include <utility>

// compiles with -std=c++20, but shouldn't
bool equals(const std::pair<int, int>& a, const std::pair<const int, const int>& b) {
    return a == b;
}
```

Is this intentional, or is it a mistake?

**Comment by Endilll** [comment]
C++23 status of a defect report means that this was the first document that has the fix incorporated. On top of that, it means that at the time the latest official publication was C++20, and defect report apply to the latest publication at the time of resolution as well. So I believe this is intentional.

**Comment by philnik777** [comment]
Yes, this is intentional. If there is no good reason not to, defect reports are applied retroactively to all standards.

**Comment by frederick-vs-ja** [comment]
"Defect Reports" is in the official title (see [this page](https://cplusplus.github.io/LWG/lwg-defects.html)).

I think nearly all accepted LWG issues should be considered as DRs. But it's curious that some new features (e.g. `std::is_aggregate`) are also introduced by LWG issues and there're no explicit notions for them.
