### ISSUE TITLE
amdgpu_gfx functions do not use s0-s3 for inreg SGPR arguments on targets using scratch instructions for stack 

### ISSUE THREAD

**Issue by arsenm** [llvm/llvm-project#78226]
Unlike compute functions, amdgpu_gfx does not attempt to claim s[0:3] for inreg SGPR argument space. They are simply dropped from the list of argument registers. 
```

; RUN: llc -march=amdgcn -mcpu=gfx940 -o - < %s

declare void @compute(i32 inreg)
declare amdgpu_gfx void @gfx(i32 inreg)

define amdgpu_kernel void @call_compute() {
  call void @compute(i32 inreg 123)
  ret void
}

define amdgpu_cs void @call_gfx() {
  call amdgpu_gfx void @gfx(i32 inreg 123)
  ret void
}

```

compute copies 123 to $sgpr0, and amdgpu_gfx copies to $sgpr4

**Comment by SahilPatidar** [comment]
hii @arsenm I am new here,  so far I understand from your description is that amdgpu_gfx functions do not use s0-s3 for inreg SGPR arguments and instead use a different register, such as $sgpr4.  I would like to take this so can you guide me where to start?

**Comment by arsenm** [comment]
> hii @arsenm I am new here, so far I understand from your description is that amdgpu_gfx functions do not use s0-s3 for inreg SGPR arguments and instead use a different register, such as $sgpr4. I would like to take this so can you guide me where to start?

I think this only needs 2 small changes, and then assorted test updates. 
1. Update AMDGPUCallingConv.td for the *_Gfx calling conventions to include sgpr0-sgpr3 in the argument list
2. Update the matching code in SIISelLowering+AMDGPUCallLowering by removing the !IsGraphics checks which pre-allocates the registers under enableFlatScratch

**Comment by SahilPatidar** [comment]
> I think this only needs 2 small changes, and then assorted test updates.
> 
> 1. Update AMDGPUCallingConv.td for the *_Gfx calling conventions to include sgpr0-sgpr3 in the argument list
> 2. Update the matching code in SIISelLowering+AMDGPUCallLowering by removing the !IsGraphics checks which pre-allocates the registers under enableFlatScratch

Thank you for your help, and another question: do I simply need to remove !IsGraphics checking or handling a specific case?
For example, in the code block below. 
`
 else if(!IsGraphics) {
    // For the fixed ABI, pass workitem IDs in the last argument register.
    allocateSpecialInputVGPRsFixed(CCInfo, MF, *TRI, *Info);

    // FIXME: Sink this into allocateSpecialInputSGPRs
    if (!Subtarget->enableFlatScratch())
      CCInfo.AllocateReg(Info->getScratchRSrcReg());

    allocateSpecialInputSGPRs(CCInfo, MF, *TRI, *Info);
  }
`

**Comment by arsenm** [comment]
> > I think this only needs 2 small changes, and then assorted test updates.
> > 
> > 1. Update AMDGPUCallingConv.td for the *_Gfx calling conventions to include sgpr0-sgpr3 in the argument list
> > 2. Update the matching code in SIISelLowering+AMDGPUCallLowering by removing the !IsGraphics checks which pre-allocates the registers under enableFlatScratch
> 
> Thank you for your help, and another question: do I simply need to remove !IsGraphics checking or handling a specific case? For example, in the code block below. ` else if(!IsGraphics) { // For the fixed ABI, pass workitem IDs in the last argument register. allocateSpecialInputVGPRsFixed(CCInfo, MF, *TRI, *Info);
> 
> ```
>    // FIXME: Sink this into allocateSpecialInputSGPRs
>    if (!Subtarget->enableFlatScratch())
>       CCInfo.AllocateReg(Info->getScratchRSrcReg());
> 
>    allocateSpecialInputSGPRs(CCInfo, MF, *TRI, *Info);
> }
> ```
> 
> `

The allocateSpecialInputSGPRs part should not happen for IsGraphics.

**Comment by SahilPatidar** [comment]
@arsenm 
Please let me know if there is anything wrong in my [commit](https://github.com/SahilPatidar/llvm-project/commit/d32db60b5f2929c570e5e212be1a70d38cc6b5db)

**Comment by SahilPatidar** [comment]
Hello @Rajveer100,
I've noticed your commits. Would you mind if I proceed with landing the PR? If I encounter any difficulties, I'll let you know, and you can proceed. Thank you for considering.

**Comment by SahilPatidar** [comment]
@arsenm,

I seek your feedback on my recent commit mentioned above. Please let me know if there are any concerns or suggestions for improvement. Thank you for your consideration.

**Comment by SahilPatidar** [comment]
Should I alter the test cases due to the identification of test case failures? Specifically, 23 tests have failed, as indicated below:

Failed Tests (23):
  LLVM :: CodeGen/AMDGPU/GlobalISel/irtranslator-call-non-fixed.ll
  LLVM :: CodeGen/AMDGPU/GlobalISel/irtranslator-call.ll
  LLVM :: CodeGen/AMDGPU/GlobalISel/irtranslator-function-args.ll
  LLVM :: CodeGen/AMDGPU/amdgpu-cs-chain-cc.ll
  LLVM :: CodeGen/AMDGPU/amdgpu-simplify-libcall-pow-codegen.ll
  LLVM :: CodeGen/AMDGPU/bf16.ll
  LLVM :: CodeGen/AMDGPU/call-args-inreg.ll
  LLVM :: CodeGen/AMDGPU/combine_andor_with_cmps.ll
  LLVM :: CodeGen/AMDGPU/flat_atomics_i32_system.ll
  LLVM :: CodeGen/AMDGPU/flat_atomics_i64_system.ll
  LLVM :: CodeGen/AMDGPU/fsub-as-fneg-src-modifier.ll
  LLVM :: CodeGen/AMDGPU/function-args-inreg.ll
  LLVM :: CodeGen/AMDGPU/gfx-callable-argument-types.ll
  LLVM :: CodeGen/AMDGPU/global_atomics_i32_system.ll
  LLVM :: CodeGen/AMDGPU/global_atomics_i64_system.ll
  LLVM :: CodeGen/AMDGPU/indirect-call.ll
  LLVM :: CodeGen/AMDGPU/isel-amdgpu-cs-chain-cc.ll
  LLVM :: CodeGen/AMDGPU/isel-amdgpu-cs-chain-preserve-cc.ll
  LLVM :: CodeGen/AMDGPU/preserve-wwm-copy-dst-reg.ll
  LLVM :: CodeGen/AMDGPU/schedule-addrspaces.ll
  LLVM :: CodeGen/AMDGPU/scratch-pointer-sink.ll
  LLVM :: CodeGen/AMDGPU/stacksave_stackrestore.ll
  LLVM :: CodeGen/AMDGPU/wwm-reserved-spill.ll


Testing Time: 2798.48s

Total Discovered Tests: 3443
  Passed           : 3412 (99.10%)
  Expectedly Failed:    8 (0.23%)
  Failed           :   23 (0.67%)

**Comment by arsenm** [comment]
> Should I alter the test cases due to the identification of test case failures? Specifically, 23 tests have failed, as indicated below:
> 


Yes, this is expected. You just need to update them to show the shifted down register numbers

**Comment by SahilPatidar** [comment]
shifted down register numbers mean s4 -> s0, s5 -> s1 and so on?

**Comment by SahilPatidar** [comment]
@arsenm, 
I'm currently not familiar with how to update tests. Could you please provide instructions on addressing the failed test cases, particularly the 23 instances that have failed?
