### ISSUE TITLE
Wrong MC/DC code generation with ternary operator

### ISSUE THREAD

**Issue by chapuni** [llvm/llvm-project#78453]
(https://godbolt.org/z/qYKKnvbva)
```
bool foo(bool a, bool b, bool c, bool d, bool e) {
    return (a || b ? c && d : e);
}
```

This is not rejected (as unsupported) but wrong code is generated.
CoverageGen emits a couple of decisions but CodeGen emits weird code.
Finally, `llvm-cov` crashes with unexpected test vector.

**Comment by chapuni** [comment]
Seems this is generic to split decisions, like `func(a && b, c && d)`.
https://godbolt.org/z/5h1dqc4be

Can I retitle?

**Comment by evodius96** [comment]
The temporary bitmap value for the ternary operator's condition was being saved after its LHS and RHS was evaluated, which means that if the LHS or RHS has a boolean expression, the bitmap value will become corrupted, and the bitmaps for all of the boolean expressions will be wrong.  The fix is to ensure that the temporary bitmap value for the ternary operator's condition is saved prior to visiting the LHS and RHS.  It's a straightforward fix, but I'll put up a PR soon.

**Comment by chapuni** [comment]
Thanks!
