### ISSUE TITLE
[Attributor] Incorrect optimization of math function when attributor module pass is run

### ISSUE THREAD

**Issue by jhuber6** [llvm/llvm-project#78507]
The Attributor module pass currently optimized out this math function incorrectly to always return `NaN`. The reproducer is at https://godbolt.org/z/1P9xTjoab. When the attributor is not run, the function remains correct, when it's run it gets incorrectly removed.

**Comment by jdoerfert** [comment]
The way I see it, we currently follow all uses through intrinsics and use the fpclass derived for the result also for the argument. That is wrong, e.g. the fabs result is more constrained then the argument is, I think.

I have a fix here: https://github.com/jdoerfert/llvm-project/tree/fpclass_fixes
But it needs to be refined (potentially after landing) to allow specific deductions.
I did not update the tests, even though they are impacted, because I wanted to first update them w/o the change and avoid churn. That resulted in me finding https://github.com/llvm/llvm-project/issues/78517.
Once @arsenm comments, we can move ahead with the fixes.

**Comment by arsenm** [comment]
I think I just ran into another manifestation of this issue where this is incorrectly adding nofpclass to an incoming function argument based on an unread use context
