### ISSUE TITLE
[lld] Large sections are sorted incorrectly for no-pic links

### ISSUE THREAD

**Issue by aeubanks** [llvm/llvm-project#78521]
With https://reviews.llvm.org/D150510, we place large sections farther from text to mitigate relocation overflows to small sections. However, "farther from text" is only correct for PIC builds that use relative relocations. Non-PIC builds use absolute relocations and typically assume that small sections are in the lower 2GB of the address space. Currently we place `.lrodata` at the very beginning of the binary, but for non-PIC builds it should go at the end.

To prevent extra segments, should we also place `.rodata` toward the end so it still shares a segment with `.lrodata`? But non-PIC binaries can still have PC-relative relocations, so keeping `.rodata` before `.text` is still useful for mitigating that type of relocation pressure?

@MaskRay

**Comment by MaskRay** [comment]
I think it is probably not linker's job to satisfy such `-no-pie` requests.
It is unfortunate to make lld "smarter" by making `.lrodata` placement different for `-no-pie` and `-pie`/`-shared`.
I think that the users, if care about the placement of `.lrodata`, should specify something like `SECTIONS { .lrodata : { *(.lrodata .lrodata.*) } } INSERT AFTER .bss;`

**Comment by aeubanks** [comment]
If placement of `.lrodata` is necessary for semantics, I'm not sure why we'd treat `-no-pie` differently from `-pie`/`-shared`? We already properly place `.lrodata` for PIC code, then why not for non-PIC code? It's not really any extra maintenance burden anyway.

**Comment by MaskRay** [comment]
Making `-no-pie`/`-pie`/`-shared` change the default section layout would be quite unusual. We should avoid it. `-fpie`/`-fpic` compiles can use a `-no-pie` link as well. They are agnostic about where `.lrodata` is placed, while decreasing the number of relative relocations.

**Comment by jyknight** [comment]
A `-no-pie` link is intended to be compatible with `-fno-pic` compiles. So, I disagree -- I think we absolutely _do_ need to change the default section layout for `-no-pie` linking so that it functions with `-fno-pic` compilations in the medium model.

I think the answer of moving `.lrodata` to the end in `-fno-pic` mode and leaving everything else the same is the best option. Sure, that costs an extra LOAD, but I'm willing to bet that moving rodata from its traditional location would be _way_ more trouble than it's worth.

If we want the layout not differ between `-fno-pic` and `-pie`/`-shared`, then we ought to move `.lrodata` to the end for the latter cases, too -- not keep the status quo. But, since the complexity of checking whether we're in no-pie mode is so low, and that has unnecessary overhead, it doesn't seem like a preferable alternative.

**Comment by aeubanks** [comment]
#81224 gives the option to place `.lrodata` toward the end of the binary
