### ISSUE TITLE
[libc++] Should `std::tuple_size<const int>` be a complete type?

### ISSUE THREAD

**Issue by frederick-vs-ja** [llvm/llvm-project#78547]
The following code snippet is currently showing implementation divergence ([Godbolt link](https://godbolt.org/z/P8oWqf5sT)). MSVC STL's `std::tuple_size<const int>` is a complete type, while libstdc++'s and libc++'s are not.
```C++
#include <tuple>

// constexpr auto foo = sizeof(std::tuple_size<int>);    // Correctly rejected.
constexpr auto bar = sizeof(std::tuple_size<const int>); // Should be well-formed?
```

It seems that MSVC STL's behavior is justified by [[contents]/1](https://eel.is/c++draft/contents#1) and [[tuple.syn]](https://eel.is/c++draft/tuple.syn), given that only the primary templates of `std::tuple_size` and `std::tuple_element` are marked `// not defined`.

I'm not sure whether this should be considered as a bug. Perhaps an LWG issue is wanted.

**Comment by philnik777** [comment]
https://eel.is/c++draft/tuple.helper#1 and https://eel.is/c++draft/tuple.helper#4 seem to contradict each other. I think this requires and LWG issue, but IMO the sane reading of this is that it should only be specialized if `tuple_size<T>` (with non-const T) is well formed.

**Comment by ldionne** [comment]
I'm going to tag this with "waiting-for-wg21" and close for the time being. The goal here is not to dismiss this issue, but rather to avoid having a large number of currently-open issues that are simply waiting for a WG21 resolution, since we seem to have a lot of them lately.

We can reopen the issue once (or if) there is a libc++ action item. Let me know if you think we should handle these issues differently, I don't think we have a set way of dealing with those right now.

**Comment by mordante** [comment]
I like this solution. If this gets resolved by WG21 we'll see it again, if it's considered not a defect it's closed. I think it would be great to mention the LWG issue that was created, in this case [LWG4040](https://cplusplus.github.io/LWG/issue4040).
