### ISSUE TITLE
[lld] lld behaves differently from ld.bfd when adding `.interp`

### ISSUE THREAD

**Issue by yshui** [llvm/llvm-project#78873]
`lld` adds the `.interp` section whenever `--dynamic-linker` is set. whereas `ld.bfd` won't add `.interp` unless the resulting binary has a `NEEDED` shared library.

in other words,

```console
ld a.o --dynamic-linker /asdf -o a
```

won't generate an `.interp` section, but

```console
ld a.o a.so --dynamic-linker /asdf -o a
```

will.

OTOH 

```console
ld.lld a.o --dynamic-linker /asdf -o a
```

adds an `.interp`, unlike `ld.bfd`.

This is related to nixos/nixpkgs#242244, which breaks clang+lld kernel build on nixos.

**Comment by brad0** [comment]
cc @MaskRay

**Comment by MaskRay** [comment]
I think lld's choice not add `PT_INTERP` is reasonable (more orthogonal) and this issue is a wont-change.
`PT_INTERP` can be used in the absence of shared object.

The build system should remove `--dynamic-linker` or specify `--no-dynamic-linker`.

GNU ld also sets a default `PT_INTERP` for `ld.bfd a.o a2.so`, which ld.lld doesn't. It does not make sense to blindly follow GNU ld here.

**Comment by yshui** [comment]
Removing `--dynamic-linker` from nix's build system isn't really practical here. I guess the only choice is patching the kernel then.

Thanks anyways.
