### ISSUE TITLE
[Flang] Formatted READ, after BN edit descriptor, of numeric field with only '.' non-blanks does not signal error condition (IOSTAT, ERR)

### ISSUE THREAD

**Issue by kiranktp** [llvm/llvm-project#79787]
Consider below reproducer:

$ cat -n repro.F90
     1  Program test_BN
     2    Character(6) :: s
     3    Real :: x
     4    Integer :: stat
     5    s = ' .  '
     6    Read(s,1,iostat=stat) x  ! no digits present, error condition
     7    Print '(F4.2,I6)',x,stat
     8    Read(s,2,iostat=stat,BLANK='NULL') x
     9    Print '(F4.2,I6)',x,stat
    10  1 Format(BN,F12.3)
    11  2 Format(F12.3)
    12  End Program test_BN

A BN edit descriptor, or a BLANK='NULL' specifier in a READ statement, should result in an error condition when the F/E/D/EN/ES field consists of the decimal point alone. The words in the Standard are "The input ﬁeld consists of an optional sign, followed by a string of one or more digits optionally containing a decimal point, including any blanks interpreted as zeros", not allowing for the possibility of decimal point alone.

llvm-flang, gcc, intel do not signal error.

**Comment by klausler** [comment]
That usage is valid with gfortran, both Intel compilers, nvfortran, NAG, and XLF.  Portability matters more than the standard.

**Comment by ThemosTsikas** [comment]
The NAG compiler sets stat to 140 (IOERR_BAD_INPUT_REAL from intrinsic non-standard module F90_IOSTAT). 

In the absence of an IOSTAT= specifier, it is possible to argue that this behaviour (accepting the input, continuing execution) is a reasonable extension of the Standard that gives an interpretation to a non-conforming program. 

When IOSTAT= specifier is present, this behaviour cannot be seen as an extension, and will result in non-Standard interpretation of a conforming program. I would argue that at the very least it merits documenting in https://github.com/llvm/llvm-project/blob/main/flang/docs/Extensions.md#intentional-violations-of-the-standard .

**Comment by klausler** [comment]
GNU, both Intels, nvfortran, and XLF all return `iostat=` of 0 for this case; only NAG returns nonzero.  Being standard-conforming here would decrease portability.
