### ISSUE TITLE
[C++20][Modules] Incorrectly distincted static local vars 

### ISSUE THREAD

**Issue by Lancern** [llvm/llvm-project#80949]
Given the following set of translation units:

```cpp
export module a;

export int __attribute__((always_inline)) foo() {
  static int x;
  return ++x;
}
```

```cpp
import a;

int test1() { return foo(); }
```

```cpp
import a;

int test2() { return foo(); }
```

```cpp
#include <iostream>

int test1();
int test2();
int main() {
  std::cout << test1();
  std::cout << test2();
}
```

The program outputs `11` instead of the expected result `12`. Function `test1` and function `test2` access distinct `static int x` objects which are mistakenly inlined into their bodies.

Up to clang 17.0.1, this behavior can happen even if `foo` is not marked with `always_inline` (with optimizations enabled). Seems like this problem is partially fixed by PR #71031 , but the PR misses `always_inline` functions.

**Comment by ChuanqiXu9** [comment]
Although we may fix the issue by treating the imported static locals as available externally, it looks more consistency to not import non-inline function bodies at all no matter if it is always_inline or not. Since we already decided to not import the non-inline function bodies: https://isocpp.org/files/papers/P3092R0.html

**Comment by ChuanqiXu9** [comment]
The previous solution gets some complaints so we probably need some workaround here.
