### ISSUE TITLE
[clangd] IncludeCleaner missing includes inserts a different path than header-insertion

### ISSUE THREAD

**Issue by torshepherd** [llvm/llvm-project#81215]
Basically, when I accept "add missing include" from the suggested fixes for IncludeCleaner, clangd inserts headers with various paths:

- just the filename (`header.hpp`)
- the full path from my desktop (with `/home/tor.shepherd/root-dir/relative-path/header.hpp`)

However, header-insertion on autocomplete consistently produces the correct path (`relative-path/header.hpp`) according to my codebase's guidelines.

(Note, both utilities produce the correct headers for stdlib includes, except IncludeCleaner produces a full path to the actual header file for `using namespace std::chrono_literals;` and autocomplete doesn't add any include for this; I would expect <chrono> to be added)

**Comment by torshepherd** [comment]
Seems like IncludeCleaner uses `include_cleaner::spellHeader` but CodeComplete uses `IncludeInserter::calculateIncludePath` - which one is preferred? I think they should at least be consolidated/ perhaps a configuration value could choose which one to use

**Comment by idrilirdi** [comment]
Can confirm, exactly the same is happening to me. I'd prefer IncludeCleaner to return the path like CodeComplete, it's a pain to have to remove all the "/home/user/root_dir"s from the headers when using the code action

**Comment by torshepherd** [comment]
@idrilirdi I intend to take a look at this this month, please ping this issue to remind me

**Comment by idrilirdi** [comment]
@torshepherd friendly ping, are there any updates on this? :)

**Comment by torshepherd** [comment]
Ok I did a bit more digging and it seems like there was an idea that the spelling strategies could be smart/extensible: https://reviews.llvm.org/D150185

I wonder why they fallback to raw absolute paths then? Seems like there are a few issues with the strategies that I've encountered:

- Too eager to do relative includes (I. E. if you include a header from the same dir, you get "MyHeader.h"). This is _not_ universally used. At my work, for instance, our guidelines prefer to always use a path relative to workspace root. So this spelling strategy is never what we want
- Too eager to fallback to absolute paths. I'm not really sure why this happens at all. This should almost never be the behavior. In fact, the default should just always be relative to base directory, no? I think the majority of codebases prefer this style.

Seems like the root issue is that the spelling strategies are not inferring usage from the codebase, but rather use a predefined hierarchy of strategies. If you just analyzed similar includes either in the same file or in different files, you could pretty easily see "ah this repository seems to use relative includes like "../MyFile.h" or "MyFile.h" for close includes, and "base/stuff/MyFile.h" for other subdirectories, etc.

CC @VitaNuova (who authored the IncludeSpeller PR) - are there plans to work more on this? If not can I take it up?

**Comment by kadircet** [comment]
encountered this couple more times in the mean while, and finally got to reproduce.

issue seems to be the result of mixing relative include-search paths and absolute file-names, and is unfortunately two-fold:

first case is, absolute path for the header, relative path for include-search-path, e.g. a translation unit:
- built in directory `/root/inner`
- has compile flags `clang -I.. ../bar/foo.cc`
- trying to spell header `/root/baz.h`.

this will yield a spelling of `/root/baz.h`, because we are not passing `WorkingDir` in https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/include-cleaner/lib/IncludeSpeller.cpp#L33-L34. Hence search path `..` is matched against `/root/baz.h` as-is. Sent out https://github.com/llvm/llvm-project/pull/95114 for the fix of this one.

---

we'd fail in the dual case as well, e.g. a translation unit:
- built in directory `/root/inner`
- has compile flags `clang -I/root/ ../bar/foo.cc`
- trying to spell header `../baz.h`.

this will yield spelling of `../baz.h`, because despite normalizing include-search-paths in https://github.com/llvm/llvm-project/blob/main/clang/lib/Lex/HeaderSearch.cpp#L2054-L2055, we don't resolve relative file-paths themselves. https://github.com/llvm/llvm-project/pull/95121 for the fix.


Reproducer i got was a result of the former, yours also sounds like the first one as you get an absolute spelling for the header.
