### ISSUE TITLE
Conflicting warnings when handling enums in a switch with -Weverything

### ISSUE THREAD

**Issue by SewerDweller** [llvm/llvm-project#81354]
foo() warns about a default case missing, while foo2() warns about a default case being present when every enum case is already handled.

https://godbolt.org/z/WxooaoeMK

**Comment by cor3ntin** [comment]
Hum, this is actually consistent with GCC https://godbolt.org/z/re8Y5W1Wv  and it is a separate flag from `-Wswitch`.
I now remember that it was the intent of this flag (and note that it is not enabled under `-Wall, -Wextra`

**Comment by cor3ntin** [comment]
This was added by https://github.com/llvm/llvm-project/pull/73077

**Comment by jyknight** [comment]
This is correct. Some users want one, and some want the other, so both are provided.

It is expected behavior for `-Weverything` to include contradicting diagnostics, see the [docs](https://clang.llvm.org/docs/UsersManual.html#enabling-all-diagnostics). As the docs also mention, it's not recommended to use `-Weverything`.

**Comment by shafik** [comment]
This stackexchange answer is also worth a read: https://softwareengineering.stackexchange.com/a/124574/84604
