### ISSUE TITLE
A module with python version 3.7 is used, but the minimum required python version is 3.6

### ISSUE THREAD

**Issue by songdongsheng** [llvm/llvm-project#81598]
Testing fails in RHEL 8：

```
stderr:
Traceback (most recent call last):
  File "/opt/llvm-build/llvm-18.x/libcxx/test/libcxx/module_std.gen.py", line 24, in <module>
    from libcxx.test.modules import module_test_generator
  File "/opt/llvm-build/llvm-18.x/rc2/llvm-project/libcxx/utils/libcxx/test/modules.py", line 11, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
```
This is because the default python in RHEL 8 is 3.6, and this test uses the new modules in python 3.7.

The easiest fix is to upgrade the python version requirement to 3.7 or higher and modify the page [Getting Started with the LLVM System](https://llvm.org/docs/GettingStarted.html).

**Comment by h-vetinari** [comment]
Yeah, it's "just" a doc issue, see this [RFC](https://discourse.llvm.org/t/rfc-upgrading-llvms-minimum-required-python-version/67571/13) - Python 3.6 is EOL (and so is 3.7 actually). It's wasted effort to maintain compatibility with these dead versions, _especially_ because getting a newer Python is not that hard (e.g. through [conda](https://docs.conda.io/en/latest/)). RHEL 8 even provides an "official" Python3.8 in the Software Collections.

**Comment by ldionne** [comment]
Closing since we don't support Python 3.6 anymore.
