### ISSUE TITLE
target emission for ctlz doesn't account for range metadata

### ISSUE THREAD

**Issue by sadlerap** [llvm/llvm-project#82075]
Consider this IR:

```llvm
define i32 @clz_nzu8(ptr %num) {
start:
  %self = load i8, ptr %num, align 1, !range !0
  %0 = tail call i8 @llvm.ctlz.i8(i8 %self, i1 true)
  %_0 = zext i8 %0 to i32
  ret i32 %_0
}

declare i8 @llvm.ctlz.i8(i8, i1 immarg)
!0 = !{ i8 1, i8 0 }
```

`llc --mcpu=x86-64-v3` (enables the `lzcnt` instruction) emits the following x86 assembly:

```asm
clz_nzu8:                               # @clz_nzu8
        movzx   eax, byte ptr [rdi]
        lzcnt   eax, eax
        add     eax, -24
        movzx   eax, al
        ret
```

If we account for the range metadata (i.e. that `%self` cannot be zero), we could save an instruction:
```asm
clz_nzu8:                               # @clz_nzu8
        movzx   eax, byte ptr [rdi]
        shl     eax, 24
        lzcnt   eax, eax
        ret
```

Or, as IR:
```llvm
define i32 @clz_nzu8(ptr %num) {
  %self = load i8, ptr %num, align 1, !range !0
  %zext = zext i8 %self to i32
  %shl = shl nuw i32 %zext, 24
  %ctlz = tail call i32 @llvm.ctlz.i32(i32 %shl, i1 true)
  ret i32 %ctlz
}

declare i32 @llvm.ctlz.i32(i32, i1 immarg)
!0 = !{ i8 1, i8 0 }
```

This optimization isn't advantageous when the instructions emitted for `@llvm.ctlz.i*` is independent of the size of the input type, such as x86 without the `lzcnt` instruction.  As far as I can tell, this means we should only really do this transformation when this intrinsic requires extending the provided integer to a larger type (for instance, i8 on x86, or i8 and i16 on aarch64).

[Alive Proof](https://alive2.llvm.org/ce/z/xxCdeg)

**Comment by Nirhar** [comment]
I'm interested in solving this problem, and I believe one way to go about this is to add an InstCombine Rule for this optimization.

Any other suggestions?

**Comment by dtcxzyw** [comment]
> I'm interested in solving this problem, and I believe one way to go about this is to add an InstCombine Rule for this optimization.
> 
> Any other suggestions?

You shouldn't implement target-specific transform in InstCombine.

**Comment by nikic** [comment]
The range metadata isn't really relevant here, because the necessary information is already encoded in the zero_is_poison flag. So this is just a matter of chosing a different legalization approach for CTLZ_ZERO_UNDEF.

**Comment by sadlerap** [comment]
Hmm, I don't know if it makes sense to run this in x86 lowering, since this transformation also applies on other targets, such as `aarch64` (see the alive link above for an example).

**Comment by Nirhar** [comment]
Since this isn't a target specific optimization, I believe there are two places where one can implement a patch for this:
1. Add an InstCombine Rule to transform the IR to include this case
2. Modify DAG Legalization to emit the right instructions given the IR

Which one is a better solution?

**Comment by RKSimon** [comment]
DAGTypeLegalizer is the way to go - most likely in PromoteIntRes_CTLZ - start there and see what effect it has on each target and then we can decide if we need something more specific

**Comment by Nirhar** [comment]
So here is my analysis of the problem:
The correct way to implement this optimization seems to be in LegalizeDAG.cpp, specifically, at this point:
https://github.com/llvm/llvm-project/blob/87b1e735b28f81d9012fd302cd07385db50a274f/llvm/lib/CodeGen/SelectionDAG/LegalizeDAG.cpp#L4978-L5007 

However the range metadata is not accessible at this point because the SDNode used at this point was never initialized with the range metadata. The Load SDNode is initialized in `SelectionDAGBuilder.cpp:visitLoad`, and the range MDNode needed for its initialization is initialized at this point:
https://github.com/llvm/llvm-project/blob/26d71d9ed56c4c23e6284dac7a9bdf603a5801f3/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp#L4342

But however `getRangeMetadata` returns nullptr because of the absence of the attribute `!noundef` as described here:
https://github.com/llvm/llvm-project/blob/26d71d9ed56c4c23e6284dac7a9bdf603a5801f3/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp#L4298-L4308

So I see three options here:
1. Consider relaxing the requirement for the !noundef attribute inside `getRangeMetadata`
2.  Do this optimization only if the load contains the !noundef attribute
3.  Consider moving the optimization to InstCombine.

Which one is a better way to choose?

**Comment by nikic** [comment]
@Nirhar As I have already said above, the range metadata is irrelevant here (proof: https://alive2.llvm.org/ce/z/w_3Ri5). All you care about is that it's a CTLZ_ZERO_UNDEF rather than CTLZ node.
