### ISSUE TITLE
Missing FoundDecl in ConceptReference.

### ISSUE THREAD

**Issue by hokein** [llvm/llvm-project#82628]
Given the following code, the `FoundDecl` is null in the `Foo`'s AST node (`ConceptReference`).

```
namespace ns {
template<typename T> concept Foo = true;
}

using ns::Foo;
template<typename T>concept Bar = Foo<T>;  // reference `Foo` points to the underlying of ns::Foo, rather than the `using` decl.
```

This breaks some clang tools: include-cleaner will report the file of the underlying decl, rather than the one for using decl; clangd's go-to-def on `Foo` jumps to the underlying decl.

**Comment by zyn0217** [comment]
I think the reason is that `LookupResult::getFoundDecl()` returns the underlying Decl of the target `UsingShadowDecl`.

https://github.com/llvm/llvm-project/blob/1f6a347c8abf8868fb4630c404480226c2efc2c2/clang/include/clang/Sema/Lookup.h#L563-L567

https://github.com/llvm/llvm-project/blob/1f6a347c8abf8868fb4630c404480226c2efc2c2/clang/lib/Sema/SemaTemplate.cpp#L5076-L5080

Perhaps it should have been `R.getRepresentativeDecl()` based on the intent of `ConceptReference::FoundDecl`.

**Comment by zyn0217** [comment]
And applying that modification gives us the AST:
```txt
`-ConceptDecl 0x7fd5249c13c8 <line:6:1, col:40> col:29 Bar
  |-TemplateTypeParmDecl 0x7fd5249c1230 <col:10, col:19> col:19 referenced typename depth 0 index 0 T
  `-ConceptSpecializationExpr 0x7fd5249c1398 <col:35, col:40> 'bool' UsingShadow 0x7fd5249c11b0 'Foo'
```

compared to that before:

```
`-ConceptDecl 0x7fe2b920b298 <line:6:1, col:40> col:29 Bar
  |-TemplateTypeParmDecl 0x7fe2b920b100 <col:10, col:19> col:19 referenced typename depth 0 index 0 T
  `-ConceptSpecializationExpr 0x7fe2b920b268 <col:35, col:40> 'bool' Concept 0x7fe2b920afb0 'Foo'
```

**Comment by hokein** [comment]
@zyn0217 thanks for the investigation, it makes sense, do you mind sending out a fix?

**Comment by zyn0217** [comment]
Hmm, this is more complicated than I expected: for the type constraint cases, e.g.
```cpp
namespace ns {
template<typename T> concept Foo = true;
}

using ns::Foo;

template <Foo T> // <-- Note here
void foo();
```

The `FoundDecl` thereof still doesn't point to the `UsingShadowDecl` that way, seemingly because the annotated token (which points to the `UsingShadowDecl`) gets desuagared implicitly within `TemplateName::getAsTemplateDecl`.

https://github.com/llvm/llvm-project/blob/597f9761c3a5ba278fa930d2fac13f156287d505/clang/lib/AST/TemplateName.cpp#L145-L152

https://github.com/llvm/llvm-project/blob/597f9761c3a5ba278fa930d2fac13f156287d505/clang/lib/Sema/SemaTemplate.cpp#L1145-L1177

**Comment by zyn0217** [comment]
The type constraint cases are not that hard to tackle, but constraints on `AutoType`s e.g. `C auto` probably need some extra work.

(I hope I can figure them all out, but it takes some time.)
