### ISSUE TITLE
RVV spilling when using VCIX instructions with `-mtune=sifive-x280`

### ISSUE THREAD

**Issue by michalt** [llvm/llvm-project#83391]
We encountered a weird problem where using `-mtune`for the X280 results in a very poor codegen: https://godbolt.org/z/qfzKMcq84 (note that by adding more blocks the problem gets worse and worse as we get more spills)

My hypothesis is that due to the recent change to allow reordering VCIX instructions, the scheduler tries to move all the loads before the VCIX instructions. What is surprising is that it doesn't seem to take into account register pressure?

@topperc and @michaelmaitland Any ideas what's happening? Thanks!

**Comment by wangpc-pp** [comment]
Is it because there is no scheduling info for VCIX insturctions?

**Comment by michalt** [comment]
> Is it because there is no scheduling info for VCIX insturctions?

Yeah, that very likely plays a role, but it's still surprising how bad the result is. It's as if scheduler was assuming unlimited number of registers..?

**Comment by wangpc-pp** [comment]
I tried to set a large latency to VCIX instructions(see #83427), it seems that the problem can be fixed.

**Comment by paulmnt** [comment]
I agree that changing the cost of VCIX instructions can somewhat mitigate the issue; however that cost cannot be assumed constant. It would be desirable to specify such cost with a flag.

In addition, I don't think this change would close the issue, because the main problem is that the scheduler appears to be ignoring the number of available vector registers. I believe that might be the issue that needs fixing.

**Comment by michalt** [comment]
I just checked internally that with #86093 things look reasonable, so I'm closing this. Thanks for help everyone! 😄
