### ISSUE TITLE
[clang][rejects valid][c++20] bad parse of constrained friend function

### ISSUE THREAD

**Issue by ericniebler** [llvm/llvm-project#83461]
The following should compile (-std=c++20):

```c++
template <class A>
concept always_true = true;

struct receiver {
  template <class Tag = int>
  friend void tag_invoke( always_true auto, receiver self) {
  }
};
```

All recent versions of clang including trunk rejects this code with:

```
<source>:9:43: error: template parameter missing a default argument
    9 |   friend void tag_invoke( always_true auto, receiver self) {
      |                                           ^
<source>:8:25: note: previous default template argument defined here
    8 |   template <class Tag = int>
      |                         ^
1 error generated.
Compiler returned: 1
```

https://godbolt.org/z/6G1hPsKM3

**Comment by shafik** [comment]
Confirmed: https://godbolt.org/z/96Y4e4j1r

I don't know what is going on here, maybe @erichkeane does

**Comment by erichkeane** [comment]
I've never seen that error before... At least it doesn't have anything to do with concepts (reduced away as:
```
struct receiver {
  template <class Tag = int>
  friend void tag_invoke(  auto, receiver self) {
  }
};```

My guess is that we're somehow ordering the 'auto' parameter 'last' in template argument ordering rather than 'first'.  I'm not sure what the CORRECT answer is there though, and wonder if this is either a CWG issue-worthy thing, or just a clang bug (Can anyone find some prose that gives explaination here?).

But effectively what it looks like is happening is that our check to prevent this pattern:
```
struct receiver {
  template <class Tag = int, class T2>
  friend void tag_invoke(receiver self) {
  }
};
```
Is picking up the 'auto' parameter.

**Comment by erichkeane** [comment]
Side note, we don't seem to have this problem with Lambdas, so figuring out what we do differently there might be informative: https://godbolt.org/z/1WzdWvKK3

**Comment by erichkeane** [comment]
OH! Strangly it is ONLY in the case of a friend function, free/member function aren't affected either for some reason.

**Comment by erichkeane** [comment]
Ah, figured it out... all my speculation was wrong!  Its an incorrect implementation of 

https://eel.is/c++draft/temp.param#14

WIP now.

**Comment by ericniebler** [comment]
Thank you for the speedy fix!
