### ISSUE TITLE
Expressions in _Generic Misinterpret the Standard

### ISSUE THREAD

**Issue by IGJoshua** [llvm/llvm-project#84172]
The _Generic keyword introduced in C11 is very useful for defining type generic code, but its capabilities are hamstrung by a narrow interpretation of the spec which I don't think is supported by the text therein.

Follows is an example program which fails to compile, but which I believe should compile under the spec:

```c
struct s1 {
    int x;
};
struct s2 {
    int y;
};

int f1(struct s1 s);
int f2(struct s2 s);

int main(void) {
    struct s1 s = {0};
    return _Generic( (s),
                     struct s1 : f1(s),
                     struct s2 : f2(s) );
}
```

This program is rejected by clang with the error

```
main.c:15:37: error: passing 'struct s1' to parameter of incompatible type 'struct s2'
                     struct s2 : f2(s) );
                                    ^
```

I believe this is in error, as the branch which the error occurs in is never evaluated, and this is known at compile time.

In ISO 9899:2023 section 6.5.1.1 paragraph 3, it says
> The controlling expression of a generic selection is not evaluated. If a generic selection has a generic association with a type name that is compatible with the type of the controlling expression, then the result expression of the generic selection is the expression in that generic association. Otherwise, the result expression of the generic selection is the expression in the default generic association. None of the expressions from any other generic association of the generic selection is evaluated.

I may be mistaken, but I believe that saying that the other generic associations are not evaluated means that they should not be rejected for being invalid as long as they parse as expressions.

**Comment by cor3ntin** [comment]
They are not evaluated, but they should still be semantically valid expressions

usually, you would write something like that instead

```c
return _Generic( (s),
                     struct s1 : f1),
                     struct s2 : f2)(s);
```

@AaronBallman

**Comment by IGJoshua** [comment]
I am aware that there are ways around this for function calls, perhaps a different motivating example would be relevant. The use with functions was the simplest.

```c
struct s1 {
    int x;
};
struct s2 {
    int y;
};
struct comp {
    struct s1 a;
    struct s2 b;
};

int main(void) {
    struct s1 s = {0};
    struct comp invalid = _Generic( (s),
        struct s1 : (struct comp){ .a = s },
        struct s2 : (struct comp){ .b = s },
    );
    struct comp valid = _Generic( (s),
        struct s1 : (struct comp){ .a = _Generic((s), struct s1: s, default: (struct s1){0}) },
        struct s2 : (struct comp){ .b = _Generic((s), struct s2: s, default: (struct s2){0}) }
    );
    return 0;
}
```

The invalid version is a semantically sensible expression if the controlling expression has a type which would result in the branch it is associated with being evaluated, while the valid version has to bend over backwards to satisfy the compiler by adding dead code.

The interpretation that leads to the invalid one being rejected seems strange to me, because it's an interpretation that explicitly requires dead code for no benefit. Meanwhile, both interpretations as far as I can tell fit with the definition set forth by the standard.

I would not consider the uniformity of compilers on this subject necessarily indicative of a good choice, especially considering permitting this code would strictly be a relaxation of a constraint and would not change the interpretation of existing code.

**Comment by AaronBallman** [comment]
> Meanwhile, both interpretations as far as I can tell fit with the definition set forth by the standard.

But it doesn't -- the standard specifies a grammar term `assignment-expression` for the association and that has specific semantics that we're required to check. There's no allowance for invalid assignment expressions just because the association is not taken.

> I would not consider the uniformity of compilers on this subject necessarily indicative of a good choice, especially considering permitting this code would strictly be a relaxation of a constraint and would not change the interpretation of existing code.

It's not intended to indicate a good choice of language design, it's indicating that all the implementations agree that the code is not valid which suggests that we're all reading the standard correctly.

We could relax the restriction as a conforming extension, but I'm not convinced that's a good design either as that would then allow for less sensible uses as well. Consider:
```
_Generic(something,
    int : 1,
    float : strlen(12)
);
```
By allowing semantically invalid (but syntactically valid) code in the untaken branches, it's now significantly easier to "hide" mistakes that will only be caught by exhaustive testing. Another benefit to the current approach is with AST representation -- allowing invalid code in untaken branches means the AST is more complicated to produce (have to wait until we've seen all associations before we can form the AST nodes in order to avoid semantic analysis on untaken branches) and consume (ast dumping, ast matching, etc all need to handle semantically invalid code that they're not expecting). So there is benefit to the approach taken by the standard, but it comes with tradeoffs like you've seen.

**Comment by cor3ntin** [comment]
> By allowing semantically invalid (but syntactically valid) 
To the extent that we could support such a thing, which is not possible in the presence of a context-dependent grammar :)

We would be limited to having un-checked token soup, which seems undesirable.
