### ISSUE TITLE
[flang] Extension: etime intrinsic for OpenRadioss application

### ISSUE THREAD

**Issue by DavidTruby** [llvm/llvm-project#84205]
The etime intrinsic is an extension provided by some other Fortran compilers (for example [gfortran](https://gcc.gnu.org/onlinedocs/gfortran/ETIME.html)). GFortran provides this intrinsic as both a subroutine and a function. 
The function version of this extension is used by OpenRadioss.
Syntax:
```
CALL ETIME(VALUES, TIME)
TIME = ETIME(VALUES)
```
Arguments:
```
VALUES	The type shall be REAL(4), DIMENSION(2).
TIME	The type shall be REAL(4).
```
Return value:
    Elapsed time in seconds since the start of program execution.

Example:
```
program test_etime
    integer(8) :: i, j
    real, dimension(2) :: tarray
    real :: result
    call ETIME(tarray, result)
    print *, result
    print *, tarray(1)
    print *, tarray(2)   
    do i=1,100000000    ! Just a delay
        j = i * i - i
    end do
    ETIME(tarray, result)
    print *, result
    print *, tarray(1)
    print *, tarray(2)
end program test_etime
```

**Comment by JumpMasterJJ** [comment]
I've been working on this issue lately. I noticed that there is already an assignee for this issue, but when I started working on the issue, there wasn't assignee. Since I couldn't directly assign it to myself, I was unable to update the assignee status. I sincerely apologize to  @mjklemm .

And there is my progress https://github.com/llvm/llvm-project/pull/90578.

My apology again.
![微信截图_20240430180056](https://github.com/llvm/llvm-project/assets/56027356/0601dae0-7bea-4c16-b72a-83e9e9e605c6)

**Comment by mjklemm** [comment]
No worries at all!  Please continue working on it!  I have assigned this to you now.  I'll be happy to help review your PR.

**Comment by mjklemm** [comment]
Closing this issue, as `etime` was implemented.

**Comment by mjklemm** [comment]
Thanks to @JumpMasterJJ for doing the implementation!
