### ISSUE TITLE
libcxx doesn't build on FreeBSD 14/amd64

### ISSUE THREAD

**Issue by rorth** [llvm/llvm-project#84476]
When trying to build LLVM 18.1.0 on FreeBSD 14.0/amd64 with `test-release.sh`, I failed miserably for `libcxx`:
* As I'd painfully discovered during a similar attempt for 17.0.6, `libcxx` needs (a variant of) `libcxx/cmake/caches/FreeBSD.cmake` to build at all (which I consider misguided; more on that below) and a checkout of `libcxxrt` (since FreeBSD doesn't deliver all the necessary headers).
* The attempt for 18.1.0 failed however:
```
FAILED: libcxx/src/CMakeFiles/cxx_shared.dir/exception.cpp.o
[...]
In file included from /var/llvm/reltest/llvm-18.1.0/final/llvm-project/libcxx/sr
c/exception.cpp:14:
/var/llvm/reltest/llvm-18.1.0/final/Phase2/Release/llvmCore-18.1.0-final.obj/run
times/runtimes-bins/libcxx/private-abi-headers/cxxabi.h:207:7: error: '__cxa_all
ocate_exception' is missing exception specification 'throw()'
  207 | void *__cxa_allocate_exception(size_t thrown_size);
      |       ^
      |                                                    throw()
/var/llvm/reltest/llvm-18.1.0/final/Phase2/Release/llvmCore-18.1.0-final.obj/inc
lude/c++/v1/__exception/exception_ptr.h:32:36: note: previous declaration is her
e
   32 | _LIBCPP_OVERRIDABLE_FUNC_VIS void* __cxa_allocate_exception(size_t) thro
w();
      |                                    ^
```
  and similar failures for `__cxa_free_exception` and `__cxa_init_primary_exception`.
* That `libcxxrt` checkout had been at
```
commit 03c83f5a57be8c5b1a29a68de5638744f17d28ba (HEAD -> master, origin/master, origin/HEAD)
Author: itrofimow <i.trofimow@yandex.ru>
Date:   Wed Oct 11 17:15:26 2023 +0300

    add __cxa_init_primary_exception (#23)
```
  where the three declarations lack the `throw()`.
* When updating `libcxxrt` to `HEAD`, the compile failures vanished.  However, the freshly build `libc++.so` has a reference to `__cxa_init_primary_exception` which isn't defined in `/usr/lib/libcxxrt.so`.  It might be possible to avoid this by defining `_LIBCPP_AVAILABILITY_HAS_INIT_PRIMARY_EXCEPTION` to `0` in `libcxx/include/__availability`, but I got tired of the nightmares those problems had caused me for both 17.0.6 and 18.1.0.

In the end, I took a different route: I chose to forget about `libcxxrt` completely, built both `libc++abi` and `libunwind` and link those objects directly into `libc++.so`.  I used the following cache file for that, which finally allowed the build to succeed (well, until the next unrelated failure):
```
set(LIBCXX_CXX_ABI libcxxabi CACHE STRING "")
set(LIBCXXABI_ENABLE_SHARED OFF CACHE BOOL "")
set(LIBUNWIND_ENABLE_SHARED OFF CACHE BOOL "")
set(LIBCXX_ENABLE_STATIC_ABI_LIBRARY ON CACHE BOOL "")
set(LIBCXXABI_ENABLE_STATIC_UNWINDER ON CACHE BOOL "")
```
To expand on the problems I see with `libcxx`'s use of cache files:
* They seem perfectly fine for cases where you just build a variant of `libcxx`, like different optimization or debug levels, use of asan or similar.
* However, in some cases (like FreeBSD), they are necessary for the build to succeed at all (well, they were in LLVM 17), with the exception that you still need a checkout of `libcxxrt`.  I'd argue that in cases like this they should be used automatically instead of having unaware users run into all sorts of build failures.  IMO the cmake files should diagnose issues like necessary but missing `libcxxrt` sources automatically and error out if necessary.  That would be way better than letting the build for hours and then fail for issues that could have been discovered up front.
* This is even more important for developers that don't build for some target every other day, but just want that build for comparison's sake with their primary targets.  Having been through such an ordeal once makes me very shy of trying this ever again.

Maybe the FreeBSD maintainers (@DimitryAndric, @brooksdavis) can comment on this?

**Comment by DimitryAndric** [comment]
Yes, the "sudden" addition of the __cxa_allocate_exception and friends with incompatible prototypes, without any option to turn them off, has caused a lot of headaches. It's unfortunate that this appeared seemingly out of nowhere in libc++, and it's even only meant as an optimization!

I think we tried to work around it by updating the prototypes in libcxxrt to match as much as possible (fully matching is impossible, since libstdc++ and libc++ use incompatible declarations), but there is no way to retroactively fix that for old FreeBSD releases.

Building against a checked-out-by-hand libcxxrt is also possible of course, but then you have to make sure it finds the freshly built libcxxrt.so instead of the system version in /usr/lib/libcxxrt.so. And another obvious workaround is to use libc++abi instead of libcxxrt.

(since it's probably also of interest for @davidchisnall, a ping here)

**Comment by ldionne** [comment]
Our aim with libc++ is to provide a general purpose build configuration that can then be configured by each vendor based on their needs. Depending on what you're actually trying to accomplish, you may want to use libc++abi or libcxxrt:
- Are you building a full toolchain for use on FreeBSD?
- What are your compatibility requirements with other system libraries?

The answer to these questions should drive whether you want to use the `FreeBSD` cache or not. By the way, we should rename the `FreeBSD.cmake` cache to `FreeBSD-system.cmake` or something like that, to embody the fact that this is the configuration used to match a system-provided libc++ but isn't necessarily the only configuration that makes sense on FreeBSD.

Overall, I think the main culprit here is that the default libc++ build looks like it's trying to give you a system FreeBSD configuration by default because of this line: https://github.com/llvm/llvm-project/blob/d2dff43170858459e03f9c8c764bf472ae7a59fa/libcxx/CMakeLists.txt#L232. In reality, we should be platform agnostic at that point in the build.

**Comment by ldionne** [comment]
> Yes, the "sudden" addition of the __cxa_allocate_exception and friends with incompatible prototypes, without any option to turn them off, has caused a lot of headaches. It's unfortunate that this appeared seemingly out of nowhere in libc++, and it's even only meant as an optimization!

I am confused -- we've been providing `__cxa_allocate_exception` forever in libc++abi. I think what you mean is that when @itrofimow introduced `__cxa_init_primary_exception`, a forward-declaration of `__cxa_allocate_exception` was added in https://github.com/llvm/llvm-project/blob/d2c49f13d8e8a5f7257b217dfe2c44ecbeb5a405/libcxx/include/__exception/exception_ptr.h#L43 and it looks like that forward-declaration is simply wrong when libcxxrt is used. If that's it, we should just fix it and cherry-pick back to LLVM 18. Does that make sense? What is the prototype of `__cxa_throw_exception` in libcxxrt?

**Comment by itrofimow** [comment]
Hi.

I've made a stupid mistake during manual testing of these changes against libcxxrt, and what should've been a seamless optimization came out as a mess w.r.t. FreeBSD/libcxxrt, I'm sorry for the headache it caused for everyone involved.

The prototypes of `__cxa_*` functions have been adjusted in libcxxrt, so the forward-declarations added are wrong for older versions of libcxxrt and are correct for the newer ones. 
I think the right way to fix that is to only have these forward-declarations in libc++ under `_LIBCPP_AVAILABILITY_HAS_INIT_PRIMARY_EXCEPTION` ifdef @ldionne.

Considering there could be some other exceptions-related ABI-additions (https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p2927r1.html), should we have a CI-configuration for `libc++` + `libcxxrt`?

**Comment by ldionne** [comment]
@itrofimow Can you make a patch for guarding the forward declaration? I can review it.

However, I don't think availability markup is used on FreeBSD so I'm not certain how that will help anything? FreeBSD doesn't allow deploying to older systems anyways, right?
