### ISSUE TITLE
Missing Optimization of Logic expression

### ISSUE THREAD

**Issue by colin-arnet** [llvm/llvm-project#84916]
Clang -O3 is not able to optimize the logic operation unlike gcc.
https://godbolt.org/z/jhnv7evGq

Source:
```
int a, c;
static int b = 4294967295;
char d;
int main() {
    c = 0;
    for (; c < 8; c = c + 3){
        d < b && (b = 0);
    }
    return d;
}
```
x86 -O3 Assembly:
```
main:                                   # @main
        movsbl  d(%rip), %eax
        movzbl  b(%rip), %ecx
        leal    -1(%rcx), %edx
        cmpb    %dl, %al
        setl    %sil
        orb     %sil, %cl
        leal    -1(%rcx), %edx
        cmpb    %dl, %al
        setl    %dl
        orb     %dl, %cl
        orb     %dl, %sil
        notb    %sil
        leal    -1(%rcx), %edx
        cmpb    %dl, %al
        setge   %dil
        testb   %dil, %sil
        jne     .LBB0_2
        cmpb    %dl, %al
        setl    %dl
        orb     %cl, %dl
        movb    %dl, b(%rip)
.LBB0_2:
        movl    $9, c(%rip)
        retq
c:
        .long   0                               # 0x0

d:
        .byte   0                               # 0x0

a:
        .long   0                               # 0x0
```

**Comment by dtcxzyw** [comment]
Missed optimizations from fuzzer-generated code are not accepted since real-world applications are unlikely to benefit from them :(
See also my previous comment https://github.com/llvm/llvm-project/issues/83812#issuecomment-1976959088 and nikic's comment https://github.com/llvm/llvm-project/issues/67813#issuecomment-1741704229.

@nikic Should we establish a policy for issues about missed optimizations and bugs found by fuzzers?

**Comment by EugeneZelenko** [comment]
@dtcxzyw: I think it will be good idea to work on bugs discovered by fuzzers. But all such issues should be properly attributed/labeled, so developers could manage their priorities in better way.

**Comment by nikic** [comment]
Agree with @dtcxzyw, this is wontfix.
