### ISSUE TITLE
GCC compatibility: Raw strings in C mode

### ISSUE THREAD

**Issue by Alcaro** [llvm/llvm-project#85703]
GCC in -xc -std=gnuNN mode accepts C++11 raw strings. https://godbolt.org/z/qoM55qqfz
```c++
// Type your code here, or load an example.
const char * square(void) {
    return R"(a"b"c)";
}
```
Perhaps Clang should too?

(Ideally, I'd like to see that feature present in C3x or something, but that's far off. It would technically break existing source code that #defines R to [something funny](https://godbolt.org/z/EWYa3hvhh).)

**Comment by shafik** [comment]
CC @AaronBallman @cor3ntin

**Comment by Sirraide** [comment]
I was thinking we could consider supporting it if `R` is not `#define`’d, but that runs into some annoying edge cases:
```c
#define FOO R"(")"
#define R "bar"

FOO // What does this expand to?
```

Or alternatively:
```c
#define R "bar"
#define FOO R"("
#undef R

FOO // What does this expand to?
```
As I see it, what `FOO` would expand to here would end up depending on where the macro is defined, not where it is used, which runs contrary to how macros normally work—that or we’d have to treat `R"(")"` and `R"("` e.g. as an annotation token, because one of those is always an invalid string literal; which one depends on whether we allow raw strings or not. That sounds doable in theory, but I’m not sure it’s worth the hassle of making sure we don’t explode as soon as you try and do anything funny with it...

**Comment by zygoloid** [comment]
Accepting this in GNU C (`-std=gnuXY`) but not in ISO C (`-std=cXY`) might be reasonable.

**Comment by Sirraide** [comment]
> Accepting this in GNU C (`-std=gnuXY`) but not in ISO C (`-std=cXY`) might be reasonable.

Yeah, on second thought, it looks like that’s what GCC does, and that would probably be the most straight-forward thing to do (and to be honest, I’d hope that no-one is `#define`’ing `R` to anything and then *also* attempting to use raw strings *in C* with their standard set to `-std=gnuWhatever`, so this isn’t very likely to break anyones code—not to mention that it’d also break w/ GCC anyway).

**Comment by AaronBallman** [comment]
> Accepting this in GNU C (`-std=gnuXY`) but not in ISO C (`-std=cXY`) might be reasonable.

Yeah, I like this approach, but I'd also be fine if we added `-fraw-string-literals` to allow users to opt into the feature in `-std=C` modes as a non-conforming language extension. That allows us to also expose the feature in C++98/03 modes.

**Comment by Sirraide** [comment]
How about both: we add `-fraw-string-literals` and enable it by default in `-std=gnu` modes only?

**Comment by AaronBallman** [comment]
> How about both: we add `-fraw-string-literals` and enable it by default in `-std=gnu` modes only?

Sorry for not being clear, but yes, that's what I think we should do.

**Comment by Sirraide** [comment]
Sounds simple enough; I’ll take a look at it
