### ISSUE TITLE
clang-diagnostic checker is active even though turned off in config

### ISSUE THREAD

**Issue by infn-ke** [llvm/llvm-project#85777]
When using clang-tidy 16 I can see that checker from clang-diagnostic- * gets applied even I have explicitly disabled it. I'm running clang-tidy via cmake with clang-tidy file like this; 

```yaml
---
Checks: >
    -*,
   bugprone-integer-*
WarningsAsErrors: >
    *
...
```

**Comment by PiotrZSL** [comment]
This is because of WarningsAsErrors.
Fixed in Clang-tidy 17:
_"WarningsAsErrors (–warnings-as-errors=) no longer promotes unlisted warnings to errors. Only the warnings listed in Checks (–checks=) will be promoted to errors. For custom error promotion, use -Werror=<warning> on the compiler command-line, irrespective of Checks (–checks=) settings."_

**Comment by infn-ke** [comment]
> This is because of WarningsAsErrors. Fixed in Clang-tidy 17: _"WarningsAsErrors (–warnings-as-errors=) no longer promotes unlisted warnings to errors. Only the warnings listed in Checks (–checks=) will be promoted to errors. For custom error promotion, use -Werror= on the compiler command-line, irrespective of Checks (–checks=) settings."_

Listed in release note

https://releases.llvm.org/17.0.1/tools/clang/tools/extra/docs/ReleaseNotes.html
