### ISSUE TITLE
Casts are incorrect in the presence of FLT_EVAL_METHOD

### ISSUE THREAD

**Issue by AaronBallman** [llvm/llvm-project#86304]
C23 6.5.5p7 says: "If the value of the expression is represented with greater range or precision than required by the type named by the cast (6.3.1.8), then the cast specifies a conversion even if the type of the expression is the same as the named type and removes any extra range and precision."

(This wording also exists in C99 but was a footnote then.)

It seems that `#pragma clang fp eval_method` does not properly implement this. Consider:
```
 #pragma clang fp eval_method(double)
 _Static_assert((float)(123.0F * 2.0F) == (float)246.0F, "");
```
The AST dump for this is:
```
TranslationUnitDecl
`-StaticAssertDecl <line:2:2, col:60> col:2
  |-ImplicitCastExpr <col:17, col:50> '_Bool' <IntegralToBoolean> FPEvalMethod=1
  | `-BinaryOperator <col:17, col:50> 'int' '==' FPEvalMethod=1
  |   |-ImplicitCastExpr <col:17, col:38> 'double' <FloatingCast> FPEvalMethod=1
  |   | `-CStyleCastExpr <col:17, col:38> 'float' <FloatingCast> FPEvalMethod=1
  |   |   `-ParenExpr <col:24, col:38> 'double'
  |   |     `-BinaryOperator <col:25, col:34> 'double' '*' FPEvalMethod=1
  |   |       |-ImplicitCastExpr <col:25> 'double' <FloatingCast> FPEvalMethod=1
  |   |       | `-FloatingLiteral <col:25> 'float' 1.230000e+02
  |   |       `-ImplicitCastExpr <col:34> 'double' <FloatingCast> FPEvalMethod=1
  |   |         `-FloatingLiteral <col:34> 'float' 2.000000e+00
  |   `-ImplicitCastExpr <col:43, col:50> 'double' <FloatingCast> FPEvalMethod=1
  |     `-CStyleCastExpr <col:43, col:50> 'float' <NoOp> FPEvalMethod=1
  |       `-FloatingLiteral <col:50> 'float' 2.460000e+02
  `-StringLiteral <col:58> 'NULL TYPE' lvalue ""
```
(https://godbolt.org/z/MGsdc4hzM)

Note that the C-style cast to `float` exists in the AST but is immediately undone by the implicit cast back to `double` due to the evaluation method. I believe the implicit casts are incorrect.

**Comment by AaronBallman** [comment]
CC @andykaylor @zahiraam

**Comment by andykaylor** [comment]
I think the fact that you're using that pragma creates a break from the standard.

I was a bit surprised to see that we are applying the eval method to comparisons, but I think that's consistent with what the documentation says. The pragma basically says that for the section of code to which it applies, we follow the rules we would have if the code had been compiled with -ffp-eval-method=<method>. The documentation for -ffp-eval-method=double says, "The compiler uses double as the floating-point evaluation method for all float expressions of type that is narrower than double." I take this as a reference to FLT_EVAL_METHOD. If FLT_EVAL_METHOD is 1 (double), the standard says "all operations and constants evaluate in the range and precision of double." Does "all operations" include comparisons? I suppose it does.

I think what is happening in your example matches that documentation.

1. The constants 123.0F and 2.0F are converted to double
2. We perform the multiplication at double precision
3. The result is truncated to single precision because of the explicit cast
4. The truncated value is extended to double precision to be used in the comparison operation

It's weird and inefficient, but it's what we said we'd do.

This led me to consider a different example:

```
#pragma clang fp eval_method(double)
int foo(float x, float y, float z) {
  return ((x / y) == z);
}
```

With no casts, this will evaluate x/y at double precision and leave the result at double precision for a comparison with z extended to double precision. If I call this as `foo(1.0f, 10.0f, 0.1f)`, it returns zero because the double precision representation of 0.1 isn't equal to 0.1f extended to double precision. If I insert an explicit cast to truncate the result of x/y to float, it will immediately promote it back to double for the comparison, but this time the comparison finds the values to be equal.

https://godbolt.org/z/Mj3qTs1jb

The only other compiler I'm aware of that supports similar behavior is ICC. It has the same behavior for my example:

https://godbolt.org/z/no7n7vjfM

**Comment by vinc17fr** [comment]
> If I call this as `foo(1.0f, 10.0f, 0.1f)`, it returns zero because the double precision representation of 0.1 isn't equal to 0.1f extended to double precision.

If the evaluation method is double (FLT_EVAL_METHOD is 1) as in your example, then `0.1` and `0.1f` should both be evaluated in double precision, thus be equal. But clang is currently buggy on this point: #88956.

**Comment by andykaylor** [comment]
> > If I call this as `foo(1.0f, 10.0f, 0.1f)`, it returns zero because the double precision representation of 0.1 isn't equal to 0.1f extended to double precision.
> 
> If the evaluation method is double (FLT_EVAL_METHOD is 1) as in your example, then `0.1` and `0.1f` should both be evaluated in double precision, thus be equal. But clang is currently buggy on this point: #88956.

In my example, the 0.1f constant is passed as an argument to a function call, so it would be truncated to single precision at that point, I think. I see your point about the handling of constants in general, but I have some questions about how that should be applied, which I'll ask on the other issue.

**Comment by vinc17fr** [comment]
> In my example, the 0.1f constant is passed as an argument to a function call, so it would be truncated to single precision at that point, I think.

It is indeed passed as an argument. I've just checked, and C17 has a footnote about the `return` statement saying: "The `return` statement is not an assignment. [...] The representation of floating-point values may have wider range or precision than implied by the type; a cast may be used to remove this extra range and precision." So the value will not be converted to single precision. The (non-public) N3149 C23 draft has the same footnote.

That said, I don't think that the absence of conversion can be guaranteed in practice, in case the conversion would be implied by the ABI.

**Comment by vinc17fr** [comment]
This is actually more complex concerning the `return` statement. See from the JTC1/SC22/WG14 documents:
* [N1017: FLT_EVAL_METHOD and extra precision and/or range](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1017.htm)
* [N1382: FLT_EVAL_METHOD and return](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1382.htm)
* [N1396: Wide function return values](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1396.htm)
* [N2172: return and extra precision](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2172.htm)

**Comment by AaronBallman** [comment]
> I think the fact that you're using that pragma creates a break from the standard.

Yeah, though I was thinking of it in the context of `FLT_EVAL_METHOD`.

> I was a bit surprised to see that we are applying the eval method to comparisons, but I think that's consistent with what the documentation says. The pragma basically says that for the section of code to which it applies, we follow the rules we would have if the code had been compiled with -ffp-eval-method=. The documentation for -ffp-eval-method=double says, "The compiler uses double as the floating-point evaluation method for all float expressions of type that is narrower than double." I take this as a reference to FLT_EVAL_METHOD. If FLT_EVAL_METHOD is 1 (double), the standard says "all operations and constants evaluate in the range and precision of double." Does "all operations" include comparisons? I suppose it does.
> 
> I think what is happening in your example matches that documentation.
> 
>     1. The constants 123.0F and 2.0F are converted to double
> 
>     2. We perform the multiplication at double precision
> 
>     3. The result is truncated to single precision because of the explicit cast
> 
>     4. The truncated value is extended to double precision to be used in the comparison operation
> 
> 
> It's weird and inefficient, but it's what we said we'd do.

Oh, I think you're correct -- this is doing what we'd expect, just in a roundabout way. I think this issue can be closed, do you agree?

**Comment by andykaylor** [comment]
Yes, I agree that this can be closed.
