### ISSUE TITLE
`std::variant<std::string>{}.index()` is not an integral constant expression

### ISSUE THREAD

**Issue by hewillk** [llvm/llvm-project#86686]
Clang rejects the following. 
Not sure if it's just because a certain language feature isn't implemented yet, correct me if I'm missing something.

```cpp
#include <variant>
#include <string>

static_assert(std::variant<std::string>{}.index() == 0);
```
https://godbolt.org/z/8cTnafsMd

**Comment by mordante** [comment]
I strongly suspect it needs this PR before it works https://github.com/llvm/llvm-project/pull/83335

**Comment by philnik777** [comment]
Yes, this is simply not implemented yet in libc++.

**Comment by huixie90** [comment]
> Yes, this is simply not implemented yet in libc++.

I could argue that it is a bug in libc++.  In #83335, I implemented a paper which added "constexpr" to some operations. However, the default constructor was `constexpr` since the beginning and we did not make `variant<string>` default constructor useable in constexpr context. (We only made trivial types usable in constexpr). In any case, I fixed it in #83335 and added a test for this particular example

**Comment by philnik777** [comment]
@huixie90 The destructor is non-trivial and not `constexpr`, making it a non-literal type. That's the reason this is rejected currently, and for that to work we have to implement P2231R1.

**Comment by philnik777** [comment]
@ldionne I'm a bit confused? We don't implement that paper, which we don't currently track as bugs. Why should this stay open?

**Comment by ldionne** [comment]
We don't track unimplemented papers as Github Issues indeed, however I wasn't under the impression that we'd go ahead and close any issue that tracks the implementation of a paper? Either way seems fine to me, but I thought it would make sense to close this when we merge #83335.

**Comment by ldionne** [comment]
I see. That seems fine to me if we don't have a PR. In this case, since there's a PR open I think it's better to add the right markup in the PR so the issue gets closed when the PR is merged. That way we leave breadcrumbs of where things are being implemented. Either way I don't care strongly about what we do with this specific issue.

At the end of the day I think we both agree we should be tracking papers and LWG issues in Github issues instead.
