### ISSUE TITLE
Does llvm14-flang or flang-new support the option "-emit-llvm"?

### ISSUE THREAD

**Issue by linkeyu** [llvm/llvm-project#86764]
I try to execute the command “flang -emit-llvm -c xx.f90“ , but I don`t get any bitcode.The version of llvm is 14.0.0.So I want to ask whether llvm14-flang or flang-new supports the option "-emit-llvm" or not?
Thanks

**Comment by banach-space** [comment]
Hi @linkeyu , thanks for opening this ticket!

As this is more of a generic question rather than an issue, I'd suggest using https://discourse.llvm.org/c/subprojects/flang/33 instead. You are likely to reach a much wider group of experts there 😅 

I don't really know the answer to your specific question - most (all) active developers only work with the latest version of LLVM. That one should work. LLVM 18 and LLVM 17 should also be fine. Not sure about the older versions.

-Andrzej
