### ISSUE TITLE
[SPIRV]  Failed Test CodeGen/SPIRV/pointers/struct-opaque-pointers.ll in Spirv prs

### ISSUE THREAD

**Issue by farzonl** [llvm/llvm-project#86872]
error: line 26: OpConstantComposite Constituent <id> '11[%11]' type does not match the Result Type <id> '6[%_struct_6]'s member type.

Link to failing build: https://github.com/llvm/llvm-project/actions/runs/8456494046/job/23166392032?pr=86844

It also failed on Builds:
https://github.com/llvm/llvm-project/actions/runs/8439402372/job/23113920601#step:8:3459
https://github.com/llvm/llvm-project/actions/runs/8423428747/job/23065142060#step:8:3459

It looks very likely that the cause of this bug is: https://github.com/llvm/llvm-project/pull/86352/files#diff-2bfdf1e4099b5b273fa6227bed91515ce764fb5fefaeafbfbf83d6896944958f

For awareness: @sudonatalie

**Comment by farzonl** [comment]
Does it make sense to disable this test for now?

**Comment by VyacheslavLevytskyy** [comment]
> @VyacheslavLevytskyy It looks like PR #86352 is still having issues in the pr pipeline. Does it make sense to disable this test for now?

It could make sense, but PR https://github.com/llvm/llvm-project/pull/86782 should fix it. Hopefully it's a better way forward.
CC: @michalpaszkowski

**Comment by farzonl** [comment]
> > @VyacheslavLevytskyy It looks like PR #86352 is still having issues in the pr pipeline. Does it make sense to disable this test for now?
> 
> It could make sense, but PR #86782 should fix it. Hopefully it's a better way forward. CC: @michalpaszkowski

What is the spir-v backends project guidance on build\test breaks? I know in other parts of llvm the guidance is to revert a pr or put in a fix as soon as possible  ussually within an hour. However this is an experimental backend so I understand if that kind of diligence is counter productive.

**Comment by VyacheslavLevytskyy** [comment]
@farzonl Thank you.
PR https://github.com/llvm/llvm-project/pull/86782 is merged.

**Comment by VyacheslavLevytskyy** [comment]
@farzonl 
Talking about the reasons of the regression, PR https://github.com/llvm/llvm-project/pull/86352 did pass with this test. The next PR https://github.com/llvm/llvm-project/pull/85979, however, have added further useful steps in type inferring and struct instead of fully unevaluated in sense of types, became semi-evaluated, that broke "spirv-val" call. So, in theory, if the path forward was to revert the PR, it'd 85979. On the other hand, 85979 was a very good and right move, in my opinion, so instead of reverting any of two PR's I added more advanced type inference that fixed the issue in the test with the broken "spirv-val" call at the same time. I guess, the most correct option in this case was, however, to just temporarily mark that broken test as xfail to keep the test suite fully correct at any moment of time. Thank you for your attention to this, and please check if the newest https://github.com/llvm/llvm-project/pull/86782 indeed resolved the issue.
CC: @michalpaszkowski @sudonatalie

**Comment by farzonl** [comment]
@VyacheslavLevytskyy  PR https://github.com/llvm/llvm-project/pull/86782 fixed the build
:https://github.com/llvm/llvm-project/actions/runs/8468716557/job/23202386285?pr=86844 
resolving this bug as fixed!
