### ISSUE TITLE
Fixing ParentMapContext.cpp to fix O(n^2) slowdown in hasParent() AST matchers

### ISSUE THREAD

**Issue by higher-performance** [llvm/llvm-project#86881]
AST matchers that reference parent nodes (e.g., `hasParent()`) can slow down **severely** (from O(seconds)/O(minutes) to O(hours)/timeouts) on large translation units, due to what appears to be a quadratic slowdown.

We have narrowed this down to the following lines, where it appears that the call to `llvm::is_contained(*Vector, ParentStack.back())` performs a linear search through a large vector, making parent lookups unusably slow.

https://github.com/llvm/llvm-project/blob/57b40b5f34383634949d1639e64a5c2acd0dc5f6/clang/lib/AST/ParentMapContext.cpp#L390-L398

Could this be fixed?

For what it's worth, at first glance, I thought that switching to binary search (and thus slowing down _insertions_ rather than lookups) would be a better trade-off that alleviates this concern, because insertions only happen once per element, whereas lookups can occur many times.

```
      auto less = [](const DynTypedNode &a, const DynTypedNode &b) {
        return b.getMemoizationData() && (!a.getMemoizationData() || a < b);
      };
      if (!ParentStack.back().getMemoizationData() && llvm::binary_search(*Vector, ParentStack.back(), less)) {
        Vector->insert(llvm::upper_bound(*Vector, ParentStack.back(), less), ParentStack.back());
      }
```

**Edit (after replies):** I believe this should preserve the correctness of the binary search, despite the fact that `DynTypedNode` appears to lack comparability for some types, since it partitions the vector and only searches the comparable portion.

**Comment by shafik** [comment]
CC @sam-mccall @AaronBallman

**Comment by AaronBallman** [comment]
Yeah, this is the first I recall hearing about a linear scan. My understanding on the challenge is that it's two-fold: 1) the AST matcher code is carefully crafted to try to avoid explosion of compile time overhead from all the template instantiations that happen for the DSL, so reasoning about the code is harder and it can be easy to accidentally regress compile-time performance, 2) we may not have memoized what we needed to depending on how the traversal happened (e.g., traverse while ignoring code not spelled in source, then `getParent()` up to a node that was skipped). Some of this may have improved since the last time I investigated this.

My intuition is that you're correct regarding trying to switch over to a binary tree so the expense is paid on insertion rather than on lookup, but I also don't recall whether TU size or AST matcher complexity will mean that change causes some situations get faster while others get slower. It certainly seems worth trying!
