### ISSUE TITLE
'class std::set<llvm::BasicBlock*>' has no member named 'completed'

### ISSUE THREAD

**Issue by Victor725** [llvm/llvm-project#87152]
An error enconted when I compiling an llvm pass.
In this pass, I go over all blocks in a function with api provided by DepthFirstIterator.h.
The error code in the pass as follows:
```
std::set<BasicBlock*> visitedSet;
for (auto i = df_ext_begin<BasicBlock*,std::set<BasicBlock*>>(&F.getEntryBlock(), visitedSet),
                e = df_ext_end<BasicBlock*,std::set<BasicBlock*>>(&F.getEntryBlock(), visitedSet);
                
                i != e; i++);
```
the error is:
![image](https://github.com/llvm/llvm-project/assets/55656122/ae12e2fb-e17e-4d94-b627-4a46deedd153)
It says that class set has no member named "completed". Is this a matter of my version of c++?

**Comment by marcauberer** [comment]
No, the C++ version is not the problem here. The implementation of DepthFirstIterator expects the given set type to implement the `completed(NodeRef)` method see [here](https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/ADT/DepthFirstIterator.h#L143). What you can do is to not use `std::set<BasicBlock*>`, but a container, that offers this method. Maybe take a look here: 

https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/ADT/DepthFirstIterator.h#L69-L78

Maybe you can use `df_iterator_default_set` directly for your usecase.

**Comment by Victor725** [comment]
OK, Thank you very much! :)
