### ISSUE TITLE
[flang] Imaginary part contains random information when passing real parameter to complex dummy argument

### ISSUE THREAD

**Issue by DavidTruby** [llvm/llvm-project#87349]
When passing a real to a subroutine that expects a complex, the imaginary part of the complex is not zeroed but has random values in it. In the following case as an example:
```
subroutine prcplx(cx)
  implicit none
  complex :: cx

  print *, "value", cx
end subroutine

program complex_args
  implicit none
  real, parameter :: val = 123.0

  call prcplx(val)
end program
```
a warning is issued that "If the procedure's interface were explicit, this reference would be in error" but the code still compiles, and the complex value is incorrect.

Classic flang and gfortran both zero the imaginary part.
We observed this behaviour in a real application so even though the code is probably not strictly correct it would be good to get this fixed.

**Comment by klausler** [comment]
gfortran emits a hard error for this test case, and f18 probably should do the same, rather than a warning.

If one splits this test into two, and compiles the program units separately, you'll observe that gfortran doesn't explicitly set any "imaginary part" to zero.  It passes the address of a 32-bit real constant and the "imaginary part" is going to be whatever the linker puts after that constant.  If it "works" with gfortran, it's only by accident.
