### ISSUE TITLE
LLDB DAP StackFrame always requires a Column number

### ISSUE THREAD

**Issue by jk000** [llvm/llvm-project#87429]
For certain sources (such as `start.S`) within the stack frame, the column number does not seem to be provided by lldb-dap (built from 18.1.2).  This causes the error `The editor could not be opened due to an unexpected error: Invalid arguments`.  Visually, the line number to the right of that frame in the call stack shows a line number but lacks a colon with a column number.

According to https://microsoft.github.io/debug-adapter-protocol/specification#Types_StackFrame, a value of `0` should probably be provided in these cases.

**Comment by semensanyok** [comment]
latest LLDB response StackFrame could miss column value. 
I have encountered it during debugging: https://github.com/mfussenegger/nvim-dap/pull/1195

This is clearly a bug. Specification requires this field.

> Thanks for the PR, but I'm not going to merge this. `column` is a required property of a `StackFrame` according to the specification:
> 
> https://microsoft.github.io/debug-adapter-protocol/specification#Types_StackFrame
> 
> This needs to be fixed in the debug adapter.

**Comment by jk000** [comment]
Closing as this is a duplicate of #73393

**Comment by mikesmullin** [comment]
Getting `The editor could not be opened due to an unexpected error. Please consult the log for more details.` from VSCode w/ `lldb-dap` extension installed. Output > Extension Host log shows `[warning] Illegal argument: TextEditor(vs.editor.ICodeEditor:1,$model11)` but I verified the path and line numbers are correct in `lldb-dap.log`
