### ISSUE TITLE
clang: /root/llvm-project/clang/lib/AST/Expr.cpp:3289: bool clang::Expr::isConstantInitializer(clang::ASTContext&, bool, const clang::Expr**) const: Assertion `!isValueDependent() && "Expression evaluator can't be called on a dependent expression."' failed.

### ISSUE THREAD

**Issue by danix800** [llvm/llvm-project#88008]
Clang trunk assertion failed on the following invalid initializer:

```c
struct S {
	int v;
};

struct T;

void test(struct T *t)
{
	struct S s = { .v = t->y }; // t->y is invalid
}
```

https://godbolt.org/z/GnT41GbT5

Possibly similar to https://reviews.llvm.org/D84145.

**Comment by shafik** [comment]
Looks like we had this since clang-12: https://godbolt.org/z/ohd4bMTEh

Perhaps here: 

https://github.com/llvm/llvm-project/blob/896b5e55711121b3de4630fe1412b50d96061c1c/clang/lib/Parse/ParseInit.cpp#L509-L513

we need `if (SubElt.isUsable() && !SubElt.get()->containsErrors())` 

or maybe here:

https://github.com/llvm/llvm-project/blob/896b5e55711121b3de4630fe1412b50d96061c1c/clang/lib/Parse/ParseDecl.cpp#L2713

We need `if (Init.isInvalid() || Init.get()->containsErrors())` 

These are just some ideas from debugging the crash.

**Comment by danix800** [comment]
> Looks like we had this since clang-12: [godbolt.org/z/ohd4bMTEh](https://godbolt.org/z/ohd4bMTEh)
> 
> Perhaps here:
> 
> https://github.com/llvm/llvm-project/blob/896b5e55711121b3de4630fe1412b50d96061c1c/clang/lib/Parse/ParseInit.cpp#L509-L513
> 
> we need `if (SubElt.isUsable() && !SubElt.get()->containsErrors())`
> 
> or maybe here:
> 
> https://github.com/llvm/llvm-project/blob/896b5e55711121b3de4630fe1412b50d96061c1c/clang/lib/Parse/ParseDecl.cpp#L2713
> 
> We need `if (Init.isInvalid() || Init.get()->containsErrors())`
> 
> These are just some ideas from debugging the crash.

Thanks for pointing this out. Could you please also take a look at PR #88014 . It might be more consistent as a fix.

**Comment by shafik** [comment]
> Thanks for pointing this out. Could you please also take a look at PR #88014 . It might be more consistent as a fix.

Apologies, for the late reply. That looks like the right fix.
