### ISSUE TITLE
Why doesn't JITlink support R_X86_64_GOTTPOFF?

### ISSUE THREAD

**Issue by Thrrreeee** [llvm/llvm-project#88232]
I find [JITlink ](R_X86_64_GOTTPOFF) have't support for R_X86_64_GOTTPOFF.

> JIT session error: In maze.bc-jitted-objectbuffer: Unsupported x86-64 relocation type R_X86_64_GOTTPOFF

Why isn't support for this relocate type implemented in JITlink? Is it because it hasn't been done yet, or are there other reasons?

**Comment by lhames** [comment]
`GOTTPOFF` is used for thread locals in the static code model. This relocation assumes a contiguous TLS block, which we can't have in general in ORC because we allow you to add new code at runtime.

On all architectures that I'm aware of we could downgrade the instruction sequence to the equivalent of a TLSGD relocation to address this, but nobody has done the work to implement that yet.

Alternatively if you control the code you can compile with the dynamic relocation model (`-fPIC`), which is recommended.

**Comment by Thrrreeee** [comment]
> On all architectures that I'm aware of we could downgrade the instruction sequence to the equivalent of a TLSGD relocation to address this, but nobody has done the work to implement that yet.
> 
> Alternatively if you control the code you can compile with the dynamic relocation model (`-fPIC`), which is recommended.

@lhames Thanks for your help, I will try to implement this
