### ISSUE TITLE
llvm-lit does not search for bash in the path

### ISSUE THREAD

**Issue by llvmbot** [llvm/llvm-project#8874]
|  |  |
| --- | --- |
| Bugzilla Link | [8502](https://llvm.org/bz8502) |
| Version | trunk |
| OS | Linux |
| Attachments | [Patch for llvm-lit to look for bash in PATH](https://user-images.githubusercontent.com/60944935/143742212-3d75a5bb-1983-4478-a146-bd40a97977fb.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @emaste,@modocache |

## Extended Description 

llvm-lit disregards PATH environment variable when looking for bash. This is due to LitConfig.getBashPath always calling Utils.which with a second argument, even when this is empty. The attached patch checks of self.path is empty and in that case calls Utils.which with just one argument, making env PATH to be used.

**Comment by widberg** [comment]
This old issue seems to have been fixed by https://github.com/llvm/llvm-project/commit/853b460e4f1e169b6d806233a298a9a2f56bed4c.

Relevant code at time the issue was opened https://github.com/llvm/llvm-project/blob/3b2ad1d0455f7b84490df02d5049958d3ac9460e/llvm/utils/lit/lit/LitConfig.py#L74
today https://github.com/llvm/llvm-project/blob/69066ab31959968ebcbca71f3872bdedef8fb8cd/llvm/utils/lit/lit/LitConfig.py#L162-L164
