### ISSUE TITLE
void parameters in function types are not accepted

### ISSUE THREAD

**Issue by Halalaluyafail3** [llvm/llvm-project#89695]
While looking at the behavior for qualified void return types (which clang gets wrong) I found that clang doesn't accept void function parameters. For example:
```c
void f(void x);
```
This code should be valid just like how the following is accepted:
```c
void g(struct undef x);
```
Both `f` and `g` have parameters of incomplete types but that is OK as long as these functions aren't called and because these are not function definitions. However, clang seems to diagnose `f` which is incorrect.

**Comment by Halalaluyafail3** [comment]
I think it is also worth mentioning that the following should be valid:
```c
void foo(const void);
void bar(void,void);
```
`foo`'s parameter list is not a single unnamed parameter with the type `void` (it is instead `const void`) so it should be a single parameter of type `const void`. `bar` is a function which takes two unnamed parameters of type `void` since there are two parameters.

**Comment by frederick-vs-ja** [comment]
[WG14 N3155](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3155.pdf) claims that `void foo(const void);` is UB (by omission) in C. It's probably a defect in the C standard that these case are not yet contract violation.

In C++, [[dcl.fct]/3](https://eel.is/c++draft/dcl.fct#3) states that these declarations are ill-formed.

**Comment by AaronBallman** [comment]
There's three issues being reported here: (1) `void` parameter with an identifier, (2) qualified `void` as a parameter, and (3) multiple parameters of type `void`.

(1) is undefined behavior which we treat as being a constraint violation (GCC gives a warning instead). C23 6.7p8 "If an identifier for an object is declared with no linkage, the type for the object shall be complete by the end of its declarator, or by the end of its init-declarator if it has an initializer. In the case of function parameters, it is the adjusted type (see 6.7.7.4) that is required to be complete." -- parameters have no linkage (C23 6.2.2p6), so by giving the parameter a name, the type needs to be complete, and `void` can never be completed. See also 6.7.7.4p9 which says "an unnamed parameter".
(2) is undefined behavior which we treat as being a constraint violation (as does GCC). C23 6.7.7.4p9 "The special case of an unnamed parameter of type `void` as the only item in the list specifies that the function has no parameters." -- "of type `void`" is talking about the syntax used and `const void` is not `void`.
(3) is undefined behavior which we treat as being a constraint violation (as does GCC) by the same logic as (2) -- "an unnamed parameter" is singular. Further, 6.7.7.4p3 "After adjustment, the parameters in a parameter type list in a function declarator that is part of a definition of that function shall not have incomplete type." means that such a function could never be defined.

I don't know of any motivating reason to relax any of the diagnostics in this space. An argument could perhaps be made to relax (1) to be a warning for GCC compatibility and because you could technically do something like `typeof(param_name) *x = 0;` but that doesn't feel particularly compelling without more context. Closing the issue as not planned, but if you have compelling rationale for why we should change the behavior, feel free to reopen with more details.

**Comment by Halalaluyafail3** [comment]
> C23 6.7p8 "If an identifier for an object is declared with no linkage, the type for the object shall be complete by the end of its declarator, or by the end of its init-declarator if it has an initializer. In the case of function parameters, it is the adjusted type (see 6.7.7.4) that is required to be complete."

This text only applies to definitions of parameters in function definitions. See [DR 295](https://www.open-std.org/jtc1/sc22/wg14/www/docs/dr_295.htm) which discusses `void` parameter types and this text specifically. If this text did apply to here, then presumably incomplete structure types would be diagnosed as well since they would be violating the same requirement.

> is undefined behavior which we treat as being a constraint violation (as does GCC). C23 6.7.7.4p9 "The special case of an unnamed parameter of type `void` as the only item in the list specifies that the function has no parameters." -- "of type `void`" is talking about the syntax used and `const void` is not `void`.

Yes, so my interpretation of the wording is that this is not a zero argument function and is instead a function taking one argument of type `const void`. I don't understand why you are referencing the syntax, it seems to be clearly talking about the type (`const void` is not `void` here so the text doesn't apply). Clang accepts using a typedef for `void` to indicate no arguments and using `register` which doesn't change the type (these both change the syntax to not be `void`). I also opened a [GCC bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114816) because GCC doesn't accept this.

> is undefined behavior which we treat as being a constraint violation (as does GCC) by the same logic as (2) -- "an unnamed parameter" is singular. Further, 6.7.7.4p3 "After adjustment, the parameters in a parameter type list in a function declarator that is part of a definition of that function shall not have incomplete type." means that such a function could never be defined.

There are multiple parameters so I think that the text which appertains to a single unnamed parameter of type should just not apply instead of making the program invalid (similar to multiple parameters in general is OK). This function declaration is not part of a definition of a function so the text requiring that the types be complete shouldn't apply.

> I don't know of any motivating reason to relax any of the diagnostics in this space.

I was thinking of using this for a sort of `void*` equivalent for function pointer types (minus implicit conversions), e.g.
```c
typedef void void_fn(void x);
```
All pointers to functions could be converted to `void_fn*` and vice versa. It would be impossible to call a function of type `void_fn` because of the incomplete parameter type. Therefore it would work like a generic function pointer type which can hold any function pointer but doesn't know how to call it. This can currently be accomplished with an incomplete structure type, however the structure type could later be completed or a definition of the structure type placed before the function type and then the function could possibly be called.
