### ISSUE TITLE
`std::lock_guard` is unavailable when `_LIBCPP_HAS_NO_THREADS` is set

### ISSUE THREAD

**Issue by petrhosek** [llvm/llvm-project#89891]
When `_LIBCPP_HAS_NO_THREADS` is set,`std::lock_guard` becomes unavailable: https://github.com/llvm/llvm-project/blob/662ef8604268b207910225ecca90daf30a46720b/libcxx/include/__mutex/lock_guard.h#L19-L51

`std::lock_guard` takes mutex implementation as a template argument, so even if the platform doesn't support standard threading API, users may still want to use it with their own custom mutex implementation which is common on baremetal platforms.

This is related to issue https://github.com/llvm/llvm-project/issues/84879.

**Comment by frederick-vs-ja** [comment]
`std::unique_lock`, `std::scoped_lock`, and `std::shared_lock` should also be made available IMO.

**Comment by ldionne** [comment]
This makes sense to me. I'm not certain why they were disabled in the first place but I think it could be because `_LIBCPP_HAS_NO_THREADS` predates our other carve-outs. So it might have been done with a different design intent.

In any case, I think we should make them available if they're generic.

**Comment by nolange** [comment]
the fix is incomplete since `std::unique_lock` and consorts aren't available.
