### ISSUE TITLE
[BOLT] Segmentation fault when optimizing static-pie RELR binary using BOLT

### ISSUE THREAD

**Issue by Andarwinux** [llvm/llvm-project#90388]
For sampling BOLT, BOLT optimized binary Segmentation fault.

Tested with llvm main, any static-pie binary can reproduce this, but normal static binary has no problem.

**Comment by yota9** [comment]
Hi. Please provide arch, log, binary to reproduce.

**Comment by yota9** [comment]
Most likely would be fixed by https://github.com/llvm/llvm-project/pull/100866
But also turned out that sometimes BOLT is currently limited on opt static binaries so it would just abort during optimisation when this patch would be applied https://github.com/llvm/llvm-project/pull/100801 So currently closing the issue as I'm quite sure it duplicates other static-related issues as #100096 . Fill free to re-open it if you've got further questions
