### ISSUE TITLE
[Flang] Intrinsic LEN and C_SIZEOF returns incorrect result when the argument is a CFI_CDESC_T descriptor of character type.

### ISSUE THREAD

**Issue by DanielCChen** [llvm/llvm-project#92421]
Consider the following code:
```
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include "ISO_Fortran_binding.h"
void sub(CFI_cdesc_t* a);
int main()
{
    int rc;
    char *p = "12345";
    CFI_cdesc_t* a;
    CFI_CDESC_T(1) at1;
    a = (CFI_cdesc_t *) &at1;

    rc = CFI_establish(a, p, CFI_attribute_pointer, CFI_type_signed_char, 5, 0, 0);
    assert(rc == CFI_SUCCESS);
    sub(a);
}
```

Fortran subroutine `sub` is as:
```
      subroutine sub(c_arg2) bind(c)
        use, intrinsic :: iso_c_binding
        character(*) :: c_arg2!(*)
        print*, "LEN(c_arg2)=", LEN(c_arg2)
        print*, "c_sizeof(c_arg2)=", c_sizeof(c_arg2)
      end
```

The expected result is
```
 LEN(c_arg2)= 5
 c_sizeof(c_arg2)= 5
```

But Flang currently outputs
```
 LEN(c_arg2)= 1
 c_sizeof(c_arg2)= 1
```

**Comment by jeanPerier** [comment]
@DanielCChen, is there a reason the code is using `CFI_type_signed_char` and not `CFI_type_char`?

The problem is that `CFI_type_signed_char` is not recognized as being a character type in CFI_establish, that ends-up overriding the `elem_len` arguments (`5`) by `1`.

https://github.com/llvm/llvm-project/blob/525bd66fc29fd056ef18118dfff3c9cc05fdd5e3/flang/runtime/ISO_Fortran_binding.cpp#L116

https://github.com/llvm/llvm-project/blob/525bd66fc29fd056ef18118dfff3c9cc05fdd5e3/flang/runtime/ISO_Fortran_util.h#L21

I think flang is doing a correct interpretation given that `CFI_type_signed_char` is considered to be an integer type in in table 18.2/18.4. `CFI_type_char` should be used instead. The `CFI_establish` requirements in F2023 18.5.5.5 requires `elem_len` to be ignored if `type` is nor CFI_type_struct, nor CFI_type_other, nor a Fortran character type code.

**Comment by DanielCChen** [comment]
@jeanPerier Thanks for the comment. You are right. `c_sighed_char` is indeed listed as Fortran integer type.
