### ISSUE TITLE
Large variations in compilation times involving static_assert

### ISSUE THREAD

**Issue by pkeir** [llvm/llvm-project#92924]
I often want to be sure that an expression is evaluated at compile time, while also checking that it produces the expected value. With a `constexpr` function called `big_calc`, expected to return zero, I might either use:

```cpp
static_assert(0==big_calc());    // (1)
```

..or:

```cpp
constexpr int ret = big_calc();  // (2)
static_assert(0==ret);
```

Surprisingly, the first of these (1) runs around 49% slower than the second (2).

```cpp
constexpr int big_calc()
{
  long i = 1, count = 0, n = (1<<22);

  for (; i < n; i++)
    count = count + i;

  bool b = count == (i * (i - 1)) / 2;

  return 0;
}
```

This is true even when `big_calc` involves more calculations. I am using Ubuntu 23.10 with an Intel i9-13900K, and Clang 17.0.2. With `n` of `big_calc` set at `(1<<22)` (as above) average compilation times are 7.5 secs. for approach (1); and 5.0 secs. for approach (2).

With `n` of `big_calc` set at `(1<<24)` average compilation times are 29.7 secs. for approach (1); and 19.8 secs. for approach (2).

`$ time clang++-17 -std=c++20 -fconstexpr-steps=$((2**32-1)) double-constant-eval.cpp`

Other approaches (e.g. SFINAE/Concepts class/function templates) are also slow; and have the performance profile of method (1).

GCC behaves similarly (with 43% performance drop).

My suspicion is that the constant expression is being evaluated twice.

It does look odd that the `big_calc` function returns zero. This was reduced from a larger problem. Curiously, if `big_calc` instead returns a boolean (i.e. `b`), and the `0==` part of each constant expression is removed, the performance profile flips: now (1) is quicker than (2).

While such long constexpr calculations are unusual, it would be a pity if third-party benchmarks didn't take such effects into account.

**Comment by AaronBallman** [comment]
I get the following behavior testing on Windows:
```
PS F:\source\llvm-project> cat 'C:\Users\aballman\OneDrive - Intel Corporation\Desktop\test.cpp'
constexpr int big_calc()
{
  long i = 1, count = 0, n = (1<<22);

  for (; i < n; i++)
    count = count + i;

  bool b = count == (i * (i - 1)) / 2;

  return 0;
}

#if defined(ONE)
static_assert(0==big_calc());    // (1)
#elif defined(TWO)
constexpr int ret = big_calc();  // (2)
static_assert(0==ret);
#endif

PS F:\source\llvm-project> Measure-Command { .\llvm\out\build\x64-Release\bin\clang.exe -cc1 -triple x86_64-pc-linux -fsyntax-only -fconstexpr-steps=10485760 -DONE 'C:\Users\aballman\OneDrive - Intel Corporation\Desktop\test.cpp'}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 33
Milliseconds      : 949
Ticks             : 339491153
TotalDays         : 0.000392929575231481
TotalHours        : 0.00943030980555556
TotalMinutes      : 0.565818588333333
TotalSeconds      : 33.9491153
TotalMilliseconds : 33949.1153



PS F:\source\llvm-project> Measure-Command { .\llvm\out\build\x64-Release\bin\clang.exe -cc1 -triple x86_64-pc-linux -fsyntax-only -fconstexpr-steps=10485760 -DTWO 'C:\Users\aballman\OneDrive - Intel Corporation\Desktop\test.cpp'}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 21
Milliseconds      : 907
Ticks             : 219071033
TotalDays         : 0.000253554436342593
TotalHours        : 0.00608530647222222
TotalMinutes      : 0.365118388333333
TotalSeconds      : 21.9071033
TotalMilliseconds : 21907.1033
```
Running the tests several times gives similar timings (avg 33s for `-DONE` and 23s for `-DTWO`).

**Comment by AaronBallman** [comment]
With *no* calls to `big_calc()`, I'm getting this timing:
```
PS F:\source\llvm-project> Measure-Command { .\llvm\out\build\x64-Release\bin\clang.exe -cc1 -triple x86_64-pc-linux -fsyntax-only -fconstexpr-steps=10485760 -DNONE 'C:\Users\aballman\OneDrive - Intel Corporation\Desktop\test.cpp'}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 11
Milliseconds      : 681
Ticks             : 116816213
TotalDays         : 0.000135203950231481
TotalHours        : 0.00324489480555556
TotalMinutes      : 0.194693688333333
TotalSeconds      : 11.6816213
TotalMilliseconds : 11681.6213
```
so we may be evaluating the function multiple times, including checking its definition.

**Comment by pkeir** [comment]
Well spotted. GCC compiles the empty version in close to 0 secs.

**Comment by AaronBallman** [comment]
Yup, we evaluate the function body (we get into the evaluator starting from here: https://github.com/llvm/llvm-project/blob/df542e1ed82bd4e5a9e345d3a3ae63a76893a0cf/clang/lib/Sema/SemaDeclCXX.cpp#L2475

For `-DONE`, I see us hitting expensive calls to [`Evaluate()`](https://github.com/llvm/llvm-project/blob/e3f74d4589e29279e9f543b58577a2ece102dc6f/clang/lib/AST/ExprConstant.cpp#L15603) from the following places:

[`Sema::CheckConstexprFunctionBody()`](https://github.com/llvm/llvm-project/blob/e3f74d4589e29279e9f543b58577a2ece102dc6f/clang/lib/Sema/SemaDeclCXX.cpp#L2475)
[`Sema::BuildStaticAssertDeclaration()`](https://github.com/llvm/llvm-project/blob/e3f74d4589e29279e9f543b58577a2ece102dc6f/clang/lib/Sema/SemaDeclCXX.cpp#L17467) which eventually ends up calling https://github.com/llvm/llvm-project/blob/e3f74d4589e29279e9f543b58577a2ece102dc6f/clang/lib/Sema/SemaChecking.cpp#L13677
[`Sema::BuildStaticAssertDeclaration()`](https://github.com/llvm/llvm-project/blob/e3f74d4589e29279e9f543b58577a2ece102dc6f/clang/lib/Sema/SemaDeclCXX.cpp#L17487)

For `-DTWO`, I see us hitting the expensive calls from:

[`Sema::CheckConstexprFunctionBody()`](https://github.com/llvm/llvm-project/blob/e3f74d4589e29279e9f543b58577a2ece102dc6f/clang/lib/Sema/SemaDeclCXX.cpp#L2475)
[`Sema::AddInitializerToDecl()`](https://github.com/llvm/llvm-project/blob/e3f74d4589e29279e9f543b58577a2ece102dc6f/clang/lib/Sema/SemaDecl.cpp#L13954) which eventually calls https://github.com/llvm/llvm-project/blob/e3f74d4589e29279e9f543b58577a2ece102dc6f/clang/lib/AST/Decl.cpp#L2652

We eventually do get into [`Sema::BuildStaticAssertDeclaration()`](https://github.com/llvm/llvm-project/blob/e3f74d4589e29279e9f543b58577a2ece102dc6f/clang/lib/Sema/SemaDeclCXX.cpp#L17467), but that call resolves quickly as does the call to `VerifyIntegerConstantExpression()`. In both cases, this is because `WasEvaluated` is true in [`VarDecl::evaluateValueImpl()`](https://github.com/llvm/llvm-project/blob/e3f74d4589e29279e9f543b58577a2ece102dc6f/clang/lib/AST/Decl.cpp#L2566) so we did not need to re-evaluate the initializer for `ret`. In the `-DONE` compilation, we don't have a variable initializer to store the computed value on.

I think there are two things worth investigating.

1) Can we skip constexpr processing of function bodies? Otherwise, the *presence* of a constexpr function impacts compile time even if the function is never called within the TU. Considering things like the STL, this seems like a major performance concern.

2) Can the value computed within `Sema::ActOnFinishFullExpr()` be stored on the resulting expression so that the subsequent call to `VerifyIntegerConstantExpression()` can take a fast path instead of having to recompute the value?

**Comment by AaronBallman** [comment]
> Can the value computed within Sema::ActOnFinishFullExpr() be stored on the resulting expression so that the subsequent call to VerifyIntegerConstantExpression() can take a fast path instead of having to recompute the value?

This might not be trivial/possible in general because the full expression may need to be evaluated multiple times with different input values.

**Comment by tbaederr** [comment]
> 1. Can we skip constexpr processing of function bodies? Otherwise, the _presence_ of a constexpr function impacts compile time even if the function is never called within the TU. Considering things like the STL, this seems like a major performance concern.

We can't drop it unless we also drop the "constexpr function never produces a constant expression" diagnostic.

**Comment by pkeir** [comment]
> > 1. Can we skip constexpr processing of function bodies? Otherwise, the _presence_ of a constexpr function impacts compile time even if the function is never called within the TU. Considering things like the STL, this seems like a major performance concern.
> 
> We can't drop it unless we also drop the "constexpr function never produces a constant expression" diagnostic.

I notice that using `-Wno-invalid-constexpr` doesn't stop the function body processing overhead; but also suspect that this diagnostic should not be a default for C++23 and onwards (after C++ proposal [P2448](https://wg21.link/p2448); also see [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106649)). GCC also supports this switch, and has it enabled by default, but doesn't have the overhead.

**Comment by AaronBallman** [comment]
The diagnostic is a useful one despite C++23 relaxing the restriction; that's why it's an error that can be downgraded into a warning (in all language modes). So I'm not certain we want to change the default for C++23 or not. CC @Fznamznon @hubert-reinterpretcast for additional opinions

I ran an experiment and it seems there's no noticeable impact in practice when disabling the code to check constexpr function bodies: http://llvm-compile-time-tracker.com/index.php?config=Overview&stat=instructions%3Au&remote=AaronBallman
![Capture](https://github.com/llvm/llvm-project/assets/4587626/5bc3b8cc-b979-499a-8304-73a888ca4699)

However, on a pathological case like the one in this issue, it does have a measurable impact: with just the function body (no constexpr uses required), it takes 10s with the check to < 1s without the check.

At the very least, because we silence the diagnostic in system headers (https://godbolt.org/z/jPoY3sKEv), it makes no sense to do the work in system headers or if the diagnostic is otherwise disabled.
