### ISSUE TITLE
[GlobalISel] Cross-typed G_CONSTANT

### ISSUE THREAD

**Issue by e-kud** [llvm/llvm-project#93627]
Let's consider the following code
```cpp
int *foo() {
    return nullptr;
}
```
When we translate it regardless of target, we obtain cross-typed `G_CONSTANT`
```
bb.1.entry:
  %0:_(p0) = G_CONSTANT i64 0
  $rax = COPY %0:_(p0)
  RET 0, implicit $rax
```

It happens because there is no requirement to have the same typed operand and return value
```
// Only supports scalar result types
def G_CONSTANT : GenericInstruction {
  let OutOperandList = (outs type0:$dst);
  let InOperandList = (ins unknown:$imm);
  let hasSideEffects = false;
}
```

I think it looks weird because we have `G_INTTOPTR` and generally speaking any specific pointer should be casted from integer. However, we have these cross-typed constants.
```
test/CodeGen/AArch64/GlobalISel/select-dup.mir:    %cst:gpr(p0) = G_CONSTANT i64 3
...
test/CodeGen/AMDGPU/GlobalISel/artifact-combiner-trunc.mir:    %1:_(p0) = G_CONSTANT i64 1
...
test/CodeGen/RISCV/GlobalISel/instruction-select/icmp-rv64.mir:    %1:gprb(p0) = G_CONSTANT i64 -10
test/CodeGen/RISCV/GlobalISel/instruction-select/icmp-rv64.mir:    %1:gprb(p0) = G_CONSTANT i64 10
```

My questions here:
1) Is it by design to have cross typed constants? I think pointer is just a particular case. When we have a separate type for floats, it is easy to imagine `%1:_(f64) = G_CONSTANT i64 1`. `MachineVerifier` checks only bit width.
2) Do we want to shift to a combination of `G_CONSTANT + G_INTTOPTR` and probably fix `G_CONSTANT` definition to match operand and return types.
3) Alternatively, there may be a special case for nulls. E.g. it's ok to have `%0:_(p0) = G_CONSTANT i64 0` but non null pointers should be introduced through  `G_CONSTANT + G_INTTOPTR`

/cc @aemerson @arsenm @qcolombet @tschuett @topperc @MalaySanghi

**Comment by arsenm** [comment]
> Is it by design to have cross typed constants? I think pointer is just a particular case

Yes, but I would not all this a "cross typed constant". There is only one type, the LLT. The encoding of the constant as an APInt isn't important, and what else would you use?  It's just a vehicle for the bits, the inner type doesn't matter. 

> Do we want to shift to a combination of G_CONSTANT + G_INTTOPTR and probably fix G_CONSTANT definition to match operand and return types.

No. This is what IRTranslator did originally long ago (I can't seem to find the commit where this changed). It also inconsistently would use imm and cimm arguments. This made it more difficult to match actual pointer constants, since now there's an obscuring instruction that patterns need to look through. Plus there's additional cost to emitting 2x the instructions, and now any combine needs to also look through the cast. Why do you think this is an issue? What problem are you seeing? I don't see any plus to re-splitting these out.

> When we have a separate type for floats, it is easy to imagine %1:_(f64) = G_CONSTANT i64 1

I agree G_FCONSTANT is bad and it would be better if we didn't have it. Was always the same in SelectionDAG, and multiplies the amount of code required to handle constants 


> Alternatively, there may be a special case for nulls

Why special case?

**Comment by e-kud** [comment]
> Yes, but I would not all this a "cross typed constant". There is only one type, the LLT. The encoding of the constant as an APInt isn't important, and what else would you use? It's just a vehicle for the bits, the inner type doesn't matter.

Oh, I got it. I haven't thought about it as a bit representation and `i64` specifies the width. I thought about it as a 64 bit integer value.

> No. This is what IRTranslator did originally long ago 

Thanks, that I wanted to know!

> Plus there's additional cost to emitting 2x the instructions

Currently we may have the situation as follows. So it's not always 2x emitting.

```
%0:_(s64) = G_CONSTANT i64 0
%1:_(p0) = G_CONSTANT i64 0
```

> now any combine needs to also look through the cast

Yes, completely agree. When I've tried to split it into two instructions I had to add peeks to combiners.

> Why do you think this is an issue? What problem are you seeing?

As I've said, I've interpreted `G_CONSTANT i64` as an integer value and I find it weird to have `G_INTTOPTR` and `G_CONSTANT` that may "cast" an integer value to pointer. Apparently I should think differently about `G_CONSTANT`.

> Why special case?

In the light of the new information it doesn't make sense anymore.

@arsenm thank you for the explanation!
