### ISSUE TITLE
[clang] Concept can access a private type in a dependent template

### ISSUE THREAD

**Issue by sigasigasiga** [llvm/llvm-project#93788]
This code compiles just fine although it shouldn't
```cpp
#include <concepts>

template<typename T>
class trait
{
    using type = int; // note that the type is private
};

template<typename T>
concept has_field = requires(T t) {
    { t.field } -> std::convertible_to<typename trait<T>::type>;
};

struct foo
{
    int field;
};

static_assert(has_field<foo>);
```

https://godbolt.org/z/WKzo7E7cK

**Comment by shafik** [comment]
CC @erichkeane

**Comment by Backl1ght** [comment]
After some debugging I find out the root cause is that there is a SFINAE error not processed during `TransformTemplateParameterList` here

https://github.com/llvm/llvm-project/blob/5021e6dd548323e1169be3d466d440009e6d1f8e/clang/lib/Sema/SemaTemplateInstantiate.cpp#L2737-L2747

I will submit a fix later.
