### ISSUE TITLE
Clang rejects standard attributes on tags

### ISSUE THREAD

**Issue by vgvassilev** [llvm/llvm-project#93982]
Clang errors out on:
```cpp
[[gnu::always_inline]] inline int f(); 
[[gsl::Pointer(int)]] struct S{};

```
with:
```
error: misplaced attributes; expected attributes here
    3 | [[gsl::Pointer(int)]] struct S{};
      | ~~~~~~~~~~~~~~~~~~~~~       ^
      |                             [[gsl::Pointer(int)]]
1 error generated.
```

where gcc happily accepts it.

I think we should support that case to improve consistency across different C++ entities which support attributes at that position.

**Comment by AaronBallman** [comment]
Clang is correct to reject that code; the grammar does not allow for such a thing. Also, GCC doesn't seem to actually accept it: https://godbolt.org/z/3cfnf8GxE (see the note where it says where the attribute needs to go).

**Comment by vgvassilev** [comment]
Ah, ok, sorry for the noise. That's very annoying inconsistency between tags and function declarations. Do you know if there is some rationale?

**Comment by AaronBallman** [comment]
The general rule is: if you can declare multiple things at the same "level" in one statement, you can use a leading attribute so that it applies to everything being declared. e.g.,
```
[[foo]] int x, y, g();
```
would apply `foo` to all three declarations despite `g()` being a function declaration.

You can only declare one structure in the same declaration. However, you can declare multiple variables along with the structure declaration, and a leading attribute would be *confusing* in that case. e.g.,
```
[[foo]] struct S {}; // Not allowed
[[foo]] struct T {} a, b, c; // Applies foo to a, b, and c
```
If it was allowed to be leading, you run into weird cases where refactoring the code from the first line to be the second line would change appertainment from the structure to the variables being declared.

**Comment by vgvassilev** [comment]
Oh, ok. Makes sense now! Thank you!
