### ISSUE TITLE
Clang should emit pedantic warnings for conversions to/from pointers to qualified arrays

### ISSUE THREAD

**Issue by rjmccall** [llvm/llvm-project#9454]
|  |  |
| --- | --- |
| Bugzilla Link | [9082](https://llvm.org/bz9082) |
| Version | trunk |
| OS | All |
| CC | @ostash,@zygoloid |

## Extended Description 
According to the C standard, conversions like the following are technically casting away const-ness, because array types are never qualified:  qualifiers apply only to the element type.
  const void *    -> const int (*)[5]
  const int *       -> const int (*)[5]

Similarly, this is not supposed to be a valid qualification conversion:
  int (*)[10]    ->  const int (*)[10]

These are kindof arbitrary restrictions that do make life unnecessarily difficult for real users;  I think clang's model (where the array and element are simultaneously qualified) really makes a lot more sense.  Nonetheless, we should at the very least provide -pedantic warnings about these conversions not being permitted by the standard(s).

**Comment by Endilll** [comment]
Clang 16 and GCC 13 don't warn about any of those conversions:
https://godbolt.org/z/YaEcne8aP

**Comment by AaronBallman** [comment]
Current wording as of C2x is 6.7.3p10: If the specification of an array type includes any type qualifiers, both the array and the element type are so-qualified. ...

This differs from C17 where the array is not qualified but the element is. The changes came in from https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2607.pdf.

I think it's reasonable to treat this paper as effectively being a DR instead of a new behavior in C2x. WDYT?

**Comment by Endilll** [comment]
Yeah, I don't think it's worth our scarce resources.

**Comment by rjmccall** [comment]
I agree with both Aaron's analysis and his conclusions.

**Comment by AaronBallman** [comment]
> I agree with both Aaron's analysis and his conclusions.

Thanks! I added it to the list of backported features in https://github.com/llvm/llvm-project/commit/09841d792f47310cf582156b92ffd9fa232853d6 so it's better documented that we did this on purpose.
