### ISSUE TITLE
Improve error message for invalid lambda captures

### ISSUE THREAD

**Issue by ilya-biryukov** [llvm/llvm-project#94764]
For the following code (https://gcc.godbolt.org/z/GGoWq45hs) Clang produces an error message that some people find confusing:
```cpp
struct X {
    int x;
    void foo() {
        [x](){};
    }
};
// <source>:4:10: error: 'x' in capture list does not name a variable
```

It seems that the error message could indeed be improved, a few ideas that come to mind:
- mentioning what kind of symbol we are actually referring to: `'class member 'x' cannot appear in capture list as it is not a variable'`
- we could suggest fixes in some situations `did you mean to capture 'this'?` or `did you mean to use a capture with initializer?`
- `variable` is technically correct and what Clang is using, but maybe it would be better to say`local variable or parameter`? I might be missing some cases, but it sounds more user-friendly than the [similar error](https://gcc.godbolt.org/z/q7aen8azc) about "automatic storage duration` that we have today: 
```
<source>:4:10: error: 'x' cannot be captured because it does not have automatic storage duration
```

**Comment by Sirraide** [comment]
> mentioning what kind of symbol we are actually referring to: 'class member 'x' cannot appear in capture list as it is not a variable'

I like this option the most personally. It makes it pretty clear what the problem is.

A fix-it might require some more thinking (e.g. don’t suggest adding `this` if it’s already there etc.), and I’m not sure how helpful it’d be. My suggestion would be to just add a new diagnostic for this case because that would already make this situation a lot less confusing.

At a glance, it looks like adding an `else if` branch for `FieldDecl` here might do the trick:
https://github.com/llvm/llvm-project/blob/bd6e324b67cdadde2593327753e99782146d9bf8/clang/lib/Sema/SemaLambda.cpp#L1247-L1250

**Comment by CedricSwa** [comment]
I would like to work on this for the weekend.

**Comment by Sirraide** [comment]
Feel free to @ me as a reviewer when you open a pr
