### ISSUE TITLE
[DebugInfo][clang] No DW_TAG_call_site-s when using -O0

### ISSUE THREAD

**Issue by spevnev** [llvm/llvm-project#95785]
When compiling using `clang -O0 -g3` DWARF does not contain any `DW_TAG_call_site` DIEs, whereas compiling with any other optimization level (-O1, -O2, -O3, -Os) produces correct DIEs.

**Comment by OCHyams** [comment]
I believe this is by design - the thinking probably being that it's not useful at O0 for the use cases imagined when implementing the feature. FYI code is [here CompilerInvocation.cpp#L1811](https://github.com/llvm/llvm-project/blob/c659e3a3f8ab797e65ca72a969b74cd06b1dfbd2/clang/lib/Frontend/CompilerInvocation.cpp#L1811). @dwblaikie and @pogo59 might have opinions on what any new/changed flags to alter this behaviour might look like.

**Comment by spevnev** [comment]
I am curious to know the reasoning behind not generating call site DIEs at -O0.

**Comment by OCHyams** [comment]
I don't have the full history, but I believe that the original motivator (or if not motivator than primary use-case) for implementing call site info was to provide it as a mechanism for consumers to evaluate DW_OP_entry_value expressions, and entry value expressions only get generated with optimisations enabled. Given it was assumed the call site info wouldn't be useful with optimisations, it was likely disabled at O0 to reduce debug info size.

Here's the review for the commit that made the change https://reviews.llvm.org/D75175.

**Comment by dwblaikie** [comment]
The issue with variadic calls is that from within the callee there's no generic way to determine the parameters and their types - probably a good solution would be for a debugger/DWARF consumer to have something like a pretty printer that can look at the variadic parameters and determine the amount/size (eg: for printf, by parsing the first argument pattern, it could produce a list of types for the other parameters)

**Comment by spevnev** [comment]
Although you cannot get parameter information from within the callee, you can do it before "calling" variadic function by using call site parameters.

For example `printf`. Subprogram only specifies unspecified_parameters, whereas actual call_site has variadic parameter:
```
DW_TAG_subprogram [42] * (0x0000000c)
                DW_AT_external [DW_FORM_flag_present]   (true)
                DW_AT_name [DW_FORM_strp]       ( .debug_str[0x0000d6d1] = "printf")
                DW_AT_decl_file [DW_FORM_data1] ("/usr/include/stdio.h")
                DW_AT_decl_line [DW_FORM_data2] (356)
                DW_AT_decl_column [DW_FORM_data1]       (12)
                DW_AT_prototyped [DW_FORM_flag_present] (true)
                DW_AT_type [DW_FORM_ref4]       (cu + 0x0094 => {0x00000094} "int")
                DW_AT_declaration [DW_FORM_flag_present]        (true)
                DW_AT_sibling [DW_FORM_ref4]    (cu + 0x1289 => {0x00001289})

0x00001282:     DW_TAG_formal_parameter [14]   (0x00001271)
                  DW_AT_type [DW_FORM_ref4]     (cu + 0x0c3d => {0x00000c3d} "const char *")

0x00001287:     DW_TAG_unspecified_parameters [45]   (0x00001271)

...

0x00001ce6:     DW_TAG_call_site [2] * (0x00001684)
                  DW_AT_call_return_pc [DW_FORM_addr]   (0x000000000040ecd6)
                  DW_AT_call_origin [DW_FORM_ref4]      (cu + 0x1271 => {0x00001271} "printf")
                  DW_AT_sibling [DW_FORM_ref4]  (cu + 0x1d12 => {0x00001d12})

0x00001cf7:       DW_TAG_call_site_parameter [1]   (0x00001ce6)
                    DW_AT_location [DW_FORM_exprloc]    (DW_OP_reg5 RDI)
                    DW_AT_call_value [DW_FORM_exprloc]  (DW_OP_addr 0x410c46)

0x00001d04:       DW_TAG_call_site_parameter [1]   (0x00001ce6)
                    DW_AT_location [DW_FORM_exprloc]    (DW_OP_reg4 RSI)
                    DW_AT_call_value [DW_FORM_exprloc]  (DW_OP_addr 0x41b340)
```

**Comment by dwblaikie** [comment]
Yes, sorry, I understand that/sorry I didn't express it more clearly  -that's what I meant by "The issue with variadic calls [that you are trying to address with call site parameters] is that from within the callee there's no generic way to determine the parameters and their types [without call site parameters]". (though your example does point out a problem with this - that the call site parameters still don't carry type information, so might be of limited value by themselves in terms of rendering something useful to the user)

Still kind of leaning towards this not being the right tool for the job (they don't carry type information and they don't match 1:1 with the function's formal parameters (which is a current source of confusion/discussion about how call site parameters are supposed to work)) - and some kind of pretty printer for varargs might be the better direction.

**Comment by spevnev** [comment]
> some kind of pretty printer for varargs might be the better direction.

I think I am missing something. How do you suggest implementing "pretty printer"? It is not like all variadic functions follow printf-like format.

> they don't match 1:1 with the function's formal parameters

Do you mean unspecified parameters? Because otherwise they should (according to the standard).

**Comment by dwblaikie** [comment]
> > some kind of pretty printer for varargs might be the better direction.
> 
> I think I am missing something. How do you suggest implementing "pretty printer"? It is not like all variadic functions follow printf-like format.

Sorry, what I mean by "pretty printer" is that the DWARF consumer (debugger, etc) would need a new extension point (a new feature added to the consumer) that works in a similar manner to pretty printers (debuggers tend to have extension points called pretty printers (or similar names) for printing out variables of certain types (eg: that help print a std::string as its string buffer, rather than as three pointers (begin/end/capacity), etc)).

So, yes, different with different rules about how they determine how many (& what type) of arguments they've been passed would have different "variadic pretty printers" (for want of a better term) that would tell the debugger, for this function, how to synthesize the parameter variables.

> > they don't match 1:1 with the function's formal parameters
> 
> Do you mean unspecified parameters? Because otherwise they should (according to the standard).

I  mean the unspecified parameters - but honestly even the constraint that they should otherwise match seems questionable to me, since the call site parameters are lower level (they do things like encode a single register - well, at least that's how LLVM's emitting them - GCC skips some things entirely instead).

eg: https://godbolt.org/z/MnWGv69oh

GCC produces a call_site_parameter only for the first parameter (a single int)
Clang produces 3 call_site_parameters, one for each register (so, two separate entries for the second argument that is a struct containing two integers)

**Comment by spevnev** [comment]
I do agree that using call site parameters for variadic arguments is more of a workaround/hack than a solution.
There are lots of quirks and issues, besides the ones you have mentioned:

- this very issue making it unusable unless optimizations are turned on
- [this issue](https://github.com/llvm/llvm-project/issues/95645) further breaking 1:1 call_site to formal parameter matching, making it necessary to rely on registers, via which they are passed, to map them
- [this issue](https://github.com/llvm/llvm-project/issues/94986) limiting this workaround to at most 6 arguments (on x86_64) (which should be mostly enough but will be unexpected to user/consumer).

However, I believe there are no alternatives available, which probably means that it will only be resolved if the DWARF v6 contains the necessary changes to somehow handle variadic arguments.

The only thing I do not really understand is why people care so much about saving space (e.g. by omitting parameter at O0) when producing a **debug** build, especially considering that the saved space is at most a few kilobytes.

**Comment by dwblaikie** [comment]
> However, I believe there are no alternatives available, which probably means that it will only be resolved if the DWARF v6 contains the necessary changes to somehow handle variadic arguments.

The solution/path I'm suggesting isn't a DWARF one - but one that any DWARF consumer could implement on their own without the need for new DWARF features. (would then be backwards compatible, compatible in cases where call site info isn't emitted, etc - but would be on a per-consumer basis (though any solution will probably need some work in every consumer anyway))

> The only thing I do not really understand is why people care so much about saving space (e.g. by omitting parameter at O0) when producing a debug build, especially considering that the saved space is at most a few kilobytes.

We do generally care about not producing more than is needed, because it all adds up. But I haven't done any particular measurements on the cost of call site info (& the cost if it were made more comprehensive - covering all arguments rather than only the register arguments). It also only applies when the arguments are constant, or are preserved by the caller for some reason - so it wouldn't work for all varargs functions even if the call site info was more comprehensive... 

Overall I think using call sites to handle varargs functions just isn't the right path.

**Comment by spevnev** [comment]
> Overall I think using call sites to handle varargs functions just isn't the right path.
Seems like that.
