### ISSUE TITLE
[libc][math] implement `signbit`

### ISSUE THREAD

**Issue by nickdesaulniers** [llvm/llvm-project#96322]
https://android-review.googlesource.com/c/platform/bionic/+/3141224/1/libc/include/math.h demonstrates that `__builtin_signbit` can be used to implement this macro (or a few fallbacks in case this builtin isn't available).  We should use godbolt.org to figure out what compilers and compiler versions support this macro.

I would put these in libc/include/llvm-libc-macros/math-macros.h (there's a comment at the bottom to start a new header for these).

It seems that we don't have tests for `isfinite`, `isinf`, or `isnan` macros from our math.h, which is problematic.  We should start a new "include" test under libc/test/include (similar to stdbit_test.cpp).

cc @lntue

**Comment by nickdesaulniers** [comment]
https://android-review.googlesource.com/c/platform/bionic/+/3141226/1/tests/math_test.cpp also has a list of other type generic macros we should provide+test.

> fpclassify, signbit,
> isfinite, isinf, isnan, isnormal, isgreater, isgreaterequal, isless,
> islessequal, islessgreater, and isunordered.

**Comment by TejasvOnly** [comment]
I'd like to work on this.

**Comment by ChristianWolff1** [comment]
Hello, I want to work in this issue... Is someone working in this issue now? ._.

**Comment by lntue** [comment]
@TejasvOnly and @ChristianWolff1 : Sorry I completely missed the notifications from this issue.  Are you still interested in implementing the remaining math function macros?  If so please create a github issue for the one that you are going to implement+test, and tag/cc me to the issue.  Please let me know if you are interested in other type of functions in libc also.
Since @akielaries already sent out a PR for `signbit`, I will assign this issue to @akielaries.

Thanks,
