### ISSUE TITLE
[FileCheck] Match is not found in a line

### ISSUE THREAD

**Issue by futog** [llvm/llvm-project#96904]
Given the following match-file:
check.txt:
`// CHECK1: else`
`// CHECK2: something`

the match `CHECK2` is not found in the following case:
`echo "something else" | FileCheck check.txt -check-prefixes=CHECK1,CHECK2`

The output:
check.txt:2:12: error: CHECK2: expected string not found in input
// CHECK2: something
           ^
<stdin>:1:15: note: scanning from here
something else
              ^

Input file: <stdin>
Check file: check.txt

-dump-input=help explains the following input dump.

Input was:
<<<<<<
         1: something else 
check:2                   X error: no match found
>>>>>>

If I switch the two lines in check.txt, it is working

**Comment by Sirraide** [comment]
I’m pretty sure that is intentional. A CHECK directive generally ‘consumes’ the line, meaning the next directive will try to match the next line in the input—at least that is how it works if you use the same check prefix. I would assume that the behaviour is the same if you use multiple prefixes. If you want to match the same line again, you probably have to use [CHECK-SAME](https://llvm.org/docs/CommandGuide/FileCheck.html#the-check-same-directive) here.
