### ISSUE TITLE
LLVM's `MCParser` does not understand `.cfi_label` directives

### ISSUE THREAD

**Issue by alexrp** [llvm/llvm-project#97222]
```console
❯ cat test.s
.globl foo
.align 2
.type foo,@function
.cfi_startproc
.cfi_label .Ldummy
.cfi_endproc
❯ riscv64-linux-gnu-gcc test.s -c
❯ /opt/llvm/bin/clang -target riscv64 test.s -c
test.s:5:1: error: unknown directive
.cfi_label .Ldummy
^
❯ /opt/llvm/bin/clang --version
clang version 18.1.6 (https://github.com/llvm/llvm-project 1118c2e05e67a36ed8ca250524525cdb66a55256)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/llvm/bin
```

This is currently a blocker for compiling glibc with Clang for ARC, C-SKY, LoongArch, and RISC-V, as these all make use of `.cfi_label` in their `start.S` ([example](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/riscv/start.S;h=ede186ef23b35b5af7c1c4ddf04b12519ed26e42;hb=HEAD#l48)).

**Comment by MaskRay** [comment]
Created #97922 to support `.cfi_label`

In glibc, https://sourceware.org/PR23125 sysdeps/riscv/start.S utilizes .cfi_label to force
DW_CFA_undefined to be placed in a FDE. arc/csky/loongarch ports have
copied this use.

```
.cfi_startproc
// DW_CFA_undefined is allowed for CIE's initial instructions.
// Without .cfi_label, gas would place DW_CFA_undefined in a CIE.
.cfi_label .Ldummy
.cfi_undefined ra
.cfi_endproc
```

Technically, `.cfi_label .Ldummy` isn't really necessary. It moves the instruction from CIE to FDE and potentially decrease the number of CIEs, usually without making the FDE larger (since the FDE has to be padded).

> ARC, C-SKY, LoongArch, and RISC-V, as these all make use of .cfi_label in their start.S ([example]

I believe ARC, C-SKY, LoongArch just copy RISC-V without understanding the rationale :)
