### ISSUE TITLE
How to compile projects with static library of Arrow

### ISSUE THREAD

**Issue by Ognimalf** [llvm/llvm-project#98473]
I'm trying to build a project which need to use apache arrow, and I'm trying to incorporate it as a static library. But the project has linked with libc++.a, which will cause a linker error:

```
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libarrow.a(utf8.cc.o): undefined reference to symbol '_ZNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEE10_M_disposeEv@@GLIBCXX_3.4.21'
```

It seems like the static lib is built with glibcxx, which contains some symbols that are not present in libc++.a. I wonder if there are some solutions to make it work.

Thanks.

**Comment by ldionne** [comment]
You must build all of the components in your stack with the same standard library. libc++ and libstdc++ are entirely different code bases, they provide different symbols with different ABIs, etc. The only thing they have in common is their API, which is specified by the C++ Standard. Unfortunately, there is no solution but to use a consistent standard library across your whole stack.

Closing since there is unfortunately nothing we can do to help.

**Comment by Ognimalf** [comment]
> You must build all of the components in your stack with the same standard library. libc++ and libstdc++ are entirely different code bases, they provide different symbols with different ABIs, etc. The only thing they have in common is their API, which is specified by the C++ Standard. Unfortunately, there is no solution but to use a consistent standard library across your whole stack.
> 
> Closing since there is unfortunately nothing we can do to help.

Got it. Thanks for reply!

**Comment by ldionne** [comment]
Note that if you build your own dynamic library, you can use the standard library of your choice *within* that dynamic library. However, you must make sure that your whole dynamic library is compiled with the same stdlib, and you must not pass any stdlib types across your dynamic library boundary.

Basically, the stdlib becomes an implementation detail of the dynamic library and it must not leak outside of it. But it doesn't look like that's the setup you're in.
