### ISSUE TITLE
Backport cb4f94db83d9c4373b485493ef079e318f63bf13 to release/18.x

### ISSUE THREAD

**Issue by willcohen** [llvm/llvm-project#98678]
This allows emscripten to continue to build with LLVM 18.

**Comment by nikic** [comment]
LLVM 18 no longer accepts backports, let alone for new features.

For reference, the commit from the title is cb4f94db83d9c4373b485493ef079e318f63bf13.

**Comment by sbc100** [comment]
Seems like a reasonable thing to backport, but can I ask what your usecase is here.  The official stance on the emscripten side is that we don't support stable LLVM releases.  Obviously if you can make it work than thats great, but I'm curious what the rationale is?

**Comment by willcohen** [comment]
@nikic Apologies for misunderstanding the release schedule and for the noise, all.
@sbc100 The reasoning was just to try to continue to try to build emscripten from a stable release, even though it's not formally supported by emscripten's stance. I'll just work on backporting it to LLVM 18 for nix internally pending the 19 release: https://github.com/NixOS/nixpkgs/pull/326633.

**Comment by RossComputerGuy** [comment]
I'm one of the maintainers for LLVM in Nix, backporting would be great if the LLVM team is willing to accept it since my stance is to upstream patches the most we can. I don't speak for the rest of the LLVM team in Nix but that's just my stance. I might not convince everyone with this stance but I would definitely appreciate it if we could get this backported. Though I do understand if it is fully decided that the PR would not be backported.

**Comment by sbc100** [comment]
@RossComputerGuy emscripten is not designed to be used with the shared/common installation of LLVM.  Instead its designed to be used with its own specific bundled/pinned version.   i.e. when you install emscripten on a given machine you can expect to install its own insternal/bundled version of clang/llvm.    I know this goes against the philosophy of many linux distros, but it might be worth making an exception.  

Its sounds be me like no more patches are being backported to 18.. regardless of how suitable they might be.

**Comment by RossComputerGuy** [comment]
> emscripten is not designed to be used with the shared/common installation of LLVM. Instead its designed to be used with its own specific bundled/pinned version. i.e. when you install emscripten on a given machine you can expect to install its own insternal/bundled version of clang/llvm.

Understood, I don't understand how emscripten works in Nix since I don't maintain it. If emscripten uses a prebuilt version of LLVM then we have to use LLVM from the nix store due to the fact the binary would not work. If it's just the source for LLVM that is vendored with emscripten then I can see it totally being reasonable for us to not have to rely on the main LLVM build.

**Comment by willcohen** [comment]
@RossComputerGuy I'll continue this convo in the nix PR! See https://github.com/emscripten-core/emscripten/issues/11362 for context.
