### ISSUE TITLE
clang-18.1 bug in Arch linux

### ISSUE THREAD

**Issue by MetalInMyVeins** [llvm/llvm-project#98732]
I'm using the latest version of clang (18.1) in arch linux (x86_64). Everything worked properly for a few days and suddenly today, `clang -v` prompts me to submit a bug report. This is the full output.
```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: clang -v
#0 0x00007c8ea41c4d90 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/lib/libLLVM.so.18.1+0x7c4d90)
#1 0x00007c8ea41c1d4d (/usr/lib/libLLVM.so.18.1+0x7c1d4d)
#2 0x00007c8ea3450ae0 (/usr/lib/libc.so.6+0x3cae0)
#3 0x00007c8ea837b113 LLVMInitializeWebAssemblyTargetInfo (/usr/lib/libLLVM.so.18.1+0x497b113)
#4 0x00005b93c3147aed clang_main(int, char**, llvm::ToolContext const&) (/usr/bin/clang-18+0x17aed)
#5 0x00005b93c313afb5 main (/usr/bin/clang-18+0xafb5)
#6 0x00007c8ea3439c88 (/usr/lib/libc.so.6+0x25c88)
#7 0x00007c8ea3439d4c __libc_start_main (/usr/lib/libc.so.6+0x25d4c)
#8 0x00005b93c313b015 _start (/usr/bin/clang-18+0xb015)
fish: Job 1, 'clang -v' terminated by signal SIGSEGV (Address boundary error)
```
Updating the system doesn't solve the problem.

**Comment by chestnykh** [comment]
Have ArchLinux too, my clang reports correct version:
$ clang -v
clang version 18.1.8
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/14.1.1
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
`

Seems that in your case the root cause of the problem is in environment

**Comment by MetalInMyVeins** [comment]
@chestnykh How can I approach to solve the issue? I tried a few ways and ran out of ideas.
