### ISSUE TITLE
Regression in "cstdlib" file

### ISSUE THREAD

**Issue by mouse07410** [llvm/llvm-project#98906]
I think this patch is explanatory:

```diff
diff -uw /opt/local/libexec/gcc14/libc++/include/c++/v1/cstdlib.orig /opt/local/libexec/gcc14/libc++/include/c++/v1/cstdlib
--- /opt/local/libexec/gcc14/libc++/include/c++/v1/cstdlib.orig	2024-07-09 13:43:11
+++ /opt/local/libexec/gcc14/libc++/include/c++/v1/cstdlib	2024-07-10 09:41:58
@@ -142,7 +142,7 @@
 using ::mbstowcs _LIBCPP_USING_IF_EXISTS;
 using ::wcstombs _LIBCPP_USING_IF_EXISTS;
 #endif
-#if !defined(_LIBCPP_CXX03_LANG)
+#if !defined(_LIBCPP_CXX03_LANG) && defined(_LIBCPP_HAS_QUICK_EXIT)
 using ::at_quick_exit _LIBCPP_USING_IF_EXISTS;
 using ::quick_exit _LIBCPP_USING_IF_EXISTS;
 #endif
```

Basically,  check for `_LIBCPP_HAS_QUICK_EXIT` was lost, and that broke GCC `-stdlib=libc++`.

**Comment by philnik777** [comment]
This macro has been removed years ago, since all somewhat modern platforms support `quick_exit` and we don't support partial implementations of the libc on gcc. What libc are you trying to use?

**Comment by ldionne** [comment]
Can you try with the SDK shipped in Xcode 16 beta 3? I see that `quick_exit` is provided by `stdlib.h` in that version.

Also, make sure you use the right version of GCC based on the version of libc++ you're using. If you're using LLVM 18, our documented and tested GCC was GCC 13, so things should work if you use GCC 13 but not other versions.

For tip-of-trunk, we now support GCC 14 (and only that), so that's the only version that will work reliably.

**Comment by ldionne** [comment]
> And no, it did not work with GCC 13 and LLVM 18 without the patch I'm asking to merge (restore). (Nor did it work with GCC 14 and LLVM 18.)

Right. I am 90% certain it would work with GCC 13 / LLVM 18 and the Xcode 16 SDK -- that's why I am suggesting this.

As a general statement, I'll say that libc++ with GCC only works on platforms with a fully conforming C Standard Library because supporting not-fully-complete C libraries requires the `using_if_exists` attribute, which GCC doesn't implement. We're happy to support these platforms on Clang, though.

By the way, this is not a philosophical opinion -- it exists due to practical concerns. Indeed, while the patch you posted above may seem small (by the way it doesn't actually work because you never define `_LIBCPP_HAS_QUICK_EXIT`), in reality many platforms are subtly non-conforming, so we'd have to maintain a large number of these `_LIBCPP_HAS_FOO` macros. All of these enablement macros also depend on system versions, which is something that we must keep evolving to avoid code rot. Long story short, we don't want to get into that business and the `using_if_exists` attribute is a nice and simple solution to that, so we rely on it and plan to keep doing so. Even though it means that GCC unfortunately doesn't get first class citizen support on all platforms.

I'll close this since we don't plan on reintroducing the macro for the reasons stated above.

**Comment by philnik777** [comment]
> > the patch you posted above may seem small (by the way it doesn't actually work because you never define `_LIBCPP_HAS_QUICK_EXIT`),
> 
> I don't know why you say "it doesn't **actually** work", because it **definitely** works and resolves the compilation problem on my Macs (MacOS Sonoma, Xcode-15.4).
> 
> Are you trying to say that the new platforms **stopped** defining those `_LIBCPP_HAS_FOO`?!

Platforms have never defined these macros. They were maintained by libc++.

**Comment by philnik777** [comment]
> > Platforms have never defined these macros. They were maintained by libc++.
> 
> OK, thanks - I stand corrected. But my question stands: does `libc++` still define these macros, or did it stop...?

No, we don't define these macros anymore.

**Comment by philnik777** [comment]
> > I am 90% certain it would work with GCC 13 / LLVM 18 and the Xcode 16 SDK
> 
> Could you please help me understand the relationship between LLVM (say, LLVM-18) and Xcode - I am assuming that LLVM uses its **own** libc++ header files, and only links to Xcode libraries as needed?
> 
> If that's the case - then how could upgrade of _Xcode_ from, e.g., 15 to 16, help with LLVM libc++ header files? I'm not arguing - just trying to understand (so I could intelligently discuss this issue in the Macports ticket).

The libc++ headers include some of the SDK headers. When updating XCode you get new headers, which should (apparently) now include declarations for `quick_exit` and friends.
