### ISSUE TITLE
type trait builtins __remove_cv[ref] are used unconditionally

### ISSUE THREAD

**Issue by AndreyG** [llvm/llvm-project#99464]
After the commit 55357160d0e151c32f86e1d6683b4bddbb706aa1 by @philnik777 the usages of builtin type traits `__remove_cv`/`__remove_cvref` are not guarded by `#if __has_builtin(__remove_cv[ref])`:
https://github.com/llvm/llvm-project/blob/da0c8b275564f814a53a5c19497669ae2d99538d/libcxx/include/__type_traits/remove_cv.h#L22
https://github.com/llvm/llvm-project/blob/da0c8b275564f814a53a5c19497669ae2d99538d/libcxx/include/__type_traits/remove_cvref.h#L42
Note that even the remaining comment is wrong now `#endif // __has_builtin(__remove_cv)`. https://github.com/llvm/llvm-project/blob/da0c8b275564f814a53a5c19497669ae2d99538d/libcxx/include/__type_traits/remove_cv.h#L31
Also note that all other type traits builtins are used only after the check, for instance `__add_pointer` here: https://github.com/llvm/llvm-project/blob/da0c8b275564f814a53a5c19497669ae2d99538d/libcxx/include/__type_traits/add_pointer.h#L23.

**Comment by philnik777** [comment]
What exactly is your point/question/bug report?

> Also note that all other type traits builtins are used only after the check

That's simply not true. Lots of type traits don't have guards. Only builtin traits which aren't supported by all supported compilers have guards.

**Comment by AndreyG** [comment]
> What exactly is your point/question/bug report?

I'd like to have usages of builtin type traits guarded. The motivation for this is the homegrown language engine which works pretty well with libc++ (and any C++ code in general) but doesn't support these type traits yet.

**Comment by philnik777** [comment]
I'm not sure what exactly you're referring to, but we can't support arbitrary C++ parsers. From our side the patch simply removed dead code. You can ask for official support for your tool, but without pre-commit testing that most likely won't happen.

**Comment by AndreyG** [comment]
Sorry, but I don't understand what's the problem with providing [the fallback](https://github.com/llvm/llvm-project/blob/0c89427b99f6f6d7c217c70f/libcxx/include/__type_traits/remove_cv.h#L31-L37) for parsers that don't support the builtin, how it was before the commit https://github.com/llvm/llvm-project/commit/55357160d0e151c32f86e1d6683b4bddbb706aa1. This is also how a lot of type traits are implemented right now: 
[add_lvalue_reference](https://github.com/llvm/llvm-project/blob/da0c8b275564f814a53a5c19497669ae2d99538d/libcxx/include/__type_traits/add_lvalue_reference.h#L21) 
[add_rvalue_reference](https://github.com/llvm/llvm-project/blob/da0c8b275564f814a53a5c19497669ae2d99538d/libcxx/include/__type_traits/add_rvalue_reference.h#L21)
[add_pointer](https://github.com/llvm/llvm-project/blob/da0c8b275564f814a53a5c19497669ae2d99538d/libcxx/include/__type_traits/add_pointer.h#L23)
[decay](https://github.com/llvm/llvm-project/blob/da0c8b275564f814a53a5c19497669ae2d99538d/libcxx/include/__type_traits/decay.h#L28)
[remove_all_extents](https://github.com/llvm/llvm-project/blob/da0c8b275564f814a53a5c19497669ae2d99538d/libcxx/include/__type_traits/remove_all_extents.h#L21)
[remove_const](https://github.com/llvm/llvm-project/blob/da0c8b275564f814a53a5c19497669ae2d99538d/libcxx/include/__type_traits/remove_const.h#L20)
[remove_extent](https://github.com/llvm/llvm-project/blob/da0c8b275564f814a53a5c19497669ae2d99538d/libcxx/include/__type_traits/remove_extent.h#L21)
[remove_pointer](https://github.com/llvm/llvm-project/blob/da0c8b275564f814a53a5c19497669ae2d99538d/libcxx/include/__type_traits/remove_pointer.h#L20)
[remove_reference](https://github.com/llvm/llvm-project/blob/da0c8b275564f814a53a5c19497669ae2d99538d/libcxx/include/__type_traits/remove_reference.h#L20)
[remove_volatile](https://github.com/llvm/llvm-project/blob/da0c8b275564f814a53a5c19497669ae2d99538d/libcxx/include/__type_traits/remove_volatile.h#L20)
After all, that's the whole point of having the ability to check `__has_builtin(...)`, right?

**Comment by philnik777** [comment]
There are also lots of traits which don't check the flag. We don't support any compilers where `__has_builtin(__remove_cv)` is false, so it's simply dead code. We don't need to check a condition which is always true. We can't keep every workaround forever, that's unmaintainable. The type traits you list all don't have corresponding builtins in GCC currently, so the `#else` implementation is checked and used with GCC.

**Comment by AndreyG** [comment]
> We don't support any compilers where __has_builtin(__remove_cv) is false

It contradicts the very first statement phrase from the [official documentation](https://libcxx.llvm.org/#platform-and-compiler-support): "Libc++ aims to support common compilers that implement the C++11 Standard."

**Comment by ldionne** [comment]
> > We don't support any compilers where __has_builtin(__remove_cv) is false
> 
> It contradicts the very first statement phrase from the [official documentation](https://libcxx.llvm.org/#platform-and-compiler-support): "Libc++ aims to support common compilers that implement the C++11 Standard."

Most importantly, we *do* in fact support common compilers, but we don't support arbitrary ones. We support GCC, Clang and most Clang-based compilers (AppleClang, IBM's compiler, etc). But no, we don't support arbitrary compilers or arbitrarily old versions of the above compilers because that would not be viable maintenance-wise. We also don't aim to support arbitrary homegrown language engines.

I don't mean this in a hostile way -- it would be great for your tool to work with libc++, however we unfortunately can't start taking into account these kinds of niche requests for support because that would never end. Libc++ is used extremely widely and you'd be surprised what kind of stuff people want to do with it, and what kind of requests we get. In order for the project to stay relevant, it has to stay focused, and that often means saying no.

**Comment by Smertig** [comment]
Hey there. For the context: I'm @AndreyG's colleague. 

> In order to strike a good balance between stability for users and maintenance cost, testing coverage and development velocity, libc++ **drops support for older compilers as newer ones are released**.

Thanks for pointing out; it makes total sense. I fully understand that supporting custom/old compilers doesn't fit in the libc++ development process (and there's no way to check compatibility with custom tools). 

However, may I ask you for the temporary exclusion here and providing fallback implementation for 3-6 more months until tooling is fully ready for those changes? Specifically, I'm talking about language support in CLion IDE / ReSharper C++ / Rider (three JetBrains products). 

We are ready with internal implementation, but delivering it to end users might take some time (you know, releasing processes). I'm asking because we already have reports from users who tried fresh libc++ in their projects (i.e. chromium) and got a lot of red code in their editor even with basic stuff:

![image](https://github.com/user-attachments/assets/52264822-509b-4d70-8e61-b667072a1588)

This was indeed our fault that we didn't provide implementation of those type traits in time, but that approach worked fine recently: usually, type traits were guarded, and we had some time to adapt. Now we realize that we should not rely on guards anymore and will support new builtin traits as fast as possible. 

I really hope that suggested changes won't affect the development process of libc++ too much. I'm ready to create corresponding PR, if needed.

Thanks!

**Comment by philnik777** [comment]
@Smertig If you want to revert IMO we should have some sort of test coverage for your tools. That could be as simple as running the parser over all headers and making sure it works. I realize that that's a request which won't be fulfilled in a few days, so I'd be happy with a promise that you'll work with us to set something up. That gives us visibility into any problems your parser has with our code, and you get very early reports when anything breaks.

**Comment by ldionne** [comment]
@philnik777 I would be fine with reverting that commit from `release/19.x` just to give folks more time as a one-off thing. The patch is small and if we only reverted it from `release/19.x`, it's as-if we didn't change anything from the maintenance point of view since we don't revert anything in `main`. WDYT?

**Comment by philnik777** [comment]
@ldionne sure, we can do that. I'd be against reverting on trunk though. Given that chromium was mentioned it seemed to me like reverting trunk was also requested.

**Comment by ldionne** [comment]
@nico Can you chime in?

FWIW I'd be against reverting on `main` as well, at least that's my first reaction.

**Comment by Smertig** [comment]
> If you want to revert IMO we should have some sort of test coverage for your tools

That's a good point. Unfortunately, I don't have a good solution that can be added to libc++'s CI right now, but I'll investigate possible options taking into account all the licensing factors. 

As a first step, we'll try to run our tooling over `main` libc++ branch daily (on our side) and support all the breaking changes ASAP. I believe, this way we would be able to avoid red code for released libc++ version (but not for trunk, unfortunately).

> I would be fine with reverting that commit from `release/19.x` just to give folks more time as a one-off thing. The patch is small and if we only reverted it from `release/19.x`, it's as-if we didn't change anything from the maintenance point of view since we don't revert anything in `main`.

It would be really nice, thank you! I also understand that reverting something from `main` doesn't sound like good idea (commit can be just lost), so I won't insist on doing that. However, this could potentially help a small number of our users who prefer trunk (i.e. chromium developers).
