### ISSUE TITLE
LWG2709: offsetof is unnecessarily imprecise

### ISSUE THREAD

**Issue by cjdb** [llvm/llvm-project#99965]
**Link:** https://wg21.link/lwg2709

If this is already implemented in Clang, then we can mark the status page as "Nothing to do".

**Comment by strega-nil** [comment]
I believe this is "Nothing to do";

```diff
-If type is not a standard-layout class
+Use of the offsetof macro with a type other than a standard-layout class
```

does not imply any need to change things, it's just a clarification of wording, and

```diff
-the results are undefined
+is conditionally-supported
```

changing from "results are undefined" to "is conditionally-supported" also doesn't affect us in any way, especially since we do support it (with a warning): <https://gcc.godbolt.org/z/d7e1f76qf>

**Comment by ldionne** [comment]
Since we're not actually providing `offsetof` ourselves and we're just using the one from the system C library, I agree there's nothing for us to do. If we were the ones implementing `offsetof`, I would have argued for documenting what we support and adding a test for it. But in the current state of things, it seems like we basically support whatever the C library decides to support.
